### ISSUE TITLE
Add support for alternate bindings for http transcoding

### ISSUE THREAD

**Issue by scotthart** [googleapis/google-cloud-cpp#10001]
For rpcs that specify a `google.api.http` option, it can contain more than one binding. 
In some cases this is a no-op:
```
    option (google.api.http) = {
      get: "/v1/{name=roles/*}"
      additional_bindings {
        get: "/v1/{name=organizations/*/roles/*}"
      }
      additional_bindings {
        get: "/v1/{name=projects/*/roles/*}"
      }
    };
```
as the emitted code always calls `request.name()` when formatting the url

But in another case, the emitted code needs to test the provided `request`:
```
    option (google.api.http) = {
      get: "/v1/roles"
      additional_bindings {
        get: "/v1/{parent=organizations/*}/roles"
      }
      additional_bindings {
        get: "/v1/{parent=projects/*}/roles"
      }
    };
```
here we need to conditionally insert the value of `request.parent()` into the url.

Eventually we may need to implement a full parser for these bindings as they can get quite complicated: https://github.com/googleapis/googleapis/blob/master/google/api/http.proto

**Comment by coryan** [comment]
No time to work on this. Closing for now.
