### ISSUE TITLE
Issuer switch API: `issuerswitch.googleapis.com`

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#10024]
The API is labeled as GA

**Comment by dbolduc** [comment]
The service does not yet exist.

I did the work to generate the library in this branch:
https://github.com/dbolduc/google-cloud-cpp/tree/feat-paymentgateway-generate-library

Googlers can see [the service docs](https://cloud.google.com/payment-gateway/) but opening this link in incognito mode will 404.

Requests to the service also 404, so I couldn't properly verify the quickstart.

**Comment by dbolduc** [comment]
We are not going to generate this. Googlers can see why at: https://b.corp.google.com/issues/237460617

**Comment by coryan** [comment]
Google is not creating client libraries for this service. Closing.
