### ISSUE TITLE
Downloading GCS cache stalls

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#10031]
Seems like we need to configure a timeout for these downloads.  It should complete in around 60 seconds when things are working well.  A timeout of 5x would not be unreasonable.

```
2022-10-11T14:13:39Z (+0s): Running:
env -C '/h' /workspace/ci/cloudbuild/cache.sh restore --bucket_url=gs://cloud-cpp-testing-resources_cloudbuild/build-cache/google-cloud-cpp --key=main/fedora-36-quickstart-production/h --fallback_key=main/fedora-36-quickstart-production/h
2022-10-11T14:13:39Z (+0s): ====> cache.sh: restore
gs://cloud-cpp-testing-resources_cloudbuild/build-cache/google-cloud-cpp/main/fedora-36-quickstart-production/h/cache.tar.gz:
    Creation time:          Tue, 11 Oct 2022 13:27:54 GMT
    Update time:            Tue, 11 Oct 2022 13:27:54 GMT
    Storage class:          STANDARD
    Content-Length:         4585769035
    Content-Type:           application/x-tar
    Component-Count:        32
    Hash (crc32c):          aYEg+g==
    ETag:                   CJDK4PKj2PoCEAE=
    Generation:             1665494874072336
    Metageneration:         1
2022-10-11T14:13:41Z (+2s): Fetching cache url gs://cloud-cpp-testing-resources_cloudbuild/build-cache/google-cloud-cpp/main/fedora-36-quickstart-production/h/cache.tar.gz
Copying gs://cloud-cpp-testing-resources_cloudbuild/build-cache/google-cloud-cpp/main/fedora-36-quickstart-production/h/cache.tar.gz to file:///tmp/tmp.S2dl2lyXhQ/cache.tar.gz
```

This failed before we created public logs:

https://pantheon.corp.google.com/cloud-build/builds;region=us-east1/a148579a-ec23-4055-89cd-0eed715a67eb;step=2?mods=logs_tg_prod&project=cloud-cpp-testing-resources

**Comment by dbolduc** [comment]
https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/10319/85926ad424b01ce5c82363a575e479fa6afa37ef/demo-fedora-demo-install/log-d7f6e486-1332-4bba-8a1b-7bd51109d1da.txt

**Comment by coryan** [comment]
https://pantheon.corp.google.com/cloud-build/builds;region=us-east1/be2d9182-9eb4-4178-91e9-3174ce7c60e0;step=2?jsmode=o&mods=logs_tg_prod&project=cloud-cpp-testing-resources

**Comment by dbolduc** [comment]
* GCB https://console.cloud.google.com/cloud-build/builds;region=us-east1/b2b0f844-159c-4dac-8aa8-4c1af635a5f7;tab=detail?project=cloud-cpp-testing-resources
* Raw https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/aef89934e50008603f68c6373c830b80cae79c1b/fedora-37-cmake-check-api/log-b2b0f844-159c-4dac-8aa8-4c1af635a5f7.txt

**Comment by dbolduc** [comment]
CONSOLE_LOG_URL
https://console.cloud.google.com/cloud-build/builds;region=us-east1/3a21e7b5-1dbb-4df0-887a-59652253c015;tab=detail?project=cloud-cpp-testing-resources
RAW_LOG_URL
https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/ad2872e3b7f02bf586c48180069167e6cedaf053/demo-opensuse-leap-demo-install/log-3a21e7b5-1dbb-4df0-887a-59652253c015.txt

**Comment by coryan** [comment]
https://pantheon.corp.google.com/cloud-build/builds;region=us-east1/1d6fe953-5efd-488c-b8d1-e0bc2150ea70;step=2?jsmode=o&mods=logs_tg_prod&project=cloud-cpp-testing-resources

**Comment by coryan** [comment]
Upgrading the gcloud CLI did not help:

https://console.cloud.google.com/cloud-build/builds;region=us-east1/dcd9eb03-4738-4b7c-b98b-a831fb4d9172?project=936212892354

**Comment by coryan** [comment]
No repeats in 90d, closing.
