### ISSUE TITLE
bigtable_examples_table_admin_snippets GenerateConsistencyToken connection reset

### ISSUE THREAD

**Issue by devbww** [googleapis/google-cloud-cpp#10082]
```
 7/24 Test #239: bigtable_examples_table_admin_snippets ...............***Failed    0.15 sec 
    :
Running GenerateConsistencyToken() example
Standard exception raised: Error in non-idempotent operation GenerateConsistencyToken: Connection reset by peer
```
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/7c25362c-3036-4279-8788-0abe9b9bdca0;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/c8625e063050fc406de8a5afe7913a9a1d80b082/fedora-36-cmake-gcs-rest/log-7c25362c-3036-4279-8788-0abe9b9bdca0.txt

Darren says, "I think the emulator went down."

**Comment by dbolduc** [comment]
Closing in favor of #8331
