### ISSUE TITLE
std::async invoked synchronously, causing problems in C++20

### ISSUE THREAD

**Issue by higher-performance** [googleapis/google-cloud-cpp#10080]
The `std::future` returned by `std::async` is discarded here:

https://github.com/googleapis/google-cloud-cpp/blob/c8625e063050fc406de8a5afe7913a9a1d80b082/google/cloud/bigtable/mutation_batcher_test.cc#L821

This is likely a bug and ~will also trigger compiler diagnostics in C++20 due to `[[nodiscard]]` being added to it~. (Edit: sorry about that, I missed the `.get` usage. There's no warning in that case; just wanted to report it in case it was a bug.)

**Comment by coryan** [comment]
Thanks for the bug report, as this is only in a test I think it is only a P3.
