### ISSUE TITLE
Consider grouping services by library in generator config

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#10237]
Our repo has a structure to it. We have services contained in libraries. If the generator configuration reflects that, it will help us maintain consistency and confidence in our documentation across all libraries. I am thinking something like:

```proto
message LibraryConfiguration {
  string name = 1;
  string display_name = 2;
  string description = 3;
  string cloud_service_root = 4;
  string cloud_service_docs = 5;
  string cloud_quickstart = 6;
  bool experimental = 7;
  repeated ServiceConfiguration service = 8;

  // we can add more knobs, but we should be cautious about doing so.
}

message GeneratorConfiguration {
  repeated LibraryConfiguration library = 1;

  // Support standalone services, for libraries that have handwritten documentation.
  repeated ServiceConfiguration service = 2;
}
```

At the moment, we generate many things in the scaffolding. https://github.com/googleapis/google-cloud-cpp/blob/a590dc461ad7a725ee0664fb9f61a1d5a4f5b04b/generator/internal/scaffold_generator.cc#L118-L132

I think (at least) the following should be generated for each `LibraryConfiguration`:
* `README.md`
* `doc/main.dox`
* `doc/options.dox`
* `quickstart/.bazelrc`
* `samples/BUILD.bazel`
* `samples/CMakeLists.txt`

We do not want to move things to the generator config, just because. Some things are easier to maintain in place, and impossible to generalize. An obvious example would be the `quickstart/quickstart.cc`'s.

I explored this some in a branch. I started with the `README.md` and `doc/main.dox`:
https://github.com/googleapis/google-cloud-cpp/compare/main...dbolduc:google-cloud-cpp:generator-library-config-dev?expand=1

**Comment by coryan** [comment]
There is a separate effort to have a single source of truth for all client libraries (across all languages).  

I have also been thinking that we could generate `main.dox` from `README.md` with a few alterations to make the generation "easy".

**Comment by dbolduc** [comment]
The individual service generators know their client names / namespaces / filepaths / endpoints. But there is not a great way to get that information back into `standalone_main.cc` in order to generate documentation type stuff.

I like the concept of the `main-dox-marker` https://github.com/googleapis/google-cloud-cpp/blob/ba4669ee64106d6269a451bddcfc6c86cf6cde5a/google/cloud/accessapproval/samples/access_approval_client_samples.cc#L29

Maybe we could extend it and have each service generate a data file that makes the extraction super-duper easy.
```
// file: google/cloud/library/v1/.foo.dat
Foo                 // service name CamelCase
foo                 // service name snake_case
library_v1          // service namespace
```

**Comment by coryan** [comment]
@dbolduc says they have a draft PR, maybe revisit in the next pass.

**Comment by coryan** [comment]
Closing. We have other thoughts.
