### ISSUE TITLE
pubsublite PublisherIntegrationTest.WithOrderingKey pure virtual method called

### ISSUE THREAD

**Issue by devbww** [googleapis/google-cloud-cpp#10256]
```
Step #3: 2022-11-16T00:10:56.819048741Z [WARNING] <140169994152128> MakeAdminServiceConnection: Unexpected option (mangled name): N6google5cloud10pubsublite6v2_5_022MaxBatchMessagesOptionE (google/cloud/options.cc:32)
Step #3: pure virtual method called
Step #3: terminate called without an active exception
Step #3: external/bazel_tools/tools/test/collect_coverage.sh: line 166:    20 Aborted                 (core dumped) "$@"
```
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/5a808753-c44d-4d8d-9ea8-e41ff5526885;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/cfc10cb3b7516ef026bf1f6c796c2863eb3685ea/fedora-36-bazel-coverage/log-5a808753-c44d-4d8d-9ea8-e41ff5526885.txt

**Comment by coryan** [comment]
No repeats in more than 90d. Closing.
