### ISSUE TITLE
kokoro/macos/bazel often times out for full builds

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#10272]
For example:

https://source.cloud.google.com/results/invocations/7feaaa95-8bb3-4147-af74-d47e0e941b7d

The code is so large that any changes touching `google_cloud_cpp_common` seem to take more than 7200 seconds.  I think we just need to increase the timeout value.
Note that by the time the CI build runs the Bazel cache is warm. This will not come up in our regular ways to detect flakes.

**Comment by dbolduc** [comment]
Is this a dup of #9571?

**Comment by coryan** [comment]
> Is this a dup of #9571?

Let's say yes, though I think we turned that bug into a "big bag of all timeout problems".

**Comment by coryan** [comment]
http://sponge2.corp.google.com/58e2f459-23cc-4e7b-a77e-f5f34b05afd3

**Comment by dbolduc** [comment]
https://source.cloud.google.com/results/invocations/2447b61d-63eb-49e1-bea1-23f027e7167d

**Comment by dbolduc** [comment]
https://source.cloud.google.com/results/invocations/da763f38-51c1-48fd-93b3-6a47513e1079

**Comment by dbolduc** [comment]
https://source.cloud.google.com/results/invocations/0118aa14-5018-4da8-ae76-36069cf4b55f

**Comment by dbolduc** [comment]
https://source.cloud.google.com/results/invocations/3dd4d303-b3a6-4c70-88a9-9cd12e7bab99
