### ISSUE TITLE
documentai quickstart flakes

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#10325]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/c599744e-3f17-4d21-98c1-5e0ac97821bc;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/c043c8b9bfdedbe553a6ad819364c13744887f38/fedora-36-cmake-quickstart-production/log-c599744e-3f17-4d21-98c1-5e0ac97821bc.txt

```
92/94 Test #377: documentai_quickstart ..............***Failed    3.41 sec
CMake Error at /workspace/cmake/quickstart-runner.cmake:90 (message):
  Non-zero exit status (1) running
  /workspace/cmake-out/google/cloud/documentai/documentai_quickstart

  google::cloud::Status thrown: INVALID_ARGUMENT: Error in non-idempotent
  operation ProcessDocument: Unsupported input file format.
```

While this is not an error message I would expect from a flake, I can successfully run the quickstart at HEAD.

I do not think this is a problem with the client library. We are using `application/pdf`, which is certainly a [supported file type](https://cloud.google.com/document-ai/docs/file-types#file_types): https://github.com/googleapis/google-cloud-cpp/blob/c043c8b9bfdedbe553a6ad819364c13744887f38/google/cloud/documentai/quickstart/quickstart.cc#L42

**Comment by coryan** [comment]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/4b06ae37-82d5-4cfb-bc94-34a5f4be4a6c;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/10430/5a376bebb0f376a5d48f77ca2c394c63e7651fcf/fedora-36-cmake-quickstart-production/log-4b06ae37-82d5-4cfb-bc94-34a5f4be4a6c.txt

**Comment by coryan** [comment]
I wonder if the GCS object we are using changes, or gets the wrong `contentType` set from time to time.

**Comment by coryan** [comment]
Maybe use the new `List*()` RPC.  Closing since we have not seen repeats in 90d.
