### ISSUE TITLE
More IntelliSense friendly interface for pubsub options

### ISSUE THREAD

**Issue by ujos** [googleapis/google-cloud-cpp#10355]
**What component of `google-cloud-cpp` is this feature request for?**

`google::cloud::Options`

**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I do not know what class should I pass into `gcp::Options::set<???>` template function argument.

**Describe the solution you'd like**

It would be much more convenient, if you move all the options classes (`GrpcBackgroundThreadsFactoryOption`, `GrpcCredentialOption`, etc) into some namespace (i.e. `gcp::options`) so I can type `gcp::options::` and press Ctrl+Space shortcut and then pick required option class from the list. If needed, namespaces can be composited from multiple namespaces:

```cpp
namespace basic_options 
{
    struct opt1 {};
    struct opt2 {};
}

namespace pubsub_subscriber_options 
{
    using namespace basic_options;
    struct opt3 {};
}
```
 
**Describe alternatives you've considered**

Define Options facade class per component and define all valid options there:

```cpp
struct SomeComponentOptions: gcp::Options
{
  void setA(int arg) { set<A>(arg); }
  void setB(int arg) { set<B>(arg); }
};
```

**Comment by coryan** [comment]
This is a fair criticism and we worried about it when introducing the `google::cloud::Options` class.  We did not consider an additional namespace.  Good idea!

FWIW, while this is not a good as your suggestion, the latest release groups the options in a common page:

https://googleapis.dev/cpp/google-cloud-pubsub/HEAD/group__pubsub-options.html

Note: The documentation for "latest" is still not out, but the release is.

**Comment by ujos** [comment]
@coryan I see there is the [SubscriberOptionList](https://googleapis.dev/cpp/google-cloud-pubsub/HEAD/group__pubsub-options.html#ga2c1b70b942849f7e6a1055fbc320972f) class. Looks like it is not complete as it does not include the supported Options from the `google::cloud` namespace.

**Comment by coryan** [comment]
Still want to do this, but no time at the moment.

**Comment by coryan** [comment]
With only one person asking for it, it is hard to prioritize.  Closing for now, please speak up if you think this would be useful.
