### ISSUE TITLE
GA timeline for the cloud storage experiemental async API

### ISSUE THREAD

**Issue by sar-gup** [googleapis/google-cloud-cpp#10406]
Hi,

Is there an ETA for the cloud storage experimental async API to be GA'ed?

We are trying to use the API and we get this error from the server side:
**Requested bucket, 'testcppbucket' is not allowed to access the GCS gRPC API. Note: this API is currently in testing, and is not yet available for general use.**

Is there a way that allows us to still use the experimental client?

**Comment by coryan** [comment]
You need to work with your account management team to be included in the allow list for GCS+gRPC.  They can talk to the GCS product management team and get that ball rolling.
