### ISSUE TITLE
Consider supporting per-call / per-client logging

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#10407]
## Background

Our stub factories only layer on the logging decorator when a tracing component is set. For example, https://github.com/googleapis/google-cloud-cpp/blob/8b2fd9430454b63844b9bc07d1b2e78678ba5002/google/cloud/accessapproval/internal/access_approval_stub_factory.cc#L53-L58

This means that whether a client logs or not is decided when the `Connection` is made. I think this is a historical artifact -- the logging decorators were designed before our library supported per-client options or per-call options.

## Analysis

The argument for doing this work is that customers would have more programmatic control over logging. For example, they could enable logging **only** for a certain RPC, by using per-call options. This may make the logs easier to sift through.

The argument against doing this work is that logging is typically enabled via environment variables. These take precedence over any per-call configuration. So, the behavior would be ever so slightly better as-is, because there would be one less layer of indirection in the non-logging case.

## Implementation

In order to support all option sources, we would:
- always include the logging decorator layer
- extract the logging components from the current options
  - (like we do in the [metadata decorator](https://github.com/googleapis/google-cloud-cpp/blob/7036edb3a3aa1a4fe00f6b2d65df3eaa604d78a5/google/cloud/accessapproval/internal/access_approval_metadata_decorator.cc#L125-L131). Maybe we don't want to plumb the `CurrentOptions()` in the long run, but we know the current options will always make it to the stubs somehow).
- eschew the `LogWrapper` if the logging components set is empty.
  - (whether we check the logging components in the decorator, or from within `LogWrapper` is an implementation detail)

**Comment by dbolduc** [comment]
## Alternative:

```cc
namespace google::cloud {
/**
 * Enables logging for a client
 * 
 * @note This option only takes affect when supplied to `Make*Connection()`.
 * 
 * @note To configure what gets logged, you must set `TracingComponentsOption`, which can be modified per-call.
 */
struct LoggingEnabledClientOption {
  using Type = bool;
};
}
```
And then in the stub factory we look for:

```cc
if (options.get<LoggingEnabledClientOption>()) { /* use logging decorator */ }
```

instead of

```cc
if (internal::Contains(options.get<TracingComponentsOption>(), "rpc")) { /* use logging decorator */ }
```

For backwards compatibility, we default the options as such:

```cc
Options PopulateCommonOptions(Options opts, ...) {
  // ......<abridged>.......
  
  if (!opts.has<TracingComponentsOption>()) {
    opts.set<TracingComponentsOption>(internal::DefaultTracingComponents());
  }
  if (!opts.has<LoggingEnabledClientOption>()) {
    opts.set<LoggingEnabledClientOption>(
        !opts.get<TracingComponentsOption>().empty());
  }

  // ......<abridged>.......
  return opts;
}
```

## Analysis

Pro:

- We could support per-call / per-client logging
- The non-logging case is unaffected. No performance hits.
 
Con:

- Too many `*Option`s to keep track of. It's probably confusing. And the names of the options aren't helping.

**Comment by coryan** [comment]
Closing for now, working on other priorities.
