### ISSUE TITLE
Cancellation token/trigger for the APIs in GCS SDK

### ISSUE THREAD

**Issue by sar-gup** [googleapis/google-cloud-cpp#10440]
**What component of `google-cloud-cpp` is this feature request for?**
google/cloud/storage

**Is your feature request related to a problem? Please describe.**
Unable to cancel an in-progress call to the SDK API method. Eg: If the user application is reading a large object from GCS by calling google::cloud::storage::client::ReadObject and wants to stop the read in the middle, there does not seem to be a mechanism to do so.

**Describe the solution you'd like**
A cancellation token/trigger which when invoked can cancel an in-progress SDK call.

**Comment by coryan** [comment]
You can do something like:

```cc
void F(storage::Client c) {
  auto reader = c.ReadObject("my-bucket", "my-object");
  // read a little bit ..
  reader.Close();  // or just return.
}
```

Calling [`Close()`](https://googleapis.dev/cpp/google-cloud-storage/latest/classgoogle_1_1cloud_1_1storage_1_1ObjectReadStream.html#a666ae074afab90696e5da94163813393) "terminates the download".

The destructor implicitly calls `Close()` too.  Is there something not working with these functions?

**Comment by sar-gup** [comment]
This should work. Thanks!
