### ISSUE TITLE
Calling storage::Client::CreateBucket() returns kAborted instead of kAlreadyExists for existing bucket

### ISSUE THREAD

**Issue by sar-gup** [googleapis/google-cloud-cpp#10478]
**Does this issue affect the google-cloud-cpp project?**
Yes

**What component of `google-cloud-cpp` is this related to?**
google/cloud/storage

**Describe the bug**
Calling storage::Client::CreateBucket() for an already existing bucket returns ::StatusCode::kAborted with a message:
"Permanent error CreateBucket: Your previous request to create the named bucket succeeded and you already own it."

The expectation for the method is to return ::StatusCode::kAlreadyExists.

**To Reproduce**

1. Call function storage::Client::CreateBucket({bucket_name},...) and ensure that it succeeds.
2. Call the same function again with the same bucket name.

Returned value of google:: cloud ::Status with:
code: kAborted
message: "Permanent error CreateBucket: Your previous request to create the named bucket succeeded and you already own it."

**Expected behavior**
Expected return value:
google:: cloud ::Status with code=kAlreadyExists.

**Operating system:**
ubuntu 20.04 LTS

**What compiler and version are you using?**
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.1.0-1ubuntu1~20.04' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --disable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-11-2V7zgg/gcc-11-11.1.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-11-2V7zgg/gcc-11-11.1.0/debian/tmp-gcn/usr --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.1.0 (Ubuntu 11.1.0-1ubuntu1~20.04)

**What version of `google-cloud-cpp` are you using?**
v2.4.0

**Comment by devbww** [comment]
Here is an RPC trace of such a failing operation, which indicates that the service indeed returns an "ABORTED" code.

```
2022-12-29T06:50:27.310150675Z [INFO] <140712213629184> CreateBucket() <<
  CreateBucketRequest={
    project_id=cloud-cpp-testing-resources,
    metadata=BucketMetadata={
      name=gcs-grpc-team-cloud-cpp-testing-examples-2022-12-29_99vubl9cj8j,
      acl=[],
      cors=[],
      default_event_based_hold=false,
      default_acl=[],
      etag=,
      id=,
      kind=,
      location=US,
      location_type=,
      metageneration=0,
      name=gcs-grpc-team-cloud-cpp-testing-examples-2022-12-29_99vubl9cj8j,
      project_number=0,
      self_link=,
      storage_class=STANDARD,
      time_created=1970-01-01T00:00:00Z,
      updated=1970-01-01T00:00:00Z,
      rpo=
    }
  }
2022-12-29T06:50:27.770371605Z [INFO] <140712213629184> CreateBucket() >>
  status={
    ABORTED: Your previous request to create the named bucket succeeded and you already own it.
    error_info={
      reason=conflict,
      domain=global,
      metadata={
        http_status_code=409
      } 
    }
  }
```

> Expected return value:
> google:: cloud ::Status with code=kAlreadyExists.

I'll leave it to my colleagues more familiar with the service to determine what should be expected.

**Comment by coryan** [comment]
> > Expected return value:
> > google:: cloud ::Status with code=kAlreadyExists.
> 
> I'll leave it to my colleagues more familiar with the service to determine what should be expected.

I think `kAlreadyExists` is a more reasonable error code in this case.  While I think we should fix this, it is not immediately obvious *how* to provide a good fix.

We need to map from HTTP status codes to `google::cloud::StatusCode` and the mapping in this case is ambiguous.  The raw error (see an example below) returns `409` and only text message indicates that this error was caused by a duplicate bucket. The protocol does mention that 409 can be used to indicate duplicate buckets (it is a bit hidden):

https://cloud.google.com/storage/docs/json_api/v1/status-codes#409-conflict

But the same error can be used for other things where `kAborted` seems more appropriate:

https://cloud.google.com/storage/docs/json_api/v1/status-codes#409_Conflict

All of this suggests that maybe we should just do something special for `CreateBucket()`.

------

```
HTTP/2 409 
x-guploader-uploadid: ADPycdvYoDYFPDxBsj8AJ8S_Ut63NFcO0ZCHaRqmV0VSzvBT2OXmcaXQuMkWS6kgGSxtR1IAQEQhHv97V8h-gQRJxzPY3w
content-type: application/json; charset=UTF-8
date: Thu, 29 Dec 2022 16:54:39 GMT
vary: Origin
vary: X-Origin
cache-control: no-cache, no-store, max-age=0, must-revalidate
expires: Mon, 01 Jan 1990 00:00:00 GMT
pragma: no-cache
content-length: 339
server: UploadServer

{
  "error": {
    "code": 409,
    "message": "Your previous request to create the named bucket succeeded and you already own it.",
    "errors": [
      {
        "message": "Your previous request to create the named bucket succeeded and you already own it.",
        "domain": "global",
        "reason": "conflict"
      }
    ]
  }
}
```
