### ISSUE TITLE
Move OCC Polling Loop to Connection layer

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#10476]
This API is anomalous in that we perform the loop for it [in the client layer](https://github.com/googleapis/google-cloud-cpp/blob/c403330a1888a78f724fa5dc22c2016cd53183da/google/cloud/spanner/admin/instance_admin_client.cc#L244-L275).

I think we erred in the design, compared with just having an analogous `Connection` method, and having the `ConnectionImpl` invoke its own `{Set,Get}IamPolicy(std::string const& resource, IamUpdater updater)` methods. But it is too late. Customers might expect several `Connection` calls in their mocks.

We should still [push the loop](https://github.com/dbolduc/google-cloud-cpp/commit/7f093a6329d500cb85e22de948586ab40abedb18) from the client to the base Connection class. (Mocks would break if we jumped straight to the `ConnectionImpl`). We should add a virtual updater method to the base class which does the dispatch. Our `MockConnection` and `ConnectionImpl` would not override this method. Our tracing stub would override it, and drop a span across the thing.

We should consider breaking the mocks in the next major release.

Also, @devbww reminds us that: "It is nice that the only functions that take a `std::string const& resource` are right next to each other". So that should get pushed to the Connection layer too.

**Comment by coryan** [comment]
This will be part of the OpenTelemetry tracing work.

**Comment by coryan** [comment]
Closing. We can reopen if needed.
