### ISSUE TITLE
Filter Connection-only Options in Client layer

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#10477]
A client's `options_` get copied for every call. As a mini-optimization we can filter out options that only apply when the connection is constructed (e.g. `EndpointOption`) when we first set the client's `options_`.

What this may look like is:
```cc
namespace google::cloud::internal {
Options FilterClientOptions(Options o) {
  o.unset<EndpointOption>();
  o.unset<GrpcNumChannelsOption>();
  // etc
  return o;
}
}
```

```cc
namespace google::cloud::foo {
Client::Client(
    std::shared_ptr<Connection> connection, Options opts)
    : connection_(std::move(connection)),
      options_(internal::FilterClientOptions(
          internal::MergeOptions(std::move(opts), connection_->options()))) {}
}
```

**Comment by devbww** [comment]
> A client's `options_` get copied for every call.

Perhaps that it something worth trying to address at its core.  For example, if there are no per-call options, might we be able to create the span without copying the client options?

**Comment by coryan** [comment]
Closing for now. Will reopen if the performance impact justifies the change.
