### ISSUE TITLE
Synchronous OpenTelemetry tracing in grpc_utils

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#10489]
Some tasks from [Milestone 1](https://docs.google.com/document/d/1JTOWvZD59AGxojTV93tKZJ9b_q2w8YUMMyuxCu5_ZC4/edit?resourcekey=0-0XjX6fh2xNKFZN20cu2otg#bookmark=id.i1nfe2c9gho2) of an internal design doc. With these tasks completed, we can support tracing a synchronous unary client call, including its subcomponents (network call, backoffs).

- [x] Add `MakeSpanGrpc()`
- [x] `EndSpan` from `grpc::ClientContext`
- [x] Add sync traced sleeper; Update `RetryLoop` to use it
- [x] Add `InjectTraceContext()`

**Comment by coryan** [comment]
dbolduc is still working on this.

**Comment by dbolduc** [comment]
The piece that is missing is parsing the gRPC peer string into attributes that follow OpenTelemetry's semantic conventions:

https://github.com/googleapis/google-cloud-cpp/blob/1145a8ccff7f8ce7fcebc0256efe6b3093e8e21a/google/cloud/internal/grpc_opentelemetry.cc#L95-L100

**Comment by dbolduc** [comment]
Closing this because...
- Parsing the peer URI is really annoying
- The information is all there. It is just that we are not perfectly following OpenTelemetry semantic conventions.
