### ISSUE TITLE
Refactor TimerQueue wait_until predicate

### ISSUE THREAD

**Issue by scotthart** [googleapis/google-cloud-cpp#10521]
Per review comment:

It strikes me that the ne < until condition should be narrower. If ne < until then an earlier timer has been installed, and we should indeed terminate the wait_until(), and start a new one with a new deadline.

But if ne > until then the timer we were awaiting has either been expired by another thread, or it has been cancelled. In either case we should also immediately terminate the wait_until(), and start a new one with a new deadline.

So, use ne != until instead.

And indeed, from there, we don't even need HasExpiredTimers(). We have an expired timer when the wait terminates iff NextExpiration() == until.

There is something wrong with that last bit. The possibility of a spurious wakeup means we'd also need until <= now() to have an expired timer. But perhaps the return value from wait_until() could still be used to avoid the need for Clock.

**Comment by devbww** [comment]
To make things concrete, here is the suggestion from the chat thread:
```
  void Service() {
    // TODO(#10512): Rather than having all threads awaiting the earliest
    // timer, we should match the N serving threads against the N earliest
    // timers (idling some threads if there aren't enough timers).
    std::unique_lock<std::mutex> lk(mu_);
    while (!shutdown_) {
      if (timers_.empty()) {
        cv_.wait(lk, [this] { return shutdown_ || !timers_.empty(); });
        continue;
      }
      auto until = timers_.begin()->first;
      if (cv_.wait_until(lk, until, [this, until] {
            return shutdown_ || timers_.empty() ||
                   timers_.begin()->first != until;
          })) {
        continue;
      }
      auto p = std::move(timers_.begin()->second);
      timers_.erase(timers_.begin());
      Expire(lk, std::move(p), until);
    }
    while (!timers_.empty()) {
      auto p = std::move(timers_.begin()->second);
      timers_.erase(timers_.begin());
      Expire(lk, std::move(p), CancelledError("TimerQueue shutdown"));
    }
  }
```
where the only helper is ...
```
  void Expire(std::unique_lock<std::mutex>& lk, PromiseType p,
              StatusOr<TimePoint> v) {
    lk.unlock();
    p.set_value(std::move(v));
    lk.lock();
  }
```
