### ISSUE TITLE
Refactor commonalities between RestRetryLoop and RetryLoop

### ISSUE THREAD

**Issue by scotthart** [googleapis/google-cloud-cpp#10575]
These two types are largely the same except for the context type `grpc::ClientContext` and `rest_internal::RestContext` that they use. Adding to the difficulties is `grpc::ClientContext` is wrapped by a std::unique_ptr because it is non-copyable/non-movable, but the libraries the .h files reside in are different which introduces dependency issues.

**Comment by coryan** [comment]
We have better cleanups to do. Closing.
