### ISSUE TITLE
Consider factoring out MD resource extraction, for tracing.

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#10582]
To summarize a discussion here: https://github.com/googleapis/google-cloud-cpp/pull/10567#discussion_r1069861842

1. We should capture the resource(s) that an RPC is targeting in our traces.
2. It is extra helpful if that resource is known when the span is created.

One way to do that is to factor out the `x-goog-request-params` stuff that is done in the MD header. (e.g. this for [explicit routing](https://github.com/googleapis/google-cloud-cpp/blob/a2a4a6da83df8ea3bf7e3fd0aa1e8f5e5b03bc9e/google/cloud/bigtable/internal/bigtable_metadata_decorator.cc#L43-L61), and this for [HTTP routing](https://github.com/googleapis/google-cloud-cpp/blob/a2a4a6da83df8ea3bf7e3fd0aa1e8f5e5b03bc9e/google/cloud/kms/internal/ekm_metadata_decorator.cc#L40))

For example, let's say we have: `google::cloud::foo_vN::FooClient::GetBar(GetBarRequest const& request)`. We can define one standalone function that does the extraction per client call. e.g.:

```cc
namespace google::cloud::foo_vN_internal {
/**
 * Extracts routing resources from the given request.
 * 
 * Returns a list of pairs.
 * 
 * e.g.: {{"k1","v1"},{"k2","v2"}}
 * As MD header: {"x-goog-request-params", "k1=v1&k2=v2"}
 * As span attributes: {{"gcloud.resource.k1","v1"},{"gcloud.resource.k2","v2"}}
 */
std::vector<std::pair<std::string, std::string>> ExtractResourcesFooGetBar(GetBarRequest const&);
}
```

Then we can call this method both from within the MD decorator, and from the connection level tracing decorator when we create the spans.

**Comment by coryan** [comment]
Darren wants to do this as part of the OpenTelemetry tracing work.

**Comment by coryan** [comment]
We won't have time to work on this for the foreseeable future.
