### ISSUE TITLE
Installed `google-cloud-cpp` w/ OpenTelemetry usable from `make(1)`

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#10795]
If `google-cloud-cpp` is compiled and installed with OpenTelemetry, we need to make sure the proper Cflags are present in the package config for the library.

OpenTelemetry does not generate a package config file, so we will have to include their Cflags as well, or install a `*.pc` file for them.

**Comment by coryan** [comment]
Still blocked on OTel, but they are making progress.
