### ISSUE TITLE
codecov coverage upload flake

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#10922]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/8c742e7c-2fd2-4213-b890-4cf616aad768;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/10915/1e1d2c659e66d13c73e2694352db2e60ef7f3a05/fedora-37-bazel-coverage/log-8c742e7c-2fd2-4213-b890-4cf616aad768.txt

```
------------------------------------------------------------
|   Uploading /var/tmp/merged-coverage.lcov to codecov.io   |
-------------------------------------------------------------
2023-02-22T19:04:33Z (+481s): Flags: --filter=gcov --file=/var/tmp/merged-coverage.lcov --branch=doc-howto-declare-ga --sha=1e1d2c659e66d13c73e2694352db2e60ef7f3a05 --pr=10915 --build=8c742e7c-2fd2-4213-b890-4cf616aad768 --verbose
curl: (56) OpenSSL SSL_read: Connection reset by peer, errno 104
```

**Comment by coryan** [comment]
No repeats in 90d, closing.

**Comment by dbolduc** [comment]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/1e878564-4e7d-4ead-bf17-6b714de16161;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/2a81b7fc2576ae8c603b5d78024d0c16336d5e17/fedora-37-bazel-coverage/log-1e878564-4e7d-4ead-bf17-6b714de16161.txt

**Comment by coryan** [comment]
We could add a retry loop around the upload.  And maybe consider upgrading:

https://github.com/codecov/uploader/releases/tag/v0.6.2

**Comment by dbolduc** [comment]
Closing, no repeats in 90 days.
