### ISSUE TITLE
vision grpc bug

### ISSUE THREAD

**Issue by BlackdeerY** [googleapis/google-cloud-cpp#10941]
**Does this issue affect the google-cloud-cpp project?**
no

**What component of `google-cloud-cpp` is this related to?**
vision

**Describe the bug**
In Windows(10) OS,
grpc don't use environment variable 'GRPC_DEFAULT_SSL_ROOTS_FILE_PATH'.
just access '/usr/share/grpc/roots.pem'.
I use vcpkg.

**Operating system:**
Windows 10

**What compiler and version are you using?**
clang version 8.0.1 (tags/RELEASE_801/final)
Target: i686-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files (x86)\LLVM\bin

**What version of `google-cloud-cpp` are you using?**
2.7.0

**Additional context**
.

**Comment by coryan** [comment]
This looks like a gRPC bug.  There is nothing we can do in `google-cloud-cpp` to stop gRPC from using `GRPC_DEFAULT_SSL_ROOTS_FILE_PATH` correctly.  Nor can we help them.

With that said, can you share how you are setting this environment variable?

**Comment by BlackdeerY** [comment]
After setting the environment variable, I logged on my Windows account again and it ran perfectly(Actually turned it back on after sleep).
I expected grpc to be available as well since it was available with echo %GRPC_DEFAULT_SSL_ROOTS_FILE_PATH% in the new cmd.
But grpc required at least a minimal sleep process.
