### ISSUE TITLE
vcpkg failed to take the filesystem lock

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#10981]
This is the same error as we saw in #4487, but I am opening a new issue because things have changed since then.

https://source.cloud.google.com/results/invocations/f92f1886-83ac-4375-a703-b64d8c1d1a6a

```
-------------------------------------------------
|   Configure CMake for bigquery's quickstart   |
-------------------------------------------------
ci/kokoro/macos/builds/quickstart-cmake.sh: line 65: error: Failed to take the filesystem lock on /Volumes/BuildData/tmpfs/src/vcpkg-quickstart/.vcpkg-root
    Resource busy: No such file or directory
```

Observations:
- We use vcpkg in [manifest mode](https://learn.microsoft.com/en-us/vcpkg/users/manifests). ([Previous discussion](https://github.com/googleapis/google-cloud-cpp/pull/4495#issuecomment-656719405) said we were using classic mode.)
- I could not find `--feature-flags=` anywhere in the vcpkg documentation. ([We use it](https://github.com/googleapis/google-cloud-cpp/blob/16ffa2e319b2d912ad202d8d6eb76a1b47091ba6/ci/kokoro/macos/builds/quickstart-cmake.sh#L62))
- There was discussion of `--x-wait-for-lock`... but I can't find that in the documentation either.

**Comment by devbww** [comment]
https://source.cloud.google.com/results/invocations/438a55b8-e76c-4508-9f86-92df8252c289

**Comment by dbolduc** [comment]
https://source.cloud.google.com/results/invocations/a728333d-57fb-4a18-9551-e1140e5d5728

**Comment by coryan** [comment]
http://sponge2.corp.google.com/edc90747-99e7-4cb2-b761-97c0f9fb7e9e

**Comment by coryan** [comment]
We may want to use these flags:

https://github.com/microsoft/vcpkg-tool/blob/7c1708eaeb1f87126ec808e9fe0f6bc7cb2c72ec/include/vcpkg/vcpkgcmdarguments.h#L181-L183

**Comment by dbolduc** [comment]
https://source.cloud.google.com/results/invocations/3876c899-4ce9-4232-9b59-1e3e2af12059

**Comment by coryan** [comment]
We no longer use Kokoro, closing.
