### ISSUE TITLE
Consolidate `dialogflow`

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#10994]
We have separate libraries for Dialogflow v2 and v3.
- `google/cloud/dialogflow_cx`
- `google/cloud/dialogflow_es`

These were generated before we established the convention that one library should hold all versions of a GCP service.

As @coryan suggests, we should redefine the clients in a new `google/cloud/dialogflow` library. The existing versioned libraries should depend on the new library.

Note that, we have internal metrics showing requests from `dialogflow`, so we should not just move the libraries without maintaining backwards compatibility. (i.e. we cannot use the same argument that let us remove `pubsub::SchemaAdminClient`).

**Comment by coryan** [comment]
Let's consider this for 2023/Q4.

**Comment by scotthart** [comment]
Closing for now.
