### ISSUE TITLE
Generate library for `mediatranslation.googleapis.com`

### ISSUE THREAD

**Issue by lazedo** [googleapis/google-cloud-cpp#11013]
**What component of `google-cloud-cpp` is this feature request for?**
mediatranslation

**Is your feature request related to a problem? Please describe.**
trying to use this library instead of custom generated 

**Describe the solution you'd like**
mediatranslation added

**Describe alternatives you've considered**
continue using custom generated api with grpc instead of this library

**Comment by coryan** [comment]
Thanks for taking the time to file a feature request.  Please give us a few days to think about how to best support products that only have "beta" and "alpha" versions:

https://github.com/googleapis/googleapis/tree/master/google/cloud/mediatranslation
https://cloud.google.com/translate/media/docs

**Comment by coryan** [comment]
We do not believe we can support libraries for alpha or beta services at this time.  The team supporting `google-cloud-cpp` is not large and we have to prioritize where we spend our time.  If this is a big problem for you, and you already have a support contract, please open a support case at https://cloud.google.com/support/.
