### ISSUE TITLE
Cloud app features? 

### ISSUE THREAD

**Issue by microchipen** [googleapis/google-cloud-cpp#11064]
**What component of `google-cloud-cpp` is this feature request for?**
For example, is this related to bigtable (i.e., something in `google/cloud/bigtable`), or GCS (i.e., something in `google/cloud/storage`)?

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when \[...\]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by coryan** [comment]
Looks like a mistake. Closing.
