### ISSUE TITLE
Exponential Backoff ranges are incorrect

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#11107]
We have a `scaling` factor, but we multiply the initial range by 2, instead.

https://github.com/googleapis/google-cloud-cpp/blob/9737c4bfc27eea6c593dcbe2d59af41d266acc0c/google/cloud/internal/backoff_policy.h#L131

Moreover, we do not check if we have hit the maximum until after generating the first backoff 

https://github.com/googleapis/google-cloud-cpp/blob/9737c4bfc27eea6c593dcbe2d59af41d266acc0c/google/cloud/internal/backoff_policy.cc#L45-L55

This leads to kooky behavior. Let's say I have an `ExponentialBackoffPolicy(10s, 11s, 1.1)`.

The first range will be: [10s, 20s], which does not respect the maximum.

All subsequent ranges will be: [5.5s, 11s], which does not respect the minimum.

Lol.

**Comment by alevenberg** [comment]
To further recap what Darren described:
Current behavior
ExponentialBackoffPolicy(10s, 11s, 1.1)
First call: [10s, 20s]
Second call: [5.5s, 11s]
Third call: [5.5s, 11s]

Intended behavior
ExponentialBackoffPolicy(10s, 11s, 1.1)
First call: [10s, 11s]
Second call: [10s, 11s]
Third call: [10s, 11s]

A more general case:
Current behavior
ExponentialBackoffPolicy(1s, 11s, 2)
First call: [1s, 2s]
Second call: [2s, 4s]
Third call: [8s, 16s]
Fourth call: [5.5s, 11s]
Fifth call: [5.5s, 11s]

Intended behavior
ExponentialBackoffPolicy(1s, 11s, 2)
First call: [1s, 2s]
Second call: [1s, 4s]
Third call: [1s, 8s]
Fourth call: [1s, 11s]
Fifth call: [1s, 11s]

#8755 describes the initial implementation decision conversation. I will move forward with implementing min-jitter.

**Comment by dbolduc** [comment]
> I will move forward with implementing min-jitter.

errrr..... I do not recommend this. I think you should fix one bug at a time, starting with this bug. Yes #8755 is juicier, but you will benefit from starting on a smaller problem.

I would say the intended behavior we want for the "more general case" (as far as this bug is concerned) is the current behavior:

`ExponentialBackoffPolicy(1s, 11s, 2)` gives...

|call # | backoff range|
|-|-|
|1 | [1s, 2s] |
|2 | [2s, 4s] |
| 3 | [4s, 8s] |
| 4 | [5.5s, 11s] |
| N | [5.5s, 11s] |
