### ISSUE TITLE
Unified REST credentials integration test does not receive `kind` field.

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#11109]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/f47171ff-8c60-4641-8a57-ea07c075e1f6;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/cae4aa9e7efc5bc0c9d0c88d850569ffa4f4ac1e/fedora-37-bazel-ubsan/log-f47171ff-8c60-4641-8a57-ea07c075e1f6.txt

```
[ RUN      ] UnifiedRestCredentialsIntegrationTest.ServiceAccountCredentials
google/cloud/internal/unified_rest_credentials_integration_test.cc:65: Failure
Value of: parsed.contains("kind")
  Actual: false
Expected: true
google/cloud/internal/unified_rest_credentials_integration_test.cc:158: Failure
Expected: MakeBigQueryRpcCall(Options{}.set<UnifiedCredentialsOption>( MakeServiceAccountCredentials(contents))) doesn't generate new fatal failures in the current thread.
  Actual: it does.
[  FAILED  ] UnifiedRestCredentialsIntegrationTest.ServiceAccountCredentials (10196 ms)
```

https://github.com/googleapis/google-cloud-cpp/blob/4755e88267bb830217d8a67b23d3a24287fd8a5f/google/cloud/internal/unified_rest_credentials_integration_test.cc#L65

**Comment by coryan** [comment]
No repeats in 90d. Closing.
