### ISSUE TITLE
change spanner::RouteToLeaderOption to be on by default

### ISSUE THREAD

**Issue by devbww** [googleapis/google-cloud-cpp#11111]
We have received the go-ahead to release the `spanner::RouteToLeaderOption` feature, but as "off by default".

Users can override this programmatically with `opts.set<spanner::RouteToLeaderOption>(true)`, or environmentally with `GOOGLE_CLOUD_CPP_SPANNER_ROUTE_TO_LEADER=1`.

This issue is for changing that back to "on by default" when the time is right.

**Comment by coryan** [comment]
Still waiting for the service team to say it is Okay to do this.
