### ISSUE TITLE
Cleanup bigquery REST metadata decorator

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#11120]
https://github.com/googleapis/google-cloud-cpp/blob/aebbf5fddf803469c2aef457fa080ff4d7810f66/google/cloud/bigquery/v2/minimal/internal/job_metadata.cc#L47-L53

We should only call `SetMetadata(context);`

According to #10255 we only do something special for explicit routing headers. (rpc's that have the `google.api.routing` annotation). I checked and the job proto does not have these.

Same goes for `GetJob()`

<hr />

Also, it is strange to me that we have a `bigquery_rest_stub.h` but we call the metadata decorator: `bigquery_metadata.h`. They both interact with a `RestContext`, so I feel like either both should have `rest` in the name, or neither.

Same goes for the logging decorator.

**Comment by jsrinnn** [comment]
Nice timing, I am currently working on a PR for adding unit tests for job_metadata.

Regarding the naming, I felt the stub needed clarification as we also have grpc stubs. Additional it is an internal impl class. I don't think we need to propagate that all the way up to the decorators, connections, clients etc.

**Comment by dbolduc** [comment]
> Regarding the file naming

See the classes in here: https://github.com/googleapis/google-cloud-cpp/tree/main/generator/integration_tests/golden/v1/internal

We have separate gRPC and REST versions of the metadata and logging decorators, too. (e.g. `golden_kitchen_sink_metadata_decorator.h` vs. `golden_kitchen_sink_rest_metadata_decorator.h`).

> internal impl

Ack that they are internal implementations that we can always change, but I think the code will be easiest to maintain if we keep it in line with the generator.

**Comment by jsrinnn** [comment]
Thanks Darren, I am going to stand by what I said before. Just like the decorators, clients and connection classes for grpc don't  explicitly have "grpc" in the name,  I don't think "rest" needs to be propagated to outer/top-level classes. In my opinion the transport used is an internal implementation detail. The stub seemed to be the apt place to clarify that.

I agree with you regarding the parameter setting and I'll remove that for now. In the future if it is needed then it can be added.

**Comment by dbolduc** [comment]
Decorators are stubs, and they do depend on the transport.

The gRPC metadata decorator extends the gRPC stub: https://github.com/googleapis/google-cloud-cpp/blob/8d2c85012177c656ab58d33abefad7436648442b/generator/integration_tests/golden/v1/internal/golden_kitchen_sink_metadata_decorator.h#L32

and it interacts with a `grpc::ClientContext`: https://github.com/googleapis/google-cloud-cpp/blob/8d2c85012177c656ab58d33abefad7436648442b/generator/integration_tests/golden/v1/internal/golden_kitchen_sink_metadata_decorator.cc#L40

<hr />

The REST metadata decorator extends the REST stub: https://github.com/googleapis/google-cloud-cpp/blob/8d2c85012177c656ab58d33abefad7436648442b/generator/integration_tests/golden/v1/internal/golden_kitchen_sink_rest_metadata_decorator.h#L35

and it interacts with a `rest_internal::RestContext`: https://github.com/googleapis/google-cloud-cpp/blob/8d2c85012177c656ab58d33abefad7436648442b/generator/integration_tests/golden/v1/internal/golden_kitchen_sink_rest_metadata_decorator.cc#L42

<hr />

> I am going to stand by what I said before

Same.

> classes for grpc don't explicitly have "grpc" in the name

Yes, I think the naming scheme is somewhat confused, but we should be consistent with what we have.

**Comment by jsrinnn** [comment]
Yeah...I don't see grpc here for the decorators: https://github.com/googleapis/google-cloud-cpp/tree/main/google/cloud/bigquery/storage/v1/internal

For now I am leaving the file name as is. 
Tbh, The links you gave our really confusing to understand with those long names. The storage/v1 filename above are much easier to read.

Howevre, for consistency I can following the kitchen sink format naming when I get to writing the integration tests. I would prefer to leave the job file the way it is.
