### ISSUE TITLE
macOS can't open file '/tmpfs/kokoro_log_reader.py'

### ISSUE THREAD

**Issue by devbww** [googleapis/google-cloud-cpp#11181]
https://source.cloud.google.com/results/invocations/53bfcda2-bd20-42f7-9ea7-1a8d42d680ed
```
/Users/kbuilder/.pyenv/versions/3.10.3/bin/python3: can't open file '/tmpfs/kokoro_log_reader.py': [Errno 2] No such file or directory
```

**Comment by coryan** [comment]
I think this is just another form of #9640.  The file is installed by Kokoro, but it is gone while trying to use it.

**Comment by devbww** [comment]
SGTM.  Thanks.  Closing in favor of #9640.
