### ISSUE TITLE
Not logged into gcloud on GCB (Cloud Build)

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#11235]
CONSOLE_LOG_URL
https://console.cloud.google.com/cloud-build/builds;region=us-east1/af35868b-728a-4715-9f14-aaa3df078f8c;tab=detail?project=cloud-cpp-testing-resources
RAW_LOG_URL
https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/11226/105795f7346a6271839935441b23dd4476108e8c/fedora-37-cxx20-cxx20/log-af35868b-728a-4715-9f14-aaa3df078f8c.txt

```
Step #8: WARNING: Could not open the configuration file: [/h/.config/gcloud/configurations/config_default].
Step #8: ERROR: (gcloud.builds.describe) You do not currently have an active account selected.
```

**Comment by coryan** [comment]
Ooooh.  I think our build scripts have a race condition:

- Step 7 (cleaning up any stale images from previous builds) and Step 2 (downloading the `ccache` files) run in parallel.  
- Step 7 wants to use the GCB service account (configured in the GCE instance)
- Step 2 wants to use a particular service account, and configures gcloud *in multiple steps*
- If Step 7 manages to run at the wrong time the authentication config is wrong.

**Comment by dbolduc** [comment]
https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/11553/006878f5e01f263f1aed1be35a91ad6fd270a3a4/fedora-37-cmake-publish-docs/log-1f4e2ab0-192d-4c10-8f77-73d17850232f.txt

**Comment by dbolduc** [comment]
CONSOLE_LOG_URL
https://console.cloud.google.com/cloud-build/builds;region=us-east1/3c4d9873-777b-4e02-8f53-9aaef503e309;tab=detail?project=cloud-cpp-testing-resources
RAW_LOG_URL
https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/11952/080c2e744f4d42cd456dbc30b516e088b7c35e17/fedora-37-bazel-xsan/log-3c4d9873-777b-4e02-8f53-9aaef503e309.txt
