### ISSUE TITLE
Create matchers for `otel::Span` links

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#11236]
This suggests to me that we need a matcher for span links. I think we would just check the span context. I don't think there is a simple way to match on names. (We would have to modify/wrap the in-memory exporter to maintain a span map, keyed by name, or something.)

I think we would want to write expectations like:

```cc
SpanDataPtr consumer_span;
opentelemetry::nostd::shared_ptr<opentelemetry::trace::Span> producer_span_1, producer_span_2;
EXPECT_THAT(consumer_span, SpanHasLinks(producer_span_1, producer_span_2));
```

Sorry that I am leaving this as an exercise for you.... Feel free to open an issue to do this work and assign it to me :)

Also parent ID, span links might be something to include in the `operator<<(, SpanData)` you added....

_Originally posted by @dbolduc in https://github.com/googleapis/google-cloud-cpp/pull/11227#discussion_r1162927969_

**Comment by dbolduc** [comment]
We decided not to use span links. Closing.
