### ISSUE TITLE
Implement Client::StopChannel()

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#1126]
This is mostly a note to record our decision **not** to implement the [`Channels: stop`](https://cloud.google.com/storage/docs/json_api/v1/channels/stop) API.

This API is rarely used, and the Pub/Sub APIs, such as `Client::DeleteNotification()` offer superior functionality.

**Comment by houglum** [comment]
SGTM, since Pub/Sub notifications are strongly encouraged over object change notifications.
