### ISSUE TITLE
Spanner LRO polling policy

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#11268]
We need basic examples showing how to override the most common defaults in hand-crafted *Client classes.

**Comment by devbww** [comment]
There are no longer any long-running operations in the hand-crafted (and supported) parts of the Spanner client.  That is, `spanner::SpannerPollingPolicyOption` and `spanner::PollingPolicy` are only used by the legacy instance/database admin classes, which are long deprecated and (hopefully) soon to be removed.

The usage of `spanner_admin::InstanceAdminPollingPolicyOption` and `spanner_admin::DatabaseAdminPollingPolicyOption` in the generated admin classes is documented in their "custom-instance-admin-policies" and "custom-database-admin-policies" snippets respectively, linked to from google/cloud/spanner/doc/override-retry-policies.dox.
