### ISSUE TITLE
Bazel quckstart tutorial silently fails

### ISSUE THREAD

**Issue by Yusup-Badiev** [googleapis/google-cloud-cpp#11488]
**Does this issue affect the google-cloud-cpp project?**
Yes

**What component of `google-cloud-cpp` is this related to?**
bigtable

**Describe the bug**
The Bazel quckstart tutorial does not work it, it stop running at line 46 in google-cloud-cpp/google/cloud/bigquery/quickstart/quickstart.cc. it just returns at that point with no error.

**To Reproduce**
1. Clone Repo
2. cd google-cloud-cpp/google/cloud/bigquery/quickstart
3. bazel build //...
4. `bazel run :quickstart <project-id>  <table-name>`
5. Notice that the code silently returns with out an error

**Expected behavior**
I expect the code to read a table and print how many rows it found, but it just exists early with no error

**Operating system:**
Ubuntu 20.04.6 LTS (Focal Fossa)

**What compiler and version are you using?**
bazel 6.1.2

**What version of `google-cloud-cpp` are you using?**
8ea75cf4f17ca32f42f21a68cd3c02d2c3e42d12

**Additional context**
The readme also says run `bazel build ...` however the command is `bazel build //...` this may however be bazel version specific I am not sure

**Comment by devbww** [comment]
> 4. bazel run :quickstart
> 5. Notice that the code silently returns with out an error

When I do that I see a usage message and a non-zero return status.
```
$ bazel run :quickstart
INFO: Analyzed target //:quickstart (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:quickstart up-to-date:
  [long-bazel-path-elided]/bin/quickstart
INFO: Elapsed time: 0.383s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: [long-bazel-path-elided]/bin/quickstart
Usage: [long-bazel-path-elided]/bin/quickstart <project-id> <table-name>
$ echo $?
1
```
That is, you have to pass a `<project-id>` and a `<table-name>` to the quickstart binary.  Indeed, the README files says, ...
```
bazel run :quickstart -- [GCP PROJECT ID] [TABLE]
```

> The readme also says run `bazel build ...` however the command is `bazel build //...`

Those two should be equivalent given that you are in a directory with a `WORKSPACE.bazel` file.

**Comment by Yusup-Badiev** [comment]
Sorry the steps to reproduce where not shown correct (they where hidden by md file syntax, I put that step in a code block). But I have figured out my error, it was a segfault caused by a credentials issue but it was not giving any output. It would be nice to have an error that says that though. However I'm gonna close this issue because it was technically user error

**Comment by coryan** [comment]
A segfault sounds bad, whether due to misconfigured credentials or not.  If you can share how to repro I would be interested, we may be able to generate a better error message. Or pass the improvement request to the gRPC team, I think we basically delegate the credential creation to that library.
