### ISSUE TITLE
Converge programmatic credentials story for C++ libraries 

### ISSUE THREAD

**Issue by frankyn** [googleapis/google-cloud-cpp#1161]
At the moment there exists gRPC and Apiary credentials story which breaks causes a break in consistency between providing credentials. 

**Goal**: User can set Google service account credentials programmatically consistently across libraries in this repository while hiding what happens underneath between gRPC and Apiary based libraries.

**Comment by coryan** [comment]
As discussed in the Kickoff Summit, this is a much more difficult endeavor in the C++ world.  There is no universally accepted I/O event loop for C++, so each of the libraries (gRPC, `google::cloud::storage`, the googleapis/google-api-client-cpp) has separate threads and I/O loops to refresh credentials. 

Furthermore, the gRPC credentials are not "usable" outside gRPC, the access token and/or refresh tokens are not accessible via the `grpc;:Credentials` object, it is completely opaque.

So, while this is a good idea, we might need a lot of design work, spread across multiple teams, to make it happen.


/cc: @devjgm FYI.

**Comment by coryan** [comment]
I think we can close this.  All the libraries support the GUAC infrastructure.  There are improvements we could make to the C++ implementation of GUAC, there are other issues to track those improvements.

**Comment by coryan** [comment]
Ooops, still blocked by #6465

**Comment by coryan** [comment]
Still blocked on #6465. It is in our KRs and it is looking good for 2022-Q3.
