### ISSUE TITLE
Move builds from Container Registry to Artifact Registry

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#11638]
We use [Container Registry] to host the docker images.  Container Registry is [deprecated](https://cloud.google.com/container-registry/docs/deprecations/container-registry-deprecation).  We need to move to [Artifact Registry].  There is a [transition guide](https://cloud.google.com/artifact-registry/docs/transition/transition-from-gcr)

[Container Registry]: https://cloud.google.com/container-registry/docs
[Artifact Registry]: https://cloud.google.com/artifact-registry/docs

**Comment by coryan** [comment]
Punt, still need to do this before 2024-05-15.

**Comment by scotthart** [comment]
Migration path allows for redirecting of grc.io so no changes needed in the repository.
