### ISSUE TITLE
curl_multi_wait might erroneously return CURLM_UNRECOVERABLE_POLL

### ISSUE THREAD

**Issue by pitrou** [googleapis/google-cloud-cpp#11647]
In https://github.com/curl/curl/issues/11135 it was determined that `curl_multi_wait` could sometimes return `CURLM_UNRECOVERABLE_POLL` on EINTR, while in most cases it turns EINTR into a success.

It is a plausible cause for a sporadic error that a user [reported](https://github.com/apache/arrow/issues/35318) when using GCS from Arrow C++:
`google::cloud::Status(UNKNOWN: Permanent error ReadObjectNotWrapped: WaitForHandles(): unexpected error code in curl_multi_*, [12]=Unrecoverable error in select/poll)`

**Comment by coryan** [comment]
Thanks for the detailed analysis.  Seems plausible and relatively easy to add a fix (or a workaround).
