### ISSUE TITLE
Fix googleapis_reference_link in documentation for generated protos

### ISSUE THREAD

**Issue by scotthart** [googleapis/google-cloud-cpp#11735]
Generated protos are not part of the googleapis repo. We need to figure out a solution for these locally defined proto files.

**Comment by coryan** [comment]
One option is to directly link the types in the reference documentation for the API.  We would need a new configuration parameter in the generator config that points to the API docs, for example:

https://cloud.google.com/compute/docs/reference/rest/v1

I think we can figure out what is the path to any resource or RPC within that directory.
