### ISSUE TITLE
Support cross-compilation: accept a different protoc binary

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#11779]
For CMake-based builds, when cross-compiling (think "macOS on x64 compiling for ARM", or "Android builds").

The `protobuf::protoc` program found by `find_package(Protobuf ...)` is the program for the *target* environment. This may not be runnable in the *host* environment (where the build is running).  However our build scripts use `$<TARGET_FILE:protobuf::protoc>`:

https://github.com/googleapis/google-cloud-cpp/blob/0c7f077b96f802c0e10f500a3e601b2663bcf353/cmake/CompileProtos.cmake#L105

https://github.com/googleapis/google-cloud-cpp/blob/0c7f077b96f802c0e10f500a3e601b2663bcf353/cmake/CompileProtos.cmake#L116

https://github.com/googleapis/google-cloud-cpp/blob/0c7f077b96f802c0e10f500a3e601b2663bcf353/cmake/CompileProtos.cmake#L203-L204

All of these need to be some  variable that can be configured from the command-line.  It seems that Protobuf >= 23.1 uses `Protobuf_PROTOC_EXECUTABLE`.  Older versions of `find_package(Protobuf)` also use that variable. Seems like a good option.

**Comment by h-vetinari** [comment]
Thanks a lot for this!

> It seems that Protobuf >= 23.1 uses `Protobuf_PROTOC_EXECUTABLE`. Older versions of `find_package(Protobuf)` also use that variable.

`Protobuf_PROTOC_EXECUTABLE` has been around for much longer than 23.x, we've been using it for years. A bit of digging in CMake's history shows that it's [at least](https://github.com/Kitware/CMake/commit/301c038aebcf2fadc9aeaf5f5a9b65eeebe546ef) 13 years old. I guess the naming was taken over when protobuf switched from autotools to CMake itself, much later.
