### ISSUE TITLE
Link C++ client libraries from Cloud Trace documentation

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#11777]
https://cloud.google.com/trace /cpp/docs/reference/trace/latest

**Comment by coryan** [comment]
Cloud Trace does not have a place to put links to the C++ client library.  All the documentation is about integration with exporters for OTel and instrumenting the code.  This requires closer collaboration with the technical writers.

**Comment by dbolduc** [comment]
This is done.

https://cloud.google.com/trace/docs/client-libraries links to https://cloud.google.com/trace/docs/setup/cpp-ot
