### ISSUE TITLE
Decide what to do about client library docs referencing apiary

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#11780]
There are a number of links to client libraries in "Service Infrastructure":

- [ ] https://cloud.google.com/service-infrastructure/docs/service-management/libraries
- [ ] https://cloud.google.com/service-infrastructure/docs/service-control/libraries
- [ ] https://cloud.google.com/service-infrastructure/docs/service-networking/libraries
- [ ] https://cloud.google.com/service-infrastructure/docs/service-consumer-management/libraries
- [ ] https://cloud.google.com/service-usage/docs /cpp/docs/reference/serviceusage/latest
- [ ] https://cloud.google.com/resource-manager/docs /cpp/docs/reference/resourcemanager/latest
- [x] https://cloud.google.com/resource-manager/docs/resource-settings/overview /cpp/docs/reference/resourcesettings/latest

They seem to use apiary libraries.  I wonder if that is intentional, just historical (and never updated), or if we want to update the C++ links.

**Comment by dbolduc** [comment]
`resourcemanager` / `resourcesettings` also link to apiary: https://cloud.google.com/resource-manager/docs/libraries

**Comment by coryan** [comment]
And b/287121340 for service usage

**Comment by coryan** [comment]
This is not actionable, or rather, not something we should be working on.
