### ISSUE TITLE
Generate library for `contentwarehouse.googleapis.com`

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#11815]
The protos are available:

https://github.com/googleapis/googleapis/tree/master/google/cloud/contentwarehouse/v1

But I cannot find the product documentation and/or its state (GA, preview, etc.)

**Comment by jskeet** [comment]
Those protos are for Content Warehouse, not Workload Manager. I don't think the Workload Manager protos have been published.

**Comment by coryan** [comment]
> Those protos are for Content Warehouse, not Workload Manager. I don't think the Workload Manager protos have been published.

Thanks, fixed the bug

**Comment by jskeet** [comment]
Now dupe of #11814?

**Comment by coryan** [comment]
I was about to say that.
