### ISSUE TITLE
Generate library for `clouderrorreporting.googleapis.com` 

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#11833]
No v1/ protos are published:

https://github.com/googleapis/googleapis/tree/master/google/devtools/clouderrorreporting

And the service seems to be GA, but some pages are marked as "beta":

https://cloud.google.com/error-reporting/docs/reference/libraries
https://cloud.google.com/error-reporting/docs/

**Comment by coryan** [comment]
Still no protos without "alpha" or "beta" labels.

**Comment by dbolduc** [comment]
Doubt they will ever publish the protos.
