### ISSUE TITLE
Add Spanner tracing stub

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#11854]
- [x] factor out spanner stub factory
- [x] use generator for spanner stubs
- [x] include tracing stub in stub factory

While I am surely stepping on toes, I could not help myself. This seemed sorta fun. I have done the first three tasks here:

https://github.com/googleapis/google-cloud-cpp/compare/main...dbolduc:spanner-use-generator-full?expand=1

**Comment by devbww** [comment]
For what it's worth, when you generate the Spanner stubs, you can ...
```
  omitted_rpcs: [
    "GetSession",
    "ListSessions",
    "Read"
  ]
```

**Comment by dbolduc** [comment]
This is done. There is an optional refactor tracked in #11888
