### ISSUE TITLE
fix the handling of PartialResultSet.resume_token

### ISSUE THREAD

**Issue by devbww** [googleapis/google-cloud-cpp#11890]
We currently assume that the service only adds a `resume_token` when the `PartialResultSet` ends with a completed row (except when the `PartialResultSet` also completes the stream, in which case the `resume_token` remains empty).

While this appears to be true in practice (and we create a _"PartialResultSetSource reader produced a resume token that is not on a row boundary"_ error when it is not), apparently we should allow for a `resume_token` in an incomplete row, and even in the middle of a `chunked_value`.

See #9359 for more context on the current state.  Internally, see go/cloud-spanner-handling-resume-token.

**Comment by scotthart** [comment]
Will address this when we encounter issues.
