### ISSUE TITLE
Decide whether we should support loading service account credentials from a P12 file

### ISSUE THREAD

**Issue by houglum** [googleapis/google-cloud-cpp#1193]
(Breaking this off from the more general issue in #579)

Other client libraries support loading credentials from .p12 files, but we *strongly* encourage users to use .json keyfiles instead.  However, if we plan to continue to support .p12 files in other languages' Cloud Storage client libraries, we should be consistent with those.

**Comment by coryan** [comment]
@frankyn do you have any thoughts on this? Do we need to support P12 files for GA?

**Comment by coryan** [comment]
Actually, never mind, I figured out how to implement this, I will be sending a PR shortly.
