### ISSUE TITLE
Handle `1xx` HTTP status code

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#12060]
In many places, we write code like:

```cc
StatusOr<T> Foo() {
  ...
  if (IsHttpError(**response)) return AsStatus(std::move(**response));
  ...
}
```

If we receive a `1xx` HTTP status code, `IsHttpError(r) == true`, but `AsStatus(r) == Status()`. Making a `StatusOr<T>` from an OK status is not OK.

https://github.com/googleapis/google-cloud-cpp/blob/7c921d9b19d694b08e9df26edf35121472c4644a/google/cloud/internal/rest_response.cc#L129-L144

I think we need to have: `IsHttpSuccess(r) == AsStatus(r).ok()`.

That means either:
1. `1xx`s should map to `kUnavailable`
2. `kMinSuccess` should be `100`
3. We need a new paradigm for processing `RestResponse`s

I think 1 is the answer. I will send a PR.

---

This is a `cleanup` instead of a `bug`, because comments seem to indicate that we never get `1xx`s in practice.

**Comment by coryan** [comment]
> If we receive a 1xx HTTP status code, IsHttpError(r) == true, but AsStatus(r) == Status(). Making a StatusOr<T> from an OK status is not OK.

You are correct so far.

> 1xxs should map to `kUnavailable`

I think maybe `kUnknown` or `kInternal`... it is a thing that should not happen.  1xx is only valid when the request is in progress, not when the response is starting to arrive.  `AsStatus()` is called in the second case.

**Comment by coryan** [comment]
Closing for now.  It seems the code could better document how and why 100s are not errors, but it is not causing that much trouble.
