### ISSUE TITLE
Expose retry policies used by OpenTelemetry Resource Detector

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#12114]
We have defaults, but as @coryan points out they should be configurable by the application.

Applications not running on GCP will want to disable any retrying. Applications running on GKE may want a long-ish retry policy.

https://github.com/googleapis/google-cloud-cpp/blob/959791f422137385c04c1a39d127b3717f2a88a3/google/cloud/opentelemetry/resource_detector.cc#L27-L31

**Comment by coryan** [comment]
Needs some thinking and a design document.

**Comment by scotthart** [comment]
Closing as we don't have time to work on this at present.
