### ISSUE TITLE
Possible rationalization of RequestTagOption in partitioned operations

### ISSUE THREAD

**Issue by devbww** [googleapis/google-cloud-cpp#12161]
In `Client::PartitionRead(..., Options)` we squirrel away the value of the `RequestTagOption` within the returned `ReadPartition`, which is then preserved by serialization/deserialization, and finally used in the `Client::Read(ReadPartition const&, Options)` call on the possibly-remote machine.  The local `RequestTagOption` in that final call is ignored.

In contrast, `Client::PartitionQuery(..., Options)` ignores the `RequestTagOption`, so its value is not represented in the returned `QueryPartition`.  But, when we call `Client::ExecuteQuery(QueryPartition const&, Options)` on the possibly-remote machine, the local `RequestTagOption` will be used.

This uneven treatment has, at different stages, struck me as both logical and weird.  I recall that I checked that the implementation in another language did the same thing, but it all probably deserves another look.

**Comment by coryan** [comment]
Seems good enough for now.
