### ISSUE TITLE
Expand some libraries missing services

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#12168]
A good engineer would solve the problem once and for all. But in the mean time, let's play some catch up.

https://github.com/googleapis/google-cloud-cpp/blob/main/doc/contributor/howto-guide-adding-generated-libraries.md#expanding-a-library

## Simple.
- [x] google/cloud/channel/v1/reports_service.proto
- [x] google/cloud/dataproc/v1/node_groups.proto
- [x] google/logging/v2/logging_config.proto
- [x] google/logging/v2/logging_metrics.proto
- [x] google/monitoring/v3/snooze_service.proto
- [x] google/cloud/osconfig/v1/osconfig_zonal_service.proto
- [x] google/cloud/resourcemanager/v3/tag_bindings.proto
- [x] google/cloud/resourcemanager/v3/tag_holds.proto
- [x] google/cloud/resourcemanager/v3/tag_keys.proto
- [x] google/cloud/resourcemanager/v3/tag_values.proto
- [x] google/cloud/retail/v2/control_service.proto
- [x] google/cloud/retail/v2/model_service.proto
- [x] google/cloud/retail/v2/serving_config_service.proto
- [x] google/cloud/run/v2/execution.proto
- [x] google/cloud/run/v2/job.proto
- [x] google/cloud/run/v2/task.proto
- [x] google/cloud/speech/v1/cloud_speech_adaptation.proto

## New service directories within existing libraries.
- [x] google/cloud/functions/v2/functions.proto

## Bi-di streaming API. Will require a hand crafted `streaming.cc`.
- [x] ~google/cloud/apigeeconnect/v1/tether.proto~: this API is only used by a Google-provided agent, it does not require client libraries.

## Pre-GA services. We will not generate them.
- [x] ~google/cloud/dataplex/v1/datascans.proto~
- [x] ~google/cloud/texttospeech/v1/cloud_tts_lrs.proto~

## `vN-1` was usurped by `vN`. We will not generate `vN-1`.
- [x] ~google/cloud/resourcemanager/v2/folders.proto~

**Comment by coryan** [comment]
We remembered why  `tether.proto` does not need a library. Closing.
