### ISSUE TITLE
de-dup Spanner logging of streaming-RPC responses

### ISSUE THREAD

**Issue by devbww** [googleapis/google-cloud-cpp#12185]
When Spanner started using generated stubs (see #11854 and #11888) it picked up generic support for streaming-RPC logging via `spanner_internal::SpannerLogging` (when the "rpc" tracing component is enabled), which adds `internal::StreamingReadRpcLogging<google::spanner::v1::PartialResultSet>` (when the "rpc-streams" tracing component is enabled) during `ExecuteStreamingSql()` and `StreamingRead()` RPCs.

However, `spanner_internal::ConnectionImpl` continues to install a `spanner_internal::LoggingResultSetReader` (when the "rpc-streams" tracing component is enabled), which wraps the `spanner_internal::DefaultPartialResultSetReader` interface, during `ReadImpl()` [StreamingRead] and `CommonQueryImpl()` [ExecuteStreamingSql] calls, and that also logs the streaming RPC.

Because the `spanner_internal::PartialResultSetReader` interface is written in terms of the Spanner-specific `PartialResultSet::resume_token`, it can include the token in the logs, and that could be very helpful in debugging. The service-independent `StreamingReadRpcLogging` can't do that.

So, the issues are:
- How can we eliminate the duplicate logging?
- How can we continue to log the resume token?

**Comment by coryan** [comment]
Maybe revisit in the next pass.
