### ISSUE TITLE
Consider implementing a parser for googlea.api.http path syntax

### ISSUE THREAD

**Issue by scotthart** [googleapis/google-cloud-cpp#12196]
Currently, we rely on simple regex and additional parsing to handle the path as no complicated usages of it exist in the googleapis proto repo. 

Grammar: https://github.com/googleapis/googleapis/blob/02aeb715005c633115bc77d563d6920731c98189/google/api/http.proto#L227-L234

**Comment by coryan** [comment]
I think more complicated cases do exist:

https://github.com/googleapis/googleapis/blob/b53aeac1895ce28b78a8295ee6e04187f4268f43/google/firestore/v1/firestore.proto#L66-L68
