### ISSUE TITLE
Consider tracking method comment substitutions

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#12190]
We have a system for tracking whether substitutions that we make on parameter comments from protos are used.

https://github.com/googleapis/google-cloud-cpp/blob/7c4bd275d07df0a8a3652c1bd40038ea5d434818/generator/internal/descriptor_utils.cc#L463-L465

https://github.com/googleapis/google-cloud-cpp/blob/7c4bd275d07df0a8a3652c1bd40038ea5d434818/generator/internal/descriptor_utils.cc#L600

We should consider doing the same thing for substitutions that we make on RPC leading comments.

**Comment by coryan** [comment]
Strike one.
