### ISSUE TITLE
Determine if we can stop emitting request field annotation in Discovery protos

### ISSUE THREAD

**Issue by scotthart** [googleapis/google-cloud-cpp#12204]
Now that `google.api.http` handling has improved and generated protos are correctly populating the `body` field, determine if we still need to continue annotating the same field listed as the value for `body` with `[json_name = "__json_request_body"]`

**Comment by coryan** [comment]
Strike one.

**Comment by scotthart** [comment]
Closing as we don't have time to work on this at present.
