### ISSUE TITLE
URL encode key value pairs in x-goog-request-params

### ISSUE THREAD

**Issue by scotthart** [googleapis/google-cloud-cpp#12232]
Per https://google.aip.dev/client-libraries/4222

This mostly affects the metadata decorators.

---

@dbolduc 's understanding is that we encode the keys and values and leave the `&` and `=` joiners as they are.

We need to:

- [x] URL encode the keys for implicit and explicit routing at code generation time
- [x] URL encode the values for...
  - [x] explicit routing in GAPICs + legacy bigtable + `testing_util::ValidateMetadataFixture`
  - [x] explicit routing -> simple case (that doesn't need a `RoutingMatcher`)
  - [x] implicit routing in GAPICs + `testing_util::ValidateMetadataFixture` ?
  - [x] storage's client side streaming APIs
  - [x] handwritten pubsub client side streaming APIs
  - [x] handwritten minimal IAM stub
  - [x] ~maybe handwritten bigquery v2~, although no requests seem to require routing. :shrug: (none of the requests set the params)
  - [x] ~legacy spanner admin, if we care to~ (We don't care to keep spanner legacy admin classes up to date, since it is legacy and now generated)

**Comment by dbolduc** [comment]
> Do we need to do anything for REST-based clients?

Yeah. Hopefully the work is identical to the gRPC GAPICs

**Comment by alevenberg** [comment]
Looked for `x-goog-request-params` in the handwritten bigquery: `google/cloud/bigquery/v2/minimal`

And none of the 4 decorators (dataset, job, project, or table) set any headers on the context.
