### ISSUE TITLE
chrono fields in bigquery Dataset must be parsed from a string

### ISSUE THREAD

**Issue by sachinpro** [googleapis/google-cloud-cpp#12268]
[Dataset](https://cloud.google.com/bigquery/docs/reference/rest/v2/datasets#Dataset) resource has defaultTableExpirationMs , defaultPartitionExpirationMs, creationTime, lastModifiedTime and maxTimeTravelHours as string, but the code parses them as int64.

**Comment by jsrinnn** [comment]
There are still some code review comments I am addressing so reopening this.
