### ISSUE TITLE
`sccache` server crashes?

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#12274]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/db0bde6d-f5bf-405c-9b8f-7fe2514af04f;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/12272/b8803cb23448d918b3e056686e83556ca90be2bb/demo-debian-buster-demo-install/log-db0bde6d-f5bf-405c-9b8f-7fe2514af04f.txt

Maybe the `sccache` server runs OOM? I am not sure if this should fail the build, though.

```
sccache: warning: The server looks like it shut down unexpectedly, compiling locally instead
```

```
sccache: error: Timed out waiting for server startup. Maybe the remote service is unreachable?
Run with SCCACHE_LOG=debug SCCACHE_NO_DAEMON=1 to get more information
make[2]: *** [google/cloud/osconfig/CMakeFiles/google_cloud_cpp_osconfig.dir/build.make:115: google/cloud/osconfig/CMakeFiles/google_cloud_cpp_osconfig.dir/agentendpoint/v1/internal/agent_endpoint_connection_impl.cc.o] Error 2
make[2]: *** Waiting for unfinished jobs....
[100%] Linking CXX static library libgoogle_cloud_cpp_asset_protos.a
[100%] Built target google_cloud_cpp_asset_protos
make[1]: *** [CMakeFiles/Makefile2:4267: google/cloud/osconfig/CMakeFiles/google_cloud_cpp_osconfig.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Scanning dependencies of target google_cloud_cpp_asset
[100%] Building CXX object google/cloud/asset/CMakeFiles/google_cloud_cpp_asset.dir/v1/asset_client.cc.o
<omitted>
[100%] Built target google_cloud_cpp_asset
make: *** [Makefile:130: all] Error 2
```

**Comment by coryan** [comment]
It is unlikely, however: the sscache daemon could shutdown because it was idle for 10m:

https://github.com/mozilla/sccache/blob/v0.5.4/src/server.rs#L72

or it could be that it terminated gracefully due to some other reason.

**Comment by dbolduc** [comment]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/2ecdc8e1-e5fa-4755-b54a-b2a51d4f1187;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/a97d711971791e1466481606fea63abf58d3e582/fedora-37-cmake-publish-docs/log-2ecdc8e1-e5fa-4755-b54a-b2a51d4f1187.txt

**Comment by dbolduc** [comment]
We haven't seen this in a while. Maybe it is gone, or maybe we are not great at logging. :shrug:
