### ISSUE TITLE
Consider making `OpenTelemetryTracingOption` always available

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#12316]
The option could be made available even when OpenTelemetry is not linked in.  The documentation could use "This option has not effect unless OpenTelemetry is enabled at compile-time".

**Comment by coryan** [comment]
When fixing this, look for locations that can remove `#ifdefs`, e.g.:

https://github.com/googleapis/google-cloud-cpp/pull/12314#discussion_r1284524934

**Comment by dbolduc** [comment]
I did this in #11897
