### ISSUE TITLE
Tracing for OCC Polling Loop APIs

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#12361]
We do not have client level tracing for the full OCC Polling Loop API. Note that we are tracing each `GetIamPolicy()` and `SetIamPolicy()` call, there just isn't a parent span to correlate the full operation.

This task is blocked on #10476, which I have started working on, but it is kind of annoying. It will not make sense to do this task for a while. The juice is not yet worth the squeeze.

**Comment by scotthart** [comment]
Blocked on moving OCC loop to connection layer.
