### ISSUE TITLE
AsyncRetryLoop may not include backoff spans

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#12373]
I think this bug will go away with the cleanups for explicit options, but I am reporting it separately to motivate a search for similar bugs.

The existing unit tests for the asynchronous retry loops set the `OptionsSpan` and this value remains set through the life of the retry loop:

https://github.com/googleapis/google-cloud-cpp/blob/184a3fb7f32d7bf53a8a89efe5e4959c2fe8530c/google/cloud/internal/async_retry_loop_test.cc#L603-L617

Any call to `google::cloud::internal::TracingEnabled()` may return `true` even if the options are not restored during the CQ loop.  In fact, this seems to be the case, as these changes cause the test to fail:

```diff
diff --git a/google/cloud/internal/async_retry_loop_test.cc b/google/cloud/internal/async_retry_loop_test.cc
index f5d260126b..ab4d6e6505 100644
--- a/google/cloud/internal/async_retry_loop_test.cc
+++ b/google/cloud/internal/async_retry_loop_test.cc
@@ -600,16 +600,23 @@ using ::testing::SizeIs;
 TEST(AsyncRetryLoopTest, TracedBackoff) {
   auto span_catcher = testing_util::InstallSpanCatcher();
 
+  AsyncSequencer<bool> sequencer;
   OptionsSpan o(EnableTracing(Options{}));
   AutomaticallyCreatedBackgroundThreads background;
-  (void)AsyncRetryLoop(
+  auto actual = AsyncRetryLoop(
       TestRetryPolicy(), TestBackoffPolicy(), Idempotency::kIdempotent,
       background.cq(),
       [&](auto, auto, auto) {
-        return make_ready_future<StatusOr<int>>(UnavailableError("try again"));
+        return sequencer.PushBack().then(
+            [](auto) { return StatusOr<int>(UnavailableError("try again")); });
       },
-      42, "error message")
-      .get();
+      42, "error message");
+
+  OptionsSpan overlay(Options{});
+  for (auto i = 0; i != kMaxRetries + 1; ++i) {
+    sequencer.PopFront().set_value(true);
+  }
+  EXPECT_THAT(actual.get(), StatusIs(StatusCode::kUnavailable));
 
   auto spans = span_catcher->GetSpans();
   EXPECT_THAT(spans,
```

I will improve the tests as part of the changes to make `Options` explicit, as I think the problem can be fixed in those cases.  

We also may want to survey the other tests looking for similar problems.

**Comment by coryan** [comment]
I think the use of a `Sequencer` in my change does not reproduce the behavior on the even loop with a real asynchronous call.  The latter would be satisfied in the CompletionQueue event loop and have the right `OptionsSpan`.

**Comment by dbolduc** [comment]
> I think the use of a `Sequencer` in my change does not reproduce the behavior on the event loop with a real asynchronous call. The latter would be satisfied in the CompletionQueue event loop and have the right `OptionsSpan`.

Yes. So I don't think this is a bug.
