### ISSUE TITLE
Unable to build from source / Incorrect instructions in `google/cloud/datastore/quickstart/README.md`

### ISSUE THREAD

**Issue by lrnq** [googleapis/google-cloud-cpp#12438]
**Does this issue affect the google-cloud-cpp project?** Yes

**What component of `google-cloud-cpp` is this related to?** datastore i.e in `google/cloud/datastore`.

**Describe the bug** Incorrect instructions in quickstart/README.md for Datastore API.

**To Reproduce** Steps to reproduce the behavior:
Using Bazel. 
1. 
```
cd $HOME/google-cloud-cpp/google/cloud/datastore/quickstart
bazel build ...
```

Yields the following output:

```
Starting local Bazel server and connecting to it...
ERROR: /home/nichlasr/google-cloud-cpp/google/cloud/datastore/quickstart/BUILD.bazel:17:10: no such target '@google_cloud_cpp//:datastore': target 'datastore' not declared in package '' defined by /home/nichlasr/.cache/bazel/_bazel_nichlasr/643045418c5ef5685d10acec40604d31/external/google_cloud_cpp/BUILD.bazel (did you mean 'metastore'? Tip: use `query "@google_cloud_cpp//:*"` to see all the targets in that package) and referenced by '//:quickstart'
ERROR: Analysis of target '//:quickstart' failed; build aborted: Analysis failed
INFO: Elapsed time: 5.008s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (37 packages loaded, 199 targets configured)
```

Using CMake (I guess [vcpkg](https://github.com/Microsoft/vcpkg.git)):
1. 
```
cd $HOME/vcpkg
./vcpkg install google-cloud-cpp[core,datastore]
```

Yields the following:

```
google-cloud-cpp has no feature named datastore.
note: updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.
```

**Expected behavior** I expect the instructions to run successfully.

**Operating system:** If you are using a Linux distribution please include the
name and version of the distribution too.

**What compiler and version are you using?** 
```
$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/11/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 11.4.0-1ubuntu1~22.04' --with-bugurl=file:///usr/share/doc/gcc-11/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-11 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-11-XeT9lY/gcc-11-11.4.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-11-XeT9lY/gcc-11-11.4.0/debian/tmp-gcn/usr --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04)
```

**What version of `google-cloud-cpp` are you using?** 
```
$ git rev-parse HEAD
56b220f745dc6d4ebbe6cb70ec2a9ed4242c41b4
```

**Additional context** 
The fact that the CMake instructions (vcpkg command) fail is not surprising given that https://github.com/googleapis/google-cloud-cpp/pull/12322 was after the latest release.

**Comment by dbolduc** [comment]
Hey, thanks for the detailed bug. You are right about everything, including the fact that the build instructions do not work until `datastore` is included in a release.

# Bazel

Bazel is fetching the latest `google-cloud-cpp` from GitHub. The quickest workaround is to build the code from outside of the quickstart directory. (The difference is which `WORKSPACE` file is being used)

```
cd google-cloud-cpp
bazel build //google/cloud/datastore/quickstart/...
```

Another alternative is to use [`--override_repository`](https://bazel.build/reference/command-line-reference#flag--override_repository). We can point it to our local copy of the repo.

```
# e.g. if your copy of the repo is in ${HOME}/my-code/google-cloud-cpp
cd my-code/google-cloud-cpp/google/cloud/datastore/quickstart
bazel build --override_repository=google_cloud_cpp=~/my-code/google-cloud-cpp ...
```

# vcpkg

This would be annoying to patch. I think you would just have to wait until we release `datastore` and update our port to include the feature.

---

Your overarching point still stands that the quickstart documentation will not work prior to a release. I will think about how to communicate that better.

Thanks again for the bug.

**Comment by lrnq** [comment]
Thanks for the prompt response @dbolduc. The suggested workarounds works. I will close this issue.
