### ISSUE TITLE
OTel Resource attributes should only be set on root span

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#12450]
@alevenberg points out that the resource labels are redundantly added to each span in a trace. They only need to be added to the root span.

These resource labels can cause clutter. Also, Cloud Trace has limits on the number of attributes per span. So that gives us extra reason to avoid repeating them unnecessarily.

---

As for implementation, if OTel calls `Recordable::SetIdentity(...)` before `Recordable::SetResource(...)`, then it might only take a line or two of code.

Otherwise, we will need to refactor to store attributes in an auxiliary data struct (i.e. not the proto), and only create the proto when needed at export time. This could take some work... but it is probably a good idea to do anyways.

**Comment by coryan** [comment]
What happens if the root span is a remote span? That is, if the application is a server that receives a request with OTel tracing information and then using a client library to make other requests?

**Comment by scotthart** [comment]
We're happy with current implementation for now, although there is at least one corner case not handled.
