### ISSUE TITLE
Simplify CMake dependency management.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#1248]
### Overview

The configuration of dependencies for CMake is getting out of control, we need to simply it.  I am going to propose that we support only two configurations:

- `external`: all the dependencies are compiled from source, obtained using `ExternalProject`. This would be the preferred build configuration, we would use this most of the time ourselves.  It is the same approach we use for the Bazel builds.
- `package`: all the dependencies are assumed to be installed and discovered using `find_package()`.  This would work for both `vcpkg`-based builds and builds that install `google-cloud-cpp`.

#### New external dependencies

We would need to introduce `external` packages for some of our current dependencies:

- `libcurl` is currently supported only as a `find_package()` module.
- `OpenSSL` (or more likely `BoringSSL`) is needed by `libcurl`, `gRPC` and `google/cloud/storage`.
- `zlib` is needed by `libcurl` and `protobuf`.

#### Simplify configuration

We should introduce a single configuration option `GOOGLE_CLOUD_CPP_DEPENDENCY_PROVIDER` that sets the source for all the modules.

#### Handling Differences

Some dependencies create different targets when compiled using `ExternalProject` vs. discovered via `find_package`.  For example, `googletest` creates `GTest::gtest_main` when compiled from source, but the CMake module creates `GTest::Main`.  We will create aliases for such cases and prefer the names created by the `ExternalProject`.

Sometimes the results of using `vcpkg + find_package()` vs. `find_package()` on a Linux installation are slightly different.  In those cases we will normalize the targets created by `vcpkg + find_package()` to be the same results as `ExternalProject`.  Again, googletest is the main culprit on this area.

#### Exceptions

OpenSSL is very hard to manage and an `ExternalProject`, it does not have a CMake file, and in fact requires Perl to compile.  BoringSSL cannot be installed, so it is not usable as an external project.  We propose to keep using OpenSSL as an external dependency.

### Alternatives Considered

**Do nothing:** we already have too many configurations we do not test, this is not viable.

**Only Support one of the configurations:** this is not tenable, both `package` and `external` are needed because:
* Supporting `find_package()` is good hygiene, it is a necessary configuration to support any package manager, and it is expected that some of our users will require it.
* Supporting `ExternalProject` makes it easier to start using the library (nothing to install before you try it), it makes it easier to develop, and makes the CMake and Bazel build more homogeneous.

**What happened to pkg-config:** sometimes the OS does not install the CMake configuration files and the only way to discover the dependencies is to use `pkg-config(1)`.  We have "supported" pkg-config builds in the past, but they are not tested and are very brittle.

**Comment by coryan** [comment]
@houglum @frankyn @mbrukman please take a look and let me know if it sounds crazy.

**Comment by houglum** [comment]
If it vastly simplifies dependency management, that's a huge plus for maintainability.  From a developer standpoint, this gets +1 from me.

I admittedly don't have enough experience with various "real-world" build systems/scenarios (read: non-Bazel) to determine whether or not this might be annoying for users though -- offhand, I can't think of any reasons users might want to support mixed dependency configurations, but that doesn't mean such reasons don't exist :)

**Comment by ras0219-msft** [comment]
@coryan We'd generally prefer vcpkg + find_package() to give the same results as `find_package()` (unless find_package() is horrifyingly broken ;)). Could you go into a bit more detail about the gtest issue?

**Comment by coryan** [comment]
@ras0219-msft  the problem is not with `vcpkg` is how we use it (or abuse it maybe?).  In any case, 
x created #1300 to track this specific issue.  Let's discuss further there if you want to.

**Comment by frankyn** [comment]
> ### Overview
> 
> The configuration of dependencies for CMake is getting out of control, we need to simply it.  I am going to propose that we support only two configurations:
> 
> - `external`: all the dependencies are compiled from source, obtained using `ExternalProject`. This would be the preferred build configuration, we would use this most of the time ourselves.  It is the same approach we use for the Bazel builds.
> - `package`: all the dependencies are assumed to be installed and discovered using `find_package()`.  This would work for both `vcpkg`-based builds and builds that install `google-cloud-cpp`.

Question: For `external` dependencies, will CMake compile and install these libraries or is the user expected to still install these? My current guess, given `it is the same approach we use for the Bazel builds` a user will not need to install them.

> #### Simplify configuration
> 
> We should introduce a single configuration option `GOOGLE_CLOUD_CPP_DEPENDENCY_PROVIDER` that sets the source for all the modules.

Will this environment variable act similar to `LD_LIBRARY_PATH`? If not, could add an example?

> ### Alternatives Considered
> **Only Support one of the configurations:** supporting `find_package()` is good hygiene, it is a necessary configuration to support any package manager, and it is expected that some of our users will require it.  Supporting `ExternalProject` makes it easier to start using the library (nothing to install before you try it), it makes it easier to develop, and makes the CMake and Bazel build more homogenous.
> 

w.r.t this alternative, does the following line act as a pro when choosing this option or comparison with the proposed? 

> Supporting `ExternalProject` makes it easier to start using the library (nothing to install before you try it), it makes it easier to develop, and makes the CMake and Bazel build more homogenous.

**Comment by coryan** [comment]
> Question: For external dependencies, will CMake compile and install these libraries or is the user expected to still install these?

CMake will download and compile the libraries. They are not "installed", at least not in the sense that they are on a well-known location (such as `/usr/local`).

> Will this environment variable act similar to LD_LIBRARY_PATH? If not, could add an example?

It is a configuration option for CMake, not an environment variable.  You would use it like any other configuration option:

```
cmake -H. -Bbuild-output -DGOOGLE_CLOUD_CPP_DEPENDENCY_PROVIDER=package
```

> w.r.t this alternative, does the following line act as a pro when choosing this option or comparison with the proposed?

> > Supporting ExternalProject makes it easier to start using the library (nothing to install before you try it), it makes it easier to develop, and makes the CMake and Bazel build more homogenous.

Yes, that is a pro.

**Comment by frankyn** [comment]
Thanks for clarifying @coryan. 

I like alternative _Only Support one of the configurations_, but it reads more as a follow-up to having `package` and `external` which can be used to eventually unify the two.

Either sounds good to me.

**Comment by frankyn** [comment]
Ah, okay! Then the proposed solution of using `package` and `external` sgtm! Thanks for further clarifying!

**Comment by ras0219-msft** [comment]
@coryan Would a vcpkg integration style that acts like `ExternalProject` be useful to you?

**Comment by coryan** [comment]
@ras0219-msft Maybe?

I prefer to minimize the number of tools my customers have to install before they try out the library.

With the current proposal they can (in the vast majority of cases) just say `cmake -H. -Bfoo && cmake --build foo` and everything gets downloaded and compiled for them.

Do you think we could have a mode where the user just types `cmake -H. -Bfoo && cmake --build foo` and that magically downloads `vcpkg`, compiles `vcpkg`, compiles all the other dependencies using `vcpkg`, and then compiles the libraries?  That would be truly awesome because I would have to maintain less code.

**Comment by ras0219-msft** [comment]
Yes, that second case is what I meant :)

**Comment by coryan** [comment]
@ras0219-msft that level of magic sounds really cool, yes we would definitely be interested in it.
