### ISSUE TITLE
Ensure that our unit tests that depend on proto libraries have them available.

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#12485]
Circa 2023-08-28, a lot of our sharded CI builds are failing because many gRPC unit tests depend on `bigtable_protos` and `iam_protos`. (and we recently stopped compiling `bigtable_protos` by default).

There are several approaches to fix this.

Ideally we remove our dependence on the bigtable and iam protos altogether.

Or slightly worse, we could only add the tests that require bigtable protos iff bigtable is enabled in the CI build.

Or as a temporary measure, we can just enable bigtable in gRPC testing builds.

**Comment by coryan** [comment]
Closing.  The test runs fine, and the extra dependency is not that painful.
