### ISSUE TITLE
Address missing header clang tidy IWYU complaints in google3

### ISSUE THREAD

**Issue by alevenberg** [googleapis/google-cloud-cpp#12533]
For context: cl/561321859

**Comment by coryan** [comment]
FWIW, we can't get these warnings with Fedora:37 (the distro we use for clang-tidy builds).  And we won't get these IWYU warnings with Fedora:38.  We will get them with Fedora:39. That typically comes out in October or November.

---

As usual, I find these to be nearly useless.  Removing unused headers is useful.  Adding "missing" headers is not.  The supposed benefits for refactoring to not really accrue in OSS land.

To me, it seems that IWYU makes me spend more time adding headers just in case than doing helpful things.  But I am outvoted, and I will gladly approve PRs to fix these things.  I will also accept comments to add "missing" headers when pointed out to me by humans or robots.

**Comment by alevenberg** [comment]
> As usual, I find these to be nearly useless. Removing unused headers is useful. Adding "missing" headers is not. The supposed benefits for refactoring to not really accrue in OSS land. 

I think with our current build system (more specifically, how our targets contain multiple files instead of having a target per class) these changes are useless. 

In general, there are [benefits](https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/WhyIWYU.md) to IWYU from a development perspective. 

In my ideal world, we would list out all dependencies explicitly in the build rules and with the headers so it was more google3 compatible. So on the import to google3 we could mostly re-use the BUILD.bazel files and apply some copybara transforms and then run build cleaner on everything.

**Comment by devbww** [comment]
Helpful or not for future refactoring, muffling the warnings should be our primary goal.

**Comment by dbolduc** [comment]
We will let upkeep track this.
