### ISSUE TITLE
Use service YAML to get the product documentation link

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#12630]
The scaffold generator guesses the product documentation link using:

https://github.com/googleapis/google-cloud-cpp/blob/43cd3d9a65df32310bca8d8878ee322d73493a03/generator/internal/scaffold_generator.cc#L92-L96

But we also have a better source in:

https://github.com/googleapis/google-cloud-cpp/blob/43cd3d9a65df32310bca8d8878ee322d73493a03/generator/internal/scaffold_generator.cc#L265

We should switch to using that source when available.

**Comment by scotthart** [comment]
Still want to do this.
