### ISSUE TITLE
Change default quickstart to use project + location

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#12631]
The scaffold generator assumes most services have a `List*` operation that just consumes a project.  This is less and less true in GCP, most services need a project and location (typically a region).  We should change this:

https://github.com/googleapis/google-cloud-cpp/blob/43cd3d9a65df32310bca8d8878ee322d73493a03/generator/internal/scaffold_generator.cc#L943-L952

To assume that is the case.  Maybe add a helper `google::cloud::Location` class.

Likewise, the scaffold generator can assume this is the case in:

https://github.com/googleapis/google-cloud-cpp/blob/43cd3d9a65df32310bca8d8878ee322d73493a03/generator/internal/scaffold_generator.cc#L474-L477

And remove the `EDIT HERE` comment from the CMakeLists.txt file.

**Comment by devbww** [comment]
Some remaining automation work here is to try to guess an appropriate `ListFoo()` call, and eliminate the remaining _"EDIT HERE"_ markers.

**Comment by coryan** [comment]
> Some remaining automation work here is to try to guess an appropriate `ListFoo()` call, and eliminate the remaining _"EDIT HERE"_ markers.

That is the work in #12632 I think @devbww  fixed this bug.
