### ISSUE TITLE
Cleanup span attributes set after span creation

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#12778]
In general, if an attribute is known at span creation time, we should use it to initialize the span. e.g.

https://github.com/googleapis/google-cloud-cpp/blob/898b7c38c6d983d1026b78b1e1dd83218d77498f/google/cloud/pubsub/internal/flow_controlled_publisher_tracing_connection.cc#L40-L42

We probably need to generalize our interfaces to support this.

**Comment by alevenberg** [comment]
Tried to get a wrapper function working, but for some reason it is not creating a span when I can the OTel StartSpan function (https://github.com/alevenberg/google-cloud-cpp/pull/1/files)

**Comment by alevenberg** [comment]
- [ ] write wrapper ([issue](https://github.com/googleapis/google-cloud-cpp/compare/main...alevenberg:google-cloud-cpp:issue-12778))
- [ ] replace flow control and batch spans with wrapper
