### ISSUE TITLE
Guidance Needed: Voice Activity Detection and Timeout Handling

### ISSUE THREAD

**Issue by Nullarity** [googleapis/google-cloud-cpp#12879]
Hi there,
I'm trying to detect absence of voice activity. For testing, I took the following code and changed it: https://github.com/GoogleCloudPlatform/cpp-samples/blob/main/speech/api/streaming_transcribe_singlethread.cc

Here are my changes:

```cpp
  private:
    Handler(google::cloud::CompletionQueue cq, ParseResult args)
        : cq_(std::move(cq)), file_(args.path, std::ios::binary) {
      auto& streaming_config = *request_.mutable_streaming_config();
      *streaming_config.mutable_config() = std::move(args.config);

    // My changes started here
    streaming_config.set_single_utterance ( true );
    streaming_config.set_enable_voice_activity_events ( true );
    auto& timeout = *streaming_config.mutable_voice_activity_timeout ();
    auto& duration = *timeout.mutable_speech_start_timeout ();
    duration.set_seconds ( 1 );
    // end of my changes
```

I'm expecting that running this code will cause the transcription process to stop right after the first chunk of data (the file is 10 seconds of silence, and I need to detect speech activity in the first second). Instead, I get the following:

![image](https://github.com/googleapis/google-cloud-cpp/assets/28710693/fde6b088-0e13-41da-b4e7-ddd25327dbef)

I'm pretty sure I'm doing something wrong. Unfortunately, I couldn't find any examples of how to set and handle timeouts. Could you please be so kind as to explain to me how it should work and what I'm doing wrong.

Thank you very much!

[changed streaming_transcribe_singlethread.cc.txt](https://github.com/googleapis/google-cloud-cpp/files/12875309/streaming_transcribe_singlethread.cc.txt)
[10 seconds of silence](https://github.com/googleapis/google-cloud-cpp/files/12875316/silence.wav.zip)

**Comment by coryan** [comment]
I think you are about to find out I am an impostor.  I am only superficially familiar with this service, and do not understand how activity events work in detail.  With that said, the [documentation](https://cloud.google.com/speech-to-text/docs/reference/rpc/google.cloud.speech.v1#google.cloud.speech.v1.StreamingRecognitionConfig) for `voice_activity_timeout` says:

> If set, the server will automatically close the stream after the specified duration has elapsed after the last VOICE_ACTIVITY speech event has been sent. The field voice_activity_events must also be set to true.

If I am reading this correctly, then the service is _supposed_ to close the stream after whatever period of inactivity (1 second in your example).

I realize this may not be what you may want.  It seems you want to get notified of inactivity but continue streaming?  None of the activity events looks relevant:

https://cloud.google.com/speech-to-text/docs/reference/rpc/google.cloud.speech.v1#google.cloud.speech.v1.StreamingRecognizeResponse.SpeechEventType

You may have to implement this on the client.  You could use client-side timeouts that are cancelled when the service detects voice activity (as opposed to the service detecting voice *in*activity).  If that seems useful this is a good place to start:

https://cloud.google.com/cpp/docs/reference/common/latest/classgoogle_1_1cloud_1_1CompletionQueue#classgoogle_1_1cloud_1_1CompletionQueue_1a760d68ec606a03ab8cc80eea8bd965b3
https://cloud.google.com/cpp/docs/reference/common/latest/classgoogle_1_1cloud_1_1CompletionQueue#classgoogle_1_1cloud_1_1CompletionQueue_1ae98eaa1bf1210e6a3773e091e93a730e

Alternatively the [Service Support Page](https://cloud.google.com/speech-to-text/docs/getting-support) links mailing lists, public issue trackers, and stackoverflow tags that may be monitored by folks with more expertise.  Oh, and there is paid support too.

**Comment by Nullarity** [comment]
Thank you for your prompt response.

I agree that if the stream is closed, such a result might be expected. However, I believe the initial chunk of data, approximately 3 seconds, should be adequate to determine the presence of silence. Alas, adjusting the timeout value doesn't seem to affect the outcome.

Nevertheless, I appreciate the resources you provided.

**Comment by coryan** [comment]
> I agree that if the stream is closed, such a result might be expected. However, I believe the initial chunk of data, approximately 3 seconds, should be adequate to determine the presence of silence. Alas, adjusting the timeout value doesn't seem to affect the outcome.

I see your point.  That is definitely a question for the service team.  There may be minimum values or maximum values for the timeouts or other implementation details that I would not be aware of.

**Comment by Nullarity** [comment]
Just for reference: [stackoverflow](https://stackoverflow.com/questions/77277292/guidance-needed-voice-activity-detection-and-timeout-handling-with-cloud-speech)

**Comment by Nullarity** [comment]
```cpp
set_audio_channel_count ( 1 );
```
solved my problem.
