### ISSUE TITLE
Compute instances SDK is not setting `network ip`

### ISSUE THREAD

**Issue by lx3-g** [googleapis/google-cloud-cpp#12870]
**What component of `google-cloud-cpp` is this related to?** 
google/cloud/compute/compute_instances

**Describe the bug** A clear and concise description of what the bug is.

Using any of these methods: 
ListInstances

https://github.com/googleapis/google-cloud-cpp/blob/main/google/cloud/compute/instances/v1/instances_client.h#L1279C58-L1279C71

AggregatedListInstances
https://github.com/googleapis/google-cloud-cpp/blob/main/google/cloud/compute/instances/v1/instances_client.h#L283

GetInstance
https://github.com/googleapis/google-cloud-cpp/blob/main/google/cloud/compute/instances/v1/instances_client.h#L751C67-L752C59

Does not set this field -- network_ip

https://github.com/googleapis/google-cloud-cpp/blob/953aefecd64b3c6ad8e856a0713eae786ad43c29/protos/google/cloud/compute/v1/internal/common_003.proto#L586

when using REST api -- it is set -- 

e.g. "https://compute.googleapis.com/compute/v1/projects/YOUPROJECT/aggregated/instances"

**To Reproduce** Steps to reproduce the behavior:

Call one of the functions above. Observe that the field is never set.

**Expected behavior** A clear and concise description of what you expected to
happen.

The field is set.

**Operating system:**
PRETTY_NAME="Debian GNU/Linux rodete"

**What compiler and version are you using?**

Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-linux-gnu/13/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 13.2.0-4' --with-bugurl=file:///usr/share/doc/gcc-13/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-13 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/libexec --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-13-oyarai/gcc-13-13.2.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-13-oyarai/gcc-13-13.2.0/debian/tmp-gcn/usr --enable-offload-defaulted --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=28
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 13.2.0 (Debian 13.2.0-4)

**What version of google-cloud-cpp are you using?**

https://github.com/googleapis/google-cloud-cpp/archive/v2.16.0.tar.gz

**Comment by coryan** [comment]
We created v2.17.0 last night, marking this as fixed.
