### ISSUE TITLE
Automate the google apis sha

### ISSUE THREAD

**Issue by alevenberg** [googleapis/google-cloud-cpp#13062]
We currently have a [process](https://github.com/googleapis/google-cloud-cpp/blob/main/doc/contributor/howto-guide-update-googleapis-sha.md) to update the google apis sha which is manually performed ~ once a week as an operator task.

I propose adding a GHA to do the same steps that runs weekly.

Right now, I have most of the work done.
- [x] Create GHA trigger
- [x] Set up all the auth for accessing the GHA (it needs permission to create a storage object, delete a storage object- in case it created one earlier, and create a token)
- [ ] Test on a branch on upstream repo (https://github.com/googleapis/google-cloud-cpp/actions/workflows/update-googleapis-sha.yml)
- [ ] Test by making an empty commit on a gha-ci-googleapis branch (so we can trigger at will)
- [ ] Use the bazel cache? (the compilation is pretty slow RN)
- [ ] Squash and merge commits in WIP branch and make a PR for review 
- [ ] Watch for a week and make sure it generates the PR on sunday

Also note, right now we use a service key for auth, but we want to try and use WIF https://github.com/googleapis/google-cloud-cpp/issues/12898

**Comment by alevenberg** [comment]
It's currently taking 2.5h+ to compile the bazel build. I'm gonna need to figure out how to connect it to the cache.

**Comment by coryan** [comment]
> It's currently taking 2.5h+ to compile the bazel build. I'm gonna need to figure out how to connect it to the cache.

You could send a PR from the GHA.  Then the existing builds with the cache will work.

**Comment by alevenberg** [comment]
Ah.... that would be a better idea.

**Comment by alevenberg** [comment]
TODO:

Create a bot account so the CLA can go through
