### ISSUE TITLE
storage: Support custom endpoints for SignURLs 

### ISSUE THREAD

**Issue by BrennaEpp** [googleapis/google-cloud-cpp#13068]
When a custom endpoint is set on the client, Sign URLs and Post Policies should automatically use that domain.

Optional: allow users to set a custom hostname for Sign URL and Post policy methods.

See the following for more information and fill out language section: go/signurl-custom-endpoint-gcs
Please add a comment or ping me if you have any questions.

**Comment by coryan** [comment]
I won't be working on this for a while.  When I start working on this problem I will assign the bug to myself.
