### ISSUE TITLE
Build stops with `Get "https://index.docker.io/v2/": EOF`

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#13113]
This looks similar to #6438, in that Kaniko is trying to make a network operation that gets interrupted or fails.

However, the specific operation seems different, so it probably has a different code path.

https://pantheon.corp.google.com/cloud-build/builds;region=us-east1/77af3865-34a4-4fa8-82d9-185883612f85?e=-13802955&mods=logs_tg_prod&project=cloud-cpp-testing-resources

```
Step #0: error building image: Get "https://index.docker.io/v2/": EOF
Finished Step #0
ERROR
ERROR: build step 0 "gcr.io/kaniko-project/executor:v1.18.0" failed: step exited with non-zero status: 1
Finished Step #7
```

**Comment by dbolduc** [comment]
Closing, Kaniko has been failing, but we haven't seen this error in a while.
