### ISSUE TITLE
Consider supporting "transition" services

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#13211]
Our build scripts have a way to support transition[^1] libraries, but as @coryan points out in https://github.com/googleapis/google-cloud-cpp/pull/13210#discussion_r1410817884 our generated code does not have a way to support transition services.

We use this flag to mark a service as experimental:
https://github.com/googleapis/google-cloud-cpp/blob/b3f5e98149ba0f547c3770d319cdf613be93c3ea/generator/generator_config.proto#L108-L113

We probably need to change that thing to an enum that includes a state for transition.

If a library is in transition then we would define:
```cc
MakeFooConnection(ExperimentalTag, Options const& o) {
  return MakeFooConnection(o);
}
```

[^1]: Transition means going from experimental -> GA.

**Comment by scotthart** [comment]
This would be nice to have if we had more transitional libraries. If we see a resurgence in those, we may want to do this.
