### ISSUE TITLE
generator golden services have same endpoint environment variable

### ISSUE THREAD

**Issue by scotthart** [googleapis/google-cloud-cpp#13229]
Both the GoldenThingAdmin and GoldenKitchenSink services use the same env var GOLDEN_KITCHEN_SINK_ENDPOINT. The env var should match the service name. My first thought was this was an issue because both services are defined in the same .proto file. However, Bigquery storage also has two services defined in the same .proto file, but does not suffer from this problem.

**Comment by scotthart** [comment]
Investigate different behavior between golden services and BigQuery and decide if any further action is needed.

**Comment by dbolduc** [comment]
We explicitly override the endpoint env var, so this is WAI.

https://github.com/googleapis/google-cloud-cpp/blob/d7f7fa99f024a3aea02efc5a3b44e55dc2032bb2/generator/integration_tests/golden_config.textproto#L28
