### ISSUE TITLE
generator should handle references to well-known protos

### ISSUE THREAD

**Issue by devbww** [googleapis/google-cloud-cpp#13255]
In https://github.com/googleapis/google-cloud-cpp/pull/13248#discussion_r1418940372 @coryan wrote ...

I think @googleapis_reference_link{} does not work for well-known protos. It will expand to:

https://github.com/googleapis/google-cloud-cpp/blob/6203e23223c5093aee647284fbbc08744a27b02d/cmake/GoogleapisConfig.cmake#L36

And the file does not exist in the googleapis/googleapis repository:

https://github.com/googleapis/googleapis/tree/master/google/protobuf

We should make the ResolveCommentReferences() function do something clever for well-known protos.

**Comment by devbww** [comment]
For what it's worth, these are names from comment links that the generator currently fails to resolve:
- google.bigtable.admin.RestoreTableMetadata
- google.cloud.aiplatform.v1.DeployedModel
- google.cloud.aiplatform.v1.DeployedModel.explanation_spec
- google.cloud.aiplatform.v1.DeployedModel.model
- google.cloud.aiplatform.v1.Endpoint
- google.cloud.aiplatform.v1.Endpoint.deployed_models
- google.cloud.aiplatform.v1.Endpoint.traffic_split
- google.cloud.aiplatform.v1.Model
- google.cloud.aiplatform.v1.Model.predict_schemata
- google.cloud.aiplatform.v1.PredictSchemata.instance_schema_uri
- google.cloud.aiplatform.v1.PredictSchemata.parameters_schema_uri
- google.cloud.automl.v1p1beta.ImageObjectDetectionModelDeploymentMetadata.node_number
- google.cloud.channel.v1.SubscriberEvent
- google.cloud.commerce.consumer.procurement.v1.OrderState.ORDER_STATE_ACTIVE
- google.cloud.datacatalog.v1.DumpItem
- google.cloud.dialogflow.cx.v3.Agent
- google.cloud.dialogflow.cx.v3.Environment
- google.cloud.dialogflow.v2.Participants.AnalyzeContent
- google.cloud.dialogflow.v2.Participants.StreamingAnalyzeContent
- google.cloud.discoveryengine.v1.DataStore
- google.cloud.documentai.v1.HumanReviewConfig
- google.cloud.kms.v1.CryptoKey
- google.cloud.location.Locations.ListLocations
- google.cloud.retail.v2.Catalog
- google.cloud.retail.v2.ProductService.GetProduct
- google.cloud.retail.v2.ProductService.ListProducts
- google.cloud.retail.v2.SearchRequest.branch
- google.cloud.retail.v2.SearchService.Search
- google.cloud.workflows.v1.Workflow
- google.rpc.Code.ALREADY_EXISTS
- google.rpc.Code.INVALID_ARGUMENT
- google.rpc.Code.NOT_FOUND

We should probably look into those too.

**Comment by dbolduc** [comment]
> google.bigtable.admin.RestoreTableMetadata

I sent a CL to fix this one upstream.

**Comment by scotthart** [comment]
Don't have time to work on this at present.
