### ISSUE TITLE
Capture Bigtable cluster zone, ID from trailers and include in traces

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#13253]
Bigtable returns a trailer: `x-goog-ext-425905942-bin`, which is the following proto encoded:

```proto
message RequestParams {
  optional string cluster_zone = 1;
  optional string cluster_id = 2;
}
```

This is the sort of information that would be good to capture in a trace.

This may prove difficult because tracing stubs are fully generated, and there is a custom scheme to interpret the binary trailer value.

**Comment by scotthart** [comment]
When we implement metrics for Bigtable this will be applicable.
