### ISSUE TITLE
Update MakeConnection and stub creation functions to use Options modified by stub creation functions instead of just a copy of the Options provided (Bigtable).

### ISSUE THREAD

**Issue by scotthart** [googleapis/google-cloud-cpp#13272]

**Comment by dbolduc** [comment]
This is not a thing for bigtable. Changing the signature of the function that creates the stub from `Options const&` -> `Options&` gives this to us for free.

https://github.com/googleapis/google-cloud-cpp/blob/f4b0970daed8b31d749cff060cb40fa639115180/google/cloud/bigtable/data_connection.cc#L163-L172
