### ISSUE TITLE
run snapshot_async_integration_test against emulator.

### ISSUE THREAD

**Issue by manish-qlogic** [googleapis/google-cloud-cpp#1338]
Emulator crashes during integration tests for snapshot_async_integration_test,.cc It crashes during ListSnapshots call, 

snapshot_async_integration_test must run against emulator after the bugs in emulator is fixed. 

Opening issue for tracking purpose.

**Comment by coryan** [comment]
Snapshots are being deprecated / decommissioned by Cloud Bigtable, there is no need to implement any features about them.
