### ISSUE TITLE
BUILD file not found in directory 'google/cloud/kms/inventory/v1' of external repository @com_google_googleapis.

### ISSUE THREAD

**Issue by mdetemad** [googleapis/google-cloud-cpp#13408]
**Does this issue affect the google-cloud-cpp project?** If the problem is with
the Google Cloud service exposed by the `google-cloud-cpp` libraries instead of
the client libraries themselves, you may consider opening a support request
instead. The `google-cloud-cpp` developers cannot help you troubleshoot problems
with the service itself.

Yes

**What component of `google-cloud-cpp` is this related to?** For example, is
this related to bigtable (i.e., something in `google/cloud/bigtable`), or GCS
(i.e., something in `google/cloud/storage`)?

KMS

**Describe the bug** A clear and concise description of what the bug is.

I am using KMS in a project and getting the following error:
no such package '@com_google_googleapis//google/cloud/kms/inventory/v1': BUILD file not found in directory 'google/cloud/kms/inventory/v1' of external repository @com_google_googleapis. Add a BUILD file to a directory to mark it as a package. and referenced by '@google_cloud_cpp//google/cloud/kms:google_cloud_cpp_kms'

**To Reproduce** Steps to reproduce the behavior:

1. Add "@com_google_googleapis//google/cloud/kms/v1:kms_cc_grpc" to the BUILD.bazel file.
1. Build it.

**Expected behavior** A clear and concise description of what you expected to
happen.

**Operating system:** If you are using a Linux distribution please include the
name and version of the distribution too.

I see this error for both MacOs and Ubuntu.

**What compiler and version are you using?** Please include the output of
`g++ -v` or `clang++ -v` or the equivalent command-line flag.

**What version of `google-cloud-cpp` are you using?** Please include the output
from `git rev-parse HEAD` if you are compiling from source, or the version
number from the applicable `google/cloud/*/version.h` file.

**Additional context** Add any other context about the problem here.

**Comment by coryan** [comment]
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Add "@com_google_googleapis//google/cloud/kms/v1:kms_cc_grpc" to the BUILD.bazel file.
> 2. Build it.

I think you want `"@com_google_googleapis//google/cloud/kms/inventory/v1:inventory_cc_grpc"`, this is defined in:

https://github.com/googleapis/googleapis/blob/3aa1ca18a5abb7a1cf00895600a67b45e8b3b47e/google/cloud/kms/inventory/v1/BUILD.bazel#L389-L394

**Comment by coryan** [comment]
I am wrong.  That is not the problem you are reporting.

**Comment by coryan** [comment]
I am able to build a small project with Bazel.  Maybe you can take a moment to see what I did and tell me how it is different from what you are trying?  I am using  `kms` quickstart as my repro attempt:

https://github.com/googleapis/google-cloud-cpp/blob/main/google/cloud/kms/quickstart/README.md

```shell
cp -r $HOME/google-cloud-cpp/google/cloud/kms/quickstart repro-13408
cd repro-13408
USE_BAZEL_VERSION=6.4.0 bazel build :quickstart
```

That compiles cleanly, and I am even able to run it:

```shell
USE_BAZEL_VERSION=6.4.0 bazel build -- :quickstart ${GOOGLE_CLOUD_PROJECT} us-central1
```

Thoughts?

**Comment by coryan** [comment]
@mdetemad per our discussion over chat, it looks like your WORKSPACE file is using an older version of `googleapis/googleapis`.  Please consider using the same version as `google-cloud-cpp`.
