### ISSUE TITLE
Support self-signed JWT service account credentials (but not OAuth tokens).

### ISSUE THREAD

**Issue by scotthart** [googleapis/google-cloud-cpp#13439]

**Comment by coryan** [comment]
FWIW, we already use self-signed JWTs:

https://github.com/googleapis/google-cloud-cpp/blob/86c87b984589fc6767ee92c0918d7e13fab30caa/google/cloud/storage/oauth2/service_account_credentials.cc#L107-L112

and in most cases this is the default:

https://github.com/googleapis/google-cloud-cpp/blob/86c87b984589fc6767ee92c0918d7e13fab30caa/google/cloud/internal/oauth2_service_account_credentials.cc#L209-L213
