### ISSUE TITLE
Implement futures and promises with continuations.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#1345]
Basically these should be an implementation of:

http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/p0159r0.html

**Comment by coryan** [comment]
Woo hoo!  This compiles and passes now:

https://github.com/coryan/google-cloud-cpp/blob/9aafe2e0ceb616c7d2f0cb00155294cfcf8d32db/google/cloud/internal/future_generic_then_test.cc#L83

@dopiera @deepankarsharma @houglum @frankyn  in case they wonder where all this template nonsense is headed.

**Comment by deepankarsharma** [comment]
@coryan - This addresses the recent emptiness in my life of not having enough templates :)
