### ISSUE TITLE
ETOOMUCHMAGIC for `SHARED_PROTO_DEPS`

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#13647]
## TL;DR;

Automatically compiling the `SHARED_PROTO_DEPS` makes it harder to shard the build when packaging `google-cloud-cpp`.

Consider a way to manually control what shard builds the protos in `SHARED_PROTO_DEPS`. Maybe by making these protos into specific features (`__shared_protos__`?) Or maybe by disabling the magic so the package maintainer has to decide what shard builds what.

## Background

https://github.com/conda-forge/google-cloud-cpp-feedstock/pull/165#issuecomment-1959527934

**Comment by scotthart** [comment]
Not going to pursue this.
