### ISSUE TITLE
Find a workaround for the enums in `securitycenter`

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#13666]
In #13664 I disabled `securitycenter` for macOS and Windows.  A better workaround might be to fix the service to not use enums (seems like a long shot).  Or fix Protobuf to support `#undef` the offending macros.  Or start using C++20 modules (ha ha, only serious).

**Comment by scotthart** [comment]
May require working with protobuf to update the ports_def.inc and ports_undef.inc.

**Comment by scotthart** [comment]
fixed by #14282
