### ISSUE TITLE
Test with all gRPC Credential classes.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#137]
Currently both `bigtable::AdminClient` and `bigtable::Client` use `grpc::GoogleDefaultCredentials`, or `grpc::InsecureChannelCredentials` if taking to the Cloud Bigtable emulator.

We need to support any sort of credentials, this means that the credentials should be a parameter, or set via a policy.  Most likely the latter, because some credential types (notably oauth credentials) require a periodic refresh (see `GoogleRefreshTokenCredentials` in the [docs](https://grpc.io/grpc/cpp/namespacegrpc.html))

One of the problems is to refresh the credentials automatically, not hard if we have an async client, or if we are willing to keep an extra thread to perform the task.

**Comment by coryan** [comment]
@sduskis I will use this bug to track the issue with supporting other credential types, including the ones that need refreshing.

**Comment by coryan** [comment]
This comment is just to record what I have discovered so far.  It may seem obvious to folks with more experience with web authentication, but some of us do not know anything about web authentication (e.g., me!), so it might be useful.

### Connecting to the Cloud Bigtable Emulator

If you are running against the [Cloud Bigtable Emulator](https://github.com/GoogleCloudPlatform/google-cloud-go/tree/master/bigtable/cmd/emulator) you really do not need (or want) authentication, so we need to use `grpc::InsecureChannelCredentials`.

The `bigtable::*Client` classes already take care of that.

### Connecting to Cloud Bigtable with a Service Account

Here, you may want to read the general [intro](https://grpc.io/docs/guides/auth.html) to authentication in gRPC.  My interpretation of this document is that basically `grpc::GoogleDefaultCredentials` works great **if** you are using a service account to access Cloud Bigtable.  There are two sub-cases:

* If you are running in GCE or GAE, the VM will have all the configuration you need to run with that service account.
* If you are running outside GCE or GAE, you need to download the private keys of that service account to a file, and set the `GOOGLE_APPLICATION_CREDENTIALS` to the path of that file
    *  There is a twist if gRPC is not installed on your machine (e.g., if you are linking statically or running from the build), documented in #38.

### Connecting to Cloud Bigtable with an OAuth 2.0 Token

That leaves basically one other case: you are running an application that cannot use a service account, for example, some kind of proxy that will access Cloud Bigtable on behalf of multiple users.  I really cannot tell how common this is, but seems like something we need to support.

In this case you may want to start with the [general documentation](https://developers.google.com/identity/protocols/OAuth2) about using OAuth 2.0 with googleapis.

I expect [this tool](https://github.com/google/oauth2l) to be useful in this case.  It can create an access (and refresh?) token for you.  It needs the scopes for Cloud Bigtable, which can be found here:

https://github.com/googleapis/googleapis/blob/master/google/bigtable/bigtable.yaml
https://github.com/googleapis/googleapis/blob/master/google/bigtable/admin/bigtableadmin.yaml

The workflow is to obtain a refresh token using the browser (who is supposed to ask the client "do you want to use <application foo> to access Cloud Bigtable).  The application uses the refresh token to get access tokens, the refresh tokens are supposed to be kept secret but last longer than access tokens.  The access tokens is what we need to pass to `grpc::AccessTokenCredentials`.  The refresh tokens are what we pass to `grpc::RefreshTokenCredentials`.

### Connecting to Cloud Bigtable with SSL Authentication

TODO - fill out this section.  I need to find out if google apis would even accept a connection authenticated by SSL on the client-side.  My guess is not.

### Connecting to Cloud Bigtable with Cronet

TODO - fill out this section.  Not clear how this is used, maybe from a Chromium or Android project?

https://chromium.googlesource.com/chromium/src/+/master/components/cronet?autodive=0%2F%2F

**Comment by coryan** [comment]
Here is a relevant bit of info about how to refresh credentials:

https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/master/bigtable-client-core-parent/bigtable-client-core/src/main/java/com/google/cloud/bigtable/grpc/io/RefreshingOAuth2CredentialsInterceptor.java

**Comment by coryan** [comment]
cc: @sduskis I had completely forgotten about this one.  I believe this should just work right out of the box, we just use the gRPC classes for Credentials.  But somebody should check, maybe write a couple of tests.

**Comment by coryan** [comment]
To document the discussion we had today, this is the reference page for gRPC:

https://grpc.io/grpc/cpp/namespacegrpc.html

This lists a number of functions to create `ChannelCredentials` and `CallCredentials`, we want to make sure the client library works with all the relevant ones.  In particular:

### In Scope: ChannelCredentials

- [ ] `GoogleDefaultCredentials` should work on GCE and on a regular workstation where the customer has configured `GOOGLE_APPLICATION_DEFAULT_CREDENTIALS` as described in [the GCP auth guide](https://cloud.google.com/docs/authentication/production).  We have tested this extensively already.

### In Scope: CallCredentials

- [ ] `gprc::GoogleComputeEngineCredentials` should work on GCE. To test these we should combine a `ChannelCredentials` (such as `gpc::GoogleDefaultCredentials()`) using `grpc::CompositeChannelCredentials()`)

- [ ] `grpc::AccessTokenCredentials` should work.  This is where [gcloud](https://cloud.google.com/sdk/gcloud/reference/beta/auth/application-default/print-access-token) should be handy, because it creates the token for you.
- [ ] `grpc::GoogleRefreshTokenCredentials` should work.  To test these one needs to create a refresh token.  Look at the code here:
https://github.com/GoogleCloudPlatform/google-cloud-cpp/blob/37ea4a449f2887693d82146431fa8db6c59ce5bd/google/cloud/storage/internal/authorized_user_credentials.h#L66
- [ ] `grpc::ServiceAccountJWTAccountCredentials` should work.  I think this is where you need to look at the code here (or call this code) to create the JWT:
https://github.com/GoogleCloudPlatform/google-cloud-cpp/blob/37ea4a449f2887693d82146431fa8db6c59ce5bd/google/cloud/storage/internal/service_account_credentials.h#L126
- [ ] `grpc::GoogleIAMCredentials()` I think should work, though in this case I am less familiar with how this works.  I think a good place to start researching would be the [python module](https://google-auth.readthedocs.io/en/latest/reference/google.auth.iam.html) that deals with them.

### Out of Scope

- [ ] `SslCredentials` this are not applicable because GCP does not support client-side certificates for authentication.

**Comment by manish-qlogic** [comment]
# Use gRPC Credential Classes with GCP Bigtable c++ client
## Before you begin
### Set the Environment Variables
Following environment variables must be set to connect to InstanceAdmin or TableAdmin endlpoints
* GOOGLE_APPLICATION_CREDENTIALS
`export GOOGLE_APPLICATION_CREDENTIALS="[PATH]"`
where [PATH] is file path for JSON file that contains either user account or Service account key. Please refer [this link](https://cloud.google.com/docs/authentication/getting-started) for more details on Google Authentication. 

* GRPC_DEFAULT_SSL_ROOTS_FILE_PATH
`export GRPC_DEFAULT_SSL_ROOTS_FILE_PATH="[PATH]"`
where [PATH] is file path for gRPC Root Certificate. Please refer [this link](https://github.com/GoogleCloudPlatform/google-cloud-cpp/tree/master/google/cloud/bigtable/examples#configure-grpc-root-certificates) for more details on gRPC Root Certifacte Configuration.

## Use Access Token Credentials
* Acquire Access Token
Use [gcloud](https://cloud.google.com/sdk/gcloud/reference/beta/auth/application-default/print-access-token)  to acquire an Access Token
* Sample code to connect to InstanceAdmin endpoint
```
#include "google/cloud/bigtable/instance_admin.h"
#include "google/cloud/bigtable/instance_admin_client.h"
#include <google/protobuf/text_format.h>
#include <typeindex>
#include <typeinfo>

int main(int argc, char* argv[]) try {
  std::string const project_id = argv[1];
  // Put Acquired Access Token
  grpc::string access_token("Valid Access Token");
  auto call_credentials = grpc::AccessTokenCredentials(access_token);
  auto channel_credentials = grpc::SslCredentials(grpc::SslCredentialsOptions());
  auto credentials = grpc::CompositeChannelCredentials(channel_credentials, call_credentials);
  auto instance_admin_client(
      google::cloud::bigtable::CreateDefaultInstanceAdminClient(
          project_id, google::cloud::bigtable::ClientOptions(credentials)));
  google::cloud::bigtable::InstanceAdmin instance_admin(instance_admin_client);
  auto instances = instance_admin.ListInstances();
  for (auto ins : instances) {
    std::string request_text;
    google::protobuf::TextFormat::PrintToString(ins, &request_text);
    std::cout << __func__ << "request=" << request_text << std::endl;
  }
  return 0;
} catch (std::exception const& ex) {
  std::cerr << "Standard C++ exception raised: " << ex.what() << std::endl;
  return 1;
}
```

## Use Refresh Token Credentials
* Sample code to connect to InstanceAdmin endpoint
```
#include "google/cloud/bigtable/instance_admin.h"
#include "google/cloud/bigtable/instance_admin_client.h"
#include <google/protobuf/text_format.h>
#include <typeindex>
#include <typeinfo>

int main(int argc, char* argv[]) try {
  std::string const project_id = argv[1];
  grpc::string refresh_token = R"""({
      "client_id": "XXXXXX.apps.googleusercontent.com",
      "client_secret": "Zmasdfcafdfdc8hD4CTg2ejr2",
      "refresh_token": "1/qNM0tasdfasdffja4py5AP0iz7D7I3Vasdfasd_s_l8Z0VacgqwVhlUQOGpnm1N",
      "type": "authorized_user"
  })""";
  auto call_credentials = grpc::GoogleRefreshTokenCredentials(refresh_token);
  auto channel_credentials = grpc::SslCredentials(grpc::SslCredentialsOptions());
  auto credentials = grpc::CompositeChannelCredentials(channel_credentials, call_credentials);
  auto instance_admin_client(
      google::cloud::bigtable::CreateDefaultInstanceAdminClient(
          project_id, google::cloud::bigtable::ClientOptions(credentials)));
  google::cloud::bigtable::InstanceAdmin instance_admin(instance_admin_client);
  auto instances = instance_admin.ListInstances();
  for (auto ins : instances) {
    std::string request_text;
    google::protobuf::TextFormat::PrintToString(ins, &request_text);
    std::cout << __func__ << "request=" << request_text << std::endl;
  }
  return 0;
} catch (std::exception const& ex) {
  std::cerr << "Standard C++ exception raised: " << ex.what() << std::endl;
  return 1;
}
```

**Comment by manish-qlogic** [comment]
@coryan 
An attempt with IAM Credentials resulted into "Received RST_STREAM with error code 1 [13=INTERNAL] " from gRPC server. I have updated these credentials as "not supported".  
Do we keep the bug open and change the milestone or create a new issue just for `grpc::GoogleIAMCredentials()`?

**Comment by coryan** [comment]
I just changed the milestone. Let's keep this bug open for the moment.  I will unassigned it too since you have done all that can be done here.

**Comment by coryan** [comment]
After re-reading the bug, we are done here.

**Comment by evanj** [comment]
This should be documented somewhere! Like maybe in the examples, or in the gRPC documentation? This is very hard to figure out on your own.
