### ISSUE TITLE
Implement a class to automatically batch mutations.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#1372]
Consider an application that reads a stream of data, like the `gcs2cbt` example. We would want to automatically batch these requests, using the asynchronous API to send the batches. We need to automatically flow control the requests too, or this can easily create more outstanding requests that expected.

This is under `Async/concurrent batches` in the surface design doc, but maybe a small document should be written when we decide to implement this feature.

**Comment by dopiera** [comment]
@coryan I'd be grateful for your thoughts / comments. Sorry for the volume, but I thought it's good to document the design process for posterity. I found it annoying to have to reverse engineer such things in the past.

Fortunately, the code should be simpler than this text :)

**Comment by coryan** [comment]
First, we need to make the easy case easy, what do you think of an API like this:

```C++
bool HasMoreMutations();
bigtable::SingleRowMutation MutationGenerator();

void AppCode(bigtable::Table table, bigtable::CompletionQueue cq) {
  auto batcher = table.CreateAsyncMutationBatcher(cq);

  while (HasMoreMutations()) {
    batcher.ScheduleMutation(MutationGenerator());
  }
  batcher.Close();
}
```

This API can do flow control by simply blocking on the `ScheduleMutation()` call if there is too much data (let's worry about *how* later).  Presumably we can also add a `Flush()` member function to that "batcher" thing that blocks.

Can we make that work?

Second, did you consider using "tokens" for the asynchronous version?  Basically the application needs to obtain a token (potentially asynchronously) before sending a mutation.  If the application provides an invalid token (or old token) then the operation simply does not schedule.  An initial version of the batcher can just have a limited number of tokens, as we gain experience the token pool can dynamically grow and shrink.

The code would look like this.

```C++
bool HasMoreMutations();
bigtable::SingleRowMutation MutationGenerator();

void AppCodeAsync(bigtable::Table table, bigtable::CompletionQueue cq) {
  auto batcher = table.CreateAsyncMutationBatcher(cq);

  // this is a bit of a hack, typically you would create a class with separate member functions for these.
  std::function<void(future<Token> token> batch_one;
  batch_one = [&](future<Token> token) {
    if (not HasMoreMutations()) {
      // TODO() we need a make_satisfied_future<> function.
      promise<void> p;  p.set_value(); return p.get_future();
    }
    future<Token> token = batcher.AsyncSchedule(token.get(), MutationGenerator());
    // Call ourselves.
    return token.then([](future<Token> token) { return batch_one(token); }
  };

  batcher.AsyncSchedule([](future<Token> token) {
    return schedule(token);
  });
  batcher.Close(); // blocks
}
```

**Comment by dopiera** [comment]
> First, we need to make the easy case easy, what do you think of an API like this:
> 
> ```c++
> bool HasMoreMutations();
> bigtable::SingleRowMutation MutationGenerator();
> 
> void AppCode(bigtable::Table table, bigtable::CompletionQueue cq) {
>   auto batcher = table.CreateAsyncMutationBatcher(cq);
> 
>   while (HasMoreMutations()) {
>     batcher.ScheduleMutation(MutationGenerator());
>   }
>   batcher.Close();
> }
> ```
> 
> This API can do flow control by simply blocking on the `ScheduleMutation()` call if there is too much data (let's worry about _how_ later). Presumably we can also add a `Flush()` member function to that "batcher" thing that blocks.
> 
> Can we make that work?

Is my understanding correct that callbacks for those mutations would still be fired asynchronously on a thread running `cq.Run()`?

If yes, I think this only makes sense if `MutationGenerator()` is generating mutations faster than CBT can accept. I'm guessing that rarely it is easy to predict it, so we're giving the user a tool which they are likely to misuse. I think we should encourage them to not mix synchronous and asynchronous programming.

We can certainly make it work, but I'm not a big fan of this. It could be implemented as a wrapper around the fully asynchronous version.

> Second, did you consider using "tokens" for the asynchronous version? Basically the application needs to obtain a token (potentially asynchronously) before sending a mutation. If the application provides an invalid token (or old token) then the operation simply does not schedule. An initial version of the batcher can just have a limited number of tokens, as we gain experience the token pool can dynamically grow and shrink.

I didn't and I think they are massively superior to what I proposed.

> The code would look like this.
> 
In your example MutationGenerator is synchronous. I've redone it such that it returns `std::future<Mutation>`:
```C++
std::future<void> ProcessBatched() {
  if (not HasMoreMutations()) {
    std::promise<void> p; p.set_value(); return p.get_future();
  }
  return MutationGenerator().then([](std::future<SingleRowMutation> m) {
    return AsyncGetToken().then([m](std::future<Token> t) {
      return AsyncApplyBatched(token.get(), m)
          .then([](std::future<MutationResponse> resp) {
            // handle result of insertion
            return Process();
          })
    })
  });
}

//======== internal, no exceptions version =====================================

void ProcessBatched(std::function<void()> callback) {
  if (not HasMoreMutations()) {
    callback();
    return;
  }
  // Status handling is omitted for brevity.
  MutationGenerator([callback](CompletionQueue &cq, SingleRowMutation &m,
                               grpc::Status &status) {
    AsyncGetToken(cq, std::move(m),
                  [callback](CompletionQueue &cq, SingleRowMutation &m, Token t,
                             grpc &status) {
                    AsyncApplyBatched(
                        cq, t, m,
                        [callback](CompletionQueue &cq, grpc::Status &status) {
                          ProcessBatched(callback);
                        })
                  })
  });
}


```

**Comment by dopiera** [comment]
I think I've got an even better idea: instead of enforcing flow control, expose the information about when the mutation got processed. This way, we indirectly indicate to the user that we're ready to accept more. The user can then use this information to slow down on their side. PTAL at the examples:

```C++

// Asynchronous MutationGenerator, futures-style
std::future<void> Process() {
  if (not HasMoreMutations()) {
    std::promise<void> p;
    p.set_value();
    return p.get_future();
  }
  return MutationGenerator().then([](std::future<SingleRowMutation> m) {
    std::future<void> mutation_admitted;
    std::future<void> mutation_applied =
        AsyncApplyBatched(std::move(m.get()), &mutation_admitted);
    // Potentially do something with mutation_applied future, but don't wait
    // for it here.
    return mutation_admitted.then(
        [](std::future<void>()) { return Process(); });
  });
}

// Synchronous MutationGenerator, futures-style
std::future<void> Process() {
  if (not HasMoreMutations()) {
    std::promise<void> p;
    p.set_value();
    return p.get_future();
  }

  std::future<void> mutation_admitted;
  std::future<void> mutation_applied =
      AsyncApplyBatched(std::move(MutationGenerator()), &mutation_admitted);
  // Potentially do something with mutation_applied future, but don't wait
  // for it here.
  return mutation_admitted.then([](std::future<void>()) { return Process(); });
}

// Asynchronous MutationGenerator, callback-style
void Process(std::function<void()> callback) {
  if (not HasMoreMutations()) {
    callback();
    return;
  }
  // Status handling is omitted for brevity.
  MutationGenerator([callback](CompletionQueue &cq, SingleRowMutation &m,
                               grpc::Status &status) {
    AsyncApplyBatched(cq, t, m,
                      [](CompletionQueue &cq, grpc::Status &status) {
                        // some callback for completed mutations
                      },
                      // Optional callback for mutation admitted.
                      [callback](CompletionQueue &cq, grpc::Status &status) {
                        Process(callback);
                      });
  })
}

// Synchronous MutationGenerator, callback-style
void Process(std::function<void()> callback) {
  if (not HasMoreMutations()) {
    callback();
    return;
  }
  // Status handling is omitted for brevity.
  AsyncApplyBatched(cq, t, MutationGenerator(),
                    [](CompletionQueue &cq, grpc::Status &status) {
                      // some callback for completed mutations
                    },
                    // Optional callback for mutation admitted.
                    [callback](CompletionQueue &cq, grpc::Status &status) {
                      Process(callback);
                    });
}

// Futures version used for the first example.
void ProcessSynchronously() {
  while (HasMoreMutations()) {
    std::future<void> mutation_admitted;
    AsyncApplyBatched(mutation, &mutation_admitted);
    std::future<void> mutation_applied = mutation_admitted.get();
    // Potentially do something with mutation_applied future, but don't wait
    // for it here.
  }
}
```

This approach has also the advantage of allowing to easily retrofit flow control to non-batched API.

**Comment by coryan** [comment]
I think this is getting complex enough that we need a design doc.  We also need to define the problem / use-cases we want to support.  Here are some thoughts on the problems:

1. A batch uploader of some sort: read a large file from the local file system (or download it from GCS), and push data "as fast as possible" to Bigtable. Similar to [gcs2cbt](https://github.com/GoogleCloudPlatform/google-cloud-cpp/blob/master/google/cloud/examples/gcs2cbt.cc).

2. Some kind of transform from CBT to CBT using the asynchronous APIs.  Imagine a "read all the rows from table A asynchronously change the data to uppercase and write to this other table". Though of course the transform would need to be more interesting.  And the source might be Spanner, or a future asynchronous API for GCS.

3. Mapping from another source of asynchronous data to CBT, assuming the source has an explicit push back mechanism.

I think blocking is perfectly fine for the first use case, and actually quite usable.  The second use case is more difficult.  I am not sure how you push back on gRPC other than by *not* reading from the underlying streaming RPC. Which for our abstractions translates into not returning from the RowReader callback.  Which probably would be reasonably supported by blocking on the batcher `.Schedule()` member function.

I am really close to calling "YAGNI" on the third use case, simply because I do not know of any, but I might be wrong and happy to hear about such a use case.


Note that the relative speed of the client and Bigtable is not an issue if  `.Schedule()` does not always flush on each request.  We can do some local buffering, the batcher could accumulate mutations until it sees that it has "enough" and only then initiate the asynchronous request. One of its control parameters could be "how many mutations before sending an asynchronous request" and another would be "how many asynchronous mutations in flight before blocking the callers".

**Comment by dopiera** [comment]
I believe #2109 fixes this.
