### ISSUE TITLE
Catch up with missing services

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#13847]
A number of proto files listed in the `*.list` files with RPC services defined are missing from the `generator_config.textproto` file:

```sh
comm -23 \
    <(git ls-files -- external/googleapis/protolists/*.list | \
            xargs sed -e 's;@com_google_googleapis//;;' -e 's;:;/;' | \
            xargs env -C .build/external/googleapis/src/googleapis_download grep -l '^service ' | sort) \
     <(sed -n  '/service_proto_path:/ {s/.*_path: "//; s/"//p}' generator/generator_config.textproto | sort) 
```

- [x] google/cloud/aiplatform/v1/feature_registry_service.proto
- [ ] google/cloud/aiplatform/v1/genai_tuning_service.proto
- [x] ~~google/cloud/apigeeconnect/v1/tether.proto~~
- [x] google/cloud/contentwarehouse/v1/pipeline_service.proto
- [x] google/cloud/dataplex/v1/catalog.proto
- [x] google/cloud/dataplex/v1/datascans.proto
- [x] google/cloud/dataplex/v1/data_taxonomy.proto
- [x] google/cloud/dataproc/v1/sessions.proto
- [x] google/cloud/dataproc/v1/session_templates.proto
- [x] google/cloud/dialogflow/cx/v3/generator.proto
- [x] google/cloud/discoveryengine/v1/data_store_service.proto
- [x] google/cloud/discoveryengine/v1/engine_service.proto
- [x] google/cloud/discoveryengine/v1/recommendation_service.proto
- [x] google/cloud/discoveryengine/v1/site_search_engine_service.proto
- [x] google/cloud/networkconnectivity/v1/policy_based_routing.proto
- [x] ~~google/cloud/notebooks/v1/service.proto~~
- [x] google/cloud/retail/v2/analytics_service.proto
- [x] google/cloud/sql/v1/cloud_sql_available_database_versions.proto
- [x] google/cloud/sql/v1/cloud_sql_events.proto
- [x] google/cloud/sql/v1/cloud_sql_iam_policies.proto
- [x] google/cloud/sql/v1/cloud_sql_instance_names.proto
- [x] google/cloud/sql/v1/cloud_sql_regions.proto
- [ ] google/cloud/texttospeech/v1/cloud_tts_lrs.proto
- [x] grafeas/v1/grafeas.proto: marked as done because we intentionally skip this one.

**Comment by dbolduc** [comment]
We should give extra scrutiny to services that were not added as part of #12168. Although some of them may be GA by now.
