### ISSUE TITLE
Implement `future<>::cancel()`.

### ISSUE THREAD

**Issue by dopiera** [googleapis/google-cloud-cpp#1386]
This is an action item from #1289.

It is not clear at this point how feasible that is, so the outcome of this bug might as well be "it's infeasible".

The design should also allow for elegant handling of `future`s chained with `future<>::then()`.

**Comment by dopiera** [comment]
@coryan I think it's safe to call it obsolete, since we agreed on cancellation tokens.

**Comment by coryan** [comment]
We might do this, but right now it is too speculative to say one way or the other.
