### ISSUE TITLE
Generator work for BQ

### ISSUE THREAD

**Issue by alevenberg** [googleapis/google-cloud-cpp#13892]
- [x] Add option to execute synchronously via command line argument
- [ ] Handle types any
   - [x] allow any type to pass parsing 
Handle any proto. The compute docs assume type=any means, any proto. BQ says it is "any" json string. We can either 1) replace this with a string or 2) inject custom types to replace. We should count how many occurrences of this is and then decide the path forward.

There are only 4 any types in bigquery's [discovery doc](https://bigquery.googleapis.com/discovery/v1/apis/bigquery/v2/rest). Search: "type": "any".  I suggest we add a flag to say what does type any map to,  a proto or a string.
```
  "TableCell": {
      "id": "TableCell",
      "properties": {
        "v": {
          "type": "any"
        }
      },
      "type": "object"
    },
```
- [x] Handle $$ case. The generator interprets this as string substitution currently.

```
 "TableReference": {
      "id": "TableReference",
      "properties": {
        "datasetId": {
          "description": "Required. The ID of the dataset containing this table.",
          "type": "string"
        },
        "projectId": {
          "description": "Required. The ID of the project containing this table.",
          "type": "string"
        },
        "tableId": {
          "description": "Required. The ID of the table. The ID can contain Unicode characters in category L (letter), M (mark), N (number), Pc (connector, including underscore), Pd (dash), and Zs (space). For more information, see [General Category](https://wikipedia.org/wiki/Unicode_character_property#General_Category). The maximum length is 1,024 characters. Certain operations allow suffixing of the table ID with a partition decorator, such as `sample_table$20190123`.",
          "type": "string"
        }
      },
```
- [x] Handle additionalProperties field, but no properties field
The BigQuery "map" JSON convention
```
  "JsonObject": {
      "additionalProperties": {
        "$ref": "JsonValue"
      },
      "description": "Represents a single JSON object.",
      "id": "JsonObject",
      "type": "object"
    },
```
- [x] Change make directory to create a directory if it DNE before
```
Status DiscoveryFile::WriteFile(
    DiscoveryDocumentProperties const& document_properties,
    std::map<std::string, DiscoveryTypeVertex> const& types) const {
  std::string version_dir_path = file_path_.substr(0, file_path_.rfind('/'));
  std::string service_dir_path =
      version_dir_path.substr(0, version_dir_path.rfind('/'));
  MakeDirectory(service_dir_path);
  MakeDirectory(version_dir_path);
  std::ofstream os(file_path_);
  return FormatFile(document_properties, types, os);
}
```
- [x] Handle the recursion case 
Ex.
```
    "TableFieldSchema": {
      "description": "A field in TableSchema",
      "id": "TableFieldSchema",
      "properties": {
        ...
        "fields": {
          "description": "Optional. Describes the nested schema fields if the type property is set to RECORD.",
          "items": {
            "$ref": "TableFieldSchema"
          },
          "type": "array"
        },
        ...
      },
      "type": "object"
    },
```
```
// A field in TableSchema
message TableFieldSchema {
  ...
  // Optional. Describes the nested schema fields if the type property is set to
  // RECORD.
  repeated TableFieldSchema fields = 5 [json_name = "fields"];
  ...
}
```
- [ ] Handle pagination
- [ ] Generate POST types

Some examples from debugging: https://paste.googleplex.com/4854632114814976#l=3

Changes exist in https://github.com/googleapis/google-cloud-cpp/compare/main...alevenberg:google-cloud-cpp:bigquery

**Comment by scotthart** [comment]
Also handle the BigQuery "map" JSON convention.

**Comment by scotthart** [comment]
Are you including injecting custom proto definitions for fields of type "any" as part of your "Handle types any" item?

**Comment by scotthart** [comment]
I would keep the "option to execute synchronously" as either a env var or command line flag, not something that is part of the configuration proto.

**Comment by alevenberg** [comment]
> Are you including injecting custom proto definitions for fields of type "any" as part of your "Handle types any" item?

No added a separate item.

> I would keep the "option to execute synchronously" as either a env var or command line flag, not something that is part of the configuration proto.

Ack noted that.

>  Also handle the BigQuery "map" JSON convention.

Not sure what this is. Added it as a line item.

**Comment by scotthart** [comment]
The BigQuery Discovery Document has slight differences in field names for paginated rpcs than what the generator expects per AIP-158 (https://google.aip.dev/158) compared to http://cloud/bigquery/docs/reference/rest/v2/jobs/list. The necessary fields are there so there should be a way to provide pagination.

**Comment by scotthart** [comment]
rest_stub_helpers.h defines overloads for Post that rely on template argument deduction to reduce the introspection required from the generator. However, this works as long as the `Response` and `Request` types are different. When they're not the resolution is ambiguous. BigQuery has a few rpcs where this occurs ("InsertDataset", "InsertJob", "InsertRoutine", "InsertTable"). For these, and any other such methods, we need to figure out a solution. One such solution is to emit both types when calling Post, e.g.:
```
StatusOr<google::cloud::cpp::bigquery::v2::Job> DefaultJobsRestStub::InsertJob(
    google::cloud::rest_internal::RestContext& rest_context,
    Options const& options,
    google::cloud::cpp::bigquery::jobs::v2::InsertJobRequest const& request) {
  return rest_internal::Post<google::cloud::cpp::bigquery::v2::Job,
                             google::cloud::cpp::bigquery::v2::Job>(
      *service_, rest_context, request.job_resource(), false,
      absl::StrCat("/", "bigquery", "/",
                   rest_internal::DetermineApiVersion("v2", options), "/",
                   "projects", "/", request.project_id(), "/", "jobs"));
}
```

**Comment by alevenberg** [comment]
> The BigQuery Discovery Document has slight differences in field names for paginated rpcs 

```
  rpc ListJobs(ListJobsRequest) returns (google.cloud.cpp.bigquery.v2.JobList) {
    option (google.api.http) = {
      get: "/bigquery/v2/projects/{project_id}/jobs"
    };
    option (google.api.method_signature) = "project_id";
  }
```

```
// Request message for ListJobs.
message ListJobsRequest {
  // The maximum number of results to return in a single response page. Leverage
  // the page tokens to iterate through the entire collection.
  optional uint32 max_results = 3 [json_name="maxResults"];

  // Page token, returned by a previous call, to request the next page of
  // results.
  optional string page_token = 5 [json_name="pageToken"];
```

```
// JobList is the response format for a jobs.list call.
message JobList {
  // A token to request the next page of results.
  optional string next_page_token = 4 [json_name="nextPageToken"];
}
```

> than what the generator expects per AIP-158 ([google.aip.dev/158](https://google.aip.dev/158))

```
message ListBooksRequest {
  int32 page_size = 2;
  string page_token = 3;
}

message ListBooksResponse {
  string next_page_token = 2;
}

```

> compared to http://cloud/bigquery/docs/reference/rest/v2/jobs/list. The necessary fields are there so there should be a way to provide pagination.

I think you are saying we should rename `max_results` fields to `page_size`, but not sure. Can you clarify?

**Comment by scotthart** [comment]
It may not be necessary to rename the field, but to alter how the generator identifies and determines pagination https://github.com/googleapis/google-cloud-cpp/blob/a77950e488c3be12832aa5efece7a0889ff47a08/generator/internal/pagination.cc#L126

**Comment by alevenberg** [comment]
> It may not be necessary to rename the field, but to alter how the generator identifies and determines pagination
> 
> https://github.com/googleapis/google-cloud-cpp/blob/a77950e488c3be12832aa5efece7a0889ff47a08/generator/internal/pagination.cc#L126

Ahh that makes sense. Thanks!

**Comment by alevenberg** [comment]
Closing out, since we are now going to use BQ protos.
