### ISSUE TITLE
Support `CreateServiceTimeSeries` in GCM exporter

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#14074]
We currently support custom metrics only. These are sent via `rpc CreateTimeSeries`.

There are also Google-defined metrics, which need to be sent via `rpc CreateServiceTimeSeries`.

Note that these both use the same request type as `CreateTimeSeries`. So the conversion from OTel types -> protos is still mostly valid.

We will need to do something about the metric type. The hardcoded `"workload.googleapis.com/"` prefix is incompatible with Google-defined metrics. Other languages have a configuration option for it.

https://github.com/googleapis/google-cloud-cpp/blob/47e17cdec66d6398966cd095f80cf34a86bffe17/google/cloud/opentelemetry/internal/time_series.cc#L73-L75

**Comment by dbolduc** [comment]
We also need to support a custom monitored resource. The code that produces a `google::api::MonitoredResource` from an `opentelemetry::sdk::resource::Resource` does not know about all monitored resources, e.g. a bigtable table.

We could either:
1. Expose an Option to override the `MonitoredResource` directly.
2. Set resource attributes to identify the new monitored resource types. Add a case for each new monitored resource type in our conversion function.

We probably want 1.

**Comment by coryan** [comment]
> We could either:
> 
> 1. Expose an Option to override the `MonitoredResource` directly.
> 2. Set resource attributes to identify the new monitored resource types. Add a case for each new monitored resource type in our conversion function.
> 
> We probably want 1.

(1) is fine for the GCS+gRPC metrics.  Presumably the option would be for the monitored resource type and the attributes will be copied verbatim?  Or would you still convert invalid characters in keys to `_` ?
