### ISSUE TITLE
Move builds to Fedora:40

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#14076]
Fedora:40 is out: https://fedoramagazine.org/announcing-fedora-linux-40/ that means Fedora:39 (what we use in most builds) will be EOL around 2024-11: https://endoflife.date/fedora

Time to start updating the builds. Start by making a list:

- [x] The demo-install build (ty @coryan)
- [x] The m32 build
- [x] The bazel build
	- [x] Handle future_error constructor being removed (https://github.com/llvm/llvm-project/commit/d2cb198f25c82bf77bb113763771590cc79a21a4)
- [x] The Cmake build
	- [x] Fix the clang tidy issues
- [x] The cxx20 build
	- [x] Fix the absl log build error 	
- [x] The cxx14 build
- [ ] #14207
	- [ ] Fix the docfx to handle "operator<<"	
	- [ ] https://github.com/doxygen/doxygen/issues/10859
- [x] The msan build
	- [x] Update the msan LLVM from 17 to 18
- [x] The checkers build

If I was to do this again, I would make a script to make and submit all the PRs to run the builds in GCB. Then go and fix one by one.

**Comment by alevenberg** [comment]
For the publish-docs build

This does not generate docs 

```
FAILED: google/cloud/CMakeFiles/cloud-docs /workspace/cmake-out/google/cloud/CMakeFiles/cloud-docs 
cd /workspace/google/cloud && /usr/bin/cmake -E make_directory /workspace/cmake-out/google/cloud && /usr/bin/doxygen /workspace/cmake-out/google/cloud/Doxyfile.cloud-docs
/workspace/google/cloud/doc/error-handling.dox:26: error: unable to resolve reference to 'google::cloud::operator<<(std::ostream&,google::cloud::Status const&)' for \ref command (warning treated as error, aborting now)
T+15.085s [...n_impl.cc.o
ninja: build stopped: subcommand failed.
==> 🕑 publish-docs completed in 239.704 seconds
```

I think I need to follow something like https://github.com/googleapis/google-cloud-cpp/pull/13852 first

**Comment by alevenberg** [comment]
Closing for the fixit, moved the publish-docs to a separate issue.
