### ISSUE TITLE
Add BigQuery Storage Read example

### ISSUE THREAD

**Issue by scotthart** [googleapis/google-cloud-cpp#14285]
Demonstrate how to use the existing BigQuery Storage Read library to put data into arrow::RecordBatch objects.

This will likely need to go in the samples repo as it will require a dep on Apache Arrow

**Comment by alevenberg** [comment]
I can try and do this as operator

**Comment by alevenberg** [comment]
https://github.com/GoogleCloudPlatform/cpp-samples/pull/335
