### ISSUE TITLE
generate discoveryengine controlservice

### ISSUE THREAD

**Issue by scotthart** [googleapis/google-cloud-cpp#14321]
This service/proto was added to the existing collection of discoveryengine protos.

**Comment by coryan** [comment]
That seems incomplete:

https://github.com/googleapis/googleapis/commit/4f3af9beb20ec70a4334af02bb36b3e5e21c09d9

Looks like at least these files are new and introduce services:

- [ ] "control_service.proto",
- [ ] "grounded_generation_service.proto",
- [ ] "project_service.proto",
- [ ] "rank_service.proto",
