### ISSUE TITLE
Allow custom lib targets to be specified in the generator_config

### ISSUE THREAD

**Issue by scotthart** [googleapis/google-cloud-cpp#14402]
99% of the time, the lib path for a service is simply `"./lib64/cmake/google_cloud_cpp_" + lib`. For the other 1% we need to specify a custom path to emit into `ci/etc/expected_install_directories`. We can either hard code these few exceptions or add support to generically specify them.

**Comment by dbolduc** [comment]
This is less relevant, as we generated the BigQuery v2 API as its own `bigquerycontrol` library.
