### ISSUE TITLE
Design how to handle multipage responses.

### ISSUE THREAD

**Issue by dopiera** [googleapis/google-cloud-cpp#1454]
Requests like `ListInstances` stream responses page by page, utilizing `next_page_token` to indicate if it's an end of stream or not.

It is not immediately obvious how to handle retries in such API calls.

My idea is to:
 * go over pages without any sleeps between them
 * accumulate result (we should make it future proof to allow for streaming)
 * if getting a page fails, keep retrying until it succeeds; if all retries on a page fail, fail the whole request
 * even if getting a page had to be retried (but eventually succeeded), move on to the next page without any delay

This is how I'd implement it:
 * Create a templated `GetPage` operation, which would meet `MeetsAsyncOperationRequirements` 
   requirements
 * Create a templated `PageIterator` class, which would keep going over pages without any delay, 
   accumulating the results and not doing any retries (an instantiation of `AsyncPollOp` with a 
  `PollingPolicy` which fails on first error and doesn't sleep between attempts)
 * The operation passed to `PageIterator` would be an `AsyncRetryOp<GetPage>`
 * Each operation which `PageIterator` starts, shares the same `RetryPolicy`, but gets a new `RPCBackoffPolicy`

This is going to allow for easily handling the operations like `ListInstances` while ignoring `failed_locations`. Handling `failed_locations` can be built on top of this.

**Comment by coryan** [comment]
> go over pages without any sleeps between them
> accumulate result

So far I agree.

> (we should make it future proof to allow for streaming)

YAGNI.  When we get there we will think about it, before then is a waste of time.

> if getting a page fails, keep retrying until it succeeds; if all retries on a page fail, fail the whole request

Agree.

> even if getting a page had to be retried (but eventually succeeded), move on to the next page without any delay

Sounds right.  All we need to do is reset the backoff policy but keep the retry policy unchanged, right?  That way more failures "count" against the failure budget, but we can make quick progress as long as there are no more failures?

> This is how I'd implement it:

Do not worry about iteration for these things.  The number of instances for a project is expected to fit in memory.

Consider an alternative where there are two operations:

- `AsyncListInstances()` and `ListInstances()` that fetch all the instances and the failed locations.
- `AsyncListInstancesTryReallyReallyHard()` and `ListInstancesTryReallyReallyHard()` that calls `AsyncListInstances()` multiple times when there are any failed locations and returns the merged results.  Maybe with a better name :grimacing:

**Comment by dopiera** [comment]
> Sounds right. All we need to do is reset the backoff policy but keep the retry policy unchanged, right? That way more failures "count" against the failure budget, but we can make quick progress as long as there are no more failures?

Pretty much. I wanted to schedule, a new AsyncRetry for every page though, which is going to have a similar effect.

> Do not worry about iteration for these things. The number of instances for a project is expected to fit in > memory.

I'm not sure I understand. Maybe I picked a confusing name (`PageIterator`). Perhaps `AllPagesFetcher` would be more descriptive. I wanted it to be responsible for kicking off the retried fetching of operations and I wanted to implement it by abusing `AsyncPollOp`.

> Consider an alternative where there are two operations:
> AsyncListInstances() and ListInstances() that fetch all the instances and the failed locations.
> AsyncListInstancesTryReallyReallyHard() and ListInstancesTryReallyReallyHard() that calls 
> AsyncListInstances() multiple times when there are any failed locations and returns the merged
> results. Maybe with a better name ￼

I don't understand why you're saying it's an alternative. I didn't want to address the `failed_locations` matter in this bug at all. I only mentioned it (poorly phrased, though) as a problem which we might be able to solve in the future by building on top of what I'm proposing here.

My key question was: are you fine with what basically is a slightly abused `AsyncPollOp` scheduling per-page `AsyncRetryOp`, all sharing the same retry policy?

I think the answer to the question, which I asked should be "no". The suggestion you made about resetting the the backoff policy is a better idea. Thanks!

I now think we should basically wrap an `AsyncPollOp` with a `PollingPolicy` crafted such that it would reset its backoff policy after every `Exhausted()` call - it's simpler and achieves the same thing.

**Comment by coryan** [comment]
> I don't understand why you're saying it's an alternative.

I was responding to this comment:

> >  Handling `failed_locations` can be built on top of this.

If we just reset the backoff policy we may not create the necessary infrastructure, but we can deal with the `failed_locations` by building on top of an API that does not.

> > Do not worry about iteration for these things. The number of instances for a project is expected to fit in  memory.

> I'm not sure I understand. Maybe I picked a confusing name (PageIterator). Perhaps AllPagesFetcher would be more descriptive. I wanted it to be responsible for kicking off the retried fetching of operations and I wanted to implement it by abusing AsyncPollOp.

My bad, you are right.

**Comment by dopiera** [comment]
This has been fixed 3 months ago.
