### ISSUE TITLE
Test driver scripts may miss errors.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#1460]
The driver scripts for tests and examples use expressions like this:

```sh
local foo="blah-$(date +%s)"
```

These are a problem because errors in the shell expansion `$(...)` are not reported in this case.  We can use:

```sh
local foo
foo="blah-$(date +%s)"
```

but those do not work with `local -r`.  We can replace the "date as a source of random numbers" with `${RANDOM}` in some cases.

Regardless, we should search for such expressions and fix them appropriately.

Thanks to @dopiera for pointing this out.

**Comment by rsimion** [comment]
@coryan  

Just to make sure:

local -r INSTANCE="in-$(date +%s)"

should become

local -r INSTANCE="in-${RANDOM}"

?

**Comment by coryan** [comment]
In general, we want to find all the places where we use `$(...)` and assign the result to a `local FOO=` variable.  How to fix it depends on the location.  Most will be something like `$(date +%s)` where the date is used as a "unique" value.  Replacing with `${RANDOM}-${RANDOM}` is probably fine in these cases.

If we have something more complicated we would need to figure out how it is being used.

**Comment by rsimion** [comment]
@coryan 
I do not think that replacing $(date +%s) with ${RANDOM}-${RANDOM} was the best approach. the emulator examples do not show up when using  ${RANDOM}-${RANDOM} , just checked all_data_examples() in run_examples_utils.sh .

**Comment by coryan** [comment]
What do you mean by "do not show up"?

**Comment by rsimion** [comment]
I mean when I run the emulator with (data +%s) I can see for instance
[ RUN      ]  data_snippets read-rowset-prefix running
[       OK ]  data_snippets read-rowset-prefix

as opposed to when running it with {RANDOM} only

**Comment by rsimion** [comment]
@coryan 
I think I am just wrong, let me check one one more time.

**Comment by rsimion** [comment]
@coryan 
sorry, made a big mistake, everything works, I forgot to restart my vm.

**Comment by coryan** [comment]
No problem. I am closing this now.
