### ISSUE TITLE
computeMetadata API?

### ISSUE THREAD

**Issue by kbowling-bullish** [googleapis/google-cloud-cpp#14670]
**What component of `google-cloud-cpp` is this feature request for?**
`google/cloud/compute`

**Describe the solution you'd like** A clear and concise description of what you
want to happen.
Is there an API for getting compute metadata i.e. from http://metadata.google.internal/computeMetadata/v1/instance/

**Describe alternatives you've considered** A clear and concise description of
any alternative solutions or features you've considered.
Currently use a HTTP and JSON library, would like to remove the only need for them in my build

**Comment by scotthart** [comment]
While I can appreciate the desire to reduce the number of dependencies of your program, I'm not aware of any other programmatic mechanism to retrieve the metadata for the compute instance you're executing on (https://cloud.google.com/compute/docs/metadata/querying-metadata#programmatically-query-metadata). I can pass along this request, but I have little influence on whether or not such a feature is added.

**Comment by kbowling-bullish** [comment]
Hi @scotthart can you link me to the implementation?
