### ISSUE TITLE
PollingPolicy's interface doesn't allow for differentiating between failures and successes

### ISSUE THREAD

**Issue by dopiera** [googleapis/google-cloud-cpp#1475]
PollingPolicy is supposed to determine delays between poll attempts.

The code indicates that it should be used the following way:
```cpp
do {
  if (/*poll finished*/) {
    // return poll result
  }
  auto delay = polling_policy->WaitPeriod();
  sleep(delay);
  auto status = ExecuteAttempt(...);
  if (not status.ok() and not polling_policy->OnFailure(status)) {
    // return that poll failed
  }
} while (not polling_policy->Exhausted())
```

This means that `OnFailure()` is not called when an attempt succeeds and `Exhausted` is called on both success and failure, so from inside `PollingPolicy`, when determining the wait period, you can't really tell if the attempt failed or not.

A default polling policy should probably poll in fixed intervals if attempts succeed. They intervals should be increased only if there is a failure. After a success it should revert to the original intervals. This behavior is not possible with the current interface.

A trivial fix would be to pass a status to `WaitPeriod`. One could also think about removing `OnFailure()` and making `Exhausted()` accept a status.

**Comment by coryan** [comment]
Reviewed on 2021-11-18, still do not know what to do about it.

**Comment by devjgm** [comment]
Things seem ok now. Will reopen this bug or a similar one if/when it seems to be needed.
