### ISSUE TITLE
Default PollingPolicy's interval never drops

### ISSUE THREAD

**Issue by dopiera** [googleapis/google-cloud-cpp#1476]
The default `PollingPolicy's` behavior is to increase the delay between attempts on every attempt - both successful and failed ones.

That means that if there are going to be a couple of transient failures at the beginning of the poll, followed only by successes, the interval between attempts is going to be larger than in the case of no failures.

That behavior seems wrong to me.

**Comment by coryan** [comment]
The current behavior seems to not cause problems, we can open a new bug if needed.
