### ISSUE TITLE
Storage: CURL SSL and Passing client Options

### ISSUE THREAD

**Issue by jfnaugusto** [googleapis/google-cloud-cpp#14784]
Hi,

I'm trying to do some test code to connect to a storage and having this error:
`Retry policy exhausted, with a last message of PerformWork() - CURL error [35]=SSL connect error`

Checking some issues opened, I'm trying to use the channel options set_ssl_root_path, apparently deprecated, but I'm not able to find any samples that allow me to use this option and also create a client with a json file.

So how would I add that option to the sample bellow...

```
namespace gc = ::google::cloud;
namespace gcs = ::google::cloud::storage;

try
{
	auto credentials = gc::MakeServiceAccountCredentials(json);
	gc::Options options;
	options.set<google::cloud::UnifiedCredentialsOption>(credentials);
	_client = std::make_unique<gcs::Client>(options);

}
catch (const std::exception& e)
{
	
}
```
Also is it possible to add a option to the underlying curl library, for example:
`curl_easy_setopt(p, CURLOPT_SSL_OPTIONS, (long)CURLSSLOPT_NATIVE_CA);`

Thanks.

**Comment by scotthart** [comment]
Have you tried using the `CARootsFilePathOption`?

https://github.com/googleapis/google-cloud-cpp/blob/8abc17086c7eb3351a11be54b419a6e6c0232b2b/google/cloud/credentials.h#L392

**Comment by jfnaugusto** [comment]
> Have you tried using the `CARootsFilePathOption`?
> 
> https://github.com/googleapis/google-cloud-cpp/blob/8abc17086c7eb3351a11be54b419a6e6c0232b2b/google/cloud/credentials.h#L392

Thanks working perfectly! :)

I was looking for the CAPathOption, guess it's a typo in the docs.
```
/// @deprecated Use google::cloud::Options and CAPathOption instead.
ChannelOptions& set_ssl_root_path(std::string ssl_root_path) {
  ssl_root_path_ = std::move(ssl_root_path);
  return *this;
}

```

**Comment by dbolduc** [comment]
>  guess it's a typo in the docs

Ah, sorry. Thanks for pointing this out. #14786 will correct it.
