### ISSUE TITLE
Failing in running speech_quickstart_global in CI

### ISSUE THREAD

**Issue by cuiy0006** [googleapis/google-cloud-cpp#14841]
Our ci failed in running `quickstart-production-pr`, error is
```
Step #2:       Test #1173: speech_quickstart_global ..............***Failed    0.40 sec
Step #2: CMake Error at /workspace/cmake/quickstart-runner.cmake:90 (message):
Step #2:   Non-zero exit status (1) running
Step #2:   /workspace/cmake-out/google/cloud/speech/speech_quickstart
Step #2: 
Step #2:   google::cloud::Status thrown: INTERNAL: Error in non-idempotent operation:
Step #2:   Internal error encountered.  error_info={reason=, domain=,
Step #2:   metadata={gcloud-cpp.retry.function=Recognize,
Step #2:   gcloud-cpp.retry.reason=non-idempotent,
Step #2:   gcloud-cpp.retry.original-message=Internal error encountered.}}
```

However, we can run it with no error locally with bazel build.

We can reproduce the error by
```
ci/cloudbuild/build.sh -t quickstart-production-pr --cloud cloud-cpp-testing-resources
```

Source IP might be the cause that produces the internal error.

I am going to disable this test. Please enable it when cloud build `quickstart-production-pr` is recovered from the error.

**Comment by scotthart** [comment]
I removed the bug label, because this is not a bug for our library, but a change in the service behavior when accessed from our CI infrastructure. This is not something we control.
