### ISSUE TITLE
Implement bigtable::Table::AsyncApply

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#1485]
This function will implement an asynchronous version of `Table::Apply`. The function will have the following signature:

```C++
class google::cloud::bigtable::Table { public:
future<void> AsyncApply(SingleRowMutation&& mutation, CompletionQueue& cq);
};
```

As part of this work we need to:

- [ ] Implement the function.
- [ ] Implement an integration test for this function.
- [ ] Implement an example for this function.
- [ ] Execute the example as part of the CI build.

The main difference between the example and the integration test is that the latter uses pre-defined values and checks the resulting state against expected outputs, while the former takes (most) of its parameters from the command-line and simply prints out any state.

**Comment by NettyH** [comment]
Hi Carlos can you please review this function definition for AsyncApply, i also added the Integration test but i want to have your aggrement before i add example. please ignore any std::cout i will remove them.

`future<void> Table::AsyncApply(SingleRowMutation&& mutation,
                               CompletionQueue& cq) {
   promise<void> p;
  grpc::Status capture_status;
  impl_.AsyncApply(
      std::move(mutation), cq,
      [&p, &capture_status](CompletionQueue& cq,
                            google::bigtable::v2::MutateRowResponse& r,
                            grpc::Status const& status) {
        p.set_value();
        capture_status = status;
      });
  if (not capture_status.ok()) {
    std::cout << capture_status.error_message().c_str() << std::endl;
  }
  auto result = p.get_future();
  result.get();

  return result;
}`

**Comment by coryan** [comment]
Candidly, PRs, even incomplete PRs are easier to review.


````C++
future Table::AsyncApply(SingleRowMutation&& mutation,
    CompletionQueue& cq) {
  promise p;
  // This is a local variable, that will go out of scope as soon as this returns
  grpc::Status capture_status;
  impl_.AsyncApply(
      std::move(mutation), cq,
      [&p, &capture_status](CompletionQueue& cq, // ERROR: capture by address of automatic variable.
          google::bigtable::v2::MutateRowResponse& r,
          grpc::Status const& status) {
          p.set_value();
          // possible undefined behavior: using a automatic variable that has gone out of scope.
          capture_status = status;
      });
   // I do not understand the intent here.
   if (not capture_status.ok()) {
      std::cout << capture_status.error_message().c_str() << std::endl;
   }
   auto result = p.get_future();
  result.get();
  return result;
}
```

**Comment by coryan** [comment]
Other than the local variable: any reason you cannot use `MakeAsyncFutureFromCallback`, like we do here:

https://github.com/coryan/google-cloud-cpp/blob/a477b7d75ed2d82d7d0d3f42434036401306cc5c/google/cloud/bigtable/table_admin.cc#L67

**Comment by rsimion** [comment]
please assign it to me, I am already working on AsyncBulkApply
@rsimion

**Comment by rsimion** [comment]
working on it
