### ISSUE TITLE
Implement bigtable::Table::AsyncBulkApply

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#1486]
This function will implement an asynchronous version of `Table::Apply`. The function will have the following signature:

```C++
class google::cloud::bigtable::Table { public:
future<void> AsyncBulkApply(BulkMutation&& mutation, CompletionQueue& cq);
};
```

As part of this work we need to:

- [ ] Implement the function.
- [ ] Implement an integration test for this function.
- [ ] Implement an example for this function.
- [ ] Execute the example as part of the CI build.

The main difference between the example and the integration test is that the latter uses pre-defined values and checks the resulting state against expected outputs, while the former takes (most) of its parameters from the command-line and simply prints out any state.

**Comment by rsimion** [comment]
please assign it to me
@rsimion

**Comment by rsimion** [comment]
It seems that Marek is working on this ticket too, I saw he logged hours for this ticket. What should I do?

**Comment by coryan** [comment]
I have no idea about who bills hours for what, not my problem, adding @sduskis and @dopiera to help you.

For what is woth, @dopiera implemented `bigtable::noex::Table::AsyncBulkApply`. Which looks similar (note the `noex::`) so I am not surprised the tickets may have been confused.

**Comment by dopiera** [comment]
I'm not working on this - It was just a misclick - I logged hours here instead of #1372.

**Comment by rsimion** [comment]
I do not see any example of a future<**void**> that I could follow. The internal AsyncBulkApply looks like this:

//----------------------
  template <**typename Functor,
            typename std::enable_if<
                **google::**cloud**::internal::is_invocable<
                    Functor, CompletionQueue&, std::vector<**FailedMutation**>&,
                    grpc::Status&**>::value,
                int**>::type valid_callback_type = 0>
  std::shared_ptr<AsyncOperation> AsyncBulkApply(CompletionQueue& cq,
                                                 Functor&& callback,
                                                 BulkMutation&& mut) {
...
  }
//----------------------
 
Here is my initial implementation:

//-----------------------
future<**void**> Table::AsyncBulkApply(BulkMutation&& mut, CompletionQueue& cq){
promise<**std::vector<**FailedMutation**>**> pfm;
future<**std::vector<**FailedMutation**>**> resultfm = pfm.get_future();

impl_.AsyncBulkApply(cq,
internal::MakeAsyncFutureFromCallback(std::move(pfm), "AsyncBulkApply"), std::move(mut));

promise<**void**> p;
future<**void**> result = p.get_future(); 

//this is blocking
std::vector<**FailedMutation**> vfm = resultfm.get();

p.set_value();

return result; 
}

What do you suggest?
