### ISSUE TITLE
Implement bigtable::Table::AsyncCheckAndMutateRow

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#1489]
This function will implement an asynchronous version of `Table::ReadRow`. The function will have the following signature:

```C++
class google::cloud::bigtable::Table { public:
template <typename ReadRowFunctor, ...>
future<bool> AsyncCheckAndMutateRow(
    std::string row_key, Filter filter,
    std::vector<Mutation> true_mutations,
    std::vector<Mutation> false_mutations,
    CompletionQueue& cq);
};
```

As part of this work we need to:

- [ ] Implement the function.
- [ ] Implement an integration test for this function.
- [ ] Implement an example for this function.
- [ ] Execute the example as part of the CI build.

The main difference between the example and the integration test is that the latter uses pre-defined values and checks the resulting state against expected outputs, while the former takes (most) of its parameters from the command-line and simply prints out any state.

**Comment by rsimion** [comment]
@coryan 
is this storage or bigtable? the label reads bigtable.?

**Comment by coryan** [comment]
Fixed, thanks!  It is bigtable.
