### ISSUE TITLE
Implement bigtable::TableAdmin::AsyncGenerateConsistencyToken

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#1499]
We want to implement an asynchronous version of `GenerateConsistencyToken` for the interfaces that use exceptions. The signature of this function should look like so:

```C++
class google::cloud::bigtable::TableAdmin { public:
  future<std::string> AsyncGenerateConsistencyToken(
      std::string const& table_id,
      CompletionQueue& cq);
};
```

As part of this work we need to:

- [ ] Implement the function.
- [ ] Implement an integration test for this function.
- [ ] Implement an example for this function.
- [ ] Execute the example as part of the CI build.

The main difference between the example and the integration test is that the latter uses pre-defined values and checks the resulting state against expected outputs, while the former takes (most) of its parameters from the command-line and simply prints out any state.

**Comment by manish-qlogic** [comment]
@coryan 

`noex::TableAdmin` combines both `AsyncGenerateConsistencyToken` and `AsyncCheckConsistency` into one call and call it as 'AsyncAwaitConsistency`. A brief discussion on this [approach](https://github.com/googleapis/google-cloud-cpp/issues/1256#issuecomment-436011235)

1. So do we need to implement a single call `AsyncWaitForConsistency`for `TableAdmin` ?
2. Are there chances for `AsyncGenerateConsistencyToken` and `AsyncCheckConsistency` to be run in isolation?

**Comment by coryan** [comment]
> 1. So do we need to implement a single call `AsyncWaitForConsistency` for `TableAdmin` ?

I would prefer if we did, yes.

> 2. Are there chances for AsyncGenerateConsistencyToken and AsyncCheckConsistency to be run in isolation?

Yes. One could generate the token in one process and wait for it in (one or more) different processes. For example because you want multiple applications to read data that is consistent to some point.

**Comment by manish-qlogic** [comment]
> Yes. One could generate the token in one process and wait for it in (one or more) different processes. For example because you want multiple applications to read data that is consistent to some point.

So if I understood it correctly, we need to implement three APIs. 
 -  `AsyncGenerateConsistencyToken` and `AsyncCheckConsistency`. This will enable user to generate token in separate process and wait for it in another.
- Third one `AsyncWaitForConsistency,` a wrapper to combine first two. This will help user to generate token and check consistency in one go.

Please let me know if this understanding is correct.

**Comment by coryan** [comment]
> So if I understood it correctly, we need to implement three APIs.
> 
> * `AsyncGenerateConsistencyToken` and `AsyncCheckConsistency`. This will enable user to generate token in separate process and wait for it in another.
> * Third one `AsyncWaitForConsistency,` a wrapper to combine first two. This will help user to generate token and check consistency in one go.
> 
> Please let me know if this understanding is correct.

Yup, I think you have that exactly right.
