### ISSUE TITLE
Implement bigtable::InstanceAdmin::AsyncGetIamPolicy

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#1536]
We want to implement an asynchronous version of `GetIamPolicy` for the interfaces that use exceptions. The signature of this function should look like so:

```C++
class google::cloud::bigtable::InstanceAdmin { public:
  future<StatusOr<google::cloud::IamPolicy>> AsyncGetIamPolicy(
      CompletionQueue& cq, std::string const& instance_id);
};
```

As part of this work we need to:

- [ ] Implement the function.
- [ ] Implement an integration test for this function.
- [ ] Implement an example for this function.
- [ ] Execute the example as part of the CI build.

The main difference between the example and the integration test is that the latter uses pre-defined values and checks the resulting state against expected outputs, while the former takes (most) of its parameters from the command-line and simply prints out any state.

**Comment by remyabel** [comment]
Hmm I've been banging my head against a wall for the past few hours trying to get started on this.

```c++
promise<google::cloud::IamPolicy> p;
auto result = p.get_future();

# Just a test
using Functor = decltype(internal::MakeAsyncFutureFromCallback(std::move(p), "AsyncGetIamPolicy"));
static_assert(google::cloud::internal::is_invocable<Functor, CompletionQueue&,
                                                    google::cloud::IamPolicy,
                                                    grpc::Status&>::value,
          "");
```

The `static_assert`/SFINAE fails unless I make the second template parameter `google::cloud::IamPolicy&`. But changing it to that breaks a bunch of code in `internal/instance_admin.h`. I'm probably missing something obvious. Can someone elucidate?

**Comment by coryan** [comment]
The code in `internal/instance_admin.h` is explicitly checking the signature of the functor and expects it to be `void(CompletionQueue&,google::cloud::IamPolicy,grpc::Status&)`.

Note the second argument is by value, that is inconsistent with the other `Async*` member functions, and probably a defect.

We are rethinking the `Async*` APIs, so it might not be the best use of your time to dig into these right now.
