### ISSUE TITLE
Additional credential type: HMAC

### ISSUE THREAD

**Issue by houglum** [googleapis/google-cloud-cpp#1556]
Context: This is branching off from #579 and creating child issues for each unimplemented credential feature that was mentioned there.  We may decide that this isn't needed, but we should have an issue open to track it regardless.

The Storage client library currently supports several OAuth2 credential types.  This issue is tracking the potential idea to add support for using HMAC credentials instead of OAuth2 credentials.

**Comment by coryan** [comment]
After review this is out of scope for GUAC, and impossible to implement for a JSON-based library.  Better open a new issue when we know exactly what we want to implement.
