### ISSUE TITLE
Additional credential type: oauth2 access token, non-refreshing

### ISSUE THREAD

**Issue by houglum** [googleapis/google-cloud-cpp#1557]
Context: This is branching off from #579 and creating child issues for each unimplemented credential feature that was mentioned there.  We may decide that this isn't needed, but we should have an issue open to track it regardless.

The Storage client library currently supports several OAuth2 credential types, each of which is refreshable and allows periodically obtaining new access tokens.  Some other tools and libraries support passing in only an access token -- this is mostly used for debugging purposes, or if you know your program won't take an hour (or whatever the expiry time of the access token is) to finish, and thus won't need to refresh the credential.

**Comment by coryan** [comment]
As an alternative: the application cloud provide a function to return the access token, so the application developer can use both a fixed value (that eventually expires) or automatically refresh the token as needed.

**Comment by coryan** [comment]
FWIW, the changes for #6105 implement the functionality for this, but this is not yet exposed in the public APIs.

**Comment by coryan** [comment]
This was fixed as part of #6640
