### ISSUE TITLE
Support blob signature via project service account.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#1595]
This would be handy when trying to create signed URLs for GCE or GAE credentials:

https://cloud.google.com/iam/reference/rest/v1/projects.serviceAccounts/signBlob

More on:

https://github.com/GoogleCloudPlatform/google-cloud-cpp/pull/1591#discussion_r239198179

**Comment by frankyn** [comment]
Use this instead: https://cloud.google.com/iam/credentials/reference/rest/v1/projects.serviceAccounts/signBlob
