### ISSUE TITLE
Decide if we want to support Xcode 7.3.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#1602]
We got a bug report, the code fails to compile with [Xcode 7.3](https://en.wikipedia.org/wiki/Xcode#7.x_series), which was released around 2015.  The problem is actually in the compiler (e.g. does not support `thread_local`), and will submit a workaround shortly.

We need to decide if the compiler is something we want to support long term, thus this bug to make us revisit the decision.

**Comment by coryan** [comment]
@devjgm @devbww I propose we remove the Xcode 7.3 build, but continue to accept patches if folks volunteer them (to a point, this is technically a pre C++11 compiler). Any thoughts?

**Comment by devjgm** [comment]
I see no problem with dropping support for Xcode 7.x. It's quite old. My contacts in our Apple dev team tell me that Apple devs tend to update compilers (and xcode versions) quickly. Apple requires modern Xcode for distributing apps in their stores too. I believe our internal Apple team only supports the most recent version of Xcode and the latest release of the previous version. So, today, I think that would be 10.1 and 9.4.1. Of course, we may choose to support more Xcode versions that that, but if 7.x doesn't fully support C++11, then I support dropping it.

**Comment by devbww** [comment]
SGTM.

**Comment by coryan** [comment]
I just sent a PR to disable the Xcode 7.3 build.
