### ISSUE TITLE
Define support level for pkg-config based builds.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#1610]
The current CMake configuration supports using [`pkg-config`](https://www.freedesktop.org/wiki/Software/pkg-config/) to discover the flags for our dependencies.  Basically the CMake file calls `pkg-config(1)` to discover what compiler and linker flags are needed to find `libcurl`, or `OpenSSL`, or `protobuf`.

In some Linux distribution it seems like this is the preferred way to configure dependencies (e.g. Gentoo [packages google-cloud-cpp](https://github.com/gentoo/gentoo/tree/master/net-libs/google-cloud-cpp) using `pkg-config(1)`.

I think we have basically three options:

1. Drop the support for `pkg-config(1)` completely, we remove the CMake code that uses `pkg-config(1)` to discover the dependencies.

1. Support `pkg-config(1)` as "contributed", meaning we accept patches to improve it, but do not create a build that runs it or fix the configuration ourselves (this is basically the current support).

1. Support `pkg-config(1)` for "realsies", meaning we create at least one build with it, and keep it working.

**Comment by coryan** [comment]
/cc: @devjgm @frankyn @houglum 

Please discuss below.  My opinion is we should support this for realsies.

**Comment by coryan** [comment]
@remyabel I effectively implemented this suggestion:

> Personally, I think that you should provide your own `FindGrpc` module, since CMake doesn't seem to have one yet.

I think we can remove `pkg-config` as an option.

**Comment by remyabel** [comment]
Yup, thank you for your hard work. We should send them a patch.
