### ISSUE TITLE
Use mutation testing to evaluate test quality

### ISSUE THREAD

**Issue by mbrukman** [googleapis/google-cloud-cpp#171]
Mutation testing can uncover ineffective tests or uncovered conditions without significant manual effort by mutating source code before running the tests and seeing if they still pass. https://github.com/mull-project/mull is an LLVM-based framework for mutation testing, under the Apache 2.0 license.

Per [Wikipedia](https://en.wikipedia.org/wiki/Mutation_testing):

> Mutation testing (or Mutation analysis or Program mutation) is used to design new software tests and evaluate the quality of existing software tests. Mutation testing involves modifying a program in small ways. Each mutated version is called a _mutant_ and tests detect and reject mutants by causing the behavior of the original version to differ from the mutant. This is called _killing_ the mutant. Test suites are measured by the percentage of mutants that they kill. New tests can be designed to kill additional mutants. Mutants are based on well-defined _mutation operators_ that either mimic typical programming errors (such as using the wrong operator or variable name) or force the creation of valuable tests (such as dividing each expression by zero). The purpose is to help the tester develop effective tests or locate weaknesses in the test data used for the program or in sections of the code that are seldom or never accessed during execution. Mutation testing is a form of white-box testing.

**Comment by coryan** [comment]
This is a cool idea but I doubt we will have time to work on it for a while, and we are cleaning up the bug DB.
