### ISSUE TITLE
SafeIdempotentMutationPolicy is too conservative w.r.t. conditional mutations.

### ISSUE THREAD

**Issue by dopiera** [googleapis/google-cloud-cpp#1715]
SafeIdempotentMutationPolicy is overly conservative w.r.t. conditional mutations. It currently considers all Currently, SafeIdempotentMutationPolicy assumes that all conditional mutations are non-idempotent.

There are cases, when idempotence can be assumed. Easy cases include empty mutation lists or always true/false condition.

Some harder are possible to infer too. E.g. if all underlying mutations are idempotent and the set of column families in the condition has an empty intersection with those in the mutations, one can safely call such a conditional mutation idempotent.

Even if the intersection is non-empty, if timestamps are distinct, one could infer idempotence.

**Comment by coryan** [comment]
We are going to close this one until there is demand from a customer.
