### ISSUE TITLE
Create non-const accessors for bigtable::Row to allow move semantics.

### ISSUE THREAD

**Issue by manish-qlogic** [googleapis/google-cloud-cpp#1746]
[bigtable::Row](https://github.com/GoogleCloudPlatform/google-cloud-cpp/blob/608dd154cf3f028982ed46cf436c1de246990f2c/google/cloud/bigtable/row.h#L32) class currently have const& accessors. 
Due to this, copies are created and makes it less efficient. 

Non const accessors needs to be created for `bigtable::Row`. This will enable efficient move of `bigtable::Row`.

**Comment by remyabel** [comment]
I don't think that would help. This example shows that removing `const&` would actually incur a copy:

```c++
#include <iostream>

struct Noisy {
    Noisy() = default;
    Noisy(Noisy&&) {
        std::cout << "Noisy&&\n";
    }
    Noisy(const Noisy&) {
        std::cout << "const Noisy&\n";
    }
    Noisy& operator=(const Noisy&) = default;
    Noisy& operator=(Noisy&&) = default;
};

struct Foo {
public:
    Foo(Noisy a)
        : a_(std::move(a)) { }
        
    Noisy a() const { return a_; }
private:
    Noisy a_;
};

int main() {
    Noisy n;
    Foo f(n);
    (void)f.a();
}
```

This outputs:

```
const Noisy&
Noisy&&
const Noisy& // extra copy
```

**Comment by coryan** [comment]
I think the thought was to add a `Noisy&& a() &&` accessor to your `Foo` class, then we can write `std::move(f).a()` and get move semantics.  This is not without some problems, of course.

**Comment by remyabel** [comment]
Right, my bad. You can still write `std::move(f).a()` with the original code and it will have exactly the same effect. The ref qualifier is not useful in this case since `Row` does not have any need to manage its own resources.

**Comment by manish-qlogic** [comment]
@coryan 

We call row_key() accessor at couple of places to store last_read_row_key_
[row_reader.cc](https://github.com/GoogleCloudPlatform/google-cloud-cpp/blob/a477b7d75ed2d82d7d0d3f42434036401306cc5c/google/cloud/bigtable/row_reader.cc#L271)
[async_row_reader.h](https://github.com/GoogleCloudPlatform/google-cloud-cpp/blob/a477b7d75ed2d82d7d0d3f42434036401306cc5c/google/cloud/bigtable/internal/async_row_reader.h#L102)

So the accessor  `std::string&& row_key() { return std::move(row_key_); }` is getting called twice.  As we are moving the row_key_, second call receives empty string.  

I would require your feedback here.

**Comment by manish-qlogic** [comment]
@coryan 
I presume this is closed.

**Comment by coryan** [comment]
Yes, thanks!
