### ISSUE TITLE
Reduce the build times to fit in Travis limit.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#1800]
Builds starting from a cold cache are failing to complete in the 50 minutes allowed by Travis CI. We need to figure out a way to reduce the build time, or increase the timeout, or both.

**Comment by coryan** [comment]
One idea is to move all the slower builds to Kokoro, where we have 4 cores per build. That would require some refactoring of the Kokoro configuration, and to test Docker running on Kokoro.

**Comment by coryan** [comment]
Another idea is to use Ninja as a backend for CMake. On Windows it made things much faster, the downside is that many customers will not use Ninja, so we should at least test that things compile with just regular make, but we can do that in the Kokoro builds.

Likewise, we could use Bazel for most of the builds, but it is useless for TEST_INSTALL=yes, and I am not sure if we can move the integration tests to it.

**Comment by remyabel** [comment]
For increasing timeouts, it looks like you need to [e-mail travis support](https://github.com/travis-ci/travis-ci/issues/9605#issuecomment-388051236).

**Comment by remyabel** [comment]
There is another potential problem. If the cache doesn't exist, Travis tries to pull the cache from other branches per [the docs](https://docs.travis-ci.com/user/caching/). We can see this in action [#1](https://travis-ci.org/GoogleCloudPlatform/google-cloud-cpp/jobs/476190431) vs [#2](https://travis-ci.org/GoogleCloudPlatform/google-cloud-cpp/jobs/476339751):

```
attempting to download cache archive
fetching PR.1801/cache-linux-trusty-7a870020136782a7f96db54e525836b424b709ef49b7bf83763ff000a1d7912c--compiler-clang.tgz
fetching PR.1801/cache--compiler-clang.tgz
fetching master/cache-linux-trusty-7a870020136782a7f96db54e525836b424b709ef49b7bf83763ff000a1d7912c--compiler-clang.tgz
fetching master/cache--compiler-clang.tgz
could not download cache
0.00s1.06sadding /home/travis/.cache/bazel to cache
creating directory /home/travis/.cache/bazel
adding /home/travis/build/GoogleCloudPlatform/google-cloud-cpp/build-output/ccache to cache
creating directory /home/travis/build/GoogleCloudPlatform/google-cloud-cpp/build-output/ccache
```

```
attempting to download cache archive
fetching PR.1801/cache-linux-trusty-7a870020136782a7f96db54e525836b424b709ef49b7bf83763ff000a1d7912c--compiler-clang.tgz
found cache
0.00s3.43sadding /home/travis/.cache/bazel to cache
creating directory /home/travis/.cache/bazel
adding /home/travis/build/GoogleCloudPlatform/google-cloud-cpp/build-output/ccache to cache
creating directory /home/travis/build/GoogleCloudPlatform/google-cloud-cpp/build-output/ccache
```

I'm not entirely sure if that's the cause of the problem, but I would expect that if it was using the same cache that the dependency stage should build instantly like so:

```
Finished CMake config at: Mon Jan  7 14:57:35 UTC 2019
Started dependency build at: Mon Jan  7 14:57:35 UTC 2019
travis_fold:start:build-dependencies

[ 18%] Built target zlib_project
[ 12%] Built target crc32c_project
[ 31%] Built target c_ares_project
[ 25%] Built target ssl_project
[ 50%] Built target googletest_project
[ 50%] Built target protobuf_project
[ 56%] Built target curl_project
[ 62%] Built target grpc_project
[100%] Built target bigtable_protos
[100%] Built target google-cloud-cpp-dependencies

travis_fold:end:build-dependencies
Finished dependency build at: Mon Jan  7 14:57:35 UTC 2019
```

**Comment by devjgm** [comment]
Is this still a problem since a lot of builds were moved to kokoro, or can this issue be closed?

**Comment by coryan** [comment]
The code coverage build is still on Travis and takes >50 minutes with a clean cache.  Let's close it for now because the workaround (two stage builds, with the first stage just warming up the cache) seems to be working.
