### ISSUE TITLE
Change remaining std::pair<Status, T> to StatusOr<T>.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#1811]
Evidently I missed at least one internal function (`SignString`) that returns `std::pair<Status, T>` and should return `StatusOr<T>`.

**Comment by coryan** [comment]
Fixed in #1810.

**Comment by remyabel** [comment]
Is this actually fixed? It looks like `SignString` still returns `std::pair<Status, std::string>`:

https://github.com/googleapis/google-cloud-cpp/blob/0160ebc1c1caa1b10b9e2f679eaae2fb78cd0e43/google/cloud/storage/oauth2/service_account_credentials.h#L124

**Comment by coryan** [comment]
Evidently not.
