### ISSUE TITLE
Moving this repo to the googleapis org

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/google-cloud-cpp#1849]
All of the repositories we manage today live under the `googleapis` GitHub org:
https://github.com/googleapis

It would be convenient if we could move this over here:
https://github.com/googleapis

If this would cause a significant amount of pain - that would be good to know :)

**Comment by coryan** [comment]
Did we create the repo in the wrong organization?  I seem to recall that other languages have their repositories here.

In any case, mechanically this looks easy enough, there is a button in GitHub to do the transfer.  And according to the [documentation](https://help.github.com/articles/transferring-a-repository/) the existing forks and links continue to work.

* I would like to @-mention all the folks that have forks in a bug to let them know this is coming, their forks will continue to work, but seems polite to do so.
* Existing release links (tarballs) are redirected, so we do not need to worry about folks that have hardcoded `http://github.com/GoogleCloudPlatform/google-cloud-cpp` in their package descriptions and/or their `WORKSPACE` files. However we should let them know so *their* future releases point to the right place. This includes:
  * TensorFlow, they have a hard-coded link in the `WORKSPACE` file.
  * Some Googlers are using the GitHub repository, same thing.
  * Send a patch to vcpkg to update their link.
  * Send a patch to the Gentoo folks that packaged TensorFlow.

* We need to fix the Kokoro configurations, that is easy.
* We need to activate Travis for this new repo, that is easy.

/cc: @devjgm FYI.

**Comment by JustinBeckwith** [comment]
Excellent - thanks for covering this in depth :) Last quarter, we moved all of the cloud and api focused repositories over to `googleapis`, so that was indeed a recent change.  We really counted on the redirects from GitHub working well here, and they did.  Once you're ready to move - just let me know, and I can initiate the transfer.

**Comment by JustinBeckwith** [comment]
Just checking back in.  Before we get the library integrated with our SLO tracking and synthesis tools, it would be really nice to get this moved over :) Is there anything we can do to help this along?

**Comment by coryan** [comment]
@dopiera @manish-qlogic @rsimion @remyabel @houglum @devbww @devjgm FYI:

We are planning to move the repository today around 4:00pm EST.  The existing PRs, links, issues, etc. should continue to work, so this is a minimal risk change.

**Comment by coryan** [comment]
@JustinBeckwith thank you for moving the repo.  Most things seem to be working. Is there any chance you could add reviewable.io to the organization?  We use it for the more complex code reviews and it is really helpful.

I believe i will need to make some changes to Kokoro to pick up the builds, planning to do that tomorrow so I have assigned this bug to myself.

**Comment by coryan** [comment]
@JustinBeckwith ping about `reviewable.io` any thoughts?

**Comment by JustinBeckwith** [comment]
I would love to do that - but I can't for the life of me figure out how 😆 Is this available in the GitHub marketplace?

**Comment by coryan** [comment]
Sorry about that, I was hoping you would have received an email requesting the app.  The application is here:

https://github.com/settings/connections/applications/7da38b6fb966259af6d5

this is what shows on my screen:

![image](https://user-images.githubusercontent.com/6241635/52083771-5b4e5000-256e-11e9-95a9-b772b62074d9.png)


I think if you login to https://reviewable.io/ using your GitHub account it walks you through the steps to add the application to the organization.

**Comment by devjgm** [comment]
@JustinBeckwith I'm curious: what do your other teams use for code review if not reviewable.io? The GitHub UI? Gerrit? Something else?

**Comment by coryan** [comment]
It is working, yay! :tada: :balloon: :tada: :balloon:

**Comment by coryan** [comment]
I think we can close this bug now.

**Comment by JustinBeckwith** [comment]
Awesome :) That invite link was what I was missing.  

> I'm curious: what do your other teams use for code review if not reviewable.io? The GitHub UI? Gerrit? Something else?
We just use the GitHub PR UR 🤷‍♂️
