### ISSUE TITLE
Upgrade to googletest and replace TEST_CASE with TEST_SUITE.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#1861]
The newer versions of googletest, including the internal version use `TEST_SUITE` instead of `TEST_CASE`, which is more standard naming. As there is no release of googletest, we need to update to a commit, currently google/googletest@b6cd405286ed8635ece71c72f118e659f4ade3fb was recommended by @gennadiycivil.

**Comment by remyabel** [comment]
Of course I neglected to also cover the Bazel build, which is why #1894 is failing. Commenting here to remind myself to fix that later.

**Comment by remyabel** [comment]
As mentioned in the PR I believe the error stems from needing to use a newer gtest for the Windows build. We can:

- Wait for new gtest release, or
- Set `GOOGLE_CLOUD_CPP_GMOCK_PROVIDER=external` and don't install it via vcpkg

What do you think?

**Comment by coryan** [comment]
I think the second option is better.

**Comment by coryan** [comment]
This was fixed in #2075.
