### ISSUE TITLE
Cleanup multiple bugs in storage/client.h documentation.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#1888]
We need to cleanup the documentation a bit, see the document prepared by @frankyn for details.

**Comment by coryan** [comment]
@frankyn I think this is now fixed, all the changes have been merged, please let me know if I missed anything.

**Comment by frankyn** [comment]
Thanks @coryan. Linking back to IamPolicy from SetIamPolicy() is the last item I had. Should I create another bug to track that?

**Comment by frankyn** [comment]
#1914 was opened to address that. Acking
