### ISSUE TITLE
Design full build matrix and implement it.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#19]
We need to gather some data and then complete the definition of the build matrix.  There is an skeleton in #8, but that won't be enough.   And a full NxMxK matrix of all combinations of compiler, platform, and build options would be overkill.

The design should answer these questions:

* What version of gRPC we support?
* What distributions of Linux we support?
* What compilers and versions we plan to support?
* For Windows, we need to get specific with MSVC versions

**Comment by coryan** [comment]
@mbrukman any news on running a survey to get answers to those questions?

**Comment by mbrukman** [comment]
@coryan — I will do this after the holidays; I was afraid the survey would be missed if sent just before everyone left for the winter holidays in December.

**Comment by coryan** [comment]
As an additional requirement on this bug: consider changing the order of the environment variables in the `.travis.yml` file so what is most interesting about the build (e.g., it uses `AddressSanitizer`) is the first environment variable instead of the last one.  That makes the interesting stuff immediately visible in Travis page.

**Comment by coryan** [comment]
@mbrukman assigning this one to you, because you need to provide some input.

**Comment by coryan** [comment]
For what is worth: it seems that some Abseil libraries do not compile under 32-bit Windows, so the build matrix does not need to concern itself with that platform.

**Comment by coryan** [comment]
@mbrukman should we close this and declare success with the current matrix?

**Comment by coryan** [comment]
I am taking this over, the current (internal to Google only) is go/cbt-cpp:build-matrix

**Comment by coryan** [comment]
Time to close this, the build matrix we have needs to be tweaked, but this bug no longer is useful.
