### ISSUE TITLE
Support policy documents with V2 Signed URLs.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#1932]
Figure out how to create signed URLs that support this:

https://cloud.google.com/storage/docs/xml-api/post-object#usage_and_examples

**Comment by remyabel** [comment]
Question. What does policy documents have to do with signed URL's in particular? As I understand it, `GoogleAccessId` is used for both, but otherwise they are independent/separate, correct?

**Comment by remyabel** [comment]
Continuing discussion here. I'm confused about why `PolicyDocumentParser` should be removed. There are two ways the user can build a policy document, either using the API i.e:

```
PolicyDocument doc;
doc.conditions.emplace_back(PolicyDocumentCondition::StartsWith("key", ""));
```

Or by supplying a string, parsing it, then deserializing it into a `PolicyDocument`:

```
std::string doc = "...";
// The following will call PolicyDocumentParser::FromJson to do the actual parsing
PolicyDocument doc = PolicyDocumentParser::FromString(doc);
```

I think that supplying it as a string is a valid use-case, even though our library is not going to make the POST request ourselves. Thoughts?

Side question: should we output the result request string (like I am currently doing) or just provide the `PolicyDocument` object?

**Comment by coryan** [comment]
> Continuing discussion here. I'm confused about why `PolicyDocumentParser` should be removed.

Maybe it should not, I was just not seeing the need.

> There are two ways the user can build a policy document, either using the API i.e:
> 
> ```
> PolicyDocument doc;
> doc.conditions.emplace_back(PolicyDocumentCondition::StartsWith("key", ""));
> ```
> Or by supplying a string, parsing it, then deserializing it into a `PolicyDocument`:
> 
> ```
> std::string doc = "...";
> // The following will call PolicyDocumentParser::FromJson to do the actual parsing
> PolicyDocument doc = PolicyDocumentParser::FromString(doc);
> ```
> I think that supplying it as a string is a valid use-case, even though our library is not going to make the POST request ourselves. Thoughts?

So in the second case we parse the string, convert to a policy doc, then convert back to string and sign that?  Do we need the intermediate deserialized string for something?  Or can we just sign whatever string they give us?

A second question: we do not know if there is demand for creating policy docs from strings. Maybe we can implement one overload with `PolicyDocument` and add the parser later if anybody asks for it?


> 
> Side question: should we output the result request string (like I am currently doing) or just provide the `PolicyDocument` object?

Do you mean here?

https://github.com/googleapis/google-cloud-cpp/pull/2359/files#diff-e6a6912329125a45ed85f5192fb6d29fR271

I think just a string won't work. I am trying to think how somebody would use this functionality.  They will need to create a form as described at the end of this document:

https://cloud.google.com/storage/docs/xml-api/post-object#usage_and_examples

To do that they need the `GoogleAccessId`, `policy`, and `signature` fields separated, so they can create the form (I think), they (or the browser under their instructions) will need to aggregate those back *into* a URL as part of making the POST request.

So I think you want to return a `StatusOr<PolicyDocumentSignature>` where `PolicyDocumentSignature` is a struct that contains the `AccessId`, `Expires`, `Policy`, and `Signature` strings you are pasting here:

https://github.com/googleapis/google-cloud-cpp/pull/2359/files#diff-e6a6912329125a45ed85f5192fb6d29fR296

**Comment by remyabel** [comment]
> So in the second case we parse the string, convert to a policy doc, then convert back to string and sign that? Do we need the intermediate deserialized string for something? Or can we just sign whatever string they give us?

That is a good point and for some reason wasn't registering in my brain. I'll remove it.

> So I think you want to return a StatusOr<PolicyDocumentSignature> where PolicyDocumentSignature is a struct that contains the AccessId, Expires, Policy, and Signature strings you are pasting here:

Agreed.
