### ISSUE TITLE
Return StatusOr from bigtable::TableAdmin::ListSnapshots

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#1952]
Rather than throwing on error, return StatusOr. The signature should look like the following:

```c++
  template <template <typename...> class Collection = std::vector>
  StatusOr<Collection<::google::bigtable::admin::v2::Snapshot>> ListSnapshots(
      bigtable::ClusterId cluster_id = bigtable::ClusterId("-"));
```

See https://github.com/googleapis/google-cloud-cpp/pull/1908 for an example.

**Comment by coryan** [comment]
This might be an opportunity to simplify this API, I think I overengineered the design to make the collection type optional, if we are going to break backwards compatibility we could change it to return:

```C++
StatusOr<std::vector<google::bigtable::admin::v2::Snapshot>> ListSnapshots(...);
```

**Comment by devjgm** [comment]
SGTM. I was thinking of that too.
