### ISSUE TITLE
Mutation batching ignores cancellation.

### ISSUE THREAD

**Issue by dopiera** [googleapis/google-cloud-cpp#1963]
It should be fairly easy to add cancellation of requests which have not been sent out.

We could potentially keep track of cancelled `SingleRowMutations` and cancel the whole batch if all it mutations have either completed or been cancelled.

**Comment by coryan** [comment]
Keep it open.

**Comment by coryan** [comment]
Leave it open but @coryan wants to kill it with fire.

**Comment by dbolduc** [comment]
The juice is not worth the squeeze. Closing.
