### ISSUE TITLE
Table::Apply() needs to be changed to use StatusOr or Status for void

### ISSUE THREAD

**Issue by rsimion** [googleapis/google-cloud-cpp#1969]
void Table::Apply(SingleRowMutation&& mut)

Files affected:

/bigtable/examples/data_snippets.cc
void Apply()

/bigtable/examples/bigtable_hello_world.cc

/bigtable/examples/bigtable_hello_app_profile.cc
/bigtable/benchmarks/endurance_benchmark.cc
/bigtable/benchmarks/apply_read_latency_benchmark.cc
/bigtable/benchmarks/embedded_server_test.cc

/bigtable/tests/data_integration_test.cc
void DataIntegrationTest::Apply
TEST_F(DataIntegrationTest, TableApply)

/bigtable/table_apply_test
TEST_F(TableApplyTest, Simple)
TEST_F(TableApplyTest, Failure)
TEST_F(TableApplyTest, Retry)
TEST_F(TableApplyTest, RetryIdempotent)

/bigtable/tests/mutations_integration_test.cc
TEST_F(MutationIntegrationTest, DeleteFromColumnForTimestampRangeTest)
TEST_F(MutationIntegrationTest, DeleteFromColumnForReversedTimestampRangeTest)
TEST_F(MutationIntegrationTest, DeleteFromColumnForAllTest)
TEST_F(MutationIntegrationTest, DeleteFromColumnForEmptyTimestampRangeTest)
TEST_F(MutationIntegrationTest, DeleteFromColumnStartingFromTest)
TEST_F(MutationIntegrationTest, DeleteFromColumnEndingAtTest) 
TEST_F(MutationIntegrationTest, DeleteFromFamilyTest) 
TEST_F(MutationIntegrationTest, DeleteFromRowTest)

**Comment by rsimion** [comment]
@coryan 
Following your suggestions in #2003, here are some approaches for Table::Apply()

```C++
void Table::Apply(SingleRowMutation&& mut) {
  std::vector<FailedMutation> failures = impl_.Apply(std::move(mut));
    if (failures.empty()) {
      return;
    }    
    for (auto&& f : failures) {
    std::cerr << "Operation " << f.original_index() 
                  << " failed with " << f.status().error_message() << '\n';  
    }
}
```

or 

```C++
StatusOr<std::vector<FailedMutation>> Table::Apply(SingleRowMutation&& mut) {
  std::vector<FailedMutation> failures = impl_.Apply(std::move(mut));
  if (!failures.empty()) {
    grpc::Status status = failures.front().status();
    if (!status.ok()) {
      return bigtable::internal::MakeStatusFromRpcError(status);
    }
  }
  return failures;	
}
```

or

```C++
StatusOr<std::vector<FailedMutation>> Table::Apply(
    SingleRowMutation&& mut) {
  std::vector<FailedMutation> failures = impl_.Apply(std::move(mut));
  if (!failures.empty()) {
      for (auto&& f : failures) {
        std::cerr << "Operation " << f.original_index() << " failed with "
                  << f.status().error_message() << '\n';
      }
 
  }
  return failures;
}
```

**Comment by coryan** [comment]
I think returning `Status` is the right thing to do here:

```c++
google::cloud::Status Table::Apply(SingleRowMutation&& mut) {
  std::vector<FailedMutation> failures = impl_.Apply(std::move(mut));
  if (failures.empty()) {
    return google::cloud::Status{};
  }
  // assert(failures.size() == 1);
  return /* TODO convert to google::cloud::Status */ failures.front();
}
```
