### ISSUE TITLE
Consider replacing `std::endl` with '\n' or "\n"

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#1978]
We use `std::endl` in most of our output streams as a means to output a newline. However, `std::endl` also implies a call to `os.flush()`, which is often either redundant or potentially has a negative performance consequence. Additionally, the code generated when using `std::endl` is more complicated as shown in this godbolt example: https://godbolt.org/z/SJbCPE

Note that the C++ Core Guidelines recommend avoiding endl: https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#slio50-avoid-endl

Finally, a tiny nit: use of `std::endl` is more characters and may cause unnecessary line wrapping.

**Questions**

* Are there any places (or maybe custom stream classes) that *require* an explicit flush after each line? If so, should those calls be written with an explicit call to flush() instead on relying on endl's implicit flush?

**Proposal**

My proposal is to follow the recommendation of the core guidelines in this case and avoid `endl`. Instead, we should use `'\n'` (or `"\n"`), within an existing string if possible, otherwise on its own (e.g., `<< "\n";`).

**NOTE:** This is a non-urgent and low-priority change. But it would also be a pretty easy textual change to make to the codebase, so it's probably still work considering and deciding one way or the other.

Thoughts?
/cc: @coryan 
/cc: @devbww

**Comment by devbww** [comment]
+1 from me.

**Comment by coryan** [comment]
If we are using `std::endl` anywhere in the critical path then that is a bug and we should fix it.  If we are showing users to use `std::endl` in an upload or something that is also a bug and we should fix them.

That is where my strong opinions stop, the rest is just mild preferences.

The uses in the examples with `std::cout` are harmless (the program exits right after printing anything).  I do not think it matters if we remove them in favor of `"\n"` or we leave then as they are.

If it is easier to replace them everywhere, then go for it.
