### ISSUE TITLE
Change status/statusor assertions to use ASSERT_OK

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#1990]
In PR #1988 `ASSERT_OK` and `EXPECT_OK` macros were added. We should start using those for all assertions with either a `Status` or `StatusOr<T>`. Current test calls that look like:

```cc
Status x = ...;
ASSERT_TRUE(x.ok()) << "blah blah";
```
Should be changed to
```cc
Status x = ...
ASSERT_OK(x);
```

If it's possible to write that all on one line (if `x` is not used again), that's fine too.

We should do the same for `StatusOr<T>`.

**Comment by coryan** [comment]
I think the "it is required for `Status`" means "it is required for `google::cloud::Status`".  We do not need one for `grpc::Status`.
