### ISSUE TITLE
Implement a failed Status matcher.

### ISSUE THREAD

**Issue by dopiera** [googleapis/google-cloud-cpp#1999]
@devbww suggested that we should have an easy way to expect a particular (set of) non-OK value(s) in tests.

That would probably be along the lines of `EXPECT_THAT(status, IsNotOk())`

**Comment by mr-salty** [comment]
I added a reasonable facsimile of `StatusIs` and `IsOk` in [testing_util/status_matchers.h](https://github.com/googleapis/google-cloud-cpp/blob/master/google/cloud/testing_util/status_matchers.h); migrating to absl should be straightforward if we need to.

I'd also like to add `IsOkAndHolds`

**Comment by devbww** [comment]
The only thing I see is the _"I'd also like to add `IsOkAndHolds`"_ from @mr-salty.

**Comment by devjgm** [comment]
Moved that new request to a separate issue: https://github.com/googleapis/google-cloud-cpp/issues/5606
