### ISSUE TITLE
Change Table::BulkApply to work with StatusOr.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#2003]
When there are failed mutations, `google::cloud::bigtable::Table::BulkApply` raises an exception with the failed mutations. We should change this function to not require exceptions.

I am not certain of the right solution, so I will propose some ideas below.

**Comment by coryan** [comment]
One solution is to always return a vector of `google::cloud::Status` objects, with the same number of elements as the BulkApply request.  The elements in this list would be all `OK` if there are no errors.
The vector would be wrapped in a `StatusOr` to deal with the case where nothing worked.

**Comment by coryan** [comment]
Another solution is to return a vector, potentially empty, of the mutations that failed. Wrapped in a StatusOr.

**Comment by coryan** [comment]
Option 1:

```C++
namespace cbt = google::cloud::bigtable;
void F(Table table, BulkMutation mutation) {
    std::vector<google::cloud::Status> failures = table.BulkApply(std::move(mutation));
    if (failures.empty()) {
      return;
    }
    std::size_t index = 0;
    for (auto&& status : failures) {
      if (status.ok()) {
        ++index;
        continue;
      }
      std::cerr << "Operation " << index << " failed with " << status << '\n';  
    }
}
```

**Comment by coryan** [comment]
Option 2:

```C++
namespace cbt = google::cloud::bigtable;
void F(Table table, BulkMutation mutation) {
    StatusOr<std::vector<google::cloud::Status>> failures = table.BulkApply(std::move(mutation));
    if (!failures) {
      std::cerr << "All mutations failed\n";
      return;
    }
    std::size_t index = 0;
    for (auto&& status : *failures) {
      if (status.ok()) {
        ++index;
        continue;
      }
      std::cerr << "Operation " << index << " failed with " << status << '\n'; 
     ++index;
    }
}
```

**Comment by coryan** [comment]
Option 3:

```C++
namespace cbt = google::cloud::bigtable;

struct MutationFailure { std::size_t original_index; google::cloud::Status status; };

void F(Table table, BulkMutation mutation) {
    std::vector<MutationFailure> failures = table.BulkApply(std::move(mutation));
    if (failures.empty()) {
      return;
    }
    for (auto&& f : failures) {
      std::cerr << "Operation " << f.original_index << " failed with " << f.status << '\n';  
    }
}
```

**Comment by coryan** [comment]
Option 4:

```C++
namespace cbt = google::cloud::bigtable;

struct MutationFailure { std::size_t original_index; google::cloud::Status status; };

void F(Table table, BulkMutation mutation) {
    StatusOr<std::vector<MutationFailure>> failures = table.BulkApply(std::move(mutation));
    if (!failures) {
      std::cerr << "All mutations failed\n";
      return;
    }
    for (auto&& f : *failures) {
      std::cerr << "Operation " << f.original_index << " failed with " << f.status << '\n'; 
    }
}
```

**Comment by coryan** [comment]
@googleapis/yoshi-cpp and @dopiera @manish-qlogic @rsimion I like Option 3 the best, but looking for opinions on how we should be implementing this.

**Comment by rsimion** [comment]
I like both, Option 3 and 4. Option 4 is consistent with using StatusOr.

**Comment by dopiera** [comment]
I'd vote for either option 1 or 3 with no strong preference for either.

The reason why I don't like wrapping the whole thing in `StatusOr<>` is that it is not clear to me what value it would bring.

I couldn't find any documentation, but I believe that the whole stream of responses can fail only with a transient error (`UNAVAILABLE` / `ABORTED`) or `DEADLINE_EXCEEDED` or `CANCELLED`. This is because `WritesDone` doesn't take any `Status`. In a common case these will be retried and will cover only a subset of mutations (because others would succeed in previous attempts), so I don't think there is any value in such a thing to the user - they should inspect individual mutations anyway.

BTW, when reading the code, I discovered that BulkMutator could be much more descriptive with errors and file #2048.

**Comment by devjgm** [comment]
fwiw, I prefer option 3.

**Comment by coryan** [comment]
I think we have consensus on Option 3. :tada: :tada: :tada:

**Comment by rsimion** [comment]
@coryan
So table.cc, Option 3(it does not use StatusOr or Status)

```C++
void Table::BulkApply(BulkMutation&& mut) {
	grpc::Status status;
    std::vector<FailedMutation> failures = impl_.BulkApply(std::move(mut), status);
    if (failures.empty()) {
      return;
    }
    for (auto&& f : failures) {
      std::cerr << "Operation " << f.original_index() 
	  << " failed with " << f.status().error_message() << " ["
      << f.status().error_code() << "]\n";
    }
}
```

or

```C++
StatusOr<std::vector<FailedMutation> Table::BulkApply(BulkMutation&& mut) {
  grpc::Status status;
  std::vector<FailedMutation> failures =
      impl_.BulkApply(std::move(mut), status);
  if (!status.ok()) {
    return bigtable::inter:nal::MakeStatusFromRpcError(status);
  }
  return failures;
}
```

or ?

**Comment by coryan** [comment]
It should be:

```C++
std::vector<FailedMutation> Table::BulkApply(BulkMutation&& mut) {
  grpc::Status status;
  std::vector<FailedMutation> failures =
      impl_.BulkApply(std::move(mut), status);
  if (!status.ok()) {
    /* fill out `failures` with N copies of `status` based on the length of `mut`. */
  }
  return failures;
}
```

**Comment by rsimion** [comment]
@coryan 
I am not sure about 
```C++
  if (!status.ok()) {
    /* fill out `failures` with N copies of `status` based on the length of `mut`. */
  }
```

Here is my understanding:

Each element(a FailedMutation object) of `failures`  has 3 variables: 
SingleRowMutation, grpc::Status, int
 
SingleRowMutation has 2 variables:
string, google::protobuf::RepeatedPtrField<google::bigtable::v2::Mutation>

Do you mean something like 
```C++  
 if (!status.ok()) {
  for(auto& f: failures){
	SingleRowMutation f_mut = f.mutation();
	grpc::Status f_stat = status;
	int f_indx = f.original_index();
	
      //  Add a new constructor to FailedMutation
     //  FailedMutation(SingleRowMutation mut, grpc::Status status, int index)
     //  : mutation_(std::move(mut)),
     //   status_(status),
     //   original_index_(index) {}
	//
	//
	f = FailedMutation(f_mut, f_stat, f_indx); 
      }
  }
```	
?
 
BulkMutation has one variable: 
MutateRowsRequest  

`mut` has already been moved

  How do I find the length of `mut`?
  And how do I relate it to `status`?

**Comment by coryan** [comment]
> How do I find the length of `mut`?

I guess you will need to save it before moving?

> And how do I relate it to `status`?

I am not sure I follow that.  You will probably need to do something like:

```
if (!status.ok()) {
  for (std::size_t i = 0; i != save_mut_length; ++i) {
    google::cloud::Status s = MakeStatusFromGrpcError(status);
    failures.emplace_back(FailedMutation(/* some empty placeholder */, s, i));
  }
}
```

**Comment by rsimion** [comment]
@coryan 

I meant what do you mean by length of `mut`?

Also the FailedMutation constructor as it is now it takes a google:::rpc::Status only. It is then converted to grpc::Status  

So I need to add a new variable and a new constructor to FailedMutation

**Comment by coryan** [comment]
> I meant what do you mean by length of `mut`?

Oh, you may need to fix #2062 first, sorry.

> Also the FailedMutation constructor as it is now it takes a google:::rpc::Status only. It is then converted to grpc::Status
> So I need to add a new variable and a new constructor to FailedMutation

You are right, of course.

**Comment by rsimion** [comment]
Ok, I will assign  #2062 to myself

**Comment by rsimion** [comment]
@coryan 

Only a few files first.

[Table::BulkApply my fork](https://github.com/rsimion/google-cloud-cpp/commit/70ba7165f4fb23f225ebbdf2f4e4028023d2ad08)
