### ISSUE TITLE
Consider mentioning CMAKE_EXPORT_COMPILE_COMMANDS in the docs

### ISSUE THREAD

**Issue by remyabel** [googleapis/google-cloud-cpp#2021]
[CMAKE_EXPORT_COMPILE_COMMANDS](https://cmake.org/cmake/help/latest/variable/CMAKE_EXPORT_COMPILE_COMMANDS.html) is a useful flag that when enabled outputs a JSON file that can be used with code completion engines like [YouCompleteMe](https://github.com/Valloric/YouCompleteMe), allowing them to have their code statically analyzed by libclang on the fly while inside a text editor. Perhaps this can go into `CONTRIBUTING.md`.

**Comment by devjgm** [comment]
I was recently wanting this too. I added it on the command-line for my own needs.

Q: Perhaps we should just set `CMAKE_EXPORT_COMPILE_COMMANDS` in cmake always. I think it's pretty cheap and I don't think there's any downsides.

**Comment by coryan** [comment]
Good news: CMAKE_EXPORT_COMPILE_COMMANDS requires CMake 3.5, and we already require that, we would have been in trouble if we required only CMake 3.4.

PRs welcome :grin:    If you do send a PR, please consider adding the generated json file to the `.gitignore` file.

**Comment by remyabel** [comment]
I don't think this can be done without making undesirable changes. It generates something like this:

```
...snip... 
-I/path/to/repos/google-cloud-cpp-1 -I/path/to/repos/google-cloud-cpp-1/build -isystem /path/to/repos/google-cloud-cpp-1/build/external/include 
...snip...
```

Which of course are incomplete/incorrect include directories. This makes sense given we are using `target_include_directories` like:

```cmake
target_include_directories(bigtable_protos
                           PUBLIC $<BUILD_INTERFACE:${CMAKE_CURRENT_BINARY_DIR}>
                                  $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}>
                                  $<INSTALL_INTERFACE:include>)
```

But I think this is a deficiency in how CMake calculates the include directories for `compile_commands.json`.

**Comment by devjgm** [comment]
I don't fully understand the problem you're referring to about cmake and its incomplete include directories. But it sounds like you're saying there's a cmake bug. Do you know if this bug has been filed w/ them? I'm curious if they are aware of it, fixing it, and/or have a workaround.

**Comment by remyabel** [comment]
Upon further testing, `compiledb` has the exact same problem, so it isn't a CMake bug then. Try this opening `google/cloud/storage/internal/object_requests.h`. You should get an error like `no type named 'json' in namespace 'google_cloud_storage_internal_nlohmann_3_4_0'`. So either the correct include directory is not being detected or my setup is wonky.

**Comment by remyabel** [comment]
Alright, I'm an idiot. I forgot the `nlohmann_json.hpp` is added by the install target.
