### ISSUE TITLE
storage: support batch operations

### ISSUE THREAD

**Issue by frankyn** [googleapis/google-cloud-cpp#2046]
This is a general request to support the Batch Operations API in the GCS library.

https://cloud.google.com/storage/docs/json_api/v1/how-tos/batch

**Comment by coryan** [comment]
I really would prefer if we did not.

If we need to have multiple operations "at the same time" then asynchronous APIs are a better abstraction, and are more future proof.

**Comment by frankyn** [comment]
Potentially this could be more of an implementation detail. The library surface API would introduce batching helpers then implementation could either multiplex or use the JSON Batch API. 

At the moment the win with the JSON Batch API is it's a single request that's handled by the GCS API reducing request overhead from performing separate requests.

**Comment by coryan** [comment]
We reviewed this, closing in favor of async operations
