### ISSUE TITLE
Use StatusOr in TableAdmin::CreateTableFromSnapshot.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#2061]
I think the signature should be:

```C++
class TableAdmin {
public:
  future<StatusOr<::google::bigtable::admin::v2::Table>> CreateTableFromSnapshot(...) { ... }
```

Note the use of `::google::cloud::future<>` and `::google::cloud::StatusOr<>`.

**Comment by remyabel** [comment]
Is that supposed to be `google::bigtable::admin::v2::Table`? I don't see any signature that returns a Snapshot.

**Comment by coryan** [comment]
Doh! Yes.
