### ISSUE TITLE
Return StatusOr from InstanceAdmin::*Impl()

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#2080]
Remove the calls to `bigtable::internal::ThrowRpcError()` and return `StatusOr<>` instead.

**Comment by rsimion** [comment]
@coryan 
I am not sure I follow.
I checked /bigtable/internal/instance_admin.cc and /bigtable/instance_admin.cc and I did not find any reference to ```bigtable::internal::ThrowRpcError()```. 
Unless I am missing something.

**Comment by coryan** [comment]
Check the comments in #2081.  I think @remyabel removed all the uses of `ThrowRpcError()`, but they did not want to close this bug because some functions do not return `StatusOr`. Can you update this bug with any functions that do not return `StatusOr<>` or `Status` to indicate errors?

**Comment by rsimion** [comment]
Every function in /bigtable/instance_admin.h and /bigtable/instance_admin.cc has

 ```Status or StatusOr or future<StatusOr<>>```

Close it?

**Comment by remyabel** [comment]
I think @dopiera covered the rest. `git log -S` shows him covering a lot (if not all) of the functions to `StatusOr`.

**Comment by coryan** [comment]
Thanks to both of you for checking, closing.
