### ISSUE TITLE
Remove bigtable::internal::ThrowRpcError()

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#2081]
Since we are converting to only returning `StatusOr<>`.

**Comment by remyabel** [comment]
Please assign me to this as well as #2080 and #2079.

**Comment by remyabel** [comment]
Started this, but I've run into a brickwall. Getting a seg fault here: 

https://github.com/remyabel/google-cloud-cpp-1/blob/d5de5bea5fbb192a073c326092b49c3ae4d8252a/google/cloud/bigtable/tests/instance_admin_async_future_integration_test.cc#L231-L233

**Comment by devbww** [comment]
```
  google::cloud::StatusOr<btadmin::Cluster> cluster_copy;
  cluster_copy->CopyFrom(*cluster);
```
The default constructor for the StatusOr will yield a (bad) Status, not a (default constructed) T, so there is no valid Cluster to copy into.  Try ``cluster_copy = *cluster;``

**Comment by remyabel** [comment]
Thanks @devbww.
