### ISSUE TITLE
Remove `noex::TableAdmin`

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#2098]
This is a placeholder, we will need to break it down into smaller tasks, now that `bigtable::TableAdmin` uses `StatusOr<>` we do not need `noex::TableAdmin`. We should remove the class.

If we do it in a single PR, then it is "easy", but it would be such a large PR that nobody would volunteer to review it.

I think we need to:

- Expose the `client()` from `noex::TableAdmin`.
- Move the implementation of each member function from `noex::TableAdmin` to `bigtable::TableAdmin`.
- Then remove `noex::TableAdmin`.

**Comment by manish-qlogic** [comment]
There are some tests cases as well that would need cleaning like [here](https://github.com/googleapis/google-cloud-cpp/blob/db6e3c9c8dc3da550320d2af0c60574566795242/google/cloud/bigtable/tests/admin_async_integration_test.cc#L35) and other places.

**Comment by manish-qlogic** [comment]
> * Expose the `client()` from `noex::TableAdmin`.

`TableAdmin` is already a [friend](https://github.com/googleapis/google-cloud-cpp/blob/db6e3c9c8dc3da550320d2af0c60574566795242/google/cloud/bigtable/internal/table_admin.h#L46) of `noex::TableAdmin` and we are using client already at [some places](https://github.com/googleapis/google-cloud-cpp/blob/db6e3c9c8dc3da550320d2af0c60574566795242/google/cloud/bigtable/table_admin.cc#L149). 

Why do we need to expose `client` which is already accessible?

> * Move the implementation of each member function from `noex::TableAdmin` to `bigtable::TableAdmin`.

looks like we wont be able to expose `op->Cancel()` to the application user?

**Comment by manish-qlogic** [comment]
> > * Move the implementation of each member function from `noex::TableAdmin` to `bigtable::TableAdmin`.
> 
> looks like we wont be able to expose `op->Cancel()` to the application user?

#1289 talks about it in greater depth.

**Comment by manish-qlogic** [comment]
here is the list of member functions to be moved ;

- [ ] Move `CreateTable`
- [ ] Move `AsyncCreateTable`
- [ ] Move `ListTables`
- Implement `AsyncListTables` in `TableAdmin`  (#1494)
- [ ] Move `GetTable`
- [ ] Move `AsyncGetTable`
- [ ] Move `DeleteTable`
- [ ] Add `AsyncDeleteTable`

- [ ] Move `ModifyColumnFamilies`
- [ ] Add `AsyncModifyColumnFamilies`
- [ ] Move `DropRowsByPrefix`
- [ ] Add `AsyncDropRowsByPrefix`
- [ ] Move `DropAllRows`
- [ ] Add `AsyncDropAllRows`

- [ ] Move `GenerateConsistencyToken`
- [ ] Move `CheckConsistency`
- [ ] Move `WaitForConsistencyCheckHelper`
- [ ] Add `AsyncAwaitConsistency`

- [ ] Move `GetSnapshot`
- [ ] Add `AsyncGetSnapshot`
- [ ] Move `DeleteSnapshot`
- [ ] Add `AsyncDeleteSnapshot`
- [ ] Move `ListSnapshots`
- Implement `AsyncListSnapshot` in `TableAdmin`  (#1258, #1506)

**Comment by coryan** [comment]
@manish-qlogic I am going to proceed and remove `noex::TableAdmin`. We can write the last function in `bigtable::TableAdmin` afterwards.

**Comment by coryan** [comment]
The class is removed, the remaining work is tracked in #1500.
