### ISSUE TITLE
Remove `noex::InstanceAdmin`

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#2099]
This is a placeholder, we will need to break it down into smaller tasks, now that `bigtable::InstanceAdmin` uses `StatusOr<>` we do not need `noex::InstanceAdmin`. We should remove the class.

If we do it in a single PR, then it is "easy", but it would be such a large PR that nobody would volunteer to review it.

I think we need to:

- Expose the `client()` from `noex::InstanceAdmin`.
- Move the implementation of each member function from `noex::InstanceAdmin` to `bigtable::InstanceAdmin`.
- Then remove `noex::InstanceAdmin`.

**Comment by manish-qlogic** [comment]
List of functions that we need to move;
# Sync APIs
 - [ ] Move `ListInstances`
 - [ ] Move `GetInstance`
 - [ ] Move `DeleteInstance`
 - [ ] Move `ListClusters`
 - [ ] Move `GetCluster`
 - [ ] Move `DeleteCluster`
 - [ ] Move `UpdateAppProfile`
 - [ ] Move `CreateAppProfile`
 - [ ] Move `GetAppProfile`
 - [ ] Move `ListAppProfiles`
 - [ ] Move `DeleteAppProfile`
 - [ ] Move `GetIamPolicy`
 - [ ] Move `SetIamPolicy`
 - [ ] Move `TestIamPermissions`

# Async APIs
 - [ ] Move `AsyncListInstances`
 - [ ] Move `AsyncCreateInstance`
 - [ ] Move `AsyncUpdateInstance`
 - [ ] Move `AsyncGetInstance`
 - [ ] Move `AsyncDeleteInstance`
 - [ ] Move `AsyncListClusters`
 - [ ] Move `AsyncGetCluster`
 - [ ] Move `AsyncDeleteCluster`
 - [ ] Move `AsyncCreateCluster`
 - [ ] Move `AsyncUpdateCluster`
 - [ ] Move `AsyncUpdateAppProfile`
 - [ ] Move `AsyncCreateAppProfile`
 - [ ] Move `AsyncGetAppProfile`
 - [ ] Move `AsyncListAppProfiles`
 - [ ] Move `AsyncDeleteAppProfile`
 - [ ] Move `AsyncGetIamPolicy`
