### ISSUE TITLE
Consider not checking for eof when reading from streams

### ISSUE THREAD

**Issue by remyabel** [googleapis/google-cloud-cpp#2144]
There are several places where this happens, i.e https://github.com/googleapis/google-cloud-cpp/blob/51e147b7c10dab5839fb65a3486ae0438ff8e4d1/google/cloud/storage/benchmarks/storage_latency_benchmark.cc#L306 and https://github.com/googleapis/google-cloud-cpp/blob/5244e73ccf104837e21bd52c419b33b45ee64a92/google/cloud/storage/client_options.cc#L105. This is considered [bad practice](https://stackoverflow.com/questions/5605125/why-is-iostreameof-inside-a-loop-condition-considered-wrong) as it is preferred to instead check the state of the stream while looping, i.e:

```c++
int data;
while(inStream >> data){
  // when we land here, we can be sure that the read was successful.
  // if it wasn't, the returned stream from operator>> would be converted to false
  // and the loop wouldn't even be entered
  // do stuff with correctly initialized data (hopefully)
}
```

instead of:

```c++
while(!inStream.eof()){
  int data;
  // yay, not end of stream yet, now read ...
  inStream >> data;
  // oh crap, now we read the end and *only* now the eof bit will be set (as well as the fail bit)
  // do stuff with (now uninitialized) data
}
```

If the above is acceptable, then `ObjectReadStream` will need to be updated accordingly.

**Comment by coryan** [comment]
Fixing the support code (examples, tests, parsing of options) should be done of couse.

But if `ObjectReadStream` needs fixing then that is more urgent.  Can you tell us in more detail what exactly is broken?

**Comment by remyabel** [comment]
I wouldn't say broken. I'm talking about these lines here: https://github.com/googleapis/google-cloud-cpp/blob/7b0746c3f2e466c074658d10907cf8d756cf21c0/google/cloud/storage/object_stream.h#L64-67

Presumably if we are reading the stream the correct way, then the `peek()` wouldn't be necessary. I could be wrong, of course.

**Comment by coryan** [comment]
Thanks!  Yes, that code (or at least the comment) sounds funny.

In any case, changing the examples and tests to use best-practices sounds like a good idea.  Removing the call to `peek()` sounds like would break this test:

https://github.com/googleapis/google-cloud-cpp/blob/6b98a34394063a3f4f2bbe7e9d3f0bc96eedc534/google/cloud/storage/tests/object_integration_test.cc#L384

So my guess is that the comment that is wrong, but the code is correct in this case.

**Comment by remyabel** [comment]
After checking the corresponding pages for various stream classes, calling `traits::eof` from `underflow` seems correct. So that isn't the problem. In any case, `basic_streambuf` doesn't have a similar `is_open` function (like you'd see on `ifstream`). Instead, I think the interface should use `operator bool()` which checks `!fail()`. Then the test should become:

```
EXPECT_FALSE(stream); 
```

**Comment by remyabel** [comment]
It seems that changing it to "best practices" results in significantly decreased performance: http://quick-bench.com/hY0cwQzDf7F3cFc-2IlA0JUDf9I

This is likely not worth pursuing.
