### ISSUE TITLE
Create storage examples for object versioning.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#2174]
We want an example that queries the versioning status of an object, and example that resets it (with `PatchObjectMetadata`) and an example that sets object versioning.

Basically we want the examples from here:

https://cloud.google.com/storage/docs/using-object-versioning

but using the C++ client library. A good inspiration would be the event based hold examples:

https://github.com/googleapis/google-cloud-cpp/blob/52b8e180b617452e088bd1ecfd162041a2391465/google/cloud/storage/examples/storage_object_samples.cc#L1256

**Comment by remyabel** [comment]
Does enabling/disabling versioning apply only to buckets or also to objects? From my reading of the docs (and looking at `gsutil`) it looks like you set that on the bucket. So that should go into `storage_bucket_samples.cc`, right?

Then I would imagine the rest of the samples there go into `sample_object_samples.cc`.

**Comment by remyabel** [comment]
Making good progress on this, but I wanted to point out two things: you can't POST `object?generation=2` (similar issue to the slashes issue). It is probably not worth fixing, though.

```
# Doing object?generation=2
object-1552300758-9901.txt%3Fgeneration%3D2
# Doing gcs::Generation{2}
object-1552300758-9901.txt?generation=2
```

Secondly, not sure if this is a problem on my end or a bug in how `DeleteObject` handles versions:

```shell
  run_example ./storage_object_samples insert-object \
      "${bucket_name}" "${object_name}" "a-string-to-serve-as-object-media"
  # Create an archived version of our object.
  run_example ./storage_object_samples insert-object \
      "${bucket_name}" "${object_name}" "a-string-to-serve-as-object-media"
  run_example ./storage_object_samples delete-versioned-object \
      "${bucket_name}" "${object_name}" "2"
  run_example ./storage_bucket_samples disable-object-versioning \
      "${bucket_name}"
  run_example ./storage_object_samples delete-object \
     "${bucket_name}" "${object_name}"
```

Where `delete-version-object` just passes `gcs::Generation` to `DeleteObject`. I would expect that the second delete should succeed but it doesn't.

**Comment by remyabel** [comment]
The problem seems to be that the precondition is failing because the generation doesn't match:

```
('self.generation ', 2)
('For ', {1: <gcs_object.GcsObjectVersion object at 0x7fa4c994eb90>, 2: <gcs_object.GcsObjectVersion object at 0x7fa4c9991f10>})
('Debug: before revisions ', {1: <gcs_object.GcsObjectVersion object at 0x7fa4c994eb90>, 2: <gcs_object.GcsObjectVersion object at 0x7fa4c9991f10>})
('Debug: after revisions ', {1: <gcs_object.GcsObjectVersion object at 0x7fa4c994eb90>})
127.0.0.1 - - [11/Mar/2019:12:54:40 +0000] "DELETE /storage/v1/b/fake-bucket-1552308878-4682/o/object-1552308880-7701.txt?generation=2 HTTP/1.1" 200 2 "-" "gcs-c++/v0.6.0+a422b631 ex Clang 6.0.0 libcurl/7.60.0 OpenSSL/1.1.0g zlib/1.2.11 c-ares/1.14.0"
('self.generation ', 2)
('For ', {1: <gcs_object.GcsObjectVersion object at 0x7fa4c994eb90>})
Precondition failed
127.0.0.1 - - [11/Mar/2019:12:54:40 +0000] "DELETE /storage/v1/b/fake-bucket-1552308878-4682/o/object-1552308880-7701.txt?generation=1 HTTP/1.1" 404 36 "-" "gcs-c++/v0.6.0+a422b631 ex Clang 6.0.0 libcurl/7.60.0 OpenSSL/1.1.0g zlib/1.2.11 c-ares/1.14.0"
```

**Comment by coryan** [comment]
> you can't POST `object?generation=2` (similar issue to the slashes issue). It is probably not worth fixing, though.

That is a fundamental feature of GCS.  You cannot change the contents of an existing object (where objects are identified by bucket + name + generation).  You can only POST and create a new generation of an object.

If you name an object with a name that contains query parameters then I think escaping the query parameters is the right behavior.

> Where `delete-version-object` just passes `gcs::Generation` to `DeleteObject`. I would expect that the second delete should succeed but it doesn't.

I expect that the testbench lost track of the "latest" object version, I will try to take a look.

**Comment by remyabel** [comment]
> That is a fundamental feature of GCS. You cannot change the contents of an existing object (where objects are identified by bucket + name + generation). You can only POST and create a new generation of an object.

I misspoke. I went back and typed "POST" when I was actually talking about DELETE'ing. I'm aware that when you insert a new object, it creates a new generation.
