### ISSUE TITLE
Create an example to print the default CMEK in a bucket

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#2177]
We want an example that prints the default CMEK in a bucket. Probably similar to:

https://github.com/googleapis/google-cloud-cpp/blob/52b8e180b617452e088bd1ecfd162041a2391465/google/cloud/storage/examples/storage_bucket_samples.cc#L111-L121

Except that only the relevant attribute (`BucketMetadata::has_encryption` and `BucketMetadata::encryption()`) are printed out.

The region tags should be `storage_bucket_TBD`.

**Comment by remyabel** [comment]
Can you clarify the requirements of this task? Looks like it was mangled by copy/paste error.

**Comment by coryan** [comment]
Indeed bad cut&paste, but this looks like it is implemented already:

https://github.com/googleapis/google-cloud-cpp/blob/a1a29d2b9fe4ec55036b1205961514387d097923/google/cloud/storage/examples/storage_bucket_samples.cc#L337-L356

And I fixed the region tag in #2180, but forgot to close this. Doing so now.
