### ISSUE TITLE
Fix strange "static initialized in constructor" idiom in the integration tests.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#2181]
A lot of our integration tests use static member variables to effectively pass command-line arguments to all the tests.  The integration tests are (by design) not hermetic and need configuration parameters, but using a `::testing::Environment` is a weird way to pass these parameters around.

One proposal is to use simply `std::string` globals, or `std::string const*` globals, or maybe a class to represent "a command-line flag".

**Comment by coryan** [comment]
Okay, there is only one of these `::test::Environment` classes left, it is more complicated, and I would prefer to leave it as-is.  I am interested in @devbww and @devjgm opinions though.  The class is here:

https://github.com/googleapis/google-cloud-cpp/blob/bea70e320e59c6aca84c4ebe2125c2009d5f36da/google/cloud/bigtable/testing/table_integration_test.h#L32

It actually does stuff, for example:

https://github.com/googleapis/google-cloud-cpp/blob/bea70e320e59c6aca84c4ebe2125c2009d5f36da/google/cloud/bigtable/testing/table_integration_test.cc#L37-L58


I could move the static member variables to the namespace, but I am not sure that is worse than having them as static members of the class.

Thoughts?

**Comment by devbww** [comment]
As I understand things we:

1. Create an Environment in `main()`, capturing any command-line arguments and possible initializing some globals.

1. Then gtest calls the environment back via `SetUp()`, where we initialize some more globals (possibly using the captured command-line arguments).

1. The tests run, accessing those globals using static functions on the Environment class.

1. Then gtest calls the environment back via `TearDown()` to do any cleanup, and deletes it.

It seems to me that this isn't fundamentally different to:

1. Create an object in `main()` using the command-line arguments, where its ctor does all the setup and all members are non-static.

1. Somehow provide access to that object for the tests.

1. After `RUN_ALL_TESTS()` returns, destroy the object, which does cleanup in its dtor.

That is, some variation (i.e., this is just a vague outline) of:
```
Env* envp;
TEST() { ... envp->Foo() ... }
int main(int argc, char** argv) {
  unique_ptr<Env> env = make_unique<Env>(argc, argv);
  envp = env.get();
  return RUN_ALL_TESTS();
}
```

One instantiation of that pattern that almost matches what we have now would be:

1. Make `TableTestEnvironment` a non-static object.

1. Then ...
```
TableTestEnvironment* envp;
TEST() { ... envp->Foo() ... }
int main(int argc, char** argv) {
  envp = new TableTestEnvironment(argc, argv);
  AddGlobalTestEnvironment(envp);
  return RUN_ALL_TESTS();
}
```
but that seems to add the `testing::Environment` complexity for little reason.

Anyway, just thoughts.

**Comment by coryan** [comment]
I am happy with things as they are. If anybody feels strongly, grab this bug and send a PR.

**Comment by devjgm** [comment]
It'd say we're all happy enough w/ the way things are now, and this issue isn't worth keeping open, IMO.
