### ISSUE TITLE
Testbench should check if buckets are empty before deleting.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#2214]
The testbench does not seem to check if a bucket is empty before trying to delete it.

**Comment by rsimion** [comment]
@coryan 
where should I check? what file/folder?
/storage/tests folder? 
integration test files?

**Comment by remyabel** [comment]
@rsimion The python files in `google/cloud/storage/testbench`.

**Comment by remyabel** [comment]
Assuming the new emulator is intended to replace the testbench I think this issue should be closed or edited.

cc @vnvo2409

**Comment by vnvo2409** [comment]
Yes, the new emulator will check if there is any live version of object before deleting a bucket. We can close this issue now.
