### ISSUE TITLE
Install only installs google_cloud_cpp_common

### ISSUE THREAD

**Issue by manmat** [googleapis/google-cloud-cpp#2234]
I followed the install.md to install the lates version on Ubuntu 18.04 and it looks like google_cloud_cpp_common got installed but storage_client not. Am I missing something? When I tried to build a small test project, CMake can't fing storage_client but it has no trouble finding google_cloud_cpp_common.

**Comment by coryan** [comment]
> Am I missing something? 

I am going to assume that we missed something, because that is likely the case.  Let me try running the instructions manually and see what I find.  While I do that:

Do you have the exact error message that CMake prints out?

I suspect it is more complicated than simply not installing storage_client.  As you can see here, the instructions are executed automatically as part of the CI build:

https://source.cloud.google.com/results/invocations/1b2ec63d-b0e7-4e5a-9519-6078095111d9/targets/cloud-cpp%2Fgithub%2Finstall%2Fubuntu/log

And the library does get installed, but maybe the CMake support files are not, or maybe they are installed but unusable for some reason, this is why having the error message would be useful.

**Comment by coryan** [comment]
I just ran through the instructions (as root, inside a Docker container) and I saved the error messages at the end of this comment.  It seems that gRPC does not install the necessary `CMake` support files when compiled with regular good-old `make`, and does not install the `pkg-config` support files when compiled with `CMake`.

Sigh...  I think we need to either change the instructions to install gRPC both ways (blegh..), or we need to create our own `FindGrpc` module that uses `pkg-config` or `CMake` support files dependencies.  I am upgrading this to a feature request. @manmat I think I can give you a workaround in a few minutes based on this:

https://github.com/googleapis/google-cloud-cpp/blob/16549a383241f30df94e283f851fbc7034586d16/ci/travis/Dockerfile.ubuntu-install#L140-L159

Let me test it first though.


----

The error log for the record.

```
CMake Error at /usr/share/cmake-3.10/Modules/CMakeFindDependencyMacro.cmake:48 (find_package):
  By not providing "FindgRPC.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "gRPC", but
  CMake did not find one.

  Could not find a package configuration file provided by "gRPC" with any of
  the following names:

    gRPCConfig.cmake
    grpc-config.cmake

  Add the installation prefix of "gRPC" to CMAKE_PREFIX_PATH or set
  "gRPC_DIR" to a directory containing one of the above files.  If "gRPC"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  /usr/local/lib/cmake/bigtable_client/bigtable_client-config.cmake:17 (find_dependency)
  CMakeLists.txt:30 (find_package)


-- Configuring incomplete, errors occurred!
See also "/root/Test/.build/CMakeFiles/CMakeOutput.log".
See also "/root/Test/.build/CMakeFiles/CMakeError.log
```

**Comment by manmat** [comment]
Hey, ok, sure. I just want a quick test project up and running.

**Comment by coryan** [comment]
The following workaround works for me on Ubuntu:18.04.  Change the instructions to [install gRPC](https://github.com/googleapis/google-cloud-cpp/blob/master/INSTALL.md#grpc-1) to the commands below.  As I said above, I think the "Right Thing":tm: is to create a FindGrpc module that automatically detects how gRPC is installed.

Sorry for the bother.

```console
cd $HOME/Downloads
apt-get remove -y libc-ares-dev libc-ares2
wget -q https://github.com/c-ares/c-ares/archive/cares-1_14_0.tar.gz
tar -xf cares-1_14_0.tar.gz

cd c-ares-cares-1_14_0
cmake \
      -DCMAKE_BUILD_TYPE="Release" \
      -DBUILD_SHARED_LIBS=yes \
      -H. -B.build
cmake --build .build --target install -- -j ${NCPU}

sudo apt update && \
sudo apt install -y automake libtool
./buildconf
./configure
install -m 644 -D -t /usr/local/lib/pkgconfig libcares.pc
ldconfig

cd $HOME/Downloads
wget -q https://github.com/grpc/grpc/archive/v1.19.1.tar.gz
tar -xf v1.19.1.tar.gz
cd grpc-1.19.1
cmake \
      -DCMAKE_BUILD_TYPE="Release" \
      -DBUILD_SHARED_LIBS=yes \
      -DgRPC_BUILD_TESTS=OFF \
      -DgRPC_ZLIB_PROVIDER=package \
      -DgRPC_SSL_PROVIDER=package \
      -DgRPC_CARES_PROVIDER=package \
      -DgRPC_PROTOBUF_PROVIDER=package \
      -H. -B.build/grpc
cmake --build .build/grpc --target install -- -j ${NCPU}
make install-pkg-config_c install-pkg-config_cxx install-certs
ldconfig
```

**Comment by remyabel** [comment]
> As I said above, I think the "Right Thing"tm is to create a FindGrpc module that automatically detects how gRPC is installed.

I suppose that would be the best approach. As mentioned in a previous issue, gentoo uses `pkg-config` for the gRPC dependency.

With that being said, how does our `config.cmake.in`'s factor into this? For example, here we are establishing a dependency on `gRPC`:

https://github.com/googleapis/google-cloud-cpp/blob/273ecad7131c2bd1b8a7f21601568e506eb223aa/google/cloud/bigtable/config.cmake.in#L17

Even though the import target `gRPC::grpc++` may have been created via the `pkg-config` option, I think that `find_dependency` tells it to look for the CMake config.

**Comment by remyabel** [comment]
Alternatively, we can use [CMakePackageConfigHelpers](https://cmake.org/cmake/help/latest/module/CMakePackageConfigHelpers.html) to write the version files and `export` to create the regular config files.

See: https://stackoverflow.com/questions/49857596/cmake-simple-config-file-example as well as https://github.com/ericniebler/range-v3/blob/1032ec4a138b7111eb5752df24c351e5a3618bae/CMakeLists.txt#L130-L144

So:

```diff
-    configure_file("config.cmake.in" "bigtable_client-config.cmake" @ONLY)
-    configure_file("${PROJECT_SOURCE_DIR}/google/cloud/config-version.cmake.in"
-                   "bigtable_client-config-version.cmake" @ONLY)
+    include(CMakePackageConfigHelpers)
+    write_basic_package_version_file(
+        ${CMAKE_CURRENT_BINARY_DIR}/bigtable_client-config-version.cmake
+        VERSION
+        "${BIGTABLE_CLIENT_VERSION_MAJOR}.${BIGTABLE_CLIENT_VERSION_MINOR}.${BIGTABLE_CLIENT_VERSION_PATCH}"
+        COMPATIBILITY
+        SameMajorVersion)
+
+    install(EXPORT bigtable-targets
+            FILE
+            bigtable_client-config.cmake
+            DESTINATION
+            "${CMAKE_INSTALL_LIBDIR}/cmake/bigtable_client")
     install(
-        FILES "${CMAKE_CURRENT_BINARY_DIR}/bigtable_client-config.cmake"
-              "${CMAKE_CURRENT_BINARY_DIR}/bigtable_client-config-version.cmake"
-              DESTINATION
-              "${CMAKE_INSTALL_LIBDIR}/cmake/bigtable_client")
+        FILES ${CMAKE_CURRENT_BINARY_DIR}/bigtable_client-config-version.cmake
+              DESTINATION "${CMAKE_INSTALL_LIBDIR}/cmake/bigtable_client")
+
+    export(EXPORT
+           bigtable-targets
+           FILE
+           bigtable_client-config.cmake)
```

But with this approach I am running into a major issue where now it can't find the `google_cloud_cpp_common` target:

```
  Found package configuration file:

    /usr/local/lib/cmake/bigtable_client/bigtable_client-config.cmake

  but it set bigtable_client_FOUND to FALSE so package "bigtable_client" is
  considered to be NOT FOUND.  Reason given by package:

  The following imported targets are referenced, but are missing:
  google_cloud_cpp_common
```

If I apply the same approach to `google_cloud_cpp_common`, it complains:

```
CMake Error: install(EXPORT "bigtable-targets" ...) includes target "bigtable_client" which requires target "google_cloud_cpp_common" that is not in this export set, but 2 times in others.
```

**Comment by manmat** [comment]
@coryan Thanks, I followed the instructions and now I get an error when I try to execute the `cmake --build build-output -- -j $(nproc)` from the last step. The error is:
```make[2]: *** No rule to make target '../third_party/googleapis/google/longrunning/operations.proto', needed by 'google/cloud/bigtable/google/longrunning/operations.grpc.pb.cc'.  Stop.
CMakeFiles/Makefile2:3398: recipe for target 'google/cloud/bigtable/CMakeFiles/bigtable_protos.dir/all' failed
make[1]: *** [google/cloud/bigtable/CMakeFiles/bigtable_protos.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  6%] Built target nlohmann_json_project
[  6%] Built target googletest_project
[  6%] Built target google_cloud_cpp_common
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2```
Any idea where this might come from?

**Comment by manmat** [comment]
Looks like explicitly providing a number for threads worked for now.
