### ISSUE TITLE
How do I specify a service account to use with the KMS samples?

### ISSUE THREAD

**Issue by remyabel** [googleapis/google-cloud-cpp#2242]
I encountered a similar problem with gsutil and asked in Slack but didn't get an answer. Essentially, the preamble:

```shell
gcloud iam service-accounts create google-cloud-cpp
gcloud iam service-accounts keys create credentials \
  --iam-account google-cloud-cpp@my-project.iam.gserviceaccount.com
gcloud projects add-iam-policy-binding my-project \
  --role='roles/storage.admin' \
  --member='serviceAccount:google-cloud-cpp@my-project.iam.gserviceaccount.com'
gcloud kms keyrings add-iam-policy-binding google-cloud-cpp-test \
  --location global \
  --member serviceAccount:google-cloud-cpp@my-project.iam.gserviceaccount.com \
  --role roles/cloudkms.admin
```

Now for the actual samples:

```shell
env GOOGLE_APPLICATION_CREDENTIALS=$PWD/credentials \
   ./build-output/ubuntu-18.04-clang-Release-tidy/google/cloud/storage/examples/storage_bucket_samples \
    create-bucket-for-project asdfasdf12345 my-project
env GOOGLE_APPLICATION_CREDENTIALS=$PWD/credentials \
    ./build-output/ubuntu-18.04-clang-Release-tidy/google/cloud/storage/examples/storage_bucket_samples \
    add-bucket-default-kms-key asdfasdf12345 projects/my-project/locations/us/keyRings/google-cloud-cpp-test/cryptoKeys/google-cloud-cpp-test-key2
```

Operation fails here:

```shell
env GOOGLE_APPLICATION_CREDENTIALS=$PWD/credentials \
    ./build-output/ubuntu-18.04-clang-Release-tidy/google/cloud/storage/examples \
    /storage_object_samples insert-object asdfasdf12345 test "testtest"
Standard C++ exception raised: Permanent error in InsertObjectMedia: {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "forbidden",
    "message": "Permission denied on Cloud KMS key. Please ensure that your Cloud Storage service account  has been authorized to use this key."
   }
  ],
  "code": 403,
  "message": "Permission denied on Cloud KMS key. Please ensure that your Cloud Storage service account  has been authorized to use this key."
 }
}
```

Note that it says "blank" for service account. If I run the sample for `get-service-account-for-project` it outputs a non-existent account: `service-####@gs-project-accounts.iam.gserviceaccount.com`

Incidentally, I get the exact same behavior with gsutil when running:

```shell
# Outputs same error
gsutil -o "GSUtil:encryption_key=projects/my-project/locations/us/keyRings/google-cloud-cpp-test/cryptoKeys/google-cloud-cpp-test-key2" cp test gs://asdfasdf12345
# Outputs same non-existent service account
gsutil kms serviceaccount -p
```

So this is 99% an error on my part, but I'm not sure what I'm doing wrong.

**Comment by remyabel** [comment]
I also tried `gcloud auth activate-service-account --key-file=credentials` and that affects other operations but doesn't seem to help with the KMS related ones.

Based on the discussion [here](https://github.com/googleapis/google-cloud-php/issues/1079#issuecomment-395229141) the `gs-project-accounts.iam.gserviceaccount.com` account needs to be fetched programmatically and then granted permissions. So:

```
ACCOUNT=$(gsutil kms serviceaccount -p)
gcloud projects add-iam-policy-binding zinc-shard-224517 \
    --role='roles/storage.admin' --member='serviceAccount:${ACCOUNT}'
gcloud projects add-iam-policy-binding zinc-shard-224517 \
    --role='roles/cloudkms.admin' --member='serviceAccount:${ACCOUNT}'
```

No success. BTW, if anyone can point me to documentation regarding this matter that would be highly appreciated.

**Comment by coryan** [comment]
I think you are looking for this?

**Comment by coryan** [comment]
I just ran these commands:

```console
export GOOGLE_CLOUD_PROJECT=...  # I used a new project to test this.
BUCKET=${GOOGLE_CLOUD_PROJECT}-test-kms          # A name for a new bucket
KR=test-key-ring    # The id for a new key ring
KEYID=test-key     # The id for a new key in ${KR}
```

Create the key ring and the key:

```
gcloud kms keyrings create ${KR} --location=global
gcloud kms keyrings list --location=global
gcloud kms keys create ${KEYID} --purpose=encryption --location=global --keyring=${KR}
gcloud kms keys list --location=global --keyring=${KR}
```

Authorize the GCS service account to access the new key:

```console
KEYNAME=projects/${GOOGLE_CLOUD_PROJECT}/locations/global/keyRings/${KR}/cryptoKeys/${KEYID}
gsutil kms authorize -p ${GOOGLE_CLOUD_PROJECT} -k ${KEYNAME}
```

Create a bucket and use the new key as the default KMS key:


```
gsutil mb gs://${BUCKET}
gsutil kms encryption -k ${KEYNAME} gs://${BUCKET}
```

Then upload an object to it:

```console
echo foo >foo.txt
gsutil cp foo.txt gs://${BUCKET}/foo.txt
```

Use gsutil to verify the key is in use:

```console
gsutil ls -L gs://${BUCKET}/foo.txt | grep kms
```

**Comment by remyabel** [comment]
Thanks, your instructions work. I'm fairly certain I did run `gsutil kms authorize` already but I'm going to take a break from this.

**Comment by mrdulin** [comment]
same issue.

```bash
gsutil kms serviceaccount -p <PROJECT_ID>
```
Got no-existent service account

**Comment by coryan** [comment]
@mrdulin can you give us some more context?  Did you follow the steps in:

https://cloud.google.com/storage/docs/encryption/using-customer-managed-keys

to enable KMS for Google Cloud Storage?  Is the Google Cloud Storage C++ library not working for you with KMS or is this a general problem with KMS and Google Cloud Storage?

**Comment by remyabel** [comment]
@mrdulin The instructions by @coryan worked for me. Does the non-existent account have the format "gs-project-accounts.iam.gserviceaccount.com"? I'm pretty sure that account is from the API end and won't be listed under your service accounts.

**Comment by mrdulin** [comment]
@coryan Sorry. Let me clear it. Here is my context: 

https://stackoverflow.com/questions/56320241/permission-denied-on-cloud-kms-key-when-using-cloud-storage

But after I run `gsutil kms authorize -p $PROJECT_ID -k projects/$PROJECT_ID/locations/global/keyRings/test/cryptoKeys/nodejs-gcp`

I can use `@google_cloud/storage` nodejs client library upload an object with `kmsKeyName`. It's weird.

**Comment by coryan** [comment]
I think the answer in stackoverflow covers it.  GCS, acting on your behalf, needs access to the KMS resources.  GCS creates a service account to perform actions on your behalf, and this service account does **not** have access to KMS until you your that `gsutil kms authorize` command.

I take it that this is not a problem specific with the C++ client library, and more of a general question about GCS, I am going to close this issue because there is no specific action in the C++ client library.

If you think the GCS documentation is not clear on this topic then please open a bug using the "send feedback" link on:

https://cloud.google.com/storage/docs/encryption/using-customer-managed-keys#top_of_page

**Comment by mrdulin** [comment]
@coryan  OK. Thanks.
