### ISSUE TITLE
Audit Bigtable C++ examples vs. node.js examples

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#2253]
Compare the Bigtable code snippets against the NodeJS snippets here:

https://github.com/googleapis/nodejs-bigtable/tree/master/samples/document-snippets

Add a bug for every snippet that is missing from the C++ client library, then close this bug.

It is possible that no snippets are missing, then record that in this bug and close it.

**Comment by manish-qlogic** [comment]
`C++` examples covers all of `node.js` example-snippets and more but they differ in 2 aspects

1. They do not share the same marker tags, as an example
`node.js` example snippet for creating app profile has a marker `// [START bigtable_create_app_profile]` where as similar C++ example has `//! [create app profile]` marker tag.

2. `node.js` exposes `GetMetaData` and `SetMetaData` for many entities like app_profile, instance, cluster. So there are examples of getting and setting MetaData.  On the other hand, `C++` does not have any such examples. 

@coryan ,
Do we care about using the same `START marker tag`?
 if yes then we have to open quite a few bugs and if no then we are good and can close this bug. Let me know and I will act accordingly.

**Comment by coryan** [comment]
Yes, we need to update the START/END region tags.  Feel free to group the bugs in related tasks if that makes sense.  Or just send a PR to fix them all and reference this one bug.

**Comment by manish-qlogic** [comment]
@coryan 

we can close this issue as a bug for every missing snippet is created.

**Comment by coryan** [comment]
SGTM.
