### ISSUE TITLE
Breakdown work for additional Bigtable C++ examples.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#2254]
We need to write the following examples.  The objective in this bug is to mark as closed the one that already exist and have a matching region tag (e.g. `bigtable_update_app_profile` is the desired region tag, we may have something different in our code).

Open bugs for any missing examples or examples with the wrong region tag, mark as done the items that have examples with a matching region tag.

Feel free to open a single item for related work (e.g. read_prefix_list and read_prefix).

Once the bugs are created you can close this bug.

- [x] bigtable_update_app_profile: Update an AppProfile
- [x] bigtable_create_replicated_cluster: Create replicated cluster in current project
- [x] bigtable_check_family_exists: Check if a column family exists
- [x] bigtable_get_or_create_family: Auto-create column family if does not exist
- [x] bigtable_get_family_metadata: Retrieve family metadata (including GC rule)
- [x] bigtable_family_ref: Retrieve a reference to a column family
- [x] bigtable_read_prefix: Read rows with row keys matching a given prefix
- [x] bigtable_read_range: Read a range of rows given start, end row keys
- [x] bigtable_read_error: How to read / handle success, error
- [x] bigtable_read_prefix_list: Read rows with row keys matching any prefix in a list
- [x] bigtable_read_multiple_ranges: Read multiple sets of ranges given sets of start, end row keys
- [x] bigtable_read_keys_set: Read using non-continguous set of row keys
- [x] bigtable_read_filter: Read the most recent value in a given column using a filter
- [x] bigtable_delete_rows: Delete all rows
- [x] bigtable_mutate_delete_columns: Delete columns within a row using mutate
- [x] bigtable_mutate_delete_rows: Delete rows using mutate
- [x] bigtable_mutate_insert_rows: Insert rows using mutate
- [x] bigtable_mutate_mix_match: Mix and match mutation operations (insert rows, delete column)
- [x] bigtable_insert_update_rows: Update or insert rows in a table
- [x] bigtable_check_table_exists: Check if a table exists
- [x] bigtable_delete_rows_prefix: Delete rows with row keys matching a given prefix
- [x] bigtable_get_or_create_table: Get table details if it exists or auto-create table if does not exist
- [x] bigtable_table_sample_splits: Retrieve sample row keys
- [x] bigtable_truncate_table: Truncate the table (delete all data)
- [x] bigtable_hw_install: Install the necessary modules/packages to run the sample. pom.xml, requirements.txt etc.

**Comment by manish-qlogic** [comment]
@coryan

Some questions
-  What is `bigtable_create_replicated_cluster` for, is it a combination of `CreateCluster` and `UpdateAppProfile` ?
- what is the difference between `bigtable_delete_rows` and `bigtable_truncate_table`?

Following tags differ in name from node,js tags but sounds similar, so I need to know the correct tag to use in snippets?

> bigtable_check_family_exists: Check if a column family exists

node.js tags it as [bigtable_exists_family](https://github.com/googleapis/google-cloud-cpp/issues/2288).

> bigtable_get_family_metadata: Retrieve family metadata (including GC rule)

node.js tags it as [bigtable_get_family_meta](https://github.com/googleapis/google-cloud-cpp/issues/2297).

> bigtable_family_ref: Retrieve a reference to a column family

I think that node.js tags it as [bigtable_get_family](https://github.com/googleapis/google-cloud-cpp/issues/2296)

> bigtable_delete_rows: Delete all rows

node.js and current CPP Client code tags it as [bigtable_del_rows](https://github.com/googleapis/google-cloud-cpp/blob/bf252b343f7931ff3dd2f83089f7de16e99c01b6/google/cloud/bigtable/examples/table_admin_snippets.cc#L182)

> bigtable_mutate_insert_rows: Insert rows using mutate

node.js and current CPP client code tags it as [bigtable_insert_rows](https://github.com/googleapis/google-cloud-cpp/blob/bf252b343f7931ff3dd2f83089f7de16e99c01b6/google/cloud/bigtable/examples/data_snippets.cc#L104)

> bigtable_check_table_exists: Check if a table exists

node.js tags it as [bigtable_exists_table](https://github.com/googleapis/google-cloud-cpp/issues/2299)

> bigtable_truncate_table: Truncate the table (delete all data)

I think node.js and current CPP client code tags it as [bigtable_del_rows](https://github.com/googleapis/google-cloud-cpp/blob/bf252b343f7931ff3dd2f83089f7de16e99c01b6/google/cloud/bigtable/examples/table_admin_snippets.cc#L182) 

> bigtable_table_sample_splits: Retrieve sample row keys
I think node.js and current CPP client code tags it as [bigtable_sample_row_keys](https://github.com/googleapis/google-cloud-cpp/blob/bf252b343f7931ff3dd2f83089f7de16e99c01b6/google/cloud/bigtable/examples/data_snippets.cc#L420)

**Comment by coryan** [comment]
> * What is `bigtable_create_replicated_cluster` for, is it a combination of `CreateCluster` and `UpdateAppProfile` ?

I think you want to create two clusters in the same instance, to demonstrate how replication works. There are no examples implemented in any language yet, and you have the description, such as it is.

> * what is the difference between `bigtable_delete_rows` and `bigtable_truncate_table`?

`bigtable_truncate_table` is supposed to use `DropAllRows()`, there is an example in Python:

https://github.com/googleapis/google-cloud-python/blob/f29e36ca7d8b5502be72b5edc2767e9b5a794abe/bigtable/google/cloud/bigtable/table.py#L554

You have the same information I have about `bigtable_delete_rows`, my guess is use `BulkApply()` to delete all the rows.

> 
> Following tags differ in name from node,js tags but sounds similar, so I need to know the correct tag to use in snippets?
> 
> > bigtable_check_family_exists: Check if a column family exists
> 
> node.js tags it as [bigtable_exists_family](https://github.com/googleapis/google-cloud-cpp/issues/2288).

Use `bigtable_check_family_exists` the other tag is not in the tracking tool inside Google.  They may change them later, but I would rather we tracked the defined tags to begin with.

> 
> > bigtable_get_family_metadata: Retrieve family metadata (including GC rule)
> 
> node.js tags it as [bigtable_get_family_meta](https://github.com/googleapis/google-cloud-cpp/issues/2297).

Same thing, use `bigtable_get_family_metadata`.

> 
> > bigtable_family_ref: Retrieve a reference to a column family
> 
> I think that node.js tags it as [bigtable_get_family](https://github.com/googleapis/google-cloud-cpp/issues/2296)

Same thing, use `bigtable_family_ref`.

> 
> > bigtable_delete_rows: Delete all rows
> 
> node.js and current CPP Client code tags it as [bigtable_del_rows](https://github.com/googleapis/google-cloud-cpp/blob/bf252b343f7931ff3dd2f83089f7de16e99c01b6/google/cloud/bigtable/examples/table_admin_snippets.cc#L182)

Same thing, use the tag in this bug.

> 
> > bigtable_mutate_insert_rows: Insert rows using mutate
> 
> node.js and current CPP client code tags it as [bigtable_insert_rows](https://github.com/googleapis/google-cloud-cpp/blob/bf252b343f7931ff3dd2f83089f7de16e99c01b6/google/cloud/bigtable/examples/data_snippets.cc#L104)
> 

Same thing, use the tag in this bug.


> > bigtable_check_table_exists: Check if a table exists
> 
> node.js tags it as [bigtable_exists_table](https://github.com/googleapis/google-cloud-cpp/issues/2299)
> 

Same thing, use the tag in this bug.


> > bigtable_truncate_table: Truncate the table (delete all data)
> 
> I think node.js and current CPP client code tags it as [bigtable_del_rows](https://github.com/googleapis/google-cloud-cpp/blob/bf252b343f7931ff3dd2f83089f7de16e99c01b6/google/cloud/bigtable/examples/table_admin_snippets.cc#L182)
>

See above, use `bigtable_truncate_table`.
 
> > bigtable_table_sample_splits: Retrieve sample row keys
> 
> I think node.js and current CPP client code tags it as [bigtable_sample_row_keys](https://github.com/googleapis/google-cloud-cpp/blob/bf252b343f7931ff3dd2f83089f7de16e99c01b6/google/cloud/bigtable/examples/data_snippets.cc#L420)

Same thing, use the tag in this bug.

> 
> > bigtable_hw_install: Install the necessary modules/packages to run the sample. pom.xml, requirements.txt etc.
> 
> Ignoring this task.

Actually we have this, but not as a code snippet of course.  Maybe we can create the right tags around it, I will add a bug for this.
