### ISSUE TITLE
Create breakdown for additional Storage examples.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#2256]
For each region tag (and description) below we need to either:

- Check if the example exists, if it does, create a bug (or simply a PR) to fix the region tag. I think there are several in that category, I am blinding copying the region tag descriptions here.
- If the example does not exist, create a bug to implement that example. If multiple examples can be grouped in a single bug that is Okay.

We can close this bug once all the child bugs are created.

- [x] storage_create_bucket_class_location: Create a GCS bucket with storage class and location parameters
- [x] storage_add_bucket_owner: Add owner access control to a GCS bucket
- [x] storage_remove_bucket_owner: Remove owner access control to a GCS bucket
- [x] storage_add_bucket_default_owner: Add default access control to a GCS bucket
- [x] storage_add_file_owner: Add owner access control to an object in a GCS bucket
- [x] storage_remove_file_owner: Remove owner access to an object in a GCS bucket
- [x] storage_print_file_acl_for_user: View the access control list for an object in a GCS bucket, filtered by user
- [x] storage_change_file_storage_class: Rewrite and update the object storage class of a GCS object
- [x] storage_view_lifecycle_management_configuration: View lifecycle configuration of a GCS bucket
- [x] storage_define_bucket_website_configuration: Set static website configuration for a GCS bucket
- [x] storage_enable_versioning: Enable object versioning for a GCS bucket
- [x] storage_disable_versioning: Disable object versioning for a GCS bucket
- [x] storage_view_versioning_status: Check if object versioning status is enabled for a GCS bucket
- [x] storage_copy_file_archived_generation: Copy an archived generation of an object in a GCS bucket
- [x] storage_delete_file_archived_generation: Delete an archived generation of an object in a GCS bucket
- [x] storage_download_public_file: Download an object from a public data set object
- [x] storage_cors_configuration: Add CORS configuration to a GCS storage bucket

**Comment by coryan** [comment]
I just submitted a PR to fix several region tags. I clicked their checkboxes already.

**Comment by remyabel** [comment]
What should the region tags be for disabling or viewing the bucket website configuration?

**Comment by coryan** [comment]
> What should the region tags be for disabling or viewing the bucket website configuration?

@remyabel I looked again, and there is not one defined. If we add such an example we can use `storage_print_website_configuration` (there are 5 `storage_print_*` region tags and 3 `storage_view_*` region tags, so I am going with `print`).

/cc: @frankyn FYI in case you have an opinion.

**Comment by frankyn** [comment]
`print` is fine. The region tags should be updated to be more consistent. I'll create a new sample request with this region tag to track this internally.

Thanks @remyabel!

**Comment by remyabel** [comment]
What would be the difference between `storage_delete_bucket_acl` and `storage_remove_bucket_owner`? This works:

```c++
    StatusOr<gcs::BucketAccessControl> patched_acl =
        client.PatchBucketAcl(bucket_name, entity,
                              gcs::BucketAccessControlPatchBuilder().set_role(
                                  gcs::BucketAccessControl::ROLE_OWNER()));
```

This does not:

```c++
    StatusOr<gcs::BucketAccessControl> patched_acl = client.PatchBucketAcl(
        bucket_name, entity,
        gcs::BucketAccessControlPatchBuilder().delete_role());
```

It errors with `type must be string, but is null` even though the [docs](https://cloud.google.com/storage/docs/json_api/v1/how-tos/performance#patch) say to delete a field you set it to NULL.

**Comment by remyabel** [comment]
So turns out that error is from [nlohmann json](https://github.com/nlohmann/json/issues/278). This:

```c++
StatusOr<gcs::BucketAccessControl> patched_acl = client.PatchBucketAcl(bucket_name, entity,
                      gcs::BucketAccessControlPatchBuilder().set_role(
                          gcs::BucketAccessControl::ROLE_OWNER()).delete_entity());
```

seems very close to the example from `bucket_acl_requests_test.cc`:

```c++
  PatchBucketAclRequest request(
      "my-bucket", "user-test-user",
      BucketAccessControlPatchBuilder().set_role("READER").delete_entity());
  nl::json expected = {{"role", "READER"}, {"entity", nullptr}};
```

Unless I'm missing something obvious. This compiles and the tests pass now, but it doesn't work in practice:

```
root@8e5bb9d8bec3:/v# env GOOGLE_APPLICATION_CREDENTIALS=$PWD/credentials ./build-output/ubuntu-18.04-clang-Debug/google/cloud/storage/examples/storage_bucket_acl_samples remove-bucket-owner asdfasdf12345 allAuthenticatedUsers
Standard C++ exception raised: Permanent error in PatchBucketAcl: {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "invalidParameter",
    "message": "Value 'null' in content does not agree with value 'allAuthenticatedUsers'. This can happen when a value set through a parameter is inconsistent with a value set in the request."
   }
  ],
  "code": 400,
  "message": "Value 'null' in content does not agree with value 'allAuthenticatedUsers'. This can happen when a value set through a parameter is inconsistent with a value set in the request."
 }
}
 [INVALID_ARGUMENT]
```

**Comment by coryan** [comment]
> What would be the difference between `storage_delete_bucket_acl` and `storage_remove_bucket_owner`?

The second should probably remove a entity from the access control list that has `OWNER` privileges (as opposed to something milder).


> It errors with `type must be string, but is null` even though the [docs](https://cloud.google.com/storage/docs/json_api/v1/how-tos/performance#patch) say to delete a field you set it to NULL.

That documentation is less than ideal.  To remove a **field** you set it to `null`, but to remove an **entry from a list** you provide a new list with the entry removed :disappointed:

So what you want to do is get the bucket ACL, remove the entry you do not want, and patch the bucket with the new ACL.

**Comment by remyabel** [comment]
Thanks. One more question (sorry if this is annoying), `GetBucketAcl` returns a **single** ACL for a particular entity, right? So if we want to remove an entity from an ACL, I use `acl()` from `BucketMetadata` instead?

**Comment by coryan** [comment]
Oh, now that you mention that, there is this:

https://github.com/googleapis/google-cloud-cpp/blob/34da3bb63c1b918650dc903a3858c6b2f97bbf5c/google/cloud/storage/client.h#L1469

That seems like the right API to document here.  There is an existing example, we may be able to just re-use that example for this.

Yes, there are two ways to manipulate the ACLs in a bucket: the {Create,Delete,Get,List,Update,Patch}BucketAcl functions, through the metadata functions.  Actually it is three, you can do IAM policies too.

I think we should use `DeleteBucketAcl` here.

**Comment by remyabel** [comment]
If we just use `DeleteBucketAcl(bucket_name, entity)` by itself, doesn't `storage_remove_bucket_owner` become redundant? The .NET samples do this:

```C#
bucket.Acl = bucket.Acl.Where((acl) =>
    !(acl.Entity == $"user-{userEmail}" && acl.Role == "OWNER")
).ToList();
```

My similar attempt:

```c++
std::vector<gcs::BucketAccessControl> original_acl =
        original_metadata->acl();
    auto it = std::find_if(original_acl.begin(), original_acl.end(),
                           [entity](const gcs::BucketAccessControl& entry) {
                             return entry.entity() == entity &&
                                    entry.role() ==
                                        gcs::BucketAccessControl::ROLE_OWNER();
                           });
```

The problem is `original_metadata->acl()` seems to be empty. I guess I'm missing how you can remove an entry from ACLs using the `BucketAcl` API, but I'll take a break from this and let someone else tackle it.

**Comment by coryan** [comment]
> The problem is original_metadata->acl() seems to be empty.

Did you use `gcs::Projection::Full()`:

https://github.com/googleapis/google-cloud-cpp/blob/53a83d51c995c1a4621a105069870ba6824dfa31/google/cloud/storage/well_known_parameters.h#L428

The default (i.e. if we do not send a projection to the server) is equivalent to `NoAcl()`.

> I guess I'm missing how you can remove an entry from ACLs using the BucketAcl API, but I'll take a break from this and let someone else tackle it.

Fair enough.

**Comment by remyabel** [comment]
I believe these already have implementations:

`storage_add_bucket_default_owner`

https://github.com/googleapis/google-cloud-cpp/blob/88ad9eab286b0883f7707bb3ea4eb5f38b6b2117/google/cloud/storage/examples/storage_default_object_acl_samples.cc#L73

`storage_print_file_acl_for_user`

https://github.com/googleapis/google-cloud-cpp/blob/master/google/cloud/storage/examples/storage_object_acl_samples.cc#L130

**Comment by remyabel** [comment]
I think this can be closed now. All samples should either be implemented or have open issues.

**Comment by coryan** [comment]
Agree, thanks!
