### ISSUE TITLE
Adding sample snippets of GetMetaData and SetMetaData for InstanceAdmin

### ISSUE THREAD

**Issue by manish-qlogic** [googleapis/google-cloud-cpp#2264]
This issue/task is a result from #2253 

`instance.js` file has following snippets that are not part of C++
[bigtable_get_instance_metadata](https://github.com/googleapis/nodejs-bigtable/blob/ef790d498cecdd978b93d64cd1bb2de5dfca0eab/samples/document-snippets/instance.js#L226)
[bigtable_set_meta_data](https://github.com/googleapis/nodejs-bigtable/blob/ef790d498cecdd978b93d64cd1bb2de5dfca0eab/samples/document-snippets/instance.js#L269)

We need to write similar snippets in BigTable C++ client if proven worthy.

**Comment by dbolduc** [comment]
closed because example snippets already exist
