### ISSUE TITLE
Add samples for AppProfile for documentation.

### ISSUE THREAD

**Issue by manish-qlogic** [googleapis/google-cloud-cpp#2265]
This issue/task is a result from #2253

app-profile.js file has following snippets that are not part of BigTable C++ Client,
[bigtable_exists_app_profile](https://github.com/googleapis/nodejs-bigtable/blob/ef790d498cecdd978b93d64cd1bb2de5dfca0eab/samples/document-snippets/app-profile.js#L59)
[bigtable_app_profile_get_meta](https://github.com/googleapis/nodejs-bigtable/blob/ef790d498cecdd978b93d64cd1bb2de5dfca0eab/samples/document-snippets/app-profile.js#L96)
[bigtable_app_profile_set_meta](https://github.com/googleapis/nodejs-bigtable/blob/ef790d498cecdd978b93d64cd1bb2de5dfca0eab/samples/document-snippets/app-profile.js#L115)

If proven worthy, we need to write similar snippets in BigTable C++ client.

**Comment by coryan** [comment]
Closing because these samples are not in the internal tracker.
