### ISSUE TITLE
Use `CMAKE_BUILD_PARALLEL_LEVEL` when we upgrade CMake

### ISSUE THREAD

**Issue by ghost** [googleapis/google-cloud-cpp#2278]
After we upgrade CMake to 3.12.x or higher, we can use [`CMAKE_BUILD_PARALLEL_LEVEL`](https://cmake.org/cmake/help/latest/envvar/CMAKE_BUILD_PARALLEL_LEVEL.html) instead of the ad-hoc approach. The other advantage of `CMAKE_BUILD_PARALLEL_LEVEL` is that it is build tool agnostic and will allow us to set parallel jobs for other build generators than make/ninja.

**Comment by coryan** [comment]
We have stopped using super builds, this is now obsolete.
