### ISSUE TITLE
Refactor common external project options to a function?

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#2284]
It would be nice if we could refactor the common command-line options passed to `ExternalProject_Add()` into a function or something, today we have a lot of repetition, for example this snippet shows up in every external project:

https://github.com/googleapis/google-cloud-cpp/blob/afe8c7b76471b2596bd64ba7d90786da253fe2bb/cmake/external/protobuf.cmake#L60-L68

It would be nice if we could just write that code once and save it in a variable, or write a wrapper around `ExternalProject_Add()` which added these options.

Alternatively, some of these options are used for very specific builds, I wonder if Bazel is a better tool to say "compile the code and all the dependencies with these magic flags".

**Comment by devjgm** [comment]
We only use `ExternalProject_Add` in a single place now (`external/googleapis/CMakeLists.txt`). We remove nearly all uses when we got rid of our super/ build. So I think the refactoring in this issue is no longer needed.
