### ISSUE TITLE
Create code snippet for bigtable_create_family.

### ISSUE THREAD

**Issue by manish-qlogic** [googleapis/google-cloud-cpp#2287]
This code snippet demonstrate the use of `TableAdmin::ModifyColumnFamilies` to create column family for a given table.

corresponding node.js snippet is available [here](https://github.com/googleapis/nodejs-bigtable/blob/ef790d498cecdd978b93d64cd1bb2de5dfca0eab/samples/document-snippets/family.js#L18)

Bigtable C++ client has a similar [code snippet](https://github.com/googleapis/google-cloud-cpp/blob/fda670cd18082148054a650d42547d6f349a72f8/google/cloud/bigtable/examples/table_admin_snippets.cc#L148) but it tries to modify multiple things in one go, where as `bigtable_create_family` is intended for one thing only. 

**Note:** This issue/task is outcome of #2253

**Edit**

> bigtable_get_or_create_family: Auto-create column family if does not exist

Task #2254 suggests to add another snippet for `bigtable_get_or_create_family`. This test case can also  be clubbed in the PR.

**Comment by coryan** [comment]
I am going to close this one in favor of #2509.  I think the Node samples are too confusing.
