### ISSUE TITLE
Create code snippet for bigtable_get_family_metadata

### ISSUE THREAD

**Issue by manish-qlogic** [googleapis/google-cloud-cpp#2297]
Need to create code snippet for documentation purposes.

corresponding node.js snippet is available [here](https://github.com/googleapis/nodejs-bigtable/blob/ef790d498cecdd978b93d64cd1bb2de5dfca0eab/samples/document-snippets/family.js#L74)

**Note:** This issue/task is outcome of #2253

**Comment by coryan** [comment]
This was fixed in #2492.
