### ISSUE TITLE
Create code snippet for bigtable_set_family_meta

### ISSUE THREAD

**Issue by manish-qlogic** [googleapis/google-cloud-cpp#2298]
Need to create code snippet for documentation purposes.

corresponding node.js snippet is available [here](https://github.com/googleapis/nodejs-bigtable/blob/master/samples/document-snippets/family.js#L93)

**Note:** This issue/task is outcome of #2253

**Comment by coryan** [comment]
I am going to close this because the example is not listed in the official tracker, and the Node code seems kind of trivial.
