### ISSUE TITLE
Create code snippet for bigtable_check_table_exists

### ISSUE THREAD

**Issue by manish-qlogic** [googleapis/google-cloud-cpp#2299]
Need to create code snippet for documentation purposes.

corresponding node.js snippet is available [here](https://github.com/googleapis/nodejs-bigtable/blob/ef790d498cecdd978b93d64cd1bb2de5dfca0eab/samples/document-snippets/table.js#L41)

```
    // [START bigtable_exists_table]
    table
      .exists()
      .then(result => {
        const exists = result[0];
      })
      .catch(err => {
        // Handle the error.
      });
    // [END bigtable_exists_table]
  },
```
**Note:** This issue/task is outcome of #2253 

**Edit**
> bigtable_get_or_create_table: Get table details if it exists or auto-create table if does not exist

Task #2254 suggests to add another snippet for bigtable_get_or_create_table. This test case can also be clubbed in the PR.

**Comment by coryan** [comment]
I talked to @billyjacobson and we agreed to only implement the samples required by the tracker, so this issue is no longer valid.
