### ISSUE TITLE
Create code snippet for bigtable_get_families

### ISSUE THREAD

**Issue by manish-qlogic** [googleapis/google-cloud-cpp#2301]
Need to create code snippet for documentation purposes.

corresponding node.js snippet is available [here](https://github.com/googleapis/nodejs-bigtable/blob/master/samples/document-snippets/table.js#L118)

**Note:** This issue/task is outcome of #2253

**Comment by coryan** [comment]
I think this is (again) another case of Node having two implementations for similar examples, with different names:

https://github.com/googleapis/nodejs-bigtable/blob/master/samples/document-snippets/table.js#L118-L127

https://github.com/googleapis/nodejs-bigtable/blob/0d8412140ceb32bf70837c6d18d5d2ce47ffba78/samples/tableadmin.js#L168-L178

The second one (`bigtable_list_column_families`) is the region tag listed in the internal tracker, I am closing this one.
