### ISSUE TITLE
Create code snippet for bigtable_delete_all_cells

### ISSUE THREAD

**Issue by manish-qlogic** [googleapis/google-cloud-cpp#2302]
Need to create code snippet for documentation purposes. `Table::Apply` or `Table::BulkApply` can be used for this purpose.

corresponding node.js snippet is available [here](https://github.com/googleapis/nodejs-bigtable/blob/ef790d498cecdd978b93d64cd1bb2de5dfca0eab/samples/document-snippets/row.js#L85)

**Note:** This issue/task is outcome of #2253

**Comment by manish-qlogic** [comment]
To add more to the description, node.js snippet calls `delete()` from [row.ts](https://github.com/googleapis/nodejs-bigtable/blob/ef790d498cecdd978b93d64cd1bb2de5dfca0eab/src/row.ts#L330).

and this `delete()` further calls [`mutateRows`](https://github.com/googleapis/nodejs-bigtable/blob/ef790d498cecdd978b93d64cd1bb2de5dfca0eab/src/table.ts#L900) with following mutation

```  
  const mutation = {
      key: this.id,
      method: Mutation.methods.DELETE,
};
```

One way to achieve this with Bigtable CPP Client is explained [here](https://github.com/googleapis/google-cloud-cpp/blob/9835b14aedfd782e157d67e2a58006ecc7a1c432/google/cloud/bigtable/tests/mutations_integration_test.cc#L441)

**Comment by rsimion** [comment]
@manish-qlogic 
thanks
