### ISSUE TITLE
Create code snippet for bigtable_row_save

### ISSUE THREAD

**Issue by manish-qlogic** [googleapis/google-cloud-cpp#2305]
Need to create code snippet for documentation purposes. 

corresponding node.js snippet is available [here](https://github.com/googleapis/nodejs-bigtable/blob/ef790d498cecdd978b93d64cd1bb2de5dfca0eab/samples/document-snippets/row.js#L293).

**Note:** This issue/task is outcome of #2253

**Comment by coryan** [comment]
I talked to @billyjacobson and we agreed to only implement the samples required by the tracker, so this issue is no longer valid.
