### ISSUE TITLE
Create code snippet for bigtable_create_rules

### ISSUE THREAD

**Issue by manish-qlogic** [googleapis/google-cloud-cpp#2308]
This code snippet demonstrate the use of `Table::ReadModifyWriteRow `.

corresponding node.js snippet is available [here](https://github.com/googleapis/nodejs-bigtable/blob/ef790d498cecdd978b93d64cd1bb2de5dfca0eab/samples/document-snippets/row.js#L43).

**Note:** This issue/task is outcome of #2253.

**Comment by coryan** [comment]
I am closing this because after talking to @billyjacobson we are only going to implement the examples listed in the DPE tracker.
