### ISSUE TITLE
Create code snippet for bigtable_mutate_rows

### ISSUE THREAD

**Issue by manish-qlogic** [googleapis/google-cloud-cpp#2312]
Need to create code snippet for documentation purposes.

corresponding node.js snippet is available [here](https://github.com/googleapis/nodejs-bigtable/blob/ef790d498cecdd978b93d64cd1bb2de5dfca0eab/samples/document-snippets/table.js#L180).

**Note:** This issue/task is outcome of #2253

**Edit/Update**

> bigtable_mutate_delete_rows: Delete rows using mutate
> bigtable_mutate_mix_match: Mix and match mutation operations (insert rows, delete column)
> bigtable_insert_update_rows: Update or insert rows in a table
> bigtable_mutate_delete_columns: Delete columns within a row using mutate

Above mentioned snippets from task #2254 can be clubbed in a single PR. All of them demonstrates different ways of using `Apply` or `BulkApply`.

**Comment by coryan** [comment]
We are not going to implement `bigtable_mutate_rows`, it is only in Node, and there is no entry for it in the internal tool. Closing this, we already have open bugs for the other items.
