### ISSUE TITLE
Create code snippet for bigtable_create_replicated_cluster

### ISSUE THREAD

**Issue by manish-qlogic** [googleapis/google-cloud-cpp#2361]
This snippets must create 2 clusters in the same instance to demonstrate replication.  This could be a combination of `bigtable_create_prod_instance` and `bigtable_create_cluster`.

This snippet is required for documentation and is carved out of from #2254.

**Comment by manish-qlogic** [comment]
@coryan ,
This [page](https://cloud.google.com/bigtable/docs/replication-settings#backup) points out to 5 different use cases for replication settings.

Should we demonstrate "Provide near-real-time backup" use case in this snippet?

**Comment by coryan** [comment]
Is there a difference on how the clusters are created for these replication settings?  I think it is only the app profiles and how you use the replicated cluster affect those use cases you are showing?

**Comment by manish-qlogic** [comment]
> Is there a difference on how the clusters are created for these replication settings? 

no difference.

> I think it is only the app profiles and how you use the replicated cluster affect those use cases you are showing?

Yes, it shows how app profile can be control replication strategy.
 
The end user would want to create a cluster for replication and would want to use some replication settings for it. Snippet will be useful, if it demonstrate creation of additional cluster and use of app profiles to control replication behavior. 

I think, There would be no difference in [`bigtable_create_cluster`](https://github.com/googleapis/google-cloud-cpp/blob/92ae48ecb70107e5511eb64f766ee17bcd72f0ac/google/cloud/bigtable/examples/bigtable_instance_admin_snippets.cc#L207) and `bigtable_create_replicated_cluster` snippets if we dont show the use of app profiles along with it.

**Comment by coryan** [comment]
> > Is there a difference on how the clusters are created for these replication settings?
> 
> no difference.
> 
> > I think it is only the app profiles and how you use the replicated cluster affect those use cases you are showing?
> 
> Yes, it shows how app profile can be control replication strategy.
> 
> The end user would want to create a cluster for replication and would want to use some replication settings for it. Snippet will be useful, if it demonstrate creation of additional cluster and use of app profiles to control replication behavior.

I think we probably want a larger example to demonstrate this.  Something closer to a real application where we show how to configure different app profiles for different parts of the app maybe?

In any case, the code snippets should remain small and focused on one thing. And they should do the thing in the description, because we need them to be easy to compare from language to language.

**Comment by coryan** [comment]
I checked with @billyjacobson and we do not need to implement this example. Closing.
