### ISSUE TITLE
Create code snippet for deleting rows from a table.

### ISSUE THREAD

**Issue by manish-qlogic** [googleapis/google-cloud-cpp#2364]
There are currently 3 versions of region tags for this operation
- `bigtable_delete_rows` : Delete all rows
- `bigtable_mutate_delete_rows` : Delete rows using mutate
- `bigtable_truncate_table` : Truncate the table (delete all data)

This task is created for figuring out the differences between these 3 variations and creating corresponding code snippet.

This is a sub task from #2254

**Comment by coryan** [comment]
I am going to say that `bigtable_delete_rows` and `bigtable_truncate_table` are the same thing. Just put both region tags around the example here:

https://github.com/googleapis/google-cloud-cpp/blob/41c30cca2a9e744914cc351f32b90c91614068b4/google/cloud/bigtable/examples/table_admin_snippets.cc#L454

The `table_mutate_delete_rows` should use a mutation to delete full rows and was implemented already.

**Comment by coryan** [comment]
@manish-qlogic  I am just going to add the region tag, this has become a trivial change.
