### ISSUE TITLE
Create code snippet for bigtable_read_prefix

### ISSUE THREAD

**Issue by manish-qlogic** [googleapis/google-cloud-cpp#2365]
Extracted from the task #2254 

Need to create following snippet in `data_snippets.cc`, this snippet demonstrates the use of `cbt::RowRange::Prefix()` in `ReadRows`. 

`bigtable_read_prefix` : Read rows with row keys matching a given prefix

**Comment by rsimion** [comment]
@manish-qlogic 

data_snippets.cc already has a ReadRows() example showing how to use Prefix
#1926

**Comment by manish-qlogic** [comment]
As per #2254, We need to have 2 snippets namely `bigtable_read_prefix_list` and `bigtable_read_prefix`. 

bigtable_read_prefix: Read rows with row keys matching a given prefix
bigtable_read_prefix_list: Read rows with row keys matching any prefix in a list

The one in [data_snippets.cc](https://github.com/googleapis/google-cloud-cpp/blob/568b27a6bf7dec3c03af00eb9e04ba761874f4ae/google/cloud/bigtable/examples/data_snippets.cc#L333) is marked as an example for `bigtable_read_prefix_list`.   it appends only one prefix though.

`bigtable_read_prefix` is different in a sense that it only pass one prefix not a list of prefix. So we need to create 2 snippets , one with prefix list and another one with single prefix.

**Comment by rsimion** [comment]
There are 3 functions in data_snippets.cc
PopulateTableHierarchy (populate the table)
ReadRowSet (read using a list of keys)
ReadRowSetPrefix (read using any prefix)
Just wanted to make sure that we do not repeat the same thing. I assigned it to myself.
