### ISSUE TITLE
Create code snippet for additional scenarios of ReadRows

### ISSUE THREAD

**Issue by manish-qlogic** [googleapis/google-cloud-cpp#2366]
Extracted from the task #2254

Need to create following snippets in `data_snippets.cc`, this snippet demonstrates the use of `cbt::RowSet()` for `ReadRows`.

`bigtable_read_multiple_ranges` : Read multiple sets of ranges given sets of start, end row keys

`bigtable_read_keys_set` : Read using non-continguous set of row keys

**Comment by coryan** [comment]
I duplicated this in #2505 and #2506.
