### ISSUE TITLE
Consider guidance to avoid `StatusOr<bool>`

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#2390]
`StatusOr<bool>` (and similarly, `optional<bool>`) can be easy to use incorrectly because it has an `operator bool` that makes call sites *appear* to be checking the contained boolean value when it's actually only checking that the StatusOr itself is OK. Consider the following code:

```
StatusOr<bool> CheckAndMutateRow(...);
...
auto result = CheckAndMutateRow(...);
if (result) {  // <--- BUG
  // ....
}
```

In the above code, `if (result)` is checking that the StatusOr itself is OK. But it's likely that the intent was actually to check that the bool returned from CheckAndMutate was true. That is, it's likely that the caller intended to write `if (result && *result)`. See #2389 for an example bug fixed.

I'm now wondering whether `StatusOr<bool>` itself is a code smell. Is it too easy to use wrong? Are there better alternatives?

I think it might be good for us to try to avoid `StatusOr<bool>`. Instead, I imagine that in most cases the bool could be replaced by another type. For example, in the `CheckAndMutateRow` example above ([code](https://github.com/googleapis/google-cloud-cpp/blob/241ef65c7219550a7c819b4f9d027bbb08b3a35b/google/cloud/bigtable/table.h#L325)), the bool could easily be replaced with an enum. 

```cc
 // OLD
 StatusOr<bool> CheckAndMutateRow(std::string row_key, Filter filter,
                                   std::vector<Mutation> true_mutations,
                                   std::vector<Mutation> false_mutations);

 // NEW
 enum class FilterResult { PASSED, FAILED };  // TODO: good naming
 StatusOr<FilterResult> CheckAndMutateRow(std::string row_key, Filter filter,
                                   std::vector<Mutation> true_mutations,
                                   std::vector<Mutation> false_mutations);
```

Then, at call sites, callers would have to be more explicit about comparing the result to `FilterResult::PASSED`.

Anyway, this is an issue for discussion. I'd be curious to hear others' opinions.

/cc: @devbww @coryan @scotthart @mr-salty

**Comment by coryan** [comment]
I think I am inclined to **not** use `StatusOr<bool>`.  We changed `CheckAndMutateRow` to use an enum, and discovered some code that was confusing the boolean of the `StatusOr` vs. the boolean inside the `StatusOr`. Whether this should be a general rule, I am less certain of: in general I distrust general rules, in general :grin:

**Comment by devjgm** [comment]
This is an old issue. While I think `StatusOr<bool>` should likely be avoided, it doesn't seem to be causing us much trouble, meaning, we're not really tempted to use it. To avoid making unnecessary work for ourselves, let's just close this and address it if it actually becomes a problem.
