### ISSUE TITLE
Change optional's member op== and op!= to free functions

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#2392]
When binary operators are implemented as member functions, they are subtly asymmetric since the LHS does not participate in any implicit conversions, while the RHS does. For example:

```cc
struct A {
  bool operator==(A const& a);
};

struct Foo {
  operator A() const;  // convertible to A;
};

Foo foo;
A a;
assert(a == foo); // OK
assert(foo == a);  // Won't compile
```

To ensure that binary operators are symmetric wrt implicit conversions, it's best to implement them as non-member functions. See also http://go/gh/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#c161-use-nonmember-functions-for-symmetric-operators

Please change [op== and op!=](https://github.com/googleapis/google-cloud-cpp/blob/master/google/cloud/optional.h#L213) in `optional` to be non-members.

**Comment by devjgm** [comment]
Since `optional` also has all the othe relational operators, you probably want to move those to be non-members as well.

**Comment by mr-salty** [comment]
so, I failed to read the bug description and started changing *all* the relational operators to free functions... seems like I might as well just finish that up at this point.

also, @coryan - is it a bug that this operator== does not compare 'owner_'?

https://github.com/googleapis/google-cloud-cpp/blob/7b0746c3f2e466c074658d10907cf8d756cf21c0/google/cloud/storage/internal/common_metadata.h#L131

**Comment by coryan** [comment]
The missing `owner_` does look like a bug.
