### ISSUE TITLE
CMake: `CURL::CURL` target should be -> `CURL::libcurl`

### ISSUE THREAD

**Issue by past-due** [googleapis/google-cloud-cpp#2406]
`CURL::libcurl` matches what libcurl exports and also what FindCURL defines as of CMake 3.12+.

See: https://cmake.org/cmake/help/v3.12/module/FindCURL.html

This impacts:
- cmake/IncludeCurl.cmake
- cmake/external/curl.cmake
- google/cloud/storage/CMakeLists.txt
- google/cloud/storage/config.cmake.in
- google/cloud/storage/tests/CMakeLists.txt

A patch is available here: https://github.com/googleapis/google-cloud-cpp/compare/master...past-due:fix_cmake_curl_target

**Comment by coryan** [comment]
Thanks!  The patch looks great.  I created a PR (#2407).  Would you be willing to sign the CLA so we can merge your patch?

**Comment by past-due** [comment]
Yep - CLA signed. 👍

**Comment by coryan** [comment]
BTW, I am still wondering where I picked `CURL::CURL` from... because I am not that creative.
In any case, the PR is merged, this is fixed. Thanks again for the bug report.
