### ISSUE TITLE
Ubuntu 14.04 will be EOL soon

### ISSUE THREAD

**Issue by remyabel** [googleapis/google-cloud-cpp#2408]
This bug is to track that Ubuntu 14.04 will be EOL [April 17th](https://askubuntu.com/questions/1126909/when-is-the-exact-date-for-eol-of-ubuntu-14-04-lts/1126933#1126933).

**Comment by coryan** [comment]
I was not going to forget, because I am looking forward to removing all the stuff for that particular version 😬

**Comment by coryan** [comment]
Fixed in #3257
