### ISSUE TITLE
Create the  storage_list_file_archived_generations sample.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#2415]
Create a sample that "List archived generations for an object in a GCS bucket".  The tag should be `storage_list_file_archived_generations`.  Details (such as they exist) are available inside Google at go/gcs-sample-tracker

Similar samples are in:

https://github.com/googleapis/google-cloud-cpp/blob/master/google/cloud/storage/examples/storage_object_samples.cc

**Comment by coryan** [comment]
I just noticed that this example exists, but with an incorrect tag: `storage_list_versioned_files`.  I am fixing other tags, so I can just go ahead and fix this one too.  Does that sound Okay?

**Comment by scotthart** [comment]
SGTM
