### ISSUE TITLE
Replace ad-hoc Join with Abseil StrJoin

### ISSUE THREAD

**Issue by ghost** [googleapis/google-cloud-cpp#2442]
This has been brought up in a couple of PRs, so we might as well open an issue to track it. When we add Abseil as a dep, we should be using `StrJoin` in these places:

https://github.com/googleapis/google-cloud-cpp/blob/4bfb249145767fd2740a339403206ac6ed64060a/google/cloud/storage/policy_document.cc#L26

https://github.com/googleapis/google-cloud-cpp/blob/60117041083c3fe9925fab2eb650807eb96066cf/google/cloud/storage/internal/sign_blob_requests.cc#L25

https://github.com/googleapis/google-cloud-cpp/blob/51e147b7c10dab5839fb65a3486ae0438ff8e4d1/google/cloud/storage/bucket_metadata.cc#L30

**Comment by coryan** [comment]
Note that this is blocked by #2309.
