### ISSUE TITLE
Consider fixing warnings emitted by ShellCheck

### ISSUE THREAD

**Issue by remyabel** [googleapis/google-cloud-cpp#2463]
[ShellCheck](https://github.com/koalaman/shellcheck) is a static analysis tool for shell scripts. I ran it on this codebase and here's the list of warnings emitted run through `uniq`. We can decide individually what warnings we care about and don't.

[SC2007](https://github.com/koalaman/shellcheck/wiki/SC2007): Use $((..)) instead of deprecated $[..]
[SC2016](https://github.com/koalaman/shellcheck/wiki/SC2016): Expressions don't expand in single quotes, use double quotes for that.
[SC2034](https://github.com/koalaman/shellcheck/wiki/SC2034): attempt appears unused. Verify use (or export if used externally).
[SC2044](https://github.com/koalaman/shellcheck/wiki/SC2044): For loops over find output are fragile. Use find -exec or a while read loop.
[SC2046](https://github.com/koalaman/shellcheck/wiki/SC2046): Quote this to prevent word splitting.
[SC2048](https://github.com/koalaman/shellcheck/wiki/SC2048): Use "$@" (with quotes) to prevent whitespace problems.
[SC2078](https://github.com/koalaman/shellcheck/wiki/SC2078): This expression is constant. Did you forget a $ somewhere?
[SC2086](https://github.com/koalaman/shellcheck/wiki/SC2086): Double quote to prevent globbing and word splitting.
[SC2146](https://github.com/koalaman/shellcheck/wiki/SC2146): This action ignores everything before the -o. Use \( \) to group.
[SC2153](https://github.com/koalaman/shellcheck/wiki/SC2153): Possible misspelling: BUCKET_NAME may not be assigned, but bucket_name is.
[SC2155](https://github.com/koalaman/shellcheck/wiki/SC2155): Declare and assign separately to avoid masking return values.
[SC2156](https://github.com/koalaman/shellcheck/wiki/SC2156): Injecting filenames is fragile and insecure. Use parameters.
[SC2164](https://github.com/koalaman/shellcheck/wiki/SC2164): Use 'cd ... || exit' or 'cd ... || return' in case cd fails.
[SC2166](https://github.com/koalaman/shellcheck/wiki/SC2166): Prefer [ p ] && [ q ] as [ p -a q ] is not well defined.
[SC2181](https://github.com/koalaman/shellcheck/wiki/SC2181): Check exit code directly with e.g. 'if mycmd;', not indirectly with $?.
[SC2196](https://github.com/koalaman/shellcheck/wiki/SC2196): egrep is non-standard and deprecated. Use grep -E instead.
[SC2230](https://github.com/koalaman/shellcheck/wiki/SC2230): which is non-standard. Use builtin 'command -v' instead.

**Comment by remyabel** [comment]
Notes:

- We probably want to ignore unused warnings for instances like `TESTBENCH_DUMP_LOG`. The warning complaining about `attempt` (where `attempt` is just a dummy variable) suggests renaming it to `_` instead.

- Bash is perfectly OK with nested quotes. Where we are using `dirname $0`, the `$0` should also be enclosed in quotes.

**Comment by coryan** [comment]
Is it possible to run this as part of `check-style.sh` or something like it?

**Comment by coryan** [comment]
Also, there are services, like codacy that run things like this:

https://github.com/codacy/codacy-shellcheck

maybe we can just turn on codacy and we do not need to configure a lot of stuff?

**Comment by remyabel** [comment]
> Is it possible to run this as part of check-style.sh or something like it?

Yes. We can just install it like any other tool in the docker files. It looks like it's available for Debian-based distros, Fedora, OSX (via homebrew) and openSUSE and probably CentOS too. Then we can just add this to `check-style.sh`:

```
find . -type f -iname '*.sh' -exec shellcheck --exclude=SC1090 '{}' \;
```

SC1090 is an extraneous warning that complains about annotating lines that source scripts, so I just disable it.

**Comment by devjgm** [comment]
I'm not sure if addressing the "`SC2155: Declare and assign separately to avoid masking return values.`" warnings will be worth the annoyance of writing:
```shell
foo="$(mycmd)"
local foo
```
instead of
```shell
local foo="$(mycmd)"
```

I'm curious what others think.

**Comment by remyabel** [comment]
As I said in #2475 it depends on whether or not we care about the return values. `set -eu` is being set at the top of the scripts, and according to [SC2155's page](https://github.com/koalaman/shellcheck/wiki/SC2155) `set -e` doesn't work properly unless you split the lines. If we decide in the lines I changed we don't care about the return values, we can either make it read-only (silences the warning) or exclude the warning.

**Comment by coryan** [comment]
What @remyabel said, this program exists successfully, and we probably wanted the error:

```sh
/bin/bash -c "f() { local foo=$(/bin/false); } ; set -e; f;"
```

**Comment by devjgm** [comment]
Yep, I understand the concern about missing failed subcommands in command substitutions on the same line as a `local` or `readonly`. Here are some reasons still questioning the value of this check:

1. Usually when `local` and `readonly` (and `export`) are used, the stdout of the subcommand is what's important, not the return value. So typically, the string output of the variable will be subsequently checked in in the script. For example, `local x=$(dirname ...); if [[ -d "$x" ]]`, or something. I think this is the typical use case.

2. Most of our uses of `local` should really be `local -r`, and those aren't flagged by shellcheck because they have to be on one line.

Overall, I don't think the value we'll get out of this particular check will be worth the hassle of us trying to remember when we need to split local/export/readonly into two lines. But this is just my opinion. I can see that there's already at least two votes in favor of this and only my one vote against it :-), so I'm happy to admit that I'm outvoted and enable this.

However, if we enable this, I think we should encourage our two-line initialization to be written with the `local var` declared first, then assigned to:

```shell
local foo
foo="$(mycmd)"
```

I think this looks less weird, and seems to make sense since `foo` never exists as a non-local variable.

**Comment by remyabel** [comment]
> But this is just my opinion. I can see that there's already at least two votes in favor of this and only my one vote against it :-)

FYI, I'm not voting either way. I agree with all your stated points and I'm happy to revise the PR with whatever the consensus is. Currently, most of the warnings emitted so far are in the tests for lines like this:

```shell
local token
token="$(./table_admin_snippets generate-consistency-token ${project_id} ${INSTANCE} ${TABLE} | awk '{print $5}')"
```

Unlike the examples run by `run_example`, the return value is not checked. `run_example` does explicitly check the return value. We just assume that these lines always succeed, but by coincidence if these lines fail, the subsequent examples will probably fail too. By splitting it into two lines, any failure will be caught by `set -e`. I think if we're going to change it, we should explicitly check the output like you suggested.

**Comment by devjgm** [comment]
FTR: Enabling the SC2155 warning seems like the safer option. So I'm happy to move forward with enabling it and revisit that decision IFF it actually proves to be annoying.
