### ISSUE TITLE
Update our version of "googleapis" protos

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#2537]
Our cmake build is fetching a version of github.com/googleapis/googleapis from [June 2018](https://github.com/googleapis/googleapis/commit/6a3277c0656219174ff7c345f31fb20a90b30b97) ([our cmake config](https://github.com/googleapis/google-cloud-cpp/blob/master/cmake/external/googleapis.cmake#L29)). This old version is missing some recent features from Spanner, such as the batch DML stuff, which was added around [March 2019](https://github.com/googleapis/googleapis/commit/8610b13d3da5e3230cf99c503558961626186249#diff-d3a56721144d7d2ae9f2707f0dc16547). It may be missing other proto features that were added.

This is the same in our [bazel config](https://github.com/googleapis/google-cloud-cpp/blob/master/bazel/google_cloud_cpp_deps.bzl#L45) also.

I'm going to prepare a PR to update our version of the googleapis protos, but this raises a couple questions:

1. Could this break anything else? In general proto and gRPC changes are supposed to be backward compatible, so I want to say "no, nothing will break here", but ya know, maybe? Is there anything for us to do here other than our normal CI testing?

2. Should we do anything more to keep current w/ the rpc protos we're using? Maybe check for and update them after each monthly release? Or just do a manual update when we discover that we need a new version for some reason?

**Comment by coryan** [comment]
Please do the update.  A heads up to prepare yourself: last time I tried to do this the BUILD files distributed with googleapis/googleapis required command-line arguments to compile. That is `bazel build //google/cloud/...:all` stopped working.

Let me forward you the thread which includes the command-line options needed.  But, again, that was last time, maybe the upgrades to bazel removed the need to add those options.

**Comment by devjgm** [comment]
A few more details. Yes, I think we need to update the version of googleapis that we're using. We might as well pick the most recent commit, which appears to be https://github.com/googleapis/googleapis/commit/25cbfd4a5386742f5968d69bd276a0436d23bd97 (well, it was the latest last night. They just did another commit today, so we should probably pick that one instead).

It was fairly easy to update our cmake build to use this newer commit. I was able to do it in a local branch with a diff like

```diff
diff --git a/cmake/external/googleapis.cmake b/cmake/external/googleapis.cmake
index 5a4e14f5..3d1c85ce 100644
--- a/cmake/external/googleapis.cmake
+++ b/cmake/external/googleapis.cmake
@@ -26,10 +26,10 @@ if (NOT TARGET googleapis_project)
     # downloaded from GitHub.
     set(
         GOOGLE_CLOUD_CPP_GOOGLEAPIS_URL
-        "https://github.com/googleapis/googleapis/archive/6a3277c0656219174ff7c345f31fb20a90b30b97.tar.gz"
+        "https://github.com/google/googleapis/archive/25cbfd4a5386742f5968d69bd276a0436d23bd97.zip"
         )
     set(GOOGLE_CLOUD_CPP_GOOGLEAPIS_SHA256
-        "793f1fe9d3adf28900792b4151b7cb2fa4ef14ae1e14ea4e7faa2be14be7a301")
+        "2d9842eea9f2eae3db3993759ba3669cf624b6d2131b1aabdbd0e56b913e96c1")
 
     if ("${CMAKE_GENERATOR}" STREQUAL "Unix Makefiles"
         OR "${CMAKE_GENERATOR}" STREQUAL "Ninja")
```

Making the analogous change for bazel did not work however. I first tried the following diff, which **does not work**.

```diff
diff --git a/bazel/google_cloud_cpp_deps.bzl b/bazel/google_cloud_cpp_deps.bzl
index 06cd931e..0a13ac18 100644
--- a/bazel/google_cloud_cpp_deps.bzl
+++ b/bazel/google_cloud_cpp_deps.bzl
@@ -42,10 +42,10 @@ def google_cloud_cpp_deps():
         http_archive(
             name = "com_github_googleapis_googleapis",
             urls = [
-                "https://github.com/google/googleapis/archive/6a3277c0656219174ff7c345f31fb20a90b30b97.zip",
+                "https://github.com/google/googleapis/archive/25cbfd4a5386742f5968d69bd276a0436d23bd97.zip",
             ],
-            strip_prefix = "googleapis-6a3277c0656219174ff7c345f31fb20a90b30b97",
-            sha256 = "82ba91a41fb01305de4e8805c0a9270ed2035007161aa5a4ec60f887a499f5e9",
+            strip_prefix = "googleapis-25cbfd4a5386742f5968d69bd276a0436d23bd97",
+            sha256 = "2d9842eea9f2eae3db3993759ba3669cf624b6d2131b1aabdbd0e56b913e96c1",
             build_file = "@com_github_googleapis_google_cloud_cpp//bazel:googleapis.BUILD",
         )
``` 

After that change, a `bazel build google/cloud/bigtable/...` blows up. I think the problem is due to the fact that in Nov '18, [they added their own BUILD files for their project](https://github.com/googleapis/googleapis/commit/b92c0fc1282ecc28972d002b0307ccf4eccb81e4#diff-0ea22445d900db774c8deb00f4a4df55), and our `bazel/googleapis.BUILD` file should no longer be used.

So, I think the next steps would look something like the following:

1. Change our cmake build to use a recent commit of googleapis/googlepis. I think this should be relatively easy per the description above. Don't submit this as a separate PR, because we want our cmake and bazel builds to be consistent wrt to dep versions.

2. Remove our `bazel/googleapis.BUILD` file and the references to it, so that we can start using all the target names as they are specified in googleapi's BUILD files.

3. Update our BUILD files that reference googleapis protos to use the correct target names as they are specified in the BUILD files. From a quick grep, I think that should be only
    *  `google/cloud/bigtable/BUILD`
    *  `google/cloud/spanner/BUILD`
    * (Nothing from GCS because it uses json/xml, not the protos.)

4. Cross your fingers and run `bazel test google/...` ??? :-)

5. If it all works, send a PR

cc: @scotthart who might be interested in taking this issue from me.

**Comment by devjgm** [comment]
Assigning this to Scott, who volunteered to take a look. Scott, please let me know if you have any questions.

Note: Yes, this issue should probably live in https://github.com/googleapis/google-cloud-cpp-spanner/issues, but it was filed before that repo existed.
