### ISSUE TITLE
Homogenize use of InstanceId, ClusterId, etc.

### ISSUE THREAD

**Issue by dopiera** [googleapis/google-cloud-cpp#2554]
Some of the API calls use `std::string` for parameters and some the respective stronger variants - `InstanceId`, `ClusterId`, etc. We should homogenize on the latter.

**Comment by coryan** [comment]
I agree we want to be consistent, but I am not sure the strongly typed strings are worth the hassle.

**Comment by coryan** [comment]
@devjgm I would like to hear your opinion on this.  Some of the RPCs in Cloud Bigtable take several string parameters, and we introduced strong types:

https://github.com/googleapis/google-cloud-cpp/blob/223b3736f71e81540f5176d336f77f8760f57ecd/google/cloud/bigtable/internal/strong_type.h#L56-L65

to minimize out-of-order parameter errors:

https://github.com/googleapis/google-cloud-cpp/blob/223b3736f71e81540f5176d336f77f8760f57ecd/google/cloud/bigtable/instance_admin.h#L237-L239

I think the strong types are more trouble that they are worth, and would rather see them removed everywhere.

Thoughts?

**Comment by coryan** [comment]
I talked offline with @devjgm and we both agree that these strong types for strings do not add a lot of value.  I think we should remove them and call it a day.
