### ISSUE TITLE
Update CI scripts and create instructions to host doxygen doc for branches

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#257]
When updating the Doxygen documentation it is useful to upload the feature branch docs to `github.io` so reviewers (and the author!) can see how the new docs look like.  Right now it is not very easy to do that because:

- We do not have instructions on how to do it.
- The CI builds (if enabled on your account) erase all changes to the `gh-pages` branch when `master` is updated.

**Comment by coryan** [comment]
For the record, if one runs:

```console
$ CXX=g++ CC=gcc CHECK_STYLE=yes GENERATE_DOCS=yes BUILD_TYPE=Release TRAVIS_OS_NAME=linux DISTRO=ubuntu DISTRO_VERSION=17.10 ./ci/build-linux.sh
$ TRAVIS_PULL_REQUEST=false TRAVIS_BRANCH=master GENERATE_DOCS=yes BUILD_TYPE=Release TRAVIS_OS_NAME=linux DISTRO=ubuntu DISTRO_VERSION=17.10 ./ci/upload-docs.sh
```

Then the Doxygen docs get posted to `<username>.github.io/google-cloud-cpp/'.  One can do that from any branch.  The only problem is that pushing to your `master`, if you have enabled Travis builds for your fork, will immediately overwrite the docs.

**Comment by remyabel** [comment]
The [gh-pages provider](https://docs.travis-ci.com/user/deployment/pages/) has been around for a while now.

**Comment by remyabel** [comment]
Assuming you're okay with migrating to the gh-pages provider, then it will look something like this:

```diff
diff --git a/.travis.yml b/.travis.yml
index 567d9cab..e2124ad2 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -82,6 +82,7 @@ matrix:
 
 script:
   - ci/travis/build-linux.sh
+  - ci/travis/build-docs.sh
 
 # We do not need to recursively extract the submodules. This saves some time in
 # the builds, the default install step then performs a lighter weight module
@@ -97,7 +98,6 @@ install:
 
 after_success:
   - ci/travis/upload-codecov.sh
-  - ci/travis/upload-docs.sh
   - ci/travis/dump-logs.sh
 
 after_failure:
@@ -116,5 +116,19 @@ before_cache:
   # if the installation is in the cache.
   - rm -fr ${HOME}/.cache/bazel/_bazel_${USER}/install
 
+# Note: deployment is always skipped for pull requests.
+deploy:
+  provider: pages
+  skip-cleanup: true
+  github-token: $GH_TOKEN
+  keep-history: true
+  email: "google-cloud-cpp-bot@users.noreply.github.com"
+  name: "Google Cloud C++ Project Robot"
+  local-dir: docs-output
+  on:
+      all_branches: true
+      # Only deploy for master and release branches.
+      condition: "${GENERATE_DOCS:-}" == "yes" || $TRAVIS_BRANCH =~ ^master|v[0-9]\.*$
+
 notifications:
   email: false
```

It's fairly common (in my experience) for the order of operations to be:
- The provider clones the source repo
- Docs are built along with everything else
- The artifacts are copied to a directory (`docs-output` in this case) which is what ultimately gets pushed to `gh-pages`

Currently `upload-docs.sh` obtains CSS/JS/... assets from the existing `gh-pages` branch which is kind of wonky. I believe those should either be in the source tree or at least pulled from a CDN.

**Comment by coryan** [comment]
@remyabel I like the idea of a `gh-pages` provider.  There is one use-case that is not immediately obvious how to solve with this:  let's say I made some big changes to the documentation, and I want to show them to the reviewers during a PR.  Can I upload those to my `github.io` page?  Obviously yes, but can I do that with a well tested script or instructions?

**Comment by remyabel** [comment]
I have not tested it yet (I disabled Travis on my account after the controversy over the acquisition), but in principle, the conditional should allow it:

> on:
>     all_branches: true
>     # Only deploy for master and release branches.
>     condition: "${GENERATE_DOCS:-}" == "yes" || $TRAVIS_BRANCH =~ ^master|v[0-9]\.*$

If `GENERATE_DOCS` is explicitly enabled, then it should deploy on *any* branch. If it isn't, then it only deploys on master/release branches. The if statements in `upload-docs.sh` will need to be updated too. Of course, you only get one `gh-pages` branch, but since we are preserving history, it's easy to revert to a previous commit.

**Comment by coryan** [comment]
So I could change the `.travis.yml` file, push to the CI system, that would push to the `gh-pages`, then I have to remember to undo the changes in the `.travis.yml` file before merging?

What do you think of changing the condition to:

```
condition: commit_message =~ \[generate-docs\] || branch =~ ^master|v[0-9]\.$ 
```

That way I can just include the `[generate-docs]` magic tag in my commit and it will do the trick, no need to change `.travis.yml` and then change it back.  I am not sure `[generate-docs\]` with the brackets is a great tag btw, but something like it would be great.

**Comment by remyabel** [comment]
> So I could change the `.travis.yml` file, push to the CI system, that would push to the `gh-pages`, then I have to remember to undo the changes in the `.travis.yml` file before merging?

Yeah, my mistake. I forgot that `GENERATE_DOCS` would be populated by the build matrix.

> What do you think of changing the condition to:

That would probably be the best approach.

**Comment by tmatsuo** [comment]
@coryan 
How about to add a capability of generating and uploading the docs under an arbitrary sub directory?

Maybe little tweak in upload-docs.sh?
```sh
subdir=""
if [[ "${DOCS_SUBDIR:-}" ne "" ]]; then
  subdir="${DOCS_SUBDIR}"
else 
  case "${TRAVIS_BRANCH:-}" in # Original case statement
  ....
  esac
fi
```
Then you can do sth like:

```sh
$ TRAVIS_PULL_REQUEST=false DOCS_SUBDIR=my-fancy-feature GENERATE_DOCS=yes BUILD_TYPE=Release TRAVIS_OS_NAME=linux DISTRO=ubuntu DISTRO_VERSION=17.10 ./ci/travis/upload-docs.sh
```

Then I hope you can have it under `<username>.github.io/google-cloud-cpp/my-fancy-feature` ?

A downside might be probably you will need to clean up the subdirs when it's not needed any more.

**Comment by coryan** [comment]
LGTM. Look forward to the PR :grinning:

**Comment by remyabel** [comment]
Small offtopic comment: `TRAVIS_PULL_REQUEST` is automatically set by Travis, you can omit it from the command line.
