### ISSUE TITLE
[Flake]: "Install" tests can fail if package repos are temporarily not working.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#2594]
The `cloud-cpp/install/*` Kokoro builds can fail if the package repositories for the particular distribution are not working for a while. For example see:

https://source.cloud.google.com/results/invocations/c59bdbb0-b8d7-47ad-967d-04cf895869fc/targets

One fix would be to retry on these failures. That might be hard because it is all in one large Dockerfile so we would need to split it.

Another fix would be to cache the Docker image with the development tools in GCR (the Google Cloud Container Registry), docker would not need to actually run the "apt install" if that portion of the Dockerfile has not changed.  That is both potentially faster and should be less flaky.

```
http://mirror.sjc02.svwh.net/fedora-epel/7/x86_64/repodata/b8a254680843940cc0fd372acbdad5fd3fe094ce9893a66023e7235c83d5ea63-other.sqlite.bz2: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
 One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:
     1. Contact the upstream for the repository and get them to fix the problem.
     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).
     3. Run the command with the repository temporarily disabled
            yum --disablerepo=<repoid> ...
     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:
            yum-config-manager --disable <repoid>
        or
            subscription-manager repos --disable=<repoid>
     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:
            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true
epel: Check uncompressed DB failed
The command '/bin/sh -c yum makecache &&     yum install -y automake cmake3 curl-devel gcc gcc-c++ git libtool make         openssl-devel pkgconfig tar wget which zlib-devel' returned a non-zero code: 1
```

**Comment by remyabel** [comment]
Could this be a Kokoro flake? It appears to iterate over all of the mirrors and fails with `HTTP Error 404 - Not Found`, suggesting an Internet issue.

**Comment by coryan** [comment]
Possibly, it could be that the network used by Kokoro to access the Internet was flaky.  But the builds for other distributions did not flake out though, so my prior is that this was CentOS-specific.

In any case, the build scripts need to be made more tolerant of these failures.

**Comment by tmatsuo** [comment]
Considering any docker build may fail, is it worth adding generic retry code around `docker build`?

**Comment by tmatsuo** [comment]
Oh, I just realized this test is solely implemented as a Dockerfile. Let me think more about it

**Comment by remyabel** [comment]
I still vote for the second option, which is caching the image. And if we do go for that route I wonder if we can rearrange the steps like this:

- Install system packages
- Install CBT components
- Install crc32c 1.0.6
- Install googletest
- Install bazel
- Install pip dependencies

The first three are pinned to a specific version, they change infrequently. And I would expect the pip dependencies to update more frequently (in my experience) so they are last.

**Comment by tmatsuo** [comment]
@remyabel I see. I have a little concern on caching the image. I'm assuming it will prevent the test from installing newer packages from yum repository, because docker doesn't detect the changes in the yum or apt repositories. This means that the test may fail to catch errors in our README and INSTALL instructions with newer yum/apt packages.

Am I missing something?

**Comment by remyabel** [comment]
In the specific case of Ubuntu/Debian, the cache busting is resolved by combining `apt update` and `apt install` into one line, like `RUN apt-get update && apt-get install -y s3cmd postgresql wget`. For Fedora/CentOS I see that @coryan explicitly uses `dnf makecache`. I don't know if those distros have the same issue, but `dnf clean all` will wipe the cache so we can try that if there's an issue.

**Comment by remyabel** [comment]
Actually you are correct. My response was to a completely different issue. I guess a workaround is to periodically run a build with `--no-cache=true`.

**Comment by tmatsuo** [comment]
@coryan @remyabel 

Yeah, considering the purpose of tests under ci/test-readme is to make sure the README and INSTALL instructions are correct, I would not cache the Docker build.

Instead, how about to install a simple bash script which just retries the given command N times, and stripping out that command in `dockerfile2markdown.sh`?

```Dockerfile
COPY ci/test-readme/retry3 /retry3
RUN chmod +x /retry3
## [START README.md]
RUN /retry3 yum makecache &&
         /retry3 yum install -y .....
```

and
```bash
sed -e 's|/retry3 ||' \
```

**Comment by coryan** [comment]
> Instead, how about to install a simple bash script which just retries the given command N times, and stripping out that command in `dockerfile2markdown.sh`?

That SGTM, keep in mind that there is such a script already in the `ci/` directory, so there is no need to rewrite it (but there may be a need to make sure it works in all the distros).
