### ISSUE TITLE
Use explicit return types in code samples.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#2604]
Though using `auto result = ...` is perfectly idiomatic, the purpose of the examples is to show how the functions are used, we should be explicit in them, e.g.:

```C++
namespace cbt = google::cloud::bigtable;
using google::cloud::StatusOr;
[](Table table) {
  StatusOr<std::pair<bool, cbt::Row>> row = table.ReadRow("foo");
```

That makes the example more readable to our customers. This gets even more important for more complex return types, such as:

```C++
namespace cbt = google::cloud::bigtable;
using google::cloud::StatusOr;
[](Table table) {
  future<StatusOr<std::pair<bool, cbt::Row>>> row = table.AsyncReadRow("foo");
```

**Comment by coryan** [comment]
Assigning to @remyabel so nobody else will start on it (they already did).  @remyabel please let me know if you want me to un-assign this issue.

**Comment by remyabel** [comment]
You can unassign me. It was fairly tedious doing the PR (even though I was using YCM to get the type of each expression) so others may prefer to tackle individual files.

**Comment by coryan** [comment]
Create a checklist for myself:

- [ ] bigtable_hello_app_profile.cc 
- [ ] bigtable_hello_world.cc 
- [ ] bigtable_instance_admin_snippets.cc 
- [ ] bigtable_quickstart.cc 
- [ ] data_async_snippets.cc 
- [ ] data_snippets.cc 
- [ ] instance_admin_async_snippets.cc: in #2610.
- [ ] table_admin_async_snippets.cc 
- [ ] table_admin_snippets.cc
