### ISSUE TITLE
Cleanup vcpkg patch.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#2640]
The folks at vcpkg have to apply this patch to compile google-cloud-cpp:

https://github.com/microsoft/vcpkg/blob/master/ports/google-cloud-cpp/cmake-libcurl-find-config.patch

That seems like a change we should upstream.

**Comment by remyabel** [comment]
Note that the above patch is rebased against 0.8.0. @past-due who implemented the above patch is also the same one who reported the [`CURL::libcurl`](https://github.com/googleapis/google-cloud-cpp/pull/2407) issue. Maybe they'll be the best person to implement this?

**Comment by past-due** [comment]
To add a brief explanation for this patch:

- vcpkg needs google-cloud-cpp to attempt finding CURL using CMake's [`find_package`](https://cmake.org/cmake/help/latest/command/find_package.html) "CONFIG" mode first, as CONFIG will pull in the appropriate dependencies _no matter how CURL is built_ (ex. with a different SSL/TLS backend)
- CMake's [`find_package`](https://cmake.org/cmake/help/latest/command/find_package.html) uses "MODULE" mode _before_ "CONFIG" mode. Hence, to force CONFIG mode first (but fallback to the existing MODULE mode handling, which may be desired / required in other situations) two calls to `find_package` are required
