### ISSUE TITLE
Cmake project doesn't propagate setup for protobuf or gRPC

### ISSUE THREAD

**Issue by mbrucher** [googleapis/google-cloud-cpp#2673]
I'm currently trying to build the latest 0.9.x version of the branch with a custom protobuf and gRPC (for compatibility reasons, we already use specific versions and cannot upgrade them right now).

### Does this issue affect the `google-cloud-cpp` project?

Yes, this is a problem with building the project.

### What version of `google-cloud-cpp` are you using?

64bf0e32fbd234a709c3aa910878723da9378f2a

### What compiler and version are you using?

```
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/opt/rh/devtoolset-3/root/usr/libexec/gcc/x86_64-redhat-linux/4.9.2/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/opt/rh/devtoolset-3/root/usr --mandir=/opt/rh/devtoolset-3/root/usr/share/man --infodir=/opt/rh/devtoolset-3/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --enable-languages=c,c++,fortran,lto --enable-plugin --with-linker-hash-style=gnu --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.9.2-20150212/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.9.2-20150212/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.9.2 20150212 (Red Hat 4.9.2-6) (GCC)

```
### What operating system and version are you using?

CentOS Linux release 7.5

### What were you trying to do?

When building the project with protobuf and gRPC set to package, the built google-apis doesn't get the protobug or gRPC that were (correctly) detected in the parent CMakeCache.txt.

I set these up by calling:

     export CMAKE_PREFIX_PATH=/path/to/protobuf/:/path/to/grpc/
     cmake -DCMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH} -DGOOGLE_CLOUD_CPP_GRPC_PROVIDER=package -DGOOGLE_CLOUD_CPP_PROTOBUF_PROVIDER=package

The Google-API CMakeCache.txt file doesn't have protobuf or gRPC set.

### What did you expect to see?

I expect the build to pass.

### What did you see instead?

The step "Performing configure step for 'googleapis_project'" fails, the error log it refers to is:

```
CMake Error: Internal CMake error, TryCompile generation of cmake failed
CMake Error at /opt/rh/devtoolset-3/root/usr/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find gRPC (missing: _gRPC_grpc_LIBRARY _gRPC_INCLUDE_DIR)
Call Stack (most recent call first):
  /opt/rh/devtoolset-3/root/usr/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  FindgRPC.cmake:338 (find_package_handle_standard_args)
  CMakeLists.txt:35 (find_package)

```
(from external/googleapis/src/googleapis_project-stamp/googleapis_project-configure-Release.cmake)

### Additional comments

Manually setting up the variables for Google-API allowed the rest of the project to build successfully.

**Comment by coryan** [comment]
Thanks for the bug report. Looks like we need to pass CMAKE_PREFIX_PATH explicitly to the external projects.

**Comment by mbrucher** [comment]
Probably the would be enough indeed!

**Comment by mbrucher** [comment]
Yep, seems to be OK, I just have to have protobuf 3.7, anything lower will not work.
Thanks @coryan !

**Comment by xprotobeast2** [comment]
I am having a similar issue using v1.19.0. I have the protobuf 3.6.1. Why exactly doesn't this fix work with this version?

**Comment by mbrucher** [comment]
You need protobuf 3.7. That's the problem. The fix only fixes protobuf detection, it doesn't fix the fact that the requirement is protobuf 3.7 because of the required language support.

**Comment by xprotobeast2** [comment]
Understood thank you!
