### ISSUE TITLE
Storage object sample cannot process an object

### ISSUE THREAD

**Issue by mbrucher** [googleapis/google-cloud-cpp#2674]
After building https://github.com/googleapis/google-cloud-cpp/blob/master/google/cloud/storage/examples/storage_object_samples.cc as an executable against 0.9.x, I used it to ensure the project was working as expected.

### Does this issue affect the `google-cloud-cpp` project?

I think it does (I'm happy to be proven wrong).

### What component of `google-cloud-cpp` is this related to?

- Cloud Storage (under development).

### What version of `google-cloud-cpp` are you using?

64bf0e32fbd234a709c3aa910878723da9378f2a

### What compiler and version are you using?

```
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/opt/rh/devtoolset-3/root/usr/libexec/gcc/x86_64-redhat-linux/4.9.2/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/opt/rh/devtoolset-3/root/usr --mandir=/opt/rh/devtoolset-3/root/usr/share/man --infodir=/opt/rh/devtoolset-3/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --enable-languages=c,c++,fortran,lto --enable-plugin --with-linker-hash-style=gnu --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.9.2-20150212/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.9.2-20150212/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.9.2 20150212 (Red Hat 4.9.2-6) (GCC)

```
### What operating system and version are you using?

CentOS Linux release 7.5

### What were you trying to do?

I was trying to list objects in a bucket, this worked fine. I also checked that I needed the right credentials to do so (without the credentials, I had an error indicating wrong credentials, as expected).
I then tried to download a file through this example and then use read-object on the same file. This failed.

### What did you expect to see?

I expected to see the result of the operation, either a downloaded file or the number of lines of this file.

### What did you see instead?

I got a curl error for the download:

    Standard C++ exception raised: Retry policy exhausted in ReadObject: PerformWork() - CURL error [6]=Couldn't resolve host name, object_name=xxxx,  bucket_name=xxxx [UNAVAILABLE]

For the read-object, I got: `The object has 0 lines`

Using gsutil on the command line did work and was able to access the file.

### Anything else you would like us to know?

I have credentials exported

**Comment by coryan** [comment]
Thanks for filing a detailed bug report.

I am having trouble reproducing this one. Maybe you can tell how is my setup materially different from yours?  Am I reading your reports correctly: did you compile + install the library and *then* compiled the example? That should work, just trying to make sure I follow the same steps you took.

```console
$ cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core) 
$ cmake -H. -B/o
[snip snip]
$ cmake --build /o --target storage_object_samples -- -j $(nproc)
$ export GOOGLE_APPLICATION_CREDENTIALS=/tmp/creds.json 
$ export MY_BUCKET_NAME=[censored
$ /o/google/cloud/storage/examples/storage_object_samples read-object ${MY_BUCKET_NAME} lorem.txt
The object has 6 lines
$ /o/google/cloud/storage/examples/storage_object_samples download-file ${MY_BUCKET_NAME} lorem.txt foo.txt
Downloaded lorem.txt to foo.txt
$ cat foo.txt
Lorem ipsum dolor sit amet, consectetur adipiscing
elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea
commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit
esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat
non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

$ g++ --version
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ ldd /o/google/cloud/storage/examples/storage_object_samples 
        linux-vdso.so.1 =>  (0x00007ffde83e9000)
        libcares.so.2 => /o/external/lib/libcares.so.2 (0x00007f1428bc8000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f14289ac000)
        libssl.so.10 => /lib64/libssl.so.10 (0x00007f142873a000)
        libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007f14282d8000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f1427fd1000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f1427ccf000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f1427ab9000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f14276ec000)
        libnsl.so.1 => /lib64/libnsl.so.1 (0x00007f14274d2000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f14272ca000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f1428ddf000)
        libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f142707d000)
        libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f1426d94000)
        libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f1426b90000)
        libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f142695d000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f1426759000)
        libz.so.1 => /o/external/lib/libz.so.1 (0x00007f142653b000)
        libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f142632b000)
        libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f1426127000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f1425f0e000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f1425ce7000)
        libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f1425a85000)
```

**Comment by mbrucher** [comment]
Indeed, I fear it's either an issue with my credentials (I'll check again today with our liaison), or it something else that I can't understand.

Here we go for ldd:

        linux-vdso.so.1 =>  (0x00007ffd9a5f6000)
        libcurl.so.4 => /lib64/libcurl.so.4 (0x00007f034c0e7000)
        libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007f034bc86000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f034b97f000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f034b67d000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f034b467000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f034b09a000)
        libidn.so.11 => /lib64/libidn.so.11 (0x00007f034ae67000)
        libssh2.so.1 => /lib64/libssh2.so.1 (0x00007f034ac3d000)
        libssl3.so => /lib64/libssl3.so (0x00007f034a9eb000)
        libsmime3.so => /lib64/libsmime3.so (0x00007f034a7c4000)
        libnss3.so => /lib64/libnss3.so (0x00007f034a497000)
        libnssutil3.so => /lib64/libnssutil3.so (0x00007f034a268000)
        libplds4.so => /lib64/libplds4.so (0x00007f034a064000)
        libplc4.so => /lib64/libplc4.so (0x00007f0349e5f000)
        libnspr4.so => /lib64/libnspr4.so (0x00007f0349c21000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f0349a05000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f0349801000)
        libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f03495b4000)
        libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f03492cc000)
        libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f0349099000)
        libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f0348e95000)
        liblber-2.4.so.2 => /lib64/liblber-2.4.so.2 (0x00007f0348c86000)
        libldap-2.4.so.2 => /lib64/libldap-2.4.so.2 (0x00007f0348a31000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f034881b000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f034c350000)
        libssl.so.10 => /lib64/libssl.so.10 (0x00007f03485a9000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f03483a1000)
        libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f0348193000)
        libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f0347f8f000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f0347d76000)
        libsasl2.so.3 => /lib64/libsasl2.so.3 (0x00007f0347b59000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f0347932000)
        libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007f03476fb000)
        libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f0347499000)
        libfreebl3.so => /lib64/libfreebl3.so (0x00007f0347296000)

Is there a debug level I can activate to check what is sent to curl for instance?

**Comment by coryan** [comment]
You can enable logging by setting some environment variables:

```console
$ export CLOUD_STORAGE_ENABLE_CLOG=yes
$ export CLOUD_STORAGE_ENABLE_TRACING=http,raw-client
```

Be prepared because it is a lot of log output.

**Comment by mbrucher** [comment]
Thanks! I don't mind digging in logs, hopefully I'll find my issue.

**Comment by mbrucher** [comment]
Got an error very quickly, the name is not resolved on a box on the cloud (one of ours), but it is resolved outside the cloud. The reason for the failure, after checking internally, is that we need to refresh these endpoints from time to time.
Thanks a lot for the help and support!
