### ISSUE TITLE
[Flake]: async_list_app_profile_test crash on Windows.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#2683]
This seems like a bug.  My guess is that running the test a few hundred times would be able to reproduce the issue.

https://source.cloud.google.com/results/invocations/0f3e6ec6-001c-4523-bb73-3ae19b8924b1/targets/cloud-cpp%2Fgithub%2Fwindows%2Fpresubmit/log

```
 23/153 Test  #23: async_list_app_profiles_test ..............................***Exception: SegFault  2.44 sec
[==========] Running 3 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 3 tests from AsyncListAppProfilesTest
[ RUN      ] AsyncListAppProfilesTest.Simple
[       OK ] AsyncListAppProfilesTest.Simple (365 ms)
[ RUN      ] AsyncListAppProfilesTest.MultipleProfiles
[       OK ] AsyncListAppProfilesTest.MultipleProfiles (18 ms)
[ RUN      ] AsyncListAppProfilesTest.FailuresAreRetried
[       OK ] AsyncListAppProfilesTest.FailuresAreRetried (25 ms)
[----------] 3 tests from AsyncListAppProfilesTest (408 ms total)
[----------] Global test environment tear-down
[==========] 3 tests from 1 test suite ran. (409 ms total)
[  PASSED  ] 3 tests.
```

**Comment by coryan** [comment]
FWIW, I just ran 1000 times with valgrind and had no problems. It seems platform specific, if anything.

**Comment by devbww** [comment]
It looks like we just crossed the "resolved within 180 days" threshold on a P2.  @coryan , do we have any indication that `async_list_app_profiles_test` is still problematic?  The last failure of the windows/continuous build I see is 142 days ago.

**Comment by coryan** [comment]
I think we should close this. It does not seem actionable in any case.
