### ISSUE TITLE
Compile failure on MacOSX

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/google-cloud-cpp#2697]
### What component of `google-cloud-cpp` is this related to?

Remove the ones that do not apply.

- Cloud Storage.

### What version of `google-cloud-cpp` are you using?

b7af0a917f84cfd5401869b40864699648021a30

### What compiler and version are you using?

$ c++ -v
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
### What operating system and version are you using?

MacOSX 10.14.5

### What were you trying to do?

Compile fails with the following error

```
/Users/tmatsuo/work/google-cloud-cpp/google/cloud/storage/benchmarks/benchmark_utils.cc:207:19: error: use of undeclared identifier 'RUSAGE_THREAD'
  (void)getrusage(RUSAGE_THREAD, &start_usage_);
                  ^
/Users/tmatsuo/work/google-cloud-cpp/google/cloud/storage/benchmarks/benchmark_utils.cc:222:19: error: use of undeclared identifier 'RUSAGE_THREAD'
  (void)getrusage(RUSAGE_THREAD, &now);
                  ^
2 errors generated.
```

### What did you expect to see?

Compile succeeds on MacOSX. Actually it successfully compiles when passing `-DGOOGLE_CLOUD_CPP_HAS_GETRUSAGE=0`, but it is nicer if it compiles without it.

`RUSAGE_THREAD` seems like linux only flag.

**Comment by coryan** [comment]
Doh!

**Comment by coryan** [comment]
In case anybody is curious, the CI builds use Bazel where we do not even try to figure out if getrusage is present.
