### ISSUE TITLE
Support mocking storage::Client.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#2710]
We got this feature request from at least two users, recording it here.

Mocking most functions in this class is not hard:

https://github.com/googleapis/google-cloud-cpp/blob/bcefc9f6322860b546ee5727cb63cdb191592a7c/google/cloud/storage/testing/mock_client.h#L27

The hard thing is to mock `Client::ReadObject()` and `Client::WriteObject()`.

- [x] Mock typical unary operations.
- [x] Mock `ReadObject` for "a read that works".
- [x] Mock `WriteObject` for "a write that works".
- [x] Mock `ReadObject` for a failure.
- [x] Mock `WriteObject` for a failure.

**Comment by manish-qlogic** [comment]
example of mocking [`writestreambuf `](https://github.com/googleapis/google-cloud-cpp/blob/0347fb585e11da1d4e36c5dad2ad157064ba5db2/google/cloud/storage/client_write_object_test.cc#L60)

**Comment by coryan** [comment]
Yes, that is the one. For ObjectReadStreambuf you probably have to go one level deeper and mock the `internal::ObjectReadSource` class. 

In both cases it would be nice to have an example that uses these mocks to read (or write) some data pre-defined by the user.

**Comment by manish-qlogic** [comment]
we will keep this task open as `storage_client_mock_samples.cc` need examples on failed scenarios.

https://github.com/googleapis/google-cloud-cpp/blob/7f13737c74aa566dc992a2b87cd4d4443703ad64/google/cloud/storage/examples/storage_client_mock_samples.cc#L58

**Comment by coryan** [comment]
I think this was fixed in #2924
