### ISSUE TITLE
Following Bazel instructions in INSTALL.md doesn't work.

### ISSUE THREAD

**Issue by bzztbomb** [googleapis/google-cloud-cpp#2717]
### Does this issue affect the `google-cloud-cpp` project?

Yes.

### What version of `google-cloud-cpp` are you using?

0.7.0 (same result with 0.9.0)

### What compiler and version are you using?

Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

### What operating system and version are you using?

OSX 10.13

### What were you trying to do?

Following the instructions under INSTALL.md for bazel projects.

### What did you expect to see?

Able to link google_api_library against my project.

### What did you see instead?

```
➜  gapi_test bazel build //:storage_install_test
ERROR: error loading package '': Every .bzl file must have a corresponding package, but '@com_github_googleapis_google_cloud_cpp//bazel:google_cloud_cpp_deps.bzl' does not have one. Please create a BUILD file in the same or any parent directory. Note that this BUILD file does not need to do anything except exist.
```

### Anything else you would like us to know?

I've attached my WORKSPACE and BUILD file.  I feel like I'm just missing a step perhaps, but I haven't been able to figure it out.

[BUILD.txt](https://github.com/googleapis/google-cloud-cpp/files/3242780/BUILD.txt)
[WORKSPACE.txt](https://github.com/googleapis/google-cloud-cpp/files/3242781/WORKSPACE.txt)

**Comment by coryan** [comment]
Can you share what version of Bazel are you using?

Thinking out loud:  we test using google-cloud-cpp as a dependency of another Bazel project in at least one of the CI builds (here is an [example][ci-link]), but for Linux, not for macOS. So it might be (a) our instructions are the test are out of sync (very possible), (b) there is a platform-specific thing to our Bazel files (doubt it, since we do test regular Bazel builds on macOS), (c) maybe there is a version-specific thing to our Bazel files (likely).

[ci-link]: https://source.cloud.google.com/results/invocations/a9590976-7db2-4273-87d7-f7d4caca62a0/targets/cloud-cpp%2Fgithub%2Fbazel-dependency%2Flinux%2Fcontinuous/log

https://github.com/googleapis/google-cloud-cpp/blob/4922eaf322ec1f8292b8f6656434ec548949e821/ci/kokoro/bazel-dependency/linux/build.sh#L34-L41

**Comment by coryan** [comment]
Or our test may be not testing what I thought...

**Comment by bzztbomb** [comment]
Thanks for replying so quickly!

I've tested with with bazel 0.24.0 and 0.26.0.  I'll look at the CI example and see if I can find anything helpful in there.

**Comment by coryan** [comment]
The instructions are wrong, we are missing the `strip_prefix`. This WORKSPACE file is working for me:

```py
workspace(name="com_github_googleapis_google_cloud_cpp_test_install")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive", "http_file")

http_archive(
    name = "com_github_googleapis_google_cloud_cpp",
    url = "http://github.com/googleapis/google-cloud-cpp/archive/v0.9.0.tar.gz",
    strip_prefix = "google-cloud-cpp-0.9.0",
    sha256 = "a072103546cfa041ad8bfc599fe5a20c58e005a1a0ee18e94b2554dc3d485604",
)

load("@com_github_googleapis_google_cloud_cpp//bazel:google_cloud_cpp_deps.bzl", "google_cloud_cpp_deps")
google_cloud_cpp_deps()
# Have to manually call the corresponding function for gRPC:
#   https://github.com/bazelbuild/bazel/issues/1550
load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")
grpc_deps()
```

(It is 1/2 through the build or so, I expect errors would have popped up sooner).

**Comment by coryan** [comment]
[BUILD.txt](https://github.com/googleapis/google-cloud-cpp/files/3242877/BUILD.txt)
[WORKSPACE.txt](https://github.com/googleapis/google-cloud-cpp/files/3242878/WORKSPACE.txt)

**Comment by coryan** [comment]
Also, if you are using Bazel-0.24.0 or higher: the protobuf version referenced from v0.7.0 was too old for that version of Bazel, the WORKSPACE file included with protobuf is not valid. I recommend you use v0.9.0 if you are using a recent Bazel.

**Comment by bzztbomb** [comment]
That worked for me!  Thank you very much!  I can create a PR with an updated INSTALL.md if that's helpful to you.

**Comment by coryan** [comment]
That would be fantastic, thank you.  Check the CONTRIBUTING.md file in case your employer has trouble with our CLA.

**Comment by bzztbomb** [comment]
Done! 

https://github.com/googleapis/google-cloud-cpp/pull/2718 

Again, thank you very much for such a fast response!
