### ISSUE TITLE
Support IAM conditions in Cloud Bigtable.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#2732]
Once we merge #2722 (or something similar) we will get the new IAM protos:

At that time we should change the IAM classes as outlined in #1833. This is the tracking bug for Cloud Bigtable of that work. We need to:

- [ ] Change `bigtable::InstanceAdmin::GetIamPolicy()` and `bigtable::InstanceAdmin::SetIamPolicy()` to return an error if the protos received from the wire are not representable using a `google::cloud::IamPolicy`.

- [ ] Create a new class in `google::cloud::bigtable` (for now) to represent `google.iam.v1.Binding` protos, this class should be a faithful representation of the proto, including the new fields.

- [ ] Create a new class in `google::cloud::bigtable` (for now) to represent `google.iam.v1.Policy` protos. This class should be a faithful representation of the proto, no attempts to reindex the data in any way. Helper functions to add, remove, and change bindings are acceptable, but there should be no "index by role" or "index by role, condition, etc."

- [ ] Create new functions in `google::cloud::bigtable::InstanceAdmin` to return the new classes represented above. Naming is important:
  * `InstanceAdmin::SetIamPolicy` can simply be an overload with the new types.
  * `InstanceAdmin::SetIamPolicyUninterpreted` is not a great name, but start exploring from there.

The first step in this bug is to create child issues for each step. We should expect the usual unit, integration, and examples for these new functions.

**Comment by remyabel** [comment]
FYI, this TODO still exists in the code:

https://github.com/googleapis/google-cloud-cpp/blob/e3f5ae369372510838a7dbeb4bf18742b8952911/google/cloud/storage/internal/bucket_requests.cc#L260
