### ISSUE TITLE
Missing field initializers for BucketRetentionPolicy in bucket_metadata.h

### ISSUE THREAD

**Issue by xprotobeast2** [googleapis/google-cloud-cpp#2738]
Answering these questions before submitting your bug report will help us give
you a quicker answer.  Thank you!

If one or more of these questions are not applicable, feel free to remove them.

### Does this issue affect the `google-cloud-cpp` project?

Yes

### What component of `google-cloud-cpp` is this related to?

Remove the ones that do not apply.

- Cloud Storage.

### What version of `google-cloud-cpp` are you using?

v0.10.0

### What compiler and version are you using?

gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.11)

### What operating system and version are you using?

Ubuntu 16.04.6 LTS (Xenial Xerus)

### What were you trying to do?

Use the client api like so 

`#include <google/cloud/storage/client.h>`

### What did you expect to see?

Correct build

### What did you see instead?

```
In file included from /workspace/builddir/google-cloud-cpp/install/include/google/cloud/storage/internal/raw_client.h:20:0,
                 from /workspace/builddir/google-cloud-cpp/install/include/google/cloud/storage/internal/logging_client.h:18,
                 from /workspace/builddir/google-cloud-cpp/install/include/google/cloud/storage/client.h:23,
                 from /workspace/src/core/filesystem.cc:31:
/workspace/builddir/google-cloud-cpp/install/include/google/cloud/storage/bucket_metadata.h: In member function 'google::cloud::storage::v1::BucketMetadata& google::cloud::storage::v1::BucketMetadata::set_retention_policy(std::chrono::seconds)':
/workspace/builddir/google-cloud-cpp/install/include/google/cloud/storage/bucket_metadata.h:796:71: error: missing initializer for member 'google::cloud::storage::v1::BucketRetentionPolicy::effective_time' [-Werror=missing-field-initializers]
     return set_retention_policy(BucketRetentionPolicy{retention_period});
                                                                       ^
/workspace/builddir/google-cloud-cpp/install/include/google/cloud/storage/bucket_metadata.h:796:71: error: missing initializer for member 'google::cloud::storage::v1::BucketRetentionPolicy::is_locked' [-Werror=missing-field-initializers]
/workspace/builddir/google-cloud-cpp/install/include/google/cloud/storage/bucket_metadata.h: In member function 'google::cloud::storage::v1::BucketMetadataPatchBuilder& google::cloud::storage::v1::BucketMetadataPatchBuilder::SetRetentionPolicy(std::chrono::seconds)':
/workspace/builddir/google-cloud-cpp/install/include/google/cloud/storage/bucket_metadata.h:958:69: error: missing initializer for member 'google::cloud::storage::v1::BucketRetentionPolicy::effective_time' [-Werror=missing-field-initializers]
     return SetRetentionPolicy(BucketRetentionPolicy{retention_period});
                                                                     ^
/workspace/builddir/google-cloud-cpp/install/include/google/cloud/storage/bucket_metadata.h:958:69: error: missing initializer for member 'google::cloud::storage::v1::BucketRetentionPolicy::is_locked' [-Werror=missing-field-initializers]
cc1plus: all warnings being treated as errors
```

### Anything else you would like us to know?
```
struct BucketRetentionPolicy {
  std::chrono::seconds retention_period;
  std::chrono::system_clock::time_point effective_time;
  bool is_locked;
};
```
There are 3 fields in this struct. My project does compile with -Werror, but I am wondering if there is something I am missing, or if this warning is always thrown.

**Comment by coryan** [comment]
> There are 3 fields in this struct. My project does compile with -Werror, but I am wondering if there is something I am missing, or if this warning is always thrown.

We compile with "-Werror -Wall" in our CI builds, so I need to research more to understand this. To answer your question: no this warning is not expected. I think it is harmless, but we should fix it.

**Comment by coryan** [comment]
Ah, `-Wmissing-field-initializers` is not part of the `-Wall` list, it is part of `-Wextra`:

https://gcc.gnu.org/onlinedocs/gcc-5.4.0/gcc/Warning-Options.html

That explains why you see it (I am guessing you turned on `-Wextra` or this warning explicitly) and we do not.

**Comment by coryan** [comment]
As you probably noticed there is an open PR to fix the warnings that you are getting. Thank you for the detailed report.  I want to discuss this with my colleagues because it is not obvious that turning on these warnings is good in all cases (the workarounds make the code harder to maintain and read in some cases).  I think we should turn them on, but I do want to hear their opinions.
