### ISSUE TITLE
Document BUILD_NAME in CONTRIBUTING.md

### ISSUE THREAD

**Issue by remyabel** [googleapis/google-cloud-cpp#2769]
`BUILD_NAME` can be used as a convenient grouping for flags. I think we should at least allude to it in the docs. Furthermore, it appears that in the line:

https://github.com/googleapis/google-cloud-cpp/blob/a186208b79d900b4ec71c6f9df3acf7638f01dc6/ci/kokoro/docker/build.sh#L159

`${suffix}` isn't defined. This should either be removed or exported in `ci/travis/linux-config.sh` if it's intended to be there.

**Comment by coryan** [comment]
For what is worth: I am trying to move the last two Travis builds to Kokoro, so all the builds will be using `BUILD_NAME=... ./ci/kokoro/docker/build.sh`.  I am trying all of this in the googleapis/google-cloud-cloud-spanner project first though.

**Comment by remyabel** [comment]
What do you think about making NCPU configurable, like this:

```diff
diff --git a/ci/kokoro/docker/build.sh b/ci/kokoro/docker/build.sh
index 0490c521d..9f5cca2dd 100755
--- a/ci/kokoro/docker/build.sh
+++ b/ci/kokoro/docker/build.sh
@@ -115,8 +115,10 @@ source "${PROJECT_ROOT}/ci/travis/linux-config.sh"
 source "${PROJECT_ROOT}/ci/define-dump-log.sh"
 
 echo "================================================================"
-NCPU=$(nproc)
-export NCPU
+if [[ -z "${NCPU+x}" ]]; then
+    NCPU=$(nproc)
+    export NCPU
+fi
 cd "${PROJECT_ROOT}"
 echo "Building with ${NCPU} cores $(date) on ${PWD}."
 
@@ -173,9 +175,7 @@ docker_flags=(
     "--env" "CXX=${CXX}"
     "--env" "CC=${CC}"
 
-    # The number of CPUs, probably should be removed, the scripts can detect
-    # this themselves in Kokoro (it was a problem on Travis).
-    "--env" "NCPU=${NCPU:-4}"
+    "--env" "${NCPU}"
 
     # Disable ccache(1) for Kokoro build builds we do not cache data between
     # builds.
```

**Comment by coryan** [comment]
> What do you think about making NCPU configurable, like this:

What is the use-case for NCPU? That is, what do we lose if we remove it altogether?

**Comment by remyabel** [comment]
Assuming that I run `BUILD_NAME=... ./ci/kokoro/docker/build.sh` on my workstation, I don't like using all of the cores. But in Kokoro you want to use all of the cores, obviously. Elsewhere we mostly have NCPU configurable, I don't see why not here.

**Comment by coryan** [comment]
> on my workstation, I don't like using all of the cores.

Ack, that makes total sense.  Yup that seems like a valuable thing to have.

**Comment by coryan** [comment]
@remyabel glad to see you back contributing btw!

**Comment by remyabel** [comment]
> @remyabel glad to see you back contributing btw!

Thanks, just trying to keep busy.

**Comment by coryan** [comment]
Since we no longer using `BUILD_NAME` I think this bug is now obsolete.  The documentation was updated to describe how to do things now, i.e., provide the build name as the first argument to the `build.sh` script.
