### ISSUE TITLE
Client::UploadFile only uploads part of the file

### ISSUE THREAD

**Issue by branyman-lp** [googleapis/google-cloud-cpp#2770]
### What component of `google-cloud-cpp` is this related to?

- Cloud Storage.

### What version of `google-cloud-cpp` are you using?

ec468fbc06cca36802323c50d32180a149ec467a
0.8.0

### What compiler and version are you using?

Visual Studio 2015

### What operating system and version are you using?

Windows 10

### What were you trying to do?

Upload several files to a bucket. File types TXT, JPG, PNG, EXR, etc.

### What did you expect to see?

All files uploaded correctly.

### What did you see instead?

The TXT files are uploaded correctly, but the binary files are partially uploaded. If I download a PNG uploaded to a bucket (partially uploaded), and compare it with the original file in a hexadecimal editor, I see that in all cases the file is only uploaded until the first "1A" hexadecimal value in the file. It  happens that 1A is used as a substitute/EOF/CTRL+Z character in different circumstances.

Is this a bug? Am I missing something in order to tell the UploadFile method the proper options?

I use that method just like the example in the documentation does:

StatusOr<gcs::ObjectMetadata> object_metadata = client.UploadFile(
        file_name, bucket_name, object_name, gcs::IfGenerationMatch(0));

Should I add more options like gcs::ContentEncoding or gcs::ContentType?

The uploaded files are set "application/octet-stream" by default. If I set the content type to "image/png" or "application/png", I have the same problem.

StatusOr<gcs::ObjectMetadata> object_metadata = client.UploadFile(
        file_name, bucket_name, object_name, gcs::IfGenerationMatch(0),
                    gcs::ContentType( "image/png" ));

**Comment by coryan** [comment]
Looks like a bug to me, we should be opening those files (I think all files) with the `std::ios::binary` flag.
