### ISSUE TITLE
Do not include nlohmann/json.hpp from any public header.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#2772]
We do not want to pollute the namespace for our users with macros or global functions in the nljson.h.

**Comment by remyabel** [comment]
The straight-forward solution is to move the member function definitions of `AuthorizedUserCredentials` into its `.cc` then explicitly instantiate:

```c++
// in authorized_user_credentials.cc
template class AuthorizedUserCredentials<storage::internal::CurlRequestBuilder>;
// in authorized_user_credentials_test.cc
template class AuthorizedUserCredentials<testing::MockHttpRequestBuilder>;
```

The problem is now linking errors exist where we're using `make_unique`:

```c++
google::cloud::internal::make_unique<AuthorizedUserCredentials<>>
```

No idea how to fix this.

Putting `extern template class AuthorizedUserCredentials` in `authorized_user_credentials.h` might work (?) but is undesirable since we'd be including a testing header.

**Comment by coryan** [comment]
Is it possible to refactor the code that uses nl::json to standalone (non-template) functions?

Consider this code:

https://github.com/googleapis/google-cloud-cpp/blob/f6c3c0871ceb7c9df93be6c760c245a7695df535/google/cloud/storage/oauth2/authorized_user_credentials.h#L92-L123

Lines 100 to 122 do not really depend on the template parameters, so we could write a function:

```C++
namespace google::cloud::storage::internal {
StatusOr<RefreshingCredentialsWrapper::TemporaryToken> ParseRefreshResponse(std::string const& payload) {
  // ... basically the code from above
}
}
```

and change the code to:

```C++
  StatusOr<RefreshingCredentialsWrapper::TemporaryToken> Refresh() {
    auto response = request_.MakeRequest(payload_);
    if (!response) {
      return std::move(response).status();
    }
    if (response->status_code >= 300) {
      return AsStatus(*response);
    }
    return ParseRefreshResponse(response->payload);
  }
```

**Comment by remyabel** [comment]
That's a good solution I had not considered, thanks.

**Comment by remyabel** [comment]
Factoring out `AssertionComponentsFromInfo` and `ServiceAccountCredentials::Refresh` is a little trickier since they both depend on `ClockType`. Should the factored out functions be passed `std::chrono::system_clock::now()` or something else?

**Comment by coryan** [comment]
> Factoring out `AssertionComponentsFromInfo` and `ServiceAccountCredentials::Refresh` is a little trickier since they both depend on `ClockType`. Should the factored out functions be passed `ClockType::now()` or something else?

I think it is reasonable to require that `ClockType::now()` returns `std::chrono::system_clock::time_point` and pass its value to the refactored function.

**Comment by remyabel** [comment]
Per https://github.com/googleapis/google-cloud-cpp/pull/2959#issuecomment-520153489 this should be re-opened.

**Comment by remyabel** [comment]
Disregard last message. Trivial fix.

**Comment by remyabel** [comment]
Disregard disregard last message, not a trivial fix. This can be re-opened.

For future reference, here are a list of headers that still include `nljson.h`:

```
google/cloud/storage/iam_policy.h
google/cloud/storage/internal/access_control_common.h
google/cloud/storage/internal/hmac_key_requests.h
google/cloud/storage/internal/service_account_requests.h
google/cloud/storage/internal/metadata_parser.h
google/cloud/storage/internal/common_metadata.h
google/cloud/storage/internal/patch_builder.h
google/cloud/storage/internal/notification_requests.h
google/cloud/storage/testing/mock_http_request.h
```

**Comment by remyabel** [comment]
I apologize for the premature PR. Let me layout some of the changes to be done/challenges so far:

- Add nlohmann/json to storage_include_test
- Split out Parser classes, i.e from `access_control_common`, `common_metadata`, `notification_requests`, etc. I've added the logic to their own files, i.e `access_control_common_parser` which is the simplest approach but is also tedious and results in a lot of files that don't really serve any other purpose
- `patch_builder.h` is tricky because it contains a `nlohmann::json` object as a member

**Comment by remyabel** [comment]
For `PatchBuilder`, the obvious approach is to use the Pimpl idiom. However, the issue is that `AddArrayField` is a templated member function. Per https://stackoverflow.com/questions/44078373/pimpl-idiom-with-template-member-function one approach is to create an overload for each type we support (I'm guessing `std:string`, `bool` and all of the integral types). Although there may be a better approach. Thoughts?

**Comment by coryan** [comment]
Looking at the code: `AddArrayField()` is in `internal::PatchBuilder`, so no application-level code is using that function.  And the only use in our code is in tests.  In other words, we can remove this function and avoid the problem altogether.

Similar analysis for `AddOptionalField()`.

**Comment by remyabel** [comment]
`AddArrayField` is used in `bucket_metadata.cc` and `object_metadata.cc`. I'm not entirely sure how to refactor it but my current approach is a wrapper like this:

```
struct PatchBuilderExtension {
 public:
  // NOLINTNEXTLINE
  explicit PatchBuilderExtension(PatchBuilder builder)
      : impl_(std::move(builder)) {}

  internal::PatchBuilder& SetArrayField(char const* field_name, std::vector<nlohmann::json> const& v);
 private:
  internal::PatchBuilder impl_;
};

PatchBuilder& PatchBuilderExtension::SetArrayField(char const* field_name, std::vector<nlohmann::json> const& v) {
    impl_.pimpl_->patch_[field_name] = v;
    return impl_;
}

// ...

impl_ = std::move(internal::PatchBuilderExtension(impl_).SetArrayField("acl", array));
```

Although I do not think this is a great approach.

**Comment by coryan** [comment]
> `AddArrayField` is used in `bucket_metadata.cc` and `object_metadata.cc`. I'm not entirely sure how to refactor it but my current approach is a wrapper like this:

Doh!  I was just searching for **Add**ArrayField, I think you meant `SetArrayField`?

> 
> ```c++
> ....
> PatchBuilder& PatchBuilderExtension::SetArrayField(char const* field_name, std::vector<nlohmann::json> const& v) {
>     impl_.pimpl_->patch_[field_name] = v;
>     return impl_;
> }
> 
> // ...
> 
> impl_ = std::move(internal::PatchBuilderExtension(impl_).SetArrayField("acl", array));
> ```
> 
> Although I do not think this is a great approach.

Maybe all we need to support is `SetArrayField(std::vector<internal::PatchBuilder>)`, it might be a bit slow, but these are very uncommon operations anyway.

You could use dynamic cast to discover the actual type of the `impl_` object, and have additional member functions.

You could also do something like `SetArrayField(std::string const& json_stringified_object)` which is also slow, but for a rarely used API this seems Okay too.

Finally, we could break this into two member functions `ClearArrayField()` and `AppendObjectToArrayField(internal::PatchBuilder)`.

It might be worthwhile to write down the different approaches, consider the pros and cons of each and make a recommendation.
