### ISSUE TITLE
[Flake]: openSUSE zypper hanging

### ISSUE THREAD

**Issue by remyabel** [googleapis/google-cloud-cpp#2780]
See https://source.cloud.google.com/results/invocations/3396796c-2a52-49f4-9bc6-980faee18f72/log and https://source.cloud.google.com/results/invocations/c719ffa0-7b9a-4264-a850-f2155a14b3d2/log.

It appears that very rarely zypper can hang when retrieving packages instead of timing out. Allegedly when this error occurs, the recommendation is to [use a specific mirror](https://mirrors.opensuse.org/). Since this error can occur at the `docker build` stage, maybe it's worth amending the `install-retry` script to manually timeout instead of relying on Kokoro/Travis to time out.

**Comment by remyabel** [comment]
I am re-reading my sleep deprived concern over and over to see if it makes sense. In any case, it appears that [@coryan's WIP PR](https://github.com/googleapis/google-cloud-cpp/pull/2779/files) will make this a non-issue.

**Comment by coryan** [comment]
I think this was fixed in #2781.
