### ISSUE TITLE
Consider ignoring ci/test-install for non-test-install steps

### ISSUE THREAD

**Issue by remyabel** [googleapis/google-cloud-cpp#2811]
When modifying any file within `ci/test-install` and building one of the test-readme Dockerfiles (i.e, `sudo docker build -f ci/test-readme/Dockerfile.ubuntu .`) the cache is invalidated and the build starts all the way over from step 9. We should consider ignoring `ci/test-install` for these lines in particular:

```Dockerfile
WORKDIR /home/build/external
COPY . /home/build/external
RUN cmake -H. -Bcmake-out -DCMAKE_BUILD_TYPE=Debug
RUN cmake --build cmake-out -- -j $(nproc)
RUN (cd cmake-out && ctest --output-on-failure
```

so that building locally is faster.

**Comment by remyabel** [comment]
This may be possible using a [multi-stage build](https://github.com/moby/moby/issues/15771#issuecomment-495408372). It goes without saying that said commands should go inside `## [START IGNORED]` sections.

**Comment by coryan** [comment]
Adding `ci/test-install` to the `.dockerignore` file would make it impossible to use it as a source for `COPY`, right?  And then we would not be able to run the tests in that directory either?

I think the answer is to move any step that depends on the code as late as possible, and I suspect splitting the README from the INSTALL tests would help here.

**Comment by coryan** [comment]
@remyabel it seems to me that the changes in #2850 fixed this, if you agree we can close it, if not, can you let me know what am I missing?

**Comment by remyabel** [comment]
Indeed that is the best we can do until some form of `COPY --exclude` is implemented. Thanks for the PR.
