### ISSUE TITLE
Provided MD5 for Resumable Uploads isn't Verified.

### ISSUE THREAD

**Issue by Jseph** [googleapis/google-cloud-cpp#2832]
### Does this issue affect the `google-cloud-cpp` project?

No.

### What component of `google-cloud-cpp` is this related to?

- Cloud Storage.

### What version of `google-cloud-cpp` are you using?

Please include the output from `git rev-parse HEAD` if you are compiling from
source, or the version number from the applicable `*/version.h` file.

### What compiler and version are you using?

0.8

### What operating system and version are you using?

gLinux

### What were you trying to do?

Have MD5 checked for resumable upload

### What did you expect to see?

If the MD5 doesn't match the upload should fail.

### What did you see instead?

The upload succeeds and and the actual MD5 is returned.

### Anything else you would like us to know?

Pretty sure the issue is [curl_client.cc:221](https://github.com/googleapis/google-cloud-cpp/blob/83423775ddad81075935c775191a84663b95dd78/google/cloud/storage/internal/curl_client.cc#L221).  GCS uses `md5Hash` not `md5` ([source](https://cloud.google.com/storage/docs/hashes-etags)).

**Comment by coryan** [comment]
The code you point to is certainly wrong. But there is probably a bug in a test too.

**Comment by Jseph** [comment]
This looks like a data loss bug to me.  I'd recommend increasing the priority to p1. What do you think?

**Comment by coryan** [comment]
Sure. Though it won't make it to the current release, we already cut the branch.

**Comment by coryan** [comment]
@manish-qlogic any updates on this?
