### ISSUE TITLE
Use [[deprecated]] attributes.

### ISSUE THREAD

**Issue by dopiera** [googleapis/google-cloud-cpp#2857]
These attributes are available since C++14.

We could add a macro or wait until dropping support for C++11.

**Comment by devjgm** [comment]
Now that we have Abseil, we could use `ABSL_DEPRECATED("Use Bar instead")`

https://github.com/abseil/abseil-cpp/blob/fbdff6f3ae0ba977a69f172e85ecaede535e70f6/absl/base/attributes.h#L630-L655

**Comment by devbww** [comment]
> Now that we have Abseil, we could use `ABSL_DEPRECATED("Use Bar instead")`

After writing that, @devjgm followed up with, _"I think it would be good for us to understand the implications of ABSL_DEPRECATED on our customers before using it, because it has the ability to break our customers' builds."_

So, I'm reopening this issue.

**Comment by remyabel** [comment]
There are still instances of `TODO(#2857)` in bigtable/instance_admin.h and storage/client.h, those TODO's need to be updated as well.

**Comment by coryan** [comment]
Thanks, I prepared a PR.  I am also asking a colleagues for ideas to automate this TODO <-> bug linking, maybe a bot that warns us when we are about to leave TODOs stale, or reopens bugs that still have pending TODOs.
