### ISSUE TITLE
Support "uniform bucket level access".

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#2869]
The `storage::BucketIamConfiguration` structure needs to change, eventually we will want to replace the existing `bucket_policy_only` field with `uniform_bucket_level_access`. But we do not want to drop compatibility, so consider this sequence:

- Rename `storage::BucketPolicyOnly` to `storage::UniformBucketLevelAccess`.

- Create a type alias `using storage::BucketPolicyOnly = storage::UniformBucketLevelAccess`.

- Add a new field to `storage::BucketIamConfiguration` called `uniform_bucket_level_access`.

- If the bucket metadata JSON object contains a `uniformBucketLevelAccess` object use that JSON object to populate both fields, and ignore any (now legacy) `bucketPolicyOnly` field.

- If the bucket metadata JSON object **only** contains the (now legacy) `bucketPolicyOnly` field, then use it to populate both fields.

This section is **unclear** discuss with @coryan and @frankyn before implementing it:

- When creating bucket metadata JSON objects for patch, insert, or update, use **only** the `uniform_bucket_level_access` field and only populate the `uniformBucketLevelAccess` field.

**Comment by frankyn** [comment]
Small update:
- When updating BPO or UBLA fields, the client is recommended only to send the UBLA field. Using the UBLA field will help unify the requests made by each field into one request reducing dependence on the BPO field.
-- At the moment both fields being set is required but this is a workaround and will be fixed when the feature GA's.
- BucketPolicyOnly samples should be updated as well to support UBLA field instead.
