### ISSUE TITLE
benchmarks and examples are enabled by a seemngly unrelated tag GOOGLE_CLOUD_CPP_ENABLE_CXX_EXCEPTIONS

### ISSUE THREAD

**Issue by yurivict** [googleapis/google-cloud-cpp#2873]
Here: https://github.com/googleapis/google-cloud-cpp/blob/master/google/cloud/storage/CMakeLists.txt#L416

It's odd that ```GOOGLE_CLOUD_CPP_ENABLE_CXX_EXCEPTIONS``` affects benchmarks and examples. Please either add relevant cmake options, ex. ENABLE_BENCHMARKS and ENABLE_OPTONS, or explain there in comments why ```GOOGLE_CLOUD_CPP_ENABLE_CXX_EXCEPTIONS``` is relevant.

**Comment by remyabel** [comment]
We use [`StatusOr`](https://github.com/googleapis/google-cloud-cpp/blob/master/doc/adr/2019-01-04-error-reporting-with-statusor.md) instead of exceptions for error reporting. The difference is that the benchmarks and examples do use exceptions (generally `std::runtime_error` is used). A PR is welcome unless you want someone else to do it.

**Comment by yurivict** [comment]
> A PR is welcome

It's always nice when a multi-billion dollar corporation asks an individual contributor to the open source project to fix things for them, as if I need ```google-cloud-cpp```.

**Comment by remyabel** [comment]
I apologize for the misunderstanding. I do not work for Google, I am a volunteer contributor. It is common practice (from what I've seen) to ask issue reporters to submit a PR if they so choose, in fact, I've submitted PRs for several issues I've reported myself. It is a courtesy, not a demand, and I am sorry if that came off wrong.

**Comment by yurivict** [comment]
> I apologize for the misunderstanding. I do not work for Google, I am a volunteer contributor. It is common practice (from what I've seen) to ask issue reporters to submit a PR if they so choose, in fact, I've submitted PRs for several issues I've reported myself. It is a courtesy, not a demand, and I am sorry if that came off wrong.

No problem!
I only care enough to submit ports to the FreeBSD ports tree. I couldn't care less for any of the google's projects, as they tend to be low quality, and from my perspective they should fix them themselves. FYI, google cloud is a commercial project, which means that they should have vested interest in fixing things in any related projects like this one.
