### ISSUE TITLE
nlohmann json is available as a package, no need to download it

### ISSUE THREAD

**Issue by yurivict** [googleapis/google-cloud-cpp#2874]
See cmake/DownloadNlohmannJson.cmake

Repology shows that nlohmann-json is available on virtually all distros: https://repology.org/project/nlohmann-json/versions
There is no need to download it.

Downloads aren't allowed in the modern packaging systems due to security concerns, and such downloads only clutter the packaging process.

**Comment by remyabel** [comment]
It's suggested in https://github.com/googleapis/google-cloud-cpp/issues/2802#issuecomment-510881426 that we use the same version of nlohmann_json that the customer has installed. In other words, it's planned that we will use `find_package` to discover it rather than downloading it.

**Comment by amensel** [comment]
Hoping to draw some attention back to this one, especially in relation to #4094. 

GCC 10 has improved improved detection of incomplete types. This revealed a bug in `nlohmann::json`: https://github.com/nlohmann/json/issues/1920

Unfortunately, versions later than 3.4.0 (the version vendored into google-cloud-cpp) are no longer safe to use alongside 3.4.0. The header guards have changed and as has the template for the `basic_json` type. This creates a nasty little fight for which I still haven't found a clean resolution.

It would be great if `nlohmann::json` could be provided as a package like other dependencies in e.g. the Protobuf or gRPC builds.

If not that, it would at least be polite to not expose the touched up and customized version that this library uses in its public includes, despite whatever claims are made in the comments of `nljson.h` about it being "safe".

**Comment by coryan** [comment]
Thanks for letting us know about the additional problems.  I have moved up this issue in our backlog, I do not think we will be able to fix it for the next release (due in less than a week).  I am hoping for the 2020-09 release.

**Comment by amensel** [comment]
Awesome! Thanks for the speedy response.

**Comment by coryan** [comment]
As you may have noticed we now have a PR that will fix this problem. But note that we have not upgraded to a newer version of nlohmann_json with #4747.  We are staying on v3.4.0 to keep the PR manageable.  The good news is that it seems to work, some of our builds use vcpkg and they are are using v3.8.0 of the nlohmann_json library, but I would like to run all builds with that version before declaring success.

**Comment by amensel** [comment]
Ah, I had missed that; I'll pull it into our build in the interim while we wait for the official release.

Thanks!

**Comment by coryan** [comment]
No problem, please let us know if you run into any trouble.
