### ISSUE TITLE
storage::Client::ReadObject() may not retry hard enough.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#2890]
A customer is reporting that `storage::Client::ReadObject()` returns a stream with `.bad()` set and a status of `[UNAVAILABLE]`.  Maybe this sequence of events is taking place, if so, it is unclear that retrying on `Read()` is a good strategy (it would work poorly in the middle of a download), maybe we need to get the error status on `ReadObjectNotWrapped()` to start the retry loop earlier.

The only thing would be this sequence:
Client::ReadObjectImpl calls peek():
https://github.com/googleapis/google-cloud-cpp/blob/7011dd82004d89b1f2c77dfd47b3938b6a42cdbe/google/cloud/storage/client.cc#L62

That calls (after some intermediate code) RetryObjectReadSource::Read(), which then calls Read() on its child source:
https://github.com/googleapis/google-cloud-cpp/blob/7011dd82004d89b1f2c77dfd47b3938b6a42cdbe/google/cloud/storage/internal/retry_object_read_source.cc#L37

if that fails, then it will try to create a new child:
https://github.com/googleapis/google-cloud-cpp/blob/7011dd82004d89b1f2c77dfd47b3938b6a42cdbe/google/cloud/storage/internal/retry_object_read_source.cc#L48

That uses the MakeCall() function:
https://github.com/googleapis/google-cloud-cpp/blob/7011dd82004d89b1f2c77dfd47b3938b6a42cdbe/google/cloud/storage/internal/retry_client.cc#L246

So any error messages there would be familiar ones, assuming it succeeds, then it tries to read from the new child:
https://github.com/googleapis/google-cloud-cpp/blob/7011dd82004d89b1f2c77dfd47b3938b6a42cdbe/google/cloud/storage/internal/retry_object_read_source.cc#L55

but if that fails it gives up.

**Comment by dopiera** [comment]
Actually, I didn't notice that I've already committed the reproducer. It's in `error_injection_integration_test.cc`.

#2995, apart from enabling the test, makes it explicit where one failed retry was enough to fail the whole download.
