### ISSUE TITLE
Create a Linux build with CMake+Ninja.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#2891]
Ninja is popular for CI builds, and for Windows builds.  In some corner cases a CMake file will work with Make, but will fail with Ninja. Mostly this is because Ninja is strict about byproducts of `ExternalProject_Add()` and some other custom rules.

Having a build with CMake+Ninja on Linux will detect these problems, and it would be easier to run and reproduce for most of the developers in the project.

**Comment by remyabel** [comment]
This is just a matter of installing `ninja-build` and using `-GNinja` right? Do we want a separate build or can we just build the super build with Ninja since it utilizes external projects?

**Comment by coryan** [comment]
> This is just a matter of installing `ninja-build` and using `-GNinja` right?

Assuming we have no bugs such as missing `BYPRODUCTS` options in any `add_custom_target()` commands.

> Do we want a separate build or can we just build the super build with Ninja since it utilizes external projects?

Using the super build with Ninja sounds reasonable.
