### ISSUE TITLE
Storage library does not retry on 410 Gone.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#2894]
This is a tracking bug to record the library behavior. It is currently considered correct, but we may learn something that changes our minds.

Sometimes the GCS service returns 410 (Gone) after we try to upload a chunk:

https://cloud.google.com/storage/docs/json_api/v1/status-codes#410_Gone

The library does not retry with a new session in this case because the library cannot retain the full contents of the stream.

We *may* want to do something different for a `FileUpload`, where restarting could be possible if the file is a regular file.

And we *could* do something if the stream is really small and we happen to have all the data in the current buffer.

**Comment by coryan** [comment]
This is working as intended. If our intentions are wrong then we can change them, but closing for now.

**Comment by eneloop2** [comment]
Reopening. What is the recommended way to handle this issue with an `ObjectWriteStream`? I have a pattern where I call `stream.Close()` in some destructor. I then inspect the metadata of the stream by calling `stream.metadata()`. The content of the metadata says that the code is `NOT_FOUND` with mesage `Permanent error UploadChunk: Gone`.

I suppose I need some way to hold a parallel buffer to the object write stream's internal `buf_` which will let me know where to continue writing?
