### ISSUE TITLE
Avoid `COPY . /var/tmp/ci` or move the super build from `ci/super` to `super`

### ISSUE THREAD

**Issue by remyabel** [googleapis/google-cloud-cpp#2905]
Currently anytime changes are made to `ci/super`, a rebuild will be triggered for any Dockerfile that has `COPY . /var/tmp/ci` in it. The simplest solution would be to move the directory.

Otherwise, if we copy the files explicitly (`install-bazel.sh`, etc) we'll have to make sure that nothing breaks due to build context changes.

**Comment by coryan** [comment]
As I mentioned in #2917 we probably need to change the directory hierarchy, as you suggest above. Maybe move from `ci/super/` to simply `super/`?
