### ISSUE TITLE
Rename `check-abi.sh` to `check-api.sh`

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#2907]
That is actually what we use it for, and with the changes in #2901 checking the ABI will no be happening.

**Comment by coryan** [comment]
@devjgm I was going to close this bug, but then noticed that the GCB build has a**b**i in the name.

**Comment by devjgm** [comment]
I used a**b**i because that's what the tools were called.... I thought about this when writing the new script, but I don't know why I landed on the **b**. Thinking back now, I'm back to thinking **p** makes more sense.

**Comment by devjgm** [comment]
I remember now my thinking.

This build all starts with a tool named `abi-dumper`. It outputs the a**b**i of some library into a dump file that we unsurprisingly name with "a**b**i" in the name. Basically we're we're using an a**b**i tool(s) as a way to roughly detect a**p**i changes. All this is to say, that a straight `s/abi/api/g` felt a little misleading. And so calling the build `check-api` may still include some abi references, and so may be slightly confusing.

Overall, I'd be happy to keep the a**b**i naming we have now. Alternatively, renaming to a**p**i is also easy (and indeed, I already did it: https://github.com/googleapis/google-cloud-cpp/compare/master...devjgm:gcb-rename-check-api?expand=1), so if someone prefers that I'm happy to send the PR to change the name.

Preference?

**Comment by coryan** [comment]
I can live with ABI or API for these.  If we decide to go with ABI let's close this bug.

I would note that our *intent* is to check for API compatibility, not ABI.  We use a tool that checks both, but we use the `-src` option:

https://github.com/googleapis/google-cloud-cpp/blob/master/ci/cloudbuild/builds/check-abi.sh#L81

Which means "show source compatibility problems **only**" (emphasis mine):

https://manpages.debian.org/unstable/abi-compliance-checker/abi-compliance-checker.1.en.html

So effectively we are checking something closer to API compat than ABI compat.

:shrug: your call.

**Comment by devjgm** [comment]
ok. Let's rename it. Little reason not to. Sent https://github.com/googleapis/google-cloud-cpp/pull/6422
