### ISSUE TITLE
datastore emulator  errors on createbukcet and read/write object

### ISSUE THREAD

**Issue by svkr521** [googleapis/google-cloud-cpp#2913]
I have set project using 
gcloud config set project svkr

and started datastore eumlator as below. Please note that at client on same machine I have exported as "export  CLOUD_STORAGE_TESTBENCH_ENDPOINT=http://localhost:8856"

[root@kr-r75-qs1 ~]# gcloud beta emulators datastore start  --data-dir=/datastore --store-on-disk --host-port=localhost:8856
WARNING: Reusing existing data in [/datastore].
Executing: /usr/lib64/google-cloud-sdk/platform/cloud-datastore-emulator/cloud_datastore_emulator start --host=localhost --port=8856 --store_on_disk=True --consistency=0.9 --allow_remote_shutdown /datastore
[datastore] Jul 24, 2019 10:16:29 AM com.google.cloud.datastore.emulator.CloudDatastore$FakeDatastoreAction$9 apply
[datastore] INFO: Provided --allow_remote_shutdown to start command which is no longer necessary.
[datastore] Jul 24, 2019 10:16:29 AM com.google.cloud.datastore.emulator.impl.LocalDatastoreFileStub <init>
[datastore] INFO: Local Datastore initialized:
[datastore]     Type: High Replication
[datastore]     Storage: /datastore/WEB-INF/appengine-generated/local_db.bin
[datastore] Jul 24, 2019 10:16:30 AM com.google.cloud.datastore.emulator.impl.LocalDatastoreFileStub load
[datastore] INFO: The backing store, /datastore/WEB-INF/appengine-generated/local_db.bin, does not exist. It will be created.
[datastore] API endpoint: http://localhost:8856
[datastore] If you are using a library that supports the DATASTORE_EMULATOR_HOST environment variable, run:
[datastore]
[datastore]   export DATASTORE_EMULATOR_HOST=localhost:8856
[datastore]
[datastore] Dev App Server is now running.
[datastore]
[datastore] The previous line was printed for backwards compatibility only.
[datastore] If your tests rely on it to confirm emulator startup,
[datastore] please migrate to the emulator health check endpoint (/). Thank you!
[datastore] The health check endpoint for this emulator instance is http://localhost:8856/Jul 24, 2019 10:19:13 AM io.gapi.emulators.grpc.GrpcServer$3 operationComplete
[datastore] INFO: Adding handler(s) to newly registered Channel.
[datastore] Jul 24, 2019 10:19:13 AM io.gapi.emulators.netty.HttpVersionRoutingHandler channelRead
[datastore] INFO: Detected non-HTTP/2 connection.
[datastore] Jul 24, 2019 10:19:13 AM io.gapi.emulators.netty.NotFoundHandler handleRequest
[datastore] INFO: Unknown request URI: /storage/v1/b?project=svkr

I tried to create bucket it fails with above error message. I was wondering why does it say unknown request.

**Comment by svkr521** [comment]
client code,

#include "google/cloud/storage/client.h"
#include <iostream>

int main(int argc, char* argv[]) {
  if (argc != 3) {
    std::cerr << "Missing project id and/or bucket name.\n";
    std::cerr << "Usage: storage_quickstart <bucket-name> <project-id>\n";
    return 1;
  }
  std::string bucket_name = argv[1];
  std::string project_id = argv[2];

  // Create aliases to make the code easier to read.
  namespace gcs = google::cloud::storage;

  // Create a client to communicate with Google Cloud Storage. This client
  // uses the default configuration for authentication and project id.
  google::cloud::StatusOr<gcs::Client> client =
      gcs::Client::CreateDefaultClient();
  if (!client) {
    std::cerr << "Failed to create Storage Client, status=" << client.status()
              << "\n";
    return 1;
  }

  google::cloud::StatusOr<gcs::BucketMetadata> bucket_metadata =
      client->CreateBucketForProject(
          bucket_name, project_id,
          gcs::BucketMetadata()
              .set_location("us-east1")
              .set_storage_class(gcs::storage_class::Regional()));
  if (!bucket_metadata) {
    std::cerr << "Error creating bucket " << bucket_name
              << ", status=" << bucket_metadata.status() << "\n";
    return 1;
  }
  std::cout << "Created bucket " << bucket_metadata->name() << "\n";
  return 0;
}

**Comment by coryan** [comment]
It seems like you figured this out yourself, but for future readers: the client library in `google-cloud-cpp/google/cloud/storage` is for Google Cloud Storage: https://cloud.google.com/storage/, not for Cloud Datastore: https://cloud.google.com/datastore/

Note that we have an emulator for GCS in the code, but this is intended for our testing only, if you find it useful that is great, but cannot guarantee that it will support your use case:

https://github.com/googleapis/google-cloud-cpp/tree/master/google/cloud/storage/testbench
