### ISSUE TITLE
BitBake Support for Google Cloud CPP?

### ISSUE THREAD

**Issue by ArjunNarayan2066** [googleapis/google-cloud-cpp#2914]
I am trying to use the Google Cloud Storage C++ SDK on a project that runs on Automotive Grade Linux. It seems that this the build platform for AGL requires a BitBake recipe used by Yocto to compile the images. I found the following BitBake recipes online for Google Cloud SDK, but it does not seem to support C++ use.

https://layers.openembedded.org/layerindex/recipe/67968/

Can anyone confirm if this is the case and if so if there is some way to integrate Google Cloud SDK into BitBake?

**Comment by devjgm** [comment]
I'm going to tag @scotthart who I think may know more about bitbake than I do.

**Comment by coryan** [comment]
> Can anyone confirm if this is the case

Confirmed, but see below.

> and if so if there is some way to integrate Google Cloud SDK into BitBake?

I am not sure integrating the Google Cloud SDK is what you want.  The Google Cloud SDK is the command-line tool to access Google Cloud Platform:

https://cloud.google.com/sdk/

It is not a library (or set of libraries) to program against Google Cloud in C++ or any other language.

If you want to integrate the C++ client libraries for Google Cloud into BitBake you would need to create BitBake rules to compile the code in this repository.  Having said that, we have no plans to package the libraries for specific Linux (or other OS) distributions.

We would gladly fix any bugs that make it hard (or even annoying) to package the google-cloud-cpp libraries, and happily accept contributions to make packaging easier, but this is not our focus for the foreseeable future.

**Comment by coryan** [comment]
Closing as it seems the question has been answered.
