### ISSUE TITLE
Investigate using grpc++_test_util

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp#2941]
grpc has a [grpc++_test_util](https://github.com/grpc/grpc/blob/216fa1cab3a42edb2e6274b67338351aade99a51/CMakeLists.txt#L3730) library; investigate whether we can/should use this in our projects. At the moment, we've at least re-made [`MockClientReader`](https://github.com/grpc/grpc/blob/618a3f561d4a93f263cca23abad086ed8f4d5e86/include/grpcpp/test/mock_stream.h#L34) in both bigtable and spanner libraries

**Comment by mr-salty** [comment]
in chat, @coryan said:

> It does not seem like gRPC installs that header. So the first step is to figure out what magical incantations in the cmake and/or make configuration for gRPC would get it to actually install the header.
Then you need to figure out if that would break the install instructions in google-cloud-cpp/INSTALL.md, I think we recommend using the system version of gRPC in some cases.

**Comment by devjgm** [comment]
It doesn't look like grpc exposes this library for callers, and I suspect it's not worth the effort for us to ask/make them do it, IMO.

**Comment by mr-salty** [comment]
fyi i couldn't find an easy way to mass unsubscribe from issues so please know that i'm just sitting here silently judging you as these fly by ;)

j/k (or am i?), hope you and the rest of the team are doing well. bradley tells me that new salty is doing great.

**Comment by devjgm** [comment]
haha.. sorry for the noise. Hope you're doing well too.

**Comment by coryan** [comment]
Maybe "unwatch" on the upper right corner of this page? It has a "never be notified" option.

**Comment by mr-salty** [comment]
ah, i don't really mind, they're occasional enough that it's nice to see...  just thought i'd take the opportunity to say hi and mess with you a ittle.

carlos - i unwatched the project but you also get subscribed to any issue/pr/etc you interact with, and there's no bulk unsubscribe. here's someone who is saltier than I am about it: https://drewdevault.com/2021/03/09/github-refuses-to-help-me-unsubscribe.html (well, from that i guess you can do 25 at a time which i'm not sure i realized, but...)
