### ISSUE TITLE
CurlHandle::AsStatus does not handle I/O errors.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#2950]
The code here:

https://github.com/googleapis/google-cloud-cpp/blob/825c3a6a985b55a0b5c33914f1fa4ed784332ea0/google/cloud/storage/internal/curl_handle.cc#L223

Does not handle I/O errors correctly. We need to handle `CURLE_RECV_ERROR` and `CURLE_SEND_ERROR` as `kUnavailable`.

The difficult bit is to write some kind of integration test for this.

**Comment by coryan** [comment]
@JustinBeckwith do you know why the automation is setting the rotating light on this bug? We have folks working on it, and there is a PR going through review.

**Comment by JustinBeckwith** [comment]
Comically, your comment fixed the glitch :) This was the Response SLO logic.  For P1 issues we expect an update on the thread every 5 days.
