### ISSUE TITLE
Subsequent writes to an object reset the stream status

### ISSUE THREAD

**Issue by dopiera** [googleapis/google-cloud-cpp#2952]
A piece of code is worth a thousand words.

This piece of code succeeds but should fail.
```c++
auto os = client->WriteObject(bucket_name, object_name, IfGenerationMatch(0),
    NewResumableUploadSession());
os.exceptions(std::ios_base::failbit);
os << some_data;
os << some_data;  // assume this fails
// ASSERT_STATUS_OK(os.metadata());  - had this been here, it would have failed
os << some_data;
ASSERT_STATUS_OK(os.metadata());
```

It is also an interesting question, why an exception is not thrown.

I will shortly provide a reproducer. This bug was actually found while injecting errors in order to fix #2950.

I haven't searched for the reasons yet.

**Comment by coryan** [comment]
My understanding is:

- `std::ios_base::failbit` is set if there are problems formatting data.
- In contrast `std::ios_base::badbit` is set if there are errors writing data.

The error you got was a write error, not a formatting error. But once that bit is set, I think the stream should not accept more data, so this is still a bug.

**Comment by dopiera** [comment]
Actually, the scenario is easy:
- you keep injecting errors, which makes a write fail until the retry policy is exhausted
- you then either close or destroy the stream (which closes it under the hood), which runs this code with already exhausted retry policy

**Comment by dopiera** [comment]
This is not reproducible. Most likely I was using `metadata()` on a stream which wasn't closed.

A different problem exists, though: #3002
