### ISSUE TITLE
Factor out payload creation from ServiceAccountCredentials::Refresh

### ISSUE THREAD

**Issue by remyabel** [googleapis/google-cloud-cpp#2956]
Follow-up to https://github.com/googleapis/google-cloud-cpp/pull/2954

The following should be moved to a separate function and the associated `*Assertion*` functions moved into the `.cc` file:

https://github.com/googleapis/google-cloud-cpp/blob/825c3a6a985b55a0b5c33914f1fa4ed784332ea0/google/cloud/storage/oauth2/service_account_credentials.h#L215-L219

Per:

> I think all these private functions that do not depend on the state of the class should become standalone functions that can be tested separately.

The unit tests will need to be changed as well.

**Comment by coryan** [comment]
I think this was fixed in #2954. We can reopen if I am wrong.

**Comment by remyabel** [comment]
Yes, it should be re-opened. This was created as follow-up.
