### ISSUE TITLE
Automatically decompress gzip-compressed packages

### ISSUE THREAD

**Issue by ArjunNarayan2066** [googleapis/google-cloud-cpp#2960]
Answering these questions before submitting your bug report will help us give
you a quicker answer.  Thank you!

If one or more of these questions are not applicable, feel free to remove them.

### Does this issue affect the `google-cloud-cpp` project?

If the problem is with the service exposed by the `google-cloud-cpp` APIs
instead of the client libraries you may consider opening a support request
instead.  The `google-cloud-cpp` developers cannot help you troubleshoot
problems with the service itself.

### What component of `google-cloud-cpp` is this related to?

- Cloud Storage.

### What version of `google-cloud-cpp` are you using?

Please include the output from `git rev-parse HEAD` if you are compiling from
source, or the version number from the applicable `*/version.h` file.

0.11 - Does that sound right?

### What operating system and version are you using?

If you are using a Linux distribution include the name and version of the
distribution too.

Ubuntu, but run on anything unix based

### What were you trying to do?

I have a file in my Google Cloud Storage bucket right now. It is gzip-compressed and contains a couple files. I manually set the content-encoding metadata in the cloud console to `gzip`. I then ran the following code:

```cpp
int main() {
    const auto credentials = google::cloud::storage::oauth2::GoogleDefaultCredentials();
    auto client = google::cloud::storage::Client(*credentials);

    string bucket_name = "some_bucket_name";
    string object_name = "some_path_to_encoded_package;
    string file_name = "test";

    auto metadata = client.GetObjectMetadata(bucket_name, object_name);

    std::cout << "The metadata for object " << metadata->name()
        << " in bucket " << metadata->bucket() << " is "
        << *metadata << "\n";

    std::cout << "Encoding: " << metadata->content_encoding() << std::endl;

    auto status = client.DownloadToFile(bucket_name, object_name, file_name);
}
```

### What did you expect to see?

I expected to see in my filesystem the uncompressed/extracted folder such that I could click on it & view the individual files. I am basing this on the `Decompressive Transcoding` section of this page: https://cloud.google.com/storage/docs/transcoding
My understanding may be incorrect but does `Decompressive Transcoding` mean that it will automatically uncompress and extract the folder and files inside?

### What did you see instead?

I see just the compressed file in my file system. It is the same behaviour if I have the content-encoding set in the console and without.

**Comment by coryan** [comment]
Note that I would expect the object to be decompressed, but even if the object contains multiple files, the files would **not** be extracted.

Transcoding is just that: as the object is being downloaded it is automatically decompressed.

We have no plans to automatically untar, or unzip, or unarchive files.

**Comment by devjgm** [comment]
No follows ups on this issue for almost a year. Closing. Feel free to re-open if necessary.
