### ISSUE TITLE
Is it possible to build the GCS cpp sdk using openssl 1.0.2j static lib?

### ISSUE THREAD

**Issue by TonySu7** [googleapis/google-cloud-cpp#2974]
Answering these questions before submitting your bug report will help us give
you a quicker answer.  Thank you!

If one or more of these questions are not applicable, feel free to remove them.

### What component of `google-cloud-cpp` is this related to?
- Cloud Storage.

### What version of `google-cloud-cpp` are you using?

150aaf8296a5dba47dd28e2a448e4bdea46f9037
### What compiler and version are you using?

gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)
### What operating system and version are you using?

centos7

### What were you trying to do?

I am trying to build the google sdk with specific version of openssl(1.0.2j), with the static lib provided. inside the openssl/lib folder, there are 
libcrypto.a  libssl.a 
two static libraries provided.

### What did you expect to see?

I suppose i can build using specific version of openssl.

### What did you see instead?

build failure. 
[ 55%] Linking CXX static library libstorage_client.a
[ 55%] Built target storage_client
Scanning dependencies of target storage_benchmarks
Scanning dependencies of target storage_bucket_acl_samples
[ 55%] Building CXX object google/cloud/storage/examples/CMakeFiles/storage_bucket_acl_samples.dir/storage_bucket_acl_samples.cc.o
[ 56%] Building CXX object google/cloud/storage/benchmarks/CMakeFiles/storage_benchmarks.dir/benchmark_utils.cc.o
Scanning dependencies of target storage_bucket_samples
[ 56%] Building CXX object google/cloud/storage/examples/CMakeFiles/storage_bucket_samples.dir/storage_bucket_samples.cc.o
[ 56%] Linking CXX static library libstorage_benchmarks.a
[ 56%] Built target storage_benchmarks
Scanning dependencies of target storage_bucket_iam_samples
[ 56%] Building CXX object google/cloud/storage/examples/CMakeFiles/storage_bucket_iam_samples.dir/storage_bucket_iam_samples.cc.o
[ 57%] Linking CXX executable storage_bucket_acl_samples
[ 58%] Linking CXX executable storage_bucket_iam_samples
[ 58%] Linking CXX executable storage_bucket_samples
/home/vsts_azpcontainer/Workspace/thirdparty/openssl/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
dso_dlfcn.c:(.text+0x11): undefined reference to `dlopen'
dso_dlfcn.c:(.text+0x24): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x2f): undefined reference to `dlclose'
/home/vsts_azpcontainer/Workspace/thirdparty/openssl/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_bind_func':
dso_dlfcn.c:(.text+0x344): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x3eb): undefined reference to `dlerror'
/home/vsts_azpcontainer/Workspace/thirdparty/openssl/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_bind_var':
dso_dlfcn.c:(.text+0x464): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x50b): undefined reference to `dlerror'
/home/vsts_azpcontainer/Workspace/thirdparty/openssl/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_load':
dso_dlfcn.c:(.text+0x579): undefined reference to `dlopen'
dso_dlfcn.c:(.text+0x5db): undefined reference to `dlclose'
dso_dlfcn.c:(.text+0x613): undefined reference to `dlerror'
/home/vsts_azpcontainer/Workspace/thirdparty/openssl/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_pathbyaddr':
dso_dlfcn.c:(.text+0x69f): undefined reference to `dladdr'
dso_dlfcn.c:(.text+0x701): undefined reference to `dlerror'
/home/vsts_azpcontainer/Workspace/thirdparty/openssl/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_unload':
dso_dlfcn.c:(.text+0x752): undefined reference to `dlclose'
collect2: error: ld returned 1 exit status
gmake[2]: *** [google/cloud/storage/examples/storage_bucket_acl_samples] Error 1
gmake[1]: *** [google/cloud/storage/examples/CMakeFiles/storage_bucket_acl_samples.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
/home/vsts_azpcontainer/Workspace/thirdparty/openssl/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
dso_dlfcn.c:(.text+0x11): undefined reference to `dlopen'
dso_dlfcn.c:(.text+0x24): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x2f): undefined reference to `dlclose'
/home/vsts_azpcontainer/Workspace/thirdparty/openssl/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_bind_func':
dso_dlfcn.c:(.text+0x344): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x3eb): undefined reference to `dlerror'
/home/vsts_azpcontainer/Workspace/thirdparty/openssl/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_bind_var':
dso_dlfcn.c:(.text+0x464): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x50b): undefined reference to `dlerror'
/home/vsts_azpcontainer/Workspace/thirdparty/openssl/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_load':
dso_dlfcn.c:(.text+0x579): undefined reference to `dlopen'
dso_dlfcn.c:(.text+0x5db): undefined reference to `dlclose'
dso_dlfcn.c:(.text+0x613): undefined reference to `dlerror'
/home/vsts_azpcontainer/Workspace/thirdparty/openssl/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_pathbyaddr':
dso_dlfcn.c:(.text+0x69f): undefined reference to `dladdr'
dso_dlfcn.c:(.text+0x701): undefined reference to `dlerror'
/home/vsts_azpcontainer/Workspace/thirdparty/openssl/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_unload':
dso_dlfcn.c:(.text+0x752): undefined reference to `dlclose'
collect2: error: ld returned 1 exit status
gmake[2]: *** [google/cloud/storage/examples/storage_bucket_iam_samples] Error 1
gmake[1]: *** [google/cloud/storage/examples/CMakeFiles/storage_bucket_iam_samples.dir/all] Error 2
/home/vsts_azpcontainer/Workspace/thirdparty/openssl/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
dso_dlfcn.c:(.text+0x11): undefined reference to `dlopen'
dso_dlfcn.c:(.text+0x24): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x2f): undefined reference to `dlclose'
/home/vsts_azpcontainer/Workspace/thirdparty/openssl/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_bind_func':
dso_dlfcn.c:(.text+0x344): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x3eb): undefined reference to `dlerror'
/home/vsts_azpcontainer/Workspace/thirdparty/openssl/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_bind_var':
dso_dlfcn.c:(.text+0x464): undefined reference to `dlsym'
dso_dlfcn.c:(.text+0x50b): undefined reference to `dlerror'
/home/vsts_azpcontainer/Workspace/thirdparty/openssl/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_load':
dso_dlfcn.c:(.text+0x579): undefined reference to `dlopen'
dso_dlfcn.c:(.text+0x5db): undefined reference to `dlclose'
dso_dlfcn.c:(.text+0x613): undefined reference to `dlerror'
/home/vsts_azpcontainer/Workspace/thirdparty/openssl/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_pathbyaddr':
dso_dlfcn.c:(.text+0x69f): undefined reference to `dladdr'
dso_dlfcn.c:(.text+0x701): undefined reference to `dlerror'
/home/vsts_azpcontainer/Workspace/thirdparty/openssl/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_unload':
dso_dlfcn.c:(.text+0x752): undefined reference to `dlclose'
collect2: error: ld returned 1 exit status
gmake[2]: *** [google/cloud/storage/examples/storage_bucket_samples] Error 1
gmake[1]: *** [google/cloud/storage/examples/CMakeFiles/storage_bucket_samples.dir/all] Error 2
CMake Error at /__w/1/s/linux_cmake/Debug/cmake-out/external/grpc/src/grpc_project-stamp/grpc_project-build-.cmake:16 (message):
  Command failed: 2

   '/usr/bin/cmake3' '--build' '/__w/1/s/linux_cmake/Debug/cmake-out/external/grpc/src/grpc_project-build' '--' '-j' '2'

  See also

    /__w/1/s/linux_cmake/Debug/cmake-out/external/grpc/src/grpc_project-stamp/grpc_project-build-*.log

gmake[2]: *** [external/grpc/src/grpc_project-stamp/grpc_project-build] Error 1
gmake[1]: *** [CMakeFiles/grpc_project.dir/all] Error 2
gmake: *** [all] Error 2
##[error]Bash exited with code '2'.

### Anything else you would like us to know?

I tried the exactly same thing on Mac Os, the build works with the static library of openssl. But failure on the Centos7.

Does GCSCPP sdk support it? If I have to use the static openssl lib, what I need to do for GCSSDK? 

Thanks a lot

**Comment by coryan** [comment]
The short answer is that we do not know.  We do not test linking statically against OpenSSL on Linux.  Having said that, the error messages indicate that it is OpenSSL itself that wants to use the dynamic loading functions (`dlopen`, `dlsym`, etc.) and this:

https://stackoverflow.com/questions/18185618/how-to-use-static-linking-with-openssl-in-c-c

leads me to believe that you are probably missing the `-ldl` option in your build.

**Comment by TonySu7** [comment]
Hi Carlos:

Thank you very much for your response. 
Actually I built  the Google Cloud Storage SDK with these errors using 
"cmake -H. -Bcmake-out
cmake --build cmake-out -- -j 4 "
Could you help me to point where is the file that I should add the "-ldl" option in this project?  is there some files in CMakeList.txt or something else? 

Thanks

**Comment by coryan** [comment]
> Actually I built the Google Cloud Storage SDK with these errors using
> "cmake -H. -Bcmake-out
> cmake --build cmake-out -- -j 4 "

Hmm... we do this routinely in our integration builds:

https://storage.googleapis.com/cloud-cpp-kokoro-status/kokoro-readme-centos-link.html

Which basically just use this Dockerfile:

https://github.com/googleapis/google-cloud-cpp/blob/master/ci/kokoro/readme/Dockerfile.centos

I just used that same Dockerfile successfully.  All of that means that I am not understanding something.

> Could you help me to point where is the file that I should add the "-ldl" option in this project? is there some files in CMakeList.txt or something else?

I think that depends on how you are getting the code to find OpenSSL in `/home/vsts_azpcontainer/Workspace/thirdparty/openssl/lib/`, which is how I interpret the logs you attached.

**Comment by TonySu7** [comment]
Hi Carlos:

Sorry for the confusion.

I think the different between my build and your integration build is that my openssl is static lib. In my folder in the `/home/vsts_azpcontainer/Workspace/thirdparty/openssl/lib/`,    all with .a lib files, without any .so shared lib.  
And I getting the code to find OpenSSL by using the `export OPEN_SSL_ROOT=/home/vsts_azpcontainer/Workspace/thirdparty/openssl/lib/`

Followed with your previous suggestion, 

I am currently added the "dl" in  
```target_link_libraries(storage_client
                              PUBLIC google_cloud_cpp_common
                             nlohmann_json
                             Crc32c::crc32c
                             CURL::libcurl
                             Threads::Threads
                             OpenSSL::SSL
                             OpenSSL::Crypto
                             ZLIB::ZLIB
                             dl
                      PRIVATE storage_common_options)
```
in the     `/google-cloud-cpp/google/cloud/storage/CMakeList.txt`  .
and trigger the option by
`export CMAKE_STATIC_LINKER_FLAGS=ldl
export CMAKE_SHARED_LINKER_FLAGS=ldl`  

All the error with GCS storage disappears, but still with error about external grpc project build. 

```[ 66%] Built target storage_throughput_vs_cpu_benchmark
CMake Error at /home/tsu/buildenv/gcscppsdk/linux_cmake/Debug/cmake-out/external/grpc/src/grpc_project-stamp/grpc_project-build-.cmake:16 (message):
  Command failed: 2

   '/usr/local/bin/cmake' '--build' '/home/tsu/buildenv/gcscppsdk/linux_cmake/Debug/cmake-out/external/grpc/src/grpc_project-build' '--' '-j' '4'

  See also

    /home/tsu/buildenv/gcscppsdk/linux_cmake/Debug/cmake-out/external/grpc/src/grpc_project-stamp/grpc_project-build-*.log


gmake[2]: *** [external/grpc/src/grpc_project-stamp/grpc_project-build] Error 1
gmake[1]: *** [CMakeFiles/grpc_project.dir/all] Error 2
gmake: *** [all] Error 2
```

inside the ` /home/tsu/buildenv/gcscppsdk/linux_cmake/Debug/cmake-out/external/grpc/src/grpc_project-stamp/grpc_project-build-*.log`, 

it says

```/usr/bin/ld: /home/tsu/workspace/thirdparty/openssl/lib/libcrypto.a(bn_gf2m.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/tsu/workspace/thirdparty/openssl/lib/libcrypto.a(ec_print.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/tsu/workspace/thirdparty/openssl/lib/libcrypto.a(rsa_gen.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/tsu/workspace/thirdparty/openssl/lib/libcrypto.a(rsa_saos.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/tsu/workspace/thirdparty/openssl/lib/libcrypto.a(rsa_pss.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/tsu/workspace/thirdparty/openssl/lib/libcrypto.a(dsa_gen.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/tsu/workspace/thirdparty/openssl/lib/libcrypto.a(dh_gen.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/tsu/workspace/thirdparty/openssl/lib/libcrypto.a(dso_dlfcn.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/tsu/workspace/thirdparty/openssl/lib/libcrypto.a(a_set.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/tsu/workspace/thirdparty/openssl/lib/libcrypto.a(bio_ndef.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/tsu/workspace/thirdparty/openssl/lib/libcrypto.a(asn_mime.o): relocation R_X86_64_32 against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/tsu/workspace/thirdparty/openssl/lib/libcrypto.a(bio_b64.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/tsu/workspace/thirdparty/openssl/lib/libcrypto.a(bio_asn1.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
gmake[5]: *** [libgrpc_csharp_ext.so] Error 1
gmake[4]: *** [CMakeFiles/grpc_csharp_ext.dir/all] Error 2
gmake[4]: *** Waiting for unfinished jobs...```


Do you have any thoughts on that? 

Thanks for your help again!

Best regards,
Tony

**Comment by remyabel** [comment]
Is `OPEN_SSL_ROOT` supposed to be `OPENSSL_ROOT_DIR`? Furthermore, you probably need to set `OPENSSL_USE_STATIC_LIBS` to true as well.

**Comment by coryan** [comment]
> I think the different between my build and your integration build is that my openssl is static lib. In my folder in the `/home/vsts_azpcontainer/Workspace/thirdparty/openssl/lib/`, all with .a lib files, without any .so shared lib.

Right.

> And I getting the code to find OpenSSL by using the `export OPEN_SSL_ROOT=/home/vsts_azpcontainer/Workspace/thirdparty/openssl/lib/`

I assume that is `OPENSSL_ROOT_DIR` as @remyabel said.

> All the error with GCS storage disappears, but still with error about external grpc project build.

First: do you need the Bigtable client?  If not, maybe you can just remove the `add_subdirectory(bigtable)` and forget about gRPC, protobuf and all the other dependencies.  We should make that configurable ourselves, but it has not gotten to the top of the queue yet.

If you do need the Bigtable client, then I recommend that you manually compile gRPC, Protobuf, CURL, and any other dependency.  Otherwise they will also default to the system's OpenSSL libraries, and will probably default to shared objects too.  The instructions in the INSTALL.md file go into some detail on how to do that.

**Comment by TonySu7** [comment]
Yes, I made a mistake there, `OPENSSL_ROOT_DIR` is what I was using. Not `OPEN_SSL_ROOT`, sorry about that

I will try to set OPENSSL_USE_STATIC_LIBS to be true and try again.

Will let you know.

Thank you very much!
Tony

**Comment by coryan** [comment]
@TonySu7 just checking if you were able to make progress with your build?

**Comment by TonySu7** [comment]
@coryan Thanks a lot for your help! 

set OPENSSL_USE_STATIC_LIBS  = true does not really works for me. There is still an issue with the grpc dependencies build. 

Thanks to your reminder,  I confirm that I do not really need bigtable.Thus I disable the Bigtable and firestore and grputil on cmakelist.txt files. I can build the libstorageclient and libgoogle_cloud_cpp_common.a without grpc dependencies using static openssl lib.

I still need to test how the built lib integrated into my project.

Thanks a lot!

Regards,
Tony

**Comment by coryan** [comment]
@TonySu7  my read is that you were able to make progress and the issue is now resolved.  Just FYI recent versions of google-cloud-cpp have CMake configuration options to disable specific libraries, for example you could say: `cmake -DGOOGLE_CLOUD_CPP_ENABLE_BIGTABLE=OFF`.
