### ISSUE TITLE
[Flake]: Timeout while building docker image.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#2984]
Two builds failed.  They timed out while building the docker image:

https://source.cloud.google.com/results/invocations/df4ae4d5-a5a4-44f4-a3dd-b0b830c51a54
https://source.cloud.google.com/results/invocations/cf482fc7-d267-47f5-b639-89f9dcce27f7

The log is empty because we do not print the log of this phase unless it fails, and the timeout is managed outside our script.  We should change the script to timeout the docker image creation within 60 minutes (that is a rough guess, it should be more than 30 minutes, but less than the 120 minutes for the full build).

**Comment by remyabel** [comment]
The Ubuntu servers seem to be really slow today. Is it viable to look into using an alternate download mirror?
