### ISSUE TITLE
Refactor IsContextMDValid to a common library.

### ISSUE THREAD

**Issue by dopiera** [googleapis/google-cloud-cpp#2994]
This function can be used to check if clients set `x-goog-request-params` properly (in line with `google.api.http`). Spanner or GCS in the future might need it too.

**Comment by remyabel** [comment]
Fixed by https://github.com/googleapis/google-cloud-cpp/commit/3f9003c775c04e64bf5e076c0a19a26b3e1dcc8d?

**Comment by remyabel** [comment]
I see that `IsContextMDValid` already exists in `testing_util` and has usage in spanner. Is there any other work to be done?

**Comment by dopiera** [comment]
I think we can close it, as @coryan fixed it in 0b212617ee5a83db8bf590e0ee211131ba3c2aa5
