### ISSUE TITLE
[Flake]: Timeout in integration tests.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#3003]
The integration tests are flaking with:

```
Running storage::internal::CurlRequestDownload integration test.
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from CurlDownloadRequestTest
[ RUN      ] CurlDownloadRequestTest.SimpleStream
/v/google/cloud/storage/tests/curl_download_request_integration_test.cc:56: Failure
Value of: result
Expected: is OK
Actual: PerformWork() - CURL error [28]=Timeout was reached [DEADLINE_EXCEEDED]
/v/google/cloud/storage/tests/run_integration_tests_testbench.sh: line 48:  8710 Segmentation fault      (core dumped) ./curl_download_request_integration_test
```

I suspect this is my changes in #2993.  The default timeouts are probably too low for the CI environment.

https://source.cloud.google.com/results/invocations/8ed88241-7810-4a66-aa56-c4ea1e7300a7/targets/cloud-cpp%2Fgithub%2Fdocker%2Fcoverage-presubmit/log

**Comment by dopiera** [comment]
FWIW, I'm moderately confident that the reason for the SIGSEGV after the timeout is #2955.

**Comment by dopiera** [comment]
> FWIW, I'm moderately confident that the reason for the SIGSEGV after the timeout is #2955.
 I am now very confident that the reason for the SIGSEGV is different - #2955 was fixed, but the segmentation fault still happens: https://source.cloud.google.com/results/invocations/af99f437-a717-48b2-bb96-4546b2077aae/targets/cloud-cpp%2Fgithub%2Fdocker%2Fcoverage-presubmit/log

**Comment by coryan** [comment]
Ack.  Shoulnd't the changes in #3028 have solved this problem?  A timeout should have resulted in a retry and the test should have (at least) taken much longer to fail?

**Comment by dopiera** [comment]
I looked into it and:
* the SIGSEGV is most likely an easy oversight in the test, I sent #3031 
* the piece of code which is tested is deep enough that it doesn't really have retries (it's raw curl); I'm thinking of removing the test - it's bound to timeout on occasion and the logic must be tested in higher level integration tests too

**Comment by coryan** [comment]
> * the SIGSEGV is most likely an easy oversight in the test, I sent #3031

I oversight when I changed the code to include timeouts.  The fix will eliminate the crashes, but not the problem...

> * the piece of code which is tested is deep enough that it doesn't really have retries (it's raw curl); I'm thinking of removing the test - it's bound to timeout on occasion and the logic must be tested in higher level integration tests too

Probably Okay to remove it, it was useful when building the library to make sure the low level components worked, but it may have outlived its usefulness.
