### ISSUE TITLE
Implement option to read the last N bytes from an object.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#3006]
Apparently sending `Range: bytes=-10` gives you the last 10 bytes, who knew.

We can create an option like `ReadFromOffset`, maybe call it `ReadTail` or `ReadLast`.

**Comment by manish-qlogic** [comment]
if `ReadLast` option is set then `ReadObjectRangeRequest::RangeHeader()` must return
``` java
"Range: bytes=-" + std::to_string(bytes_from_end);
```

But `ReadObjectRangeRequest::RangeHeader()` works even when both `ReadFromOffset` and `ReadRange` are set.

https://github.com/googleapis/google-cloud-cpp/blob/56fd6bfd5ed3c55af5bef97a629f2526ec4d96b1/google/cloud/storage/internal/object_requests.cc#L267

With the introduction of third option(`ReadLast`),What should be the behavior


1. When all three options namely `ReadFromOffset`, `ReadRange` and `ReadLast` are set?
>  One approach would be to return an error.  I think you *can* change `Client::ReadObject()` to emit a compile-time error if all three are set.  Look at HasUseResumableUpload in client.h, you could create a compile-time check `HasAllRangeOptions`:

``` java
struct HasReadLast : public disjunction<is_same<ReadLast, Options>...>;
// Similar for HasReadFromOffset and ReadRange.
struct HasAllRangeOptions : public std::integral_constant<bool,
    HasReadFromOffset::value && HasReadRange::value && HasReadLast> {};
static_assert(!HasAllReadOptions::value, "Cannot set all 3 options Bla Blah");
```


2. When `ReadLast` is set along wtth one of other options in `ReadFromOffset` and `ReadRange`?
>  I think `ReadLast` is incompatible with the other options, let's prevent users from setting it if the others are set.

3. How to handle retry for `ReadLast` scenario?
>  You need to figure out a way to start the download from the last place in that case.  Maybe unset ReadLast and just use ReadFromOffset?
> Alternate way is keep track of offset and a successful read will reduce this offset.
