### ISSUE TITLE
Should not have to manually delete composition files

### ISSUE THREAD

**Issue by acastruc** [googleapis/google-cloud-cpp#3014]
### Does this issue affect the `google-cloud-cpp` project?
Yes

If the problem is with the service exposed by the `google-cloud-cpp` APIs
instead of the client libraries you may consider opening a support request
instead.  The `google-cloud-cpp` developers cannot help you troubleshoot
problems with the service itself.

### What component of `google-cloud-cpp` is this related to?

Remove the ones that do not apply.
- Cloud Storage.

### What version of `google-cloud-cpp` are you using?

Please include the output from `git rev-parse HEAD` if you are compiling from
source, or the version number from the applicable `*/version.h` file.
6430b38c4f600c5fb04f1ed62b8e6debe9463699

### What compiler and version are you using?
Apple LLVM version 10.0.0 (clang-1000.11.45.5)

### What operating system and version are you using?
Mac 10.13.6

### What were you trying to do?
I work on a product that's primary focus is fast transfers of very large files.
After implementing a pool of threads that upload parts of a large file concurrently, the limitations of the google cloud storage "part" paradigm are problematic for us. Namely it seems that functionality is missing that would be common to anyone uploading large files:
1.  Why force the client to manually delete the 'part' files after they are composed? Why not have Client::Compose() do this for you? We deal with huge files with many parts. Having to make 1 REST request per part (to delete afterwards) seems wasteful. I'm not sure what workflow would ever want to keep the part files after composition.
2. Unlike AWS, Azure, the GCS part files are visible to user because they are just regular files. I don't see a way to 'hide' these until they can be composed and deleted. Many of our clients have workflows  that detect the presence of files and kick off some workflow in response. If possible we don't want to trigger this while uploading 'part' files.
3. The compose limit of 32 seems low. And just increasing part size is not always appropriate, depending on connection speed and reliability.

### What did you expect to see?
Be able to call a Compose() API that
1. takes > 32 'parts' at a time
2. automatically delete the 'part' files for you once they are composed
3. it would be nice if the 'part' files are hidden from view until they are composed + discarded.

What was the behaviour you expected from the library?
To make it as easy as possible for clients to use object composition with as few API calls as possible

### What did you see instead?
The API as it stands now forces all applications to reproduce logic that I would expect would be a common requirement when it comes to composing objects.

**Comment by coryan** [comment]
Closing in favor of #7054.
