### ISSUE TITLE
Create a helper to "compose and delete the sources".

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#3015]
As the title says, we want a helper function to compose multiple source objects and then delete the objects when the compose operation is successful.  Error reporting might require some thinking.
See #3014 for the motivation.

**Comment by coryan** [comment]
Should we close this?  It looks like #3239 did implement the functionality, right?

**Comment by dopiera** [comment]
`and then delete the objects` part is missing, but this should be addressed by parallel uploads (#3279), so closing.
