### ISSUE TITLE
Installation integration test fails on OpenSuse

### ISSUE THREAD

**Issue by dopiera** [googleapis/google-cloud-cpp#3032]
When trying to compile `test-install/bigtable` after installing on OpenSuse, cmake fails with:
```
CMake Error at /usr/local/lib64/cmake/googleapis/googleapis-config.cmake:43 (add_library):
  add_library cannot create imported target
  "googleapis-c++::api_resource_protos" because another target with the same
  name already exists.

```
This seems to boil down to including the file file (`googleapis-config.cmake`) twice:
* via
```
  /usr/share/cmake/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /usr/local/lib64/cmake/bigtable_client/bigtable_client-config.cmake:17 (find_dependency)
  CMakeLists.txt:30 (find_package)
```
* and via
```
Call Stack (most recent call first):
  /usr/share/cmake/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /usr/local/lib64/cmake/google_cloud_cpp_grpc_utils/google_cloud_cpp_grpc_utils-config.cmake:16 (find_dependency)
  /usr/share/cmake/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /usr/local/lib64/cmake/bigtable_client/bigtable_client-config.cmake:19 (find_dependency)
  CMakeLists.txt:30 (find_package)
```

I haven't figured out why, yet. I'll get back to it on Monday.

**Comment by remyabel** [comment]
It appears that in the failed PR's the images are being rebuilt, probably from a base image update. That suggests to me that a package update (maybe CMake) is causing the failure. I don't have the proper permissions to pull from gcr.io, can you try using the cached image and see if it works?

```diff
diff --git a/ci/kokoro/install/Dockerfile.opensuse b/ci/kokoro/install/Dockerfile.opensuse
index b9ad60021..b33e906b4 100644
--- a/ci/kokoro/install/Dockerfile.opensuse
+++ b/ci/kokoro/install/Dockerfile.opensuse
@@ -13,7 +13,7 @@
 # limitations under the License.
 
 ARG DISTRO_VERSION=latest
-FROM opensuse/tumbleweed:${DISTRO_VERSION} AS devtools
+FROM gcr.io/cloud-cpp-testing-resources/google-cloud-cpp/test-install-opensuse:latest AS devtools
 ARG NCPU=4
 
 ## [START INSTALL.md]
```

```shell
sudo docker build --build-arg "NCPU=$(nproc)" -f ci/kokoro/install/Dockerfile.opensuse .
```

**Comment by coryan** [comment]
I just rebuilt the images locally and was able to repro the problem.  I think the issue is that `googleapis-config.cmake` is getting included twice (see the stack trace above), and both times it defines the targets:

https://github.com/googleapis/cpp-cmakefiles/blob/51d2b0895c8e301cd132038252734df0ed41afc4/cmake/config.cmake.in#L39-L43

I think this is a bug in `cpp-cmakefiles`, but that does not explain why it was not happening before.

**Comment by coryan** [comment]
I do not think we want to cut the release next week with this bug in, updating to P1.

**Comment by remyabel** [comment]
> I just rebuilt the images locally and was able to repro the problem.

Were you able to use the cached image and reproduce the problem? It'd be nice to test using an older base image of OpenSuse but they don't provide older tags.

> I think this is a bug in cpp-cmakefiles, but that does not explain why it was not happening before.

The only variable I can think of that changed is the base image.

**Comment by dopiera** [comment]
> ```diff
> +FROM gcr.io/cloud-cpp-testing-resources/google-cloud-cpp/test-install-opensuse:latest AS devtools
> ```

I don't have permissions either :(

**Comment by remyabel** [comment]
I compiled 3.14.6 from source inside `Dockerfile.opensuse` and the project builds fine. I'm guessing that the newer version of CMake (3.15) might either A) have a regression, or B) is more stricter about the duplicate targets.

**Comment by dopiera** [comment]
On Aug 27, `cmake-3.15.1-1.1.x86_64.rpm` was introduced to Tumbleweed. I just installed the previous version (`cmake-3.14.5-3.1.x86_64.rpm`) and it work just fine, so indeed we're looking at some breaking `cmake` change.

**Comment by dopiera** [comment]
FWIW, I've added some `message()`s to the file in question and noticed that it is only included once with `cmake-3.14` (only the first stack trace quoted above), so we're not looking at a different handling of including files twice, but at some change of `find_package` behaviour, which results in the file being included twice.

**Comment by remyabel** [comment]
Per the [release notes](https://cmake.org/cmake/help/v3.15/release/3.15.html):

- The CMAKE_FIND_PACKAGE_PREFER_CONFIG variable was added to tell find_package() calls to look for a package configuration file first even if a find module is available.

- In CMake 3.15.0 and 3.15.1 the CMAKE_FIND_PACKAGE_PREFER_CONFIG variable caused the find_package() command to fail on a missing package even without the REQUIRED option. This has been fixed.

WE should try using to 3.15.2 on OpenSUSE and enabling (or disabling) the `CMAKE_FIND_PACKAGE_PREFER_CONFIG` variable. If it works with 3.15.2 then we probably don't need to report it as a bug.

**Comment by dopiera** [comment]
Nice catch. I just tried both
* `cmake -DCMAKE_FIND_PACKAGE_PREFER_CONFIG=FALSE  -H. -Bcmake-out`
* `cmake -DCMAKE_FIND_PACKAGE_PREFER_CONFIG=TRUE  -H. -Bcmake-out`
and it didn't work :(.

But it does hint we're searching in the right area.

FWIW, I'm attaching `cmake --trace` output for both old and new cmake. Maybe someone smarter than me can figure out what is wrong with the new one.
[new.txt](https://github.com/googleapis/google-cloud-cpp/files/3563743/new.txt)
[old.txt](https://github.com/googleapis/google-cloud-cpp/files/3563744/old.txt)

The interesting bit is that the old one includes `/usr/local/lib64/cmake/google_cloud_cpp_grpc_utils/FindProtobufWithTargets.cmake`, but the new one doesn't.

**Comment by remyabel** [comment]
I don't think `TRUE` or `FALSE` are valid values for that variable. You need `ONLY`, `NEVER` or `BOTH`. Supposedly the new default value is `ONLY`, we may need to set it to `BOTH` to get the old behavior.

**Comment by remyabel** [comment]
Whoops. Disregard my last comment. I was confusing it with [CMAKE_FIND_ROOT_PATH_MODE_PACKAGE](https://cmake.org/cmake/help/latest/variable/CMAKE_FIND_ROOT_PATH_MODE_PACKAGE.html)

**Comment by dopiera** [comment]
@coryan I believe you fixed this and we can now close it?

**Comment by coryan** [comment]
I agree.
