### ISSUE TITLE
Allow for not copying data in upload retries 

### ISSUE THREAD

**Issue by dopiera** [googleapis/google-cloud-cpp#3036]
Currently member functions `UploadChunk()` and `UploadFinalChunk()` accept a `std::string const &` as the data carrier.

On retries, there is a need to pass only a part of this data to lower layers, which is impossible with this type. We should change it to something that would allow it, e.g.:
* raw `char *` and size
* something along the lines of `boost::buffer<>`
* ...

**Comment by coryan** [comment]
This is related to #2664, different problem, but the solution might be similar in that both would use a non-owning type (like `boost::buffer<>` or `std::span<char>`) to represent the buffer to be sent.
