### ISSUE TITLE
Allow users to mock functions returning storage::*Metadata values.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#3042]
For "good reasons" the `storage::*Metadata` classes do not have constructors or accessors that can set every field. Many of these classes have fields that are read-only, that is, setting the fields in a `Update` or `Patch` request is always an error.

The only way to initialize these values is through the functions to convert a string in the JSON object format into `storage::*Metadata` object. But these functions live in the `internal::` namespace, and applications should not be calling functions in the `internal::` namespace, not even for mocks.

Maybe we can create functions in a `storage_mocks` namespace, which at least would make it obvious that they are (a) not for general use, and (b) part of our public APIs that we intend to support.

**Comment by devjgm** [comment]
To be fixed as part of https://github.com/googleapis/google-cloud-cpp/issues/7142
