### ISSUE TITLE
Determine namespace(s) to use for "utility" classes.

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp#3046]
Our "utility" classes are currently in the namespace `google::cloud::internal`.  This is fairly unwieldy to type, but attempting to abbreviate it also has issues.

* using-declarations can result in ADL problems (this was actually seen with `make_unique` with a C++17 compiler).
* writing `internal::foo` tends not to work because individual projects have their own more deeply nested `internal` namespaces (e.g. `google::cloud::spanner::internal`).

It would be nice to have a short namespace (similar to `std` or `absl`) so we can name these types unambiguously and without too much cruft.

We should also update/eliminate existing using declarations in this project and others (i.e. spanner).

**Comment by coryan** [comment]
Is there something actionable here?  Are we going to do something?

**Comment by devjgm** [comment]
The pattern we're using now is:

* `google::cloud::foo` (the main product namespace)
* `google::cloud::foo_inernal` (internal bits; a peer of the public namespace)
* `google::cloud::foo_mocks` (optional public namespace for mocks; again a peer of the public namespace)

I don't think it's worth re-namespacing our existing libraries (Spanner, Bigtable, GCS) to match this pattern. But new products (like Pub/Sub), including generated ones, should use this scheme.

At this point, I don't think there's any further work for this issue. Closing.

**Comment by mr-salty** [comment]
we could rename our existing libraries and use aliases so we can migrate slowly.
