### ISSUE TITLE
investigate using prow for cloud C++ repos

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp#3065]
k8s has a system called [prow](https://github.com/kubernetes/test-infra/blob/master/prow/README.md) that does CI/CD, policy enforcement, and automatically merges PRs. let's investigate (not necessarily now, just noting this for future consideration) whether we should use it for our repos as well.

**Comment by JustinBeckwith** [comment]
Calling @bcoe @chingor13 - we have a framework for doing this stuff!
https://github.com/googleapis/repo-automation-bots/

We have several bots that are rolling out, and we're happy to work with y'all.  Prow is something we've discussed as well.

**Comment by bcoe** [comment]
@mr-salty funny you should bring up the topic of automatic merges, I have a peer starting work on this feature soon; would love to know your requirements.

**Comment by mr-salty** [comment]
cool.  Are these bots we're already using like [Conventional Commit Lint GCF](https://github.com/apps/conventional-commit-lint-gcf) from that repo or duplicates? I'm not clear on that, and the landing page doesn't provide much insight (the "Website" link is also broken).

**Comment by mr-salty** [comment]
as far as the auto-merge bot, I liked the functionality and don't think I have any special requirements... Probably it should be disabled by default and only trigger if you put an 'auto-merge' label on the PR or something?  If the label is present and the PR can be merged, then have it trigger when the PR is approved and all the tests have passed (which I assume is the general idea...)

**Comment by bcoe** [comment]
@mr-salty these are the bots we are writing like Conventional Commit Lint GCF, they are housed [here](https://github.com/googleapis/repo-automation-bots).

We're in the process of developing a bot that would merge if an `automerge` label is set, if all `required` checks have passed. It's being worked on by someone who's just coming up to speed on the team, so we're likely tracking next quarter for completion.

Want to share some requirements [here](https://github.com/googleapis/repo-automation-bots/issues/49)? would love your help.

**Comment by coryan** [comment]
I think we are reasonably happy with GCB, which solves the same space (Linux builds) as prow.
/cc: @devjgm
