### ISSUE TITLE
Add examples of different credential classes

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#3067]
Take the experience in #137 and lift that into examples.

**Comment by coryan** [comment]
Can we close this or are we done?  If we only have one credential type left, let's close this bug and open an specific one.

**Comment by coryan** [comment]
Fix @manish-qlogic is there any work left to do?

**Comment by manish-qlogic** [comment]
[Documentation](https://googleapis.dev/cpp/google-cloud-bigtable/latest/bigtable-samples-grpc-credentials.html) has pseudo code example for `Refresh Token`. We do not have working example that is part of CI. It is difficult to write such an example. 

I think, as current documentation and code meets the primary purpose of writing credential examples [(see remark).](https://github.com/googleapis/google-cloud-cpp/issues/137#issuecomment-532814530), We can close this task.

**Comment by coryan** [comment]
SGTM.
