### ISSUE TITLE
Consider using symbol visibility to enforce the "API" boundary

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#3069]
Making the symbols in `google::cloud::*::internal` hidden, or *only* marking the symbols outside that namespace visible (and defaulting to hidden), can make the interface boundaries more explicit, and would actually enforce them for shared objects.

There are some downsides:

- It has no effect for static libraries, so at least some users would be free to use the hidden symbols anyway.
- It requires us to add decorators (like `FOO_EXPORT`) before each class (including template classes) and function.

**Comment by devjgm** [comment]
Punting for now.

**Comment by coryan** [comment]
Closing, we can reopen if we ever find the time to work on this.
