### ISSUE TITLE
Create new helper function for "archive" storage class.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#3075]
We have a number of helper functions for storage class:

https://github.com/googleapis/google-cloud-cpp/blob/e9ccd39d9f12066f43d77f621fdb560a6a0a178b/google/cloud/storage/storage_class.h#L26-L54

We need to add another one of these for `ARCHIVE`.

**Comment by coryan** [comment]
We also need to fix the helpers to create lifecycle policies:

https://github.com/googleapis/google-cloud-cpp/blob/1cc95570aaf877f9e86f64f50b7de246d5dad604/google/cloud/storage/lifecycle_rule.cc#L49

**Comment by frankyn** [comment]
Please assign, @tritone as the reviewer.
