### ISSUE TITLE
X-Upload-Content-Length not Well Supported

### ISSUE THREAD

**Issue by Jseph** [googleapis/google-cloud-cpp#3162]
Issue #857 states all standard parameters in google/cloud/storage are supported in the client libraries.  This doesn't appear to be the case for X-Upload-Content-Length.  We are setting it as a custom header but I would expect it to be in the [well_supported_headers](https://github.com/googleapis/google-cloud-cpp/blob/master/google/cloud/storage/well_known_headers.h) code with all the other x- headers.

**Comment by coryan** [comment]
Thanks, I think when we created the bug we decided (see https://github.com/googleapis/google-cloud-cpp/issues/857#issuecomment-415092420) that the library could set the header when needed.  Can you tell us more about why is the header useful in your use case?  Is it as an additional integrity check? Or something else?

**Comment by Jseph** [comment]
Being able to specify size and MD5 upfront for resumable uploads is part of our end-to-end integrity check story.  It protects us from accidentally bugs causing us to close the stream early or retries resulting in uploading too many bytes, especially for objects where we don't know the checksum ahead of time.  It also protects against corruption if there is a bug in the client library like #2980.

In the comment it says the library sets this value as needed.  There are 3 issues with this approach:

1. AFAICT the library actually only sets Content-Length. X-Upload-Content-Length is never set.
1. This header should be set when the resumable upload is initiated ([source](https://cloud.google.com/storage/docs/json_api/v1/how-tos/resumable-upload#start-resumable)).  This is before the client library is aware of the total object size.
1. If the library were able to set this header it would be setting it based on the data provided to the client library.  It doesn't help protect against corruption resulting from us using the library wrong.

**Comment by Jseph** [comment]
Using CustomHeader is a viable workaround for us but I think it prevents us from setting any other custom headers on the request in the future.
