### ISSUE TITLE
storage_client.pc not getting created during install

### ISSUE THREAD

**Issue by sdhavale** [googleapis/google-cloud-cpp#3174]
### What component of `google-cloud-cpp` is this related to?
Storage Client
- Cloud Storage.

### What version of `google-cloud-cpp` are you using?
v0.12.0

### What compiler and version are you using?
$clang++ -v
clang version 3.8.1-24 (tags/RELEASE_381/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/6.3.0
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/6.3.0
Candidate multilib: .;@m64
Selected multilib: .;@m64

### What operating system and version are you using?
Debian 9.9 Stretch

### What were you trying to do?
storage_client.pc is not getting created during installation.

### What did you expect to see?
storage_client.pc should get created when I do cmake --build . --target install in the last step of installation

### What did you see instead?
Saw few other .pc files getting created, but not storage_client.pc.

### Anything else you would like us to know?
I followed the steps mentioned in install.md file for Debian Stretch. I am not using gcc/g++ but clang++ instead. I want to know if I am missing anything. I didn't see any errors.

**Comment by coryan** [comment]
Reproduced using this Dockerfile [Dockerfile.debian-repro.txt](https://github.com/googleapis/google-cloud-cpp/files/3681411/Dockerfile.debian-repro.txt) largely a copy of `ci/kokoro/install/Dockerfile.debian`

It is, however, fixed in 0.13.0 (see [Dockerfile.debian.txt](https://github.com/googleapis/google-cloud-cpp/files/3681416/Dockerfile.debian.txt)

Please upgrade to 0.13.0, and apologies for the inconvenience.

**Comment by sdhavale** [comment]
I tried installing 0.13.0, but I am getting some errors like :
Could NOT find ProtobufWithTargets (missing:  ProtobufWithTargets_FOUND ProtobufWithTargets_VERSION)
and
In file included from /root/Downloads/google-cloud cpp/google/cloud/grpc_utils/grpc_error_delegate.h:20:
/usr/local/include/google/rpc/status.pb.h:10:10: fatal error: 'google/protobuf/port_def.inc' file not found
#include <google/protobuf/port_def.inc>.

 Not sure if this is because I am using a clang compiler as opposed to gcc/g++. Attached are logs:  
[google-cpp-install.txt](https://github.com/googleapis/google-cloud-cpp/files/3683185/google-cpp-install.txt)

**Comment by coryan** [comment]
> I tried installing 0.13.0, but I am getting some errors like :
> Could NOT find ProtobufWithTargets (missing: ProtobufWithTargets_FOUND ProtobufWithTargets_VERSION)

Hmmm... That is probably a bug in our CMake config files, however, I am not getting that in my build.

> and
> In file included from /root/Downloads/google-cloud cpp/google/cloud/grpc_utils/grpc_error_delegate.h:20:
> /usr/local/include/google/rpc/status.pb.h:10:10: fatal error: 'google/protobuf/port_def.inc' file not found
> #include <google/protobuf/port_def.inc>.
> 

My version of `/usr/local/include/google/rpc/status.pb.h` (from grpc-1.19.1) does not have that `#include`.  What versions of protobuf and gRPC are you installing?

> Not sure if this is because I am using a clang compiler as opposed to gcc/g++.

I just tested with clang and it worked for me using [Dockerfile.debian.txt](https://github.com/googleapis/google-cloud-cpp/files/3683235/Dockerfile.debian.txt)

it worked, so we can (I think) discount that.

> Attached are logs:
> [google-cpp-install.txt](https://github.com/googleapis/google-cloud-cpp/files/3683185/google-cpp-install.txt)

Thanks, nothing obvious from looking at them unfortunately.

**Comment by sdhavale** [comment]
I had earlier installed all the dependencies using clang. I again tried the installation by installing dependencies using g++ and using clang only for google-cloud-cpp, and it worked.
Thank you.

**Comment by coryan** [comment]
No problem.  For what is worth, I was able to compile some of the dependencies with Clang:

[Dockerfile.debian.txt](https://github.com/googleapis/google-cloud-cpp/files/3688056/Dockerfile.debian.txt)

But I was not able to compile Protobuf with Clang.

In any case, seems like you are unblocked, I am closing this bug, feel free to reopen (or create a new one) if you need help.
