### ISSUE TITLE
testing::MockClient is not reusable for clients of c++ SDK

### ISSUE THREAD

**Issue by acastruc** [googleapis/google-cloud-cpp#3176]
### Does this issue affect the `google-cloud-cpp` project?
yes
### What component of `google-cloud-cpp` is this related to?

- Cloud Storage.

### What version of `google-cloud-cpp` are you using?
https://github.com/googleapis/google-cloud-cpp/commit/6430b38c4f600c5fb04f1ed62b8e6debe9463699

### What compiler and version are you using?
Apple LLVM version 10.0.0 (clang-1000.11.45.5)

### What operating system and version are you using?
Mac 10.13.6
If you are using a Linux distribution include the name and version of the
distribution too.

### What were you trying to do?
I have a class 'MyClass' that use the gcs::Client by making api calls
I have unit tests for 'MyClass'. I'd like to use MockClient from the SDK. Obviously the unit test binary links in SDK lib.
But I am unable to  
#include "google/cloud/storage/testing/mock_client.h"
in the hopes of leveraging google::cloud::storage::testing::MockClient;
I've ensured that file is present. I am trying to have a mock client that returns a vector of ObjectMetadata when Client::ListObjects is called.

### What did you expect to see?
MockClient is reusable. Specifically the ability to mock a vector of ObjectMetadata instances that are returned as the result of a call to Client::ListObjects(...)

What was the behavior you expected from the library?
It would be nice to be able to use this to mock the gcs::Client in our projects. 
Specifically to do things like mock what ObjectMetadata gets returned from Client::ListObjects()
I have seen examples in the SDK test source code however I am unable to compile with the existing MockClient. I only see examples in the documentation for ReadObject and WriteObject
### What did you see instead?
Compiler errors as soon as I add the #include and nothing else.

Call to implicitly-deleted copy constructor of 'std::__1::unique_ptr<google::cloud::storage::v1::internal::ObjectReadSource, std::__1::default_delete<google::cloud::storage::v1::internal::ObjectReadSource> >'

Call to implicitly-deleted copy constructor of 'std::__1::unique_ptr<google::cloud::storage::v1::internal::ResumableUploadSession, std::__1::default_delete<google::cloud::storage::v1::internal::ResumableUploadSession> >'

No matching constructor for initialization of 'const google::cloud::v0::StatusOr<std::__1::unique_ptr<google::cloud::storage::v1::internal::ObjectReadSource, std::__1::default_delete<google::cloud::storage::v1::internal::ObjectReadSource> > >'

No matching constructor for initialization of 'google::cloud::v0::StatusOr<std::__1::unique_ptr<google::cloud::storage::v1::internal::ObjectReadSource, std::__1::default_delete<google::cloud::storage::v1::internal::ObjectReadSource> > >'
...

What was the behavior you actually observed?
none
### Anything else you would like us to know?
Is this simply user error ? Is it possible to leverage MockClient from outside the sdk ?

**Comment by acastruc** [comment]
It occurs to me that maybe my version of gmock is too old. I am using 1.7

**Comment by coryan** [comment]
> It occurs to me that maybe my version of gmock is too old. I am using 1.7

That sounds likely, we cannot use 1.8+ (for complicated reasons), so we never test with 1.7.  Would it be hard for you to upgrade to google/googletest@b6cd405286ed8635ece71c72f118e659f4ade3fb or newer?

**Comment by acastruc** [comment]
I am trying that now

**Comment by acastruc** [comment]
Gmock 1.7.0 was the culprit
