### ISSUE TITLE
MutationBatcherTest.BatchIsFlushedImmediately assertion failed: pthread_mutex_destroy(mu)

### ISSUE THREAD

**Issue by dopiera** [googleapis/google-cloud-cpp#3181]
It failed on me once on an unrelated PR: https://source.cloud.google.com/results/invocations/019a2ff5-f2ac-4f05-b77e-83ad557b7c0d/targets/cloud-cpp%2Fgithub%2Finstall%2Fopensuse-leap-presubmit/log

I'm guessing we're destroying the batcher too early. The question remains whether it's a real issue or a test issue.

**Comment by coryan** [comment]
This is (I think) a duplicate of #2249
