### ISSUE TITLE
update "cutting a release" docs

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp#3188]
The "cutting a release" docs [(example)](https://github.com/googleapis/google-cloud-cpp/blob/master/doc/cutting-a-release.md) are out of date.

This applies to all projects, but I'm only filing one issue here to discuss changes.

* We may want to consider "refactoring" those documents into a common part (hopefully the majority of it) and repo-specific parts.
* The `skip-ci` tag is not effective since moving to kokoro; we should remove it.
* "This will start a CI build cycle. The builds should pass"... is not accurate; kokoro does not kick off a CI build. The release notes change will (since skip-ci isn't effective); that isn't technically the same thing since it runs against `master` and not the release branch but they **should** be identical at that point.

**Comment by mr-salty** [comment]
A larger issue: do we have the "flow" correct? The current process, as written, will result in the release branch `README.md` **not** containing the release notes for that release. There's also a race condition between committing the release notes and cutting the branch which @coryan gave a reason for involving package maintainers that I didn't quite understand.

Is there a way we can cut the branch first, then write the release notes and have them end up present in both the release branch and master?  Does this work?

* cut a branch from master at a given commit.
* write the release notes based on the commits in that branch vs. the prior release.
* send a PR to pull those release notes into the release branch directly (do permissions allow that?)
* when CI passes, publish the release (do we need the pre-release step?)
* merge the release notes change back into `master`

**Comment by mr-salty** [comment]
@devbww @scotthart and I discussed the following change to the documented procedure (in all repos), unless we're missing something (which may require input from @coryan so let's ping him when he returns)

* write the release notes, have them reviewed, and check them in.
  * Right now, there's a "Ask your colleagues to review the release notes." section much later (after "Create a pre-release"), but that does not appear to be what happens in practice.
  * There is still a race here while the notes are in review, if some commits come in the in meantime we will have to update the notes to refer to them.
* Create the tag explicitly *at* the commit for the release notes.
  * That gets rid of a second possible race, where more commits arrive after the notes are checked in.
* Get rid of the "pre-release" and just create a release, since there doesn't seem to be a need for it.

**Comment by coryan** [comment]
> @devbww @scotthart and I discussed the following change to the documented procedure (in all repos), unless we're missing something (which may require input from @coryan so let's ping him when he returns)
> 
> * write the release notes, have them reviewed, and check them in.
>   
>   * Right now, there's a "Ask your colleagues to review the release notes." section much later (after "Create a pre-release"), but that does not appear to be what happens in practice.

This is trying to make sure the release notes in the release match the release notes in the README *and* match previous release notes for previous releases.  As an example, I have caught release notes that are missing the SHA256 numbers.

>   * There is still a race here while the notes are in review, if some commits come in the in meantime we will have to update the notes to refer to them.

Correct.

> * Create the tag explicitly _at_ the commit for the release notes.

That sounds like a very good idea.

> * Get rid of the "pre-release" and just create a release, since there doesn't seem to be a need for it.

This seems fine.  The only difference in practice is that we *may* change the description of the release afterwards, for example if the SHA numbers do not match or we missed some important notes.

**Comment by coryan** [comment]
Is there something left to be done here?
/cc: @devjgm because he has been updating these docs.

**Comment by devjgm** [comment]
The release process has changed a ton since this issue was filed. Most of what's in this issue is now obsolete. We currently have a single release doc (well, 1 for the OSS part, and one for importing). These docs should be much easier to keep up to date. And AFAIK, they are current as of now.

I think we should close this particular issue. If we discover new issues w/ the current release doc(s), we should probably file new issues.

**Comment by mr-salty** [comment]
+1
