### ISSUE TITLE
Document thread-safety of BigTable API

### ISSUE THREAD

**Issue by jkuszmaul** [googleapis/google-cloud-cpp#3207]
Akin to #803, increase documentation as to which APIs can be safely accessed in a thread-safe manner.

In particular, the use-case I am looking at is:
1. Create a single `Table`.
2. Call `ReadRows` a bunch of time
3. Spawn one thread per returned `RowReader`
4. In each thread, iterate over the `RowReader` it now has--one thread may begin to iterate over the `RowReader` before all the `RowReader`s have been created.

I might also want to, e.g., call `ReadRows` in separate threads. I don't have a need for it, but documenting whether an individual `RowReader` object can be accessed from multiple threads would also be nice.

Per @coryan in the `#cloud-bigtable` slack channel, it sounds like this is safe. However it is not reflected well in the documentation--e.g., https://googleapis.dev/cpp/google-cloud-bigtable/1.3.0/classgoogle_1_1cloud_1_1bigtable_1_1v1_1_1Table.html explicitly suggests that operating on a single `Table` in multiple threads is not safe, and that the correct method would be to copy-construct instances for each thread.

**Comment by coryan** [comment]
There is a 'Thread Safety' section here:

https://googleapis.dev/cpp/google-cloud-bigtable/1.3.0/classgoogle_1_1cloud_1_1bigtable_1_1v1_1_1Table.html#details

Does that address the question, or you think each member function should repeat the thread safety guarantees?

**Comment by jkuszmaul** [comment]
Yeah, that's what I was mentioning in the post. I guess the thing I'm curious about here specifically is that, since `RowReader` objects seem to use the same underlying `DataClient`, the above documentation does not make it clear that it is safe to access multiple `RowReaders` in parallel--if I were to follow it to a "t", then I'd make copies of the `Table` before each call to `ReadRows`. Documenting each method individually seems unnecessary--`ReadRows` is just a bit special because it continues to cause operations to be performed on the table even after the call to `ReadRows`. It's also the case that it'd be nice to know if any functions _are_ allowed to safely be accessed from multiple threads on a single instance of a `Table`, although that is not my current use case.

Also, tbh, I had missed that section on my first reading of the documentation. I'll put that on me though.

**Comment by jkuszmaul** [comment]
Although thinking about it, I'm wondering if it might just be simpler to document all the methods individually. That feels like it'd be unnecessary, but that might be lower effort than having to field questions like "Would it be safe to call `Table::table_name()` on the same instance from multiple threads?". But that also makes more documentation that you'd have to maintain. So I'm largely agnostic on it.
