### ISSUE TITLE
Warn users that the `ARCHIVE` storage class is not GA

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#3253]
We should add comments to the helpers related to the `ARCHIVE` storage class saying that these are not generally available.  I think `storage_class::Archive()` and `SetStorageClassArchive()` are the main ones.

**Comment by coryan** [comment]
Alternatively, we could just remove these functions, looks like the feature is going to be on hold.

**Comment by tritone** [comment]
This is no longer needed; please close. Thanks!
