### ISSUE TITLE
`Table::idempotent_mutation_policy_` may be inadvertently mutated

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp#3256]
[`Table::idempotent_mutation_policy_`](https://github.com/googleapis/google-cloud-cpp/blob/70bbb4ca1daed4525bf4b9f1fa2d61d75d0f5c39/google/cloud/bigtable/table.h#L836) is treated as a Prototype in some cases [(example)](https://github.com/googleapis/google-cloud-cpp/blob/70bbb4ca1daed4525bf4b9f1fa2d61d75d0f5c39/google/cloud/bigtable/table.cc#L74) but in other cases we call the non-const method `is_idempotent()` directly [(example)](https://github.com/googleapis/google-cloud-cpp/blob/70bbb4ca1daed4525bf4b9f1fa2d61d75d0f5c39/google/cloud/bigtable/table.cc#L234-L235) which potentially modifies the policy state for future calls.

In practice this is not currently a problem because none of the `is_idempotent()` overloads actually change the state, but we should clean this up by either:

* make `idempotent_mutation_policy_` const and name it `idempotent_mutation_policy_prototype_`  (like the other policies) to make it clear it must be `clone()`d before use.
* make `IdempotentMutationPolicy::is_idempotent()` methods `const`. Then we can also make `idempotent_mutation_policy_` const (but should not name it `...prototype_`), and should likely stop cloning it in all circumstances.  This is the approach used in [GCS retry_client](https://github.com/googleapis/google-cloud-cpp/blob/70bbb4ca1daed4525bf4b9f1fa2d61d75d0f5c39/google/cloud/storage/internal/retry_client.cc#L132) in a similar circumstance.

**Comment by coryan** [comment]
This should get fixed with #5934

**Comment by coryan** [comment]
We are happy with the class maintaining its invariants.  Closing.
