### ISSUE TITLE
Default bigtable connection pool size is inconsistent

### ISSUE THREAD

**Issue by PeteyPii** [googleapis/google-cloud-cpp#3260]
Default constructing a ClientOptions object and calling ClientOptions::set_connection_pool_size(0) results in different pool sizes despite the documentation claiming both are the default. See [here](https://github.com/PeteyPii/google-cloud-cpp/blob/e9c21295a63e46965ef1d0088d82492cf7b6346c/google/cloud/bigtable/client_options.cc#L77).

**Comment by coryan** [comment]
Fixed in #3261
