### ISSUE TITLE
Fix static vs. shared support in libcurl super build file.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#3269]
The libcurl CMake files do not use the standard configuration parameters for static vs. shared, we probably need to set `CURL_STATICLIB` and `CURL_SHAREDLIB` based on `BUILD_SHARED_LIBS`.

**Comment by remyabel** [comment]
It's the other way around. The old option `CURL_STATICLIB` was replaced by `BUILD_SHARED_LIBS`. I checked version 7.65.3.
