### ISSUE TITLE
[Flake]: gRPC assertion in macOS build

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#3273]
I have seen this crash a couple of times.  I think @remyabel is right, and this is related to grpc/grpc#20311

The log reads:

```
E1118 19:13:59.012583000 123145316958208 tls_pthread.cc:26]            assertion failed: 0 == pthread_setspecific(tls->key, (void*)value)
external/bazel_tools/tools/test/test-setup.sh: line 310: 84821 Abort trap: 6           "${TEST_PATH}" "$@" 2>&1
================================================================================
[2,722 / 2,729] 132 / 137 tests, 1 failed; Compiling google/cloud/examples/gcs2cbt.cc; 5s darwin-sandbox ... (4 actions, 3 running)
```

The full log is on:

https://source.cloud.google.com/results/invocations/8f741d0f-98ec-441d-b527-a0b9f154bcd9/targets/cloud-cpp%2Fgithub%2Fmacos%2Fpresubmit/log

**Comment by coryan** [comment]
Might be related to: grpc/grpc#20429 or grpc/grpc#20413

**Comment by mr-salty** [comment]
This issue shows as "out of SLO" on our dashboard, although it did not have the rotating beacon label.

IIUC it "must be resolved within 180 days" with no option to extend the time. Is this still happening?

**Comment by coryan** [comment]
We continue to see this in `-spanner` (see the link around 2019-11-19). You can close this one, but I suspect we will need to reopen it soon.

**Comment by mr-salty** [comment]
If it's still happening, the bug shouldn't be closed.  I don't think dropping it to p3 is necessarily the right answer either but better than closing it, and at least makes it "in SLO"

**Comment by coryan** [comment]
An alternative is to use the `external` label as "blocked on an external bug", since we have several bugs in gRPC that are candidates.

**Comment by devbww** [comment]
The last reported instance of this was 2020-01-31.  Perhaps the gRPC updates did fix something.

I'm suggesting we should close for now.  And in the meantime I'm removing the beacon label.

**Comment by coryan** [comment]
Agree, we previously agreed with @devjgm to close flakes that do not repeat after 90 days.
