### ISSUE TITLE
is the `gh-pages` branch in this repo still used?

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp#3289]
I noticed that the [gh-pages branch](https://github.com/googleapis/google-cloud-cpp/tree/gh-pages) in this repo is ~6 months behind... but the docs on https://googleapis.github.io/google-cloud-cpp/ still appear to be up to date.  Do we need this branch, or can we delete it?

note there are also some references in the docs: https://github.com/googleapis/google-cloud-cpp/search?q=gh-pages&unscoped_q=gh-pages

**Comment by remyabel** [comment]
The docs are now published/served from GCP, but the index page (which links to `googleapis.dev`) is still hosted in `gh-pages`. I would imagine that the index page needs to be hosted on `googleapis.dev` before deleting the branch.

**Comment by coryan** [comment]
I fixed the `ci/kokoro/docker/upload-docs.sh` script only to discover that our token to upload pages had expired.  I am going to disable the upload (but keep the script running) and then I have to stop working on this.

**Comment by coryan** [comment]
This is now working again, for example:

https://googleapis.github.io/google-cloud-cpp/latest/pubsub/
