### ISSUE TITLE
Write speeds not affected by write chunk size

### ISSUE THREAD

**Issue by gxr** [googleapis/google-cloud-cpp#3290]
Answering these questions before submitting your bug report will help us give
you a quicker answer.  Thank you!

If one or more of these questions are not applicable, feel free to remove them.

### Does this issue affect the `google-cloud-cpp` project?

If the problem is with the service exposed by the `google-cloud-cpp` APIs
instead of the client libraries you may consider opening a support request
instead.  The `google-cloud-cpp` developers cannot help you troubleshoot
problems with the service itself.

### What component of `google-cloud-cpp` is this related to?

Remove the ones that do not apply.
- Cloud Storage.

### What version of `google-cloud-cpp` are you using?
0.15.0

Please include the output from `git rev-parse HEAD` if you are compiling from
source, or the version number from the applicable `*/version.h` file.

### What compiler and version are you using?
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/opt/foo/libexec/gcc/x86_64-pc-linux-gnu/9.1.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /tmp/tmp.kmkSDUDFn8/build/../gcc-9.1.0/configure --prefix=/opt/foo--enable-languages=c,c++ --disable-multilib --enable-shared --enable-lto --enable-threads=posix --with-arch=haswell --with-tune=skylake
Thread model: posix
gcc version 9.1.0 (GCC)

Please include the output of `g++ -v` or the equivalent command-line flag.

### What operating system and version are you using?
Centos 7

If you are using a Linux distribution include the name and version of the
distribution too.

### What were you trying to do?
Trying to write a file a to cloud storage using ObjectWriteStream

### What did you expect to see?
I expect to see above 100 MB/s transfer rates using the ObjectWriteStream since I can easily reproduce way higher transfer rates with iperf3. I am also able to reproduce 200 MB/s download speed easily between a google compute node and cloud storage.

### What did you see instead?
I see only up to 30 MB/s upload rate regardless of how many bytes are being written at once when I do stream->write(char*, bytes). I expect to see a sweet spot with a good choice of bytes but that is not the case. I am able to achieve a much higher download rate by chunking appropriately.

### Anything else you would like us to know?

Looking at the source code I notice that the payload is being copied as a std::string which at first glance seems to suggest some unnecessary copying? Perhaps one could use a std::string_view instead? Another question is whether or not you guys intend on switching to HTTP2 which should have better performance as well.

**Comment by coryan** [comment]
Thank you for filing a detailed report.

> I am able to achieve a much higher download rate by chunking appropriately.

This is normal, GCS is much faster at downloading vs. uploading.

> I see only up to 30 MB/s upload rate regardless of how many bytes are being written at once when I do stream->write(char*, bytes).

How big of a range did you use?  We recommend really big chunks for high throughput, previous experiments (see #2657) suggest that using 16MiB chunks for large files gets you about 50MiB/s, which is consistent with what other folks get, for example:

https://medium.com/google-cloud/google-cloud-storage-large-object-upload-speeds-7339751eaa24


> I expect to see a sweet spot with a good choice of bytes but that is not the case.

Note that multiples of 256KiB are sort of ideal from a buffer management perspective.

> Looking at the source code I notice that the payload is being copied as a std::string which at first glance seems to suggest some unnecessary copying? Perhaps one could use a std::string_view instead?

Unfortunately we want/need to support C++11 users.  There is an open bug (#2664) to optimize this path, but the memory bandwidth of that additional copy is not the limiting factor here.

> Another question is whether or not you guys intend on switching to HTTP2 which should have better performance as well.

No such plans at the moment.  There is ongoing work to parallelize uploads for large files, I realize that is not going to help you though.

Let me know if you have any further questions.

**Comment by gxr** [comment]
That makes sense. Thank you.
