### ISSUE TITLE
GCE auto detection broken in GCS library

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#3304]
It seems that the GCE detection is broken for Cloud Run (and presumably things like Google App Engine Flex).  The `/sys` file system does not include the file used here:

https://github.com/googleapis/google-cloud-cpp/blob/cc0004e045237e0133cc5acd155d02d2d80abddb/google/cloud/storage/internal/compute_engine_util.cc#L93

The gRPC detection changed over the last year to use the metadata server as a fallback even if we cannot assert that the machine is a GCE instance.  We should probably do the same.

**Comment by dopiera** [comment]
Good news: GKE, AppEngine Flex and GCE work.

Bad news: after pretty deep digging, I don't know how to address Cloud Run.

Contrary to others, Cloud Run uses gVisor, which does a pretty good job at hiding what it runs on. It is pretty easy to tell it's gVisor, but it I have no idea how to tell if it's running inside Google.

FWIW, there is a somewhat related bug: https://github.com/google/gvisor/issues/54

This is what I tried to get some data:
* grep the whole VFS for `google`, `appengine`
* read the kernel log (`/dev/kmsg` is missing, but `syslog(SYSLOG_ACTION_READ_ALL)` works) - you can tell it's gVisor
* grepping `vdso`, `vsyscall`, `vvar`
* dumping a process' memory and grepping it
* uname (it is hardcoded to `Linux ef89c97e0a83 4.4.0 #1 SMP Sun Jan 10 15:06:54 PST 2016 x86_64 x86_64 x86_64 GNU/Linux`, but it doesn't tell if it's Cloud Run or not)
* cpuinfo (nothing specific)
* dmidecode (`/dev/mem` is unavailable)

I think that if we want to solve it reliably, we need either need support in gVisor or an internal service which would tell you if you're inside or not.

**Comment by dopiera** [comment]
Actually, I did find a way - rev DNS the main DNS server.

```
$ host $(cat /etc/resolv.conf | grep ^nameserver | cut -f2- -d ' ')
254.169.254.169.in-addr.arpa domain name pointer metadata.google.internal.
```
It's pretty brittle, though. Especially that:
* if the user starts a `systemd-resolver` or `dnsmasq`, it no longer works
* if the user changes the nameserver, it no longer works
* if the user uses some NSS magic, it might not work

**Comment by coryan** [comment]
gRPC seems to query `metadata.google.internal` *without* checking for any other conditions. I think the argument is basically: "if it works, and the credentials are valid, then you were on GCE or something that behaves like GCE and produces good credentials".  If the application does not want us to try `metadata.google.internal.` they can set `GOOGLE_APPLICATION_CREDENTIALS`. GCE is the last resort, right?

**Comment by dopiera** [comment]
@coryan following your request, I'm describing how to run on App Engine Flex

Apply this patch and compile (under Fedora 31):
```patch
diff --git a/google/cloud/storage/examples/CMakeLists.txt b/google/cloud/storage/examples/CMakeLists.txt
index b82d3b459..6112987e3 100644
--- a/google/cloud/storage/examples/CMakeLists.txt
+++ b/google/cloud/storage/examples/CMakeLists.txt
@@ -47,6 +47,7 @@ set(storage_examples
     storage_service_account_samples.cc
     storage_signed_url_v2_samples.cc
     storage_signed_url_v4_samples.cc
+    storage_test_gce_creds.cc
     storage_website_samples.cc)
 
 set(storage_examples_unit_tests
diff --git a/google/cloud/storage/examples/storage_test_gce_creds.cc b/google/cloud/storage/examples/storage_test_gce_creds.cc
new file mode 100644
index 000000000..b4f164e77
--- /dev/null
+++ b/google/cloud/storage/examples/storage_test_gce_creds.cc
@@ -0,0 +1,22 @@
+#include "google/cloud/storage/client.h"
+#include "google/cloud/storage/oauth2/compute_engine_credentials.h"
+#include "google/cloud/storage/oauth2/google_credentials.h"
+#include <iostream>
+
+int main() {
+  auto creds = google::cloud::storage::oauth2::GoogleDefaultCredentials();
+  std::cout << "Got " << (!creds ? "no " : "") << "credentials" << std::endl;
+  if (!creds) {
+    std::cout << "Cred error: " << creds.status() << std::endl;
+    return 1;
+  }
+  auto* ptr = creds->get();
+  std::cout
+      << "Credentials are "
+      << ((typeid(*ptr) !=
+           typeid(google::cloud::storage::oauth2::ComputeEngineCredentials<>))
+              ? "not "
+              : "")
+      << "ComputeEngineCredentials" << std::endl;
+  return 0;
+}
```

Prepare a directory containing:
* results of compilation:  `libcrc32c.so.1`,  `libcrc32c.so.1.1.0`, `storage_test_gce_creds`
* Dockerfile:
```docker
FROM fedora:31

COPY . /pkg

ENV LD_LIBRARY_PATH=/pkg
ENTRYPOINT /pkg/storage_test_gce_creds
```
* app.yml
```yaml
runtime: custom
env: flex
```

In order to run on App Engine Flex run: `gcloud app deploy`.

In order to run on Cloud Run, in that directory run:
```sh
$ docker build -t gcr.io/grass-clump-479/detect
$ docker push gcr.io/grass-clump-479/detect:latest
$ gcloud run deploy --image gcr.io/grass-clump-479/detect --platform managed
```
In order to run on K8s:
Create a directory with a file containing:
```yml
apiVersion: v1
kind: Pod
metadata:
  name: detect-test
spec:
  containers:
  - name: detect-test
    image: gcr.io/grass-clump-479/detect:latest
```
In that directory run
```sh
$ gcloud container clusters create detect-test --num-nodes=1 --zone us-central1-c
$ kubectl apply -f .
$ kubectl logs detect-test
```
