### ISSUE TITLE
Composing objects in groups of 32 leads to rateLimitExceeded error

### ISSUE THREAD

**Issue by acastruc** [googleapis/google-cloud-cpp#3309]
Answering these questions before submitting your bug report will help us give
you a quicker answer.  Thank you!

If one or more of these questions are not applicable, feel free to remove them.

### Does this issue affect the `google-cloud-cpp` project?
Yes, specifically the ComposeObject api
If the problem is with the service exposed by the `google-cloud-cpp` APIs
instead of the client libraries you may consider opening a support request
instead.  The `google-cloud-cpp` developers cannot help you troubleshoot
problems with the service itself.

### What component of `google-cloud-cpp` is this related to?
- Cloud Storage

### What version of `google-cloud-cpp` are you using?
https://github.com/googleapis/google-cloud-cpp/commit/6430b38c4f600c5fb04f1ed62b8e6debe9463699
0.11

### What compiler and version are you using?
Apple LLVM version 10.0.0 (clang-1000.11.45.5)

### What operating system and version are you using?
Mac 10.13.6

### What were you trying to do?
I work within a business space that's concerned with transferring large files quickly and securely to destinations such as cloud storage. We maximize upload throughput by multi-part concurrent uploads which are then assembled into the original object. This paradigm is quite common in cloud storage providers and indeed most offer api to handle the details of file assembly automatically. However, certain limitations of the google cloud storage "part" paradigm are problematic for us. The specific scenario that we are investigating here was a 10Gb file broken into 1000 part files. 

### What did you expect to see?
The ComposeObject api return success as we reassemble the final 10Gb object.

###What was the behaviour you expected from the library?
Calling the ComposeObject api with groups of 32 objects (as is the documented limit of cpp api) until all 1000 parts are successfully composed into the single file.

### What did you see instead?
Once the part files are uploaded, if we upload too fast and the calls to ComposeObject api are too close together the ComposeObject api fails with a 429 error code
ComposeObject api returns
Error in non-idempotent operation ComposeObject: {
  "error": {
    "code": 429,
    "message": "The rate of change requests to the object bucket/folder/10G.bin exceeds the rate limit. Please reduce the rate of create, update, and delete requests.",
    "errors": [
      {
        "message": "The rate of change requests to the object bucket/folder/10G.bin exceeds the rate limit. Please reduce the rate of create, update, and delete requests.",
        "domain": "usageLimits",
        "reason": "rateLimitExceeded"
      }
    ]
  }
}
Users of the ComposeObject api are forced to limit the calls to 32 objects at a time. We should not then be penalized because we need to do more than 32 faster than the backend services can handle. This is one of the reasons other cloud storage providers hide the details of composing parts into larger files.

### Anything else you would like us to know?
The implementation of the gcs ComposeObject (specifically its limitations) should not be forcing callers of the api to have to 'slow down' the composes. Allow a larger compose limit or remove the ratelimiting of composeobject calls.
Yes, Increasing the part size would reduce the number of parts and thus # calls to ComposeObject api but this only masks the issue. Besides, we need to be able to adjust part sizes to maximize throughput. And for any given part size there is a overall file size that can yield a large number of parts.

Include here information about your environment that is not captured above, or
any other information you think might be relevant.

**Comment by coryan** [comment]
Thank you for filing a detailed bug report.  I will pass this on to my colleagues working on GCS, maybe they can raise the 32 object limit and/or increase the object change rate limit in the service.  Unfortunately, there is little we can do in the library to fix either.

We can, however, build better functionality in the library to help you use the existing APIs as efficiently as possible.  We recently [released](https://github.com/googleapis/google-cloud-cpp/releases/tag/v0.17.0) a new version of the library with two functions that might help you:

- `google::cloud::storage::ComposeMany` ([docs](https://googleapis.dev/cpp/google-cloud-storage/latest/namespacegoogle_1_1cloud_1_1storage_1_1v1.html#a848d7fcfc556c5e45fc552ea81e68054)) can create an object from an unlimited number of components. It does need a prefix to store temporary objects, as it creates an object for the first 32 components, another object for the remaining 32 components, and so forth (and then builds up a hierarchy of objects until the final object is built).

- You may want to take a look at `google::cloud::storage::ParallelUploadFile()` ([docs](https://googleapis.dev/cpp/google-cloud-storage/latest/namespacegoogle_1_1cloud_1_1storage_1_1v1.html#aa7c3ff7d43779f608cb2e814cb4386f1)) which uploads a file using multiple shards (and threads) and then uses `ComposeMany` to build the larger object.

Please let us know if these help.

**Comment by acastruc** [comment]
@coryan I have a question. Back before the ::ComposeMany api was introduced we composed in groups of 32, then manually deleted files. One side effect we noticed was that uploading a multipart file this way required DELETE permissions enabled on the bucket. Is this true with the new ComposeMany() api ?
Similarly, a retention policy actively interferes with deleting parts. Is this true with the new ComposeMany() api ?
Thanks

**Comment by coryan** [comment]
> @coryan I have a question. Back before the ::ComposeMany api was introduced we composed in groups of 32, then manually deleted files. One side effect we noticed was that uploading a multipart file this way required DELETE permissions enabled on the bucket. Is this true with the new ComposeMany() api ?

Yes.

> Similarly, a retention policy actively interferes with deleting parts. Is this true with the new ComposeMany() api ?

My guess is "yes", because `ComposeMany()` is just a helper to call `Compose()` repeatedly (no new server-side stuff).  Though I am not sure what interference you have in mind, if you could explain I would be grateful, I think I will be learning something.

**Comment by acastruc** [comment]
Ugh. IMO this is more reason to do as AWS and Azure and treat part files as second class citizens - they are hidden from the end user and are completely managed by the storage service, hence there is no i) rate limiting on compose, ii) no delete permissions to clean up parts, iii) no retention policy that binds the parts
My company works in an industry where companies are very security conscious-they do not understand (rightly so) why they need to enable DELETE permissions in order to upload large files. Ditto for retention policy

**Comment by coryan** [comment]
Got it. I think the GCS understands the value of multi-part uploading too.

One idea we have been bouncing around is using a separate bucket to hold the parts during the upload, and then "moving" the final object (using `Client::RewriteObject()`) to the destination bucket. `RewriteObject` is (mostly) server-side: you do not need to download and upload the data again, but you might need multiple calls before the operation completes. Would that be useful to you?

**Comment by acastruc** [comment]
Let me first say that I really appreciate your comments and input on this, and I am happy to work towards the best solution. 
As for an additional bucket, I can think of a couple problem with that:
i) it pushes implementation details to the customer - they will wonder why they need two buckets to upload to one bucket? Our customers often use multiple cloud storage vendors, so they are perplexed when we tell them they need DELETE permissions and/or two buckets for GCS but not for S3/Azure
ii) we service many industries by providing fast transfers of very large files to storage, any storage, including cloud storage. Performance is critical and is in fact a differentiator for our company. So an additional move/copy at the end undoes much of what we are striving to accomplish.

**Comment by coryan** [comment]
I hear the problems, nothing we can do to hide the inherent differences between multi-part uploads and upload+compose in the client library. All we can do is make it easier to work with upload+compose.

> Performance is critical and is in fact a differentiator for our company. So an additional move/copy at the end undoes much of what we are striving to accomplish.

Ack. I would encourage you to test though, because `RewriteObject` does not copy the metadata in many cases.  As I recall if (a) if there are no changes to the encryption key, (b) there are no changes to the location and storage class, then  `RewriteObject` is just a metadata operation.

**Comment by acastruc** [comment]
> nothing we can do to hide the inherent differences between multi-part uploads and upload+compose in the client library

Can you elaborate? i.e. What do you call a multipart upload vs upload+compose ? Are they two different things? In my mind they're the same.  How does google::cloud::storage::ParallelUploadFile() fit in ?

**Comment by coryan** [comment]
> u elaborate? i.e. What do you call a multipart upload vs upload+compose ?

I was drawing a difference between the behavior of S3 vs. GCS.  I am not sure there is an widely recognized name for the current GCS behavior.

> Are they two different things? In my mind they're the same.

Well, in an alternative universe (or some desirable future) GCS could offer an API that behaved exactly like S3 with respect to uploading large files in parts... until then:

> How does google::storage::ParallelUploadFile() fit in ?

An easier way to use multiple uploads and then compose and delete.

**Comment by acastruc** [comment]
Gotcha, thanks

**Comment by coryan** [comment]
I think the questions in this bug report are answered, there is work for the GCS backend team maybe, but this is not the place to track it. Closing.
