### ISSUE TITLE
InsertObject() api is returning error: EasyPerform() - CURL error [52]

### ISSUE THREAD

**Issue by acastruc** [googleapis/google-cloud-cpp#3315]
### Does this issue affect the `google-cloud-cpp` project?
Affect it how? I'm seeing an error, not sure if it's user error or something else.

If the problem is with the service exposed by the `google-cloud-cpp` APIs
instead of the client libraries you may consider opening a support request
instead.  The `google-cloud-cpp` developers cannot help you troubleshoot
problems with the service itself.
Ok. But I cannot tell at this time whether or not this is the case

### What component of `google-cloud-cpp` is this related to?
- Cloud Storage.

### What version of `google-cloud-cpp` are you using?
6430b38
0.11

### What compiler and version are you using?
Apple LLVM version 10.0.0 (clang-1000.11.45.5)

### What operating system and version are you using?
Mac 10.13.6

### What were you trying to do?
I work within a business space that's concerned with transferring large files quickly and securely to destinations such as cloud storage. We maximize upload throughput by multi-part concurrent uploads which are then assembled into the original object. 
The specific scenario that we are investigating here was a 5Gb file broken into 100Mb part files.
(So about 50 parts)

We are using client::InsertObject(...) api for each part.

### What did you expect to see?
Once all part files are uploaded we compose them into the original file. 
Unfortunately we never got that far.

### What did you see instead?
Near the end of the 50 part upload we are seeing
InsertObject returns error
Failed to upload part 46 of files/test/file-5G.dat: Error in non-idempotent operation InsertObjectMedia: EasyPerform() - CURL error [52]=Server returned nothing (no headers, no data) [UNKNOWN]
We see this error for 4 or 5 of the last few parts in flight.

**Comment by acastruc** [comment]
Just FYI I am in the process of upgrading the sdk version to the latest to see if that helps.

**Comment by coryan** [comment]
>
> Ok. But I cannot tell at this time whether or not this is the case

Thank you for filing the bug report.  I think I can assert that this is a bug in `google-cloud-cpp`.

> The specific scenario that we are investigating here was a 5Gb file broken into 100Mb part files.
> (So about 50 parts)

Ack.

> 
> We are using client::InsertObject(...) api for each part.

That makes sense, given the part sizes.

> ### What did you see instead?
>
> Near the end of the 50 part upload we are seeing
> InsertObject returns error
> Failed to upload part 46 of files/test/file-5G.dat: Error in non-idempotent operation InsertObjectMedia: EasyPerform() - CURL error [52]=Server returned nothing (no headers, no data) [UNKNOWN]
> We see this error for 4 or 5 of the last few parts in flight.

It is a bit strange that you got *that* error, but in hindsight the library should handle that as a retryable error (there are some caveats, but not applicable in this case).

I will fix the library to do so, and then I will make another pass through the error codes and see if something else strikes me as retryable.

**Comment by coryan** [comment]
@acastruc I just sent #3316 for review.  I am not sure if you want to apply that patch, or you would rather wait until it is merged (which I expect will happen in a few days), or until the next release (which I expect will happen early next month).

**Comment by acastruc** [comment]
That's great @coryan . 
As for the part size, we originally chose that from comments in [https://github.com/GoogleCloudPlatform/gsutil/blob/master/gslib/commands/config.py](url)

> 'parallel_composite_upload_threshold' specifies the maximum size of a file to
upload in a single stream. 
...
 Setting an extremely low threshold is unadvisable. The vast majority of
 environments will see degraded performance for thresholds below 80M, and it
 is almost never advantageous to have a threshold below 20M.

Of course I'm open to suggestions if this is not the case.

**Comment by coryan** [comment]
> That's great @coryan .
> As for the part size, we originally chose that from comments in [https://github.com/GoogleCloudPlatform/gsutil/blob/master/gslib/commands/config.py](url)

This all looks good.  What I meant is that given a part size of 100 MiB, then using `InsertObject()` is perfectly reasonable, as opposed to `WriteObject()`.

As to the ideal part size, I would think the larger the better, as long as (a) you can afford the memory, and (b) your network does not suffer from a lot of disconnects.  I would use probably 64MiB for the part size, but just because I like round numbers like that.  I would think 1GiB for the part size is too big, and even 512MiB gives me pause. OTOH I grew up counting KiB of RAM in my computers and remain old fashioned that way.

**Comment by coryan** [comment]
@acastruc the PR is merged, please feel free to reopen this bug if it does not help with your problem.
