### ISSUE TITLE
Delimiter support for ListObjects?

### ISSUE THREAD

**Issue by yasushi-saito** [googleapis/google-cloud-cpp#3319]
Objects: list API (https://cloud.google.com/storage/docs/json_api/v1/objects/list) supports the "delimiter" arg to list prefixes ending with that prefix, but I don't see this supported in the C++ SDK. Is there a way to do this?

**Comment by coryan** [comment]
Looks like we completely missed it.  I think I can send a PR today to add it.

**Comment by coryan** [comment]
Thanks for filing this bug report.  I just sent #3320 for review, you have a few options:

- If you want, you can apply that patch to your copy of the code.
- You may want to wait until the code is reviewed and gets merged, that should take a few days.
- You may want to wait until the next release (due early in 2020-02).
