### ISSUE TITLE
V4 Signed URLs support virtual hosted-style URLs

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#3327]
We want `Client::SignUrlV4()` to (**optionally**) create URLs of the form `https://[BUCKET_NAME].storage.googleapis.com/...` as opposed to (the only option today) `https://storage.googleapis.com/[BUCKET_NAME]/...`.

**Comment by frankyn** [comment]
Hi @dopiera, Is there an update on this request?

**Comment by dopiera** [comment]
Hi, still working, almost there.

**Comment by frankyn** [comment]
thanks @dopiera!
