### ISSUE TITLE
V4 Signed URLs support bucket-bound hostnames

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#3328]
GCS supports bucket-bound hostnames:

https://cloud.google.com/storage/docs/request-endpoints#cname

That is, the owners of a domain, say `gcs-subdomain.my.domain.tld`, can create a bucket with the name of this domain (`gcs-subdomain.my.domain.tld`) and they can have GCS serve data from that bucket.

We want `Client::SignUrlV4()` to (**optionally**) create URLs of the form `http://[BUCKET_NAME]/` **or** `https://[BUCKET_NAME]` when the caller explicitly requests such names.

**Comment by frankyn** [comment]
Friendly ping on this request.

**Comment by frankyn** [comment]
@dopiera is this fixed/complete based on your latest PR?

**Comment by dopiera** [comment]
Yes, sorry, for some reason I put a wrong bug number in the PR.
