### ISSUE TITLE
V4 Signed Urls formatting fixes

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#3329]
To increase compatibility with S3 we (maybe) need to make some changes to the code. For each of these either write a test to show that the code is already, or create a separate bug to fix it:

- [x] query parameters should be sorted by Unicode code point, *not* by case insensitive ordering.  Note that C++ typically uses UTF-8, so sorting by bytes should work (see *sorting order* in [UTF-8](https://en.wikipedia.org/wiki/UTF-8))
- [x] Consecutive whitespace characters should be replaced by a single space 
- [x] Query parameters should be URL encoded only once.
- [x] The signed header list must be sorted
- [x] Require that any header starting with `x-goog-` (or `x-amz-`) *is* signed (aka sensitive headers must always be signed).
- [x] If the user provides a `x-goog-content-sha256` header (or `x-amz-content-sha256`) then use that value instead of `UNSIGNED-PAYLOAD` in the signature algorithm.

**Comment by manish-qlogic** [comment]
Conformance test at following location needs to be corrected

https://github.com/googleapis/conformance-tests/blob/1efa0ca5bffd4373c56a69bf73cd3161f0eeae89/storage/v1/v4_signatures.json#L12

The value of `expectedStringToSign` and `expectedCanonicalRequest` are swapped.

Following PR will track this point
https://github.com/googleapis/conformance-tests/pull/23

**Comment by manish-qlogic** [comment]
@coryan 

>Require that any header starting with x-goog- (or x-amz-) is signed (aka sensitive headers must always be signed).

is it fine to interpret  "_sensitive headers must always be signed_" as "_sensitive headers must be part of signed header list_".?

GCS C++ client always keep extension headers in signed header list. So if above interpretation is correct then we do not have any additional work on this task.

**Comment by coryan** [comment]
> @coryan
> 
> > Require that any header starting with x-goog- (or x-amz-) is signed (aka sensitive headers must always be signed).
> 
> is it fine to interpret "_sensitive headers must always be signed_" as "_sensitive headers must be part of signed header list_".?
> 
> GCS C++ client always keep extension headers in signed header list. So if above interpretation is correct then we do not have any additional work on this task.

I think you are correct. I would phrase it slightly different: in the C++ client library it is impossible to have a header that is *not* signed. Therefore this is trivially true for the client library and we can close this bug.
