### ISSUE TITLE
Q: Can we move googleapis BUILD rules into googleapis repo?

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#3340]
We currently define our own C++ build rules for the protos in the googleapis repo. Here's our BUILD file for it: https://github.com/googleapis/google-cloud-cpp/blob/master/bazel/googleapis.BUILD

However, it looks like the googleapis repo has a spot where we could put the C++ build rules right in their BUILD files. See here: https://github.com/googleapis/googleapis/blob/cda99c1f7dc5e4ca9b1caeae1dc330838cbc1461/google/spanner/v1/BUILD.bazel#L373-L376

Is there any reason we shouldn't do this? It seems like it shouldn't be too difficult and may be a good idea to move the build rules for the googleapis proto into that repo.

**Comment by coryan** [comment]
I think the answer is yes, and we have bugs open to do so (#3347)
