### ISSUE TITLE
GCS Resumable Uploads erroneously ABORTED

### ISSUE THREAD

**Issue by wpjohnson** [googleapis/google-cloud-cpp#3342]
Answering these questions before submitting your bug report will help us give
you a quicker answer.  Thank you!

If one or more of these questions are not applicable, feel free to remove them.

### Does this issue affect the `google-cloud-cpp` project?

Yes.

### What component of `google-cloud-cpp` is this related to?

- Cloud Storage.

### What version of `google-cloud-cpp` are you using?

v1.8.0

### What were you trying to do?

Upload objects to GCS via Resumable Upload.

### What did you expect to see?

Objects are uploaded successfully.

### What did you see instead?

Uploads of objects that are exact multiples of the upload chunk size are erroneously `ABORTED` and must be retried.

### Anything else you would like us to know?

When uploading objects of sizes 2MiB, 3MiB, and 4MiB with an upload chunk size of 2MiB, the final chunk upload of only the 4MiB object results in the client library returning:
+ `ABORTED`
+ "Could not continue upload stream. GCS requested byte 0 which has already been uploaded."

The actual response received by the client library is a HTTP 200, which indicates that [the resumable upload is complete](https://cloud.google.com/storage/docs/performing-resumable-uploads#upload-file).

This error message originates from [this PR](https://github.com/googleapis/google-cloud-cpp/pull/3283). Perhaps there is a boundary edge-case which causes this error to be erroneously returned?

**Comment by coryan** [comment]
Thank you for the detailed bug report.  I tried to write an integration test to reproduce this issue, but it seems to work fine.  Do you mind taking a look at it and letting me know what I should be doing differently?

https://github.com/googleapis/google-cloud-cpp/compare/master...coryan:repro-3342?expand=1

> This error message originates from this PR. Perhaps there is a boundary edge-case which causes this error to be erroneously returned?

That sounds possible, but we still need to figure out exactly what it is.

**Comment by wpjohnson** [comment]
Looks like we set `google::cloud::storage::ClientOptions::SetUploadBufferSize` to the same as the chunk size.

Can you try either:
(1) setting the upload buffer size to 2MiB (because it appears the default in these integration tests is 8MiB)
(2) trying to upload objects with sizes that are multiples of 8MiB instead (16MiB, 32MiB)

**Comment by wpjohnson** [comment]
And I think you also need to set the optional [`X-Upload-Content-Length`](https://cloud.google.com/storage/docs/performing-resumable-uploads#initiate-session) header when starting the resumable upload.

With the `X-Upload-Content-Length` header set and uploading an object with a size equal to a multiple of the [`UploadBufferSize`](https://github.com/googleapis/google-cloud-cpp/blob/caaef3af7eb36d51831f70f8d6d151f759454af0/google/cloud/storage/client_options.h#L110-L111), when [`Flush()`](https://github.com/googleapis/google-cloud-cpp/blob/caaef3af7eb36d51831f70f8d6d151f759454af0/google/cloud/storage/internal/object_streambuf.cc#L359-L383) is called for the final chunk it receives an unexpected HTTP 200 response from GCS:

For example, a 40B object:
```http
PUT /upload/storage/v1/b/bucket/o?uploadType=resumable&upload_id=XXX
Content-Range: bytes 20-39/*
Content-Length: 20

<object_data>

HTTP/1.1 200 OK
Content-Type: application/json; charset=UTF-8
Content-Length: 742

<object_metadata>
```

`Flush()` only expects HTTP 308 (or errors) that have a `Content-Range` header, which provides the next expected byte to upload. So it chokes on the HTTP 200 response.

**Comment by wpjohnson** [comment]
This doesn't happen for objects with a size that is not an exact multiple of the `UploadBufferSize` because [`FlushFinal()`](https://github.com/googleapis/google-cloud-cpp/blob/master/google/cloud/storage/internal/object_streambuf.cc#L333-L357) is called for the final chunk upload.

Since the `ObjectWriteStreambuf` doesn't know the total size of the object being uploaded, perhaps it's sufficient to check if the `ResumableUploadSession` is done?

Replace [`Flush()` lines 379-382](https://github.com/googleapis/google-cloud-cpp/blob/master/google/cloud/storage/internal/object_streambuf.cc#L379-L382) with:
```c++
last_response_ = upload_session_->UploadChunk(to_send);
if (!last_response || !IsOpen()) {
  return last_response_;
}
```

**Comment by coryan** [comment]
I think the `X-Upload-Content-Length` does it, I can repro the bug myself.
