### ISSUE TITLE
Storage: V4 Signature Supplying Additional Query Parameters With GCS Signed URLs

### ISSUE THREAD

**Issue by frankyn** [googleapis/google-cloud-cpp#3344]
Tracking issue for work defined in companion document.

[New Client Request - Support For Query Params With GCS Signed URLs](https://docs.google.com/document/d/1PnH2K-M-2wkkYkUyLBh7JDDRqYgBNimP5fUFuEeB4u4/edit#heading=h.xgsgzd636vko)

@coryan I missed this during my first pass of the filed issues for C++.

**Comment by coryan** [comment]
I think this might be covered by `AddQueryParameterOption()` which allows you to add query parameters, but it would be worth writing a test using it.

**Comment by frankyn** [comment]
+1, a test and updating conformance tests. 

Conformance tests need a checkoff on proto spec. GCS team approved them today.
