### ISSUE TITLE
Move googleapis.BUILD to googleapis/googleapis/**/BUILD

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#3347]
The source of truth for these files is inside Google, so we need to make the changes there.

**Comment by coryan** [comment]
Also submit changes to include `google/storage/v1`.

**Comment by devjgm** [comment]
Done. We now use the BUILD rules defined in the http://github.com/googleapis/googleapis repo.

Related: https://github.com/googleapis/google-cloud-cpp/blob/master/bazel/googleapis.BUILD
