### ISSUE TITLE
Proposal: split google-cloud-cpp

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#3350]
## Background

The `google-cloud-cpp` repository has become too large to manage effectively. Some of our customers are only interested in one of the libraries (say the GCS client), and they need to unnecessarily the other libraries and their dependencies. For the library developers, the builds take too long, and changes that affect (or should only affect) the Cloud Bigtable libraries are unnecessarily tested against the Google Cloud Storage libraries and vice-versa.

## Overview

This is a proposal to split `google-cloud-cpp` into four repositories:

* `google-cloud-cpp-bigtable`: will contain (roughly) the code in `google/cloud/bigtable/**` and any supporting CI and/or build scripts.
* `google-cloud-cpp-storage`: will contain (roughly) the code in `google/cloud/storage/**` and any supporting CI and/or build scripts.
* `google-cloud-cpp-firestore`: will contain the code in `google/cloud/firestore/**` and any supporting CI and/or build scripts.
* `google-cloud-cpp`: will contain examples that use more than one `google-cloud-cpp-*` client library, such as `google/cloud/examples/gcs2cbt/**`.

## Project Sequence (with approximate dates)

* Early in 2020-Q2 we will create a new release for `google-cloud-cpp`.
* We will stop adding features to this repository, but will continue to apply bug fixes as needed.
* Soon after this release (we anticipate this will take hours), we will create the new repositories, `google-cloud-cpp-{bigtable,storage,firestore}` with the corresponding contents from `google-cloud-cpp`.
* At this point we will stop fixing bugs in `google-cloud-cpp`, all new features and bug fixes will be implemented in `google-cloud-cpp-{bigtable,storage,firestore}`.
* Simultaneously we will then enable the CI builds for these new repositories, we anticipate that this will take a few days.
* Once the CI builds are working (and passing!) we will create new releases for `google-cloud-cpp-*`.
* The repository release numbers will match the library release numbers.
* The library minor release numbers will be increased, even if no code changes happened as the code was moved.
* Once the new repositories have releases we will remove the code from `google-cloud-cpp/google/cloud/{bigtable,storage,firestore}/**`
* At this point we will cut a new release for `google-cloud-cpp`, this will be the first release without any of the libraries in it. This release will increase the major number for the repository.

## Expected Impact

We know this change impact existing users, but we believe users will be able to migrate to this new scheme with small amounts of effort. We anticipate that **no** changes to the C++ code will be needed. We expect that some changes to the build and/or packaging scripts will be needed.

### Users Downloading from GitHub

We expect that a number of our customers download the source from GitHub and then incorporate the code into their build scripts. Existing releases of `google-cloud-cpp` will continue to work and will have exactly the same contents as before. Therefore, customers that have pinned their scripts to use a release will have **no impact** until such time as they decide to upgrade. Users that download `master` will break immediately, but we hope this is a small number, and that they are cognizant of the risks of depending on a development branch.

#### Changes for CMake Users depending on pre-installed libraries

No changes to their `CMakeLists.txt` files should be needed for these customers. Some changes to their build / installation scripts would be needed at the time they decide to upgrade.

#### Changes for CMake Users with Super Builds

These customers will need to change their top-level `CMakeLists.txt` to add new external projects.

#### Bazel Users

Bazel users will need to change their `WORKSPACE` file to introduce `google-cloud-cpp-bigtable` and/or `google-cloud-cpp-storage` as a new dependency.

### Package Maintainers

Package maintainers that use `google-cloud-cpp` will need to create new packages for `google-cloud-cpp-bigtable`, `google-cloud-cpp-storage`, and `google-cloud-cpp-firestore`. Packaging tools that automatically detect "the latest version" and install from that version will immediately break when we create a new release of `google-cloud-cpp`.

**Comment by devjgm** [comment]
UPDATE: We've decided to we're not going to split this repo. On the contrary, we're going to (re-)combine our already split repos back into this one, creating a single monorepo. See https://github.com/googleapis/google-cloud-cpp/issues/3612 with the details of this plan.
