### ISSUE TITLE
Packages for openSUSE Build Service

### ISSUE THREAD

**Issue by coogor** [googleapis/google-cloud-cpp#3355]
Hi, I have seen that you give build instructions for openSUSE, but I cant find cloud-cpp anywhere on OBS (build.opensuse.org),
As OBS is the build system for all *SUSE Distributions, could you create a project/package there as well and build it?
Thanks!

**Comment by coryan** [comment]
In general we have not created binary packages for any specific distribution. We know folks use binary packages, but there are so many distributions that we could spend all our time just keeping up with them.  Instead, we try to make it as easy as possible for package maintainers to create packages for their favorite distribution.

In short, we would love to do this, but we have many other priorities ahead. Happy to accept PRs to support binary packages for openSUSE or any other distribution.

**Comment by coogor** [comment]
I guess we dont need a PR, 'just' grab the sourcecode, put it on OBS, have a spec file and build the binary. OBS can do this for nearly every distro, from one source file. Thats the big advantage. But as usually, one has to do it....

**Comment by coryan** [comment]
Reviewed on 2021-12-16, we have plans to do more with binary package creation in 2022.

**Comment by coryan** [comment]
We have work scheduled for H2/2022, keep for now.

**Comment by coryan** [comment]
We need to consolidate all these issues around binary packages.  Now scheduled for 2023.

**Comment by coryan** [comment]
Closing in favor of #10039
