### ISSUE TITLE
Create an example of endless streaming for speech-to-text.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#3356]
The [Cloud Speech-to-Text](https://cloud.google.com/speech-to-text) service limits streams to 305 seconds:

https://cloud.google.com/speech-to-text/quotas

There are examples in other languages showing how to implement "endless" or "infinite" streaming:

https://cloud.google.com/speech-to-text/docs/endless-streaming-tutorial

We should write such an example in C++.

**Comment by tumusudheer** [comment]
Hi,

It would be great if this can be along the lines of [streaming_transcribe.cc](https://github.com/GoogleCloudPlatform/cpp-samples/blob/master/speech/api/streaming_transcribe.cc) where one thread is writing the audio to google speech stream while another thread is reading responses from the stream and processing them.
Main complexity is
1. Resetting the stream properly every x seconds
2. synchronizing the stream and other object between multiple threads
3. Make sure audio that is coming while the stream is getting reset does get processed without any loss

May be a pseudo code to start with will be very helpful.

Thank you.

**Comment by devjgm** [comment]
Unassigned, but we still want this.

**Comment by coryan** [comment]
Seems like we will not have time to work on this for the foreseeable future.

**Comment by mohammadkhair7** [comment]
It is key and important to provide such features by Google per the link below. Please work on it and test it well to enable development applications using it.

M. Khair

[> Hi,
> 
> It would be great if this can be along the lines of [streaming_transcribe.cc](https://github.com/GoogleCloudPlatform/cpp-samples/blob/master/speech/api/streaming_transcribe.cc) where one thread is writing the audio to google speech stream while another thread is reading responses from the stream and processing them. Main complexity is
> 
> 1. Resetting the stream properly every x seconds
> 2. synchronizing the stream and other object between multiple threads
> 3. Make sure audio that is coming while the stream is getting reset does get processed without any loss
> 
> May be a pseudo code to start with will be very helpful.
> 
> Thank you.

](https://github.com/googleapis/google-cloud-cpp/issues/3356#issuecomment-579896134)
