### ISSUE TITLE
[Flake]: possible table leak in integration tests

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#3361]
It seems like the integration tests are leaking a table, the name pattern is `tbl-$(date +%s)-${RANDOM}` but I have not researched where exactly is the leak.

We should consider changing the driver script to remove any tables older than X days.

**Comment by mr-salty** [comment]
I like the second thing, it seems like it's possible for tests to fail in a way that they don't clean up regardless.

But, it would be nice to find the actual leak too if this isn't failed cleanup - I propose we ensure any tests that create tables incorporate the test name in the table name for easier identification.

**Comment by coryan** [comment]
We just had this happen again, multiple build failures. I am removing all the tables older than two days:

```
MAGIC_NUMBER=$(date +%s --date='1 day ago')

for table in $(cbt -project cloud-cpp-testing-resources -instance test-instance ls | grep '^tbl-' | awk '{ if ($1 < "tbl-[PUT THE MAGIC HERE]-") { print $1; } }'); do cbt -project cloud-cpp-testing-resources -instance test-instance deletetable $table; sleep 1; done
```

**Comment by devbww** [comment]
> it seems like it's possible for tests to fail in a way that they don't clean up regardless.

Ack, and the closing PR doesn't address this.  But the practical issue should be fixed at least.
