### ISSUE TITLE
Newbie question:   working with gcloud beta emulators datastore

### ISSUE THREAD

**Issue by yxiang92128** [googleapis/google-cloud-cpp#3370]
I have two simple questions:
1. Is "gcloud beta emulators datastore" the correct emulator to work with google-cloud-cpp client library?
2. Is there an additional CLI you are aware of that works with the datastore emulator that can create bucket, and copy data to/from the bucket? Or do I have to write application using google-cloud-cpp to achieve that?   I need a CLI to populate a stress test environment to drive the sdk-based development. 

Many thanks,

Yang

**Comment by coryan** [comment]
> 1. Is "gcloud beta emulators datastore" the correct emulator to work with google-cloud-cpp client library?

Unfortunately not. That is for [Cloud Datastore](https://cloud.google.com/datastore/) a NoSQL database, and `google-cloud-cpp` is for [Cloud Bigtable](https://cloud.google.com/bigtable) (a different NoSQL database) and [Google Cloud Storage](https://cloud.google.com/storage) (GCS) an object storage service.

> 2. Is there an additional CLI you are aware of that works with the datastore emulator that can create bucket, and copy data to/from the bucket?

I am not sure I am parsing this correctly.  Seems like you are looking for an emulator for GCS. There is no official emulator for GCS.  There is a testbench (suitable for tests) in `google-cloud-cpp/google/cloud/storage/testbench` which implements (most) of the GCS REST API.

> Or do I have to write application using google-cloud-cpp to achieve that? 

Other than the testbench mentioned above, `google-cloud-cpp` contains client libraries, I do not think they are a good starting point to implement an emulator.

>  I need a CLI to populate a stress test environment to drive the sdk-based development.

I am not sure I understand.  Are you looking for a CLI to populate GCS instances for testing?  Or a CLI to stress test some SDK?

It is possible I misunderstood your question. If so, please let me know what I missed.

**Comment by yxiang92128** [comment]
Hi, 
thanks for the prompt replies.

I am looking for a CLI to populate the GCS instances and an emulator if possible.  So my take is that 
I can use gsutil to populate the GCS backend and there is no emulator available but a testbench can be used to test the REST APIs.

Thanks,

Yang
