### ISSUE TITLE
cmake questions: generate compile_commands.json and also turn off testing

### ISSUE THREAD

**Issue by svasan** [googleapis/google-cloud-cpp#3381]
### Does this issue affect the `google-cloud-cpp` project?

Project builds but am not able to turn off tests or generate a compile_commands.json 

### What component of `google-cloud-cpp` is this related to?

Build system

### What version of `google-cloud-cpp` are you using?
```
$ git rev-parse HEAD
864b4630e4fba217e7471dbfe3059c0be7ab0824
```

### What compiler and version are you using?

Apple LLVM version 10.0.1 (clang-1001.0.46.4)

```
$ grep COMPILER cmake-out/CMakeCache.txt
CMAKE_CXX_COMPILER:FILEPATH=/Library/Developer/CommandLineTools/usr/bin/c++
CMAKE_C_COMPILER:FILEPATH=/Library/Developer/CommandLineTools/usr/bin/cc
//ADVANCED property for variable: CMAKE_CXX_COMPILER
CMAKE_CXX_COMPILER-ADVANCED:INTERNAL=1
//ADVANCED property for variable: CMAKE_C_COMPILER
CMAKE_C_COMPILER-ADVANCED:INTERNAL=1

$ ls -al /Library/Developer/CommandLineTools/usr/bin/{cc,c++}
lrwxr-xr-x  1 root  admin  5 Sep 16 15:39 /Library/Developer/CommandLineTools/usr/bin/c++ -> clang
lrwxr-xr-x  1 root  admin  5 Sep 16 15:39 /Library/Developer/CommandLineTools/usr/bin/cc -> clang

$ /Library/Developer/CommandLineTools/usr/bin/clang --version
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

```
### What operating system and version are you using?

macOS 10.14.6

### What were you trying to do?

I am trying to generate compile_commands.json by passing CMAKE_EXPORT_COMPILE_COMMANDS flag, and ignore tests using BUILD_TESTING as mentioned in the readme

```
$ cmake -DBUILD_TESTING=OFF -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -Hsuper -Bcmake-out
-- The CXX compiler identification is AppleClang 10.0.1.10010046
-- The C compiler identification is AppleClang 10.0.1.10010046
.....
.....
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    BUILD_TESTING
```
BUILD_TESTING flag seems to be ignored

```
$ cmake --build cmake-out -- -j 8
Scanning dependencies of target c-ares-project
.....
.....
[ 98%] Performing test step for 'google_cloud_cpp_project'
        Start   1: bucket_access_control_test
  1/143 Test   #1: bucket_access_control_test ................................   Passed    0.02 sec
.....
.....
143/143 Test #143: field_path_test ...........................................   Passed    0.01 sec

100% tests passed, 0 tests failed out of 143

Total Test time (real) =  20.64 sec
[100%] Completed 'google_cloud_cpp_project'
[100%] Built target google_cloud_cpp_project
```

```
$ find . -name "compile_commands.json"
# nothing found
$
```
I expected the build to generate a compile_commands.json and not run tests. 

### What did you see instead?

No compile_commands.json was generated. The build also ran the tests.

I'm not sure if I'm missing something or doing something wrong. Any help appreciated. Thanks

**Comment by coryan** [comment]
You are using the super build, and we are not passing those flags down to the sub-projects. Probably we should.

Just to help us understand how folks use the library, do you mind answer a couple more questions?
  * Is your intention to do development for `google-cloud-cpp`?
  * If so, then you probably want to keep testing turned on?
  * If not, then why do you need the `compile_commands.json` file?
  * Are you planning to use the library in a larger super project or something?

**Comment by svasan** [comment]
@coryan  I'm more looking to use the library for something I'm working on and was trying to understand it better. compiler_commands.json was to use with clangd for my current dev setup to navigate/follow code better. 

Based on your comment, I just added the flags to the CMAKE_ARGS in super/CMakeLists.txt which worked. Thanks. 

I'm using the cmake commands from the README and -H was confusing since the help lists that as equivalent to --help but the code looks for -H or -S so I guess it's an older version of -S?

Is this what a "proper" solution to forward args would look like https://stackoverflow.com/questions/12021448/how-can-cmake-arguments-be-forwarded-to-externalproject or is there something simpler?

**Comment by devjgm** [comment]
@svasan FWIW, I develop in this codebase using vim, and I get a `compile_commands.json` file using https://github.com/grailbio/bazel-compilation-database. It does use bazel, but it only needs to be run once (unless you add new files, then it needs to be run again). Then you can continue to build with cmake and use whatever editor you want (well, whichever one understands `compile_commands.json`).

**Comment by svasan** [comment]
@devjgm  That's neat. Thanks for the tip. I haven't used bazel but will try it out.

**Comment by coryan** [comment]
Closing this issue as the questions seem to have been answered.

**Comment by devjgm** [comment]
For posterity, here's the small script I use to generate a `compile_commands.json` file using bazel.

```bash
#!/bin/bash
readonly TMP_DIR="$(mktemp -d "/tmp/bazel-compdb-temp-XXXXXXX")"
cleanup() {
  rm -rf "${TMP_DIR}"
}
trap cleanup EXIT
readonly REPO="https://github.com/grailbio/bazel-compilation-database"
git clone --depth=1 "${REPO}" "${TMP_DIR}"
CC=clang CXX=clang++ "${TMP_DIR}/generate.sh"
```

I run it manually whenever we add new C++ files to our repo (which is to say, not very often).

Also, I'm closing this, because it looks like Carlos accidentally forgot to close it 3 days ago when he commented.
