### ISSUE TITLE
Link RetryPolicy examples from main page.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#3391]
We should link examples like these:

https://github.com/googleapis/google-cloud-cpp/blob/e0c86d4bc8b2cfb08defb07cb37a057e00e3acbd/google/cloud/storage/examples/storage_object_samples.cc#L202-L229

from the landing page.

**Comment by remyabel** [comment]
Is this still relevant? That specific example is already linked:

https://github.com/googleapis/google-cloud-cpp/blob/master/google/cloud/storage/doc/storage-main.dox#L153

Unless you mean change the rest of the document too?

**Comment by coryan** [comment]
You are right, this seems obsolete.
