### ISSUE TITLE
Consider disabling MD5 hashes by default

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#3395]
The MD5 hash seems to be the most CPU intensive part of downloading an object. Considering that some objects do not have a MD5, and we are already computing the CRC32C checksum maybe we should consider disabling this feature by default.

**Comment by coryan** [comment]
Some numbers on the cost of computing MD5s on a n1-standard-16 workstation:

```
Doing md5 for 3s on 16 size blocks: 16673497 md5's in 2.95s
Doing md5 for 3s on 64 size blocks: 10119904 md5's in 2.95s
Doing md5 for 3s on 256 size blocks: 4595456 md5's in 2.98s
Doing md5 for 3s on 1024 size blocks: 1396581 md5's in 2.96s
Doing md5 for 3s on 8192 size blocks: 181017 md5's in 2.85s
Doing md5 for 3s on 16384 size blocks: 94762 md5's in 2.96s
OpenSSL 1.1.1  11 Sep 2018
built on: Tue Nov 12 16:58:35 2019 UTC
options:bn(64,64) rc4(16x,int) des(int) aes(partial) blowfish(ptr) 
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -Wa,--noexecstack -g -O2 -fdebug-prefix-map=/build/openssl-kxN_24/openssl-1.1.1=. -fstack-protector-strong -Wformat -Werror=format-security -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2
The 'numbers' are in 1000s of bytes per second processed.
type             16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
md5              90432.53k   219550.46k   394777.43k   483141.54k   520312.72k   524520.48k
```

This limits the bandwidth on a single core to (approx.) 500MiB/s.  Considering that we can download about 500 MiB/s on a single CPU with curl (which does not compute MD5s or CRC32C):


```
/usr/bin/time curl --libcurl foo.c  -H "Authorization: Bearer $(gcloud auth print-access-token)" https://storage.googleapis.com/cloud-cpp-testing-coryan-8g/object001.bin -o /dev/null 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 8192M  100 8192M    0     0   319M      0  0:00:25  0:00:25 --:--:--  267M
```

The effect is easily measurable using one of our benchmarks:

![tp elapsed-vs-size-local-large mibs](https://user-images.githubusercontent.com/6241635/75204054-d8320600-573d-11ea-9b2f-abbe7ae35bda.png)

## Recommendation

The cost seems excessive, we are spending 1/2 of the CPU for an **additional** hash on top of the CRC32C, and sometimes the server does not even have the MD5 hash.

**Comment by vnvo2409** [comment]
I will work on this issue.
This means We should enable `DisableMD5Hash` option by default ( and add option `EnableMD5Hash` ) or there are more things to consider ?

**Comment by coryan** [comment]
The way these options are implemented is a bit quirky:

https://github.com/googleapis/google-cloud-cpp/blob/2bf8435284b722d44359fca6d4977fe4c908f121/google/cloud/storage/hashing_options.h#L59-L65

The default constructor for this option leaves the option "uninitialized":

https://github.com/googleapis/google-cloud-cpp/blob/2bf8435284b722d44359fca6d4977fe4c908f121/google/cloud/storage/internal/complex_option.h#L41-L57


and the code interprets that "not disabled, therefore enabled".  One possible fix is to change the default constructor for `DisableMD5Hash` to set the option to "true".

**Comment by vnvo2409** [comment]
I am thinking of remove the option `DisableMD5Hash`, disable the md5 check by default in the code and add an option `EnableMD5Hash`. What do you think ?

**Comment by coryan** [comment]
> I am thinking of remove the option `DisableMD5Hash`, disable the md5 check by default in the code and add an option `EnableMD5Hash`. What do you think ?

That I am afraid we cannot do.  We should strive to keep backwards compatibility, removing the option would break user code unnecessarily.  We do break backwards compatibility when needed, but I do not think this change reaches the (somewhat arbitrary, gut-based), threshold.

**Comment by vnvo2409** [comment]
So maybe we should add `EnableMD5Hash` and We will prefer `EnableMD5Hash` over `DisableMD5Hash` when there are 2 options in the same function.
