### ISSUE TITLE
Add logging to the credential refresh RPCs

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#3429]
We need a way to log the credential refresh RPCs, without it, it is really hard to troubleshoot problems with credentials. cf #3426 .

**Comment by kaustubhpatil2611** [comment]
Hello @coryan ,
I would like to take up this issue! Can i work on it?

**Comment by coryan** [comment]
Certainly, feel free to send us a PR. Remember to sign the CLA so we can accept your contribution.

**Comment by coryan** [comment]
Seems like this will be fixed as part of the migration to the `rest-internal` library.

**Comment by coryan** [comment]
@scotthart is working on it
