### ISSUE TITLE
Consider fixing next expected byte calculation in storage Client::UploadStreamResumable

### ISSUE THREAD

**Issue by awkv** [googleapis/google-cloud-cpp#3432]
It seems next expected byte calculation in `Client::UploadStreamResumable` :
`auto expected = session->next_expected_byte() + gcount - 1;`
should be:
`auto expected = session->next_expected_byte() + gcount;`

That would match with `CurlResumableUploadSession::Update()` next expected byte calculation:
`next_expected_ = result->last_committed_byte + 1;`

Please note that wrong next expected byte calculation doesn't affect what the library uploads because later stream pointer is adjusted (actually to the same location):
```
 if (session->next_expected_byte() != expected) {
      GCP_LOG(WARNING) << "unexpected last committed byte "
                       << " expected=" << expected
                       << " got=" << session->next_expected_byte();
      source.seekg(session->next_expected_byte(), std::ios::beg);
    }
```
So expected that fixing calculation will avoid `source.seekg()` on every file chunk.

**Comment by coryan** [comment]
Thanks! I will try to get this scheduled soon.
