### ISSUE TITLE
bigtable: read and filtering sample request

### ISSUE THREAD

**Issue by billyjacobson** [googleapis/google-cloud-cpp#3496]
Can we get samples for reading and filtering data in Bigtable. Like the samples we have here: https://github.com/GoogleCloudPlatform/java-docs-samples/tree/master/bigtable/snippets/src/main/java/com/example/bigtable 

@coryan

**Comment by coryan** [comment]
Sure.  Seems like the first step is to break down this bug in probably one GitHub issue per sample (or one GitHub issue by each logical group).

**Comment by billyjacobson** [comment]
Created separate issues: 

https://github.com/googleapis/google-cloud-cpp/issues/3499
https://github.com/googleapis/google-cloud-cpp/issues/3500
