### ISSUE TITLE
Enable CMake Cache for ci/kokoro/windows

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#3518]
Probably will require testing with clcache, clash and maybe others.

**Comment by coryan** [comment]
A pragmatic solution to this *might* be to simply run the MSVC+CMake builds post-PR **only**.

This has some risks, from time to time the build would break and we would need a followup PR, but worse, most folks are not familiar with MSVC and would have no easy way to "test" their fixes until it gets merged (that is a really long edit+compile+test cycle).

As a workaround (and this is an idea that needs to be tested), maybe we can create a PR build, mark it "disabled" and have folks manually trigger a PR build when they really want to make sure their code works with MSVC+CMake.

A bit complicated in the bad case, but probably quite workable in the common case. And easier than finding a caching solutions for CMake+MSVC, my search-fu has only discovered paying products and open source projects abandoned for 2+ years.

@devjgm thoughts?

**Comment by coryan** [comment]
We decided to disable this build for PRs. Closing.
