### ISSUE TITLE
Cleanup Examples for Bigtable

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#3523]
- [x] Refactor command-line parsing and auto-running to a common library.
- [x] Refactor bigtable_grpc_credentials.cc
- [x] Refactor data_snippets.cc
- [x] Refactor data_async_snippets.cc
- [x] Refactor bigtable_hello_app_profile.cc
- [x] Refactor bigtable_hello_instance_admin.cc
- [x] Refactor bigtable_hello_table_admin.cc
- [x] Refactor bigtable_hello_world.cc
- [x] Refactor bigtable_instance_admin_snippets.cc
- [x] Refactor bigtable_quickstart.cc
- [x] Refactor instance_admin_async_snippets.cc
- [x] Refactor table_admin_async_snippets.cc
- [x] Refactor table_admin_snippets.cc

**Comment by coryan** [comment]
Broke this down into smaller issues, closing.
