### ISSUE TITLE
Cleanup Examples for Storage

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#3524]
This is a rough breakdown, we may want to create separate bugs for some of these steps. We may also want to split some of the larger programs (storage_bucket_samples.cc, storage_object_samples.cc) into smaller ones.

- [x] Refactor command line parsing to a library
- [ ] Refactor `storage_bucket_samples.cc` to have an auto run
- [x] Refactor `run_examples_utils.sh:run_all_bucket_examples()` to `storage_bucket_samples.cc`
- [x] Refactor `run_examples_utils.sh:run_all_service_account_examples()` to `storage_service_account_samples.cc`
- [x] Refactor `run_examples_utils.sh:run_all_requester_pays_examples()` to `storage_bucket_samples.cc`
- [x] Refactor `run_examples_utils.sh:run_all_event_based_hold_examples()` to `storage_bucket_samples.cc`
- [x] Refactor `run_examples_utils.sh:run_all_retention_policy_examples()` to `storage_bucket_samples.cc`
- [x] Refactor `run_examples_utils.sh:run_lifecycle_management_examples()` to `storage_bucket_samples.cc`
- [x] Refactor `run_examples_utils.sh:run_all_bucket_acl_examples()` to `storage_bucket_samples.cc`
- [x] Refactor `run_examples_utils.sh:run_all_default_object_acl_examples()` to `storage_bucket_samples.cc`
- [x] Refactor `run_examples_utils.sh:run_all_object_examples()` to `storage_object_samples.cc`
- [x] Refactor `run_examples_utils.sh:run_upload_and_download_examples()` to `storage_object_samples.cc`
- [x] Refactor `run_examples_utils.sh:run_resumable_file_upload_examples()` to `storage_object_samples.cc`
- [x] Refactor `run_examples_utils.sh:run_resumable_write_object_examples()` to `storage_object_samples.cc`
- [x] Refactor `run_examples_utils.sh:run_rewrite_examples()` to `storage_object_samples.cc`
- [x] Refactor `run_examples_utils.sh:run_rename_examples()` to `storage_object_samples.cc`
- [x] Refactor `run_examples_utils.sh:run_resume_rewrite_examples()` to `storage_object_samples.cc`
- [x] Refactor `run_examples_utils.sh:run_all_public_object_examples()` to `storage_object_samples.cc`
- [x] Refactor `run_examples_utils.sh:run_event_based_hold_examples()` to `storage_object_samples.cc`
- [x] Refactor `run_examples_utils.sh:run_temporary_hold_examples()` to `storage_object_samples.cc`
- [x] Refactor `run_examples_utils.sh:run_object_versioning_examples()` to `storage_object_samples.cc`
- [x] Refactor `run_examples_utils.sh:run_all_cmek_examples()` to `storage_object_samples.cc`
- [x] Refactor `run_examples_utils.sh:run_all_signed_url_v2_examples()` to `storage_object_samples.cc`
- [x] Refactor `run_examples_utils.sh:run_all_signed_url_v4_examples()` to `storage_object_samples.cc`
- [x] Refactor `run_examples_utils.sh:run_signed_policy_document_examples()` to `storage_object_samples.cc`
- [x] Refactor `run_examples_utils.sh:run_all_object_acl_examples()` to `storage_object_acl_samples.cc`
- [x] Refactor `run_examples_utils.sh:run_all_notification_examples()` to `storage_notification_samples.cc`
- [x] Refactor `run_examples_utils.sh:run_all_bucket_iam_examples()` to `storage_bucket_iam_samples.cc`
- [x] Refactor `run_examples_utils.sh:run_static_website_configuration_examples()` to `storage_bucket_samples.cc`
- [x] Refactor `run_examples_utils.sh:run_cors_configuration_examples()` to `storage_bucket_samples.cc`
- [x] Refactor `run_examples_utils.sh:run_mocking_client_examples()` to `storage_client_mock_samples.cc`
- [x] Refactor `run_examples_utils.sh:run_quickstart()` to quickstart builds.

**Comment by coryan** [comment]
I broke down this task into smaller bugs. Closing.
