### ISSUE TITLE
Cache integration test results for CMake

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#3529]
This might be optional.

**Comment by coryan** [comment]
One idea to explore, the documentation says that running CTest with `--rerun-failed` only runs the tests that failed the last time. But not clear if this works well with tests that "changed" or with test filtering (e.g. `-LE integration-tests`).

**Comment by coryan** [comment]
I am going to close this because I think the benefits will be too small to matter. With CMake we run most of the integration tests against the emulators, which takes a few seconds.
If these become a bottleneck we can revisit.
