### ISSUE TITLE
Simplify README.md similar to -spanner/README.md

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#3533]
Rewrite -cpp's README.md and related docs to be "simplified" like -spanner/README.md. This may involve moving some build instructions to another doc, like doc/packaging.md. It should also explain the monorepo layout so that users can find the libraries they need.

https://github.com/googleapis/google-cloud-cpp-spanner/blob/master/README.md

**Comment by coryan** [comment]
See #3604, the README changes and the quickstart changes are somewhat related.
