### ISSUE TITLE
Update the ci/kokoro/readme builds to test the new instructions

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#3534]
Update the ci/kokoro/readme builds to test the new instructions, they use CMake today, will likely use Bazel in the future.
* Alternatively delete them altogether (coryan@ does not like that)
* Optimize the ci/kokoro/readme builds after we decide what their disposition will be.

**Comment by coryan** [comment]
It seems that we need:

- A build for macOS+Bazel for the `quickstart/` directories.
- A build for Windows+Bazel for the `quickstart/` directories.
- A build for macOS+CMake+vcpkg for the `quickstart/` directories.
- A build for Windows+CMake+vcpkg for the `quickstart/` directories.
- A build for Linux+CMake+vcpkg for the `quickstart/` directories.

The ci/kokoro/readme builds only serve to document what is the minimal set of build tools required to compile the code, we can **probably** remove them.

We do not have any coverage to verify the instructions for the *next* release, all the builds for `quickstart/` work against the previous release. This is very unfortunate, and we should think of a workaround, e.g.:

- Create Bazel builds where the `WORKSPACE` file points to the *current* code, maybe just for Linux.
- Create a CMake+vcpkg build with an overlay that somehow (don't know how right now) points to the *current* PR code.

**Comment by coryan** [comment]
I am closing this because I created smaller bugs for each build. I think each one takes between 1/2 day and two days of work.
