### ISSUE TITLE
Make sure refdocs builds can publish docs for -spanner, -pubsub, etc.

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#3541]
Make sure refdocs builds can publish docs for -spanner, -pubsub, etc.

**Comment by tmatsuo** [comment]
When merging a library to g-c-cpp repo, we'll need to make sure the doxygen docs are correctly generated (for example, Spanner build downloads common's tag, but we will not need to do that when merged, but we'll have to set correct flags for common's tag) and tweak the publish-refdocs.sh at: https://github.com/googleapis/google-cloud-cpp/blob/master/ci/kokoro/docker/publish-refdocs.sh

**Comment by coryan** [comment]
It seems this becomes an extra step to perform in the merging PR, we need to change `publish-refdocs.sh` to reference the imported library. I have updated the relevant issues to include this step. I think we can close this.
