### ISSUE TITLE
Make sure we can use one credentials file for all the service

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#3546]
Make sure we can use one credentials file for all the services *or* we switch credentials before running the integration tests for each service

**Comment by coryan** [comment]
I think this is done. The integration tests run using an account with permissions for `Cloud Spanner`, `Cloud Pub/Sub`, `Cloud Storage`, and `Cloud Bigtable`.

We can reopen if we find out I was wrong.
