### ISSUE TITLE
Rename all the CMake targets to be unique with the incoming targets

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#3548]
Rename all the -cpp CMake targets (libraries, tests, benchmarks, examples) to be unique with the incoming targets.
* Remember that CMake target names are in a global namespace

**Comment by coryan** [comment]
I *think* the thing that matters is the target name, not the name of the binary. We can probably prefix the name of the targets with `storage_client` or `bigtable_client` (as the case might be) and leave the binary name untouched.

**Comment by coryan** [comment]
I think this is now fixed. If we do get a collision apply the same technique used in any of the PRs attached to this issue.
