### ISSUE TITLE
Copy code from google-cloud-cpp-spanner

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#3561]
# Moving Spanner code into `-cpp` (a single PR)

## Move the code into `google/cloud/spanner`

Think of this as simply copying the files. But ideally, we'll copy the files over *and* preserve their git history. See https://github.com/googleapis/google-cloud-cpp/issues/3549#issuecomment-614963681 for details about how this was done for `-pubsub`. Once the files are in `-cpp/google/cloud/spanner`, we'll need to make further changes, otherwise the `-cpp` build will break.

After copying the code into `google/cloud/spanner`, the following updates will need to be made:

- [ ] Change `spanner/CMakeLists.txt` to use `../config-version.cmake.in`
- [ ] `rm google/cloud/spanner/config-version.cmake.in`
- [ ] Replace `@com_github_googleapis_google_cloud_cpp_common` in BUILD files, because that code is now locally within `-cpp`.
```
cd google/cloud
perl -p -i -e 's,\@com_github_googleapis_google_cloud_cpp_common,,g' spanner/samples/BUILD spanner/BUILD spanner/integration_tests/BUILD spanner/benchmarks/BUILD
```
- [x] Move/copy over `ci/generate-markdown/generage-spanner-readme.md` and hook it up.

GOAL: Try make preparations in the original repo so that when the code moves into `-cpp`, you can make _zero_ changes to the newly added files in `google/cloud/spanner`. 

## Update top-level `CMakeLists.txt`

Add an option/flag to make building the new dir optional.

## Update files in `ci/...`

grep in `ci/...` for places that mention `bigtable` or `storage` to see where you might need to add an additional configuration for the new `$project` being added. In particular:

* `ci/kokoro/docker/build-in-docker-cmake.sh` has a list of expected directories that get installed, which will likely need to be updated.
* `ci/kokoro/docker/publish-refdocs.sh` has the list of directories that produce documentation.
* `ci/etc/integration-tests-config.*` list the environment variables necessary to run the integration tests and examples.
* `ci/etc/quickstart-config.*` lists the directories with a `quickstart` example and now to invoke that example.
* `ci/kokoro/docker/check-abi.sh` contains the libraries that are GA and for which we want to check that their APIs don't accidentally change. Spanner will need to be added to this list.

## Update top-level README.md

This file should contain a link/reference to the newly added code. This file is probably autogenerated, so be sure to edit the right file(s).

## Quick/local tests

1. Run `build.sh asan`, which will use bazel to build.
1. Run `build.sh clang-tidy`, which will use cmake
1. Run `build.sh integration`

In both cases, try creating a build break in the newly imported code to make sure the build fails. Also try creating a runtime test failure, to make sure the test fails.

Also, create a DRAFT PR and see what the presubmit CI builds say.

**IMPORTANT:** The PR will need to be *merged* and not *squashed* so that the history is preserved. In order to do this, you'll need to allow "merge commits" in the [project's settings](https://github.com/googleapis/google-cloud-cpp/settings) temporarily. Then after the merge, disallow them again.

NOTE: All these steps should go in a single PR.

**Comment by devjgm** [comment]
Re: preserving history, see the notes in https://github.com/googleapis/google-cloud-cpp/pull/3728, which moves `release/` and preserves history.

**Comment by coryan** [comment]
Remember to update the `ci/` scripts as needed, e.g.:

* `ci/kokoro/docker/build-in-docker-cmake.sh` has a list of expected directories that get installed, which will likely need to be updated.
* `ci/kokoro/docker/publish-refdocs.sh` has the list of directories that produce documentation.
* `ci/etc/integration-tests-config.*` list the environment variables necessary to run the integration tests and examples.
* `ci/etc/quickstart-config.*` lists the directories with a `quickstart` example and now to invoke that example.

**Comment by coryan** [comment]
We also need to copy the API baseline from `ci/test-api` and update the `check-abi.sh` script (which needs to be renamed, but that is a separate issue).
