### ISSUE TITLE
Copy code from google-cloud-cpp-common

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#3582]
UPDATED: based on @coryan 's comment below.

... to `google/cloud/*.{h,cc}` so that it lives at the same path as it does in its current repo. Otherwise, callers includes would break.

We should investigate how to preserve history as well when doing this copy.

**Comment by coryan** [comment]
If we import to that directory we need to change *all* the `#include` directives, and our *customers* may need to change theirs.  That seems less than ideal.  I would think the files go to `google/cloud/*.{h,cc}`, which is where they came from.

**Comment by devjgm** [comment]
Good point. Agreed. I updated the original to reflect this.

**Comment by devjgm** [comment]
See this issue with all the steps and details about how we did a similar move for the `-pubsub` repo.
https://github.com/googleapis/google-cloud-cpp/issues/3549

And see this comment for a script on how to move the code with git history. 
https://github.com/googleapis/google-cloud-cpp/issues/3549#issuecomment-614963681

**Comment by coryan** [comment]
I will take a stab at this, wish me luck.

**Comment by coryan** [comment]
- [ ] Need to move the `google/cloud` and `ci/templates/` directories.
- [ ] Need to move `doc/cpp-style-guide.md`.
- [ ] Change all CMake files and Bazel files to compile against the *local* version of `google-cloud-cpp-common`.
- [ ] Change references to `doc/cpp-style-guide.md`
