### ISSUE TITLE
Create new vcpkg

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#3590]
Create new vcpkg packages that references the monorepo as a dependency.

**Comment by coryan** [comment]
This will need to wait until we cut a release of `-cpp`. At that time I need to create a single PR to vcpkg that:

- Updates `g-c-cpp` to the new version, make sure it installs the `-common` library (it should)
- Makes `g-c-cpp-common` an empty package that just depends on `g-c-cpp`, this protects any customers that had `vcpkg install google-cloud-cpp-common` in their scripts.
- Makes `g-c-cpp-spanner` depend on `g-c-cpp`.

**Comment by devjgm** [comment]
Was this done? Or does it need to wait for the June release?

**Comment by coryan** [comment]
I needs to wait for the June release, as soon as we update the `-common` or `-cpp` packages we will break the `-spanner` package. In June I will prepare a PR to update all 3 packages at the same time.

**Comment by coryan** [comment]
Done.
