### ISSUE TITLE
Announce that -spanner will be moving in N days

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#3591]
For Spanner, I think N = 60

We want to give customers a heads up that the -spanner repo will be moving into the monorepo at -cpp. We should cut a release and and include an announcement that this will be happening. We may also want to drop a note in our slack channel and anywhere else we can, like on the README.md.

**Comment by devjgm** [comment]
Tasks:

- [ ] Update https://github.com/googleapis/google-cloud-cpp-spanner/blob/master/README.md to say that `-spanner` is moving into the `-cpp` monorepo and link to https://github.com/googleapis/google-cloud-cpp/issues/3612
- [ ] Include a similar blurb in Spanner's April Release Notes. Tagging @scotthart who will be handling the next Spanner release

**Comment by devjgm** [comment]
Assigning this to @scotthart since he'll do the next announcement.

**Comment by coryan** [comment]
Should we close this?  Seems like we took both steps referenced above?

**Comment by devjgm** [comment]
Yeppers.
