### ISSUE TITLE
Announce that -common will be moving in N days

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#3592]
For Common, I think N = 60 (maybe even 30, but -common has to move after Spanner, so it might as well be 60)

We want to give customers a heads up that the -common repo will be moving into the monorepo at -cpp. We should cut a release and and include an announcement that this will be happening. We may also want to drop a note in our slack channel and anywhere else we can, like on the README.md.

**Comment by devjgm** [comment]
Tasks:

- [ ] Update https://github.com/googleapis/google-cloud-cpp-common/blob/master/README.md to say that `-common` is moving into the `-cpp` monorepo and link to https://github.com/googleapis/google-cloud-cpp/issues/3612
- [ ] Include a similar blurb in Common's April Release Notes. Tagging @scotthart who will be handling the next Common release

**Comment by devjgm** [comment]
Assigning this to @scotthart since he'll do the next announcement.

**Comment by coryan** [comment]
Should we close this?  We already took both steps.

**Comment by devjgm** [comment]
Yes. Thanks for pointing this out.
