### ISSUE TITLE
Make sure .clang-format file is compatible across the repos

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#3596]
We want to make sure all repos are formatted w/ the same `.clang-format` file so that moving code doesn't involve unrelated formatting changes.

**Comment by coryan** [comment]
That was done as part of googleapis/google-cloud-cpp-common#196 Some changes may have sneaked since then, but I doubt it.

**Comment by devjgm** [comment]
That issue brought cmake-format into alignment, but did it also do the same for `.clang-format`? I'm looking at [Spanner's .clang-format file](https://github.com/googleapis/google-cloud-cpp-spanner/blob/master/.clang-format#L12), and it contains the string `"google/cloud/spanner"`, so I'm thinking this .clang-format file cannot work in -cpp. And the [-cpp .clang-format file](https://github.com/googleapis/google-cloud-cpp/blob/master/.clang-format#L12) doesn't sort project-level includes before common includes.

That's what I was referring to in this issue.

**Comment by coryan** [comment]
Ah, yep, I did not do much with those. We might need per-directory `.clang-format` files too, we should see if those work.

**Comment by devjgm** [comment]
I tried per-directory .clang-format files. clang-format stops as soon as it finds a single `.clang-format` file. So we'd need copy the full .clang-format file to each project directory. But see my PR above, with something that generic that I think may work.

**Comment by devjgm** [comment]
We need to do this for the following repos:

- [ ] -cpp
- [ ] -spanner
- [ ] -common
- [ ] -pubsub
- [ ] -bigquery

**Comment by devjgm** [comment]
Done.
