### ISSUE TITLE
Include guards for -spanner start with GOOGLE_CLOUD_CPP_SPANNER_

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#3603]
We may want to fix this in `-spanner` before copying the code or in the PR to copy the code, or we may change the include guard checks to allow the alternative prefix temporarily.

**Comment by devjgm** [comment]
It seems safe and likely easiest to change the `-spanner` include guards to `GOOGLE_CLOUD_CPP_` today so that it matches the include guard pattern used in `-cpp`. That's my plan.
