### ISSUE TITLE
Change to per-repo versioning

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#3615]
# Overview

As described in #3612, this repo is changing to a monorepo that will contain the code for all the Cloud C++ client libraries. Each library will live in a per-library directory, like `google/cloud/$library`. The repo itself will have a version number that corresponds with the versions on the https://github.com/googleapis/google-cloud-cpp/releases page. But each individual library **will not** contain their own version numbers. To be clear (and visually skimmable):

**There will be a single per-repo version number, NOT per-library version numbers.** 

This differs from today where there is a repo version number, and each individual library also has their own version number. For example, today we have:

- Current repo version: [v0.20.0](https://github.com/googleapis/google-cloud-cpp/releases/tag/v0.20.0)
- Current GCS version: [v1.11.x](https://github.com/googleapis/google-cloud-cpp/blob/master/google/cloud/storage/CHANGELOG.md#v111x---2020-03)
- Current Bigtable version: [v1.8.x](https://github.com/googleapis/google-cloud-cpp/blob/master/google/cloud/bigtable/CHANGELOG.md#v18x---2020-02)

All libraries will be assumed to be Generally Available (GA) unless otherwise noted in the `google/cloud/$library/README.md` file.

**Comment by coryan** [comment]
I think until `-common` is merged into the repo we will need to manually sync and keep GCS and Bigtable version numbers. @devjgm if you agree, I can send an initial PR later today.

**Comment by devjgm** [comment]
I'm not sure I understand why we need to wait for `-common` to be merged into this repo. I was thinking that we could, say today, bump the GCS and Bigtable version numbers to say `1.5.0`. Then in our May release of `-cpp`, we'd release the whole repo at version `1.5.0`. That would put the whole repo, and Bigtable and GCS, at version 1.5.0. 

Let me know what I'm misunderstanding.

**Comment by coryan** [comment]
I think you are right, except for a couple of weird places, let me send a PR.
