### ISSUE TITLE
Potential optimization for clang-tidy build

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#3618]
The `clang-tidy` build is not firmly below 20m, which would be ideal before accepting further libraries into `google-cloud-cpp`.  Looking at the logs for one build which took 21m25s I found this:

```
[ID: 2428702] Build finished after 751 secs, exit value: 0


Warning: Permanently added 'localhost' (ECDSA) to the list of known hosts.
[18:25:47] Collecting build artifacts from build VM
[18:32:41] Kokoro builder finished
[18:33:02] Running blaze commands.
[18:33:06] Finished running blaze commands.
[18:33:08] /tmp/workspace/workspace/cloud-cpp/github/google-cloud-cpp/master/docker/clang-tidy-presubmit/artifacts/custom_sponge_config.csv does not exist in the workspace, no custom config value to log
[18:33:16] Updating SpongeV2 invocation.
[18:33:21] Updating ResultStore invocation.
```

Note that the build script completes in about 12m31s, but **after** the script finishes there are roughly 7m spent "Collecting build artifacts".  I suspect this is the same problem as the Windows builds, except that not as bad, removing the `${KOKORO_ARTIFACTS_DIR}` might speed up the builds.

**Comment by devjgm** [comment]
What kind of stuff is in `KOKORO_ARTIFACTS_DIR`? I'm wondering, so we know what type of stuff to remove/keep.

**Comment by coryan** [comment]
First, we already remote this directory for the Windows builds, because it just takes too long to copy in that platform (something to do with our `rsync` works), so most likely it is "safe" to do so.

Having said that, the code is checked out into this directory, and therefore all the build output (e.g. the full `cmake-out/` and `cmake-out/home` directories) are created there too. We might be able to save most of the time if we remove those directories at the end of the build.
