### ISSUE TITLE
Create google/cloud/storage/{README.md,quickstart/}

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#3620]
We want each per-library area to contain its own `README.md` and `quickstart/` area. The build instructions that currently exist in the top-level `README.md` file would be replaced by the instructions in the `google/cloud/storage/quickstart/` folder.

The `google/cloud/storage/README.md` should follow a pattern similar to https://github.com/googleapis/google-cloud-cpp-spanner/blob/master/README.md

The `google/cloud/storage/quickstart/` directory should follow a pattern similar to https://github.com/googleapis/google-cloud-cpp-spanner/tree/master/quickstart

Tasks:
- [ ] Created/updated `google/cloud/storage/README.md`
- [ ] Created `google/cloud/storage/quickstart/`
- [ ] Build scripts test `google/cloud/storage/quickstart/`

**Comment by coryan** [comment]
Note that there is a quickstart program in `google/cloud/storage/examples/storage_quickstart.cc` which is probably suitable for this, it is referenced by the cloudsite documentation too.
