### ISSUE TITLE
Create google/cloud/bigtable/{README.md,quickstart/}

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#3621]
We want each per-library area to contain its own `README.md` and `quickstart/` area. The build instructions that currently exist in the top-level `README.md` file would be replaced by the instructions in the `google/cloud/bigtable/quickstart/` folder.

The `google/cloud/bigtable/README.md` should follow a pattern similar to https://github.com/googleapis/google-cloud-cpp-spanner/blob/master/README.md

The `google/cloud/bigtable/quickstart/` directory should follow a pattern similar to https://github.com/googleapis/google-cloud-cpp-spanner/tree/master/quickstart

Tasks:
- [ ] Created/updated `google/cloud/bigtable/README.md`
- [ ] Created `google/cloud/bigtable/quickstart/`
- [ ] Build scripts test `google/cloud/bigtable/quickstart/`

**Comment by coryan** [comment]
Note that there is a quickstart program in `google/cloud/bigtable/examples/bigtable_quickstart.cc` which is probably suitable for this, it is referenced by the cloudsite documentation too.
