### ISSUE TITLE
Refactor spanner examples to use common example framework

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#3625]
We are introducing a common framework for all the examples in `storage` and `bigtable`, once the code is in a monorepo we should use that for the `spanner` examples too.

**Comment by devjgm** [comment]
JFYI: Since the cloudsite online documentation extracts code snippets from spanner's single samples `.cc` file, we should probably keep everything in a single file for now so we don't break the online documentation.

**Comment by devjgm** [comment]
To avoid breaking the online documentation on the cloud site, we probably want to keep all the examples in the same file. If/when we split them into separate files, we'll need to coordinate w/ tech writers.

**Comment by devjgm** [comment]
We're happy w/ the samples as they are.
