### ISSUE TITLE
Implement escaping in V4 POST policies

### ISSUE THREAD

**Issue by dopiera** [googleapis/google-cloud-cpp#3635]
Policy should be encoded as defined in
https://docs.google.com/document/d/1XYkqJ_pPazkg6NuhRUEl_cReUtzX1DbgvF_jbPzgzog/edit#heading=h.rze9ynrxgv37

**Comment by frankyn** [comment]
@dopiera I believe this can be closed. Is that correct?

**Comment by coryan** [comment]
Yes.
