### ISSUE TITLE
Kokoro random timeouts in the build

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#3645]
It is unclear why. We invoke bazel about 20 minutes into the build
(after fetching dependencies and such), the build reports no progress
and then seems to be killed due to the timeout:

http://sponge2/1d3eb1e7-26f5-4c23-81f9-f097cf98575e

**Comment by coryan** [comment]
Here is another one:

https://source.cloud.google.com/results/invocations/b5b4a117-8d6c-4190-b84a-8a124c2c9688/targets

**Comment by devjgm** [comment]
FWIW, my suspicion from looking at these logs and a number of other flakes on macos is that I think the macos servers are just way overloaded, and sometimes things run super slow and end up timing out. Not sure how best to fix this.

**Comment by coryan** [comment]
This might be similar, only 60m, but also a timeout for lack of progress:

https://source.cloud.google.com/results/invocations/caff63e5-b2e2-4fb2-a079-421e996d8dc6/details

**Comment by coryan** [comment]
This time the build was trying to upload the cache, maybe we can setup a timeout in the script and just not update the cache?

https://source.cloud.google.com/results/invocations/6efb9ea3-f20d-4c98-b430-a9ef67b01bb9

**Comment by coryan** [comment]
https://source.cloud.google.com/results/invocations/5970321a-7773-4acd-b891-1bfc66cece96/targets

**Comment by coryan** [comment]
This time early in the build:

https://source.cloud.google.com/results/invocations/c5501130-6eea-494c-981d-843043e20e96/targets/cloud-cpp%2Fgithub%2Fgoogle-cloud-cpp%2Fmaster%2Fmacos%2Fquickstart-bazel/log

```
[61 / 254] Compiling external/com_google_protobuf/src/google/protobuf/compiler/java/java_enum_lite.cc [for host]; 82s darwin-sandbox ... (4 actions running)


ERROR: Aborting VM command due to timeout of 3600 seconds
```

**Comment by coryan** [comment]
Another one:

https://source.cloud.google.com/results/invocations/93570f7a-7698-4363-8c79-ae6e568031c6

I am following up with the Kokoro team.

**Comment by coryan** [comment]
One more:

https://source.cloud.google.com/results/invocations/06490f04-0c30-4ff5-a8a3-fb941d95e842

**Comment by remyabel** [comment]
Another instance I think:

https://source.cloud.google.com/results/invocations/f73cd1d7-cce7-4d63-b9a9-f1b669b04b50/log
https://source.cloud.google.com/results/invocations/380bc50d-f053-4683-a2ca-a26fa94def66

**Comment by coryan** [comment]
https://source.cloud.google.com/results/invocations/24f24d57-8e0d-49f6-9574-2541fd1d8ad0

**Comment by devbww** [comment]
https://source.cloud.google.com/results/invocations/3cd34422-6186-4d7e-b303-260ca9b77856

**Comment by devjgm** [comment]
https://fusion2.corp.google.com/invocations/52a81017-111b-4e2d-9e3c-f8d1bcff161b/targets/cloud-cpp%2Fgithub%2Fgoogle-cloud-cpp%2Fmaster%2Fmacos%2Fcmake-super/log

I emailed the kokoro team about this.

**Comment by devjgm** [comment]
The kokoro team confirmed that the infrastructure is aging and these timeouts are a result. They are moving to new infrastructure that will hopefully improve the situation.

I don't think there's anything we can really do on our side to address these issues, other than wait.

**Comment by coryan** [comment]
https://source.cloud.google.com/results/invocations/7bc579fb-3fd9-4ee6-a932-f4c364e84428

**Comment by coryan** [comment]
https://source.cloud.google.com/results/invocations/d201ac87-eda3-4a30-a99e-9c7de677d4c0

**Comment by coryan** [comment]
https://source.cloud.google.com/results/invocations/2040b93a-8e42-408b-83b7-cade84ffd66b

**Comment by coryan** [comment]
This time on a PR:

https://source.cloud.google.com/results/invocations/4c650c20-c0b3-4c08-a796-76cd773bcf23/targets

**Comment by coryan** [comment]
https://source.cloud.google.com/results/invocations/71df3b85-893c-49aa-9ce9-ae386bcad641/targets

**Comment by coryan** [comment]
https://sponge2.corp.google.com/a9e6ae19-eac0-4eb0-a14d-21e3a3da0e1c

**Comment by dbolduc** [comment]
https://source.cloud.google.com/results/invocations/a3992313-b14f-4046-9bcf-d700ba10464b/log

**Comment by coryan** [comment]
https://source.cloud.google.com/results/invocations/215dfa36-63ad-45d7-8a30-2aaf23421b68

**Comment by coryan** [comment]
https://source.cloud.google.com/results/invocations/a796e03e-4ec7-45ac-b417-aa904944760b

**Comment by devbww** [comment]
https://source.cloud.google.com/results/invocations/58f972ab-e109-4ca8-81f6-30b10608e054

**Comment by devbww** [comment]
https://source.cloud.google.com/results/invocations/07d4bcbd-a725-4c77-a5ad-f73865b7a9e8

This one well into the build, and on Windows, but fits in with _"infrastructure is aging and these timeouts are a result."_

```
[1677/1797] Building CXX object google\cloud\storage\tests\CMakeFiles\storage_object_compose_many_integration_test.dir\object_compose_many_integration_test.cc.obj

ERROR: Aborting VM command due to timeout of 10800 seconds
```

**Comment by devbww** [comment]
https://source.cloud.google.com/results/invocations/516d6831-d535-4615-a951-9b0aee701589

**Comment by devbww** [comment]
https://source.cloud.google.com/results/invocations/4bfb3f7e-9098-4ef4-afb3-955347588950

**Comment by devbww** [comment]
https://source.cloud.google.com/results/invocations/5e0d7740-2b40-47fb-bfcb-ea8f86bf0ebe

**Comment by coryan** [comment]
https://source.cloud.google.com/results/invocations/a479fd9b-e174-430d-8917-531ae8f0db3f

**Comment by coryan** [comment]
```
ERROR: Aborting VM command due to timeout of 10800 seconds

Warning: Permanently added 'localhost' (ED25519) to the list of known hosts.
```

https://source.cloud.google.com/results/invocations/943c99db-db40-444b-aef4-ed8b0c06ca53

**Comment by coryan** [comment]
```
ERROR: Aborting VM command due to timeout of 3600 seconds

Warning: Permanently added 'localhost' (ED25519) to the list of known hosts.
```

https://source.cloud.google.com/results/invocations/17d9ee06-c286-4aed-ac79-e5c03aa9b722/targets

**Comment by dbolduc** [comment]
https://source.cloud.google.com/results/invocations/15b393ad-d290-43ea-82c3-9fc593d5aff9

**Comment by dbolduc** [comment]
https://source.cloud.google.com/results/invocations/5f342426-0875-4cbd-8c42-2104f8f7bd01

**Comment by coryan** [comment]
https://source.cloud.google.com/results/invocations/627d3a62-0d16-49d7-b7fc-e1e080cb56f6

**Comment by dbolduc** [comment]
here is a windows one: https://source.cloud.google.com/results/invocations/8faf50e9-b50b-43d0-abb9-bb2234a73355/log

**Comment by dbolduc** [comment]
two more windows:
https://source.cloud.google.com/results/invocations/6d97b87e-fc2a-428f-aded-49e0c8321483
https://source.cloud.google.com/results/invocations/ec027a45-6534-45fb-a9b1-be48b565f7b4

**Comment by scotthart** [comment]
macos bazel cache timeout error
https://source.cloud.google.com/results/invocations/80755448-6a3c-4c94-899d-4a38d9901c53

**Comment by coryan** [comment]
FWIW, I think that build has all kinds of problems.  Yes, there are Bazel cache time outs, but that is not what caused the build to fail.  The failure is the compiler crashing further down in the build, which suggests this would be a good candidate for #8325.

<details>
<summary>Compiler crash log</summary>

```
ERROR: /private/var/tmp/_bazel_kbuilder/958e32d54e02d3b435828e68d1d5184e/external/com_google_googleapis/google/cloud/networkmanagement/v1/BUILD.bazel:364:16: Compiling external/com_google_googleapis/google/cloud/networkmanagement/v1/reachability.grpc.pb.cc failed: (Aborted): wrapped_clang_pp failed: error executing command
  (cd /private/var/tmp/_bazel_kbuilder/958e32d54e02d3b435828e68d1d5184e/sandbox/darwin-sandbox/3798/execroot/com_github_googleapis_google_cloud_cpp && \
  exec env - \
    APPLE_SDK_PLATFORM=MacOSX \
    APPLE_SDK_VERSION_OVERRIDE=10.15 \
    GOOGLE_APPLICATION_CREDENTIALS=/tmpfs/src/gfile/kokoro-run-key.json \
    PATH='/Volumes/BuildData/tmpfs/src/github/google-cloud-cpp/ci/lib:/Users/kbuilder/.pyenv/shims:/Users/kbuilder/.rvm/gems/ruby-2.6.3/bin:/Users/kbuilder/.rvm/gems/ruby-2.6.3@global/bin:/Users/kbuilder/.rvm/rubies/ruby-2.6.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/kbuilder/.rvm/bin:/Users/kbuilder/.rvm/bin' \
    XCODE_VERSION_OVERRIDE=12.0.1.12A7300 \
    ZERO_AR_DATE=1 \
  external/local_config_cc/wrapped_clang_pp '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -O0 -DDEBUG '-std=c++11' 'DEBUG_PREFIX_MAP_PWD=.' -iquote external/com_google_googleapis -iquote bazel-out/darwin-fastbuild/bin/external/com_google_googleapis -iquote external/com_google_protobuf -iquote bazel-out/darwin-fastbuild/bin/external/com_google_protobuf -iquote external/zlib -iquote bazel-out/darwin-fastbuild/bin/external/zlib -iquote external/com_github_grpc_grpc -iquote bazel-out/darwin-fastbuild/bin/external/com_github_grpc_grpc -iquote external/com_google_absl -iquote bazel-out/darwin-fastbuild/bin/external/com_google_absl -Ibazel-out/darwin-fastbuild/bin/external/com_google_protobuf/_virtual_includes/descriptor_proto -Ibazel-out/darwin-fastbuild/bin/external/com_google_protobuf/_virtual_includes/any_proto -Ibazel-out/darwin-fastbuild/bin/external/com_google_protobuf/_virtual_includes/duration_proto -Ibazel-out/darwin-fastbuild/bin/external/com_google_protobuf/_virtual_includes/empty_proto -Ibazel-out/darwin-fastbuild/bin/external/com_google_protobuf/_virtual_includes/field_mask_proto -Ibazel-out/darwin-fastbuild/bin/external/com_google_protobuf/_virtual_includes/timestamp_proto -isystem external/com_google_protobuf/src -isystem bazel-out/darwin-fastbuild/bin/external/com_google_protobuf/src -isystem external/zlib -isystem bazel-out/darwin-fastbuild/bin/external/zlib -isystem external/com_github_grpc_grpc/include -isystem bazel-out/darwin-fastbuild/bin/external/com_github_grpc_grpc/include -isystem external/com_github_grpc_grpc/src/core/ext/upb-generated -isystem bazel-out/darwin-fastbuild/bin/external/com_github_grpc_grpc/src/core/ext/upb-generated -isystem external/com_github_grpc_grpc/src/core/ext/upbdefs-generated -isystem bazel-out/darwin-fastbuild/bin/external/com_github_grpc_grpc/src/core/ext/upbdefs-generated -MD -MF bazel-out/darwin-fastbuild/bin/external/com_google_googleapis/google/cloud/networkmanagement/v1/_objs/networkmanagement_cc_grpc/reachability.grpc.pb.d '-frandom-seed=bazel-out/darwin-fastbuild/bin/external/com_google_googleapis/google/cloud/networkmanagement/v1/_objs/networkmanagement_cc_grpc/reachability.grpc.pb.o' -isysroot __BAZEL_XCODE_SDKROOT__ -F__BAZEL_XCODE_SDKROOT__/System/Library/Frameworks -F__BAZEL_XCODE_DEVELOPER_DIR__/Platforms/MacOSX.platform/Developer/Library/Frameworks '-mmacosx-version-min=10.15' -no-canonical-prefixes -pthread -DGRPC_BAZEL_BUILD -DGRPC_BAZEL_BUILD -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -target x86_64-apple-macosx -c bazel-out/darwin-fastbuild/bin/external/com_google_googleapis/google/cloud/networkmanagement/v1/reachability.grpc.pb.cc -o bazel-out/darwin-fastbuild/bin/external/com_google_googleapis/google/cloud/networkmanagement/v1/_objs/networkmanagement_cc_grpc/reachability.grpc.pb.o)
# Configuration: d815d16f97a848692644e4066c244c793cae13d41cb38573cd9770b0c10020c6
# Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox
clang++: error: unable to execute command: Segmentation fault: 11
clang++: error: clang frontend command failed due to signal (use -v to see invocation)
Apple clang version 12.0.0 (clang-1200.0.32.2)
Target: x86_64-apple-macosx
Thread model: posix
InstalledDir: /Applications/Xcode_12.0.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
clang++: note: diagnostic msg: PLEASE submit a bug report to http://developer.apple.com/bugreporter/ and include the crash backtrace, preprocessed source, and associated run script.
clang++: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang++: note: diagnostic msg: /var/folders/zd/yrv0rx2d6n305sntp8vv5n8h0000gn/T/reachability-5950c2.cpp
clang++: note: diagnostic msg: /var/folders/zd/yrv0rx2d6n305sntp8vv5n8h0000gn/T/reachability-5950c2.sh
clang++: note: diagnostic msg: Crash backtrace is located in
clang++: note: diagnostic msg: /Users/kbuilder/Library/Logs/DiagnosticReports/clang++_<YYYY-MM-DD-HHMMSS>_<hostname>.crash
clang++: note: diagnostic msg: (choose the .crash file that corresponds to your crash)
clang++: note: diagnostic msg:

********************
Error in child process '/usr/bin/xcrun'. 254
```

</details>


In addition the VM running the build also seems to have been terminated:

```
google/cloud/datacatalog/v1/policytagmanagerserialization.proto:23:1: warning: Import google/iam/v1/policy.proto is unused.

Server terminated abruptly (error code: 14, error message: 'Socket closed', log file: '/private/var/tmp/_bazel_kbuilder/958e32d54e02d3b435828e68d1d5184e/server/jvm.out')

2022-02-21T15:56:55Z (+392s): build script reported errors.
2022-02-21T15:56:55Z (+392s): cleaning up artifacts.
rm -rf /tmpfs/src/github/google-cloud-cpp/cmake-out


[ID: 5249186] Build finished after 393 secs, exit value: 1
```

**Comment by coryan** [comment]
90d without repeats, closing.
