### ISSUE TITLE
Support BoringSSL

### ISSUE THREAD

**Issue by DimanNe** [googleapis/google-cloud-cpp#3693]
### Does this issue affect the `google-cloud-cpp` project?
Yes

### What component of `google-cloud-cpp` is this related to?
- CMakeLists.txt

### What version of `google-cloud-cpp` are you using?
v0.21.x branch

### What operating system and version are you using?
Kubuntu 20.04

### What were you trying to do?
I have a monorepo with all libraries and dependencies, including `boringssl`. (If you are interested, I have this structure because I want to be able to build everything with various clang sanitisers).

When I try to configure `google-cloud-cpp` it says that it cannot find OpenSSL...

The problem is that OpenSSL is hardcoded in its `google-cloud-cpp/google/cloud/storage/CMakeLists.txt`:
```
target_link_libraries(
    storage_client
    PUBLIC google_cloud_cpp_common
           nlohmann_json
           Crc32c::crc32c
           CURL::libcurl
           Threads::Threads
           OpenSSL::SSL
           OpenSSL::Crypto
           ssl
           crypto
           ZLIB::ZLIB
    PRIVATE storage_common_options)
```

### What did you expect to see?
I would expect it to reuse already exported/configured targets of BoringSSL.

**Comment by coryan** [comment]
Generally, you are trying to use CMake for something that it is not great at.  CMake is good at finding what is installed on your workstation and using those libraries. You. are trying to do *exactly* the opposite, you want CMake to use the libraries that you compiled, and *avoid* any libraries installed in your workstation. Consider using Bazel for a build like this.

> I would expect it to reuse already exported/configured targets of BoringSSL.

What does BoringSSL calls itself? What targets does it generate?  Maybe we can switch the CMake files to detect BoringSSL as an alternative, but this won't be a high priority for us.

> The problem is that OpenSSL is hardcoded in its `google-cloud-cpp/google/cloud/storage/CMakeLists.txt`:

Hmm... *technically* the `OpenSSL::SSL` *target* could point to anything, you could create something like:

```
add_library(OpenSSL::SSL INTERFACE)
target_link_libraries(OpenSSL::SSL BoringSSL)
```

But there might be some additional incantations required to keep CMake from getting confused.

**Comment by DimanNe** [comment]
I would be glad to switch over to Bazel, if IDEs supported it (in particular QtCreator)...
But anyway, thank you for your suggestions!

**Comment by coryan** [comment]
Closing for now, if there is more demand we can reconsider.
