### ISSUE TITLE
Change quickstart/BUILD files to use top-level build targets

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#3703]
See https://github.com/googleapis/google-cloud-cpp/pull/3702

We want the `google/cloud/*/quickstart/BUILD` files to reference the bazel build targets that are defined in the top-level BUILD file. However, they cannot do this until that top-level BUILD file is included in a release.

**Comment by coryan** [comment]
I have moved this to the post-monorepo cleanups, it is distracting in the current milestone and not actionable.

**Comment by devjgm** [comment]
SGTM. For future us, this is only waiting for any new release of `-cpp`. So anytime after the May release this could be done.
