### ISSUE TITLE
Consider new source directory structure

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#3719]
As we move this repo to a monorepo (#3612), we'll be moving more non-source stuff into the `google/cloud/*/` directories. For example, we'll have stuff like:

**TODAY**
```
README.md
CHANGELOG.md
...
google/cloud/storage
    |- README.md
    |- foo.h
    |- foo.cc
    |- examples/
    |- ci/
    |- doc/
    |- quickstart/
    ...
``` 
This has the actual source code and non-source code artifacts living along side each other, with no clear dividing line or structure.

After we move to a monorepo, we might want to consider re-arranging the per-library files into a structure more like the following:

**PROPOSED**
```
README.md
CHANGELOG.md
libraries/
    |- bigtable/
    |- firestore/
    |- spanner/
    |- storage/
        |- README.md
        |- docs/
        |- ci/
        |- examples/
        |- quickstart/
        |- src/
            |- foo.h
            |- foo.cc
```

You probably get the picture.

I think we can make these changes without breaking any callers or builds. The code would all still get installed in the same places as it does today. And as long as our bazel users are using our top-level BUILD file, their build targets should not be broken either.

Something for us to consider.

**Comment by devjgm** [comment]
Using a directory structure like this may enable us to allow bazel users to use angle-bracket includes. See https://github.com/googleapis/google-cloud-cpp-spanner/issues/1424 for more details about this particular issue.

**Comment by coryan** [comment]
Where is `google/cloud/storage/client.h` in the proposed structure?  What is the full path?  How does one `#include` the file from other code (examples, unit and integration tests)?

**Comment by devjgm** [comment]
The source directory structure is independent of the installed directory structure. The installed structure would look the same in `/usr/local/include` or something like that. But within our repo, the location of that file might be `<reporoot>/libraries/storage/src/google/cloud/storage/client.h` Or perhaps more simply just `<reporoot>/libraries/storage/src/client.h`

**Comment by coryan** [comment]
> The source directory structure is independent of the installed directory structure.

Ideally yes, in practice it is more work to make that work and not worth the trouble.

> The installed structure would look the same in `/usr/local/include` or something like that.

I think we should not change that.  Where the header files live (their names, their path relative to $PREFIX) is part of the contract.  Changing that is a lot of work for folks we better have a good reason to make such a change.

> But within our repo, the location of that file might be `<reporoot>/libraries/storage/src/google/cloud/storage/client.h`

That would work, a bit tedious don't you think?

> Or perhaps, if we can make this work, just `<reporoot>/libraries/storage/src/client.h`

Making that work would require either (a) a more complicated build process that recreates the install structure before building, or (b) an install process that changes the `#includes` from `#include "storage/src/client.h"` to `#include "google/cloud/storage/client.h"`, or (c) change all the includes to be relative, so once the application finds the first header the other headers are found via "./internal/foo.h" and so forth.

**Comment by devjgm** [comment]
> > The source directory structure is independent of the installed directory structure.
> 
> Ideally yes, in practice it is more work to make that work and not worth the trouble.
> 
> > The installed structure would look the same in `/usr/local/include` or something like that.
> 
> I think we should not change that. Where the header files live (their names, their path relative to $PREFIX) is part of the contract. Changing that is a lot of work for folks we better have a good reason to make such a change.

Agreed. I, and this issue, are not proposing anything that would affect installed locations or breaking any contract that would affect users. I'm only talking about the location of files _within this repo_.

> 
> > But within our repo, the location of that file might be `<reporoot>/libraries/storage/src/google/cloud/storage/client.h`
> 
> That would work, a bit tedious don't you think?

Tedious? Why? I don't follow.

> 
> > Or perhaps, if we can make this work, just `<reporoot>/libraries/storage/src/client.h`
> 
> Making that work would require either (a) a more complicated build process that recreates the install structure before building, or (b) an install process that changes the `#includes` from `#include "storage/src/client.h"` to `#include "google/cloud/storage/client.h"`, or (c) change all the includes to be relative, so once the application finds the first header the other headers are found via "./internal/foo.h" and so forth.

I believe doing this is pretty easy with bazel. But if it's difficult w/ cmake, then I'm happy to forget this. That's why I mentioned the "if we can do this" part. This is a very minor point. I'd be totally happy with `<reporoot>/libraries/storage/google/cloud/storage/client.h` (notice here I dropped the `src` component; we could keep that or drop it, doesn't matter).

**Comment by devjgm** [comment]
This would be a breaking change, and not worth doing on its own.
