### ISSUE TITLE
Consider requiring CMake>=3.15 to simplify quickstarts

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#3729]
I am about to add some CMake nastiness to handle static vs. dynamic MSVC runtimes in the quickstart CMake files.

If we were to require CMake >= 3.15 for the quickstart guides (which maybe it is reasonable), we can simplify all of this using:

https://cmake.org/cmake/help/v3.15/variable/CMAKE_MSVC_RUNTIME_LIBRARY.html#variable:CMAKE_MSVC_RUNTIME_LIBRARY

**Comment by devjgm** [comment]
I think using a newer CMake in the quickstart is reasonable, especially if it simplifies the example for customers.

**Comment by coryan** [comment]
It is complicated... We cannot simply say `cmake_minimum_required(3.15)` because that breaks the build for older Linux distros. And if we say `cmake_minimum_required(3.5)` we get the *behavior* from 3.5 (i.e. no support for `CMAKE_MSVC_RUNTIME_LIBRARY`).

The solution I am coming up with is to ask Windows users to override the policy on the command-line, which is not awesome, but at least it works.  It might be worse that before though, we can discuss that in the review.
