### ISSUE TITLE
Rename the bazel-dependency build

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#3735]
The bazel-dependency build in ci/kokoro/docker really is testing the quickstart builds for Linux+Bazel.

It seems like the name should be something more descriptive, like `quickstart-bazel`.

**Comment by devjgm** [comment]
Notes from @coryan 
> I normally do such things in this sequence: (1) create a new build on GitHub called quickstart-bazel, (2) enable the continuous build for that in google3, (3) troubleshoot in case I broke something, (4) enable the pre-submit build in google3 and remove the old build in google3, (5) remove the old build from GitHub.
