### ISSUE TITLE
Best way/library to connect to Cloud SQL > MySql instance using cpp

### ISSUE THREAD

**Issue by tumusudheer** [googleapis/google-cloud-cpp#3741]
### Does this issue affect the `google-cloud-cpp` project?

No

### What component of `google-cloud-cpp` is this related to?

- Cloud SQL

### What operating system and version are you using?

Ubuntu 18.04

### What were you trying to do?

If possible, produce a recipe for reproducing the problem.

Hi,

I'm looking for best library to use to connect to Cloud SQL > MySql instance ?  I found libraries for Bigtable and big query but not for cloud sql. May I know  if I can use any existing library to use ? Or what are the best recommenced ways to connect to cloud sql>  mysql instance using c++ ?

Thank you, Any assistance / suggestions are well appreciated.

**Comment by coryan** [comment]
Sorry, no experience with Cloud SQL and C++ yet.  AFAIK, Cloud SQL should work with any C++ library for MySql?  You may want to check stackoverflow or the `#cloudsql` channel at googlecloud-community.slack.com

**Comment by coryan** [comment]
After 2 weeks I assume the answer above is enough. Feel free to reopen if you have specific questions about this repository.
