### ISSUE TITLE
New feature: consider Drive API support

### ISSUE THREAD

**Issue by awkv** [googleapis/google-cloud-cpp#3748]
Consider supporting Drive API in storage. As far as I know there is no official c++ library for it. So that will be well appreciated. Drive API could share a lot with existing GCS client library.

**Comment by devjgm** [comment]
Thanks for the feature request. It's helpful for us to know which APIs customers actually want.

I believe the Drive API for other languages is purely auto-generated. We don't yet have an auto generator for C++, but we do plan to work on that in the coming months. While I can't promise anything about the Drive API specifically, once we have an auto generator for C++, I imagine it'll be much easier to add C++ support for lots of Google APIs.

In the meantime, I'll keep this FR open to let others thumbs-up if they want.

**Comment by awkv** [comment]
> It's helpful for us to know which APIs customers actually want.

Please take a look at [this header](https://github.com/awkv/cloudstorageapi/blob/master/include/cloudstorageapi/cloud_storage_client.h).
This is what I came up with after reviewing several cloud storages. Please note it is work in progress but you will get an idea.

**Comment by coryan** [comment]
Maybe revisit once we have generated more GCP libraries.

**Comment by coryan** [comment]
We will revisit once we have the generator for REST APIs.

**Comment by coryan** [comment]
Still working on the REST APIs.
