### ISSUE TITLE
`InstanceAdmin::ProtoToWrapper` needs cleanup.

### ISSUE THREAD

**Issue by manish-qlogic** [googleapis/google-cloud-cpp#3756]
function [`InstanceAdmin::ProtoToWrapper`](https://github.com/googleapis/google-cloud-cpp/blob/df9fc191b90985c9fd76abe19200bbc6ff684a34/google/cloud/bigtable/instance_admin.cc#L1087) is still referring to `Protobuf (3.9.1)` where as `bigtable` is currently using the newer version of `Protobuf`.

**Comment by amitchauhan1007** [comment]
The function should remain as-is until we use protobuf >= v3.8.0-rc1 everywhere

**Comment by coryan** [comment]
Thanks for figuring that out.

**Comment by amitchauhan1007** [comment]
Following are my findings:
- For all builds using protobuf version g.e.(>=) v3.8.0-rc1, function "GetReflection" has been declared as static and thus needs to be accessed through static call. For all previous protobuf versions, the function call has to be object based as it is non-static.
- Current Docker build "ci-fedora-install-31-clang-tidy" has been using protobuf version 3.6.1 and hence function GetReflection is accessed through a non-static way.
- CMake build has been using protobuf version 3.11.3 and hence the function "GetReflection" has been declared as static.
