### ISSUE TITLE
use service account in samples where possible

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp#3757]
Branched this discussion off from #3749

@coryan:

In my changes I have cleaned up the use of `allAuthenticatedUsers` in favor of a service account (removes a small window when new objects are basically public), but that is completely optional, we can do it in a future cleanup.

@mr-salty:

I was using`storage_bucket_acl_samples.cc` as a reference and originally used `entity` for the Update/Patch/Delete tests like we do there, but the tests were failing, and I saw the `.sh` used `allAuthenticatedUsers` for all the cases, so I changed these back to `allAuthenticatedUsers` as well (and missed some cleanup). 

I took another look at why it wasn't working, and I see the `UpdateBucketAcl` example works differently than `UpdateDefaultObjectAcl` in that it doesn't do a "Get" first (which fails).  Or should *all* of these use the service account? Note `storage_bucket_acl_samples` still uses `allAuthenticatedUsers` in some cases.

**Comment by mr-salty** [comment]
I intended this to apply to all the samples, but maybe a bug per sample makes more sense?  I opened #3763 for the default object samples, @coryan do we need any others?

**Comment by coryan** [comment]
Ooops, sorry. I think that is the other sample, and I looked around in case my recollection was off.
