### ISSUE TITLE
CreateBazelConfig.cmake should use relative paths

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#3766]
There's a difference in the `CreateBazelConfig.cmake` file between `-bigquery` and `-cpp`. In `-bigquery` it uses relative paths (https://github.com/googleapis/google-cloud-cpp-bigquery/blob/c510df5eedfeea6554bf1232d751daf140ff63ad/cmake/CreateBazelConfig.cmake#L62-L76). But in `-cpp` it uses absolute paths.

I think we want the version from `-bigquery` using relative paths.

**Comment by coryan** [comment]
@devjgm is this the bug you are fixing in #3781 ?

**Comment by devjgm** [comment]
Yes. I forgot I filed this issue. I updated the PR to mark this as fixed.
