### ISSUE TITLE
ObjectMetadata error EasyPerform()

### ISSUE THREAD

**Issue by verdiereNicolas** [googleapis/google-cloud-cpp#3770]
Hello,

### Does this issue affect the `google-cloud-cpp` project?
No, i have a problem with a functionality.
I create a project with QtCreator.

### What component of `google-cloud-cpp` is this related to?

- Cloud Firestore (commnunity supported).

### What version of `google-cloud-cpp` are you using?

I used the latest version. 

### What compiler and version are you using?
I used gcc version 7.5.0.

### What operating system and version are you using?

I worked with ubuntu ~18.04 and Qt-creator 4.11.1 

### What were you trying to do?

I try to read my bucket. I can create a client with my json.
 
### What did you expect to see?
I will to see the same result like this command: `gsutil cp gs://bucket *.pdf`

### What did you see instead?

But when i  used `StatusOr<gcs::ObjectMetadata> object_metadata = client->GetObjectMetadata(bucket_name,object_name );` i received this error what():  

> Permanent error in GetObjectMetadata: EasyPerform() - CURL error [60]=SSL peer certificate or SSH remote key was not OK [UNKNOWN]

### Anything else you would like us to know?
I have follow your readme for install this package.
I move on the file for used function in my project.
Before i have used my project and all functionality works.
But i have a problems with my computer and i reinitialized it.

Thanks you.

**Comment by coryan** [comment]
> Permanent error in GetObjectMetadata: EasyPerform() - CURL error [60]=SSL peer certificate or SSH remote key was not OK [UNKNOWN]

The most likely cause for that (as you point out below) is that you are missing the certificates needed by libcurl.

- Is the the `ca-certificates` package installed on your machine?
- Are you using a super build (`cmake -Hsuper -B...`)?

**Comment by verdiereNicolas** [comment]
Thanks for helping.
ca-certificates is al-ready install.
Yes i used cmake -Hsuper for super build.

**Comment by coryan** [comment]
Okay, your ${BINARY_DIR} (whatever you passed the `-B` flag) should have a `external/bin/curl-config` program installed.  In my case I used `.build`, and I was able to run it using:

```
.build/external/bin/curl-config --ca
```

That will output the name of the Certificate Authority file picked by libcurl (the version of `libcurl` actually compiled as part of the super build).

Does that file exist?
Has it been updated recently?

If the answer to either is "no", then that is likely the problem.  You should consider rebuilding that file with something like `update-ca-certificates` though the program name to perform the update may be different in your system.

**Comment by verdiereNicolas** [comment]
Thank you for your help.
But now i work with other function.
I come back later on this error.

**Comment by DimanNe** [comment]
I have the same issue:
```
W0502 09:53:07.994941 330692 ... Permanent error in GetObjectMetadata: EasyPerform() - CURL error [16]=Error in the HTTP2 framing layer [UNKNOWN]
```
I am using `google-cloud-cpp` built from sources. What is strange, is that the error is **intermittent**. In the app I am uploading a bunch of files (~2GiB) to Google Cloud storage, and 3 uploads are successful, then 4 failures for 4 different files, then 2 successful uploads and so on...

**Comment by coryan** [comment]
Closing for now, feel free to reopen when you get back to this and/or you have more information.
