### ISSUE TITLE
Read objects in to existing memory

### ISSUE THREAD

**Issue by spnshah** [googleapis/google-cloud-cpp#3782]
### What component of `google-cloud-cpp` is this related to?
- Cloud Storage.

### What version of `google-cloud-cpp` are you using?
52b4edc0650ce272c939838f4affd7480186a7b4

### What compiler and version are you using?
gcc version 5.3.1 20160301 [gcc-5-branch revision 233849] (SUSE Linux)

### What operating system and version are you using?
SUSE Linux Enterprise Server 12 SP3

### What were you trying to do?
Trying to use an existing pre-allocated buffer and read objects in that buffer without using any new memory. This is in context with the read object operation and to make ObjectReadStream use an existing memory and not create a new one.

### What did you expect to see?
Use existing buffer and not have ReadObject create a new one. A way to pass in pre-allocated buffer (void*) to either ReadObjects, or somehow have ObjectReadStream created from a buffer.

### Anything else you would like us to know?
Tried couple of cast (void* to stream) experiments and ObjectReadStream.rdbuf()->pubsetbuf() but no success so far.

**Comment by coryan** [comment]
I assume you are trying to avoid data copies?  In general, using `.read()` will do that, e.g.:

```
auto reader = client.ReadObject(....); // copies a small buffer (about 128KiB)
std::vector<char> buffer(4 * 1024 * 1024);
// copies directly into `buffer` as data is received and decrypted:
reader.read(buffer.data(), buffer.size());
```

Does that answer your question?

**Comment by spnshah** [comment]
I was actually trying to avoid the memory creation that happens within `client.ReadObject()` for, I guess `std::basic_istream<char>` because I have a pre-allocated buffer already and was looking for some ways to have `ReadObject` (or some other method) fill that buffer directly rather then have it go to the `stream` or `reader`.

Example (which doesn't work of course):
```
void *buf;  //Memory allocated already.
unsigned int bufSize;  //Length of buf.
stream->rdbuf()->pubsetbuf(static_cast<char*>(buf), bufSize); //Pointing stream to an already allocated buffer, something like this.
stream = client.ReadObject(bucketName, objectName);
```

**Comment by coryan** [comment]
I am not sure how that would work.  `ReadObject()` needs to create an object, which needs the buffer and has no knowledge of what you did to `stream` (which has not been initialized yet).

I guess we could provide an option where you pass on a buffer for `ReadObject()` to use, maybe something like:

```
auto stream = client.ReadObject(bucket_name, object_name, gcs::Buffer(std::move(my_buffer))));
```

But that has very limited value: you would be saving a nanoseconds in an operation that takes dozens of milliseconds to execute. Admittedly a lot of that is waiting for I/O, even so, there are far more expensive operations going on in that request: our measurements show that decrypting the data and performing MD5 hashes are the main CPU users, not memory allocations, and not data copying (though this is not trivial and thus the recommendation above on how to avoid as much as possible).

Maybe you can tell us more about why you are trying to do this? Maybe I misunderstand the use-case and tradeoffs involved?

**Comment by spnshah** [comment]
Thank you Carlos for that information, I will re-evaluate if that request is buying me anything. 

Also, in the above example, I forgot to mention that `buf` is already allocated and initialized.

I will be having a case where we are downloading gigabytes of data in parallel from cloud and if that operation creates its own new memory for streams, that might add up quickly to make a difference. My restriction is that, I already have a buffer to be used for streams for reading object and I don't want to discard/ignore it. And with `auto stream = client.ReadObject()`, my understanding is that a new different memory is being allocated to/for `stream` (please correct me if I am wrong here) and the existing memory(`buf`) is kind of unused. Then we have to `read()` the `stream` in to the `buf`, which will involves data copy. To my knowledge AWS and Azure SDKs has ways to avoid new memory creation and data copy and hence I was trying to investigate if something similar is available from Google. 

I think I am okay for now but will approach again if we see a value there. Thanks again for the prompt help Carlos.

**Comment by coryan** [comment]
> Thank you Carlos for that information, I will re-evaluate if that request is buying me anything.
> 

Maybe this helps:

```C++
void F(gcs::Client client, std::string bucket, std::string object,
    char* buffer, std::size_t buflen) {
  auto stream = client.ReadObject(bucket, object);    // 1
  do {                                                // 2
    stream.read(buffer, buflen);                      // 3
  } while (stream);                                   // 4
}
```

* Line `1` performs a handful of allocations. The largest one is a buffer (let's calling the "ios buffer") of 128KiB which is used only when using buffered iostream operations.
* Line `3` performs zero allocations, the data is copied straight from the libcurl+OpenSSL buffer into `buffer`.
    * The ios buffer allocated in line `1` is bypassed (with some exceptions).
    * The exception is that any data already in ios buffer is copied into `buffer` and if that is larger than `buflen` no additional reads are performed.
    * If more reads are needed the ios buffer plays no role.
* Line `2` and `4` perform no allocations and are included for completeness sake.


> Also, in the above example, I forgot to mention that `buf` is already allocated and initialized.

As you can see above you can use a pre-allocated buffer.

> 
> I will be having a case where we are downloading gigabytes of data in parallel from cloud and if that operation creates its own new memory for streams, that might add up quickly to make a difference.

If you had a 8,000 parallel downloads that would be about 1GiB in addition to your own buffers. Is that the concern?  We can make that internal buffer adjustable so you can make it smaller if that is the case.


> My restriction is that, I already have a buffer to be used for streams for reading object and I don't want to discard/ignore it. And with `auto stream = client.ReadObject()`, my understanding is that a new different memory is being allocated to/for `stream` (please correct me if I am wrong here)

See above, yes, some new data is allocated, but for unformatted I/O it plays no role after the first few KiB.

> and the existing memory(`buf`) is kind of unused. Then we have to `read()` the `stream` in to the `buf`, which will involves data copy.

The `read()` call bypasses the internal buffer (unless all the data you want happens to be in the internal buffer already). There is a data copy, from the socket buffer (or really the buffer for libcurl + OpenSSL) into your buffer, but that is unavoidable (to the best of my knowledge).

> To my knowledge AWS and Azure SDKs has ways to avoid new memory creation and data copy and hence I was trying to investigate if something similar is available from Google.

Our benchmarks show that the data copy, while not trivial, is a small fraction of the CPU costs when compared to the decryption, checksums, and I/O.

Furthermore, even if you gave us the buffer when the stream is created, we still would need to copy any incoming data from the libcurl+OpenSSL buffer. The number of data copies would be the same.

> I think I am okay for now but will approach again if we see a value there. Thanks again for the prompt help Carlos.

No problem, let me know if making the buffer size adjustable would help in your case.

**Comment by spnshah** [comment]
Sure, I will reach out to you if making the buffer size adjustable makes sense for us. Prior to that, the plan is to have the storage-cpp implementation done on our side so we have a full end-to-end setup in place to conduct real tests.
Thank you again Carlos for the timely help.

**Comment by coryan** [comment]
I think the original question is answered. Closing.
