### ISSUE TITLE
Consider: Reduce version # duplication in Dockerfiles

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#3788]
Currently our Dockerfiles in `ci/...` contain blocks such as:

https://github.com/googleapis/google-cloud-cpp/blob/a442ac1c5823a2ac6244102a5d8a7c85f4890c30/ci/kokoro/docker/Dockerfile.fedora-install#L66-L75

This is fine and works, but when we update our version of the `cpp-cmakefiles` package, we need to update the version number in 3 separate places. And the version has a slightly different format in the various places, so doing the replacement w/ a regex is not trivial.

## Proposal

We may be able to rewrite these docker commands to only use the version number in a single location. For example, we can directly untar the output of the wget, bypassing the need to name the `tar.gz` file a second time. We can also use tar's `--transform=` flag to remove the version number from the extracted files, so that we can simply `cd cpp-cmakefiles/` after extracting. So something like the following should work:

```
WORKDIR /var/tmp/build
RUN wget -q -O - https://github.com/googleapis/cpp-cmakefiles/archive/v0.8.0.tar.gz | \
      tar -zxf - -transform='s,^[^/]\+/\?,cpp-cmakefiles/,'  # <-- NEW
    cd cpp-cmakefiles                                        # <-- NO VERSION
    cmake \
      -DBUILD_SHARED_LIBS=YES \
      -H. -Bcmake-out && \
    cmake --build cmake-out --target install -- -j ${NCPU} && \
    ldconfig && \
    cd /var/tmp && rm -fr build
```

We could probably do something similar for more than just the `cpp-cmakefiles` repo.

I'm sure there are other ways (besides `--transform=`) to extract the tar into an unversioned directory of a statically known name. Those options would probably work fine too.

**Comment by coryan** [comment]
An alternative option is to automatically generate these Dockerfiles, like we do for `ci/kokoro/install/Dockerfile.*`.

**Comment by devbww** [comment]
> I'm sure there are other ways

Perhaps something like ...
```
mkdir cpp-cmakefiles
cd cpp-cmakefiles
wget ... | tar -zxf - --strip-components=1
cmake ...
```
