### ISSUE TITLE
speed up `Verify Formatting` step

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp#3794]
When I run `./ci/kokoro/docker/build.sh clang-tidy`) on my workstation, the `Verify formatting` step takes ~45 seconds even with only a few files modified. Investigate whether we can speed this up (does it/could it format changed files only?)

**Comment by coryan** [comment]
There are also opportunities to parallelize this, e.g., running clang-format in different threads for `google/cloud/{storage,bigtable,spanner,.}`

Likewise, the cmake-format, buildifier and python formatting can run in parallel.

**Comment by devjgm** [comment]
Here's timing info from my laptop:

```
## Checking include guards START:  Thu Apr 16 13:13:36 UTC 2020
## Checking include guards   END:  Thu Apr 16 13:13:36 UTC 2020
Delta: <1s

## Checking cmake format START:  Thu Apr 16 13:13:36 UTC 2020
## Checking cmake format   END:  Thu Apr 16 13:13:47 UTC 2020
Delta: 11s

## Checking clang-format START:  Thu Apr 16 13:13:47 UTC 2020
## Checking clang-format   END:  Thu Apr 16 13:14:05 UTC 2020
Delta: 18s

## Checking sed xform START:  Thu Apr 16 13:14:05 UTC 2020
## Checking sed xform   END:  Thu Apr 16 13:14:06 UTC 2020
Delta: 1s
 
## Checking buildifier START:  Thu Apr 16 13:14:06 UTC 2020
## Checking buildifier   END:  Thu Apr 16 13:14:06 UTC 2020
Delta: <1s

## Checking python formatting START:  Thu Apr 16 13:14:06 UTC 2020
## Checking python formatting   END:  Thu Apr 16 13:14:07 UTC 2020
Delta: 1s

## Checking shell check START:  Thu Apr 16 13:14:07 UTC 2020
## Checking shell check   END:  Thu Apr 16 13:14:08 UTC 2020
Delta: 1s

## Checking fixing whitespace START:  Thu Apr 16 13:14:08 UTC 2020
## Checking fixing whitespace   END:  Thu Apr 16 13:14:10 UTC 2020
Delta: 2s
```

This is quite unscientific, and it's just one snapshot. But it tells us roughly which ones steps are the big ones and which are small. Note: that I've seen the clang-format step take upwards of 40s.

I'd say that focusing on the clang-format and cmake-format steps will be the biggest bang.

**Comment by devjgm** [comment]
In #3431 (March 4, 2020) we updated `cmake_format` from 0.6.0 to 0.6.8. I _think_ that update "fixed" the problem w/ cmake_format that caused it to change the timestamp on files even when it did not change them. Therefore, I think we could change the `cmake_format` code in `check-style.sh` to use something like `find ... | xargs -0 cmake_format -i`, which would likely speed it up too.
