### ISSUE TITLE
Prep: Update CMake files to use `include(GoogleCloudCppCommon)`

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#3827]
In `-cpp`, most common CMake settings are configured in one place. So before the code is moved into `-cpp`, update the `google/cloud/$project/CMakeLIsts.txt` file to source this one file, and it probably don't need to source any others. Again, this is attempting to make it so the code and build work unchanged when moved into `-cpp`.

Example: https://github.com/googleapis/google-cloud-cpp-bigquery/pull/48

**Comment by scotthart** [comment]
fixed in https://github.com/googleapis/google-cloud-cpp-pubsub/pull/115
