### ISSUE TITLE
Codecov CI shows red X on lots of PRs 

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#3844]
There are tons of PRs that do not affect the code coverage at all, yet the codecov/project CI build shows up as broken, and we have to ignore it to submit. If there's some way for us to fix this, great. If not, we can close this and live with it.

![codecov-break](https://user-images.githubusercontent.com/9447643/79616142-49ed5700-80d2-11ea-8ef5-96657d0ac0f6.png)

**Comment by coryan** [comment]
I think we can tell codecov to not report these (send a PR to `.codecov.yml`) .  That would be better than the situation today where we are training ourselves to ignore these.

**Comment by devjgm** [comment]
oh, cool. But I'm not sure what "these" are. Why did it fail? I see https://docs.codecov.io/docs/codecovyml-reference, but I don't know which setting/param to tweak because I have no idea _why_ it breaks. Do you know which setting we should tweak?

**Comment by devjgm** [comment]
Nm. I see you already fixed in https://github.com/googleapis/google-cloud-cpp/issues/3844

**Comment by devjgm** [comment]
@coryan can close?

**Comment by coryan** [comment]
Oh yes, I forgot.
