### ISSUE TITLE
Clearly document our support guarantees

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#3846]
I don't think we have any docs that clearly state what our support guarantees are for the library. Things like what are allowed uses of our library, and what are not. What is part of the public API and what is not. What can users safely rely upon and what should they not.

We will work hard and diligently to avoid breaking any well behaved callers. However, callers using the library in an unsupported way may well break.

We should write a _short_ and clear document that humans can easily read (not a legalese doc) and understand. The goal is to give our customers confidence in what they can rely upon, and suggestions about what they should avoid.

**Comment by coryan** [comment]
The stuff in googleapis/google-cloud-cpp-common#262 would be relevant for this discussion.

**Comment by devjgm** [comment]
Of course. I knew this sounded familiar. FWIW, I moved that issue into this repo `-cpp`, and I'm going to close this issue in favor of that other one, which has better details.

The new issue is: https://github.com/googleapis/google-cloud-cpp/issues/3847
