### ISSUE TITLE
Document what we consider an "API breakage"

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#3847]
I think we should create an ADR documenting what is an API breakage, or at least the things we do not consider part of the API.  I am thinking of:

- We make no attempts to preserve the A**B**I.  We change object sizes, add fields, change private members functions and fields without notice. We also may add default parameters to a function without notice.
- For the purposes of this document "API" means the "library API", the guarantees about the REST and/or gRPC APIs offered by GCP are discussed elsewhere.
- We try to preserve the API, but we will break the API if we think it is important, we will document -- to the best of our abilities -- any API breakage.
- Header files are part of the API, but you should not rely on indirect `#includes`.
- We consider type aliases and inline functions part of the API
- We do **not** consider types, functions or objects in the `internal` (or `foo_internal`) namespace to be part of the API, we will change those without notice.
- We do **not** consider types, functions or objects used in our tests part of the API, this includes anything in the `testing` or `foo_testing` namespace.
- We do **not** consider header files in the `internal/` or `testing/` or `testing_utils/` directories to be part of the API.
- This list is not exhaustive, as we discover other things that should not be considered part of the API we will update this list, but still will document any changes.

**Comment by devjgm** [comment]
We should also document what we guarantee wrt to our build deps: https://github.com/googleapis/google-cloud-cpp/pull/5054#issuecomment-692141373
