### ISSUE TITLE
Remove ci/coverity-scan.sh

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#3858]
It looks like https://github.com/googleapis/google-cloud-cpp/blob/master/ci/coverity-scan.sh is no longer used by any of our builds, and it looks like it's only received some global-cleanup-type tweaks in about a year. If it's no longer needed/used, we might want to remove it.

**Comment by coryan** [comment]
We always ran that manually.  I would rather keep it, it serves as documentation on how to run with that tool.

**Comment by devjgm** [comment]
Ok. Thanks
