### ISSUE TITLE
Unify the build_info.{h,cc} C++ and CMake code

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#3867]
The pubsub, spanner, and bigquery code all generate a C++ file named `internal/build_info.{h,cc}` that includes info about the build environment. Currently this logic is handled separately for bigquery, spanner, and pubsub. Once they're all merged into `-cpp`, we should unify this into a single place. This would also allow it to be used by bigtable and storage.

**Comment by coryan** [comment]
I will clean these up for `bigquery` and `pubsub`, since they are already into the monorepo.

**Comment by coryan** [comment]
Releasing back to the pool as it is blocked for `-spanner`.
