### ISSUE TITLE
Cleanup test tags and their use in the CI scripts

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#3868]
We use build tags to split the tests across several dimensions:

- Unit tests basically have no tags, they run by default.
- Integration tests of any kind are labeled `integration-tests`, we mostly use that tag to exclude integration tests when running the unit test only.
- Some integration tests need to have the `bigtable` emulator running **or** the environment variables necessary to contact production, these are labeled `bigtable-integration-tests`
- Some integration tests need to have the `storage` emulator (aka tetsbench) running **or** the environment variables necessary to contact production, these are labeled `storage-integration-tests`
- Some integration tests only run against production, these are labeled `integration-tests-no-emulator`

Some integration tests need environment variables that change on each run **and** they typically need a lot of support from the CI scripts to setup the environment to run the test.

Because passing these variables to all the other integration tests would disable caching, we exclude them *by name* in the Bazel runs, and then run them *by name* in the CI scripts **if** we have setup the environment configuration they need.

This is all too complicated, and passing names of tests in the scripts is hard to maintain. we need to clean all of this up.

**Comment by devjgm** [comment]
Hmm, I don't really see a way to do this that works in both bazel and cmake. Basically, we need a way to say something like "run all the integration tests for Bigtable". There are two important pieces of information: "integration tests" and "bigtable". With bazel we can specify both of these like `bazel test --test_tag_fitlers=integration-tests google/cloud/bigtable/...`. That is, we have the build target path and the tag filter to provide those two pieces of information.

With CMake/CTest, I don't believe we have the target path option. We only have labels. And AFAICT, there's no way with ctest to specify run the targets that have *both* labels, i.e., the following doesn't work `ctest -L bigtable -L integration-tests`. The second `-L` overwrites the first. Therefore, I think with ctest we need to combine both of those two pieces of information into a single label, which is exactly what we've done and where we're at now.

We could simplify these labels for bazel, but I'd say trying to keep the labels in sync between cmake and bazel is probably a good idea.

So, I'm thinking there's not much we can do to simplify our use of test tags/labels. Are there other tasks or items being tracked by this issue? If not, we might be able to close this.

**Comment by coryan** [comment]
There is also the crazy `*no-emulator` any thoughts on that?  Maybe we can treat this as the "documentation" of how these work and close it?  Or move it to ci/README.md?  WDYT?

**Comment by devjgm** [comment]
Actually, I was wrong. ctest does give us a way to do what we need since we use a consistent naming convention. `-R` will match test names against the given regex, and `-L` will match test labels against a given regex. So to run all of Bigtable's integration tests we could do: `ctest -R bigtable -L integration-tests`, which is logically equivalent to what we can do with bazel.

So now I'm thinking of a simplified configuration as follows:

* **All integration tests get a `integration-test` label.** This is mostly just useful when we want to broadly _exclude_ all integration tests. This will apply to bazel and cmake.
* **All integration tests that talk to production will _also_ get a `integration-test-production` label**. This will replace the "*-no-emulator" labels, and I think will read a bit more clearly.
* **All integration tests that use an emulator will _also_ get a `integration-test-emulator` label**.
* **All `${product}-integration-tests` labels will be removed**. We'll use either bazel targets or `-R ${product}` to select these tests.



Does this sound like it'd be any simpler and clearer?

**Comment by coryan** [comment]
SGTM, thanks for thinking through it.

**Comment by coryan** [comment]
Oh, implementation-wise: in CMake we override the labels after creating the targets to set `no-emulator` (now `-production`/`-emulator`) tags.  We (currently) have no easy way to pass that information to Bazel and code it twice or simply ignore it for Bazel (and then hardcode specific targets to skip in the emulator).

Can we do better?

**Comment by devjgm** [comment]
After working through https://github.com/googleapis/google-cloud-cpp/pull/4257, I now understand your last comment. Our test labels are not in sync between cmake and bazel. It would be nice to keep them in sync. 

After https://github.com/googleapis/google-cloud-cpp/pull/4257 lands, I may close this issue and open a new one that is focused on that specific issue.

**Comment by devjgm** [comment]
To summarize the situation of where we're at now (after #4257) it's...

- Both Bazel and CMake: unit tests have no labels.
- CMake+Bazel: test programs (or programs that need testing) that are **not** unit tests (integration tests, examples, benchmarks, etc) have the `integration-test` label.
- CMake: test programs that can run only against production have the `integration-test-production` label.
- CMake: test programs that can run against production or the corresponding emulator(s) have the `integration-test-emulator` label.
- CMake: to run the tests against emulators filter by the `integration-test-emulator` and by the program prefix (e.g. `bigtable_`)
- Bazel: there are no labels for distinguish what programs can only run in production, instead the CI scripts have hard-coded lists of targets. See #4259 for an issue tracking a fix for this.
