### ISSUE TITLE
ensure `cloud-cpp-testing-bucket` gets cleaned up regularly

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp#3872]
Currently, our testing bucket `cloud-cpp-testing-bucket` has 43156 objects with date stamps from 2020-03-21 to 2020-04-21.  Having that many objects in the bucket drastically increases the runtime of some of our integration tests (see #3854) - when running against an empty bucket the runtimes of the two longest tests drop from 115 to 5 seconds and 72 to 2 seconds.

We should clean these objects up much more aggressively, or find another way to preserve performance even if the bucket becomes heavily populated.

**Comment by mr-salty** [comment]
is there any reason not to change this to 1 day from 30 days?

```
gsutil lifecycle  get gs://cloud-cpp-testing-bucket
{"rule": [{"action": {"type": "Delete"}, "condition": {"age": 30}}]}
```

**Comment by coryan** [comment]
> is there any reason not to change this to 1 day from 30 days?

I cannot think of any, please make the change.

**Comment by mr-salty** [comment]
thanks - done.  I'll call this closed for now, probably even a day is longer than we need but GCS only supports days and I don't think it's worth writing some custom job to do that.

n.b.: "Updates to your lifecycle configuration may take up to 24 hours to go into effect."  Maybe I'll clean some of them up manually.

```
$ gsutil lifecycle get gs://cloud-cpp-testing-bucket
{"rule": [{"action": {"type": "Delete"}, "condition": {"age": 1}}]}
```

**Comment by mr-salty** [comment]
> Maybe I'll clean some of them up manually.

this is easy enough to do with xargs so I'm doing this now.

**Comment by mr-salty** [comment]
I cleaned up everything older than 24h but this still seems like a lot, are they "leaking" from failed tests?

$ `gsutil ls gs://cloud-cpp-testing-bucket  | wc -l`
6980

**Comment by coryan** [comment]
> I cleaned up everything older than 24h but this still seems like a lot, are they "leaking" from failed tests?

As long as they don't leak from successful tests and we have the lifecycle rule I am mostly happy.  Making the tests more complicated to delete things on a failure seems like the wrong place to put effort.

**Comment by devbww** [comment]
> As long as they don't leak from successful tests ...

I don't grok the API, so forgive a naive question, but who deletes those `.src-<N>` objects?

**Comment by mr-salty** [comment]
oh yeah, I meant to check my own bucket and forgot... but indeed it was left with a bunch of files:

4x like `gs://salty-test-bucket-1/ob-99byJPL6W6xA0T5I.txt`
100x like `gs://salty-test-bucket-1/vmouvliqcywedcfd.src-13`

**Comment by mr-salty** [comment]
the former have "contents for the final revision" in them, so they come from `object_list_objects_versions_integration_test.cc`

the .src ones appear to be `object_compose_many_integration_test.cc`

**Comment by mr-salty** [comment]
as Carlos pointed out in the PR, there are also previous versions that need to be cleaned up.

With the PR as it stands, when I run all of the integration tests I end up with zero "live" objects but 444 total non-live objects, with many different filename patterns and a few inside "directories".  I'll work on tracking them down.

I think my plan will be to add a generic mechanism to ObjectIntegrationTest to allow tests to register objects they create, so they can be automatically deleted in TearDown (which runs whether the test passes or fails).

**Comment by mr-salty** [comment]
I never finished the PR I have for this, although setting the lifetime to 1 day has largely solved the original problem of long test runtimes. It would still be better to clean up properly, but I don't think it's a high priority.

**Comment by coryan** [comment]
I am marking this as resolved, the object leaks (if any) from the integration tests are cleaned up by the lifecycle rule.
