### ISSUE TITLE
Create google/cloud/README.md in -common

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#3908]
In the new monorepo world, every "product" in google/cloud/*/ has its own README.md file. Since our "common" package also contains user-facing stuff, we probably also want a README.md for that too. This is slightly weird since common lives in `google/cloud/*` directly, not a subdir, but I think that should be fine.

**Comment by coryan** [comment]
Fixed in https://github.com/googleapis/google-cloud-cpp-common/pull/285 and imported via #3918
