### ISSUE TITLE
Cleanup how functions are sourced in CI scripts

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#3911]
We have several `.sh` files that define functions used by other scripts, and these are getting more complex as the functions in one `.sh` file assume the functions in another `.sh` file have been loaded.

It would be nice to make these dependencies explicit.

It is also possible that this is a smell and that shell is the wrong tool for this.

**Comment by devjgm** [comment]
I don't (yet) think bash scripts are the wrong tool. But we probably could improve things with a little more structure around our scripts. For example, we might consider

* Move the bash scripts that are actually _libraries_ into a `lib` directory to make it clearer what's a library and what's an executable.
* Sourcing bash libraries should probably happen near the top of the executable, like how includes work in C++
* Bash _libraries_ should use the include guard trick so they can be sourced multiple times safely
```shell
if (( CI_LIB_GCLOUD_LIB_SH__++ == 0 )); then
...
fi  # include guard
```
* Libraries could use "namespacing", like
```shell
# File: ci/lib/gcloud_lib.sh
function gcloud::create_config() {
...
}
```
