### ISSUE TITLE
Cleanup downloading of cache tarball to the middle of the source code.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#3915]
We should avoid downloading the cache tarball to the middle of the source code, as discussed here:

https://github.com/googleapis/google-cloud-cpp/pull/3894#discussion_r414544593

Maybe we can make the cache a public GCS object and download it from inside the Dockerfile? Or maybe we can pass the secrets necessary to download the cache to the `docker build` command?

**Comment by devjgm** [comment]
This issue was fixed (or avoided or now moot) when we moved all builds to GCB in #6180.
