### ISSUE TITLE
Compile only the common components that are needed

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#3926]
With CMake, customers may disable compiling specific libraries, say because they
only want to compile `google/cloud/storage` and do not want to compile the
other dependencies (gRPC, Protobuf, etc.)

After we import `google-cloud-cpp-common` we will always compile all the
common components, even if they are not needed by the libraries that
the customer selected. It would be nice to disable the common
components that are not needed.

This may be as simple as adding the right `EXCLUDE_FROM_ALL` options
into the CMake files, or may require some more fine tuning.

**Comment by devjgm** [comment]
Maybe we could have two "common" libraries. Maybe `common` and `common-grpc`. GCS should not take the dep on `common-grpc`. That way our client libraries simply say what they depend on and they get exactly what they depend on, no more no less. Just a thought.

**Comment by remyabel** [comment]
Another leftover TODO:

https://github.com/googleapis/google-cloud-cpp/blob/80f03434e7e590d53302fa0bda1f883ab987a5c2/CMakeLists.txt#L169-L171
