### ISSUE TITLE
CMake configuration is not well suited for monorepo builds

### ISSUE THREAD

**Issue by DimanNe** [googleapis/google-cloud-cpp#3928]
### Does this issue affect the `google-cloud-cpp-common` project?
Yes

### What version of `google-cloud-cpp-common` are you using?
v0.25.x

### What operating system and version are you using?
Kubuntu 20.04

### What were you trying to do?
I have a monorepo with all libraries and dependencies, including `llvm-project/libcxx` and `llvm-project/libcxxabi`. (If you are interested, I have this structure because I want to be able to build everything with various clang sanitisers).

I add this project (`google-cloud-cpp-common`) as a directory in my `contrib/` folder and include it in CMakeLists.txt in this way: `add_subdirectory(google-cloud-cpp-common)`.

When I try to configure the project, it says this:
```
CMake Error: install(EXPORT "google_cloud_cpp_common-targets" ...) includes target "google_cloud_cpp_common" which requires target "cxx_static" that is not in the export set.
CMake Error: install(EXPORT "google_cloud_cpp_common-targets" ...) includes target "google_cloud_cpp_common" which requires target "cxxabi_static" that is not in the export set.
```
Note, `cxx_static` and `cxxabi_static` come from llvm.

I think that the root cause is that I do not want to install anything, but `google-cloud-cpp-common/google/cloud/CMakeLists.txt` tries to and fails...

### What did you expect to see?
I am not very good at CMake (so there might be a better/proper solution), but I would probably expect an option to disable any installation at all.

**Comment by devjgm** [comment]
@DimanNe Thanks for contacting us. I hope you've figured out a solution that works for you. Feel free to re-open this issue if you have more questions about this.
