### ISSUE TITLE
All repos: Move user-facing bazel build targets to top-level BUILD

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#3929]
See the change made to -spanner here: https://github.com/googleapis/google-cloud-cpp-spanner/pull/1396

We want to make that change to all of our repos: -cpp, -common, -pubsub, -bigquery.

The reasons are:

1. It gives users a simple, clean BUILD file where they can easily see the targets that they're allowed to use.

1. It lets users include our headers using either of `"..."` or `<...>`

- [ ] `-cpp`
- [x] `-spanner`

**Comment by coryan** [comment]
How is this different from #3701 ?

**Comment by devjgm** [comment]
It's not. I think https://github.com/googleapis/google-cloud-cpp/issues/3701 supercedes this one.
