### ISSUE TITLE
provide common support for date/time parsing and formatting

### ISSUE THREAD

**Issue by devbww** [googleapis/google-cloud-cpp#3934]
Both [google-cloud-cpp](https://github.com/googleapis/google-cloud-cpp) and [google-cloud-cpp-spanner](https://github.com/googleapis/google-cloud-cpp-spanner) include support for parsing and formatting times.  The latter even has its own `Timestamp` class, whereas the former uses `std::chrono::system_clock::time_point`.

See
```
googleapis/google-cloud-cpp-common:google/cloud/internal/format_time_point.h
googleapis/google-cloud-cpp-common:google/cloud/internal/parse_rfc3339.h
```
and
```
googleapis/google-cloud-cpp-spanner:google/cloud/spanner/internal/time_format.h
googleapis/google-cloud-cpp-spanner:google/cloud/spanner/internal/date.h
```
There may be an opportunity to unify those implementations in `google-cloud-cpp-common`, and particularly so if we move to `absl::Time` and `absl::CivilDay` first.

**Comment by devjgm** [comment]
FYI, this is doable now that this is all in a single repo.

**Comment by devjgm** [comment]
To be clear, I think the real cleanup that we want here is not to unify our time formatting/parsing functions, but rather offload all of our formatting/parsing to the `absl/time/time.h` library. We may still have a few small wrapper functions, that we want to unify too, but the real work of formatting and parsing should be handled by Abseil.

Also, note that doing this is blocked on Abseil's next LTS release, which should happen toward the end of July 2020.

**Comment by devjgm** [comment]
After #4625, I think this particular issue is closed. There's no very little (no?) date/time formatting/parsing duplication between common and spanner. There's still some date/time formatting that could be cleaned up in common (e.g., https://github.com/googleapis/google-cloud-cpp/pull/4680), but I think that's mostly covered by #4458
