### ISSUE TITLE
Consider whether we want to keep ci/templates

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#3942]
https://github.com/googleapis/google-cloud-cpp/tree/master/ci/templates contains scripts and `.in` files that help us generate `ci/kokoro/install/Dockerfile.*` and its `build.sh` script. I believe the intent of `ci/templates` was to help us managed similar builds across multiple repos. However, with a monorepo we no longer have a problem keeping things in sync.

Therefore, we should consider whether it helps/hurts to keep these templates and generate these files vs just keeping/editing the files directly (like we do in `ci/kokoro/docker/`).

**Comment by coryan** [comment]
Quick thoughts:

- I think generating `ci/kokoro/install/build.sh` is no longer a good idea.
- I think generating `ci/kokoro/install/Dockerfile.*` is still useful (lots of repetition across them)
- It would be nice if we *also* generated `ci/kokoro/docker/Dockerfile.*`

Having said that, if we delete all this code you will not make it terribly said, making the same changes to 13-14 Dockerfiles is relatively easy.
