### ISSUE TITLE
[Flake] Test failure on Windows+Bazel

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#3952]
Looks like a test race condition to me:

```
INFO: From Testing //google/cloud:completion_queue_test:
==================== Test output for //google/cloud:completion_queue_test:
[==========] Running 13 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 13 tests from CompletionQueueTest
[ RUN      ] CompletionQueueTest.TimerSmokeTest
[       OK ] CompletionQueueTest.TimerSmokeTest (10 ms)
[ RUN      ] CompletionQueueTest.MockSmokeTest
[       OK ] CompletionQueueTest.MockSmokeTest (2 ms)
[ RUN      ] CompletionQueueTest.ShutdownWithPending
[       OK ] CompletionQueueTest.ShutdownWithPending (22 ms)
[ RUN      ] CompletionQueueTest.CanCancelAllEvents
google/cloud/completion_queue_test.cc(152): error: Expected equality of these values:
  std::future_status::ready
    Which is: 4-byte object <00-00 00-00>
  f.wait_for(ms(100))
    Which is: 4-byte object <01-00 00-00>
[  FAILED  ] CompletionQueueTest.CanCancelAllEvents (156 ms)
```

https://source.cloud.google.com/results/invocations/7ff6b89f-719f-4976-9399-b9fc16c8bc55

Source:

https://github.com/googleapis/google-cloud-cpp/blob/eca3262e773ca0ba0a7d8911b551b7797d7f7111/google/cloud/completion_queue_test.cc#L131-L154

**Comment by coryan** [comment]
This seems like a repeat:

https://source.cloud.google.com/results/invocations/dc0c268b-0743-4326-a114-44d6bd7fa0b4

**Comment by coryan** [comment]
https://source.cloud.google.com/results/invocations/7b4db044-bc29-474b-9a46-f4e8bff7d9cf/targets

**Comment by devbww** [comment]
So, the theory is that 100ms is not always sufficient for the `CancelAll()` to have completed its effect, have `cq.Run()` return, and `done.set_value()` satisfy the `wait_for()`?

If so, and short of ubiquitous simulated-clock support, it seems the only course of action is to increase the timeout.  Yes?

**Comment by coryan** [comment]
Or just call `f.wait()` there is no reason to set a timeout, the next line will block until the thread returns, which also blocks "forever".

**Comment by coryan** [comment]
Also, that timer on line 141 seems unnecessarily tight.  We really want timers that will *not* expire, so we have a chance to cancel them.  Setting them to 1 hour would be Okay in my book.
