### ISSUE TITLE
Enable clang-tidy for all targets

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#3958]
Currently I think clang-tidy is not running for all of our targets. I only see the following CMake files that are calling the `google_cloud_cpp_add_clang_tidy` CMake function:

```shell
cmake/GoogleCloudCppCommon.cmake
148:function (google_cloud_cpp_add_clang_tidy target)

google/cloud/storage/CMakeLists.txt
273:google_cloud_cpp_add_clang_tidy(storage_client)

google/cloud/bigtable/CMakeLists.txt
197:google_cloud_cpp_add_clang_tidy(bigtable_client)

google/cloud/firestore/CMakeLists.txt
66:google_cloud_cpp_add_clang_tidy(firestore_client)

google/cloud/CMakeLists.txt
200:google_cloud_cpp_add_clang_tidy(google_cloud_cpp_common)
353:    google_cloud_cpp_add_clang_tidy(google_cloud_cpp_grpc_utils)
```

Specifically there is nothing for "common", "pubsub", or "bigquery". This is probably a step we missed when migrating code over.

The *extra credit* solution would do something generic that automatically applies to *all* of our CMake targets today and in the future, so we don't have to remember to do this.

**Comment by devjgm** [comment]
Here is where our build script enables clang tidy:

https://github.com/googleapis/google-cloud-cpp/blob/141d2c8d375c0b9c580a6bd78de6c3e8e3d63ae4/ci/kokoro/docker/build-in-docker-cmake.sh#L75-L77

I'm wondering if we just change to this line:

```shell
cmake_extra_flags+=("-DCMAKE_CXX_CLANG_TIDY=clang-tidy")
```
would that work for everything that's built by this cmake invocation? It may also let us avoid the need to explicitly enable clang-tidy for individual targets.

**Comment by devjgm** [comment]
A quick experiment doing this shows a lot of new clang-tidy issues that were hiding out.

**Comment by coryan** [comment]
I spent some time today looking into this.  The tests and examples have never had clang-tidy enabled, it might be nice to do that, but it would take significant effort.

I will send a PR (need to do some testing) to make it more obvious that the libraries have this enabled.

The fix using `CMAKE_CXX_CLANG_TIDY` seems like a good idea. I believe the path to implement should be:

- Manually add `google_cloud_cpp_add_clang_tidy(${target})` to the targets in one directory, and fix any warnings / errors generated by clang-tidy.
- After all the directories are fixed, change the CMake code to use `CMAKE_CXX_CLANG_TIDY`.

**Comment by coryan** [comment]
I am stopping work on this after the PR I just sent.  Folks are welcome to use https://github.com/coryan/google-cloud-cpp/commit/0fc5b0edfbe9d18a38c9438ab642140f9e8450bc as the basis for further improvements.

**Comment by devbww** [comment]
I'll start taking a look.  If anyone chooses to start dealing with a particular sub-tree, please yell.

**Comment by mr-salty** [comment]
pretty much all the examples have a lambda that passes everything by value like:

`[](gcs::Client client, std::string bucket_name, std::string entity) { ... }`

Which triggers `performance-unnecessary-value-param` warnings; the APIs themselves use const-refs so we can't `std::move` them out for the most part.

Changing them all to const-ref is fairly mechanical, but these do show up in the external docs and it seems like the choice of making them values was intentional - so just wanted to make sure we're all agreed that is what we want to do.

**Comment by mr-salty** [comment]
ok, `storage/` is done, @devbww I am moving on to `bigtable`

**Comment by devjgm** [comment]
FTR, we also want to enable clang-tidy in all of our headers where it's possible to do so without breaking an existing API. I imagine we may not be able to get bigtable/ and storage/ fully clean, because changes there may break APIs.

It would be good to change the `HeaderFilterRegex` in our `.clang-tidy` file to a negative filter, so that all headers are checked by default *except* for the few places that are listed. For example, we might want to change to the following as soon as we can:

```
HeaderFilterRegex: "google/cloud/(?!storage/|bigtable/).*"
```

**Comment by coryan** [comment]
Note that #4097 introduces a TODO() related to this issue.

**Comment by coryan** [comment]
FWIW, `google/cloud/bigtable/benchmarks` does not seem to have `clang-tidy` enabled.
