### ISSUE TITLE
Windows+CMake gets invalidated too often

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#3987]
The Windows+CMake builds cache the `vcpkg` artifacts, as follows:

- The continuous integration builds update the cache. These only run on commits to `master`
- The pull-request builds fetch the artifacts and rebuild them
  - If we have changed our dependencies or build scripts this will update the artifacts, but **also**
  - If there are any changes upstream in `vcpkg` the cache is invalidated and rebuilt

The latter happens more often that we commit to `master`, so periodically the builds take a *long* time because the cache is invalid. We should consider either:

- Pin to the version of `vcpkg` we used to create the cache.
- Periodically run a build on `master` just to update the cache.

**Comment by coryan** [comment]
Just FYI, I had to manually trigger some builds at `master` to keep PRs snappy today.

**Comment by devjgm** [comment]
I kinda like your "pin the version of vcpkg" idea. I'm guessing that solution would be our CI builds (the non PR builds) would update the cache and they would also update their version of vcpkg. Then on PR builds, they'd fetch the cache, and sync to the same vcpkg version that was used in the CI build. How would they know which vcpkg hash to sync to? The CI builds would have to stash some artifact about it in the cache that the PR builds fetch.

Am I understanding your idea correctly?

**Comment by coryan** [comment]
> I kinda like your "pin the version of vcpkg" idea. I'm guessing that solution would be our CI builds (the non PR builds) would update the cache and they would also update their version of vcpkg.

That would be a really cool implementation, yes.  We could start by simply having the `vcpkg` version hardcoded in the CI script, and update them when we cut a release or some other important points.

> Then on PR builds, they'd fetch the cache, and sync to the same vcpkg version that was used in the CI build. How would they know which vcpkg hash to sync to? The CI builds would have to stash some artifact about it in the cache that the PR builds fetch.

Maybe a `.txt` file stored along the cache? Easy enough to download it and use as an input for the `git clone ... vcpkg` step.

> 
> Am I understanding your idea correctly?

Yes.

**Comment by coryan** [comment]
Manually triggered builds at `master` today.

**Comment by coryan** [comment]
This was fixed in #4681
