### ISSUE TITLE
ObjectReadStream failed on `tellg()`

### ISSUE THREAD

**Issue by vnvo2409** [googleapis/google-cloud-cpp#4013]
**What component of `google-cloud-cpp` is this related to?**
`google/cloud/storage`

**Describe the bug**
`ObjectReadStream::tellg()` return `-1` even when `ObjectReadStream::status()::code() == kOK`

**To Reproduce**
```cpp
reader.seekg(0, reader.end);
int64_t read = reader.tellg(); // -1
reader.seekg(0, reader.beg);
```

**Expected behavior**
`tellg()` return non-negative.

**Operating system:**
MacOS 10.15

**What compiler and version are you using?**
Apple clang version 11.0.0 (clang-1100.0.33.16)

**What version of `google-cloud-cpp` are you using?**
https://github.com/googleapis/google-cloud-cpp/releases/tag/v1.13.0

**Additional context**
I want to get the size of the internal stream without create a new `std::string` variable. In the code above, `reader.tellg()` should return the actual size of that stream instead of `-1`

**Comment by coryan** [comment]
I think we should override `pubseekoff()` and always fail both `seekg()` and `tellg()` operations at least that would not be misleading as none of them is implemented.

If you want to find out the size of the object you need to call `Client::GetObjectMetadata()`. You should also be able to get this information from the headers in `ObjectReadStream::headers()`. 

Thinking about it, we might be able to implement `seekg()`, but it will be fairly expensive: we would need to reset the download and set the offset options accordingly.

**Comment by vnvo2409** [comment]
Could you tell me where to look at `ObjectReadStream::headers()` because it is not documented

**Comment by vnvo2409** [comment]
OK I found it, it is a `std::multimap<std::string, std::string>`.

**Comment by coryan** [comment]
Yeah, the header you want is `content-length`.

**Comment by coryan** [comment]
I am going to reopen this because fixing the functions to set the right errors is important.

**Comment by vnvo2409** [comment]
If you need help, I am very happy to contribut

**Comment by coryan** [comment]
I am going to close this.  Supporting `tellg()` in the general case seems like a separate feature.
