### ISSUE TITLE
Use emulator for some CI builds (maybe coverage?)

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#4023]
The Spanner emulator supports *most* functionality currently, but not all. Even so, we might be able to still use it to make some of our CI builds run faster. We may want to experiment with this.

The following is an untested braindump about how one might go about setting this up.

To use the emulator (on Debian), you must first install the gcloud SDK following: https://cloud.google.com/sdk/docs/downloads-apt-get. You'll also need to install the emulator apt pkg. To make the `gcloud` command available from within a docker image that will run the tests, you may want to add something like the following to the right `Dockerfile.<distro>` file:

```
RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" \
    >> /etc/apt/sources.list.d/google-cloud-sdk.list

RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg \
    | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -

RUN apt-get update && \
    apt-get --no-install-recommends install -y \
    google-cloud-sdk \
    google-cloud-sdk-spanner-emulator
```

For non apt-based systems, you'll need to modify the commands (i.e., to use `yum`, maybe).

Then from within the `build-in-docker-bazel.sh` or `build-in-docker-cmake.sh` script, we'll want to start the emulator before running the tests. We'll also need to tell the tests which host and port the emulator is listening on (currently it's *always* "localhost:9010").

```sh
gcloud beta emulators spanner start &
export SPANNER_EMULATOR_HOST="localhost:9010"
... # for bazel, you'll need to use the --test_env= flag
```

Then, maybe the tests will talk to the emulator???

### Open issues/questions:
* If the emulator doesn't support *all* functionality, is it worth using at all? I mean, we'd need to not test certain code paths when using the emulator.
* Which builds would benefit the most from using the emulator? I'm thinking maybe "coverage" would be good. The actual "integration" builds seem like they may still benefit from hitting real prod so we're 100% sure that our code works with the *real* prod.

**Comment by coryan** [comment]
FYI, this has become more intriguing as the code coverage builds are the slowest (currently 31 minutes), 10 of which (at least) are spent running the spanner integration tests.
