### ISSUE TITLE
Implement an endurance test

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#4024]
@coryan suggested something along the lines of the following. He can chime in (or edit this comment) to correct me.

We'd need a binary that stresses various parts of the Spanner library over a long period of time. Some aspects of this binary are:

* It should run for a long time. Maybe 10 or maybe 24 hours.
* It's OK if it is only run manually by humans at first. But ultimately, we may want to have a process that runs it automatically each night.
* It should use multiple threads. Sometimes spiking to a large number of threads. This will stress the creation of Sessions.
* It should sometimes be silent for over an hour, to let sessions time out and potentially expires.
* It does not need to function as a full-blown *load test*. The goal is not to see how much load Spanner can handle. The goal is to use the library in a variety of real-world scenarios.

**Comment by coryan** [comment]
There is an effort to do this across all Spanner client libraries.  Should be done by 2022/Q2.

**Comment by coryan** [comment]
Strike 3, closing.
