### ISSUE TITLE
Re-evaluate SessionPool session allocation logic

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp#4029]
There are a few performance-related constraints on how `SessionPool::Allocate()` returns sessions:

* It should return a recently used `Session`.  This is because the backends cache `Session` information in memory for a short time (30 seconds, although we shouldn't assume the duration is guaranteed), so re-using a `Session` within ~30 seconds has a positive impact on performance.
* `Sessions` should be distributed across available RPC Channels.  If 100 Sessions are in use, performance will be better if we're using 25 Sessions each on 4 Channels vs. 100 Sessions on the same channel.

Currently, we implement this using a vector of `Sessions` that we treat as a stack (LIFO) - allocated sessions come from the end, and released sessions are put on the end.  However, when we allocate new `Sessions` we shuffle (using `std::shuffle()`) the entire vector.  This is somewhat expensive and also completely disrupts the LIFO ordering.

Another aspect to consider is identifying "old" Sessions that need to be refreshed (i.e. they're approaching the one hour timeout) or deleted (we'd prefer to delete older Sessions, so we can avoid having to refresh them, although in reality we probably mostly just want to avoid deleting sessions that are still in the backend cache).

So, we should consider a different mechanism that doesn't disrupt the LIFO ordering (especially not the "very recent" Sessions, ~30 seconds since last use), ideally makes refresh/delete logic simpler, and is computationally cheap (although, the number of sessions is likely ~a few hundred so it's not likely to be a huge issue).

Brad and I had discussed keeping per-channel `Session` stacks, and having `Allocate()` select which channel to use (either round-robin or perhaps the least-loaded).  I think we could do this relatively easily now, but it's not necessary for GA.

Another possibility is distributing newly allocated `Sessions` throughout the existing ones rather that shuffling.  We may be able to start inserting only after existing sessions that were last used > 30s ago. However, we have to consider the case where we initially allocate `min_sessions` sessions on multiple channels, where the calls will likely complete in close proximity, and it's very important to make sure those sessions are properly interleaved when we return them.

**Comment by devjgm** [comment]
Discussed. Closing for now. Will reopen if we decide to do something.
