### ISSUE TITLE
Consider having version numbers for dependencies as a variable in INSTALL.md

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/google-cloud-cpp#4030]
When going through the instructions in the INSTALL.md, users might want to install the latest release versions for some dependencies.

For example, the following section

```
cd $HOME/Downloads
wget -q https://github.com/c-ares/c-ares/archive/cares-1_14_0.tar.gz && \
    tar -xf cares-1_14_0.tar.gz && \
    cd c-ares-cares-1_14_0 && \
    ./buildconf && ./configure && make -j ${NCPU:-4} && \
sudo make install && \
sudo ldconfig
```

is useful if you're ok with cares-1_14_0, but if you want to install c-ares 1_15_0 (the current latest), you can not just copy & paste.

How about to have the version number as a variable like:
```
export CARES_VERSION=1_14_0
cd $HOME/Downloads
wget -q https://github.com/c-ares/c-ares/archive/cares-${CARES_VERSION}.tar.gz && \
    tar -xf cares-${CARES_VERSION}.tar.gz && \
    cd c-ares-cares-${CARES_VERSION} && \
    ./buildconf && ./configure && make -j ${NCPU:-4} && \
sudo make install && \
sudo ldconfig
```
That way, you can copy & paste most of the shell commands for installing any version.

**Comment by devjgm** [comment]
We changed most/all of our install instructions to use the pattern
```
RUN curl -sSL https://github.com/nlohmann/json/archive/v3.9.1.tar.gz | \
    tar -xzf - --strip-components=1 && \
    cmake \
...
```
And in that pattern, the version number is only listed once. So I think this should address the original request above in a different way.
