### ISSUE TITLE
Consider introducing "PREFERRED_INSTANCE_CONFIG_FOR_TEST" environment variable

### ISSUE THREAD

**Issue by tmatsuo** [googleapis/google-cloud-cpp#4031]
Currently, in our integration tests for `InstanceAdminClient`, we first list all the `InstanceConfig` and pick the first one from the list for creating a new instance.

On the server side, there is a certain resource limit for each `InstanceConfig`. Picking the first one doesn't always work. If we know the right instance config to choose for the test, we can set this environment variable to instruct our test to pick the right `InstanceConfig` from the list.

**Comment by devbww** [comment]
In https://github.com/googleapis/google-cloud-cpp-spanner/pull/1403 we moved from using the first `InstanceConfig` to using a random one (that matches a regex), so I'm going to close this.
