### ISSUE TITLE
Improve logging configuration for integration tests

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#4034]
When an integration test fails we usually just get the last error, for example, consider this:

https://source.cloud.google.com/results/invocations/210ad400-3d02-47a9-9c6e-f108660c039a/targets/cloud-cpp%2Fspanner%2Fdocker%2Fmsan-presubmit/log

the only error message reads:

```
[ RUN      ] DatabaseAdminClient.DatabaseBasicCRUD
google/cloud/spanner/integration_tests/database_admin_integration_test.cc:134: Failure
Value of: metadata
Expected: is OK
Actual: Duplicate name in schema: Singers. [FAILED_PRECONDITION]
[  FAILED  ] DatabaseAdminClient.DatabaseBasicCRUD (67083 ms)
```

that is not enough to diagnose the problem, we have no idea if the test had to retry requests, what was the name of the project, instance, or database where this fails, or anything else.

I think we can do better, for example:

1. We could enable full tracing for all the integration tests, just set `GOOGLE_CLOUD_CPP_ENABLE_TRACING=cpp` and `GOOGLE_CLOUD_CPP_ENABLE_CLOG=yes` in the environment.  This will produce a lot of output, but would be mostly hidden.
1. We could also implement a fancy logger that preserves the last N messages, and logs them only if one of them is an error or when a test assertion fails.

See also: googleapis/google-cloud-cpp-spanner#679

**Comment by coryan** [comment]
FWIW, it seems this just repeated:


```
Running spanner_create_storing_index sample
Duplicate name in schema: AlbumsByAlbumTitle2.
================================================================================

[snip ... snip ... snip ...]

//google/cloud/spanner/integration_tests:session_pool_integration_test   PASSED in 31.5s
//google/cloud/spanner/samples:samples                                   FAILED in 51.5s
  /h/.cache/bazel/_bazel_kbuilder/a7ecd8237744645c5d189c197108d6d2/execroot/com_github_googleapis_google_cloud_cpp/bazel-out/k8-fastbuild/testlogs/google/cloud/spanner/samples/samples/test.log
```

https://source.cloud.google.com/results/invocations/a27264ec-f166-42d7-8db2-e3cbab0815c2

**Comment by mr-salty** [comment]
note that was in a sample rather than an integration test.
I filed #4758 so we have a separate issue for the flake itself independent of "improve logging"

**Comment by devbww** [comment]
Option 1, "enable full tracing for all the integration tests", proved infeasible ... too much output.  See #5626, #5627, and #5636.

Option 2, "implement a fancy logger that preserves the last N messages" is already covered in #662, so I'll leave this issue closed.
