### ISSUE TITLE
Add git commit hash to bazel builds

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#4035]
We try to stamp our builds with a "git commit hash". [Here's how we get this info](https://github.com/googleapis/google-cloud-cpp-spanner/blob/master/google/cloud/spanner/CMakeLists.txt#L30) in our CMake builds. This info is exposed in C++ in the `g::c::s::internal::BuildMetadata()` function [here](https://github.com/googleapis/google-cloud-cpp-spanner/blob/master/google/cloud/spanner/internal/build_info.h#L73).

The problem is that it's unclear how to get this info from bazel, so currently our bazel builds always report a git hash of "unknown".
https://github.com/googleapis/google-cloud-cpp-spanner/blob/master/google/cloud/spanner/BUILD#L26

This issue is to try to do the following:

Figure out how to get the git commit hash (i.e., ` git rev-parse --short HEAD`) when running a bazel build. This should work when our library is built directly, AND when it's build as a dep of some other project.

Some notes:

* Running the `git` command directly in a `genrule` doesn't work because it is executed in an environment without the `.git/` directory structure. It *might* work to add `.git/**` to the `srcs` attribute of the `genrule`, but I haven't tried this.

* Using bazel's `--workspace_status_command=` argument *does* work. Almost. It works when one specifies that flag. And we could add that flag to all of our bazel invocations by adding it to our `.bazelrc` file. However, this would not get picked up and used when our project is a dep of another, which is probably the common case.

Related to PR googleapis/google-cloud-cpp-spanner#278

**Comment by coryan** [comment]
https://kchodorow.com/2017/03/27/stamping-your-builds/ might be useful.

**Comment by remyabel** [comment]
This seems relevant: https://github.com/bazelbuild/bazel/issues/4464
