### ISSUE TITLE
Cannot determine `IsPermanentFailure()` from existing `RetryPolicy` 

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp#4042]
I am creating a version of bigtable's `async_retry_unary_rpc.h` for spanner, but there is no `IsPermanentFailure()` call on spanner's `RetryPolicy`, which the retry logic uses (although, only to generate an error message).

bigtable's policies wrap the common policies to include this method, but I wasn't sure we'd want to make that change in spanner, and since all the existing spanner policies end up using `internal::SafeGrpcRetry` I decided to just call `IsPermanentFailure()` on that instead.

note the spanner policies are currently just aliases for types in `google-cloud-cpp-common`, so if we change anything we should probably change it there.

I'm creating this bug before the code is submitted so I can reference it in a TODO.

**Comment by coryan** [comment]
This may have become easier to fix as part of the #4912 changes.

**Comment by mr-salty** [comment]
This was originally bug 1388 in spanner, and the TODO I mentioned was removed in https://github.com/googleapis/google-cloud-cpp-spanner/pull/1441

[async_retry_unary_rpc:125](https://github.com/googleapis/google-cloud-cpp/blob/ededf6c3577883b79a9b3511e40da588194c501f/google/cloud/internal/async_retry_unary_rpc.h#L125) still calls `IsPermanentFailure()` on the `RpcRetryPolicy` although I'm not sure if that's really still an issue (and I'm having trouble recalling why I thought it was to begin with).  So, I'm inclined to close this
