### ISSUE TITLE
Speed up clang-tidy build

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#4057]
This build is too slow, it is taking over 35m to run.

**Comment by coryan** [comment]
@devjgm discovered this:  https://gitlab.kitware.com/cmake/cmake/-/merge_requests/1791

Our build command line looks like this:

```
cd /v/cmake-out/ci-fedora-install-31-clang-tidy/google/cloud/spanner && /usr/bin/ccache /usr/bin/cmake -E __run_co_compile --tidy="/usr/bin/clang-tidy;--extra-arg-before=--driver-mode=g++" --source=/v/google/cloud/spanner/version.cc -- /usr/bin/clang++   -I/v -I/v/cmake-out/ci-fedora-install-31-clang-tidy  -g   -std=gnu++11 -o CMakeFiles/spanner_client.dir/version.cc.o -c /v/google/cloud/spanner/version.cc
```

Which is not what we want... The version of CMake used for this is:

```
$ cmake --version
cmake version 3.17.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

Which suggests that patch should be in.

**Comment by devjgm** [comment]
https://reviews.bitcoinabc.org/D5150?id=15995 suggests that the issue may be related to using a `RULE_LAUNCH_COMPILE` property, [like we do](https://github.com/googleapis/google-cloud-cpp/blob/87d600391bb245fe7734ded9d032de595bd21f8d/CMakeLists.txt#L96-L99), vs something like `set(CMAKE_CXX_COMPILER_LAUNCHER ${CCACHE_PROGRAM_PATH})`.

**Comment by coryan** [comment]
Yup, I am testing that right now.
