### ISSUE TITLE
`ObjectWriteStream` sync to server without `Close()`

### ISSUE THREAD

**Issue by vnvo2409** [googleapis/google-cloud-cpp#4066]
**What component of `google-cloud-cpp` is this feature request for?**
`google/cloud/storage`

**Is your feature request related to a problem? Please describe.**
In fact, I am implementing Google Cloud Storage API for Tensorflow. I would like to have an `ObjectWriteStream` which can sync to server without close the temporary `std::basic_ostream<char>`. I know that object of GCS can not be appended but I want to provide a feeling that is the same as on local filesystem to the users.

**Describe the solution you'd like**

Here is a psuedo-code
```cpp
ObjectWriteStreamCustom f; // Create a temporary ostream
f.open("gs://bucket/object");
f << "abc"

// Create an object in cloud. Both temp ostream and object have the same content "abc"
f.sync(); 

// Append to ostream. ostream now is "abcdef"
f << "def"

// Overwrite the old object with a new object whose content is "abcdef"
f.sync();

// Curently, we can only save file to server by calling Close()`
f.close();
```

**Describe alternatives you've considered**
Till now, I create a struct with a fstream
```cpp
typdef struct f {
    std::fstream file;
    gcs::Client cl;
}

Sync() {
    // The code to move data from fstream to basic_stream.
    // This code may cause error when fstream is a super large file (for example, dataset to train AI)
    // Because we need to allocate a large enough buffer to hold fstream and after that
    // we read the buffer into ObjectWriteStream, so we likely have 3 copy of a dataset.
    // if writer support Sync(). I won't even need the struct nor the temporary fstream.
    // In addition, transfering data between streams in c++ is usually not a good pratice
    int size = f.file.tellp();
    char* buffer = malloc(size);
    auto writer = f.cl.WriteObject(bucket, object);
    writer.read(buffer, size);
    writer.Close();
}
```

**Comment by coryan** [comment]
I thought TensorFlow already had GCS support?

In any case, what you want to do, sounds hard.  Let me make sure sure I follow:

- You want folks to be able to read a section of a GCS object?  That is possible today using the `gcs::Range()` option. But maybe you want more?

- Or you want folks to be able to read a section of a GCS object and then skip or rewind to a different section?  That is not possible today, you could try to implement this using a library like you describe and maybe some sort of cache.  That is, when the application reads bytes [1, 1000] you save them before returning them to the rest of the application.  When they ask for bytes [500, 1500] you can just read the bytes that are missing ([1001, 1500]) and return the union.

- If you want or need to offer an iostream API then I would start by looking at the Boost.IOStream library, it may have functionality to compose iostream objects (not sure, but worth looking before reinventing that wheel)

- Do you want to be able to write in the middle of a GCS object?  That will be very hard. You basically would be trying to implement POSIX semantics over an  immutable object store.
  - You could avoid storing large files and just store "chunks" that then you reassemble in whatever API you expose, so rewriting in the middle does not change that much data.
  - Or implement some kind of log-based filesystem.
  - Or stream all the bytes before the change to a temporary object, then stream the changed bytes to a second temporary object, and then stream the trailing bytes to a third temporary object and finally use `gcs::Client::Compose` to join them.  That would be *very* slow too.

**Comment by vnvo2409** [comment]
Sorry, I have misexpressed myself about what I needs.
https://github.com/googleapis/google-cloud-cpp/blob/1b8f971101ee7547c9346bca78694d9176844c06/google/cloud/storage/object_stream.h#L240-L254
Here is how `Close()` works with `ObjectWriteStream`. I would like to have a `Sync()` which works extractly the same as `Close()`works except `close the stream`. Instead, it sets a bool variable, let's say `bool need_sync` to `false`. Each call to `Close()` and `Sync()` will check that variable to see that if it needs sync or not. In case it need sync, we will ***overwrite the object on cloud with a new object, not append to the object on cloud***. Each function that modify the stream will set `need_sync` to `true`

**Comment by vnvo2409** [comment]
`DownloadToFile` and `UploadFile` seem to be what I need. I'm sorry for not reading carefully the documents. Thank you for your help

**Comment by coryan** [comment]
No problems.  You may want to take a look at `storage::ParallelUploadFile()` if you are uploading particularly large objects:

https://googleapis.dev/cpp/google-cloud-storage/latest/namespacegoogle_1_1cloud_1_1storage_1_1v1.html#aa7c3ff7d43779f608cb2e814cb4386f1

**Comment by vnvo2409** [comment]
Thank you. I have to deal with particularly large objects so `ObjectReadStream` and `ObjectWriteStream` which are stored in memory aren't what I need. I will take a look at `storage::ParallelUploadFile()` as well.
