### ISSUE TITLE
Split spanner integration tests that cannot use the emulator

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#4080]
**What component of `google-cloud-cpp` is this feature request for?**

Cloud Spanner

**Is your feature request related to a problem? Please describe.**

Some of the integration tests and examples cannot run against the emulator. The tests detect when the emulator is in use and return immediately (via `GTEST_SKIP()` or something similar).

**Describe the solution you'd like**

If we can split them to separate programs then we can label the program as `integration-test-no-emulator` and the CI scripts will run them against production. Best of both worlds?

**Describe alternatives you've considered**

Run all the tests against production works, but it is too slow in the `coverage` build.

**Comment by devjgm** [comment]
Closing. Things are working fine as they are now.
