### ISSUE TITLE
Enable CI tests linking against current code as DLL

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#4090]
Related to:
_Originally posted by @coryan in https://github.com/googleapis/google-cloud-cpp/issues/2309#issuecomment-627286503_

Today, we have the `windows/quickstart-dll` build that tests linking against our installed libraries as a DLL. That's good, but the quickstart builds link against the currently *released* version of our code, not the version at HEAD.

It would be good to create a CI build that tests linking against our code as a DLL/.so using our current HEAD rather than the release. This will allow us to detect errors before we cut the release.

**Comment by coryan** [comment]
Changed the title because we have a build for `.so`: `ci/kokoro/docker/shared` does that.

**Comment by coryan** [comment]
This might be useful:

https://docs.bazel.build/versions/master/command-line-reference.html#flag--override_repository

**Comment by devjgm** [comment]
Dropping this. Can reconsider when our deps (e.g. protobuf) support compiling as DLL.

**Comment by coryan** [comment]
See #5849
