### ISSUE TITLE
Create a build for Clang-11

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#4093]
The latest version of Clang is 10.  We should probably update the clang-9 build, and maybe rename it to clang-latest.

Fedora:32 includes this compiler, so does Ubuntu:20.04.

**Comment by devjgm** [comment]
FWIW, https://github.com/googleapis/google-cloud-cpp/pull/4511 changes the msan build to use clang 10. I'm not sure if that satisfies this issue, or if we still want another "clang-latest" build.

**Comment by remyabel** [comment]
Fedora 33 has Clang 11 now. Did we still want a Clang 10 build specifically?

**Comment by coryan** [comment]
I think we just wanted "latest", or "latest that it is easy to install".  clang-11 would be great.

**Comment by coryan** [comment]
This has been replaced by #5764.
