### ISSUE TITLE
YouTube access

### ISSUE THREAD

**Issue by forderud** [googleapis/google-cloud-cpp#4114]
I don't get any hits when searching for "youtube" in this repo. Therefore, assuming that YouTube is not yet supported.

It would be a nice extension to be able to access the YouTube APIs and upload movies programmatically using this library.

**Comment by devjgm** [comment]
@forderud thanks for the feature request. While the primary focus of the libraries in this repo are *Google Cloud* APIs, of which YouTube is not one, I realize that from the outside users don't care about that detail -- they just see Google products and want good APIs to access them. And I completely agree with that. We also have a broader goal of making C++ work great for all of Google's customers and products. So I'm going to leave this feature request open for a bit, and we'll see what happens. Thanks.

**Comment by devjgm** [comment]
I'm going to ask internally to see what the YT team would like to do about this.

**Comment by devjgm** [comment]
I've forwarded this request to the YouTube team. They're aware of it. I can't really comment further one way or the other. But they'll be responsible for this request from here.
