### ISSUE TITLE
gcloud crashed (TokenRevokeError): invalid_request when running tests

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp#4115]
This doesn't make the tests fail, but I've been looking at a lot of test logs today and see it in most or all of them.

We should decide if it's really a `gcloud` bug as the message suggests or if there's anything we can do to fix it (does `gcloud` need to be updated, or are we holding it wrong?)

```
2020-05-13T18:22:24Z: Create the gcloud configuration for the cloud-cpp tests.
Activated service account credentials for: [kokoro-build-uploader@cloud-cpp-integration-tests.iam.gserviceaccount.com]
Updated property [core/account].
================================================================
2020-05-13T18:22:25Z: Downloading build cache cache-ci-fedora-31-asan.tar.gz from cloud-cpp-kokoro-results/build-cache/google-cloud-cpp
ERROR: gcloud crashed (TokenRevokeError): invalid_request

If you would like to report this issue, please run the following command:
  gcloud feedback

To check gcloud for common problems, please run the following command:
  gcloud info --run-diagnostics
The following configurations will be deleted:
 - cloud-cpp-integration
Deleted [cloud-cpp-integration].
```

**Comment by mr-salty** [comment]
This is still happening [(example log from 2021-01-21)](https://source.cloud.google.com/results/invocations/609669e1-a1a5-437a-b20e-d777d5a6885f/targets/cloud-cpp%2Fgithub%2Fgoogle-cloud-cpp%2Fmaster%2Fdocker%2Fintegration/log).  It's just log spam and doesn't seem to hurt anything, so I'll leave it up to someone else whether it's worth worrying about.

**Comment by coryan** [comment]
AFAICT we no longer use the build script that had this problem, and the specific step is gone too.  Closing as it seems obsolete.
