### ISSUE TITLE
[Flake] Standard C++ exception raised: Socket closed

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#4119]
Here's a flake from the `macos/cmake-super-presubmit` build ([full log](https://source.cloud.google.com/results/invocations/43cad785-afe5-4c78-b662-1dd4f2b39d4c/targets/cloud-cpp%2Fgithub%2Fgoogle-cloud-cpp%2Fmaster%2Fmacos%2Fcmake-super-presubmit/log)).

```
 89/105 Test #268: bigtable_examples_data_snippets .................................***Failed   19.78 sec
Running MutateInsertUpdateRows() example [1]
Row successfully updated
Running MutateInsertUpdateRows() example [2]
Row successfully updated
Running WriteSimple() example
Successfully wrote rowphone#4c410523#20190501
Running WriteBatch() example
Successfully wrote 2 rows.
Running WriteIncrement() example
Successfully updated rowphone#4c410523#20190501
Running WriteConditionally() example
Successfully updated row
Creating table tbl-data-1589403548-tdnncews

Preparing data for MutateDeleteColumns()
Row successfully updated
Running MutateDeleteColumns() example
Columns successfully deleted from row
Running MutateDeleteRows() example [1]
All rows successfully deleted

Preparing data for MutateDeleteRows()
Row successfully updated
Row successfully updated
Running MutateDeleteRows() example [2]
All rows successfully deleted

Preparing data for RenameColumn()
Row successfully updated
Row successfully updated
Row successfully updated
Running RenameColumn() example
Row successfully updated

Preparing data for multiple examples
Running Apply() example
Running Apply() with relaxed idempotency example
Running Apply() with custom retry example
Running BulkApply() example
All mutations applied successfully

Populate data for prefix and row set examples
Standard C++ exception raised: Socket closed

        Start 338: spanner_database_admin_integration_test
```

I seem to recall @devbww seeing similar issues recently also. I think they may have been on his Linux laptop, so perhaps not related to macOS.

**Comment by devjgm** [comment]
Another one, this time from the macOS bazel build.
https://source.cloud.google.com/results/invocations/510e852f-b29d-4b19-a788-8c42c15eb892/targets/cloud-cpp%2Fgithub%2Fgoogle-cloud-cpp%2Fmaster%2Fmacos%2Fbazel-presubmit/log

**Comment by coryan** [comment]
And here is a FD shutdown....

https://source.cloud.google.com/results/invocations/cf0f6f56-ff40-4a1e-bbca-f30cc79c5072/targets

**Comment by devjgm** [comment]
So far, these all seem to be from https://github.com/googleapis/google-cloud-cpp/blob/master/google/cloud/bigtable/examples/data_snippets.cc

**Comment by devbww** [comment]
> I seem to recall @devbww seeing similar issues recently also. I think they may have been on his Linux laptop

They were from a "real" machine, with good connectivity (i.e., in a DC).

And mine always seemed to come from the "Populate data for prefix and row set examples" phase.

**Comment by coryan** [comment]
Another one: https://source.cloud.google.com/results/invocations/efce7a98-b30e-4e1c-992c-5ea663c61383

**Comment by coryan** [comment]
Just a couple of observations.  The code here:

https://github.com/googleapis/google-cloud-cpp/blob/7072fb944e4f571b7d796b5b6d48ac26da938f96/google/cloud/bigtable/examples/data_snippets.cc#L575-L580

is generating non-idempotent mutations, which are **not** automatically retried, so if anything fails the function throws on the first failure (no retries) and the test fails.

Since this is (according to the comments) just populating data for the samples to run maybe we could use idempotent mutations.

Likewise here (the FD shutdown failures above):

https://github.com/googleapis/google-cloud-cpp/blob/7072fb944e4f571b7d796b5b6d48ac26da938f96/google/cloud/bigtable/examples/data_snippets.cc#L109-L126

As to why this is happening more now: we used to not run integration tests on macOS, so if transient failures are common there we would not have noticed.

**Comment by coryan** [comment]
A different version of this problem continues to happen:

https://source.cloud.google.com/results/invocations/8cef6d14-741b-45c6-86a8-53f01a8597aa

**Comment by coryan** [comment]
And again. This one is interesting because it is on macOS+Bazel:

https://source.cloud.google.com/results/invocations/26acc800-e9e4-4f86-96e2-7701c181b343/targets

That rules out the SSL library (we use BoringSSL with Bazel).

**Comment by coryan** [comment]
I ran this 300 times on my laptop, without problems.

**Comment by coryan** [comment]
Another 300 runs with Bazel, built on the command line, no crashes on my laptop.

**Comment by coryan** [comment]
Well, this is annoying, I modified the CI script to run this test 100 times and it passed:

https://source.cloud.google.com/results/invocations/015f3784-d2d2-43bc-a7dc-59f05a143dd4

**Comment by coryan** [comment]
Another one:

https://source.cloud.google.com/results/invocations/809f0bb1-4297-40a1-b9d0-a42a7a95ef2d

**Comment by coryan** [comment]
A new variation, still on macOS, this time CMake:

```
Running the AsyncReadModifyWrite() example
libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: AsyncReadModifyWriteRowImplnon-idempotent operation failed, last error=Socket closed
*** SIGABRT received at time=1590008385 ***
```

https://source.cloud.google.com/results/invocations/43d807df-17f6-4211-8caa-e8cc8b6138e3/targets

**Comment by coryan** [comment]
https://source.cloud.google.com/results/invocations/3b4a017e-0160-4d6b-bb8d-91ce9c0ae2f1

I might stop reporting these.

**Comment by coryan** [comment]
https://source.cloud.google.com/results/invocations/140a43c2-7ae6-448a-afa7-3ebcd00e53b5/targets

**Comment by coryan** [comment]
https://source.cloud.google.com/results/invocations/e1422486-1b54-445c-a0c9-8facafe36e03/details

**Comment by coryan** [comment]
https://source.cloud.google.com/results/invocations/04b4a7b5-c84f-483a-ac5b-d8372f89a06b

**Comment by coryan** [comment]
I forgot about https://github.com/googleapis/google-cloud-cpp/issues/4119#issuecomment-631729431 above, that is quite different, a lot less common, but not fixed by #4281

**Comment by coryan** [comment]
Seems like we missed a few:

https://source.cloud.google.com/results/invocations/e51fe8e1-f1fa-46a5-93f9-190534e35f9f

**Comment by coryan** [comment]
The latest changes should make it less likely to run into this flake. We should close if there are no repeats.

**Comment by devjgm** [comment]
It's been over 90 days with no repeats, so closing (per the previous comment).
