### ISSUE TITLE
Invalid SOVERSION for the gRPC utils library

### ISSUE THREAD

**Issue by sjoubert** [googleapis/google-cloud-cpp#4128]
Following d97387496873db54ea4b04ef6baa83355b6a6268 it seems the variables used to set the `VERSION` and `SOVERSION` properties of the `google_cloud_cp_grpc_utils` target library are not defined anymore.
https://github.com/googleapis/google-cloud-cpp/blob/3d550c851f6a8519f76ae7d407572c79bfafb848/google/cloud/CMakeLists.txt#L346-L347
This results in the string `SOVERSION` being used as the version value and no soversion being set.

**To Reproduce**
1. Enable the gRPC utils (`GOOGLE_CLOUD_CPP_ENABLE_GRPC_UTILS=ON`)
2. Build
3. The resulting library in `<build>/google/cloud/` is named libgoogle_cloud_cpp_grpc_utils.so.SOVERSION`

**Expected behavior**
The resulting library and a associated symlink with the appropriate numeric values as version suffixes (probably `${GOOGLE_CLOUD_CPP_VERSION}` and `${GOOGLE_CLOUD_CPP_VERSION_MAJOR}`)

**Context**
* Linux Debian testing/bullseye
* google-cloud-cpp version 1.13.0
* CMake 3.17.1

**Comment by devjgm** [comment]
Thanks for the bug report! On first glance, your analysis of the problem looks right. Let me repro locally, then come up with a PR.

**Comment by devjgm** [comment]
@sjoubert I'm testing https://github.com/googleapis/google-cloud-cpp/pull/4131. If you'd like to patch in that PR and let us know if it indeed fixes the issue you saw, that'd be great. Otherwise, I think I've repro'd it locally and I think it fixes the issue.

**Comment by sjoubert** [comment]
> @sjoubert I'm testing #4131. If you'd like to patch in that PR and let us know if it indeed fixes the issue you saw, that'd be great. Otherwise, I think I've repro'd it locally and I think it fixes the issue.

It fixes the issue on my side too. Thanks!

**Comment by devjgm** [comment]
Thanks again for the bug report @sjoubert.
