### ISSUE TITLE
Need a CI build that detects incorrectly installed .so files

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#4132]
We had a bug report (https://github.com/googleapis/google-cloud-cpp/issues/4128) that pointed out that the grpc_utils .so was being installed without a version. The issue was that we were using the wrong variable in the `google/cloud/CMakeLists.txt` file (fix PR: https://github.com/googleapis/google-cloud-cpp/pull/4131).

We should have a CI build to detect when/if this happens. We perhaps need a new `ci/kokoro/install` build to detect these cases.

**Comment by coryan** [comment]
See https://github.com/googleapis/google-cloud-cpp/issues/4265#issuecomment-634147864 it seems like improperly installed `.so` files still "work".  That suggests to me that no build checking for breakage will do the trick.

But we could add a step to the CI scripts that searches for files with unexpected extensions. In principle we only install files matching a few patterns, like with `.*\.h`, `.*\.inc`, `.*\.proto`, `.*\.cmake`, `.*\.pc`, `lib.*\.a$`, `lib.*\.so`, `lib.*\..so\.${GOOGLE_CLOUD_CPP_VERSION_MAJOR}`, `lib.*\..so\.${GOOGLE_CLOUD_CPP_VERSION}`
