### ISSUE TITLE
Fix namespace in testing_utils/assert_ok

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#4142]
https://github.com/googleapis/google-cloud-cpp/blob/d89ed054eaa3307b149c6d84361547faedb8d04c/google/cloud/testing_util/assert_ok.h#L22-L23

Should be `google::cloud::<inline-ns>::testing_util`

**Comment by coryan** [comment]
Looks like @devbww is fixing this, assigning.
