### ISSUE TITLE
Proposal: reduce configuration in docker/build.sh

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#4144]
Currently the `docker/build.sh` script does these things:

- Validate the build name
- Use the build name to determine the Docker image
- Use the build name to determine what script to run in side the docker image (which one of the `build-in-docker-*.sh` gets called)
- Use the build name to determine the source directory (`.` vs. `super/`) for CMake builds
- Use the build name to determine the Bazel configuration
- Use the build name to determine the CMake configuration and testing configuration of the build and passes it through environment variables.

I propose we refactor the work and move more of the responsibility to the `build-in-docker-*.sh` scripts.  The `build.sh` script would do this:

- Validate the build name
- Use the build name to determine the Docker image
- Use the build name to determine what script to run in side the docker image (which one of the `build-in-docker-*.sh` gets called)
- Call that script with the build name.

Then the `build-in-docker-*.sh` would use the build name to configure themselves.

I think it is obvious this will simplify `build.sh`. And because the `build-in-docker-*` will only need with configuring one build system, they will be simpler than the larger `build.sh` which knows how to configure *two* build systems.

Furthermore, we would have explicit variables in the script, instead of environment variables that are hard to trace.

**Comment by devjgm** [comment]
Sounds like a good idea.

**Comment by coryan** [comment]
This is now obsolete.
