### ISSUE TITLE
Implement storage::GrpcClient::PatchBucket

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#4162]

**Comment by vnvo2409** [comment]
@coryan 

gRPC Patch operations requires an `update_mask`. I am thinking that we will add a member variable `std::string update_mask` to `BucketMetadataPatchBuilder`

https://github.com/googleapis/google-cloud-cpp/blob/b48c41612cdf173d7435bdfe175bae0efce107d6/google/cloud/storage/bucket_metadata.h#L976-L979

Each time we call a `Set` or `Reset` function, we append that field to `update_mask` and return that `update_mask` to gRPC.

One more thing to consider, We need a `BucketMetadata`. We could parse it using `json_payload` from `PatchBucketRequest`. WDYT ?

**Comment by coryan** [comment]
`PatchBucket` and `PatchObject` will be some of the trickiest code in the plugin.  You may want to write a mini design doc.

> gRPC Patch operations requires an `update_mask`. I am thinking that we will add a member variable `std::string update_mask` to `BucketMetadataPatchBuilder`

Probably should be `std::set<std::string>` because the same field may be modified multiple times.

> Each time we call a `Set` or `Reset` function, we append that field to `update_mask` and return that `update_mask` to gRPC.

See above.

> One more thing to consider, We need a `BucketMetadata`. We could parse it using `json_payload` from `PatchBucketRequest`.

That would probably work.

Note that `Patch*` operations in gRPC cannot support partial patches to the `labels` field.  In gRPC `labels` is a map, you can set it, clear it, or reset it.  In JSON it is a sub-object, you can set a few labels, and clear others.

We probably need to return an error if the application tries to perform a `Patch*` operation that is not representable in gRPC.

**Comment by vnvo2409** [comment]
> Note that Patch* operations in gRPC cannot support partial patches to the labels field. In gRPC labels is a map, you can set it, clear it, or reset it. In JSON it is a sub-object, you can set a few labels, and clear others.

I learned it the hard way when working on the new emulator.

> We probably need to return an error if the application tries to perform a Patch* operation that is not representable in gRPC.

It is harder than it looks. Note that `ToProto` does not have any mechanic for indicating success/failure. This is the reason why I have to rewrite `CreateNotificationRequest` in #5687 to keep a `NotificationMetadata` rather than `json_payload`. With `json_payload`, we still could construct a `NotificationMetadata/BucketMetadata`, but it will fall silently if an error takes place. 

What do you think ?

**Comment by coryan** [comment]
> > We probably need to return an error if the application tries to perform a Patch* operation that is not representable in gRPC.
> 
> It is harder than it looks. Note that `ToProto` does not have any mechanic for indicating success/failure.

We control the `ToProto` functions, some of them could return `StatusOr<...>`. Alternatively, we can create a `GrpcClient::Validate(BucketMetadataPatchBuilder const&)` function that returns an error when the builder is not representable.  I think changing the interface for `ToProto()` is easier to maintain.

I see that you will need to change `PatchBucketMetadataRequest`, for clarity, maybe make that change in a separate PR?

**Comment by vnvo2409** [comment]
> I see that you will need to change PatchBucketMetadataRequest, for clarity, maybe make that change in a separate PR?

I will send you 2 PRs:

- First PR will implement an `update_mask` for `BucketMetadataPatchBuilder` and testing. For `PatchBucketRequest`, it needs an additional member variable `update_mask` for holding the `update_mask` from `BucketMetadataPatchBuilder` ( cause we don't keep `BucketMetadataPatchBuilder` inside `PatchBucketRequest` ).
- Second PR will implement `ToProto`, `GrpcClient::PatchBucket` and testing.

Is that okay for you ?

**Comment by vnvo2409** [comment]
one more thing, we should use `absl::*_hash_set` or `std::unordered_set` because according to #5634, we should prefer `absl` ?

**Comment by coryan** [comment]
> * First PR will implement an `update_mask` for `BucketMetadataPatchBuilder` and testing. For `PatchBucketRequest`, it needs an additional member variable `update_mask` for holding the `update_mask` from `BucketMetadataPatchBuilder` ( cause we don't keep `BucketMetadataPatchBuilder` inside `PatchBucketRequest` ).
> * Second PR will implement `ToProto`, `GrpcClient::PatchBucket` and testing.
> 
> Is that okay for you ?

Yes.

> one more thing, we should use `absl::*_hash_set` or `std::unordered_set`

`std::set<>`, `std::unordered_set<>` or `absl::*_hash_set<>` are all fine by me. The sizes are small enough, and the feature used rarely enough, that all of them will perform reasonably well.

> because according to #5634, we should prefer `absl` ?

That is a request, not a requirement, and only applies to `std::mutex`.

**Comment by vnvo2409** [comment]
@coryan 

The problem with `labels` is more complicated. Suppose that I have a bucket with labels: `{"key1" : "val1" }`. I want add one more label, so it becomes `{"key1" : "val1" , "key2" : "val2"}`
https://github.com/googleapis/google-cloud-cpp/blob/b48c41612cdf173d7435bdfe175bae0efce107d6/google/cloud/storage/client.h#L520-L523

We have `original` with `{"key1" : "val1" }` ( assume that the metadata comes from the previous operation ). 

With `REST`, we could pass `updated` with `{"key1" : "val1" , "key2" : "val2"}`, the `json_payload` will result in `{"key2" : "val2" }`

With `gRPC`, if we follow the same approach with `REST`, we will lost the first label ( `{"key1" : "val1" }` ). We have to clear the labels inside `original` before passing it to `PatchBucket`.

We could:
- Leave it as-is but users have to be aware of which `raw_client` they are using.
- Refactor `PatchBucketRequest`, get rid of `json_payload`.
- Have a `complex_option` and let user choose which behavior they want. ( something like `MergeLabels`, `OverrideLabels`, `UpdateLabels`, etc ).

WDYT ?

**Comment by coryan** [comment]
Thanks for describing the problem. Frankly I had not thought much about it.

https://github.com/googleapis/google-cloud-cpp/blob/b48c41612cdf173d7435bdfe175bae0efce107d6/google/cloud/storage/client.h#L520-L523

I think in principle we should carry the *intent* expressed by the caller through the different layers.  In this case the intent is to change the bucket to look like `updated`.  Admittedly that might be hard, or hard to do efficiently, with the current structure, but our goal is clear.

> We could:
> 
> * Leave it as-is but users have to be aware of which `raw_client` they are using.

Cannot say that I really like that, too much burden on the users migrating from REST to gRPC, and makes it impossible to retire gRPC at any point.

> * Have a `complex_option` and let user choose which behavior they want. ( something like `MergeLabels`, `OverrideLabels`, `UpdateLabels`, etc ).

I think we would want the current behavior to be preserved if the user does not use this option, which leaves us in the same place.

> * Refactor `PatchBucketRequest`, get rid of `json_payload`.

We should explore this path I think.  A few options:

* Just generate an error, as described below.
* Instead of calculating the minimal set of changes that produces the desired effect, calculate a set of changes that works for both gRPC and REST.  Specifically, instead of just creating the label additions, **always** replace all the labels. That works for both, right?
* Add new member functions to RawClient to express "this is a patch based on a diff of two bucket metadata operations". Then the `RawClient` can compute the optimal patch for its protocol.  This is more work

> 
> > We probably need to return an error if the application tries to perform a Patch* operation that is not representable in gRPC.
> 
> I think any `Patch` operation is representable in `gRPC`. It just produces unexpected result.

Well, that is what I mean by "not representable": it produces different results in gRPC and REST.   In your examplke, a patch that adds one label and leaves other labels untouched, and there is way to say *exactly* that in gRPC.

**Comment by vnvo2409** [comment]
> Just generate an error, as described below.

I think generating an error does not do anything helpful in easing the burdens on users when migrating to `gRPC` from `REST`, so I don't prefer this solution.

---

> Add new member functions to RawClient to express "this is a patch based on a diff of two bucket metadata operations". Then the RawClient can compute the optimal patch for its protocol. This is more work.

This is something I really want to do. However, my idea is getting rid of `json_payloads` in `gRPC`, since `BucketMetadataPatchBuilder` is using `nlohmann::json` underneath and it is heavily tied with `REST`. 

I think `PatchBucketRequest` should hold a 
```cpp
absl::variant<std::string /*json_payload*/, 
  std::pair<google::cloud::storage::v1::Bucket /* grpc metadata */,
  std::unordered_set<std::string> /* update_mask */> metadata;
```

and we will add a function, something like `PatchBucketRequestBuilder` to `RawClient` and let each client construct their own `PatchBucketRequest`.

So https://github.com/googleapis/google-cloud-cpp/blob/b48c41612cdf173d7435bdfe175bae0efce107d6/google/cloud/storage/client.h#L520-L525

will become 
```cpp
 StatusOr<BucketMetadata> PatchBucket(std::string bucket_name, 
                                      BucketMetadata const& original, 
                                      BucketMetadata const& updated, 
                                      Options&&... options) { 
  auto request = raw_client_-> PatchBucketRequestBuilder(bucket_name, original, updated);
```

WDYT ?

**Comment by coryan** [comment]
> > Just generate an error, as described below.
> 
> I think generating an error does not do anything helpful in easing the burdens on users when migrating to `gRPC` from `REST`, so I don't prefer this solution.

True enough.

> 
> > Add new member functions to RawClient to express "this is a patch based on a diff of two bucket metadata operations". Then the RawClient can compute the optimal patch for its protocol. This is more work.
> 
> This is something I really want to do. However, my idea is getting rid of `json_payloads` in `gRPC`, since `BucketMetadataPatchBuilder` is using `nlohmann::json` underneath and it is heavily tied with `REST`.
> 
> I think `PatchBucketRequest` should hold a
> 
> ```c++
> absl::variant<std::string /*json_payload*/, 
>   std::pair<google::cloud::storage::v1::Bucket /* grpc metadata */,
>   std::unordered_set<std::string> /* update_mask */> metadata;
> ```
> 
> and we will add a function, something like `PatchBucketRequestBuilder` to `RawClient` and let each client construct their own `PatchBucketRequest`.

Why not just two or  three overloads of `PatchBucket` in `RawClient`?  Creating a variant to pass to a single function that then needs to break out the variant seems like a complicated way to go about this?

BTW, this is why I think a small design document is important, you want to capture the proposed design, the alternatives, and why the alternatives are rejected.  Future engineers in the project (including you!) would like to know such things.

**Comment by vnvo2409** [comment]
You are right. I will try to publish a design doc by the end of this week. It will contain a summary of what we are dicussing so far and some potential solutions for this problem.

**Comment by vnvo2409** [comment]
Sorry. I am afraid that it will take a bit longer.

**Comment by vnvo2409** [comment]
I am sorry for putting this issue on hold for too long. First time writing a [design doc](https://drive.google.com/file/d/1eG1qHtm85To2MBnj9ZT-aspgsTsMFWib/view?usp=sharing). Please take a look at it! Thank you!
