### ISSUE TITLE
Implement storage::GrpcClient::GetObjectMetadata

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#4198]

**Comment by vnvo2409** [comment]
I could work on this feature and some easy grpc releated features ( list, get ). 

Is there anything I should be aware of ?

And I would like to have some guides for setting up a grpc sever .

**Comment by vnvo2409** [comment]
@coryan any thought ?

**Comment by coryan** [comment]
Oh, sorry, I thought I had responded but obviously did not.

> I could work on this feature and some easy grpc releated features ( list, get ).

Thanks for volunteering!  We would love to have your help, but please read below because you may find this less interesting when you hear more about it.

> 
> Is there anything I should be aware of ?

Right now, there is no emulator for GCS+gRPC, so all testing is either unit tests or must run against production. Furthermore, GCS+gRPC is not GA, and some RPCs are completely missing.  Obviously that makes it both harder than normal, and more expensive than normal as all production usage is charged (but we could -- maybe -- find a way to fix that).

> And I would like to have some guides for setting up a grpc sever .

Unfortunately there is none.  We could try to extend the current Python client to also support gRPC, but candidly I am not sure how hard or easy that would be.

**Comment by vnvo2409** [comment]
> Unfortunately there is none.

I am also looking for some links about gRPC+GCS in production since I could not find anything about GCS+gRPC in production either ( endpoint, request, response ).

> We could try to extend the current Python client to also support gRPC, but candidly I am not sure how hard or easy that would be.

I am thinking that gRPC and REST backend should be the same. The difference is the endpoint, the way we send request and the response the server returned, right ? If I am right, I could extend the current Python client to also support gRPC.

**Comment by coryan** [comment]
> > Unfortunately there is none.
> 
> I am also looking for some links about gRPC+GCS in production since I could not find anything about GCS+gRPC in production either ( endpoint, request, response ).

The endpoint is `storage.googleapis.com` that is documented (along with the gRPC request / responses) only the proto definitions here:

https://github.com/googleapis/googleapis/tree/master/google/storage/v1

Note that while the endpoint is public, there is an allow-list: your project or bucket is probably not in the list and would not be able to make the requests.

> 
> > We could try to extend the current Python client to also support gRPC, but candidly I am not sure how hard or easy that would be.
> 
> I am thinking that gRPC and REST backend should be the same. The difference is the endpoint, the way we send request and the response the server returned, right ?

In production the endpoint is the same, there is some negotiation done by the gRPC client library to switch from plain HTTP/2 to gRPC over HTTP/2.  We can make the testbench behave differently, at least initially, with a different endpoint for gRPC. We do something similar for XML vs. JSON where the endpoint is the same in production, but we split it for testing to keep the testbench simpler (at the cost of complexity in the `CurlClient` constructor).

> If I am right, I could extend the current Python client to also support gRPC.

That would be really neat.  I would start with different endpoints for the gRPC and HTTP/REST APIs. We can change the client library to work with that.  Once that is working we can think about how to merge the two endpoints in the testbench. What do you think?  In any case, sounds like we should create a bug to make the changes to the testbench first?  Maybe using the existing RPCs like `CreateBucket()`?

**Comment by vnvo2409** [comment]
I've created a new issue here #4751
