### ISSUE TITLE
Fix storage::ObjectMetadata's ToProto/FromProto test

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#4217]
It does not seem to test the acl() field.

**Comment by vnvo2409** [comment]
@coryan 

Could you elaborate this issue a little bit more ? Because I think it is already tested here.
https://github.com/googleapis/google-cloud-cpp/blob/9b7388d70ca66eb669a3170fffae1adcd01742e8/google/cloud/storage/internal/grpc_client_test.cc#L54-L61

**Comment by coryan** [comment]
Seems like an obsolete issue, we should remove the TODO and close this.
