### ISSUE TITLE
Audit spanner tests and RUN_SLOW_INTEGRATION_TESTS

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#4228]
In `-spanner` we used to `RUN_SLOW_INTEGRATION_TESTS` environment variable to turn on specific tests. I think the nightly builds set that to `backup,instance`, while the coverage build only set it to `backup`, and the other builds did not set it at all.

I believe we lost this when we moved to `-cpp`, and most (all?) the builds do not set this at all.

We need to audit how the variable is used in the code, and make sure the CI scripts are covering these cases. Note that `instance` turns on tests that have very limited quota and are *very* slow, so it cannot be just turned on everywhere (OTOH, we have an emulator now, so maybe we can turn it on for more builds).

**Comment by devjgm** [comment]
NOTE: We already use a `RUN_SLOW_INTEGRATION_TESTS` variable, but only in our macos/build.sh script. It's set to either "yes" or "no".

https://github.com/googleapis/google-cloud-cpp/blob/07cd8ee3118cd3ec549c4b45f1484088e0393287/ci/kokoro/macos/build.sh#L27-L31 

Our `google/cloud/spanner/...` code does check an environment variable named `RUN_SLOW_INTEGRATION_TESTS`, but it expects a value like "instance", or "backup", or "instance,backup". Not yes/no.

So I think nothing is using our current `RUN_SLOW_INTEGRATION_TESTS` varaible.

**Comment by coryan** [comment]
Thanks for looking into this, I know it is hard to untangle all the scripts sometimes.

> So I think nothing is using our current `RUN_SLOW_INTEGRATION_TESTS` varaible.

You probably know this: that is an oopsie. Effectively there are tests / examples that we wrote and are not running, that should make us sad.  We probably want to see how the variable was used in `-spanner` and copy that usage to `-cpp`.

nit: s/var**ai**ble/variable/

**Comment by devjgm** [comment]
Yep, my plan is to get these running in `-cpp`. I'm using this issue as my place for notes as I untangle a little bit of stuff.

**Comment by devjgm** [comment]
How did this work in `-spanner`? Back in the `-spanner` repo, `RUN_SLOW_INTEGRATION_TESTS` was only enabled (set to "instance,backup") in a `coverage` build.

https://github.com/devjgm/google-cloud-cpp-spanner/blob/e9f73518069f69f79ab8e74e69ea68babcc20a58/ci/kokoro/docker/build.sh#L86-L88

Other than that, these slow builds were not run.
