### ISSUE TITLE
clang-tidy incorrectly warns about unused using decls in .h files

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#4230]
In our `build-in-docker-cmake.sh` script, we have a couple optimizations around running clang-tidy, because it's super slow in a repo with lots of C++ source files.

In particular, this part: https://github.com/googleapis/google-cloud-cpp/blob/3adfb06ca8f7c2fd167e5da6d7b9875466ad4b69/ci/kokoro/docker/build-in-docker-cmake.sh#L139-L149

Runs clang-tidy only on the changed `.cc` and `.h` files. However, when we run clang-tidy on a `.h` file like `clang-tidy foo.h`, it sometimes complains about unused using declarations that are actually used in other .cc files.

For now, I think I may disable `misc-unused-using-decls` when checking header files. I'm not sure if there are other "unused" warnings that may also fire, but I haven't seen them yet. It's OK if we miss a warning during our presubmit CI runs, because the post-submit will do a full build and will catch any new errors.

**Comment by devjgm** [comment]
There's currently no action to take on this issue. The current problem was fixed by https://github.com/googleapis/google-cloud-cpp/pull/4223.

**Comment by coryan** [comment]
There is a similar problem with `readability-redundant-declaration`, using `friend` in the header may appear as unused.
