### ISSUE TITLE
Remove 'googleapis' from vcpkg

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#4249]
We archived the https://github.com/googleapis/cpp-cmakefiles repo. This repo was in vcpkg under the name 'googleapis'. After our June release, we should probably remove that package from vcpkg.

**Comment by coryan** [comment]
I *think* we want to make `googleapis` into an empty package that just depends on `google-cloud-cpp`, but I see what you mean.  We need to do something similar with `-spanner`.

**Comment by coryan** [comment]
Effectively this is done, there is a `googleapis` package, but it is simply an alias.
