### ISSUE TITLE
Use Abseil Time for our internal time parsing/formatting, etc 

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#4258]
We currently have non-trivial time formatting/parsing logic spread around in several files, including

https://github.com/googleapis/google-cloud-cpp/blob/master/google/cloud/spanner/date.cc
https://github.com/googleapis/google-cloud-cpp/blob/master/google/cloud/spanner/timestamp.cc
https://github.com/googleapis/google-cloud-cpp/blob/master/google/cloud/internal/parse_rfc3339.cc

And probably several more. My first thought was to consolidate these so that we're at least using a single implementation. However, now that we can use `absl/time/time.h`, we should probably just use that directly, or keep our own small wrappers around that (if there's reason to do so).

**Comment by coryan** [comment]
Is this just a refinement (or a dup?) of #3934 ?

**Comment by devbww** [comment]
I would say a dup, so I'll close this.

FTR, the work is covered under the "Audit and remove unnecessary code that is now redundant in the monorepo with Abseil" 2020Q3 OKR, so I'll start looking at it soon.
