### ISSUE TITLE
Can we drop GOOGLE_CLOUD_CPP_CLANG_TIDY?

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#4263]
I'm thinking/hoping that we can get rid of this whole `EnableClangTidy.cmake` file. Instead of using this file and setting the `CMAKE_CXX_CLANG_TIDY` option programatically, I think we can remove this file and then in `build-in-docker-cmake.sh:85` we could change

```sh
# OLD
cmake_extra_flags+=("-DGOOGLE_CLOUD_CPP_CLANG_TIDY=ON")
```
to
```sh
# NEW 
cmake_extra_flags+=("-DCMAKE_CXX_CLANG_TIDY=clang-tidy")
```

I think that would be simpler because we wouldn't need to detect and act on the CMAKE_VERSION to figure out if it works with clang-tidy. Instead, that's simply up to the user who installed a particular version of cmake and, if they have cmake >= 3.6, they can enable the clang-tidy checks using the standard instructions [described here](https://blog.kitware.com/static-checks-with-cmake-cdash-iwyu-clang-tidy-lwyu-cpplint-and-cppcheck/). Additionally, there's no need for us to provide the `GOOGLE_CLOUD_CPP_CLANG_TIDY` option, which is just another option for people to know about.

We could certainly consider/do this in a future PR, so it need not block you.

Thoughts?

_Originally posted by @devjgm in https://github.com/googleapis/google-cloud-cpp/pull/4262_

**Comment by devjgm** [comment]
See also https://github.com/googleapis/google-cloud-cpp/pull/4262#pullrequestreview-417169620 from @coryan from that same PR:

> FYI, the PR builds only run clang-tidy on modified files, but the full builds run clang-tidy on everything, so @devbww's comment is very important, the PR will pass, the build will fail (Brad, you can test this locally by passing the right KOKORO_... environment variables).

> Maybe we can stop clang-tidy from running on generated code? Or just disabled it for external/googleapis ?

**Comment by devjgm** [comment]
@devbww in https://github.com/googleapis/google-cloud-cpp/pull/4262#discussion_r429439135 you mentioned that changing to `-DCMAKE_CXX_CLANG_TIDY=clang-tidy` caused clang-tidy errors in generated code.

I was trying to repro that, basically w/ the intent of closing this issue as "can't do now" or something. But I couldn't repro this issue.

How were you able to demonstrate a problem using `-DCMAKE_CXX_CLANG_TIDY=clang-tidy`?

FWIW, the diff I used was:

```diff
diff --git a/ci/kokoro/docker/build-in-docker-cmake.sh b/ci/kokoro/docker/build-in-docker-cmake.sh
index 280832029..5ca1cb48c 100755
--- a/ci/kokoro/docker/build-in-docker-cmake.sh
+++ b/ci/kokoro/docker/build-in-docker-cmake.sh
@@ -82,7 +82,8 @@ if [[ "${CLANG_TIDY:-}" = "yes" ]]; then
   # part of the regular build.
   if [[ "${KOKORO_JOB_TYPE:-}" != "PRESUBMIT_GITHUB" && \
     "${KOKORO_JOB_TYPE:-}" != "PRESUBMIT_GIT_ON_BORG" ]]; then
-    cmake_extra_flags+=("-DGOOGLE_CLOUD_CPP_CLANG_TIDY=ON")
+    # cmake_extra_flags+=("-DGOOGLE_CLOUD_CPP_CLANG_TIDY=ON")
+    cmake_extra_flags+=("-DCMAKE_CXX_CLANG_TIDY=clang-tidy")
   fi
 fi
```

**Comment by devbww** [comment]
All I can say is that it fails for me.  Happy to supply logs.

Did you purge your `cmake-out/` tree?

**Comment by devjgm** [comment]
Removing `cmake-out/` did the trick. Now I see the same errors you do. Thanks.
