### ISSUE TITLE
Invalid VERSION value for pubsub library

### ISSUE THREAD

**Issue by sjoubert** [googleapis/google-cloud-cpp#4265]
The `VERSION` property value for the pubsub libraries seems invalid:
```
$ ls build/google/cloud/pubsub/libpubsub_client.so*
google/cloud/pubsub/libpubsub_client.so -> libpubsub_client.so.1
google/cloud/pubsub/libpubsub_client.so.
google/cloud/pubsub/libpubsub_client.so.1 -> libpubsub_client.so.
```
The `GOOGLE_CLOUD_CPP_VERSION` variable used to fill that property is not set in the context it is used:
https://github.com/googleapis/google-cloud-cpp/blob/d915c7f57fa407cf58e6c78ad5401657345da990/google/cloud/pubsub/CMakeLists.txt#L61-L63

Other libraries use the separate version variables `${GOOGLE_CLOUD_CPP_VERSION_MAJOR}.${GOOGLE_CLOUD_CPP_VERSION_MINOR}.${GOOGLE_CLOUD_CPP_VERSION_PATCH}`. I believe bigquery and spanner may have the same issue.

This is probably another case for #4132

**Context**
* Linux Debian testing/bullseye
* google-cloud-cpp d915c7f57fa407cf58e6c78ad5401657345da990
* CMake 3.17.1

**Comment by coryan** [comment]
Thanks for the detailed bug report.  Can you let us know how you detected the problem?  Visual inspection or did you have something fail?

**Comment by sjoubert** [comment]
Yes, visual inspection. By listing the installed files I noticed the missing version.
As far as I can tell, this is working even without a numeric value. It's just not a common pattern.

**Comment by coryan** [comment]
Thank you for filing these bug reports, they are very useful.  Pity it requires looking at the installed files, but still doable: we can change the CI scripts to search for files with "weird" patterns after installing the files.
