### ISSUE TITLE
Enable passwordless sudo in all our Dockerfiles

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#4272]
Sometimes when we're debugging a problem in a Docker image, such as if we run

```
./ci/kokoro/docker/build.sh integration bash
```

which drops us at a bash shell in the docker container for our integration tests, we need additional tools to help debug the problem. Installing tools, like `apt install <blah>` requires root. Currently, we can't sudo in our docker containers.

We should:

1. Install sudo in all of our docker images
2. Enable passwordless sudo for all in our images. I think we can do this latter step with something like the following in each Dockerfile:
```
RUN echo "ALL ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
```

**Comment by coryan** [comment]
Good idea, you may want to install `sudo` also... I think we do not install it and it may not be installed by default in the base image (distributions are competing on the minimal image size).
