### ISSUE TITLE
Enable Spanner+Emulator+Bazel tests

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#4297]
https://github.com/googleapis/google-cloud-cpp/blob/e01df8e3eb7e7d3c61c71dd7c59c1b713f8ff3e1/ci/kokoro/docker/build-in-docker-bazel.sh#L149

currently runs the Bigtable tests with an emulator using bazel (in the `ci/kokoro/docker/build.sh integration` build). However, it doesn't do the same for Spanner (or Storage). It runs the Spanner integration tests, but against prod, not the emulator.

We should probably enable the emulator.

**Comment by coryan** [comment]
May want to fix #4080 before doing this.

**Comment by devjgm** [comment]
Note: This issue may become even more important if we switch our coverage builds to use bazel (https://github.com/googleapis/google-cloud-cpp/pull/5070).

**Comment by devjgm** [comment]
FTR, a the Spanner integration tests hitting production took 4 min today. Not that this is high or low, but it's a data point. That's how much time we could potentially save.

**Comment by coryan** [comment]
I think this was fixed in #6812
