### ISSUE TITLE
Spanner: Implement CMEK support

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#4312]
Internal tracking: b/157706906

**Comment by devjgm** [comment]
Note: this work is currently blocked on us being able to get access to the protos.

**Comment by devjgm** [comment]
The CMEK protos are available in the `spanner_cmek` branch here: https://github.com/googleapis/googleapis/blob/spanner_cmek/google/spanner/admin/database/v1/common.proto

**Comment by mr-salty** [comment]
This is done aside from implementing a code sample, which I'll take care of:

Show how to create a database with an encryption key. In the same sample, call GetDatabase (or the equivalent) to verify that the encryption key is set as expected.

Region tag: *spanner_create_database_with_encryption_key*

**Comment by mr-salty** [comment]
geez, rebasing made a mess out of this issue's history.

this is done except for backup/restore, I will complete that and close this issue.
