### ISSUE TITLE
Create logging layer for Cloud Bigtable

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#4320]
The GCS and Spanner libraries have an (optional) layer to log every RPC sent and the corresponding response.

It would be nice to have a similar feature in Cloud Bigtable. This would require (probably) multiple changes, so the first step is to write them down here and then break down the work into smaller bugs.

**Comment by manish-qlogic** [comment]
As async apis might go away in bigtable for admin operations, it is decided to work only for synchronous apis. 

This task will be decided into 3 PRs.

- [X] logging client for `data_client`(#5515).
- [ ] logging client for `admin_client`.
- [ ] logging client for `instance_admin_client`.

**Comment by coryan** [comment]
I think this is done, thanks!
