### ISSUE TITLE
Spanner doc: Add sample showing CreateInstance

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#4347]
Internal reference: b/148418510

The internally referenced issue has a link to a spec doc and more details. Basically no client library in any language has this sample. So we want to coordinate so that all libraries implement a similar sample.

As an example, here's the PR adding this sample for C#: https://github.com/GoogleCloudPlatform/dotnet-docs-samples/pull/1072

**Comment by coryan** [comment]
It might be a matter of adding the right region tags to this:

https://github.com/googleapis/google-cloud-cpp/blob/f07d03d6f4bc2917608bb987ded48324147b81ad/google/cloud/spanner/samples/samples.cc#L67-L110
