### ISSUE TITLE
Consider: switch to absl::Status

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#4375]
[I'm filing this issue so we have somewhere to discuss this issue and record our thoughts, not necessarily to make the change.]

We currently use a custom `google::cloud::Status` class ([code](https://github.com/googleapis/google-cloud-cpp/blob/master/google/cloud/status.h)). It's designed to be essentially `absl::Status` ([code](https://github.com/abseil/abseil-cpp/blob/2946ac0dea49c894215a998aebb19d2f1d942909/absl/status/status.h)). Now that we have a dep on Abseil, we could consider replacing our custom class with an alias to `absl::Status`.

Having just done that in a scratch branch, here are the first differences that I see.

1. `absl::Status::message()` returns an `absl::string_view` rather than `std::string` like we do. That causes lots of build breaks.

2. `absl::Status` (the class) is marked `ABSL_MUST_USE_RESULT`, which means that if a function returns an `absl::Status`, the compiler will ensure that the status is not ignored. I think this is generally a good thing, but it also causes a few breaks in our code ([example](https://github.com/googleapis/google-cloud-cpp/blob/eff996fde79bf68a2e64393cb00ef3eab59385f2/google/cloud/storage/oauth2/compute_engine_credentials.h#L95)). 

There may be more, but those were the majority of the first breaks that I saw.

Both of those are A**P**I breaks. So if we consider our `Status` class to be part of our public API (which I think we do), then we'd have to consider this change an API breaking change. Therefore, it's not clear if/when we'd want to make such a change.

**Comment by coryan** [comment]
I think this code would work with our `Status` and break with `absl::Status` then?

```C++
Status Foo();

void F() {
  auto m = Foo().message();
  // use m here...
}
```

So there are also changes in behavior which would not be "detected" until run-time?

**Comment by devjgm** [comment]
Indeed. Functions returning `string_view` always worry me.

**Comment by devjgm** [comment]
... although, I think `auto m = F().x();` would always worry me. In that statement, I've no idea what `x()` returned. The only way to know if that's safe is to know exactly what `x()` returns and the `auto` hides that.

**Comment by devjgm** [comment]
After chatting w/ the team, we decided to wait until an `absl::StatusOr` is available, then we might consider taking an API break and adopting both classes... or we may decide that it's not worth it.

**Comment by coryan** [comment]
FTR, we discussed this internally and decided it is was not worth the breaking change.

Also, we neglected to write down this here, but `absl::StatusOr<>` lacks a `operator bool()`, this code works with `google::cloud::StatusOr<>`, but would fail to compile with `absl::StatusOr<>`:

```cc
StatusOr<T> x = ...;
if (!x) return;
```

**Comment by bduclaux** [comment]
Indeed, the lack of this operator would break a lot of customer code too !

**Comment by devjgm** [comment]
To add to what @coryan said, until it's clearer what Abseil's forward-looking API guarantees are, I think we should avoid Abseil _types_ in our public APIs.

**Comment by devjgm** [comment]
Based on the previous few comments, I think we should close this issue for now. We can re-open or start a new issue if/when we decide to move forward with `absl::Status` and `absl::StatusOr`
