### ISSUE TITLE
Authenticating GCS from within a kubernetes cluster

### ISSUE THREAD

**Issue by code-mc** [googleapis/google-cloud-cpp#4378]
Hi. I'm currently trying to get the GCS sample working in our kubernetes cluster hosted on google cloud. Kubernetes offers (as far as I'm aware) two approaches to authenticate with the google cloud services. One is the workload identity which provides temporary tokens and the other are mounted credentials using the "automountServiceAccountToken" option.

The workload identity approach provides a json file but once provided to this library it gives an error as there is no type field in the json. I've tried various type fields like "service_account", "authorized_user" and "anonymous". All seem to expect different json files.

The mounted credential approach also doesn't seem to work as that does not provide any json files. It mounts a token, namespace and ca.cert file. The token file looks like a bearer token, but I honestly don't know.

The third approach would be to generate the credential file outside the cluster and mount it when launching the cluster. But I'd rather not go with that approach as that doesn't seem very secure and CI/CD friendly.

Does anyone have any experience in authenticating from within a kubernetes cluster?

**Comment by coryan** [comment]
Are you running on GKE or your own cluster?  On GKE you should be able to use the metadata server to get credentials for the cluster's service account.  That might not be secure enough if you want to run workloads with and without access to GCS in the same cluster.

You can also use secrets and load a service account, as we do here:

t





> Hi. I'm currently trying to get the GCS sample working in our kubernetes cluster hosted on google cloud. Kubernetes offers (as far as I'm aware) two approaches to authenticate with the google cloud services. One is the workload identity which provides temporary tokens

I think that is the one you want, but using this:

https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#using_from_your_code

Starting with v1.13.0 (you did not mention what version of the library you were using, can you share?) the client library should be able to recognize that it is inside a GKE cluster (I think you are using GKE?  You mentioned k8s, but not GKE explicitly, maybe me assuming GKE is unwarranted) and use the cluster's metadata server to get access tokens.  You do not need to "mount" any files or set the `GOOGLE_APPLICATION_CREDENTIALS` environment variable, the library contacts the metadata service directly.

Mind you, we have not tested that configuration explicitly, so it is possible we missed something.

> and the other are mounted credentials using the "automountServiceAccountToken" option.
> 
> The workload identity approach provides a json file but once provided to this library it gives an error as there is no type field in the json. I've tried various type fields like "service_account", "authorized_user" and "anonymous". All seem to expect different json files.
> 
> The mounted credential approach also doesn't seem to work as that does not provide any json files. It mounts a token, namespace and ca.cert file. The token file looks like a bearer token, but I honestly don't know.

I suspect all those are not in the formats expected by the auth classes in the library.

> 
> The third approach would be to generate the credential file outside the cluster and mount it when launching the cluster. But I'd rather not go with that approach as that doesn't seem very secure and CI/CD friendly.
> 
> Does anyone have any experience in authenticating from within a kubernetes cluster?

I have used both these approaches in the past successfully:

https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity#alternatives

They are adequate for experiments and tests, but maybe not for deployments facing the Internet.

**Comment by mikedanese** [comment]
Can we leave this open until the GKE metadata server is fixed?

**Comment by coryan** [comment]
Sure.

**Comment by mikedanese** [comment]
This is ready to close. The fix is in gke-metadata-server > 0.3.6. I see the latest GKE versions in prod on 0.3.11 and 0.3.19. Thanks for the report!

**Comment by coryan** [comment]
Thanks for keeping us updated.  Closing.
