### ISSUE TITLE
Support DirectPath for Cloud Spanner

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#4381]
See the changes in #4379 for GCS, we need similar changes for Cloud Spanner

**Comment by coryan** [comment]
Actually it is simpler see #4388

**Comment by AditiThirdEye** [comment]
Hello @coryan , 
Can you please assign this issue to me, I would like to work on this.
Regards

**Comment by coryan** [comment]
This may not be a good starting issue for an external contributor, testing is fairly difficult.

**Comment by AditiThirdEye** [comment]
Hello @coryan ,
Okay, actually there are very few good first issue and me and my team is taking these as a part of major project hence was asking for assignment. But sure I was looking for good first issue, to start with.

Thanks

**Comment by coryan** [comment]
We will see how the work for Cloud Bigtable goes.

**Comment by coryan** [comment]
Still waiting for Bigtable.

**Comment by coryan** [comment]
Closing, does not look that the service teams are pushing for this.
