### ISSUE TITLE
Support DirectPath for Cloud Bigtable

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#4382]
See the changes in #4379, we need similar changes for Cloud Bigtable

**Comment by coryan** [comment]
Actually it is simpler see #4388

**Comment by AditiThirdEye** [comment]
Hello @coryan , 
Is the PR done? Otherwise,
I would like to solve this issue.

**Comment by coryan** [comment]
This is a OKR for this quarter.

**Comment by coryan** [comment]
@dbolduc  is working on it.
