### ISSUE TITLE
Use Spanner emulator for more

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#4387]
Features releasing in Emulator 0.8.0:
* Partition Read
* Partition Query
* Partition DML

We should update our tests to use the emulator for these tests.

**Comment by coryan** [comment]
Remember to update the CI builds to pick up a new emulator first.  I think we get it through the Cloud SDK, and this SDK is pinned to a specific version and therefore the emulator too.

**Comment by devjgm** [comment]
Fixed in https://github.com/googleapis/google-cloud-cpp/pull/4443
