### ISSUE TITLE
GCS user-agent prefix info doesn't seem to be showing up correctly on the server

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#4400]
If I look at the server-side data to see the language version being used, it's null. Not sure if somethings wrong in my sql (likely) or in the client library. This issue is to not forget about this and track the fix.

**Comment by mr-salty** [comment]
sounds like we're not sure if this was an issue with the query or the library; dropping to p3 for now.

**Comment by coryan** [comment]
Closing, my recollection is that we established this was how the pipelines work (or fail to work) in the backend.
