### ISSUE TITLE
Troubleshoot problems with SampleRowKeys()

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#441]
On Fedora (and only on Fedora) the regression tests freeze from time to time.  No responses are recorded in the test.

**Comment by coryan** [comment]
Well, I just saw it freeze on Ubuntu, which I guess is good news because it means this is not platform specific?  Note that this could be in gRPC or in the emulator or in the client library.

**Comment by coryan** [comment]
Here is a example of a frozen build:

https://travis-ci.org/coryan/google-cloud-cpp/jobs/368372069

**Comment by hemant-qlogic** [comment]
I also got this problem while running tests on ubuntu-16.04
Here is the link
https://travis-ci.org/GoogleCloudPlatform/google-cloud-cpp/jobs/372332188

**Comment by DanielMahu** [comment]
Some signs point to an emulator bug. I've run this locally with some added arguments:
```
  --gtest_filter='*SampleRow*' \
    --gtest_repeat=1000 --gtest_break_on_failure
```
and after 206 iterations of the test, output stopped and the emulator window had a crash with the message `fatal error: concurrent map iteration and map write`. I can take a look at this.

@hemant-qlogic please file a different bug for the unit test, it's a separate issue.

**Comment by coryan** [comment]
@garye who has implemented most of the emulator and might want to hear about it.

**Comment by garye** [comment]
Can you point me to a test that is failing?

**Comment by hemant-qlogic** [comment]
Added new issue for table_admin_test no response case in #470

**Comment by coryan** [comment]
@garye the specific test that breaks is here:

https://github.com/GoogleCloudPlatform/google-cloud-cpp/blob/master/bigtable/tests/data_integration_test.cc#L549

The test is running against the latest gcloud emulator, we download the latest and greatest version before running the integration tests.  I will let the folks actually working on this bug to speak about results with a local build.

**Comment by DanielMahu** [comment]
The older emulator version on my laptop produced a crash dump with a stack trace inside hashmap code, which is pasted at the end of this comment, since it's no longer relevant: the implementation was changed meanwhile to btree in https://github.com/GoogleCloudPlatform/google-cloud-go/commit/781cba7caa1b7524afce83ae96e255d4d7a8ee69, which seems to have fixed the concurrency bug.

The versioning scheme of Cloud SDK still eludes me, there is a mix of large incremental numbers like 187.0.0, smaller incremental numbers like v0.21.0, and dates like 2018.04.30. In any case, the patch mentioned above is present since the end of January, and v0.18.0 and later of the google-cloud-go repo.

The failing log shows we were `Installing components from version: 187.0.0`. This was bumped to 199 in #467, so the issue should be gone now.

For the curious, here is the first part of the emulator crash dump:
```
[bigtable] fatal error: concurrent map iteration and map write
[bigtable]
[bigtable] goroutine 5074 [running]:
[bigtable] runtime.throw(0x14f8471, 0x26)
[bigtable] 	/usr/lib/google-golang/src/runtime/panic.go:608 +0x9e fp=0xc42028f920 sp=0xc42028f900 pc=0x102a1de
[bigtable] runtime.mapiternext(0xc42028fa48)
[bigtable] 	/usr/lib/google-golang/src/runtime/hashmap.go:778 +0x6f1 fp=0xc42028f9b8 sp=0xc42028f920 pc=0x1009d01
[bigtable] runtime.mapiterinit(0x144be40, 0xc427d2c540, 0xc42028fa48)
[bigtable] 	/usr/lib/google-golang/src/runtime/hashmap.go:768 +0x270 fp=0xc42028fa20 sp=0xc42028f9b8 pc=0x10093b0
[bigtable] cloud.google.com/go/bigtable/bttest.(*row).size(0xc424899fc0, 0x46)
[bigtable] 	/usr/local/google/home/garyelliott/go/src/cloud.google.com/go/bigtable/bttest/inmem.go:1230 +0x142 fp=0xc42028fb18 sp=0xc42028fa20 pc=0x13cd4a2
[bigtable] cloud.google.com/go/bigtable/bttest.(*server).SampleRowKeys(0xc420056300, 0xc422273760, 0x17598c0, 0xc421bdff10, 0x0, 0x0)
```

**Comment by coryan** [comment]
While it is a lot more rare, it is still happening. @garye to reproduce this download and compile `google-cloud-cpp`, the instructions are on the [README](https://github.com/GoogleCloudPlatform/google-cloud-cpp/blob/master/README.md) file.

The compile run the integration tests in a loop, because it does not happen every time, I used:

```console
cd build-output/bigtable/tests
while timeout 5m env  CBT=/usr/local/google-cloud-sdk/bin/cbt  CBT_EMULATOR=/usr/local/google-cloud-sdk/platform/bigtable-emulator/cbtemulator ../../../bigtable/tests/run_integration_tests_emulator.sh ; do date ; done
```


When I was able to reproduce the problem I got this [log](https://github.com/GoogleCloudPlatform/google-cloud-cpp/files/2042862/emulator.log) from the emulator.

The gcloud version I was using was:

```console
$ /usr/local/google-cloud-sdk/bin/gcloud --version
Google Cloud SDK 202.0.0
bigtable 
bq 2.0.33
cbt 
core 2018.05.18
gsutil 4.31
```

**Comment by coryan** [comment]
Removed the "bug" label because this is a bug in another system, not ours.

**Comment by coryan** [comment]
Marking this fixed. I ran the integration tests against a recent version of the emulator and it did not crash, I used 4 cores and ran each test 100 times.

**Comment by coryan** [comment]
Well, it seems I was wrong, I am seeing crashes in the CI build again.

**Comment by coryan** [comment]
Here is an example of a recent crash and its effect on the build:

https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/6583/315f8bef55392aa34b1646c788eca48004f8c8e1/fedora-33-cxx17/log-d91e8e79-4d34-4aa2-99de-57c86f5d0a85.txt

**Comment by coryan** [comment]
https://pantheon.corp.google.com/cloud-build/builds;region=us-east1/716efceb-e330-49b4-82f5-75bf8b768460;step=3?project=cloud-cpp-testing-resources

**Comment by coryan** [comment]
On second thought, I think #6981 fixed this issue.

**Comment by dbolduc** [comment]
https://source.cloud.google.com/results/invocations/01523fdf-8e51-49af-b611-b663d089ec31/targets/cloud-cpp%2Fgithub%2Fgoogle-cloud-cpp%2Fmain%2Fmacos%2Fbazel-presubmit/log
