### ISSUE TITLE
Use `-fsanitize=null`

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#4415]
For more nullptr detection. Our code is currently clean. Note: this flag can be run with asan (and the xsan build proposed in https://github.com/googleapis/google-cloud-cpp/pull/4414), so this need not be another build for us.

**Comment by coryan** [comment]
I think this is happening as part of #6083 ?

**Comment by devjgm** [comment]
Yes. Actually, it's done as of https://github.com/googleapis/google-cloud-cpp/pull/6090
