### ISSUE TITLE
windows/cmake-release build has been failing continuously since 18 June

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp#4425]
Last successful build was Jun 16, 2020, 5:05:06 PM EDT: [log](https://source.cloud.google.com/results/invocations/2217846a-df59-4f0b-9524-e9a552f5ad82/log)

First failure was Jun 18, 2020, 11:48:54 AM EDT: [log](https://source.cloud.google.com/results/invocations/eff2f336-8857-4ad7-b7c6-f465053b1a13/log)

The failures look like this:
```
261/262 Test #294: spanner_database_admin_connection_test ............................***Timeout 1500.01 sec
Running main() from gmock_main.cc
[==========] Running 48 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 48 tests from DatabaseAdminClientTest
[ RUN      ] DatabaseAdminClientTest.CreateDatabaseSuccess
..\..\google\cloud\spanner\database_admin_connection_test.cc(77): error: Expected equality of these values:
  std::future_status::ready
    Which is: 4-byte object <00-00 00-00>
  fut.wait_for(std::chrono::seconds(10))
    Which is: 4-byte object <01-00 00-00>

262/262 Test #298: spanner_instance_admin_connection_test ............................***Timeout 1500.01 sec
[...\
[ RUN      ] InstanceAdminClientTest.CreateInstanceSuccess
..\..\google\cloud\spanner\instance_admin_connection_test.cc(152): error: Expected equality of these values:
  std::future_status::ready
    Which is: 4-byte object <00-00 00-00>
  fut.wait_for(std::chrono::seconds(10))
    Which is: 4-byte object <01-00 00-00>
```

i.e. the `CreateDatabase` and `CreateInstance` calls did not complete in 10 seconds, and in fact did not complete in 25 minutes before the test timed out.  Note that both of these are operating on mock stubs, they are not making calls to the the spanner service or emulator.

**Comment by coryan** [comment]
/cc: @devjgm the first failure just included the `g::c::optional<T>` -> `absl::optional<T>` changes.  I do not think we want to revert, but I think maybe there is a subtle difference in behavior under MSVC.
