### ISSUE TITLE
Why ParallelUploadFile() requires a `Client` instead of `Client&`

### ISSUE THREAD

**Issue by vnvo2409** [googleapis/google-cloud-cpp#4435]
**What component of `google-cloud-cpp` is this related to?**
`google/cloud/storage`

**Describe the bug**
`ParallelUploadFile()` copy by value instead of reference or pointer
**Additional context**
If I want to upload many files, I have to create many copies of `Client`. This is not memory-efficient.

**Comment by coryan** [comment]
On my workstation `sizeof(Client)` is 16. A `gcs::Client` contains a single `std::shared_ptr<gcs::internal::RawClient>` and just the shared pointer (not its contents) are copied in each request.

> If I want to upload many files, I have to create many copies of `Client`. This is not memory-efficient.

Unless you are doing millions of uploads at a time, I suspect the extra 8 bytes (compared to a reference) won't matter.  

Also, I am curious as to why you would want to make so many uploads at a time that memory would become a problem.  The point of ParallelUploadFile() is to saturate the CPU/network-card/IO bandwidth.  If things are working well, more than a handful of ParallelUploadFile() running in parallel (on the same program) would just not make faster progress than the same calls to `ParallelUploadFile()` in series.  But I might be missing something about your application.

**Comment by vnvo2409** [comment]
Thank you. I understand now. I will close the issue.
