### ISSUE TITLE
Add ReadRange ( and maybe ReadFromOffset, ReadLast ) to UploadFile 

### ISSUE THREAD

**Issue by vnvo2409** [googleapis/google-cloud-cpp#4437]
**What component of `google-cloud-cpp` is this feature request for?**
`google/cloud/storage`

**Describe the solution you'd like**
I would like to add `ReadRange` to `UploadFile`, So I can upload only a part of the local file. This could solve the problem with file with infinite source
https://github.com/googleapis/google-cloud-cpp/blob/42b7087a20dbd8f013e823100d8bed05e154e9d4/google/cloud/storage/client.cc#L129-L130

**Describe alternatives you've considered**
Load the content to an `ObjectWriteStream` but it will be much easier to use `UploadFile`

**Additional context**
I think it is not too much complicated to implement this feature. With `UploadFileSimple`, we need to change this line
https://github.com/googleapis/google-cloud-cpp/blob/42b7087a20dbd8f013e823100d8bed05e154e9d4/google/cloud/storage/client.cc#L115
With `UploadFileResumable`, we need to add a offset to this line
https://github.com/googleapis/google-cloud-cpp/blob/42b7087a20dbd8f013e823100d8bed05e154e9d4/google/cloud/storage/client.cc#L165 
and change the condition of while
https://github.com/googleapis/google-cloud-cpp/blob/42b7087a20dbd8f013e823100d8bed05e154e9d4/google/cloud/storage/client.cc#L175-L176

I could work on this feature

**Comment by coryan** [comment]
This is a nice feature request.  Reusing `ReadRange()` is a bit worrisome, what do you think if we create a new option called `UploadRange()` (and maybe `UploadLimit()`)?

**Comment by vnvo2409** [comment]
So we will have 3 options:
- `UploadRange()` for upload from bytes start to bytes end
- `UploadLimit()` the maximum number of bytes to upload ( for file with infinite sources )
- `UploadFromOffset()` upload from an offset.
I will send you a PR for `UploadFile`

**Comment by vnvo2409** [comment]
Close by https://github.com/googleapis/google-cloud-cpp/pull/4473#event-3530049441
