### ISSUE TITLE
 Audit and remove unnecessary code that is now redundant in the monorepo with Abseil

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#4458]
This issue may spawn separate issues to clean up each of the redundant things that the audit finds. That's fine.

**Comment by coryan** [comment]
Some related bugs:

- #4375 - absl::Status
- #108 - absl::conjunction
- #4528 - time parsing
- #3990 - stack trace
- #3934 - time parsing

There are probably many more. Search for:

- uses of `std::getline()` as a version of `absl::StrSplit()`
- the string `char const* sep = ` probably as part of something that could be replaced by `absl::StrJoin()`.

**Comment by devjgm** [comment]
We may also want to replace our `google::cloud::Date` class with `absl::CivilDay`

**Comment by remyabel** [comment]
I did not see an issue for `absl::StrJoin` so I created https://github.com/googleapis/google-cloud-cpp/issues/5121.

**Comment by coryan** [comment]
@devjgm I think it would be useful to break down this issue into specific tasks, as-is, we never will know when we are "done".

**Comment by devjgm** [comment]
I think the only real remaining issue here was the time-parsing code changes, so I split that out into https://github.com/googleapis/google-cloud-cpp/issues/5426, and will close this issue.
