### ISSUE TITLE
Make it "easy" to run our integration tests against a staging server

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#4459]
If we're developing a new feature that isn't yet available on public-facing servers, we need a way to easily run our integration tests against a staging server. We already have "ENDPOINT" environment variable(s) that the C++ code should respect to do this, but there's currently no way to set the appropriate variables when running our integration tests with `ci/kokoro/docker/build.sh integration`. 

One solution might be to teach our `build.sh` script(s) how to forward the appropriate env vars from the invoker's environment to the environment that's run in the docker container.

**Comment by devbww** [comment]
For the record, the following now works to run the Spanner integration tests against a different endpoint:
```
$ GOOGLE_CLOUD_CPP_SPANNER_DEFAULT_ENDPOINT=alternate-server ci/kokoro/docker/build.sh integration
```
