### ISSUE TITLE
[flake] testbench failed to start for GCS integration test

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#4477]
Full log: https://source.cloud.google.com/results/invocations/08e3baea-eacb-4eba-be8a-bb30e08b3a05/targets/cloud-cpp%2Fgithub%2Fgoogle-cloud-cpp%2Fmaster%2Fdocker%2Fintegration/log

Relevant log snippet:

```
...
[ -------- ] Integration test environment set-up
Launching testbench emulator in the background
Cannot connect to testbench; aborting test.
/v/google/cloud/storage/tools/run_testbench_utils.sh: line 34: kill: (22995) - No such process
[ -------- ] Integration test environment tear-down.
Killing testbench server [22995] ... 2020-07-03T18:37:11Z: Docker run failed with exit status 1.
...
```

Relevant code:

https://github.com/googleapis/google-cloud-cpp/blob/2ce51b80562e0b9903d1eef9327eb58ac26fa50c/google/cloud/storage/tools/run_testbench_utils.sh#L100-L103

It's interesting that `testbench.log` was empty since the cat produced no output. However, a previous line ([line 74](https://github.com/googleapis/google-cloud-cpp/blob/2ce51b80562e0b9903d1eef9327eb58ac26fa50c/google/cloud/storage/tools/run_testbench_utils.sh#L74)) **successfully read the randomly chosen port from the file**, so it wasn't empty at that point.

**Comment by coryan** [comment]
This sounds like a dup of #4471, note that the code has been updated since.

**Comment by devjgm** [comment]
@coryan already found and fixed this issue in https://github.com/googleapis/google-cloud-cpp/issues/4471
