### ISSUE TITLE
Automate CHANGELOG.md creation during release

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#4479]
This step (https://github.com/googleapis/google-cloud-cpp/tree/master/release#update-changelogmd) in the release process seems fairly automateable. At least, we should be able to produce a fairly simple script that does much of that step, perhaps still requiring human intervention at the end to verify the produced text and maybe to send the PR.

**Comment by remyabel** [comment]
TIL I learned `git shortlog` is a thing. It shows commits in the format of:

```
Bradley White (8):
      test(spanner): correct guard on UpdateDatabaseDdlMetadata expectation (#5301)
      refactor(spanner): some simple CreateDatabase() refactoring (#5303)
      test(spanner): deflake benchmark database creation (#5395)
      fix: build problems with MSVC+x86 (#5435)
      cleanup(spanner): plumb ConnectionOptions into admin connection classes (#5519)
      cleanup(storage): use google.storage.v1.internal for internal protos (#5530)
      feat(spanner): Point-In-Time Recovery (lite) throttled DB update (#5562)
      chore: bump version numbers after v1.21 release (#5568)

Carlos O'Ryan (89):
      cleanup(pubsub): return types for ack/nack functions (#5245)
      cleanup(pubsub)!: make Subscriber more consistent (#5247)
      cleanup(pubsub)!: rename SubcriptionOptions (#5251)
      refactor(pubsub): consolidate integration tests (#5252)
      feat(pubsub): support subscription filters (#5253)
```

etc., similar to how the Linux kernel does it. It's different from the existing format of the CHANGELOG but this could be something to consider.

**Comment by coryan** [comment]
https://xkcd.com/1205/

**Comment by coryan** [comment]
I think this is done. The [changes.sh](https://github.com/googleapis/google-cloud-cpp/blob/main/release/changes.sh) script does a good job, the remaining changes are things that require human intervention (e.g., merging related changes to a single line).
