### ISSUE TITLE
`prefixes` in `ListObjectReponse`

### ISSUE THREAD

**Issue by vnvo2409** [googleapis/google-cloud-cpp#4482]
**What component of `google-cloud-cpp` is this feature request for?**
`storage`

**Is your feature request related to a problem? Please describe.**
I am implementing a `GetChildren` function will work in a directory-like mode.

**Describe the solution you'd like**
I would like to have access to `prefixes` in the reponse.
**Additional context**
If this is not possible, Is there any way I could access to the raw reponse instead of `ListObjectsReader`

**Comment by coryan** [comment]
I think we completely missed `prefixes` 😞 

The C++ object to process the response (`internal::ListObjectsResponse`) does not have `prefixes` either, so either way we would need to make changes.

I think the "Right Thing":tm: here is to add a new function to `Client` that returns an iterator over the prefixes. Maybe something like:

```{c++}
class Client { public:
  ListObjectPrefixesReader ListMatchingPrefixes(std::string bucket_name, ...);
};
```

`ListObjectPrefixesReader` would be a single pass input range of `std::string`, and the call could always use a suitable `Fields()` value to discard the data it will not use.

The downside is that you need two sets of RPCs: (1) to discover the prefixes that match and (2) to discover the objects that match.  OTOH, prefixes are very different from object names and/or object metadata, so maybe it makes sense to have completely different APIs?

As an alternative we could create a function called `ListObjectNamesAndPrefixes` and return a single pass input range of `std::string` and `Kind` (wrapped in a struct or pair) where `Kind` would tell you if the string represents a prefix or a real object name.

Or thinking about it some more, maybe `absl::variant<std::string, ObjectMetadata>` is an alternative here... that is super hard to use though.

**Comment by vnvo2409** [comment]
> As an alternative we could create a function called ListObjectNamesAndPrefixes and return a single pass input range of std::string and Kind (wrapped in a struct or pair) where Kind would tell you if the string represents a prefix or a real object name.

I think this makes sense because if someone wants `prefixes`, they usually need the name of the object only. I could work on this features but I may need some instructions, What do you think ?

**Comment by coryan** [comment]
Sorry for the delay, we had a quick back and forth on this internally.  It seems we settled on this:

```C++
using ListObjectsAndPrefixesReader =
    internal::PaginationRange<
        absl::variant<std::string, ObjectMetadata>,
        internal::ListObjectsRequest,
        internal::ListObjectsResponse>;

class Client { public:
  ListObjectsAndPrefixesReader ListObjectsAndPrefixes(/* same arguments as ListObjects */);
}; 
```

This is a bit ugly, but supports users that may want to get metadata and prefixes. It is trivial to convert those to `std::pair<std::string, bool>` and with a suitable `gcs::Fields()` argument you can get the server to return only the name in the `items`.


As to the implementation.  There are several things you would need to change:

- We would need to modify the testbench to return prefixes, so we can run integration tests end-to-end.
- We would need to modify `ListObjectsResponse` to add the prefixes field, and populate it when parsing the JSON (and gRPC?) result.
- `storage::internal::PaginationRange` needs larger changes, currently it assumes the response contains a `items` field of type `std::vector<T>`, but we now need to merge `prefixes` and `items` into a single vector of `absl::variant<>`.
  - Probably it would be time to refactor this class to use  `google::cloud::PaginationRange<>` which has a function to extract the current page from the response.
  - This function should merge the prefixes and object metadata items and sort them.
- After those changes the implementation of `ListObjectsAndPrefixes()` is easy, it needs:
  - At least a simple integration test
  - At least one example

**Comment by vnvo2409** [comment]
Close by #4494
