### ISSUE TITLE
google::cloud::storage::ObjectWriteStream fails if > 4 GiB written

### ISSUE THREAD

**Issue by orinem** [googleapis/google-cloud-cpp#4497]
**What component of `google-cloud-cpp` is this related to?**
google/cloud/storage

**Describe the bug**
In 32-bit builds, uploading streams > 4 GiB fail with:

Permanent error in UploadGenericChunk: Failed to parse Content-Range header. [INVALID_ARGUMENT]

**To Reproduce**

In a 32-bit build:

Use google::cloud::storage::Client::WriteObject to get a stream (m_writer).  Write > 4 GiB to the stream.  Close the stream.

m_writer->metadata().ok() is false and m_writer->last_status().message() is as above.

**Expected behavior**
Success.

**Operating system:**
Windows 10, but not particularly relevant.

**What compiler and version are you using?**
Visual Studio 2019, but not particularly relevant.

**What version of `google-cloud-cpp` are you using?**
Irrelevant, underlying problem is in current version: b308a107402f28e097898e91a07295231878cdcf

**Investigation**

The Content-Range header was:

Content-Range: bytes 9135194112-9136473156/546538565

546538565 is rather obviously 9136473157 mod 2^32 so we are looking for a 64 to 32 bit truncation.  It was found in object_streambuf.cc.

**FIX**
Change std::size_t to std::uint64_t in object_streambuf.cc when calculating the upload size.

std::size_t upload_size = upload_session_->next_expected_byte() + actual_size;

_should be_

std::uint64_t upload_size = upload_session_->next_expected_byte() + actual_size;

'auto' would probably work as well; std::size_t is not well defined and is wrong.

Note that next_expected_byte() returns std::uint64_t and UploadFinalChunk() where upload_size is used expects std::uint64_t.

**Comment by coryan** [comment]
Thank you for the bug report.  I have submitted a PR for review with the fixes for your problem (and I think a number of other problems).

**Comment by orinem** [comment]
I verified the fix for my case.  Thanks for your prompt attention to the matter.
