### ISSUE TITLE
Include Abseil headers with angle brackets

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#4501]
We need to include Abseil headers with angle brackets because on some platforms their headers are not clean under `-Werrror`. We can work around this by disabling `-Werror`, but obviously that is not a great answer because that becomes a transitive problem for our customers: they have to disable -Werror too because our headers are not clean.

For an specific example abseil/abseil-cpp#582 breaks under Windows+MSVC+x86.

**Comment by devjgm** [comment]
I think Abseil will need to do some work to support angle-bracket includes in Bazel builds. We should file a feature request for this.

**Comment by coryan** [comment]
Done: abseil/abseil-cpp#740

**Comment by coryan** [comment]
When compiled with MSVC+x86 some Abseil headers (notably "absl/strings/str_join.h") generate warnings, and break our builds (as we compile with warnings-as-errors). This particular warning is useful, and we do not want to disable it globally. Instead we disable the warning before including "absl/strings/str_join.h", and enable it again after the include.

I have refactored the code to silence the warning, include `"absl/strings/str_join.h"` and re-enable the warnings to a single header (see #5163). When we have a reliable mechanism to disable warnings generated in Abseil headers (e.g. when `#include <absl/...>` works) we can remove that header and replace its call sites with `#include <absl/strings/str_join.h>` (or include with quotes if that works).

Removing this file (or any such file) should be a simple global search&replace followed by `clang-format` to reorder the includes.

**Comment by devjgm** [comment]
Doesn't seem like this is going to happen any time soon. This is difficult to do w/o support from Bazel.
