### ISSUE TITLE
Caching mechanism for GCS storage

### ISSUE THREAD

**Issue by vnvo2409** [googleapis/google-cloud-cpp#4503]
One more feature that I could work on it.
I am thinking about add a `cache` layer between the client and server. Something likes:
```
clien <-> cache <-> server
```

It could be used for:
- caching object metadata, bucket metadata ( list objects, list bucket, ... ).
- caching some parts of an object ( use with gcs::ReadRange ), we could fetch only some parts not in the cache yet. ( e.g the first time we fetch and cache offset 1 - 3, the second time, if we need 1 - 5, we could fetch from 4 - 5 and append to the data in the cache ).
- maybe more .

I just write my idea here, If you think this feature is good, I will provide more details about how I will implement it.

**Comment by coryan** [comment]
There are only two hard problems in computer science:

- Naming
- Cache invalidation
- Off-by-one errors

😀 

This is (most likely) outside the scope of the `google-cloud-cpp` project. It makes sense for some, but not all applications. 

Maybe you want to create your own project to do this (say vnvo2409/gcs-cache).  This can be made to work with some minor changes `[1]` to `gcs::Client`.  Would that work for you? 

`[1]`: in brief, assume your cache is implemented as a new "RawClient" sitting on top of the RetryClient. We need to add a mechanism for applications to "push" this cache, but once pushed the application works the same way.

**Comment by vnvo2409** [comment]
Ahh I see.

Indeed, I am a GSoC student who is working for Tensorflow to port some filesystem to `modular c api filesystem`. I've already implemented a caching mechanism in Tensorflow but I was thinking that could be helpful for other applications so I opened an issue here.

In addition, since I would like to get more involved in open source in this summer, please tell me if there is an issue that is suitable for me. Thank you
