### ISSUE TITLE
Update spanner retries/timeouts to use settings from json files

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#4528]
The default timeout and retry settings for our spanner clients should come from the following official json files:

* Client: https://github.com/googleapis/googleapis/blob/master/google/spanner/v1/spanner_grpc_service_config.json
* DatabaseAdminClient: https://github.com/googleapis/googleapis/blob/master/google/spanner/admin/database/v1/spanner_admin_database_grpc_service_config.json
* InstanceAdminClient: https://github.com/googleapis/googleapis/blob/master/google/spanner/admin/instance/v1/spanner_admin_instance_grpc_service_config.json

We should audit where our current default settings are different, and then update them to match what's recommended in the json files.

**Comment by coryan** [comment]
FWIW, I think for Bigtable we wrote some program to read similar files to these and generate header files that we then just compile.

Also, our retry policies are per-client, not per method.  It would be a fairly large change to modify the policies to know what function is being called and what values they should use in that case.

**Comment by hengfengli** [comment]
Hi @devjgm, is there any update with this issue?

**Comment by mr-salty** [comment]
I don't think anyone has looked at this but I can take care of it

**Comment by mr-salty** [comment]
@scotthart Greg tells me the generator will be able to parse these files and generate code?  So, I'm going to plan to do the easy thing for now and just hardcode the values from the json files, I assume they're not expected to change super often anyways.

**Comment by devjgm** [comment]
Is this done to the extent that we can do anything?

**Comment by mr-salty** [comment]
I think we can/should still do something with this (I'm going to have to hack something for PDML regardless).  I wanted to have a group discussion about it but haven't gotten it together yet.

**Comment by devjgm** [comment]
I'm a bit confused about what remains on this issue. @mr-salty can you please clearly summarize what needs to be done in order to close this issue?

**Comment by mr-salty** [comment]
The work item for this bug (as stated in the original report) is "update [timeout and retry settings] to match what's recommended in the json files".

However, that is blocked on deciding how we want to approach retries and timeouts in general (i.e. what we discussed during our meeting today). I'm not sure if that merits a separate github issue or not. Really, this issue likely applies to all of our client libraries.

**Comment by coryan** [comment]
We will revisit, it may need changes in the generator and some infrastructure to have per-function defaults.

**Comment by devbww** [comment]
Blocked by #8473.

**Comment by coryan** [comment]
Closing. Applications can now override these on a single function if needed.
