### ISSUE TITLE
[Flake] Executable not found in Windows+MSVC+x86 build

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#4539]
Only in one build so far:

https://source.cloud.google.com/results/invocations/6d029c20-cbee-427a-9352-3dac361efb54

```
[542/1264] Building CXX object google\cloud\storage\CMakeFiles\storage_internal_nljson_use_third_party_test.dir\internal\nljson_use_third_party_test.cc.obj
[543/1264] Linking CXX executable google\cloud\storage\internal_http_response_test.exe
[544/1264] Linking CXX executable google\cloud\storage\internal_nljson_use_third_party_test.exe

...
...

        Start  82: storage_internal_nljson_use_third_party_test
Could not find executable T:/src/github/google-cloud-cpp/cmake-out/msvc-x86-windows-static/google/cloud/storage/internal_nljson_use_third_party_test.exe
Looked in the following places:
T:/src/github/google-cloud-cpp/cmake-out/msvc-x86-windows-static/google/cloud/storage/internal_nljson_use_third_party_test.exe
T:/src/github/google-cloud-cpp/cmake-out/msvc-x86-windows-static/google/cloud/storage/internal_nljson_use_third_party_test.exe.exe
T:/src/github/google-cloud-cpp/cmake-out/msvc-x86-windows-static/google/cloud/storage/Release/internal_nljson_use_third_party_test.exe
T:/src/github/google-cloud-cpp/cmake-out/msvc-x86-windows-static/google/cloud/storage/Release/internal_nljson_use_third_party_test.exe.exe
Release/T:/src/github/google-cloud-cpp/cmake-out/msvc-x86-windows-static/google/cloud/storage/internal_nljson_use_third_party_test.exe
Release/T:/src/github/google-cloud-cpp/cmake-out/msvc-x86-windows-static/google/cloud/storage/internal_nljson_use_third_party_test.exe.exe
Unable to find executable: T:/src/github/google-cloud-cpp/cmake-out/msvc-x86-windows-static/google/cloud/storage/internal_nljson_use_third_party_test.exe
 79/263 Test  #82: storage_internal_nljson_use_third_party_test ......................***Not Run   0.00 sec

```

uh?

**Comment by coryan** [comment]
Different executable, same problem:

https://source.cloud.google.com/results/invocations/ba08c3ff-8229-4d56-b351-7f6770230623

```
[600/1287] Building CXX object google\cloud\storage\CMakeFiles\storage_internal_retry_object_read_source_test.dir\internal\retry_object_read_source_test.cc.obj
[601/1287] Linking CXX executable google\cloud\storage\internal_tuple_filter_test.exe

...
...

        Start 100: storage_internal_tuple_filter_test
Could not find executable T:/src/github/google-cloud-cpp/cmake-out/msvc-x86-windows-static/google/cloud/storage/internal_tuple_filter_test.exe
Looked in the following places:
T:/src/github/google-cloud-cpp/cmake-out/msvc-x86-windows-static/google/cloud/storage/internal_tuple_filter_test.exe
T:/src/github/google-cloud-cpp/cmake-out/msvc-x86-windows-static/google/cloud/storage/internal_tuple_filter_test.exe.exe
T:/src/github/google-cloud-cpp/cmake-out/msvc-x86-windows-static/google/cloud/storage/Release/internal_tuple_filter_test.exe
T:/src/github/google-cloud-cpp/cmake-out/msvc-x86-windows-static/google/cloud/storage/Release/internal_tuple_filter_test.exe.exe
Release/T:/src/github/google-cloud-cpp/cmake-out/msvc-x86-windows-static/google/cloud/storage/internal_tuple_filter_test.exe
Release/T:/src/github/google-cloud-cpp/cmake-out/msvc-x86-windows-static/google/cloud/storage/internal_tuple_filter_test.exe.exe
Unable to find executable: T:/src/github/google-cloud-cpp/cmake-out/msvc-x86-windows-static/google/cloud/storage/internal_tuple_filter_test.exe
 97/270 Test #100: storage_internal_tuple_filter_test ................................***Not Run   0.00 sec
```

**Comment by mr-salty** [comment]
The test has failed 4x in a row missing "storage_internal_tuple_filter_test" (the one above + 3 more so far):
https://source.cloud.google.com/results/invocations/5d7cd31e-de42-49c5-ac74-f2c36307c759
https://source.cloud.google.com/results/invocations/8bda8d10-9569-4393-a833-9a1f1ffeab43
https://source.cloud.google.com/results/invocations/f84c7d05-7d0e-448f-85e8-417050830294

**Comment by coryan** [comment]
For future reference, with some additional debug logs. The `.exe` file is actually missing:

https://source.cloud.google.com/results/invocations/28da8d35-d3c9-4a29-a0a1-80041642a0a4

Adding an additional build step to rebuild the file triggers a rebuild (of only the missing `.exe) but then the tests fail with `BAD_COMMAND`:

https://source.cloud.google.com/results/invocations/3fd54bf8-39a6-48a0-a071-8f898b5c1e29

**Comment by devbww** [comment]
A random observation that may be totally unrelated, but the `vcpkg` parts of that log file warn that "The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build."

**Comment by coryan** [comment]
> A random observation that may be totally unrelated, but the `vcpkg` parts of that log file warn that "The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build."

Intriguing... I am going to put this on the back burner because (a) we use the same setup (directories and so forth) for the x64 builds where this is not a problem, and (b) I do not believe we do any incremental builds, the build directory is empty at the beginning of the build.

**Comment by coryan** [comment]
FWIW, it seems that building the problematic targets *before* building all the targets works around the issue:

https://source.cloud.google.com/results/invocations/433cde4e-0d43-40b9-87ef-a6e94590179c

This is obviously brittle, because the list of targets affected by this problem (and we do not know *what* the problem is) may change (and has changed) over time. But at least it can get us good builds soon.

**Comment by coryan** [comment]
> > A random observation that may be totally unrelated, but the `vcpkg` parts of that log file warn that "The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build."
> 
> Intriguing... I am going to put this on the back burner because (a) we use the same setup (directories and so forth) for the x64 builds where this is not a problem, and (b) I do not believe we do any incremental builds, the build directory is empty at the beginning of the build.

I look at those again.  That is warning about how the `vcpkg.exe` executable is built, not how many of our code is built. I think the possibility of `vcpkg.exe` being "just wrong enough" to trigger this bug is remote.

**Comment by coryan** [comment]
FWIW, the latest (automated) build was successful:

https://source.cloud.google.com/results/invocations/bcaeaaf4-84cb-4ff8-b43d-7ed1637f07c1

@mr-salty I am not planning to continue researching this.  You can probably stop work on this issue too. We should leave it open for now, we close unrepeated flakes after 90 days (best effort, when somebody notices).

Upgrading the compiler might help too, but that is a topic for a longer discussion.

**Comment by mr-salty** [comment]
Yeah, this looks great now, thanks!

Future operators, if you see this happen please add the failing test to this list to apply the workaround Carlos implemented: 
https://github.com/googleapis/google-cloud-cpp/blob/d3f7d79d1c612b10cdba4e12294aa04c67fead0c/ci/kokoro/windows/build-cmake.ps1#L51-L59

**Comment by devbww** [comment]
No reported recurrences since 2020-09-01.  Lowering to p3.

**Comment by coryan** [comment]
AFAICT this was caused by the antivirus software running in the CI build directories, since @tmatsuo disabled AV, I think we can close this bug.
