### ISSUE TITLE
Remove duplicate implementation of IsProtoEqual matcher

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#4540]
We have an implementation in `google/cloud/testing_util/is_proto_equal.h`:

https://github.com/googleapis/google-cloud-cpp/blob/b2022257af543364d051c4b9f403e28b6cf48e32/google/cloud/testing_util/is_proto_equal.h#L31-L37

and a different implementation in `google/cloud/spanner/testing/matchers.h`:

https://github.com/googleapis/google-cloud-cpp/blob/b2022257af543364d051c4b9f403e28b6cf48e32/google/cloud/spanner/testing/matchers.h#L31-L38

Not a big deal but we should refactor them.

**Comment by mr-salty** [comment]
Hey I accidentally fixed this in #4695
