### ISSUE TITLE
Support move-only callables in pubsub::Subscriber::Subscribe()

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#4556]
I am about so send a PR with the skeleton for `pubsub::SubscriberConnection`. This initial version uses `std::function<>` to type erase the callback provided by the application. This might be too heavy weight, and a lighter weight type erasure might work better.

**Comment by devjgm** [comment]
Do we need to take ownership of the passed callback? If so, then `std::function` doesn't seem too bad to me.

**Comment by coryan** [comment]
We do need ownership.  I would also like us to support move-only callables. I could close this bug and open a new one, but I am lazy as the fix would be the same?

I am going to rename it.

**Comment by coryan** [comment]
After some discussion we decided not to do this.
