### ISSUE TITLE
Enable master branch protection

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/google-cloud-cpp#4593]
This repository does not seem to have master branch
          protection enabled, at least in the way I'm expecting.
          I was hoping for:

          - master branch protection
          - requiring at least one code reviewer
          - requiring at least two status checks
          - enforcing rules for admins

          Please turn it on!

**Comment by coryan** [comment]
Master branch protections are enabled, we require at least one code reviewer, and the rules are enforced for admins.

The mismatch is because we require only one status check (the CLA check). What other status check you have in mind?

**Comment by JustinBeckwith** [comment]
Typically we require some kind of unit test, linter, or basic validation.  It looks like you run a lot of checks, the idea is that you pick the ones you'd never merge a PR without passing, and make that required.

**Comment by coryan** [comment]
Historically we never enforced these because they failed too often.  If we are going to pick some I suggest:

- clang-tidy
- one windows build
- one macos build

**Comment by devjgm** [comment]
Does the CLA check count as one of our checks? If so, and if we need two, **I'd suggest CLA check + clang-tidy**. We effectively never submit when any of the other builds are *actually* broken, but the windows and macos builds are flaky enough that I'd be slightly nervous having them *required*.... but just a thought.

**Comment by coryan** [comment]
Okay, I just fixed this because I got tired of talking about it.
