### ISSUE TITLE
Add mechanism to create `storage::Client` with modified retry policy

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#4598]
We have a customer request to provide some mechanism to create a new `storage::Client` with a modified policy. That is, the application would want something like:

```cc
namespace gcs = google::cloud::storage;

gcs::Client ModifyRetryPolicy(gcs::Client c) {
  // cloud also be c.ModifyPolicies(....);
  return gcs::SomethingSomething(std::move(c), gcs::LimitedTimeRetryPolicy(...));
}


void F(gcs::Client c) {
  auto client = ModifyRetryPolicy(c);
  c->ListObjects(); // use original policies
  client->ListObjects(); // use modified policies
}
```

**Comment by coryan** [comment]
Some random thoughts:

Note that we do not want to modify the policy held by the existing `internal::RetryClient` that breaks thread-safety, so we *must* create a new hierarchy.

Using just virtual functions might be hard, as the policies do not share a common base class, and do not apply to all the `RawClient` objects.

 we can navigate the stack of `RawClient` objects, search for the one with the right policy to change, and then create a new stack with the changes.  The `Client` class already knows about most of the types in the stack, because the stack is built by that class (so maybe some RTTI would be needed).

But we need a new member function to `clone()` an existing client.  I think the pseudo-code would be something like:

```cc
class Client { public:
  static Client With(Client original, RetryPolicy p) {
    return Client(internal::RawClientWith(raw_client(), std::move(p));
  }
};

static std::shared_ptr<RawClient> internal::RawClientWith(std::shared_ptr<RawClient> client, RetryPolicy p) {
    if (dynamic_cast<internal::RetryClient*>(client.get()) {
      return std::make_shared<RetryClient>(p.clone(), client->child());
    }
    return client->clone(      // <--- this is new
        internal::RawClientWith(child(),   // <--- ugh, I do not think all RawClients have this.
        std::move(p)
    );
  };
};
```

the `ugh` comment is a deal breaker right now... maybe... maybe we could add that function and the client at the bottom of the stack returns `nullptr`...

**Comment by devjgm** [comment]
We would like to do it, but no time now. Leaving open for now.

**Comment by coryan** [comment]
This is now obsolete, each request can override the retry and/or backoff policies.  See #9247
