### ISSUE TITLE
Add a function to convert from `g::c::Status` -> `absl::Status`

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#4612]
Due to https://github.com/googleapis/google-cloud-cpp/issues/4375, we will *probably* not be adopting `absl::Status`, and instead we'll keep our custom `google::cloud::Status` class https://github.com/googleapis/google-cloud-cpp/blob/master/google/cloud/status.h

It's likely that customers may want to convert from our Status to `absl::Status`, so we may want to provide a function like:

```cc
absl::Status ToAbslStatus(google::cloud::Status const& s);
```

**Q: Where should this function live?**

`google/cloud/status.h` is an obvious choice, but that would require that all of our customers would also get the Abseil dep, even when they don't need it (i.e., non-Google customers). Other thoughts:

* `google/cloud/absl_status.h`
* `google/cloud/absl_utils.h` -- Maybe there are more Abseil helpers we have or may need?
* ???

/cc @curiousg23

**Comment by devjgm** [comment]
We now have a hard dep on Abseil, so I suspect that concern mentioned above is likely no longer an issue.

**Comment by coryan** [comment]
While the dependency on Abseil is there, adding this function exposes `absl::Status` in our public API, maybe harmless, but we had decided to only use the `absl::` names that come from `std::` in our public API. we can change our minds, of course.    🤷

**Comment by devjgm** [comment]
At this point, we've decided that we don't want to expose `absl::Status` in our headers (at least not publically). So we will not be adding these conversion functions in this repo. We'll work with folks who may need them to figure out a good alternative.
