### ISSUE TITLE
Support maxResults in Object: list

### ISSUE THREAD

**Issue by vnvo2409** [googleapis/google-cloud-cpp#4615]
New parameters for the Object: list method (aka storage::Client::ListObjects()).
- `maxResults` Maximum combined number of entries in `items[]` and `prefixes[]` to return in a single page of responses.

More details at: https://cloud.google.com/storage/docs/json_api/v1/objects/list

I could work on this feature.

**Comment by coryan** [comment]
Hmm... that limits the number of elements returned by each page, but our API hides the pagination behind an iterator. How would application developers use this?  What is the benefit for them?  I can see it used to generate more than one request for unit and integration tests, but I do not see the benefit for production code.  More likely than not I am missing something?

**Comment by vnvo2409** [comment]
You are right. Indeed, the benefit is quite small.

Tensorflow are enforcing the behavior of `posix filesystem` on `gcs filesystem`. E.g if we have an object whose key is `path/to/a/file`. `PathExist('path/to/a/')` will return `true` and `'path/to/a/'` will be counted as a directory. In that case, I only need to fetch one result from `ListObjectsAndPrefixes` with the `Prefix("path/to/a/")`.

I am thinking of using `CustomHeader` instead. What do you think ?

**Comment by coryan** [comment]
Some thoughts:

- Trying to make GCS (an object storage system) look like a filesystem is bound to be awkward in places.
- Can we use the ordering constraints to stop the `for()` loop early?
- Can we use `startOffset` and `endOffset` to limit the search?


There may be some useful ideas here too:

https://cloud.google.com/storage/docs/gsutil/addlhelp/HowSubdirectoriesWork

**Comment by vnvo2409** [comment]
Thank for your suggestion. I will close this issue
