### ISSUE TITLE
Implement pubsub_listen_ordered_messages sample

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#4656]
Subscribe to some messages and manually sort them.

https://github.com/googleapis/nodejs-pubsub/blob/dcdec71e3a496b041dc8d1d0f03eda85d5d0cf63/samples/listenForOrderedMessages.js#L49-L114

**Comment by remyabel** [comment]
The region tags for `publishOrderedDate` was [updated](https://github.com/googleapis/nodejs-pubsub/commit/b501325265056319167fb8d5f81e1a0c3582af09) 23 days ago but `listenForOrderedMessages` hasn't been updated in 6 months. I modelled my PR after that sample (including the logic to use a timeout to wait for messages and then sort them by a counterId) so if that is also outdated, I'll wait for updated information how to proceed.

**Comment by coryan** [comment]
I think we are not going to implement any specific examples for receiving ordered messages.  The same code as receiving regular messages "Just Works":tm:
