### ISSUE TITLE
Unable to use the "storage-*" API on Ubuntu 16.04.2

### ISSUE THREAD

**Issue by ns-osmolsky** [googleapis/google-cloud-cpp#4682]
**Does this issue affect the google-cloud-cpp project?**
No

**What component of `google-cloud-cpp` is this related to?**
something in `google/cloud/storage`

**Describe the bug**
I've built the whole project on Ubuntu 16.04.2 using the steps described here: https://github.com/googleapis/google-cloud-cpp/blob/master/doc/setup-cmake-environment.md and observe two issues:

* The minimal "quickstart" app describe here https://googleapis.dev/cpp/google-cloud-storage/latest/ fails with the following:
```
$ GOOGLE_APPLICATION_CREDENTIALS=~/src/gcp-ml-access.json LD_LIBRARY_PATH=~/local-cpp/lib/ ./gtest gs://my-bucket
Error creating object: Permanent error in CreateResumableSession: Not Found [NOT_FOUND] [NOT_FOUND]
```
I can use any value of "bucket" and the message is the same... it seems something is fundamentally broken...

* All  `storage_*` tests fail:
```
The following tests FAILED:
        126 - storage_bucket_integration_test (Failed)
        129 - storage_curl_resumable_upload_session_integration_test (Failed)
        130 - storage_curl_sign_blob_integration_test (Failed)
        132 - storage_grpc_integration_test (Failed)
        133 - storage_key_file_integration_test (Failed)
        134 - storage_object_basic_crud_integration_test (Failed)
        135 - storage_object_checksum_integration_test (Failed)
        136 - storage_object_compose_many_integration_test (Failed)
        137 - storage_object_file_integration_test (Failed)
        138 - storage_object_file_multi_threaded_test (Failed)
        139 - storage_object_hash_integration_test (Failed)
        140 - storage_object_insert_integration_test (Failed)
        141 - storage_object_integration_test (Failed)
        142 - storage_object_list_objects_versions_integration_test (Failed)
        143 - storage_object_media_integration_test (Failed)
        144 - storage_object_parallel_upload_integration_test (Failed)
        145 - storage_object_plenty_clients_serially_integration_test (Failed)
        146 - storage_object_plenty_clients_simultaneously_integration_test (Failed)
        147 - storage_object_resumable_parallel_upload_integration_test (Failed)
        148 - storage_object_resumable_write_integration_test (Failed)
        149 - storage_object_rewrite_integration_test (Failed)
        150 - storage_object_write_streambuf_integration_test (Failed)
        151 - storage_service_account_integration_test (Failed)
        152 - storage_signed_url_conformance_test (Failed)
        153 - storage_signed_url_integration_test (Failed)
...
```

**Expected behavior**
Well, I am hoping that the tests would pass when I follow your build instructions... Otherwise I have no hope of getting the minimal client app working....

**Operating system:**
Ubuntu 16.04.2

**What compiler and version are you using?**
The default distro compiler: `g++ (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609`

**What version of `google-cloud-cpp` are you using?**
I've tried Master, 1.15 and 1.14.

**Additional context**
It seems something is fundamentally broken in my environment. I'd appreciate any pointers on how I'd go about narrowing down the issue...

**Comment by coryan** [comment]
> $ GOOGLE_APPLICATION_CREDENTIALS=~/src/gcp-ml-access.json LD_LIBRARY_PATH=~/local-cpp/lib/ ./gtest gs://my-bucket

I think this is what is going on: the quickstart program expects a bucket name, as in `my-bucket`.  The `gs://` prefix is a convention used in gsutil (and a few other places, but they are not required).

Let us know if that fixes the problem for you, if not, then we need to know if you made any changes to the quickstart program, and we may need to turn on debugging to see a full trace of the HTTP messages (see the [API Notes](https://googleapis.dev/cpp/google-cloud-storage/latest/index.html) section in the Doxygen docs).

**Comment by coryan** [comment]
This might be a bug, but I am more inclined to believe is a question for now.

**Comment by ns-osmolsky** [comment]
Hello @coryan, wow, that was indeed the problem! Thank you! I wish the quickstart sample had made it clear - the arg is the straight bucket name, with no paths, prefixes, URIs etc.

Thank you very much! I can get on with my project now.
