### ISSUE TITLE
[Q] Running "storage" tests on Ubuntu 16

### ISSUE THREAD

**Issue by ns-osmolsky** [googleapis/google-cloud-cpp#4691]
As I mentioned in #4682, most "storage*" tests fail for me. This does not look right and it would be good it someone took a look at that on a clean VM.

I ran a few test executables directly and they fail with this:
```
$ ./google/cloud/storage/tests/bucket_integration_test
Running main() from gmock_main.cc
[==========] Running 40 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 40 tests from BucketIntegrationTest
[ RUN      ] BucketIntegrationTest.BasicCRUD
/home/osmolsky/toolchain_build/google-cloud-cpp/google/cloud/storage/tests/bucket_integration_test.cc:39: Failure
Value of: project_id_.empty()
  Actual: true
Expected: false
[  FAILED  ] BucketIntegrationTest.BasicCRUD (1 ms)
[ RUN      ] BucketIntegrationTest.CreatePredefinedAcl
/home/osmolsky/toolchain_build/google-cloud-cpp/google/cloud/storage/tests/bucket_integration_test.cc:39: Failure
Value of: project_id_.empty()
  Actual: true
Expected: false
```
and this:
```
$ ./google/cloud/storage/tests/key_file_integration_test
Running main() from gmock_main.cc
[==========] Running 4 tests from 2 test suites.
[----------] Global test environment set-up.
[----------] 2 tests from KeyFileJsonTest/KeyFileIntegrationTest
[ RUN      ] KeyFileJsonTest/KeyFileIntegrationTest.ObjectWriteSignAndReadDefaultAccount/0
/home/osmolsky/toolchain_build/google-cloud-cpp/google/cloud/storage/tests/key_file_integration_test.cc:43: Failure
Value of: bucket_name_.empty()
  Actual: true
Expected: false
[  FAILED  ] KeyFileJsonTest/KeyFileIntegrationTest.ObjectWriteSignAndReadDefaultAccount/0, where GetParam() = "GOOGLE_CLOUD_CPP_STORAGE_TEST_KEY_FILE_JSON" (2 ms)
[ RUN      ] KeyFileJsonTest/KeyFileIntegrationTest.ObjectWriteSignAndReadExplicitAccount/0
/home/osmolsky/toolchain_build/google-cloud-cpp/google/cloud/storage/tests/key_file_integration_test.cc:43: Failure
Value of: bucket_name_.empty()
  Actual: true
Expected: false
```

**Comment by coryan** [comment]
`bucket_integration_test` (as the name suggests) is an integration test, it tries to run actual calls to the GCS service and therefore needs a number of environment variables to configure the service account it will use, the google cloud project, any testing resources (such as buckets and Pub/Sub topics), etc.

If you want to run these tests, you can find a list of these environment variables here:

https://github.com/googleapis/google-cloud-cpp/blob/63c0dea04c550aac33fbcedb6a933ec028bc65ca/ci/etc/integration-tests-config.sh#L22-L25

https://github.com/googleapis/google-cloud-cpp/blob/63c0dea04c550aac33fbcedb6a933ec028bc65ca/ci/etc/integration-tests-config.sh#L34-L47

Note that the *values* used in that file are for our CI builds, as I am sure you realize, you would need to provide your own values.

**Comment by ns-osmolsky** [comment]
Thanks! That clarifies the issue.
