### ISSUE TITLE
implement testing `Status` matchers

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp#4693]
Implement matchers that can check a `google::cloud::Status` in a single `EXPECT` statement.

We shouldn't spend too much effort on this until we resolve whether to switch to `absl::Status` (#4375), but we can implement our matchers in ways that are similar to (more specifically, subsets of) absl matchers to help the transition if we do go that direction.

**Comment by coryan** [comment]
This seems (to me) to be a duplicate of #1999? Feel free to reopen if I was wrong.
