### ISSUE TITLE
Dangling pointer in CompletionQueue timers cancelation?

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#4736]
This looks like a potentially dangling pointer to me:

https://github.com/googleapis/google-cloud-cpp/blob/eaff742ef1686aa2c3c8f43bf374f70f949065f3/google/cloud/completion_queue.cc#L41

When `AsyncTimerFuture` goes out of scope (usually because the timer expired) the `future<>` associated with that `promise_` may still be in scope and the application may still try to cancel the timer (though it is too late).  That will try to use `this` which is no longer valid.

I think we should transfer *ownership* of the `alarm_` to the cancellation callback, but keep a non-owning pointer in the `AsyncTimerFuture`.

**Comment by coryan** [comment]
Actually it is not as bad as I thought, the cancel callback cannot be called for "ready" futures:

https://github.com/googleapis/google-cloud-cpp/blob/b8d008315f88d73ed5b95b3585c5a857e6d8930e/google/cloud/internal/future_impl.h#L211-L214

https://github.com/googleapis/google-cloud-cpp/blob/b8d008315f88d73ed5b95b3585c5a857e6d8930e/google/cloud/internal/future_impl.h#L83

and a timer that has expired is ready, it has an (error) value.

**Comment by coryan** [comment]
Since it cannot cause a crash, this is just confusing code, so it is a cleanup.

**Comment by devbww** [comment]
I'm going to assert that this is obsolete.  The cleanup and additional fix happened in #5176.
