### ISSUE TITLE
[flake] macos cmake-super build failed with "Command failed: 2" and no other error message

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp#4754]
Seen once on 2020-07-30 in the macos cmake-super build: [log](https://source.cloud.google.com/results/invocations/26ec1ba5-3bf5-4203-8090-4856c4bdf53b/targets/cloud-cpp%2Fgithub%2Fgoogle-cloud-cpp%2Fmaster%2Fmacos%2Fcmake-super/log)

There is no useful error message I can see, the `curl-project-build-*.log` the error refers to is not present in the "artifacts" tab.
The total build duration was <5 minutes so this does not appear to be a timeout issue.

```
[ 74%] Performing build step for 'curl-project'
CMake Error at /Volumes/BuildData/tmpfs/src/github/google-cloud-cpp/cmake-out/macos/external/curl/src/curl-project-stamp/curl-project-build-.cmake:49 (message):
  Command failed: 2

   '/usr/local/Cellar/cmake/3.16.4/bin/cmake' '--build' '/Volumes/BuildData/tmpfs/src/github/google-cloud-cpp/cmake-out/macos/external/curl/src/curl-project-build' '--' '-j' '4'

  See also

    /Volumes/BuildData/tmpfs/src/github/google-cloud-cpp/cmake-out/macos/external/curl/src/curl-project-stamp/curl-project-build-*.log


make[2]: *** [external/curl/src/curl-project-stamp/curl-project-build] Error 1
make[1]: *** [CMakeFiles/curl-project.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by coryan** [comment]
No repeats for 90d, closing.

**Comment by mr-salty** [comment]
Similar flake, building grpc this time, on 2020-12-15.
As above, the log it refers to is not present in "artifacts", and the build duration is ~5 minutes (slightly over - 5:37 this time)

https://source.cloud.google.com/results/invocations/c07b4159-17c6-4db4-8fda-72a9af7e04cc/targets/cloud-cpp%2Fgithub%2Fgoogle-cloud-cpp%2Fmaster%2Fmacos%2Fcmake-super/log

```
[ 84%] Performing build step for 'grpc-project'
CMake Error at /Volumes/BuildData/tmpfs/src/github/google-cloud-cpp/cmake-out/macos/external/grpc/src/grpc-project-stamp/grpc-project-build-.cmake:49 (message):
  Command failed: 2

   '/usr/local/Cellar/cmake/3.16.4/bin/cmake' '--build' '/Volumes/BuildData/tmpfs/src/github/google-cloud-cpp/cmake-out/macos/external/grpc/src/grpc-project-build' '--' '-j' '4'

  See also

    /Volumes/BuildData/tmpfs/src/github/google-cloud-cpp/cmake-out/macos/external/grpc/src/grpc-project-stamp/grpc-project-build-*.log


make[2]: *** [external/grpc/src/grpc-project-stamp/grpc-project-build] Error 1
make[1]: *** [CMakeFiles/grpc-project.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by devjgm** [comment]
This is not a user-facing issue. It's a CI flake that's more like a cleanup.

**Comment by coryan** [comment]
No repeats in over 90d.  Seems related to download failures in super builds, we have download errors in other builds too, maybe we should consider all download failures the same "flake".
