### ISSUE TITLE
Improve build times for full builds

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#4783]
Some of the full builds (i.e., not PR builds) are fairly slow, nearing the 2 hour limit (#4782 increases the limit for some to 3 hours).

Generally we do not care about the build times for these, except because:

- If they go over the limit the build fails and that seems like an unforced flake error.
- The full builds refresh the build cache, slow builds means out of date caches for 2-3 hours after a PR is merged.

**Comment by coryan** [comment]
Some ideas on how to solve the problem [1]:

- For CMake-based builds we can simply turn on the ccache for full builds. It is currently turned off to keep the caches small and free of "old stuff". ccache has a simple mechanism to limit the cache size which is already turned on.

- For Bazel-based builds we cannot do the same: the cache grows without limit, so over time we would accumulate more and more stale data in the cache, until (and this is not that far away) the process of uploading and downloading the cache will take longer than the build.

It seems like the "Right Thing":tm: &nbsp; for Bazel builds is to turn on [GCS-based caching](https://docs.bazel.build/versions/master/remote-caching.html#google-cloud-storage) which would allow us to delete anything older than (say) 90d to keep the cache sizes under control.  Seems like we could even use these caches for our local builds too, but all of this requires experimentation to see what the performance implications would be.

[1]: I separated these from the problem description because the ideas for solutions might be bad, but the problem is still real.

**Comment by mr-salty** [comment]
FYI there is https://github.com/bazelbuild/bazel/issues/5139 "local caching: implement --disk_cache_size=GiB" although it's been pending for a long time. I wrote a script to prune the cache on my local machine we could adapt. It's currently based on atime but I could make it use a size threshold.

**Comment by devjgm** [comment]
I'm interested in that idea about using GCS as a remote, shared bazel cache. I'm looking into that.
