### ISSUE TITLE
Consider dropping gcc 4.8 support

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#4788]
Today we have a [CI build that tests using gcc 4.8.5 on centos-7](https://github.com/googleapis/google-cloud-cpp/blob/2c596e310e4de862143bd120b184ea714f305b75/ci/kokoro/docker/build.sh#L178-L188). An upcoming Abseil release will break on this compiler. Abseil dropped gcc 4.8 in August 2019, requiring gcc >= 4.9. We officially [support](https://github.com/googleapis/google-cloud-cpp#supported-platforms) GCC >= 4.9 as well, even though we test with 4.8.5.

Centos 7 is a supported version of Linux. It's default compiler is gcc 4.8.5, which I believe is why we test with it. However, it is possible to install gcc 7 on centos 7 with something like:
 
1. `yum install centos-release-scl`
2. `yum install devtoolset-7`
3. `scl enable devtoolset-7 bash`
4. `gcc --version`, which should show gcc version 7

We should consider dropping gcc 4.8 support. If we did this, would we need a gcc 4.**9** build?

If we did this we'd need to do the following:

- [ ] Install gcc-7 in our centos-7 docker image(s)
- [ ] Update our packaging instructions (which should be automatic since that's generated from the Docker files)
- [ ] Rename our "gcc-4.8" build to indicate the version it's testing

**Comment by coryan** [comment]
*IF* we are dropping GCC-4.8 then I think we can drop GCC-4.9 too: of the distros that we support, the next GCC version installed by default is GCC-5.x on Ubuntu:16.04. (I said "I think", somebody should check my math).

I am not sure what can we realistically do at this time other than dropping GCC-4.8.  It makes me sad that we are forced to do so, without giving customers more notice.  It makes me happy because we can stop writing ugly workarounds for it.

**Comment by devjgm** [comment]
Some data gathering about Linux OS versions and the default compiles available.

## Our "docker" builds
distro | gcc | clang
--------| ---- | ----
centos:7 | 4.8.5 | 3.4.2
fedora:31 | 9.3.1 | 9.0.1
fedora:32 | 10.2.1 | 10.0.0
ubuntu:xenial (16.04) | 5.4.0 | 3.8.0
ubuntu:bionic (18.04) | 7.5.0 | 6.0.0

## Our "install" builds

distro | gcc | clang
--------| ----- | ------
centos:8 | 8.3.1 | 9.0.1
debian:buster | 8.3.0 | 7.0.1
debian:stretch | 6.3.0 | 3.8.0
opensuse/leap | 7.5.0 | 9.0.1
opensuse/tumbleweed | 10.2.1 | 10.0.1
ubuntu:focal (20.04) | 9.3.0 | 10.0.0

**Comment by devjgm** [comment]
A little more data: A table of our build names with the distro and compiler they use

build name | distro | compiler
--------------- | ------- | ----------
clang-tidy | fedora-install:31 | clang
coverage | fedora-install:31 | gcc
integration | ubuntu:18.04 | gcc
integration-nightly | ubuntu:18.04 | gcc
publish-refdocs | fedora-install:31 | clang
asan | fedora:31 | clang
msan | fedora-libcxx-msan:32 | clang
tsan | fedora:31 | clang
ubsan | fedora:31 | clang
cmake-super | ubuntu:18.04 | gcc
ninja | fedora-install:31 | gcc
gcc-9 | fedora-install:31 | gcc
clang-9 | fedora-install:31 | clang
noex | fedora-install:31 | gcc
no-tests | fedora-install:31 | gcc
gcc-4.8 | centos:7 | gcc
clang-3.8 | ubuntu:16.04 | clang
libcxx | fedora-install:31 | clang
shared | fedora-install:31 | gcc
gcs-no-grpc | fedora-install:31 | gcc
check-abi | fedora-install:31 | gcc
update-abi | fedora-install:31 | gcc
cxx17 | fedora-install:31 | gcc
quickstart-bazel | ubuntu:18.04 | gcc
quickstart-cmake | ubuntu:18.04 | gcc
publish-refdocs | fedora-install:31 | clang

**Comment by coryan** [comment]
Thanks for collecting the data.  I assume you omitted the `install` builds that use the same compiler / docker image as `docker` build?  Because I am missing a few.

**Comment by devjgm** [comment]
Yes, I omitted the install builds that were dupes. To make this less confusing, I just combined the first two tables into one; there's no distinction between docker builds and install builds now.

**Comment by devjgm** [comment]
# Proposal

**REMOVE**:
build name | distro | compiler
----------|-------|---
~~gcc-4.8~~ |	~~centos:7~~	| ~~gcc~~

**ADD**:
build name | distro | compiler
---- | --- | ---
gcc-5.4 | ubuntu:xenial (16.04) | gcc (5.4.0)

Alternatively, we could create a new docker image with an older version of gcc, say, 5.0, so we can test with that.

**Comment by coryan** [comment]
👍  on your proposal.  I think you *also* want to change the `centos-7` build on `install` to use `devtoolset-7` as you described above. Our customers coming from RHEL 7 and/or CentOS 7 may want to know how to install / package the libraries.
