### ISSUE TITLE
Consider merging BatchingConfig into PublisherOptions

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#4811]
We currently have two classes, but seems like one should do. It would make the configuration easier to use.

**Comment by coryan** [comment]
@devjgm I wonder if you have any thoughts, here is the code in question:

https://github.com/googleapis/google-cloud-cpp/blob/d45182b3e46dd430e827797fad9c4a6f0340d0b5/google/cloud/pubsub/publisher_options.h#L62-L70

**Comment by devjgm** [comment]
Merging the two makes sense to me. We'd have a single `PublisherOptions` class, that has getters, and fluent-style setters. Unless we have the need to pass around `BatchingOptions` separately, I think merging them would make usage easier. +1
