### ISSUE TITLE
Use Ninja for all docker CMake builds

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#4827]
Ninja is a faster than `Make` at building code in general. We should consider using Ninja (i.e., pass `-GNinja` to our `cmake` invocation) in all of our _docker_ builds. Some benefits of this change:

1. Our full builds may be slightly faster
2. Our incremental builds may be faster
3. We could then remove the explicit "ninja" build

How would we test the normal cmake `Makefile` build? That build is tested by our install builds, which are also used to generate our user-facing packing documentation. 

Questions:
1. Do we want to make this change?
2. Might this mess up our existing cmake build caches? We might need to delete or recreate them. I'm not sure about this.

/cc: @coryan for some thoughts

**Comment by coryan** [comment]
> Do we want to make this change?

I think so.

> Might this mess up our existing cmake build caches? We might need to delete or recreate them. I'm not sure about this.

The CMake cache is really a `ccache`. Worst case the cache is invalidated because Ninja reorders the command-line options or something similar (I doubt it), but the only downside is a slow batch of PR builds (assuming nothing bad happens, of course).
