### ISSUE TITLE
Fix the coverage build to work with Ninja

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#4837]
In #4828 I enabled the Ninja generator for all of our cmake builds. Everything seemed fine, until we noticed that the code coverage numbers increased by 2%. Later, @coryan noticed that the reason is because our coverage build no longer included coverage data for .cc files and the generator/* directory. See https://codecov.io/gh/googleapis/google-cloud-cpp/pull/4828/tree/google/cloud

This seems to have something to do w/ Ninja, but we're not sure what yet. The short-term fix is probably to disable Ninja for the coverage build. A better fix would be to figure out why the coverage upload doesn't seem to work when we use Ninja.

**Comment by coryan** [comment]
This sounds relevant:

https://github.com/RWTH-HPC/CMake-codecov/issues/6#issuecomment-573209374

**Comment by devjgm** [comment]
fwiw, `CC=clang CXX=clang++ bazel coverage --test_tag_filters=-integration-test ... ` also generates a coverage report, though I'm not sure how/if that can be fed into codecov.io... or if it would really help.

**Comment by coryan** [comment]
I think this is now obsolete.
