### ISSUE TITLE
clang-tidy not checking generator/ headers

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#4842]
The fix for this should be as simple as tweaking this regex: https://github.com/googleapis/google-cloud-cpp/blob/c9627eaca9a25241890a7d3d8f7b398ef3585624/.clang-tidy#L58

To test that this works, we should be able to add a clang-tidy violation to a header in the `generator/` folder. However, when I do this, I do not see any warnings. Weird.

After much debugging I found the problem, but I'm not sure how best to fix it. Here's the command used to compile the code in the `generator/...` directory.

```shell
/usr/bin/cmake -E __run_co_compile --launcher=/usr/bin/ccache --tidy="clang-tidy;--extra-arg-before=--driver-mode=g++" --source=../../generator/internal/codegen_utils.cc -- /usr/bin/clang++  -D__CLANG_SUPPORT_DYN_ANNOTATION__ -I. -isystem ../../ -isystem external/googleapis -g   -Wall -Wextra -Werror -std=gnu++11 -MD -MT generator/CMakeFiles/google_cloud_cpp_generator.dir/internal/codegen_utils.cc.o -MF generator/CMakeFiles/google_cloud_cpp_generator.dir/internal/codegen_utils.cc.o.d -o generator/CMakeFiles/google_cloud_cpp_generator.dir/internal/codegen_utils.cc.o -c ../../generator/internal/codegen_utils.cc

```

Ninja (not the problem here... I think) compiles the code with a PWD of `cmake-out/*clang-tidy/`, so all the `../..` paths in the above command are referring to the project root. The problem is the argument **`-isystem ../../`**, which is saying to treat all includes from the project root as **system headers**, which clang-tidy ignores for the purpose of warnings. The actual argument should be **`-I ../../`**. Indeed if I manually change correct that flag, clang-tidy correctly warns on violates in the headers.

The generated compile command works correctly for code in our `google/cloud/...` tree. That is, it correctly uses `-I ../../`. Only code in our `generator/...` tree is incorrectly treating includes from the project root as as system includes.

Why?!?!?!?

This looks suspicious, but I'm not sure if it's *the* problem:

https://github.com/googleapis/google-cloud-cpp/blob/c9627eaca9a25241890a7d3d8f7b398ef3585624/cmake/CompileProtos.cmake#L251-L254

That's all the debugging time I have for now, so this was mostly a braindump.

/cc @coryan @scotthart as FYI

**Comment by coryan** [comment]
I think you are right, the protos are probably to blame.  Note that we want the generated protos to be treated as system headers, but that is being too aggressive.  We probably want to remove the `$<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}>` from that command.
