### ISSUE TITLE
consider using github Commit Linter

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp#4852]
[Commit Linter](https://github.com/marketplace/actions/commit-linter) is an action that runs [commitlint](https://github.com/conventional-changelog/commitlint) to check the syntax of commit messages.

Among other things, this can enforce a uniform set of `type` tags on commit messages, currently the list is: *build, chore, ci, docs, feat, fix, perf, refactor, revert, style, test [[source](https://github.com/conventional-changelog/commitlint/blob/da0c75db92cff7d88e065a1ee8dfbc1bde2af9e1/%40commitlint/config-conventional/index.js#L23-L33)]

**Comment by devjgm** [comment]
Would this replace the conventional commits bot that we currently use?

**Comment by mr-salty** [comment]
possibly - I didn't compare their feature sets but if it's a superset we could obviously disable the existing one.

**Comment by devjgm** [comment]
The conventional commits bot that we're already using seems to be working fine. I don't think there's enough need to investigate something else to replace something that's working. So closing for now. We can investigate Commit Linter if the current bot starts causing problems.
