### ISSUE TITLE
Reread generated Pub/Sub documentation and cleanup mistakes

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#4860]
Read the generated Doxygen documentation and search for:

- [x] typos and spelling errors
- [x] broken links
- [x] missing brief descriptions
- [x] missing long descriptions
- [x] missing parameter descriptions
- [x] missing description of retry behavior
- [x] missing examples
- [x] inconsistencies in number
- [x] inconsistencies in function descriptions (e.g., saying "Change X" vs. "Changes X")
- [x] paragraphs should be indented (no blank lines after `@par`)

open one bug per class with a punch list.

**Comment by remyabel** [comment]
FYI, I adapted [this approach](https://github.com/ARMmbed/mbed-os/pull/8970/files?file-filters%5B%5D=.dat&file-filters%5B%5D=.pws&file-filters%5B%5D=.sh&file-filters%5B%5D=.yml) to automatically scan a folder using aspell to spot typos. The only real work to be done is to add keywords specific to this codebase to the ignore file. I plan on opening more PR's for typos in the rest of the codebase.

Would you think it would be a good idea to add automatic spellchecking to the CI?

**Comment by coryan** [comment]
I would appreciate the auto spellchecking (obviously), let me summon @devjgm in case they have any thoughts.

**Comment by devjgm** [comment]
My opinion: I think spell checking during the CI sounds like moderate win if it's not too noisy and doesn't require much manual maintenance.

In case it's helpful, consider looking into [cspell](https://www.npmjs.com/package/cspell). I believe that's what coc-vim and vscode's spell checkers are based on. It's quite smart about correctly handling `WordsLikeThis`. I use it in vim and it seems to have fairly low false positives.

**Comment by remyabel** [comment]
@devjgm Thanks for the suggestion. That tool does the job well and it caught additional misspellings the other approach did not. Should we open a separate issue to further discuss adding spellchecking to the CI?

**Comment by coryan** [comment]
Good idea, I just created #5093
