### ISSUE TITLE
Flake: Windows CI, bazel fails to download dep, checksum error

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#4861]
Example:

```
2020-08-10T14:01:36.5961915+00:00 Fetch dependencies [2]
Loading: 0 packages loaded
INFO: Repository upb instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  C:/b/rvommcsc/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
WARNING: Download from https://github.com/protocolbuffers/upb/archive/d8f3d6f9d415b31f3ce56d46791706c38fa311bc.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Checksum was e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 but wanted e9c136e56b98c8eb48ad1c9f8df4a6348e99f9f336ee6199c4259a312c2e3598
ERROR: An error occurred during the fetch of repository 'upb':
   java.io.IOException: Error downloading [https://github.com/protocolbuffers/upb/archive/d8f3d6f9d415b31f3ce56d46791706c38fa311bc.tar.gz] to C:/b/rvommcsc/external/upb/d8f3d6f9d415b31f3ce56d46791706c38fa311bc.tar.gz: Checksum was e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 but wanted e9c136e56b98c8eb48ad1c9f8df4a6348e99f9f336ee6199c4259a312c2e3598
INFO: Repository com_google_protobuf instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  C:/b/rvommcsc/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Repository build_bazel_rules_apple instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  C:/b/rvommcsc/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Repository io_bazel_rules_go instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  C:/b/rvommcsc/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: no such package '@upb//bazel': java.io.IOException: Error downloading [https://github.com/protocolbuffers/upb/archive/d8f3d6f9d415b31f3ce56d46791706c38fa311bc.tar.gz] to C:/b/rvommcsc/external/upb/d8f3d6f9d415b31f3ce56d46791706c38fa311bc.tar.gz: Checksum was e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 but wanted e9c136e56b98c8eb48ad1c9f8df4a6348e99f9f336ee6199c4259a312c2e3598
```

https://source.cloud.google.com/results/invocations/4dd28d84-4486-40ed-b44e-30ad8901bf55/targets/cloud-devrel%2Fclient-libraries%2Fcpp%2Fgoogle-cloud-cpp%2Fwindows%2Fbazel-release/log
and
https://source.cloud.google.com/results/invocations/e9d88e8f-8d70-4d95-a59a-d6fe636ff0e7/targets/cloud-devrel%2Fclient-libraries%2Fcpp%2Fgoogle-cloud-cpp%2Fwindows%2Fquickstart-bazel/log

These are two cases that both happened 2020-08-10 @7am PDT

We can see here that bazel downloaded something, but the checksum didn't match what was expected. So, uh, what did it download?

I wonder if there's any verbose logging we can enable?

Idea: Maybe we could add a simple `curl <some known url>` to the beginning of `build.bat` so that can look in all of our logs and see whether normal fetches of a known webpage are working as we expect, or if we start getting some weird 404, or redirect, or something else strange.

**Comment by coryan** [comment]
I think we have seen this before in https://github.com/googleapis/google-cloud-cpp/issues/4045#issuecomment-653112881

Whether we want to mark this a duplicate or split the two problems I leave that to you.

> We can see here that bazel downloaded something, but the checksum didn't match what was expected. So, uh, what did it download?

I believe GitHub may create these tarballs on the fly, so if GitHub is having issues then we will get bad downloads, it could even be a nice "Ooops.html" page.


> Idea: Maybe we could add a simple curl <some known url> to the beginning of build.bat so that can look in all of our logs and see whether normal fetches of a known webpage are working as we expect, or if we start getting some weird 404, or redirect, or something else strange.

Earlier in the log chocolatey already downloaded some stuff:

```
T:\src>choco install --no-progress -y bazel --version 3.3.1
[snip]
url:  https://github.com/bazelbuild/bazel/releases/download/3.3.1/bazel-3.3.1-windows-x86_64.zip
hash: 48bbdad295a60a45d854b07163b86569eca1e5401a11f0ea4828c67a4b3168fa
Downloading bazel 64 bit
  from 'https://github.com/bazelbuild/bazel/releases/download/3.3.1/bazel-3.3.1-windows-x86_64.zip'

Download of bazel-3.3.1-windows-x86_64.zip (38.51 MB) completed.
Hashes match.
Extracting C:\Users\kbuilder\chocolatey\bazel\3.3.1\bazel-3.3.1-windows-x86_64.zip to C:\ProgramData\chocolatey\lib\bazel...
```

I am not sure another `curl` will help.

**Comment by coryan** [comment]
No repeats in 90d, closing.
