### ISSUE TITLE
GCS bazel cache should use a separate service account

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#4877]
> > Reviewed 1 of 1 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4869#-:-MEbhAIg9zZ5jQkYsr6P:bnfp4nl)_ status: :shipit: complete! all files reviewed, all discussions resolved
> 
> _[ci/kokoro/docker/build-in-docker-bazel.sh, line 64 at r1](https://reviewable.io/reviews/googleapis/google-cloud-cpp/4869#-MEbfjsD16XPHRThg_bW:-MEbfjsD16XPHRThg_bX:b-f4qh8h) ([raw file](https://github.com/googleapis/google-cloud-cpp/blob/7d76df21019acbf4f0ae03f323d89c3e770550ff/ci/kokoro/docker/build-in-docker-bazel.sh#L64)):_
> 
> > ```shell
> >   io::log "Using bazel remote cache: ${BAZEL_CACHE}"
> >   bazel_args+=("--remote_cache=${BAZEL_CACHE}")
> >   bazel_args+=("--google_credentials=${GOOGLE_APPLICATION_CREDENTIALS}")
> > ```
> 
> FYI: I think we should consider a different service account (and more limited privileges) for Bazel, we do not want Bazel accidentally breaking our tests by changing files in the wrong bucket.
> Likewise, we probably don't want one of the tests or benchmarks accidentally corrupting the cache.
> 
> Maybe open a bug to clean this up?

https://github.com/googleapis/google-cloud-cpp/pull/4869#pullrequestreview-466696142

**Comment by devjgm** [comment]
Punting for now.

**Comment by coryan** [comment]
Good idea, but not a major problem right now. Closing.
