### ISSUE TITLE
[Q] How to list all folders in a path?

### ISSUE THREAD

**Issue by Jiefei-Wang** [googleapis/google-cloud-cpp#4879]
Hi, Is there any way to list folders in a path? The function `Client::ListObjects` with prefix and delimiter options can list all files in a path, but it seems like it would not return the folder names. I have to remove the delimiter options so that I can see the folder names appear, but it will also list all files in the subdirectory. Is there any smarter way to do it? To be more clear, I want the `prefixes[]` property in the response of the JSON API [Objects: list](https://cloud.google.com/storage/docs/json_api/v1/objects/list).

Thanks,
Jiefei

**Comment by coryan** [comment]
We recently added `Client::ListObjectsAndPrefixes()`:

https://googleapis.dev/cpp/google-cloud-storage/master/classgoogle_1_1cloud_1_1storage_1_1v1_1_1Client.html#a49479ec17a165f6196aa85935153e2b5


It is part of the v1.16.0 release, but for some reason the documentation is not up.  Does that answer your question?

**Comment by Jiefei-Wang** [comment]
Thanks for your answer! This function is not available in the library in vcpkg yet, but I think this should be the solution to my question.

**Comment by coryan** [comment]
FWIW, I just checked and the 1.16.0 release is at `HEAD` in vcpkg, and includes this function. You are correct in that the latest vcpkg release (2020.06) does not include the change. You may be able to pick up the latest version of the `google-cloud-cpp` using a vcpkg overlay or just updated to `HEAD`, though I understand why that might be more trouble than it is worth.
