### ISSUE TITLE
Latest release documentation is not up

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#4880]
In googleapis.dev the "latest" version still points to `v1.15.0`, but we released `v1.16.0` more than a week ago.

At first I thought we had forgotten to trigger the build to create these docs, but I did that this morning:

https://source.cloud.google.com/results/invocations/fc0cd4b3-f6c0-4f09-b302-4447fc3e0d02

and the documents are not up.

**Comment by mr-salty** [comment]
@devjgm looks like you fixed it to me?

**Comment by devjgm** [comment]
Almost. https://googleapis.dev/cpp/google-cloud-spanner/latest/ is up-to-date now. Maybe too up-to-date, because it's showing v 1.17 and we've only released 1.16.

**Comment by coryan** [comment]
The 1.17.0 stuff may have been caused by my manual build last night.

**Comment by mr-salty** [comment]
this was resolved by releasing 1.17 (and 1.18).

**Comment by remyabel** [comment]
Is this fixed? https://googleapis.github.io/google-cloud-cpp/latest/pubsub/ has the up-to-date version but https://googleapis.dev/cpp/google-cloud-pubsub/latest/ does not.

**Comment by coryan** [comment]
Pub/Sub still has the "Beta" labels, once we release GA it will be fine.
