### ISSUE TITLE
Update pubsub README file

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#4883]
Update the status, link to the Cloud Pub/Sub documentation, add an example, and generally make it look like the README for our GA client libraries.

**Comment by anguillanneuf** [comment]
A good example is the Java [README](https://github.com/googleapis/java-pubsub). 

(required)
- product description
-  link to product documentation and library documentation
- versioning

(highly recommend to have)
- quickstart
  - installation guide
- example usage

(optional) 
- contributing guide
- community
- license
