### ISSUE TITLE
Consider fully qualifying using-declarations in examples

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#4964]
Our examples and code snippets typically have several using declarations to make the code more readable, e.g.:

```cc
//! [foo-tag]
using google::cloud::StatusOr;
// ... ... more example ...
//! [foo-tag]
```

As @mr-salty says:

https://github.com/googleapis/google-cloud-cpp/pull/4963#pullrequestreview-474934853

maybe we should fully qualify those.

**Comment by devjgm** [comment]
+1 to a cleanup to fully qualify these.

**Comment by mr-salty** [comment]
More generally, I'd propose we recommend following https://abseil.io/tips/ in our code. Internally, these are "recommended but not required". They do have solid rationale behind them and are subject to discussion and review before being published, and in my experience most code does adhere to them. I think the same would be reasonable for our codebase.

https://github.com/googleapis/google-cloud-cpp/blob/master/CONTRIBUTING.md#style says:
> This repository follows the Google C++ Style Guide, with some additional constraints specified in the [style guide](https://github.com/googleapis/google-cloud-cpp/blob/master/doc/cpp-style-guide.md). Please make sure your contributions adhere to the style guide.

we could add something there, or to the linked (local) style guide variations
