### ISSUE TITLE
cleanup: snippet-bot full scan

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#4969]
Find all the invalid / incorrect region tags.

## snippet-bot scan result
Life is too short to manually check unmatched region tags.
Here is the result:
Great job! No unmatching region tags found!

---
Report generated by [snippet-bot](https://github.com/apps/snippet-bot).
If you find problems with this result, please file an issue at:
https://github.com/googleapis/repo-automation-bots/issues.

**Comment by coryan** [comment]
Closing for now as the bot goes into troubleshooting.

**Comment by tmatsuo** [comment]
I think we resolved the bot issue. Re-opening

**Comment by tmatsuo** [comment]
It worked! Now this repo should be good to go, closing.
