### ISSUE TITLE
Bigtable latency spikes every hour due to grpc reconnects

### ISSUE THREAD

**Issue by jc2729** [googleapis/google-cloud-cpp#4996]
Is it possible to implement something similar to the ChannelPrimer in the Bigtable Java client to mitigate hourly spikes in latency due to underlying grpc connection shutdowns & reconnects 

Java client reference: https://github.com/googleapis/java-bigtable/pull/115
Related Github issue for Java client: https://github.com/googleapis/java-bigtable-hbase/issues/1463

**Comment by mr-salty** [comment]
@coryan you seem like the most likely person to have insight on this, if not assign it back and i'll dig into it.

**Comment by coryan** [comment]
A change similar to googleapis/java-bigtable#115 seems possible, but requires a number of changes:

- The Bigtable classes do not have a set of background threads and/or completion queues with them, we would need to add such background threads to `Table`, `TableAdmin`, etc.

- Then we would need to use something like this `grpc::ChannelInterface::NotifyOnStateChange`, to query the state of each channel and get notified when it changes:

https://grpc.github.io/grpc/cpp/classgrpc_1_1_channel_interface.html#a2acd32839ec4e5e92fe4b796a913623f

Note that we should avoid calling `GetCurrentState(true)` as that might block.

- Alternatively, we could simply make a "ping" call, but there is no equivalent to `SELECT 1;` in Bigtable-land, that would require some thinking...

So, this is a valid feature request, I will put it in the backlog, no promises on when it will be done.
