### ISSUE TITLE
Implement Cloud Firestore Client

### ISSUE THREAD

**Issue by chemelnucfin** [googleapis/google-cloud-cpp#501]
See [here](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-firestore/src/main/java/com/google/cloud/firestore/Firestore.java) and [here](https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-firestore/src/main/java/com/google/cloud/firestore/FirestoreImpl.java)

**Comment by coryan** [comment]
@chemelnucfin I created a label so we can track the firestore items more easily.  As you probably know, we have not prioritized work on this client.  But if you are able to send PRs for it we will be happy to review them.

**Comment by devjgm** [comment]
I think the firestore clients are autogenerated, which means we'll handle it with our imminent autogenerator. There's been no movement on this particular issue, and I don't think we need to track this work separately, so closing. Feel free to re-open if you think this issue was closed in haste.
