### ISSUE TITLE
Spanner: We should be able to control with fine-ish granularity which tests run against the emulator 

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#5019]
If/when spanner has new updates, it's not always required that those features launch in the Spanner emulator at the same time. However, those features will need to exist in our library, even before they're available in the emulator.

So we should look at our Spanner integration and samples testing infrastructure to make sure we can accommodate Spanner tests that will work with the emulator as well as those that only work against production. We can do that today with somewhat coarse granularity, but perhaps we should have more precise control over this.

I know @devbww was going to look into this. Please update this issue w/ whatever you find about how things work today.

**Comment by coryan** [comment]
Specific samples can be (and are) skipped already:

https://github.com/googleapis/google-cloud-cpp/blob/1778a7860c0b24ab46d213b8cf57fe3f3fa6d08b/google/cloud/spanner/samples/samples.cc#L3123-L3127


Likewise, we can skip or modify the behavior of tests:

https://github.com/googleapis/google-cloud-cpp/blob/1778a7860c0b24ab46d213b8cf57fe3f3fa6d08b/google/cloud/spanner/integration_tests/client_integration_test.cc#L363-L369


I think the problem arises when tests or examples depend on each other, e.g. a sample that creates a table with "all possible types" and then a example to populate or query that table based on specific values of each type.  Or the benchmarks that smoke test "all possible types".

**Comment by devbww** [comment]
+1 to what Carlos said.  It is the coarser issues, like the very shape of the data, where things become more difficult to conditionalize.

**Comment by coryan** [comment]
I think we are happy with the current approach. Closing.
