### ISSUE TITLE
`session_url` is actually `session_id` in gRPC

### ISSUE THREAD

**Issue by dopiera** [googleapis/google-cloud-cpp#5030]
When a resumable session is started, a resumable session id is returned.

In cURL mode, this is actually the whole URL with all parameters bound. Unfortunately, in gRPC it is only the id token itself.

This causes the following problems:
* gRPC and cURL implementations cannot be mixed
* some parts of the `GrpcClient` API (e.g. `DeleteResumableSession`) cannot be easily implemented (they also need the bucket and the object, which are parts of the URL)

There are two possible approaches:
* change the internal and external APIs to make the resumable session id an object (perhaps with distinct implementations for gRPC and cURL)
* synthesize the whole URL in the `GrpcClient`

I think we should go with the latter because:
* a session id (a string currently) is a part of the public API
* we will get interchangeability of the cURL and gRPC APIs

The implementation is quite obscure, though, because we need to generate and parse strings.

**Comment by coryan** [comment]
To followup our discussion in the meeting:

- Keeping the type as a `std::string` is the way to go.
- Encoding the gRPC session id as a URL might be problematic, we would need to URL-escape the object name and possibly other things.
- We could consider encoding `grpc` sessions ids by starting with `grpc://` or something similar.
- The hybrid client could "resume" the right session type depending on whether it starts with `https://` (or `http://` for testing) and/or `grpc://`.

 In any case, we need to write down exactly what we want to do, because it sounds more complicated than usual.

**Comment by dopiera** [comment]
Some more elaborate design decisions

# Problem
In the cURL world, we use resumable session URL, which contains the resumable session ID and some other properties:
- bucket name
- object name
- all request parameters
- endpoint

In gRPC, we only use the resumable session ID.

This is a problem because:
1.  cURL and gRPC implementations cannot be easilly mixed, which may not be obvious to the user (i.e. starting a resumable stream with cURL client and resuming with gRPC).
1. The internal, `RawClient` API is hard to implement with gRPC because it expects the whole URL rathern than the ID.
2. The end user receives the URL in the user-facing API (they can obtain the resumable session URL via  ObjectWriteStream::resumable_session_id()`), there is no such URL in gRPC
3. When the user changes their client in the middle of a resumable parallel upload, the upload will fail, becaues the persistent state of the upload contains the resumable session ID/URL

This additional information from the URL is required to implement:
* `GrpcClient::Delete`
* `GrpcClient::RestoreResumableSession` (only the endpoint - we currently take it
    from the client setup)

# We decided that we will:
* stick to the cURL meaning of the `resumable_session_id`, i.e. a URI containing all the required fields
* synthesize the URIs for gRPC
* for gRPC rather than using the regular URL format, use a "gRPC://" scheme followed by a base64-encoded binary proto containing all the required fields (we considered synthesizing proper URLs, but decided not to because of the high possibility of introducing bugs (think URL escaping, etc.))
* if `HybridClient` receives a non-empty `UseResumableUploadSession`, it will
  pick the respective implementation

# Some more details
Both cURL and gRPC clients will validate the URIs.

The protobuf encoded in the URI will be:
```
string bucket = 1;
string object = 2;
string upload_id = 3;
CommonObjectRequestParams common_object_request_params = 4;
CommonRequestParams common_request_params = 5;
```

## HybridClient switch
`HybridClient` needs to pick the right implementation in the following member
functions:
* `CreateResumableSession`
* `RestoreResumableSession`
* `DeleteResumableUpload`
* `UploadChunk`
All of them are straight-forward. Moreover, unless there is a bug in the code, it should not be possible for the user to call trigger a
`RawClient::UploadChunk` for mismatched implementation because this is baked into the internals of respective `ResumableUploadSession` implementations. Because parallel uploads are a simple consumer of the APIs, it should work out
of the box.

## Mixing implementations
It seems sane to expect the user to not resume an upload with a gRPC client which was started with a cURL client (and vice-versa). It is, however, possible that the user has multiple processes running resumable uploads and changes their
configuration via a rolling rollout. If they decide to swtich from cURL to gRPC, they might try to resume a cURL upload with gRPC. This becomes even more likely with parallel uploads, as they store the session URL/ID in the persistent state.

In order to make sure this doesn't happen we need to:
* make sure the error messages are clear (trying to resume a cURL upload with gRPC)
* when changing the default client to gRPC, we first change it to `HybridClient`, and only in the next release to `GrpcClient`
* inform the user of this strategy when releasing / announcing gRPC support

**Comment by coryan** [comment]
Just wondering:

> The protobuf encoded in the URI will be:
>
> ```
> string bucket = 1;
> string object = 2;
> string upload_id = 3;
> CommonObjectRequestParams common_object_request_params = 4;
> CommonRequestParams common_request_params = 5;
> ```

Maybe we should verify if the `*_request_params` fields are needed.  I suspect they are saved by the server as part of the state pointed-at-by `upload_id`.

**Comment by remyabel** [comment]
This TODO still exists as well:

https://github.com/googleapis/google-cloud-cpp/blob/9b7388d70ca66eb669a3170fffae1adcd01742e8/google/cloud/storage/tests/object_integration_test.cc#L902
