### ISSUE TITLE
No way to specify content length in gRPC GCS

### ISSUE THREAD

**Issue by dopiera** [googleapis/google-cloud-cpp#5032]
In cURL API there is `X-Upload-Content-Length` header, which allows specifying the desired content length of an object. There is no counterpart in gRPC API.

There is a field in the proto, but the comments suggest that it should not be used for this purpose

**Comment by coryan** [comment]
This seems like a dup to #4286 ?

**Comment by devjgm** [comment]
Still blocked.

**Comment by coryan** [comment]
Unblocked and now a feature request only.
