### ISSUE TITLE
Define the minimum Bazel version supported and create a CI build for it

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#5069]
It is Okay if many or most of our builds use an specific Bazel version, but we should define what is the minimum version we support (which probably will need to be >= the minimum version supported by Abseil and gRPC), and we need to have a CI build that uses that specific version.

**Comment by devjgm** [comment]
Most of our builds the min bazel version that we support (currently 4.0). See #8095. We also now have a build that tests our code using the newest LTS version of bazel (currently 5.0). See #8099. Tentatively our plan is to support the two newest LTS releases of Bazel (currently 4.x and 5.x), and we do have tests that verify this.
