### ISSUE TITLE
Can I use HMAC credentials to create a new client?

### ISSUE THREAD

**Issue by sdhavale** [googleapis/google-cloud-cpp#5071]
We want to switch an existing application from using AWS S3 to Google Cloud Storage at our company. We wish to use HMAC credentials for authentication for the same. Is it possible to create a gcs::Client to use HMAC credentials instead of the default credentials? Could you point me to an example for the same if we can do that? We primarily want to do operations such as Get/Put/Delete objects on the bucket.

**Comment by coryan** [comment]
The `gcs::Client` library uses (primarily) the JSON API:

https://cloud.google.com/storage/docs/json_api

which does not support HMAC authentication:

https://cloud.google.com/storage/docs/json_api/v1/how-tos/authorizing

There are cases where the `gcs::Client` uses the XML API (mostly for historical performance reasons), but using HMAC authentication would turn the library into a minefield, as some APIs would work and others would not.

If HMAC credentials are a must for you, then I am afraid the best choice might be:

https://cloud.google.com/storage/docs/migrating#migration-simple

Note that you *can* use different service accounts for authentication with the client library, typically by setting the `GOOGLE_APPLICATION_CREDENTIALS` environment variable, or

https://googleapis.dev/cpp/google-cloud-storage/latest/namespacegoogle_1_1cloud_1_1storage_1_1v1_1_1oauth2.html#a23765c2dbae21def39dc939013c07750

**Comment by sdhavale** [comment]
Thanks for the quick response and clarification.
