### ISSUE TITLE
Consider adding cspell to clang-tidy build

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#5093]
We could avoid typos in the code and comments if we ran a spell checker as part of the CI build. `clang-tidy` seems like the obvious candidate.

We should consider the number of false positives, if it is too high, or requires a lot of configuration to keep the false positives low, then this would not work.

**Comment by remyabel** [comment]
I'm leaning against adding this to the CI.

First, I configured the tool to check `CStyleComment`s only as it doesn't seem to have dedicated doxygen support and spellchecking variable names can lead to false positives (like `cntr` or variable names with underscores). So the configuration would look something like this:

```json
    "languageSettings": [
        {
            "languageId": "cpp",
            "includeRegExpList": [
                "CStyleComment"
            ],
            "ignoreRegExpList": [
                "/@param.*/",
                "/@tparam.*/",
                "NOLINT*"
            ]
        }
    ]
```

The exclude list is also getting kind of big. This is what I have so far:

```json
"words": [
        "grpc",
        "DNDEBUG",
        "absl",
        "deserializes",
        "btadmin",
        "goog",
        "INPROCESS",
        "ning",
        "coryan",
        "LCOV",
        "noex",
        "FFFZ",
        "Bazel",
        "unsets",
        "reimplements",
        "reimplementation",
        "Nacking",
        "rerunnable",
        "unchunk",
        "i'th",
        "STRUCT's",
        "Fooey",
        "CMEK",
        "ADCs",
        "csek",
        "cmek",
        "URL's",
        "gcloud",
        "VM's",
        "Lxxxxxx",
        "POST'ing",
        "gmock",
        "CRTP",
        "symbolizer",
        "grpclb"
    ],
```

One may be tempted to write a regexp exclude for the capitalized acronyms but it did catch a typo in `GOOGLE_CLOUD_CPP_CPP_VBERSION` so I do not think that would be wise. There aren't *that* many typos, so it's still feasible to run the tool manually and fix the typos before submitting a PR. On the other hand, we could make a concerted effort to ensure consistent capitalization, grammar and punctuation (which are not necessarily typos) with some of the keywords/acronyms or writing regexp for certain syntax (like `absl::foo`) to avoid false positives. Thoughts?

**Comment by coryan** [comment]
The number of exceptions does not look terribly onerous to me, summoning @devjgm in case they disagree.  There are a few that maybe we should change ("unchunk -> reassemble chunks", "reimplements -> re-implements ??").

I wonder if there is a way to skip backtick quoted symbols, as in `absl::FooBar`, but I think we should proceed regardless.

**Comment by devjgm** [comment]
I'm OK w/ proceeding. It doesn't look too bad.

cspell does support a `ignoreRegExp` option. We might consider ignore things in backticks as Carlos suggested.

**Comment by mr-salty** [comment]
Yeah, 100% agree with skipping things in backticks. Hopefully that will bring the size of the exclude list down, although we may need to do some edits to existing files to add backticks.

I also see `coryan` in the exclude list, is that from a `TODO` that could be changed to a bug#?

**Comment by remyabel** [comment]
> I also see coryan in the exclude list, is that from a TODO that could be changed to a bug#?

Yes, that sounds like a separate bug should be filed for it. Or have #41 be reopened.
