### ISSUE TITLE
Consider using sandboxfs for our macOS builds

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#5099]
Apparently it is much faster, but it is unclear if we can use it:

https://blog.bazel.build/2018/04/13/preliminary-sandboxfs-support.html

**Comment by devjgm** [comment]
May like to do this. Keeping open for now.

**Comment by devjgm** [comment]
This is already enabled by default. From https://bazel.build/docs/user-manual#strategy-options

> sandboxed causes commands to be executed inside a sandbox on the local machine. This requires that all input files, data dependencies and tools are listed as direct dependencies in the srcs, data and tools attributes. **Bazel enables local sandboxing by default, on systems that support sandboxed execution.**

And indeed from one of our recent macos builds I see 

```
[6,376 / 6,381] 26 / 429 tests; Testing //generator:internal_predicate_utils_test; 0s remote-cache, darwin-sandbox ... (5 actions, 2 running)
```

And "darwin-sandbox" is the magic string.
