### ISSUE TITLE
Build failure with MSAN

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#5106]
This started recently:

https://source.cloud.google.com/results/invocations/bb59c9cc-4757-4b1c-8388-609e08ec5916/details

```
ERROR: /v/google/cloud/spanner/BUILD:73:9: Couldn't build file google/cloud/spanner/_objs/database_admin_connection_test/database_admin_connection_test.pic.o: undeclared inclusion(s) in rule '//google/cloud/spanner:database_admin_connection_test':
this rule is missing dependency declarations for the following files included by 'google/cloud/spanner/database_admin_connection_test.cc':
  '/usr/lib64/clang/10.0.1/share/msan_blacklist.txt'
  '/usr/lib64/clang/10.0.1/include/stddef.h'
  '/usr/lib64/clang/10.0.1/include/__stddef_max_align_t.h'
  '/usr/lib64/clang/10.0.1/include/stdint.h'
  '/usr/lib64/clang/10.0.1/include/stdarg.h'
  '/usr/lib64/clang/10.0.1/include/limits.h'
  '/usr/lib64/clang/10.0.1/include/float.h'
```

**Comment by coryan** [comment]
Fixed by clearing some stale cache files.

**Comment by mr-salty** [comment]
I noticed this in the log:

```
2020-09-22T04:11:04Z: Downloading build cache cache-ci-fedora-libcxx-msan-32-msan.tar.gz from cloud-cpp-kokoro-results/build-cache/google-cloud-cpp
ERROR: gcloud crashed (TokenRevokeError): invalid_request
```

does that result in a corrupt/truncated tarball? I don't see any errors related to untarring it so could be a red herring.

also, I wonder if we should `set -x` in all our shell scripts (prints commands being executed)... unsure if it would be helpful in debugging or just noise.

**Comment by coryan** [comment]
The error in the log is unrelated to downloading the tarball and/or extracting it.

**Comment by devjgm** [comment]
This was probably fixed by https://github.com/googleapis/google-cloud-cpp/pull/5108

**Comment by mr-salty** [comment]
@coryan sounds like a vote for `set -x` to me?

**Comment by coryan** [comment]
@mr-salty I can see the argument for `set -x`, OTOH I like the cleaner logs. Send a PR and we can see if the logs are tolerable, or file a bug if you don't have the time right now.

**Comment by coryan** [comment]
@devjgm yes, this might be fixed, I want to see a few more PRs + full builds, I declared victory too early yesterday.

**Comment by coryan** [comment]
I think this is really fixed now (famous last words).
FWIW, the PR builds are taking 10-15m (I am sure you can find/create outliers, just change "version.h" or something), and the full builds are taking about 20-25m.
