### ISSUE TITLE
Decide on grammar for words considered misspelled

### ISSUE THREAD

**Issue by ghost** [googleapis/google-cloud-cpp#5110]
Per https://github.com/googleapis/google-cloud-cpp/pull/5107#pullrequestreview-493051504

> maybe a separate bug to consider de-serializes, re-runnable, etc. ditto for the coryan thing.

Some of these are correctly spelled (according to a cursory search anyway), so it's just a matter of deciding on how to spell it or whether to exclude them from the spellcheck.

**Comment by remyabel** [comment]
A lot of diagnostics also pop up for plural versions of words or apostrophes (`gcloud's foo`). cspell may be fine with `gMock` but trips on `gMock's` and complains about `Mock's`. Figuring out a consistent way of dealing with that would be great too.

**Comment by devjgm** [comment]
We could use a regex to ignore all words that end with `'s`, maybe like  `"ignoreRegExpList": ["/'s\\b/"]`.

More info: https://github.com/streetsidesoftware/cspell/issues/36

**Comment by remyabel** [comment]
Thanks for digging up that issue and suggesting the change. I have added those changes as well.

**Comment by devjgm** [comment]
We're now using `typos-cli`, which doesn't seem to have this issue. We can re-open this or a new issue for areas where `typos` causes us trouble.

https://github.com/googleapis/google-cloud-cpp/blob/2802fd38d02b35a17fa4b38f54caace7ebeba2d6/ci/cloudbuild/dockerfiles/checkers.Dockerfile#L43
