### ISSUE TITLE
Disable tarball cache for all Bazel CI builds

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#5113]
I missed that we were turning on the Bazel tarball caches for all CI builds (I thought it was just CMake).

I believe this is not a good idea, Bazel has no mechanism to prune the local cache. If the CI build downloads the old tarball the cache is populated with old data, it then gets the new data during the CI build, and then gets uploaded with the old and the new data for the PRs **and** for the next full CI build.  Effectively the tarball grows without any limits (note that ccache is limited to 4.0GiB by configuration, so it does not have this problem).

We disabled the download for full CI builds to avoid this, the tarball created in each full CI build was "fresh".

**Comment by mr-salty** [comment]
what effect does this have on build times, and how can we enable caching without this problem?

there is an open issue about cache pruning: https://github.com/bazelbuild/bazel/issues/5139

I also have a script I use to prune my own cache, perhaps we could adapt that.

**Comment by devjgm** [comment]
To be clear, I think this was enabled last week in https://github.com/googleapis/google-cloud-cpp/pull/5063. I think it was a mistake to enable downloading of that cache on bazel builds -- only cmake was the intent.

I agree that the CI bazel builds should not download the tarball cache. The CI bazel builds can (and do) use bazel's remote cache. And I think they can then *upload* a new tarball cache to be used (downloaded) by the presubmit builds.

**Comment by mr-salty** [comment]
Is there a doc somewhere that describes how all of this stuff does or is intended to work?

**Comment by devjgm** [comment]
Does a bunch of `.sh` files count as a doc?

**Comment by coryan** [comment]
@mr-salty to your question:

> what effect does this have on build times, and how can we enable caching without this problem?

Should be close to zero for PR builds (this is just for full CI builds).  The full CI builds still have the Bazel GCS cache (vs. the tarball we used for historic + seems to work + belt & suspender reasons), so I would expect them to take < 30m anyway.
