### ISSUE TITLE
Consider switching to absl string facilities like StrJoin

### ISSUE THREAD

**Issue by remyabel** [googleapis/google-cloud-cpp#5121]
Per https://github.com/googleapis/google-cloud-cpp/issues/4458#issuecomment-658710495:

> the string char const* sep = probably as part of something that could be replaced by absl::StrJoin().

In some cases this is a no-brainer. Like:

```c++
char const* sep = ", ";
for (auto f : foo) {
   os << f << sep;
}
// becomes:
absl::StrJoin(foo, ", ");
```

In other cases, the code (I think) becomes slightly harder to read. Consider https://github.com/googleapis/google-cloud-cpp/blob/master/google/cloud/bigtable/tests/data_integration_test.cc#L503:

```c++
std::ostringstream os;
char const* sep = "[";
for (auto const& f : failures) {
    os << sep << "failed[" << f.original_index() << "]=" << f.status();
    sep = ", ";
}
os << "]";
return os.str();
```

Becomes:

```c++
struct Formatter {
    void operator()(std::string* out, int original_index) {
        out->append("failed[");
        out->append(std::to_string(original_index));
    }
    void operator()(std::string* out, const google::cloud::Status& status) {
        out->append("]=");
        auto f = absl::StreamFormatter();
        f(out, status);
    }
};
ASSERT_TRUE(failures.empty()) << "failures=" << [&failures]() {
  std::string out = "[";
  for (auto const& f: failures) {
    auto p = absl::PairFormatter(Formatter(), "", Formatter());
    absl::StrJoin(std::make_pair(f.original_index(), f.status()), ", ", p);
  }
  absl::StrAppend(&out, "]");
  return out;
}();
```

Note: I am sleep deprived when I wrote this and the original edit did not work at all, so it's possible this code is non-functional.

The `StreamFormatter` is just a quick way to convert the status to a string. My C++ is a bit rusty so I'm sure it could be simplified but wanted input on the approach before proceeding. Thoughts?

**Comment by coryan** [comment]
FWIW, we could just write:

```cc
ASSERT_TRUE(failures.empty()) << "failures=" << [&failures]() {
  std::string out = "[";
  for (auto const& f: failures) {
    auto p = absl::PairFormatter(Formatter(), "", Formatter());
    absl::StrJoin(std::make_pair(f.original_index(), f.status()), ", ", p);
  }
  absl::StrAppend(&out, "]");
  return out;
}();
```

as

```
ASSERT_THAT(failures, ::testing::ElementsAre());
```

which would print the elements in binary form (at least).  And maybe we can add some `PrintTo()` overloads to correctly format the protos.

**Comment by remyabel** [comment]
On second thought, I think I chose a bad example. My current code (which doesn't compile) would require passing a container of pairs to `StrJoin`, which would undoubtably make the code more complex and unreadable. I'll revisit this in the morning.

> ```
> ASSERT_THAT(failures, ::testing::ElementsAre());
> ```
> 
> which would print the elements in binary form (at least). And maybe we can add some `PrintTo()` overloads to correctly format the protos.

That does sound simpler.

**Comment by remyabel** [comment]
One potential snag is that for custom types, there ends up being duplicate logic between the `ostream` overloads and the custom formatters. Example:

```c++
struct PolicyDocumentConditionFormatter {
    void operator()(std::string* out, PolicyDocumentCondition const& condition) {
        out->append("PolicyDocumentCondition=[");
        out->append(absl::StrJoin(condition.elements(), ", "));
        out->append("]");
    }
};

std::ostream& operator<<(std::ostream& os, PolicyDocumentCondition const& rhs) {
  return os << "PolicyDocumentCondition=["
            << absl::StrJoin(rhs.elements(), ", ") << "]";
}

std::ostream& operator<<(std::ostream& os, PolicyDocument const& rhs) {
  os << "PolicyDocument={";
  os << "expiration=" << google::cloud::internal::FormatRfc3339(rhs.expiration)
     << ", ";
  os << "conditions=[";
  os << absl::StrJoin(rhs.conditions, ", ", PolicyDocumentConditionFormatter{});
  return os << "]}";
}
```

Having these types convertible to string or having a `ToString` like method would solve this issue, but it would also require more refactoring. Is the effort worth it?

**Comment by remyabel** [comment]
This is a duplicate of #2442

**Comment by remyabel** [comment]
What is going on with the assigning to closed issues?

**Comment by coryan** [comment]
@JustinBeckwith is normalizing the issues across all the `googleapis/` repositories to facilitate analysis.  It has been very noisy / spammy.

**Comment by JustinBeckwith** [comment]
Apologies, it's done now.
