### ISSUE TITLE
add sample for setting deadline / retries in spanner

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp#5162]
Implement a sample showing how to configure deadline/timeout and retries in spanner

**Comment by coryan** [comment]
There is one at the bottom of this page:

https://googleapis.dev/cpp/google-cloud-spanner/latest/

Sadly, the `Make*AdminConnection()` functions do have examples:

https://googleapis.dev/cpp/google-cloud-spanner/latest/namespacegoogle_1_1cloud_1_1spanner_1_1v1.html#ad5c7a5710f85cd99a0100a9aafff2ebd

https://googleapis.dev/cpp/google-cloud-spanner/latest/namespacegoogle_1_1cloud_1_1spanner_1_1v1.html#acb6f2ab6c3b387c6dab8c42a8183ddda

And there is a snippet for `MakeConnection()`:


https://github.com/googleapis/google-cloud-cpp/blob/e2af28553ae72e15be90ad207d12aaac470a752d/google/cloud/spanner/samples/samples.cc#L2528-L2557


We just have not connected it to the documentation for this function:

https://googleapis.dev/cpp/google-cloud-spanner/latest/namespacegoogle_1_1cloud_1_1spanner_1_1v1.html#aa84a1b1edc2531ba3d960bf1e17cb756
