### ISSUE TITLE
[Q] How to set request timeout to 10 seconds?

### ISSUE THREAD

**Issue by dkalinowski** [googleapis/google-cloud-cpp#5180]
Hello, our project is using this SDK to retrieve files from google cloud storage. We found out that when running GCS client in a network that requires a proxy with env variables unset: `http_proxy=` `https_proxy=` client hangs for 16 minutes without any log from GCS side, probably due to default timeout settings.

```
...
auto credentials = google::cloud::storage::v1::oauth2::GoogleDefaultCredentials();
auto options = google::cloud::storage::ClientOptions(*credentials);
google::cloud::storage::Client client(options);
client.ListObjects(bucket, google::cloud::storage::Prefix('file.jpg'));
```

By reading documentation we found out there is `RetryPolicy` that could potentially be used to decrease timeout to desired 10 seconds. So we tried using `LimitedErrorCountRetryPolicy` and/or `LimitedTimeRetryPolicy` option decorators to decrease the timeout but without results.

```
google::cloud::storage::Client client(options, google::cloud::storage::LimitedErrorCountRetryPolicy(0), google::cloud::storage::LimitedTimeRetryPolicy(std::chrono::seconds(10)));

$ date
Mon Oct  5 08:50:28 UTC 2020
$ ./client; date
Mon Oct  5 08:52:41 UTC 2020
2min
```

```
google::cloud::storage::Client client(options);

$ date
Mon Oct  5 08:32:02 UTC 2020
$ ./client; date
Mon Oct  5 08:48:42 UTC 2020
16min
```

```
google::cloud::storage::Client client(options, google::cloud::storage::LimitedErrorCountRetryPolicy(0));

$ date
Mon Oct  5 08:21:07 UTC 2020
$ ./client; date
Mon Oct  5 08:23:20 UTC 2020
2min
```

Why is 2minute the magic lower bound limit? Is it bug or intended? How to decrease the timeout to 10 seconds?

**Comment by coryan** [comment]
The short answer is that we do not set a timeout per-se.  The retry policies control for how long does the library keep retrying, but there is not (at this time) a mechanism to set the per-RPC timeout.

I am upgrading this to a feature request.

**Comment by coryan** [comment]
@devbww because this is related to #4926

**Comment by dkalinowski** [comment]
@coryan I don't mean per-RPC timeout. This is example app and all I do is call ListObjects single time. How to set 10 seconds timeout policy for all requests within an app?

**Comment by coryan** [comment]
> @coryan I don't mean per-RPC timeout. This is example app and all I do is call `ListObjects` single time. How to set 10 seconds timeout policy for all requests within an app?

You cannot right now.  When I said "per-RPC" I meant "per-RPC in the retry loop".
