### ISSUE TITLE
[Q] PubSub roadmap

### ISSUE THREAD

**Issue by shinzui** [googleapis/google-cloud-cpp#5199]
The pubsub client is marked as experimental. Do you have a roadmap when it would be safe to use it in production, and it has feature parity with the other language implementations? 

Thank you.

**Comment by coryan** [comment]
Soon?  We are aiming for 2020-Q4.  It might be as soon as 2020-11-01.

**Comment by coryan** [comment]
Sorry, did not mean to close so quickly.  Let me know if you have further questions.

**Comment by shinzui** [comment]
No worries. Thank you for the quick answer, and it’s great that it’s going to be avaialble soon. Is it going to have feature parity with the other clients? I’m particularly interested in dead queue and filtering support.

**Comment by coryan** [comment]
>  Is it going to have feature parity with the other clients?

That is the plan.

> I’m particularly interested in dead queue and filtering support.

The admin APIs to set or update the filter in a subscription are not there yet.

I believe dead letter queues are already working.  There are even examples, this one shows you how to get the delivery attempt count:

https://github.com/googleapis/google-cloud-cpp/blob/5c6ee9e771848d18bb3fd6c21663a4d8d53fd82f/google/cloud/pubsub/samples/samples.cc#L346-L378

There are other examples on how to create dead letter queues and update them.

**Comment by shinzui** [comment]
Thank you. I should have looked at the samples before asking. I’ll close the issue.
