### ISSUE TITLE
Change Subscriber to receive all parameters in the constructor

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#5204]
For consistency with other languages the class will be setup and the `Start()` function will have no arguments.

Makes me wonder if this should be a standalone function.

**Comment by kamalaboulhosn** [comment]
I think ultimately, having a stateful Subscriber class will be useful. There might be some methods coming in the future that would make it easier to have one, e.g., there have been discussions about adding a method to stop tracking a message in flow control and then allowing one to call Ack using the message's AckId. I guess this could be a standalone function as well, though. I do like the symmetry of a Publisher and a Subscriber class.

**Comment by coryan** [comment]
Ack. After #5247 the API became:

```cc
void Handler(pubsub::Message m, pubsub::AckHandler h);

void F(pubsub::Subscription s) {
  pubsub::Subscriber subscriber(pubsub::MakeSubscriberConnection(s));
  auto future = subscriber.Subscribe(Handler);
  future.wait_for(std::chrono::hours(1));
}
```

**Comment by coryan** [comment]
I am assuming it is, closing.
