### ISSUE TITLE
Add instructions for running unit tests and integration tests

### ISSUE THREAD

**Issue by hbchai** [googleapis/google-cloud-cpp#5233]
**What component of `google-cloud-cpp` is this feature request for?**
bigtable

**Is your feature request related to a problem? Please describe.**
The problem is really understanding how to run tests to vet a change being proposed to the project (e.g. candidate for PR).

**Describe the solution you'd like**
It would be very helpful to give example commands for running the unit tests, e.g. with test type filtering, alongside the build instructions.

**Comment by remyabel** [comment]
The easiest way is to use the Docker build which runs the tests automatically. However, I think all the manual instructions are in  https://github.com/googleapis/google-cloud-cpp/blob/master/doc/setup-development-environment.md and https://github.com/googleapis/google-cloud-cpp/blob/master/doc/setup-cmake-environment.md.

**Comment by remyabel** [comment]
There's also https://github.com/googleapis/google-cloud-cpp/blob/master/CONTRIBUTING.md but I think the instructions in all 3 have gotten a bit outdated. Might be worth opening a separate issue on fixing that.

**Comment by coryan** [comment]
This was fixed (I think) as part of the changes for #5246.  For example, see:

https://github.com/googleapis/google-cloud-cpp/blob/master/doc/contributor/howto-guide-running-ci-builds-locally.md
