### ISSUE TITLE
[Q] doxygen-docs seems to fail with strange clang-related error

### ISSUE THREAD

**Issue by remyabel** [googleapis/google-cloud-cpp#5249]
I'm on Fedora 32 with Clang 10.0.1 and Doxygen 1.8.20. I have not updated my packages recently and I'm at HEAD (23a1474fe0cfff3ac93ac5d701dd5934d22088ce). I've used the following steps to build the project:

```
cmake -Hsuper -Bcmake-out/si \
    -DGOOGLE_CLOUD_CPP_EXTERNAL_PREFIX=$HOME/local-cpp -GNinja
cmake --build cmake-out/si --target project-dependencies -- -j 8
cmake -H. -Bcmake-out/home -DCMAKE_PREFIX_PATH=$HOME/local-cpp
cmake --build cmake-out/home -- -j 8
```

Then:

```
cmake --build cmake-out/home --target doxygen-docs
```

Results in this strange error:

```
[  0%] Generate cloud HTML documentation
error: fixed-compilation-database: Error while opening fixed database: No such file or directory
json-compilation-database: Error while opening JSON database: No such file or directory
 using clang compilation database path of: "(null)"
 (warning treated as error, aborting now)
```

If I disable `DOXYGEN_CLANG_ASSISTED_PARSING` which is what instructs Doxygen to use the clang-based backend I get a compilation error instead:

```
[  0%] Generate cloud HTML documentation
[  0%] Built target cloud-docs
Scanning dependencies of target generator-docs
[  0%] Generate generator HTML documentation
/home/tom/second_drive/google-cloud-cpp-1/generator/internal/descriptor_utils.h:50: error: no matching file member found for 
std::vector< std::unique_ptr< GeneratorInterface > > google::cloud::generator_internal::MakeGenerators(const google::protobuf::ServiceDescriptor *service, google::protobuf::compiler::GeneratorContext *context, const std::vector< std::pair< std::string, std::string >> &vars)
Possible candidates:
 'std::vector< std::unique_ptr< GeneratorInterface > > MakeGenerators(google::protobuf::ServiceDescriptor const *service, google::protobuf::compiler::GeneratorContext *context, std::vector< std::pair< std::string, std::string >> const &vars)' at line 252 of file /home/tom/second_drive/google-cloud-cpp-1/generator/internal/descriptor_utils.cc
 (warning treated as error, aborting now)
```

The error persists whether `-DCMAKE_EXPORT_COMPILE_COMMANDS=ON` is present and whether or not `compile_commands.json` is present.

I have deleted my cache/ccache directories and recloned the project, so I don't think it's any stale build files. I also checked out a relatively old (a month) commit and still got the same issue. I'm fairly sure it's an issue with my system, but wanted to post here to double-check that I'm not going crazy.

**Comment by coryan** [comment]
At a guess, we may not be setting `CLANG_DATABASE_PATH`:

https://www.doxygen.nl/manual/config.html#config_source_browser

**Comment by remyabel** [comment]
Thanks. That does not fix the issue either. Just results in this error:

```
error: /usr/include/wchar.h:35:10: fatal error: 'stddef.h' file not found [clang]
```

I also tried using the precompiled version of doxygen 1.8.15 but that also results in a host of errors. I suspect the issue might be Clang compatibility? The Clang on my system is 10 but the prebuilt version of doxygen links against Clang 9, so it's possible that they haven't tested it. I haven't been able to successfully test it yet.

I'll consider reporting this issue upstream but I'll leave this open incase it becomes a blocker for switching the Dockerfiles to Fedora 33.

**Comment by remyabel** [comment]
I'm not going to report this to Doxygen (yet) because I created a minimal example where setting `CLANG_DATABASE_PATH` fixes the issue.

**test.hpp**:

```c++
/**
 * Test
 * @par
 * Blah blah blah.
 */
void test();
```

**main.cpp**:

```c++
#include "test.hpp"
int main() {}
```

**CMakeLists.txt**:

```cmake
cmake_minimum_required(VERSION 3.17.4)

project(doxygen-test CXX)

find_package(Doxygen)
if (Doxygen_FOUND)
    set(DOXYGEN_FILE_PATTERNS *.hpp *.cc)
    set(DOXYGEN_QUIET YES)
    set(DOXYGEN_WARN_AS_ERROR YES)
    set(DOXYGEN_BUILTIN_STL_SUPPORT YES)
    set(DOXYGEN_CLANG_ASSISTED_PARSING YES)
    set(DOXYGEN_CLANG_DATABASE_PATH ${CMAKE_BINARY_DIR})
    set(DOXYGEN_CLANG_OPTIONS "-std=c++11")
    set(DOXYGEN_SEARCH_INCLUDES YES)
    doxygen_add_docs(
        test-docs ${CMAKE_CURRENT_SOURCE_DIR}
        WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR} COMMENT
        "Generate test HTML documentation")
endif ()

set(headers test.hpp)

add_executable(test main.cpp)
```

Then run the following commands:

```console
cmake -H. -Bcmake-out -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
cmake --build cmake-out/ --target test-docs
```

For GCPP, I still get the `stddef.h` error even though I've tried GCC, Clang 9 and Clang 10. This suggests to me that there's some setting somewhere that's breaking. Of course I still think this is a Doxygen bug but I'd like to investigate further before reporting the issue.

**Comment by remyabel** [comment]
Maybe my example was *too* minimalistic. I included `<string>` and now get the `stddef.h` error:

```
error: /usr/include/wchar.h:35:10: fatal error: 'stddef.h' file not found [clang]
 (warning treated as error, aborting now)
```

This leads me back to my original theory about there being a Clang incompatibility issue in Doxygen. The only thing I have not tried yet is to use both GCC 9 **and** Clang 9 (so that Clang finds GCC 9 as the candidate installation).

**Comment by remyabel** [comment]
After testing it with Docker and confirming the issue was not my system, I reported it to Doxygen: https://github.com/doxygen/doxygen/issues/8118

**Comment by coryan** [comment]
FWIW, this seems to go away with Fedora:34.

**Comment by remyabel** [comment]
Even though the original issue is still open (no feedback from developer), it looks like this is fixed now.
