### ISSUE TITLE
Spanner: PITR Database support

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#5256]
OKR tracking issue

**Comment by devbww** [comment]
Delivered https://github.com/googleapis/google-cloud-cpp/archive/preview-spanner_cmek_and_pitr_lite.tar.gz which currently corresponds to commit 69c7348b4c1f2d8f7cdc603c12aa0c265266428b.

Note that once the "throttled" support is released (#5257), we will need to update that tarball.
