### ISSUE TITLE
Allow applications to share Stub and gRPC channels in Publisher/Subscriber

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#5266]
As currently defined a `pubsub::Publisher` is bound to a specific topic, that is probably the "Right Thing":tm: but it is done by binding the underlying `pubsub::PublisherConnection` to a specific topic too, which means applications cannot share gRPC resources (stubs, channels, sockets) across `Publishers`.

That seems less than ideal, the application should have better control of what resources are bound to what.  Indirectly they do, because gRPC shares sockets with the same attributes, even if created by different channels, but that seems a bit awkward to depend on.

The proposed changes in `pubsub::Publisher` are:

```cc
namespace pubsub = google::cloud::pubsub;

void NewStyleP(pubsub::Topic t1, pubsub::Topic t2) {
  auto connection = pubsub::MakePublisherConnection();
  auto p1 = pubsub::Publisher(
    t1, pubsub::PublisherConfig{}, connection);
  auto p2 = pubsub::Publisher(
    t2, pubsub::PublisherConfig{}, connection);
  p1.Publish(...); // no change
  p2.Publish(...); // no change
}

void CurrentStyleP(pubsub::Topic t1, pubsub::Topic t2) {
  // Sharing is indirect, the application has to reason about gRPC internals to figure out what is going on.
  auto p1 = pubsub::Publisher(pubsub::MakePublisherConnection(t1, pubsub::PublisherConfig{}));
  auto p2 = pubsub::Publisher(pubsub::MakePublisherConnection(t2, pubsub::PublisherConfig{}));
  p1.Publish(...); // no change
  p2.Publish(...); // no change
}
```

We would need similar changes in the `Subscriber`.

**Comment by coryan** [comment]
@kamalaboulhosn and @devjgm  thoughts?

**Comment by coryan** [comment]
@kamalaboulhosn and @devjgm sorry to be a bother, but we need to stabilize the API as soon as we can.

**Comment by kamalaboulhosn** [comment]
Just to make sure I understand, the goal is to choose between the approaches in the two `NewStyleP`methods? If so, I prefer the first one. It reminds me of how in Java one passes in a `ChannelProvider` that is used to create the channels. One can either have a provider that returns the same channel or returns different channels each time it is called.

**Comment by coryan** [comment]
Ack. Sounds good.

[*]: the second one is the current style, the function was misnamed, I have corrected that too.

**Comment by coryan** [comment]
I had to revert these changes. Memory management for the thread pools became a nightmare, the APIs look too different from the other libraries, and mocking was weird.  We may revisit this in the future (I think these changes can be made backwards-compatible), but not now.

**Comment by kamalaboulhosn** [comment]
That's fine. I think instantiating publishers to multiple topics in the same task is probably the exception and not the norm.
