### ISSUE TITLE
[Q] ... Character set on the credentials provided by Google

### ISSUE THREAD

**Issue by spnshah** [googleapis/google-cloud-cpp#5290]
Hello,

I have noticed that the credentials text file I receive from Google console, when generating a new set of credentials for a service or user account, is usually in ASCII. Please correct if that understanding isn't true.

So, I wanted to ask, is there a possibility of being provided with credentials contents in Unicode from the console? Is that allowed?

This is to gauge what size needs to be reserved on our end to store the information based on its character set.

Thanks

**Comment by coryan** [comment]
That might be a better question for the IAM folks or the console folks than us.  There are externally visible issue trackers. You may have to browse the components to discover the right one, these may be good starts:

https://issuetracker.google.com/issues/new?component=187225

https://issuetracker.google.com/issues/new?component=187161

**Comment by spnshah** [comment]
Oh okay. Sure, I can ask over there. 

Thanks for the pointer.
