### ISSUE TITLE
Allow disabling benchmarks

### ISSUE THREAD

**Issue by remyabel** [googleapis/google-cloud-cpp#5297]
Benchmarks are not particularly interesting for package maintainers. It seems like pubsub and  spanner already has this logic:

https://github.com/googleapis/google-cloud-cpp/blob/54c23df2975e8e6449295cd22141e30320cf5bf5/google/cloud/spanner/benchmarks/CMakeLists.txt#L99-100

The next two questions are:
- Do we stick with just using `BUILD_TESTING` for this or we introduce a new option like `GOOGLE_CLOUD_CPP_ENABLE_BENCHMARKS`?
- Spanner seems to define `spanner_client_define_benchmarks` twice, I do not know if this is intentional or not

**Comment by coryan** [comment]
I think `BUILD_TESTING` is the way to go.

Defining `spanner_client_define_benchmarks` twice is probably an oversight, but harmless, we define the function and call it once, mostly to get a scope for variables.  Defining it again has no downside other than our own confusion.

**Comment by remyabel** [comment]
I see now that one function is for *micro* benchmarks and the other is for *macro* benchmarks. Although this isn't obvious at first glance, so I'll add a comment.

**Comment by remyabel** [comment]
I looked more closely and it seems like this issue is not necessary.
