### ISSUE TITLE
Consider using nghttp2 with libcurl in our bazel builds

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#5308]
While digging into a separate bug (b/171350177), I noticed that our bazel builds compile libcurl WITHOUT nghttp2, which is different than most normal libcurl package installations, and therefore, different from our cmake builds. Without nghttp2, I *think* our compiled libcurl will only do (up to) HTTP/1.1. I.e., it will not handle HTTP/2.0. 

This may be OK, I'm not necessarily saying it's a bug or a defect. But we may want to look into why this is and see if we want our bazel builds to (also) compile and use nghttp2 and to support HTTP/2.0 transfers.

Note, this mostly affects GCS since that's (currently) the only library that uses libcurl.

**Comment by coryan** [comment]
This might be useful / relevant:

https://github.com/bazelbuild/rules_foreign_cc/blob/master/examples/cmake_nghttp2/BUILD

**Comment by coryan** [comment]
See #5342 seems more doable now that we are using Bazel >= 4.0

**Comment by coryan** [comment]
Punting for now, will revisit.

**Comment by coryan** [comment]
We have no time for this.
