### ISSUE TITLE
spanner::InstanceAdminConnection member functions should return kUnimplemented

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#5338]
We think pure virtual functions are a recipe to break backwards compatibility as we add member functions. The class should:

- Return a status of `kUnimplemented` for simpler RPCs.
- Return a satisfied future with a status of `kUnimplemented` for asynchronous and polling RPCs.
- Return a range containing a single value with status `kUnimplemented` for iteration APIs.

**Comment by devbww** [comment]
This is now the case for `spanner_admin::InstanceAdminConnection` (generated).  `spanner::InstanceAdminConnection` is deprecated.
