### ISSUE TITLE
`Default{InstanceAdmin,Admin,Data}Client` are not entirely thread safe

### ISSUE THREAD

**Issue by dopiera** [googleapis/google-cloud-cpp#5352]
Despite what the documentation says, `DefaultDataClient`, `DefaultInstanceAdminClient` and `DefaultAdminClient` are not really thread-safe because there is no memory nor compiler barrier between their constructors and using the members (so the members might not be in the other thread's view of memory by the time they're used).

The scenario:
* create a `DefaultDataClient`
* once the ctor finishes, pass the pointer to `DefaultDataClient` to another thread
* the other thread accesses a member (e.g. `impl_`), which might point to garbage in this other thread's view of memory

The risk is low, but we should fix it.

**Comment by coryan** [comment]
> create a DefaultDataClient
> once the ctor finishes, pass the pointer to DefaultDataClient to another thread

How would you do that *correctly* without synchronization?  Meaning, I think the act of "pass the pointer ... to another thread", if done correctly, would create a *happens-before* relationship.

**Comment by dopiera** [comment]
After a discussion, we agreed that these objects are no less safe than any other objects (e.g. `std::string`). It is implicitly assumed that whenever an object is shared between threads, its state is fully initialized before other threads access it (which is typically achieved by a full barrier being issued on the transfer from one thread to another). Therefore, I'm closing this issue.
