### ISSUE TITLE
Automatically detect when the API baselines need an update

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#5358]
When we add an API we should update the API baseline before the next release. Otherwise the API might be released, then removed and the `check-abi` script would not detect that we broke the API.

Ideally the builds should detect that the baseline need an update, maybe by breaking both when we add and remove APIs.

**Comment by coryan** [comment]
One possibility is to run the API checks "backwards", using the new API dump as the "baseline" and see if the old dump is missing something.  In principle this should detect additions.

**Comment by devjgm** [comment]
We now update the API baseline as part of each release, so that should take care of this.
https://github.com/googleapis/google-cloud-cpp/tree/main/release
