### ISSUE TITLE
Replace custom time-parsing code with Abseil >= Sept 2020 LTS 

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#5426]
After we can take a dep on the Sept 2020 LTS (https://github.com/abseil/abseil-cpp/releases/tag/20200923.2), we should replace all of our custom time-parsing code with Abseil's time parsing functions. We need to wait on that LTS for some time-parsing fixes in Abseil's code.

This issue is being split out from https://github.com/googleapis/google-cloud-cpp/issues/4458#issuecomment-720472425

**Comment by devbww** [comment]
For the record, I have a pending PR that I believe will cover this.

**Comment by bduclaux** [comment]
Also, StatusOr is now in Abseil. See https://abseil.io/blog/2020-091021-status

**Comment by coryan** [comment]
@bduclaux yes, we are aware, see #4375 (unfortunately the `StatusOr<>` is Abseil is incompatible in a couple of ways)
