### ISSUE TITLE
Split GetObjectMedia not found from grpc_integration_test

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#5428]
This test can only run in production, we should split it to its own file and make it a production-only test.

**Comment by vnvo2409** [comment]
I would like to ask why this test can not run against production ?
One reason is we hard-coded `storage.googleapis.com`
https://github.com/googleapis/google-cloud-cpp/blob/0e3303aad95877f24b25a9523ba10e51d8f6075b/google/cloud/storage/tests/grpc_integration_test.cc#L189

But to me, it is possible to run this test against production.

**Comment by coryan** [comment]
> I would like to ask why this test can not run against production ?

The opposite, right?  It *only* runs against production.  That is because it creates an explicit connection to the production service, as shown in your code sample:

https://github.com/googleapis/google-cloud-cpp/blob/0e3303aad95877f24b25a9523ba10e51d8f6075b/google/cloud/storage/tests/grpc_integration_test.cc#L189


That requires (at least) a valid set of credentials and the right connectivity.  If the question is "Why can't we run this against the emulator?" That would be because we did not have an emulator for gRPC before (or if we did, it did not emulate this behavior).  We can change the test to use your new emulator, of course, that would be better if we can do it.

**Comment by vnvo2409** [comment]
> That would be because we did not have an emulator for gRPC before (or if we did, it did not emulate this behavior). We can change the test to use your new emulator, of course, that would be better if we can do it.

That's right, I ask this question with the new emulator in mind.

**Comment by vnvo2409** [comment]
FYI, this test passes with the new emulator. I changed these lines
https://github.com/googleapis/google-cloud-cpp/blob/d560e4c2664ab6802d4219ede4540c951b20ea52/google/cloud/storage/tests/grpc_integration_test.cc#L197-L198
to
```cpp
auto options = ClientOptions::CreateDefaultClientOptions();
auto channel = google::cloud::storage::internal::CreateGrpcChannel(*options);
```
However, we have to use the `internal` namespace.

**Comment by coryan** [comment]
Using `internal` in our own tests is perfectly Okay.
