### ISSUE TITLE
Automatically create multiple streams on `Subscriber::Subscribe()`

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#5431]
Each StreamingPull is limited to 10MB/s:

https://cloud.google.com/pubsub/quotas#resource_limits

We should create more than one streaming pull for each `Subscribe()` call, controlled with a subscription option, of course.  The implementation seems "simple":

- Create several  `StreamingSubscriptionBatchSource` and `SubscriptionLeaseManagement` objects connected to each other.
- They all feed into a single `SubscriptionMessageQueue`
- Acks and Nacks need to be demux to the right source.
- We need to think more about ordering keys.

**Comment by devjgm** [comment]
Not needed at this point.
