### ISSUE TITLE
New CI build for Bigtable + Direct-Path

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#5432]
We want a PR and CI build that runs the Bigtable tests using direct-path. Some things to consider:

- We need to use a separate project for this
- That suggests we will need custom service account keys and new "resources" (instances and so forth).
- We need to consider the impact of this into flakiness due to quota issues.
- There is no way to verify that Direct-Path (DP) was *actually* used.

Sounds like we should write a one pager, probably as a comment to this bug.

**Comment by coryan** [comment]
/cc: @devjgm this is a candidate for the 2020-Q4 milestone.

**Comment by bduclaux** [comment]
It would be nice to have a small tutorial on how to use Direct Path (setting GOOGLE_CLOUD_ENABLE_DIRECT_PATH, configuring network VPC using gcloud, etc.). 
Seems like there are a few things to do to make it work for customers running on GCE.
Thanks !

**Comment by coryan** [comment]
We actually just need one integration tests in the CI build that uses DP.  That seems more reasonable.

Testing that DP was effective is hard, but maybe can be done by looking a `grpc::ClientContext::peer()`, direct path uses an specific range of IPv6 addresses.

**Comment by coryan** [comment]
This seems to have gone stale, the Bigtable team seems to have changed their minds about needing this, closing, we can reopen if needed.
