### ISSUE TITLE
Avoid markers that look like region tags

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#5446]
We use "region tags" to extract code samples for `cloud.google.com`, a region starts with `[START $tag]` and finishes with `[END $tag]` where `$tag` is the region tag name.  We use similar markers in other places:

https://github.com/googleapis/google-cloud-cpp/blob/0e3303aad95877f24b25a9523ba10e51d8f6075b/ci/generate-markdown/extract-install.sh#L21-L22

We should not. They work, but they confuse some of the tooling, such as the region tag bot.

**Comment by remyabel** [comment]
How will this affect https://github.com/googleapis/google-cloud-cpp/issues/2356?

**Comment by coryan** [comment]
Separate issues I think.  #2356 is asking us to use the bigtable region tags for a README or some other document describing how to install the Bigtable client.  This bug is saying we should not use things that look like region tags for other purposes (e.g. extract from Docker files to `.md` files).

**Comment by remyabel** [comment]
Fixed by https://github.com/googleapis/google-cloud-cpp/pull/5476
