### ISSUE TITLE
[testing] track impact of presubmit coverage being < CI coverage

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp#5456]
presubmit only runs a subset of the full CI tests. This was an intentional tradeoff the team made between build time and coverage.  However, it does mean that the CI run can fail even on "green" PRs.

Our tooling identifies this as a "flake" since it's a build break, although it's not actually a flake, it's deterministic. However, it is still an issue - it makes our repo "red" until a fix is submitted, which potentially impacts customers who are trying to use the repo at `HEAD`, and too many CI failures may be interpreted by users to indicate "low-quality" or process problems.

We had a team discussion about this last week; this PR is to track occurrences and discuss potential mitigation strategies.

Recent occurrences:
* today (Nov 9) in #5454 (fixed in #5455)
* last week (Nov 6) in #5406 (fixed in #5435).

I didn't look for prior examples, but I will look into it and add data here if it's not too time consuming.

**Comment by mr-salty** [comment]
one question: is it possible to run a different set of tests at PR merge time vs. when a PR is created or updated?

**Comment by coryan** [comment]
> one question: is it possible to run a different set of tests at PR merge time vs. when a PR is created or updated?

You mean a new set of builds when somebody presses "Squash + Merge"?  I do not think so.  We *could* create builds (somehow), that only trigger when somebody says "/unleash-the-expensive-tests" (or adds a label to that effect).

**Comment by mr-salty** [comment]
yeah, the former was what I was hoping we could do.
the latter could be useful, although obviously relies on remembering to do it.

**Comment by mr-salty** [comment]
if we figure out how to do the latter we might also introduce a "minimal" label for things like doc changes, comment-only changes, etc. where we really just have to check formatting and can skip the actual tests.

**Comment by coryan** [comment]
I think #5445 pass its builds using cache results from previous runs, `gcs-grpc` is a Bazel-based builds and bazel does not know about changes in the emulator code.  We can revert #5445 or move forward.

**Comment by coryan** [comment]
This could have been caught by better PR builds:

https://source.cloud.google.com/results/invocations/49478c64-57ce-4c9f-a149-691e588f8940

**Comment by coryan** [comment]
A known issue is that only the nightly builds can run some integration tests / samples, see #6020 and:

https://source.cloud.google.com/results/invocations/a5961d35-049b-4b36-8aba-402f1dfb5b64

**Comment by coryan** [comment]
https://source.cloud.google.com/results/invocations/8d58568c-1bc9-4054-8e1f-d0d05e38323d

**Comment by devjgm** [comment]
Is it possible to run some of our windows builds on Linux? Maybe under wine? Maybe cross-compile somehow? Maybe we can't run tests, but I wonder if we could do a rough "compile on windows on Linux" build that may catch some of these errors sooner if fun on every PR/CI in GCB.

... or maybe I'm misunderstanding this issue. What's the reason why the windows/cmake-release-x86 build is not run on every CI/PR?

**Comment by coryan** [comment]
> ... or maybe I'm misunderstanding this issue. What's the reason why the windows/cmake-release-x86 build is not run on every CI/PR?

Good question.  Because it takes about 1hr for the Windows+x86 builds to run.

Why?  Bazel does not support x86 (last time I checked, it may have changed), so we cannot use the Bazel cache like we do for the other builds. So, testing only with CMake.

Why is the CMake build slow?  Because there is no `ccache` equivalent for Windows + MSVC (again, last time I checked, this may have changed).

Could we do this on Linux?  We could try to setup a build with `-m32`, I am not sure it would catch the same problems, but maybe some.

**Comment by remyabel** [comment]
Drive-by comment: this discussion reminded me that [msvc-wine](https://github.com/mstorsjo/msvc-wine) exists.

**Comment by coryan** [comment]
FYI, Bazel 4.1.0 supports MSVC+x86:

https://docs.bazel.build/versions/4.1.0/windows.html#build-c-with-msvc

Unfortunately, BoringSSL does not, so our builds fail. I started on support for this in the CI scripts:

https://github.com/coryan/google-cloud-cpp/pull/new/ci-create-bazel-x86-build-configuration

**Comment by coryan** [comment]
https://source.cloud.google.com/results/invocations/16fa3e54-f71c-4d23-b4bb-9adb0cd06834

**Comment by coryan** [comment]
https://github.com/googleapis/google-cloud-cpp/pull/7323

**Comment by coryan** [comment]
https://source.cloud.google.com/results/invocations/7de7f3ec-4e0b-40ff-b281-54d4d1870af1

**Comment by coryan** [comment]
http://sponge2.corp.google.com/4f93c60f-8269-4158-bbaf-f78fab9a9fb4

**Comment by dbolduc** [comment]
https://source.cloud.google.com/results/invocations/f7184aec-4c82-4082-8916-23abc0fc03ad

**Comment by coryan** [comment]
https://source.cloud.google.com/results/invocations/419c4a81-0991-48a2-92fc-7c47b2bb87f2

**Comment by coryan** [comment]
FWIW, the builds now take about 30m.  It should be possible to enable the presubmit builds without impacting our PR times too much.

**Comment by coryan** [comment]
We closed the gap now that Windows builds run on `n1-standard-16` VMs.
