### ISSUE TITLE
[Flake] Windows bazel build failure: Failed to connect to <cache URL>: cannot find a NameResolver for <cache URL>

### ISSUE THREAD

**Issue by mr-salty** [googleapis/google-cloud-cpp#5477]
This happened for 3 windows bazel builds in the same invocation (2020-11-10, 21:00PST, PR #5458 ):

[`bazel`](https://source.cloud.google.com/results/invocations/7c9a032c-4e4b-4329-9e1b-c2dd37aaf648/targets/cloud-devrel%2Fclient-libraries%2Fcpp%2Fgoogle-cloud-cpp%2Fwindows%2Fbazel/log)
[`bazel-release`](https://source.cloud.google.com/results/invocations/430901e6-35b7-428d-8e16-732d5707d0ba/targets/cloud-devrel%2Fclient-libraries%2Fcpp%2Fgoogle-cloud-cpp%2Fwindows%2Fbazel-release/log)
[`quickstart-bazel`](https://source.cloud.google.com/results/invocations/92bae5cd-9805-4866-ad88-f91e0d5d9baa/targets/cloud-devrel%2Fclient-libraries%2Fcpp%2Fgoogle-cloud-cpp%2Fwindows%2Fquickstart-bazel/log)

they all failed in a similar fashion with i.e. `ERROR: Failed to connect to 'https://storage.googleapis.com/cloud-cpp-bazel-cache/windows/bazel': cannot find a NameResolver for https://storage.googleapis.com/cloud-cpp-bazel-cache/windows/bazel`

```
Using bazel remote cache: https://storage.googleapis.com/cloud-cpp-bazel-cache/windows/bazel

2020-11-11T05:04:33.5072605+00:00 Fetch dependencies [1]

2020-11-11T05:04:33.5072605+00:00 Compiling and running unit tests
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=80
INFO: Options provided by the client:
  Inherited 'build' options: --python_path=C:/Python37/python.exe
INFO: Reading rc options for 'test' from t:\src\github\google-cloud-cpp\.bazelrc:
  Inherited 'build' options: --copt=-DGRPC_BAZEL_BUILD --experimental_convenience_symlinks=ignore
ERROR: Unrecognized option: --experimental_convenience_symlinks=ignore
INFO: Invocation ID: 3cd7b7fe-36df-4a0e-9e74-a163273232e3
ERROR: Failed to connect to 'https://storage.googleapis.com/cloud-cpp-bazel-cache/windows/bazel': cannot find a NameResolver for https://storage.googleapis.com/cloud-cpp-bazel-cache/windows/bazel
bazel test failed with exit code 2.
```

The quickstart build had some additional errors: `ERROR: Unrecognized option: --remote_cache=...`.  That does not appear in the other builds, and does not appear in a [successful `quickstart-bazel` build]( https://source.cloud.google.com/results/invocations/4160b1db-89e7-4635-9398-0636294c23e5/targets/cloud-devrel%2Fclient-libraries%2Fcpp%2Fgoogle-cloud-cpp%2Fwindows%2Fquickstart-bazel/log), although it seems to be using the same URL: `Using bazel remote cache: https://storage.googleapis.com/cloud-cpp-bazel-cache/windows/quickstart-bazel`

```
Using bazel remote cache: https://storage.googleapis.com/cloud-cpp-bazel-cache/windows/quickstart-bazel

2020-11-11T05:04:49.1971807+00:00 Loading integration tests config

2020-11-11T05:04:50.4471152+00:00  Fetch dependencies for bigtable [1]
Starting local Bazel server and connecting to it...
ERROR: Unrecognized option: --remote_cache=https://storage.googleapis.com/cloud-cpp-bazel-cache/windows/quickstart-bazel

2020-11-11T05:05:52.4784087+00:00  Fetch dependencies for bigtable [2]
ERROR: Unrecognized option: --remote_cache=https://storage.googleapis.com/cloud-cpp-bazel-cache/windows/quickstart-bazel

2020-11-11T05:07:52.5900105+00:00  Fetch dependencies for bigtable [3]
ERROR: Unrecognized option: --remote_cache=https://storage.googleapis.com/cloud-cpp-bazel-cache/windows/quickstart-bazel

2020-11-11T05:10:52.7017110+00:00  Compiling quickstart for bigtable
INFO: Invocation ID: 9e9c8046-27ae-4654-8b92-f5467144532b
ERROR: Failed to connect to 'https://storage.googleapis.com/cloud-cpp-bazel-cache/windows/quickstart-bazel': cannot find a NameResolver for https://storage.googleapis.com/cloud-cpp-bazel-cache/windows/quickstart-bazel
ERROR: Error initializing RemoteModule
```

**Comment by mr-salty** [comment]
no other invocations (including the preceding and following ones) exhibit this issue AFAICT

**Comment by coryan** [comment]
FWIW, an error earlier in those logs is (I think) relevant:

```
T:\src>choco install --no-progress -y bazel --version 3.5.0
Chocolatey v0.10.15
Installing the following packages:
bazel
By installing you accept licenses for the packages.
[NuGet] The operation has timed out
bazel not installed. The package was not found with the source(s) listed.
 Source(s): 'https://chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Version was specified as '3.5.0'. It is possible that version
 does not exist for 'bazel' at the source specified.
Please see https://chocolatey.org/docs/troubleshooting for more
 assistance.
```

That left the default version of Bazel installed on the machine, which much too old for our needs:

```
2020-11-11T05:04:26.6674007+00:00 Capture Bazel information for troubleshooting
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
Build label: 0.24.1
```

One action to take would be to stop the build if the Bazel installation fails.  Better to fail earlier.

A different action would be to retry, one would hope `chocolatey` does that automatically, but evidently it does not:

https://github.com/chocolatey/choco/issues/385

Yet another action would be to setup our own Kokoro machines with Bazel 3.x pre-installed, so we don't need to install it as part of the CI build.

**Comment by mr-salty** [comment]
Thanks for taking a look, I missed that.

I think retrying and then failing the whole build is reasonable for now, I'll plan to do that (whether I can figure out how to test it is another thing...)

**Comment by mr-salty** [comment]
sorry, I didn't get around to this and likely won't, so unassigning...

**Comment by coryan** [comment]
No repeats or updates in more than 90d, closing.
