### ISSUE TITLE
Remove emulator workarounds for version_retention_period in Spanner integration tests

### ISSUE THREAD

**Issue by devbww** [googleapis/google-cloud-cpp#5479]
There is some cleanup to do in the integration tests and samples when the Spanner emulator supports `version_retention_period`.

**Comment by devbww** [comment]
Let's keep the reminder open (if only to keep our `TODO(#5479)` comments live).

**Comment by devbww** [comment]
Let's keep the reminder open (if only to keep our TODO(#5479) comments live).

**Comment by coryan** [comment]
This is waiting for emulator to fix things.
