### ISSUE TITLE
Enable GCS integration test against the emulator on Window and MacOS

### ISSUE THREAD

**Issue by vnghia** [googleapis/google-cloud-cpp#5498]
**What component of `google-cloud-cpp` is this feature request for?**
`google/cloud/storage`

This issue is a remind for us to enable GCS integration tests against the emulator in the CI for Windows and MacOS

/cc @coryan

**Comment by coryan** [comment]
Too busy right now. Maybe if we move the macOS + Windows builds to a different CI system.

**Comment by coryan** [comment]
This is obsolete. We decided to disable all but the quickstart tests on Windows and macOS.
