### ISSUE TITLE
generator: generate integration test boilerplate

### ISSUE THREAD

**Issue by scotthart** [googleapis/google-cloud-cpp#5501]
While the details of each integration test will require hand authoring, much of the build and code framework can be generated.

**Comment by scotthart** [comment]
It should be possible to generate the failure case for each rpc, by sending an empty request.

**Comment by scotthart** [comment]
These rpc failure test cases should be generated exercise the logging decorator.

**Comment by coryan** [comment]
We decided this would not be needed, closing.
