### ISSUE TITLE
Support ArchLinux package

### ISSUE THREAD

**Issue by mortymacs** [googleapis/google-cloud-cpp#5505]
**What component of `google-cloud-cpp` is this feature request for?**
Support the ArchLinux package.

**Is your feature request related to a problem? Please describe.**
In ArchLinux, I should compile the project manually and use it the same as other distributions as you mentioned.
But with a little bit different dependencies. 

**Describe the solution you'd like**
I've prepared 3 AUR packages for ArchLinux based on your instructions:
https://aur.archlinux.org/packages/google-cloud-cpp/
https://aur.archlinux.org/packages/google-crc32c/
https://aur.archlinux.org/packages/google-cloud-cpp-abseil-cpp/

Users can install `google-cloud-cpp` by `yay` for example, `yay -S google-cloud-cpp`.
All dependencies will be installed automatically and no need for any extra step.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by coryan** [comment]
Thank you very much for doing this.  Can you share what made it hard (if anything) to prepare these packages?  Or put another way, what could we do to make it easier for people like you to prepare the package specifications?

Any thoughts on how can we help you maintain these packages up to date?  Should we send you PRs when we create new releases?  Where to?

I noticed that you created a `google-cloud-cpp-abseil-cpp` package, while the `grpc` also compiles Abseil as a dependency:

https://github.com/archlinux/svntogit-community/blob/packages/grpc/trunk/PKGBUILD#L18

Shouldn't we use that instead? Or maybe refactor abseil-cpp to its own package?

**Comment by mortymacs** [comment]
Dear @coryan,
Thank you. well, I've already prepared the ArchLinux package based on your document with a little bit of customization, but the whole steps are the same. I just wanted to tell you that maybe we can add it to the document ([packaging](https://github.com/googleapis/google-cloud-cpp/blob/master/doc/packaging.md)) for the ArchLinux distribution. Because I as a developer had this problem and I start using Docker(Ubuntu) instead to compile my codes. But now by this ArchLinux package, I can do the development and compilation in my system without any virtualization or dockerizing and I know I only need to keep updating these packages by watching the google-clould-cpp repository.

About, abseil-cpp, I checked that and I asked about it, the abseil-cpp inside grpc is using as a vendor and it will not be installed globally in the client system. I've created a new abseil-cpp pacakge because google-cloud-cpp uses a specific abseil-cpp version. When I tried to compile it with the new abseil-cpp version, it starts showing some errors like can't find a specific namespace in abseil-cpp library and it failed.
If you have a plan to upgrade google-cloud-cpp to use the new abseil-cpp, please let me know I can contribute :wink:

**Comment by devjgm** [comment]
We're still considering whether/how we're going to support binary packages. When we do, we'll consider arch packages as well.
