### ISSUE TITLE
Consider a cmake variable like GOOGLE_CLOUD_CPP_ENABLE=gcs,spanner

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#5511]
We currently expose CMake variables to let folks enable/disable building each library.

https://github.com/googleapis/google-cloud-cpp/blob/d560e4c2664ab6802d4219ede4540c951b20ea52/CMakeLists.txt#L128-L139

We expose one variable per library. Each one defaults to `ON`. As the number of libraries grows, especially as we start auto-generating them, expecting users to enumerate each library that they want to turn `OFF` will not scale.

Instead, we may want to expose a single CMake variable that takes a list of libraries to build. The default could still be all libraries, but it could be overridden on the cmake command-line if a user only wants to build a subset of the libraries. I imagine a variable something like

```shell
$ cmake -DGOOGLE_CLOUD_CPP_ENABLE=gcs,spanner ...
``` 

Which would build *only* the GCS and Spanner libraries (and all their deps). This would work correctly for users even as our repository grows new libraries.

**Comment by remyabel** [comment]
Note that combining `GOOGLE_CLOUD_CPP_ENABLE` with `GOOGLE_CLOUD_CPP_ENABLE_*` may pose problems. Assume for the sake of argument we explicitly enable anything specified in `GOOGLE_CLOUD_CPP_ENABLE` then disable the rest (rather than set everything to OFF by default for compatibility), we would need to use `set (... CACHE ... FORCE)` to override the options. However, this means the user can no longer override these variables. See [Confused about CMake's cached variable setting priority](https://stackoverflow.com/questions/26145865/confused-about-cmakes-cached-variable-setting-priority). There is rather the ugly workaround of using different variables than the options themselves but perhaps there is a better way.

**Comment by coryan** [comment]
One thought is to have:

1) Initialize the list from the individual variables unless it is set in the command line. something like:

```cmake
set(GOOGLE_CLOUD_CPP_ENABLE_DEFAULT)
# Add all the GOOGLE_CLOUD_CPP_ENABLE_* variables that are ON

set(GOOGLE_CLOUD_CPP_ENABLE
    ${GOOGLE_CLOUD_CPP_ENABLE_DEFAULT}
    CACHE STRING "The list of libraries to build.")
```

2) Change the conditions from:

```cmake
if (GOOGLE_CLOUD_CPP_ENABLE_STORAGE)
    add_subdirectory(google/cloud/storage)
endif ()
```

to:

```cmake
if (storage IN_LIST GOOGLE_CLOUD_CPP_ENABLE)
    add_subdirectory(google/cloud/storage)
endif ()
```

**Comment by devjgm** [comment]
I like that this approach works with with both the old and the new-style "enable" variables. Would we need to continue adding per-library `GOOGLE_CLOUD_CPP_ENABLE_*` variables as we add more libraries?  

Another thought would be to initialize `GOOGLE_CLOUD_CPP_ENABLE` by default to a list containing all of the libraries. Then remove the ones where `GOOGLE_CLOUD_CPP_ENABLE_*` is OFF. Maybe like

```cmake
set(GOOGLE_CLOUD_CPP_ENABLE
    "storage;spanner;pubsub;bigtable;..."
    CACHE STRING "The list of libraries to build.")

if (NOT $GOOGLE_CLOUD_CPP_ENABLE_STORAGE)
  list(REMOVE_ITEM $GOOGLE_CLOUD_CPP_ENABLE "storage")
endif ()
# and so on for the 7 library-specific enables that we have today. Do not add more for new libraries.

foreach (library IN $GOOGLE_CLOUD_CPP_ENABLE)
  add_subdirectory(google/cloud/${library})
endforeach ()
```

**Comment by remyabel** [comment]
I think both of those approaches don't follow the requirement that `GOOGLE_CLOUD_CPP_ENABLE` builds only what's listed and disables everything else, although I only tested @devjgm's approach. Although I'm happy to drop this requirement if it simplifies things.

> Initialize the list from the individual variables unless it is set in the command line

I'm not sure how exactly to "detect" that a variable is being set from the command line. If I understand correctly, the logic is:

- All the `GOOGLE_CLOUD_CPP_ENABLE_*` options are enabled by default
- `GOOGLE_CLOUD_CPP_ENABLE` is empty by default, unless overridden by the command-line

But if we add any `GOOGLE_CLOUD_CPP_ENABLE_*` that is `ON` to the list then that will also include the options enabled by default. Maybe I'm overthinking it?

**Comment by coryan** [comment]
> I think both of those approaches don't follow the requirement that `GOOGLE_CLOUD_CPP_ENABLE` builds only what's listed and disables everything else, 

How so?  The change also proposes to change the `add_subdirectory()` commands to be protected by the list, using `storage` as an example the top-level CMake file would say:

```cmake
if (storage IN_LIST GOOGLE_CLOUD_ENABLE)
  add_subdirectory(storage)
endif ()
```


> > Initialize the list from the individual variables unless it is set in the command line
> 
> I'm not sure how exactly to "detect" that a variable is being set from the command line. 

I was thinking that if the variable was not "ON" then it was changed in the command-line, but @devjgm's approach appears more robust.

> But if we add any `GOOGLE_CLOUD_CPP_ENABLE_*` that is `ON` to the list then that will also include the options enabled by default. Maybe I'm overthinking it?

Right, that is why @devjgm approach of removing the items from the list that are OFF seems better.


Maybe I am confused, if you implemented this already update the PR and we can discuss over the code.

**Comment by remyabel** [comment]
> How so? The change also proposes to change the add_subdirectory() commands to be protected by the list, using storage as an example the top-level CMake file would say:

Makes sense. I think I confused myself when I was checking the values of the variables and forgot about this aspect of the approach. Thanks for the clarification.
