### ISSUE TITLE
[Flake] Windows+MSVC+x86 link failure due to "virus"

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#5536]
Seems like the virus detector had a false positive. The change (obviously) did not include any viruses, and the file in question was not even part of the last change (or affected by it in any meaningful way).

```
mt.exe : general error c101008d: Failed to write the updated manifest to the resource of file "google\cloud\grpc_error_delegate_test.exe". Operation did not complete successfully because the file contains a virus or potentially unwanted software.
```

https://source.cloud.google.com/results/invocations/b272f599-2c38-42b7-b5a5-962fe8f0b61a

This may be related to the problems reported in #4539

**Comment by devjgm** [comment]
We disabled the virus detector in our build directories recently to fix other issues it was causing, and I suspect that disabling that would also fix this issue.

I'm going to close this assuming it's been worked around now. We can reopen if we see another one of these.

Related to https://github.com/googleapis/google-cloud-cpp/issues/4539
