### ISSUE TITLE
[Flake] Storage emulator fails with "internal server error" during testing

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#5553]
I have noticed a number of these failures, all in PRs so far:

```
[ RUN      ] ObjectFileIntegrationTest.UploadFileBinary
../../google/cloud/storage/tests/object_file_integration_test.cc:241: Failure
Value of: meta
Expected: is OK
Actual: Retry policy exhausted in InsertObjectMedia: <html>
  <head>
    <title>Internal Server Error</title>
  </head>
  <body>
    <h1><p>Internal Server Error</p></h1>

  </body>
</html>
 [UNAVAILABLE] [UNAVAILABLE]
[  FAILED  ] ObjectFileIntegrationTest.UploadFileBinary (123509 ms)
```

https://source.cloud.google.com/results/invocations/b48a5fb1-83a3-4766-9371-2e44343e43de/targets

**Comment by coryan** [comment]
@vnvo2409 FYI.

**Comment by vnvo2409** [comment]
Do these failures always happen with `UploadFileBinary` ?

It seems that the log wasn't dumped as expected. I will send a PR for:

- dumping log.
- better error propagation.
- unittest for binary data.

**Comment by coryan** [comment]
> Do these failures always happen with `UploadFileBinary` ?

As far as I can tell, yes.

> It seems that the log wasn't dumped as expected. I will send a PR for:
> 
> * dumping log.
> * better error propagation.
> * unittest for binary data.

Thanks.
