### ISSUE TITLE
[flake] google/cloud:completion_queue_test fails on invalid notify counter

### ISSUE THREAD

**Issue by dopiera** [googleapis/google-cloud-cpp#5571]
The test failed on me on unrelated changes with the following assertion:

google/cloud/completion_queue_test.cc:707: Failure
Expected: (impl->notify_counter()) <= (kBurstCount * burst_size / 2), actual: 8529 vs 6400

Detailed test log:
https://source.cloud.google.com/results/invocations/a4fe5b78-48b4-430e-9483-bb9d492c51a2/targets/cloud-cpp%2Fgithub%2Fgoogle-cloud-cpp%2Fmaster%2Fdocker%2Ftsan-presubmit/log

It seems that the check itself is too aggressive, but more investigation is needed.

**Comment by devjgm** [comment]
Some more data about this flake.

Currently, it looks like this flakes < 1:100 runs, which I determined by seeing no flakes with.
```shell
$ bazel test --config=tsan --runs_per_test=100 //google/cloud:completion_queue_test
...
//google/cloud:completion_queue_test                                     PASSED in 70.9s
  Stats over 100 runs: max = 70.9s, min = 21.5s, avg = 66.2s, dev = 9.1s
```
But from many runs throughout the day, I did see it flake sometimes, so the flake _is_ reproducible, though rarely.

HOWEVER, in https://github.com/googleapis/google-cloud-cpp/pull/5579, I'm upgrading gRPC to the newest 1.34.0 release, and with this change, this TSAN flake is much more reproducible (though still a flake).

```shell
$ bazel test --config=tsan --runs_per_test=100 //google/cloud:completion_queue_test
...
//google/cloud:completion_queue_test                                     FAILED in 5 out of 100 in 122.7s
```

So I think we'll need to address this flake before upgrading to gRPC 1.34.0 (which is currently blocked on some other issues, like https://github.com/grpc/grpc/issues/24904)

**Comment by coryan** [comment]
I think the "fix" is to remove this assertion:

https://github.com/googleapis/google-cloud-cpp/blob/2997d2f90cab96279ae955c4399cc00744633d04/google/cloud/completion_queue_test.cc#L707

Basically this is asserting that "most" bursts do not create a new notification (because an existing thread will handle them).   This is true for an average run, but a particular run may fail to show this.  I would have gone with a stronger assertion, something like:

```cc
  EXPECT_LE(impl->notify_counter(), kBurstCount + delta);
```

with `delta` being some small number, and I thought (incorrectly) that the weaker assertion would not flake.

**Comment by devjgm** [comment]
Sounds reasonable to me. I can make a PR, because I can test it easily w/ my other PR patched in.

**Comment by coryan** [comment]
Ooops, I created a PR already.  I was able to repro the problem using:

```
CXX=clang++ CC=clang bazel test --config tsan --runs_per_test=1600 --jobs=64 --test_tag_filters=-integration-test //google/cloud:completion_queue_test
```

and it went away after my change.

**Comment by devjgm** [comment]
Ack, ok. thanks.
