### ISSUE TITLE
Visual Studio 2017

### ISSUE THREAD

**Issue by tgredfish** [googleapis/google-cloud-cpp#5573]
Can this be compiled and used in Visual Studio 2017?  If not what support is there for google cloud api libraries in VS 2017?

**Comment by coryan** [comment]
> Can this be compiled and used in Visual Studio 2017?

We don't test with it, so at a guess I would say "no, but we probably could get it to work".  Let me give it a try and I can at least tell you how hard it would be.

> If not what support is there for google cloud api libraries in VS 2017?

Don't have any good answers for you.  Presumably you could compile with MSVC 2019 and then link the binary artifacts with 2017, but that sounds terribly convoluted.

**Comment by coryan** [comment]
Yup, it did not compile, and it was not that hard to get a build going. I used Bazel for my test.  See above for the PR to fix the build problems, note that there is potentially more work to fix the integration tests (unlikely, but not out of the question).  And note that we have not setup a CI build, so this could break again.

**Comment by tgredfish** [comment]
Thank you for the quick response.  I will follow the thread to see if this becomes available to compile in MSVC 2017.  We are not in a position to upgrade to the new compiler yet.  But when we do, I will check this out again.

**Comment by coryan** [comment]
Glad we could help. I am going to close this question as it is now answered.

FWIW, in addition to fixing the existing build problems I just finished configuring CI builds for MSVC 2017, that means the code should continue to build with this compiler for the foreseeable future. The next release (due in about a month) should include these changes, but you can pick them up from the tip of `master` right now if you prefer.
