### ISSUE TITLE
Automatically save state in UploadFile.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#559]
For APIs that write in chunks, we should consider two approaches to support resumable uploads:

- [ ] The upload iostream has accessors to get the resume token.  The library automatically uses the token if an RPC fails.  The application is responsible for saving and reusing the token in the case where the application crashes.

- [ ] For the "upload file" API, the application provides an interface to store and retrieve tokens, e.g.:

```C++
class UploadTokenSaver { public:
  virtual void StoreToken(
    std::string const& bucket_name, std::string const& object_name, std::string const& token) = 0;
  virtual std::pair<bool, std::string> RetrieveToken(
    std::string const& bucket_name, std::string const& object_name) = 0;
};
```

- [ ] The library should provide a basic `UploadTokenSaver` using flat files in `$HOME/.boto` or a similar directory.

- [ ] The library might provide a `UploadTokenSaver` class based on sqlite, this should be optional and not built by default (or the build should not fail if sqlite is not found).

**Comment by coryan** [comment]
I am moving this out of the Beta milestone.
The remaining work to make the `UploadFile()` API automatically save its state is more of an advanced feature.

/cc: @frankyn @houglum

**Comment by houglum** [comment]
Makes sense, +1.

**Comment by frankyn** [comment]
Sorry I may have heard this part before, but what do you mean by save its state?

**Comment by coryan** [comment]
At some point we thought it would be nice if `UploadFile()` saved the resumable session in some persistent store (that the application would need to provide), and if the application crashes then it can restore the state and restart the file upload from the last received byte.

That level of magic belongs in the advanced features for the library.

**Comment by frankyn** [comment]
Thanks for clarifying. I agree as well.

**Comment by coryan** [comment]
We are going to close this, when we get customer demand for it we can revisit.
