### ISSUE TITLE
[Q] Building GCP CPP SDK v1.21.0

### ISSUE THREAD

**Issue by adhitya97** [googleapis/google-cloud-cpp#5590]
I am trying to build only the storage library portion of GCP CPP SDK using CMake, mentioning 

`GOOGLE_CLOUD_CPP_ENABLE=storage`

and 

`GOOGLE_CLOUD_CPP_ENABLE_GRPC_EXPRESSION OFF`

Prior to v1.21.0, the storage library did not require GPRC, protobuf and building of some external APIs.

But, with v1.21.0, it seems like these additional libraries also look to be built. Is it because some dependencies have been added to the storage library on these package?

If it is indeed required, how can I point the build source to a local server rather than to an external Github repository for the Google API build?

**Comment by coryan** [comment]
> 
> Prior to v1.21.0, the storage library did not require GPRC, protobuf and building of some external APIs.

Ack.

> 
> But, with v1.21.0, it seems like these additional libraries also look to be built. Is it because some dependencies have been added to the storage library on these package?

No, but it seems we introduced a bug in how `GOOGLE_CLOUD_CPP_ENABLE_GRPC` and `GOOGLE_CLOUD_CPP_ENABLE_GRPC_EXPRESSION` are computed.  Let me see if I can find a workaround.

> If it is indeed required, how can I point the build source to a local server rather than to an external Github repository for the Google API build?

I am not sure I follow.  Are you trying to avoid the download from http://github.com/googleapis/googleapis ?

**Comment by adhitya97** [comment]
> I am not sure I follow. Are you trying to avoid the download from http://github.com/googleapis/googleapis ?

Yes, I am trying to avoid the download.

**Comment by coryan** [comment]
> No, but it seems we introduced a bug in how `GOOGLE_CLOUD_CPP_ENABLE_GRPC` and `GOOGLE_CLOUD_CPP_ENABLE_GRPC_EXPRESSION` are computed.

It seems that the test libraries are built by default and they need the gRPC dependencies.  I will send a PR to fix that.

> Let me see if I can find a workaround.

This works for me, please let us know if it makes sense:

```sh
cmake -GNinja -H. -Bcmake-out/only-storage \
    -DGOOGLE_CLOUD_CPP_ENABLE=storage \
    -DBUILD_TESTING=OFF \
    -DGOOGLE_CLOUD_CPP_ENABLE_GRPC=OFF
```

Naturally you can use another generator (other than `Ninja`), and/or may need to provide additional flags such as `CMAKE_PREFIX_PATH`.

**Comment by coryan** [comment]
> > I am not sure I follow. Are you trying to avoid the download from [http://github.com/googleapis/googleapis](https://github.com/googleapis/googleapis) ?
> 
> Yes, I am trying to avoid the download.

Okay, I have not tested this in a long time, but you may be able to use `-DGOOGLE_CLOUD_CPP_GOOGLEAPIS_URL=$ALTERNATIVE_LOCATION` in your CMake configuration step.

**Comment by coryan** [comment]
I guess this question is now answered. If you have any followups please feel free to reopen.
