### ISSUE TITLE
generator: determine how to generate ConnectionOptions in a multi-service product

### ISSUE THREAD

**Issue by scotthart** [googleapis/google-cloud-cpp#5601]
Given that the current `google::cloud::ConnectionOptions` supports only a single endpoint, determine how `google::cloud::<product>::ConnectionOptions` should be defined/generated in a product with multiple services where not all the services have the same endpoint.

**Comment by devjgm** [comment]
We might want to see if we can factor the default endpoint out of ConnectionOptions. We might be able to remove that requirement from `ConnectionTraits` ([link](https://github.com/googleapis/google-cloud-cpp/blob/00671b0972e27d66301a56801e3f7859e56d3439/google/cloud/connection_options.h#L77)), and have the default end-point be set within the `MakeConnection()` method itself. The `ConnectionOptions` class itself could retain (for API compat) `endpoint()` and `set_endpoint()` methods, but these would only be for users who wish to _override_ the endpoint. The default wouldn't be set there.

Just a thought.

**Comment by scotthart** [comment]
Would we also need to factor out the other defaults provided in ConnectionOptions? number of transport channels and user agent string prefix?
