### ISSUE TITLE
[Q] Setting the SSL certificate path when creating credentials using CreateComputeEngineCredentials

### ISSUE THREAD

**Issue by adhitya97** [googleapis/google-cloud-cpp#5619]
Is there a way to set the SSL root path while creating credentials using the CreateComputeEngineCredentials()?

Also, how can client options like HTTP request timeouts be set while creating a client? Ideally, this would be done in the curl init, but would this support be extended later?

**Comment by coryan** [comment]
> Is there a way to set the SSL root path while creating credentials using the CreateComputeEngineCredentials()?

For the credentials?  No, we have not added anything to support that.  I don't think it is needed, as the compute engine credentials are fetched via `http`:

https://github.com/googleapis/google-cloud-cpp/blob/8cc99f977b55097ae359fab29373ae17370fd7af/google/cloud/storage/oauth2/compute_engine_credentials.h#L132-L146

> Also, how can client options like HTTP request timeouts be set while creating a client?

You cannot, see #5180 for the existing feature request.

> Ideally, this would be done in the curl init, but would this support be extended later?

I am not sure I follow.



PS: In the future, could you split topics like this?  It is too easy for us to miss an aspect of a multi-topic question vs. a single-topic request.

**Comment by coryan** [comment]
Please feel free to reopen this question if you want to follow up.
