### ISSUE TITLE
Consider using a single inline namespace for all the libraries

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#5622]
Currently each library has a different inline namespace, e.g. `google::cloud::spanner::$VERSION`, and `google::cloud::pubsub::$VERSION`.  Now that all the libraries share a version we should consider moving them to `google::cloud::$VERSION`.

This is a breaking change, and it is not clear there is an advantage to our customers.  Without such an advantage I would say we should not do it.

**Comment by devjgm** [comment]
We tried this with the generator, but were not able to do it due to the issues described in https://github.com/googleapis/google-cloud-cpp/issues/5974
