### ISSUE TITLE
[Flake] Invalid JWT errors in macOS build

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#5689]
https://source.cloud.google.com/results/invocations/f79d1093-334b-4633-b572-ddd56ef3a533

```

Standard exception raised: Permanent error in CreateBucket: {"error":"invalid_grant","error_description":"Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values in the JWT claim."} [INVALID_ARGUMENT] [INVALID_ARGUMENT]
libc++abi.dylib: terminating with uncaught exception of type google::cloud::v1::RuntimeStatusError: Permanent error in CreateBucket: {"error":"invalid_grant","error_description":"Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values in the JWT claim."} 
```

The clocks may be out of sync:

```
Errors while running CTest
2021-01-07T19:38:25Z: build script reported errors. 


[ID: 9023459] Build finished after 1706 secs, exit value: 1


Warning: Permanently added 'localhost' (ECDSA) to the list of known hosts.

[11:33:23] Collecting build artifacts from build VM
```

I reached out to the Kokoro folks.

**Comment by coryan** [comment]
Confirmed by the Kokoro folks, they fixed the machine in question. It remains unclear if other machines may have the same problem now or into the future.

**Comment by coryan** [comment]
I think this is the same:

http://sponge2/5953ae02-9a79-49c7-9f1b-d29ce7fe0f99

**Comment by devjgm** [comment]
Again https://source.cloud.google.com/results/invocations/a07fafe6-c7b2-4cd9-8f3b-05055cad4091/targets/cloud-cpp%2Fgithub%2Fgoogle-cloud-cpp%2Fmaster%2Fmacos%2Fquickstart-bazel-presubmit/log

**Comment by coryan** [comment]
https://source.cloud.google.com/results/invocations/20452e60-887d-4b14-bd91-c850a37b8fa1

**Comment by coryan** [comment]
https://source.cloud.google.com/results/invocations/6a38a782-c37c-4e5b-8d3e-8dc3c3d27657

**Comment by coryan** [comment]
https://source.cloud.google.com/results/invocations/f4cfe6de-a28e-4d6b-9fee-0a8b2c2be69b

**Comment by coryan** [comment]
Another one: https://source.cloud.google.com/results/invocations/e184ff64-eebd-4b66-a65d-e0ceac7ef6d4

**Comment by coryan** [comment]
Did not work: http://sponge2.corp.google.com/ccca9019-f55b-43a4-a357-b61fd7927bfe

**Comment by coryan** [comment]
My "fix" did not work, and I am out of ideas.  I created #6005 to troubleshoot things.  I am not convinced the problem is just out of sync clocks.  See this log:

https://source.cloud.google.com/results/invocations/b00c3ef3-c401-4bbd-b435-46325505636b

The log says the machine was already close to synchronized:

```
================================================================
2021-03-09T14:26:22Z: using sntp to synchronize clock from time.google.com. 
sntp 4.2.8p10@1.3728-o Tue Mar 21 14:36:42 UTC 2017 (136.200.1~4588)
kod_init_kod_db(): Cannot open KoD db file /var/db/ntp-kod: No such file or directory
2021-03-09 06:26:23.058912 (+0800) -0.000565 +/- 0.000544 time.google.com 216.239.35.4 s1 no-leap
```

But then curl fails to download a file:

```
================================================================
2021-03-09T14:26:23Z: getting roots.pem for gRPC. 
curl: (60) SSL certificate problem: certificate is not yet valid
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
HTTPS-proxy has similar options --proxy-cacert and --proxy-insecure.
```

I am out of ideas.

**Comment by coryan** [comment]
https://source.cloud.google.com/results/invocations/c8869bde-9b1c-45e8-9a76-7ac431897b61

**Comment by coryan** [comment]
https://source.cloud.google.com/results/invocations/8bf8da00-0965-4d5b-904a-a171593a87f8

**Comment by devbww** [comment]
https://source.cloud.google.com/results/invocations/e3cc25db-1920-4895-be8c-a3d7c87fa5f2

**Comment by devbww** [comment]
https://source.cloud.google.com/results/invocations/04c1cf43-6369-4806-a931-dd8f50f1290d

**Comment by coryan** [comment]
https://source.cloud.google.com/results/invocations/08c150f4-c315-4441-9e8f-5145682013e3

**Comment by devjgm** [comment]
https://fusion2.corp.google.com/invocations/3c3e77d5-85c7-4f0b-b926-18b32e0ebd31/targets/cloud-cpp%2Fgithub%2Fgoogle-cloud-cpp%2Fmaster%2Fmacos%2Fbazel/log

**Comment by coryan** [comment]
https://source.cloud.google.com/results/invocations/e218bc47-bfc6-4b75-84c2-9901d9336067

I cancelled that build after 42m, it was less than 1/2 through, and normally it takes less than 10m.

**Comment by coryan** [comment]
https://source.cloud.google.com/results/invocations/3ed500c1-adff-4765-9b51-d410b9dc83ac

**Comment by coryan** [comment]
I have not seen this error since we moved to the `catalina` pool for macOS build. Closing.
