### ISSUE TITLE
[Q] Consistency guarantees for reads in an uncommitted Spanner transaction

### ISSUE THREAD

**Issue by pfedor** [googleapis/google-cloud-cpp#5695]
Hello,

If I perform some reads using a transaction provided to the mutator given to spanner::Client::Commit(), will the results always reflect the state of the database from some timestamp, even if the transaction later fails to commit? For example,

1. Say that I do a lookup by key, and in the db there will always be at most one row for that key (say it's a primary key). Will the Read performed in an uncommitted transaction always see at most one row?

2. Say I have two columns in a table, and the application logic guarantees that for every existing row, exactly one of these columns will be NULL. Is it possible for an uncommitted transaction to see both of them NULL, or neither?

Thank you!

**Comment by devbww** [comment]
> If I perform some reads using a transaction provided to the mutator given to spanner::Client::Commit(), will the results always reflect the state of the database from some timestamp

Yes.  [http://cloud/spanner/docs/transactions](http://cloud/spanner/docs/transactions) says:

_A transaction in Cloud Spanner is a set of reads and writes that execute atomically at a single logical point in time across columns, rows, and tables in a database._

And that implies that the answers to your other questions are (1) yes, and (2) no.

Read further down that page, particularly to the [Isolation](https://cloud.google.com/spanner/docs/transactions#isolation) section for more information.

**Comment by pfedor** [comment]
Thank you very much.
