### ISSUE TITLE
Support option to set ssl_dir_path (aka CURLOPT_CAPATH)

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#5705]
This is motivated by #5703.

Similar to `CURLOPT_CAINFO`, but explicitly set the directory containing CA info:

https://curl.se/libcurl/c/CURLOPT_CAPATH.html
https://curl.se/libcurl/c/CURLOPT_CAINFO.html

**Comment by remyabel** [comment]
I think that `ssl_dir_path` is a vague name and reading `ssl_root_path` makes me think "root directory" instead of "root of trust" like the comment says. So `ssl_dir_path` would be especially confusing. WDYT about having the names be `ssl_capath` and `ssl_cainfo` respectively although the latter would be a breaking change?

**Comment by coryan** [comment]
A few comments:

* I agree, the names you propose are easier to understand.
* We are taking a harder stance around breaking changes.  Is there a way we could continue to support the old name and add the new one.  Marking (with a comment for now) the old one as deprecated and with a planned date for removal (maybe 12 months from the date it is deprecated).
* We do have some plans to provide an authentication library that would work for both gRPC and REST-based libraries.  It would introduce a new `foo::Credentials` type, and new attributes to control CAPATH, CAINFO and maybe other parameters.  It *might* be better to wait for that class.

**Comment by remyabel** [comment]
Revisiting this issue. Is the correct order of operations?

- Add an option similar to `CARootsFilePathOption` in `credentials.h` for `CURLOPT_CAPATH`
- Add the corresponding to `storage::ChannelOptions`
- Add the appropriate logic to `storage::MakeOptions` to use the new option

Potentially more work in other files for the new option?

**Comment by coryan** [comment]
The order looks correct, but let me add one step before that:

- Figure out how to support this option with gRPC, or if that is not possible, how to express that some options are protocol-specific.

My prior (but I may have missed something) is that it is not possible to support `CARootsFilePathOption` with gRPC.  A second reading of the [gRPC documentation], and maybe of the [gRPC core] functions would be in order.

Now, assuming there is no support in gRPC, then we have some choices to make:

-# Reimplement whatever OpenSSL does for these so we can support them with gRPC. That sound difficult, and maybe not a great idea.
-# Only support this for REST-based libraries (GCS is the only one today).  That would be sad, these are the "unified" credentials after all.
-# Maybe not support this at all. If there is no demand (or very little demand), then maybe the additional complexity is not justified.

Right now I am inclined to believe that the last option is the right one.  What do you think?

[gRPC documentation]: https://grpc.github.io/grpc/cpp/namespacegrpc.html
[gRPC core]: https://grpc.github.io/grpc/core/globals_func.html

**Comment by remyabel** [comment]
Less work sounds good.

**Comment by coryan** [comment]
Closing, we can reopen if somebody really needs this feature.
