### ISSUE TITLE
Integrate the client library with OpenCensus for C++

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#571]
All operations should be integrated with OpenCensus for C++.  This is probably blocked by abseil/abseil-cpp#111 because OpenCensus depends on Abseil.

**Comment by coryan** [comment]
I just created #957 and #958 to track this.

**Comment by coryan** [comment]
Oh, this bug is for the storage client.  I was thinking Bigtable.  For the storage client we need to do more development.  There is no gRPC API for GCS, so we are using libcurl.  I am sure it is still possible to integrate with OpenCensus via Bazel, but it would be more work.

Notice that in either case it would be hard to do a deeper integration in the library without CMake support.  We can build a demo that links (and uses) OpenCensus, but we cannot have the library create spans for a single logical operation that is retried multiple times (for example), because that wouldn't link when the client library is compiled with CMake, and we are not really looking forward to peppering the code with `#ifdefs`.

**Comment by devjgm** [comment]
FWIW, we have a dep on Abseil now, so that should no longer be a blocker.

**Comment by coryan** [comment]
This is now obsolete. OpenCensus for C++ does not seem to be under active development after the "merge" into OpenTelemetry.
