### ISSUE TITLE
Proposal: consistent names for libraries and targets in CMake

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#5726]
## Status

This has been implemented. We are waiting until 2022-02-15 to retire the legacy Bazel rules, CMake packages, and CMake rules.

## Background

The Bigtable client library is called `libbigtable_client.{a,so}`, the CMake target is called `bigtable_client`.  The storage library follows the same pattern.

These names are prone to conflicts. Any other application or library provider could create a `storage_client` target.

When it came time to write Spanner we created an alias `googleapis-c++::spanner_client`, which at least is less prone to conflicts, but it is too redundant: it is unlikely that our Java googleapis will have CMake targets.  PubSub also uses the `googleapis-c++::` prefix.

The common libraries (`libgoogle_cloud_cpp_common.{a,so}` and `libgoogle_cloud_cpp_grpc_utils.{a,so}`) do not have targets with the `googleapis-c++::` prefix.

The proto libraries are exported with the `googleapis-c++::` prefix.

## Proposal

* For CMake we will use a prefix (`google-cloud-cpp::`) consistently across **all** our exported libraries.
* For Bazel we will recommend that applications use `//:bigtable`, `//:pubsub`, etc. as the target they link.
* For CMake we will recommend `google-cloud-cpp::bigtable`, `google-cloud-cpp::storage`
* For CMake packages will be imported with:
  ```cmake
  find_package(google_cloud_cpp_bigtable)
  find_package(google_cloud_cpp_pubsub)
  find_package(google_cloud_cpp_storage)
  ```
* Though rarely used, proto libraries will be imported with:
  ```cmake
  find_package(google_cloud_cpp_googleapis)
  ```

### T: As Soon as Possible

* Export all libraries with the `google-cloud-cpp::` prefix
* Change all our examples and tests to use this prefix
* Add aliases for the old names (`storage_client`, `bigtable_client`, etc.)
* Declare these aliases as deprecated and announce that they will be removed ~in 2 * X months~ by a certain date.
* Include this bug as a reference
* We should explore using the `DEPRECATION` [property](https://cmake.org/cmake/help/latest/prop_tgt/DEPRECATION.html) to warn users.
* Change the Bazel in `google/cloud/*/BUILD` to use the `deprecation` directive and reference this bug (as well as the top-level targets), see #3701 
* Rename the physical libraries to `libgoogle_cloud_cpp_${name}.a` (or `.so`)
* Create backwards compatibility physical libraries.

### T + 6 months

* Change the CMake files to only export the backwards compatibility targets if a macro is set (e.g. `GOOGLE_CLOUD_CPP_DEFINE_LEGACY_TARGET_NAMES`)

### T + 12 months

* Remove the `GOOGLE_CLOUD_CPP_DEFINE_LEGACY_TARGET_NAMES` macro.
* Change the Bazel files to mark the targets in `google/cloud/*/BUILD` as private
* This decommissions the legacy targets.

### What do we do about physical library names?

Renaming the libraries, even when we create backwards compatibility targets, will break users that use `-l${lib}` options directly.  There is not much we can do for these users:

- There is no way to magically link an additional library, not when the libraries are static.
- There is no way to generate a warning / deprecation message, not when the libraries are static.

## Work Estimates

All estimates in "ideal hours", that is, uninterrupted work.

- [x] Create a test to verify the existing CMake targets remain usable (3h)
- [x] Create a test to verify the existing Bazel targets remain usable (3h)
- [x] Create a test to verify the existing CMake targets in `external/googleapis` remain usable (3h)
- [x] Mark all the existing Bazel targets as deprecated (1h)
- [x] Create new Bazel targets for `${library}_client_mocks` named `//:${library}_mocks` (3h)
- [x] Rename the googleapis CMake exported targets to use `google-cloud-cpp::` prefix (5h)
- [x] Rename the bigtable CMake exported targets to use `google-cloud-cpp::` prefix (5h)
- [x] Rename the pubsub CMake exported targets to use `google-cloud-cpp::` prefix (5h)
- [x] Rename the spanner CMake exported targets to use `google-cloud-cpp::` prefix (5h)
- [x] Rename the storage CMake exported targets to use `google-cloud-cpp::` prefix (5h)
- [x] Rename the iam CMake exported targets to use `google-cloud-cpp::` prefix (5h)
- [x] Rename the logging CMake exported targets to use `google-cloud-cpp::` prefix (5h)
- [x] Create new release (2h)
- [x] Push new release to vcpkg (1h)
- [x] Use new targets in quickstart programs (1h)

**Comment by devjgm** [comment]
Good idea. I like it. Thanks. Cleaning up and simplifying the build targets is a good idea, especially before we add NN new libraries from the generator. A few other thoughts to consider:

* https://github.com/googleapis/google-cloud-cpp/issues/3701 suggests cleaning up bazel targets by deprecating `//google/cloud:foo_client` in favor of `//:foo_client`. We may want to lump the build target deprecations/simplifications together. That is, only if we agree that we want to proceed with #3701 at all.
* While we're cleaning up build target names, we may want to consider bazel as well so that we end up with names that are mostly consistent even between build systems. I.e., whatever pattern we choose for cmake, we may want to follow the same pattern w/ bazel target naming. (note: this is independent of whether or not we do #3701)
* Regarding the spelling of the prefix, though a mouth full, it may be unsurprising for users if we pick the project name `google-cloud-cpp::` as the cmake prefix.
* To shorten the names of the library slightly, we could consider omitting "_client". For example, `google-cloud-cpp::lib${prefix}_{storage,spanner}.*`

**Comment by coryan** [comment]
Collecting some notes, I will update the description later:

* We also have `bigtable::client` and `storage::client` alialies.
* The bigtable protos appear as `bigtable_protos` in some places, and `googleapis-c++::bigtable_protos`.
* use `google-cloud-cpp::` instead of `googleapis-c++::`
* We need to think about the changes to `pkg-config`
* need to rename the files for `find_package(storage_client)` vs. `find_package(google_cloud_cpp_common)`
* we need to offer backwards compatibility `.pc` and `.cmake` files
* if we define aliases in the `${foo}-config.cmake` files we need to remember to protect them with `if(NOT TARGET ...)` otherwise the user cannot do `find_package(${foo})` multiple times.

* We need to decide if we would rename any `lib${bar}.a` to `libgoogle_cloud_cpp_${bar}.a`. For these we could:
  - Create a file with a undefined symbol called `lib${bar}_is_deprecated_use_libgoogle_cloud_cpp_${bar}_instead`
  - That way users saying `-l${bar}` explicitly (not through `pkg-config` or `CMake`) would get a link error.

* We need to add tests to verify these backwards compatibility files are properly installed.  A series of quickstart-like programs in the `ci/kokoro/install` builds might work.
* We should probably start with these tests.

**Comment by coryan** [comment]
@devjgm I have updated the description with the work I think we should do.  It includes renaming the physical libraries (which I think is necessary), and creating backwards compatibility libraries (which I am less certain of).

**Comment by coryan** [comment]
More notes:

* We need to decide if the Bazel targets stay `@...google_cloud_cpp//:${library}_client` or become `@...google_cloud_cpp//:${library}`
* Maintaining backwards compatibility *physical* libraries for the `googleapis-c++::${foo}_protos` (in `external/googleapis`) is a pain.

**Comment by ecourreges-orange** [comment]
FYI the [packaging doc](https://github.com/googleapis/google-cloud-cpp/blob/master/doc/packaging.md#using-google-cloud-cpp-in-cmake-based-projects) does not work as is on current master as you now have renamed the packages to `google_cloud_cpp_bigtable` etc. instead of `google_cloud_bigtable`

**Comment by coryan** [comment]
@ecourreges-orange thank you again for pointing out the problems in the documentation, as you probably noticed we merged a PR to fix the problem earlier today.  Let us know if you have any other problems.

**Comment by coryan** [comment]
This is done as of #8413
