### ISSUE TITLE
BQ: Generator needs integrate w/ hand-written code

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#5728]
In https://github.com/googleapis/google-cloud-cpp/issues/5727 we discuss needing to hand-write a "resumer" for BigQuery streaming reads, but want to use the microgenerator to generate the rest of the library. Therefore, the microgenerator needs a way to allow hand-written code for some parts.

We can collect more thoughts about this in this issue.

**Comment by scotthart** [comment]
Addressed in #5751 #5752 #5989
