### ISSUE TITLE
Implement "ConnectionOptions2"

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#5738]
(A quick late-Friday brain dump so we don't lose too much state.)

# Background

The current `ConnectionOptions` class is a template

https://github.com/googleapis/google-cloud-cpp/blob/a94d60293ec829a432bee142c4272b64aea40360/google/cloud/connection_options.h#L41-L43

Its template parameter is a traits type that defines three service customizable functions, for example

https://github.com/googleapis/google-cloud-cpp/blob/a94d60293ec829a432bee142c4272b64aea40360/google/cloud/pubsub/connection_options.h#L27-L36

# The issue

The problem that we're running into with the microgenerator is that no all services have a single `end_point`, some have multiple endpoints, for example, there may be separate end points for data and admin connections. For example, the Bigtable `ClientOptions` class:

https://github.com/googleapis/google-cloud-cpp/blob/a94d60293ec829a432bee142c4272b64aea40360/google/cloud/bigtable/client_options.h#L85-L92

@scotthart wrote a nice doc about this issue and outlined several options (internal only doc, sorry: go/cloud-cxx:connection-options2-choice)

# The solution

We discussed the options in Scott's doc above and as a team we decided on a solution that looks basically like this.

* We're going to create a _new_ "Connection Options" class. Until we settle on a final name, it should be named `internal::ConnectionOptions2`. This name is "internal", clearly not the final name, and it should be easy for us to find references to this name to rename later.
* `internal::ConnetionOptions2` will be a "bag of optionals" for all of its fields. That is, any option may be set, or not. The default state for all options will be unset (this matches optional's default). Note: Fields that have a native "unset" state do not need to be wrapped in an optional, for example, `std::shared_ptr<T>` could be unset with `nullptr`.
* Default values will be applied by the relevant "MakeConnection" function. For example, it would be the responsibility of `spanner::MakeConnection(..., internal::ConnectionOptions2)` to use the _default_ endpoint of `spanner.googleapis.com` if the relevant option is unset in the argument. **This is the point that fixes the issue above**. This way, the data connection and admin connections can use the same `internal::ConnectionOptions2` class, and yet they can apply their own defaults to  unset fields.
* What about the existing `ConnectionOptions` class? It will continue to exist for the current services that use it for backward compatibility. It will (probably) be re-implemented on top of the new `internal::ConnectionOptions2` class, but it will preserve its existing interface and semantics.
* _NEW_ client libraries -- including those we generate -- will use _only_ the new `internal::ConnectionOptions2` class.

# A class sketch -- OUTDATED: https://github.com/googleapis/google-cloud-cpp/issues/5738#issuecomment-776282956

Following the design of https://github.com/googleapis/google-cloud-cpp/blob/master/google/cloud/spanner/query_options.h, here's a sketch of what the new class may look like:

```cc
class internal::ConnectionOptions2 {
  std::shared_ptr<grpc::ChannelCredentials> credentials() const;
  ConnectionOptions2& set_credentials(std::shared_ptr<grpc::ChannelCredentials>);

  absl::optional<std::string> const& endpoint() const;
  ConnectionOptions2& set_endpoint(absl::optional<std::string>);

  absl::optional<int> const& num_channels() const;
  ConnectionOptions2& set_num_channels(absl::optional<int>);

  absl::optional<std::string> const& channel_pool_domain() const;
  ConnectionOptions2& set_channel_pool_domain(absl::optional<std::string>);

  absl::optional<std::string> const& user_agent_prefix() const;
  ConnectionOptions2& set_user_agent_prefix(absl::optional<std::string>);

  using BackgroundThreadsFactory = std::function<std::unique_ptr<BackgroundThreads>()>;
  BackgroundThreadsFactory background_threads_factory() const;
  ConnectionOptions2& set_background_threads_factory(BackgroundThreadsFactory) const;

  // [1]
  std::set<std::string> const& tracing_components() const;
  ConnectionOptions2& tracing_components(absl::optional<TracingOptions>);

  absl::optional<TracingOptions> tracing_options() const;
  ConnectionOptions2& set_tracing_options(absl::optional<TracingOptions>);
};
```

PLUS we may want a non-member helper function to create `grpc::ChannelArguments` from this options class to replicate the behavior of https://github.com/googleapis/google-cloud-cpp/blob/a94d60293ec829a432bee142c4272b64aea40360/google/cloud/connection_options.h#L183

[1]: Note that "tracing components" have richer semantics than a normal "bag of optionals" class normally has. In the existing class today, there are separate methods for `tracing_eabled`, `enable_tracing`, and `disable_tracing`. So, it may not be sufficient to just expose a `std::set` here. Some alternatives are to move the "tracing components" into the existing `TracingOptions` class. Or perhaps create a separate `TracingComponents` class.

UPDATE 2021-02-08: We could improve the readability of "tracking_enabled" at call sites with a non-member "contains" function like `if (internal::Contains(ops.tracing_components(), "rpc"))`

**Comment by devjgm** [comment]
Related to https://github.com/googleapis/google-cloud-cpp/pull/5612#pullrequestreview-550168323

**Comment by devjgm** [comment]
@coryan suggested an interesting idea about making the `Options` class more generic so that it could also work with the GCS library, which doesn't use gRPC and so the gRPC options don't make sense. Indeed, any given service may have some unique options. Carlos also proposed a cool API for this. I then took that an sketched up

https://github.com/googleapis/google-cloud-cpp/compare/master...devjgm:any-options?expand=1

**Comment by devjgm** [comment]
I'm liking the class sketch at https://github.com/googleapis/google-cloud-cpp/compare/master...devjgm:any-options?expand=1. The main parts of the interface look like:

# New Sketch

```cc
class Options {
 public:
  /// Constructs an empty instance.
  Options() = default;

  Options(Options const&) = default;
  Options& operator=(Options const&) = default;
  Options(Options&&) = default;
  Options& operator=(Options&&) = default;

  /// Returns true iff no options are currently set.
  bool empty() const { ... }

  /// Sets the specified option and returns a reference to `*this`.
  template <typename T>
  Options& set(T&& t) {
    ...
  }

  /// Erases the option specified by the type `T`.
  template <typename T>
  void unset() {
    ...
  }

  /// Gets option specified by its type `T` if it was set.
  template <typename T>
  absl::optional<T> get() const {
    ...
  }

  /// Returns the option of type `T` if set, else @p default_value.
  template <typename T>
  T get_or(T&& default_value) const {
    ...
  }

 private:
  ...
};
```
## Example usage:
```cc
// Given
struct EndpointOption {
  std::string value;
};
struct FooOption {
  int value;
};
...
auto opts = Options{}.set(EndpointOption{"blah.googleapis.com"})
                     .set(FooOption{42});
absl::optional<FooOption> foo = opts.get<FooOption>();
assert(foo.has_value());
assert(foo->value == 42);
```

# Some observations about this

1. It solves the biggest problem mention in the OP -- naming! `ConnectionOptions` was unavailable, but `Options` is available :smile:
2. It's simple and flexible.
3. The "options" structs that can be get/get have flexibility. They can be plain-ol' structs as in the example here, or they could be more sophisticated classes that might even have some logic to, say, read a default value from the environment. That would all work with this `Options` class.
4. I **do not** like that this supports copy-assignment *but not* `operator==`. This makes the type irregular and more difficult to reason about (e.g., what's the post condition of `Options a; Options b = a;` if we can't say they're equal). However, I see no way around this since `std::any` forced this problem on us. Ahh well. It's probably fine.

# Open questions

1. What methods should this class have? I originally include a `size()` member, but @devbww pointed out that such a method is likely not useful (one can't iterate the options), and I agreed and removed that method. He also indicated that `empty()` may also be superfluous, which may be true, but that one seems somewhat more fundamental to me, so I left it. However, maybe I'm wrong and that should be removed too. What else? Are there other options methods that we need (we could probably add them later, though)?
2. What should the methods be named? @coryan likes more fluent-builder style names, like `Options{}.with(IntOption{42}).with(...)`, rather than the traditional verb names like `set` as I've used here. @devjgm prefers the latter, because I think of this as a pretty traditional setter/getters style class, and the ability to fluently chain the setters is simply a convenience. If it were a classic "builder" object without the need for getters (what's the "getter" counterpart to `.with()`?), and whose sole purpose was to be used in a fluent chain, then `.with()` may sound more appealing to me. But I could certainly be convinced otherwise.
3. Do the "Option" structs/classes need to expose their own default value? I think the answer is **no** they do not need to. It is not a goal that we need expose the default values for any settings programmatically to users. Is it OK if some particular option does expose its default value programatically to users? Sure, but that becomes part of the public API and so it should be considered whether it's desirable.

**Comment by coryan** [comment]
> It solves the biggest problem mention in the OP -- naming! ConnectionOptions was unavailable, but Options is available 😄

So true.

nit: you probably already thought of this, but I think it should be:

```cc
template <typename U>
absl::optional<T> get_or(U&& u)
```

another nit: https://google.github.io/styleguide/cppguide.html#Run-Time_Type_Information__RTTI_

I assume this use is Okay, but you would know better.

**Comment by devjgm** [comment]
> `template <typename U>`
> `absl::optional<T> get_or(U&& u)`

Unless I'm misunderstanding, I think you mean that to return T (not `optional<T>`), like:
```cc
  template <typename T, typename U>
  T get_or(U&& default_value) const
```
and the `default_value` param of type `U` would be used as an argument to construct the returned `T` if we we need to use the default. I hadn't considered that, though it's a good idea. 

The one potential downside is that this would be the first and only place in this code where the `Options` class places any requirement on the `T` option structs. The requirement placed here is that `T` is constructible from a *single* argument of type `U`. This may not be a big deal, and we could work around it by making `get_or` a variadic function template. But I think this new requirement would be something to consider, but this is probably still a good idea.

> another nit: https://google.github.io/styleguide/cppguide.html#Run-Time_Type_Information__RTTI_
> I assume this use is Okay, but you would know better.

I also think this is okay. The caution around rtti is to avoid re-implementing virtual functions with if-else statements. I think what we're doing here with a type map is kinda exactly what `typeid` is intended for, and anything else we did would basically be re-implementing `typeid`.

**Comment by coryan** [comment]
> > `template <typename U>`
> > `absl::optional<T> get_or(U&& u)`
> 
> Unless I'm misunderstanding, I think you mean that to return T (not `optional<T>`), like:
> 
> ```c++
>   template <typename T, typename U>
>   T get_or(U&& default_value) const
> ```
> 

Yup.

> The one potential downside is that this would be the first and only place in this code where the `Options` class places any requirement on the `T` option structs. 

True enough, fwiw, I stole this idea from `std::optional<>` (you probably knew that too).


> The requirement placed here is that `T` is constructible from a _single_ argument of type `U`. This may not be a big deal, and we could work around it by making `get_or` a variadic function template. But I think this new requirement would be something to consider, but this is probably still a good idea.

Yes.  I guess the caller use `U==T` if there is no good single-argument constructor, e.g.:

```cc
void F(Options o) {
  auto p = o.value_or<std::pair<int, std::string>>(std::make_pair(42, "good answer"));
}
```

If the variadic arg thing is a pain to implement, then this option might work.

> 
> > another nit: https://google.github.io/styleguide/cppguide.html#Run-Time_Type_Information__RTTI_
> > I assume this use is Okay, but you would know better.
> 
> I also think this is okay. The caution around rtti is to avoid re-implementing virtual functions with if-else statements. I think what we're doing here with a type map is kinda exactly what `typeid` is intended for, and anything else we did would basically be re-implementing `typeid`.

**Comment by devjgm** [comment]
I updated https://github.com/googleapis/google-cloud-cpp/compare/master...devjgm:any-options?expand=1 to use this pattern, with variadic function templates, so we no longer care about how many args `T` must be constructed with.

I like this approach. One nice thing is that it makes all of the functions, including set, look more similar. For example, they all now take the option type as an explicit function template parameter, and the optional arguments to the function are forwarded to the `T`'s constructor. 

For example, we now have

```cc
Options opts;
opts.set<FooOption>(123);  // instead of opts.set(FooOption{123}), which now matches
opts.get<FooOption>();     // and...
opts.get_or<FooOption>(123);
```

**Comment by devjgm** [comment]
# Next Steps

- [ ] Send a PR with the new `Options` class (https://github.com/googleapis/google-cloud-cpp/compare/master...devjgm:any-options?expand=1)
- [ ] Create "Options" structs that correspond to all the current options (i.e., member functions) in [connection_options.h](https://github.com/googleapis/google-cloud-cpp/blob/master/google/cloud/connection_options.h). We probably want to separate the grpc-specific options from those that are more general. This way, GCS could re-use some of these options.
- [ ] Re-implement [`google::cloud::ConnectionOptions`](https://github.com/googleapis/google-cloud-cpp/blob/master/google/cloud/connection_options.h) in terms of the new `Options` class. 
- [ ] Teach the microgenerator to generate code using the new `Options` class.
- [ ] Add overloads for existing `MakeConnection` (et al) functions that take the new `Options` class.

**Comment by devjgm** [comment]
# Strict options checking
## The problem

There was some concern and discussion on the team about the dynamic `Options` class described above allowing users to accidentally create configurations that are ignored by some functions and thus the code may not do what the user intended. We don't think this will be common, but when it does happen, what tools can we provide the user to help them debug the problem more quickly? We discussed possible solutions in an internal-only doc (sorry) https://docs.google.com/document/d/15bG_kO1zbaDlYyqXXY5j91YxQJ8m61MnddgHt4MzXKs/edit?ts=6026da04&resourcekey=0-q7e_r4HRKIcnUDHXboa--w#

```cc
auto opts = Options{}.set<GrpcCredentialOption>(cred);  // OOPS: Wrong type of credential; GCS would use oauth
auto gcs = storage::Client(opts);
```
## The solution
The solution we decided to go withis one we called **Strict Options Checking**, which is **off by default**, but the user can enable with an option. This solution would allow users who are debugging a problem to temporarily enable extra debug logging of the `Options` class that will cause it to _log_ output when certain functions use `Options`, and whether or not the `Options` contained settings that _were not_ used.  For example:

```cc
auto opts = Options{}
                .set<GrpcCredentialOption>(cred)  // OOPS: Wrong type of credential; GCS would use oauth
                .set<OptionsDebugLogging>(true);  // <-- User enables this to help diagnose the problem    
auto gcs = storage::Client(opts);  // Emits runtime log message that 
                                   // GrpcCredentialOption was not used.
```

## The implementation

The implementation would consist of a public user-visible option that users could set on any `Options` instance indicating that they want some extra debug logging enabled. There would also be a _private_ function that _we_ call from within our factory functions (or wherever) that consume user-provided `Options`. This function would log which options were _expected_ and which options were set **but unexpected**. A sketch would be something like:

```cc
// google/cloud/options.h
namespace google::cloud {

// The setting that users may optionally set to enable/disable debug logging of options
struct OptionsDebugLogging {
  bool value;
};

namespace internal {
// A variadic function template that will log all the *unexpected* (and probably expected, because why not?)
// settings that appeared in the provided `opts` argument. `caller` is just the calling `func` that may be useful to include
// in the logged output.
template <typename... Expected>
void MaybeDebugLog(Options opts, char const* caller, Expected&&... expected);
}  // namespace internal
}  // namespace google::cloud
```

**Comment by devjgm** [comment]
Note: In the "Strict Options Checking" comment above https://github.com/googleapis/google-cloud-cpp/issues/5738#issuecomment-779897018, the logged typename may not be very pretty. It'll most likely be the C++ type's mangled name, which could look something like `N6google5cloud2v18EndpointOptionE` (I copied some other mangled name and made it look like an option, so this is not valid mangling). That is the logged output _might_ look something like:

```console
Unexpected option (mangled name): N6google5cloud2v18EndpointOptionE
```

This is not great. But it would likely still give the user a hint about what might be wrong.

**Alternatives**

* We could reach into Abseil's internals and call https://github.com/abseil/abseil-cpp/blob/master/absl/debugging/internal/demangle.h. I don't like this option.
* We could use macros more to allow us to capture the stringified option name that the user actually types, then save that off somewhere. That would likely change the core of the `Options` API, because `opts.set<FooOption>(123)` doesn't leave space for a macro. I don't really like this option either.
* We could write our own minimal demangler. I don't know what's really involved here, but it seems like a pretty bad idea :-)
* We could use `abi::__cxa_demangle`, but that doesn't seem like a portable option.

Since our goal is just to help users debug, I think logging the mangled name is probably fine. Maybe we could also include instructions about running it through `c++filt` to demangle it.

**Comment by devjgm** [comment]
# Option discoverability

Q: One of the final remaining questions about this API is how can we improve discoverability so users can easily find and use the options that are available?

Some thoughts

* We should minimize the number of places where users can find options. Specifically, we should have the top-level `common_options.h` and `grpc_options.h` files, and perhaps those are the only top-level options files. And the only reason those are even two (instead of one) files is to avoid the need for a gRPC dep. So I imagine any future top-level options could go into one of those two files.
* **IF** we needed to add another top-level options file, it would be fine, but we should strive to keep this to a minimum.
* Each product should have *one* product-level `product/options.h` file that defines *all* of the user-facing options for that product. Again, this gives users a small number of places to look for available options.
* If a product has multiple logically distinct services, it would be fine to have separate `<product>/<service>_options.h` files if that makes sense for the product. Again, the principle is just minimizing these files so they are easy for users to discover.
* Each "*options.h" file can have logically distinct groups of options. For example, `spanner/options.h` may have a group of "SpannerPolicyOptions" and a separate group of "SessionPoolOptions". This allows functions to more precisely specify the options that it excepts. For example, `spanner::MakeConnection()` may indicate that it accepts `CommonOptionList`, `GrpcOptionList`, `SpannerPolicyOptionList`, and `SessionPoolOptionList`. Whereas `spanner::MakeAdminConnection` would not list the session-pool options.

Is this enough? I think it might be. However, there are a few more things we _could_ do if we think they'd be good for customers.

1. @coryan suggested putting all structs in an `options` namespace. This would let users' IDEs discover and autocomplete options. I like this idea, but I wonder if a single "options" namespace is too broad...
2. A variant of @coryan 's idea is to put all options in a `struct` that's named for the group. For example all the gRPC options (in `grpc_options.h`) would be listed in `struct GrpcOptions`. Within that scope, they would be able to have a shorter name. So for example, what is currently `GrpcCredentialOption` would become `GrpcOptions::Credential`. This would also help users' IDEs to discover and autocomplete options. Why a `struct` and not a namespace? Because doing this in a `struct` will make it easier for `CheckExpectedOptions` to discover the correct `OptionList` for each group, because it could be listed as a member of the struct, and the _struct_ itself would be the template argument passed to `CheckExpectedOptions`. Similarly, we'd have `CommonOptions::Endpoint` (et al.), and `SpannerOptions::RetryPolicy` (et al.), and `SessionPool::MinSessions` (et al.), etc.

Any comments/opinions? 

I'd be OK leaving things as they are. I'd also be OK doing (2) above, which wouldn't be difficult.

**Comment by coryan** [comment]
I vote we leave it as-is and change it later if we find it is an actual problem.

**Comment by devjgm** [comment]
`Options` now exists and is public: https://github.com/googleapis/google-cloud-cpp/blob/master/google/cloud/options.h

All the spanner code was changed to use `Options` internally instead of `ConnectionOptions`. See

https://github.com/googleapis/google-cloud-cpp/blob/82538c2b4cfb813fb8a8583abf376fce377c733e/google/cloud/spanner/client.h#L666-L667

Now, @scotthart will change the Generator to use `Options`. But this particular issue is closed.
