### ISSUE TITLE
bigtable: connection pool sample

### ISSUE THREAD

**Issue by billyjacobson** [googleapis/google-cloud-cpp#5758]
Can we add a sample showing how to set the number of connection pools for Bigtable. Here is an example in Java https://github.com/googleapis/java-bigtable/pull/601

**Comment by coryan** [comment]
nit: "number of connection pools" implies setting up multiple pools, which we can do in the C++ client.  I think you meant "size of the connection pool" which is the number of connections in a given pool.

**Comment by billyjacobson** [comment]
> nit: "number of connection pools" implies setting up multiple pools, which we can do in the C++ client. I think you meant "size of the connection pool" which is the number of connections in a given pool.

Yes, thanks for the catch and clarification
