### ISSUE TITLE
Build error with clang-12

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#5762]
The following code does not compile with Clang-12 (I am using macOS, but I think the problem is more general):

https://github.com/googleapis/google-cloud-cpp/blob/4eb5b7c257b549483730f7e8dadb8ee8583134e2/google/cloud/spanner/value.h#L423

The problem is when `T == bool`, and the iteration does not return references.

**Comment by coryan** [comment]
I will try to send a PR later today.  We also need to create a build with Clang-12.

**Comment by coryan** [comment]
Also in one of the tests, I captured the error message this time:

```
/Users/coryan/cbt-develop/google/cloud/spanner/integration_tests/data_types_integration_test.cc:49:20: error: loop variable 'x' is always a copy because the range of type 'const std::__1::vector<bool, std::__1::allocator<bool> >' does not return a reference [-Werror,-Wrange-loop-analysis]
  for (auto const& x : data) {
                   ^
/Users/coryan/cbt-develop/google/cloud/spanner/integration_tests/data_types_integration_test.cc:94:17: note: in instantiation of function template specialization 'google::cloud::spanner::v1::(anonymous namespace)::WriteReadData<std::__1::vector<bool, std::__1::allocator<bool> > >' requested here
  auto result = WriteReadData(*client_, data, "BoolValue");
                ^
/Users/coryan/cbt-develop/google/cloud/spanner/integration_tests/data_types_integration_test.cc:49:8: note: use non-reference type 'std::__1::__bit_const_reference<std::__1::vector<bool, std::__1::allocator<bool> > >'
  for (auto const& x : data) {
       ^~~~~~~~~~~~~~~
1 error generated.
```

**Comment by devjgm** [comment]
This warning is incorrectly issued by clang with `-Wrange-loop-analysis` as described in https://reviews.llvm.org/D73007. I'm not sure which version of clang includes the fix. But I believe our code is actually correct as written. 

We may still want to workaround the false warnings from our `.h` files, which customers may include. However, we may not need to jump through too many hoops to fix our `_test.cc` files if we could instead test w/ a version of clang that has this bug fixed.

**Comment by coryan** [comment]
Whether it is a bug in the compiler or not, it stops the build from working on macOS with the latest xcode. At least it breaks when I upgraded my laptop.  In any case, the fix is not that complicated, there is a PR attached.
