### ISSUE TITLE
[Flake] Possible race condition in pubsub unit test

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#5774]
This smells like a race condition in the test, not the code:

https://source.cloud.google.com/results/invocations/21e0e87d-39dd-47d1-bfb4-7e7915597b23

```
[ RUN      ] BatchingPublisherConnectionTest.BatchByMessageSizeOversizedSingleton
/Volumes/BuildData/tmpfs/src/github/google-cloud-cpp/google/cloud/pubsub/internal/batching_publisher_connection_test.cc:295: Failure
Expected equality of these values:
  3
  request.messages_size()
    Which is: 1
[libprotobuf FATAL /Volumes/BuildData/tmpfs/src/github/google-cloud-cpp/cmake-out/macos/external/include/google/protobuf/repeated_field.h:1706] CHECK failed: (index) < (current_size_): 
/Volumes/BuildData/tmpfs/src/github/google-cloud-cpp/google/cloud/pubsub/internal/batching_publisher_connection_test.cc:292: Failure
Actual function call count doesn't match EXPECT_CALL(*mock, AsyncPublish)...
         Expected: to be called 3 times
           Actual: called once - unsatisfied and active
unknown file: Failure
C++ exception with description "The associated promise has been destructed prior to the associated state becoming ready." thrown in the test body.
[  FAILED  ] BatchingPublisherConnectionTest.BatchByMessageSizeOversizedSingleton (29 ms)
```

**Comment by devjgm** [comment]
While attempting to reproduce this error on *linux* with *bazel*, I saw the following flake, which looks quite similar, though it's from a different test:

```
[ RUN      ] BatchingPublisherConnectionTest.BatchByFlush
google/cloud/pubsub/internal/batching_publisher_connection_test.cc:472: Failure
Expected equality of these values:
  2
  request.messages_size()
    Which is: 1
[libprotobuf FATAL external/com_google_protobuf/src/google/protobuf/repeated_field.h:1706] CHECK failed: (index) < (current_size_):
google/cloud/pubsub/internal/batching_publisher_connection_test.cc:508: Failure
Expected equality of these values:
  "test-message-id-" + std::to_string(i)
    Which is: "test-message-id-1"
  *r
    Which is: "ack-for-test-data-1"
-- Test timed out at 2021-02-01 18:29:56 UTC --
```

**Comment by devjgm** [comment]
Another one on macOS: https://source.cloud.google.com/results/invocations/e7679fd1-111f-4fe3-a772-2a98332929dc/targets/cloud-cpp%2Fgithub%2Fgoogle-cloud-cpp%2Fmaster%2Fmacos%2Fcmake-super-presubmit/log

But note that this is exactly the same error that I was able to repro on Linux in the comment above, so it's not a macos-specific issue.

**Comment by devbww** [comment]
No recurrence for 90 days.  Closing.

**Comment by dbolduc** [comment]
https://source.cloud.google.com/results/invocations/ef104243-168d-4f79-95e4-a4ffef910f47/targets/

> [ RUN      ] BatchingPublisherConnectionTest.BatchByMessageSizeOversizedSingleton
../../../../google/cloud/pubsub/internal/batching_publisher_connection_test.cc:295: Failure
Expected equality of these values:
  3
  request.messages_size()
    Which is: 1
[libprotobuf FATAL ../../external/include/google/protobuf/repeated_field.h:1706] CHECK failed: (index) < (current_size_):
../../../../google/cloud/pubsub/internal/batching_publisher_connection_test.cc:303: Failure
Expected equality of these values:
  1
  request.messages_size()
    Which is: 2
../../../../google/cloud/pubsub/internal/batching_publisher_connection_test.cc:304: Failure
Expected equality of these values:
  oversized_payload
    Which is: "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
  request.messages(0).data()
    Which is: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
../../../../google/cloud/pubsub/internal/batching_publisher_connection_test.cc:309: Failure
Expected equality of these values:
  3
  request.messages_size()
    Which is: 1
../../../../google/cloud/pubsub/internal/batching_publisher_connection_test.cc:310: Failure
Expected equality of these values:
  single_payload
    Which is: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
  request.messages(0).data()
    Which is: "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
[libprotobuf FATAL ../../external/include/google/protobuf/repeated_field.h:1706] CHECK failed: (index) < (current_size_):
unknown file: Failure
C++ exception with description "CHECK failed: (index) < (current_size_): " thrown in the test body.

**Comment by coryan** [comment]
https://source.cloud.google.com/results/invocations/01eb13d7-345e-4406-b044-448abf79b0a3
