### ISSUE TITLE
Consider: creating a vcpkg.json manifest file

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#5803]
vcpkg has a feature (experimental?) where a project can list their dependencies in a top-level JSON "manifest" file. It's described here: https://github.com/microsoft/vcpkg/blob/master/docs/specifications/manifests.md

The idea is that this may be an easier way for customers to compile the (our) code as well as installing all the needed dependencies (via vcpkg). 

We may want to include a top-level `vcpkg.json` file. We should also have a CI build that tests using it. Indeed, we may want ALL of our vcpkg-based CI builds to use this.

**Comment by devjgm** [comment]
@coryan and I chatted about this for a while. Here are some notes from our discussion.

* We could rely more heavily on `vcpkg` to fetch/compile our dependencies. **This will be primarily beneficial for us, as project developers.** 
* Using `vcpkg` to fetch our deps when compiling our code from source likely would NOT benefit our customers.
* Using `vcpkg` could replace our need to have and test a "super build". Though, we'd likely keep but deprecated our super build for a while, perhaps removing it only after 12-months or so.
* We should likely enable vcpkg binary caching first. See https://github.com/googleapis/google-cloud-cpp/issues/5356

Some steps that might make sense:

1. Switch our "quickstart-cmake" builds, which already use `vcpkg`, to use binary caching.
2. Switch the "quickstart-cmake" builds to using a `vcpkg.json` manifest.
3. Once we do the above two things, we'll understand more about binary caching and vcpkg, and by this point, we should be able to create a top-level `vcpkg.json` manifest.

**Comment by devjgm** [comment]
Hmm.. Since vcpkg seems to always install both dbg and release builds of a library, that's going to be 2x slower than choosing one. Something to consider since `vcpkg install google-cloud-cpp` will take a long time.

**Comment by coryan** [comment]
Apparently there are ways to avoid that, but they all seem complicated:

https://github.com/microsoft/vcpkg/issues/13513

**Comment by coryan** [comment]
This was done in #6191.
