### ISSUE TITLE
generator: modify generator to run emitted code through clang-format

### ISSUE THREAD

**Issue by scotthart** [googleapis/google-cloud-cpp#5821]
Currently the generated code does is not run through clang-format, nor are the existing golden files. Modify the existing integration test to compare the emitted code to golden code after applying clang-format to both.

**Comment by scotthart** [comment]
Currently running clang-format over emitted code is an additional step in the build process. Determine, and implement if possible, a mechanism to plumb the emitted code through clang-format as part of code generation.

**Comment by coryan** [comment]
We are happy with how it works today.
