### ISSUE TITLE
[Flake] macOS + Bazel builds cannot download toolchain artifacts

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#5836]
Happened twice today:

https://source.cloud.google.com/results/invocations/6fd9e0f1-76a8-48cf-8281-7d94ab4dab1e
https://source.cloud.google.com/results/invocations/da7a15c5-425e-4c19-9bbe-8c011b604c5e

Both with:

```
INFO: Repository go_sdk instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule _go_download_sdk defined at:
  /Volumes/BuildData/tmpfs/tmp/bazel/external/io_bazel_rules_go/go/private/sdk.bzl:53:35: in <toplevel>
WARNING: Download from https://dl.google.com/go/go1.12.5.darwin-amd64.tar.gz failed: class java.io.IOException Read timed out
ERROR: An error occurred during the fetch of repository 'go_sdk':
   Traceback (most recent call last):
	File "/Volumes/BuildData/tmpfs/tmp/bazel/external/io_bazel_rules_go/go/private/sdk.bzl", line 51, column 16, in _go_download_sdk_impl
		_remote_sdk(ctx, [url.format(filename) for url in ctx.attr.urls], ctx.attr.strip_prefix, sha256)
	File "/Volumes/BuildData/tmpfs/tmp/bazel/external/io_bazel_rules_go/go/private/sdk.bzl", line 121, column 21, in _remote_sdk
		ctx.download(
Error in download: java.io.IOException: Error downloading [https://dl.google.com/go/go1.12.5.darwin-amd64.tar.gz] to /Volumes/BuildData/tmpfs/tmp/bazel/external/go_sdk/go_sdk.tar.gz: Read timed out
WARNING: errors encountered while analyzing target '//google/cloud/bigtable:metadata_update_policy_test': it will not be built
```

This is after we make 3 attempts to download these artifacts.  The artifact is reachable from my laptop.

**Comment by coryan** [comment]
https://source.cloud.google.com/results/invocations/f3bf7ced-4f02-4148-b606-3ce71a2798c4

**Comment by coryan** [comment]
https://source.cloud.google.com/results/invocations/7bc579fb-3fd9-4ee6-a932-f4c364e84428

**Comment by coryan** [comment]
Over 90d without repeats, closing.

**Comment by devbww** [comment]
http://sponge2.corp.google.com/456797d5-1a2e-4862-ba4e-4e1b55605aea
https://source.cloud.google.com/results/invocations/456797d5-1a2e-4862-ba4e-4e1b55605aea

**Comment by coryan** [comment]
For the golang SDK, there are ways to mitigate this:

- Download the golang SDK (with retry) and then set an environment variable to stop Bazel from downloading.
- We could work with the gRPC team to avoid this dep for their downstream dependencies
- We could patch the BUILD/WORKSPACE files.

**Comment by coryan** [comment]
Has not repeated in 90d. Closing.
