### ISSUE TITLE
Consider requiring CMake >= 3.15 with MSVC

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#5852]
Until CMake 3.15 there was no reliable way to switch the MSVC runtime library:

https://cmake.org/cmake/help/latest/variable/CMAKE_MSVC_RUNTIME_LIBRARY.html

We have a hack in place:

https://github.com/googleapis/google-cloud-cpp/blob/467e97b4a3e07eb1ae9e28f16c64c45721c37de8/cmake/SelectMSVCRuntime.cmake#L30-L39

I think we should remove it and require customers to use a newer CMake with MSVC. Installing a new version is easy, assuming their own code does not require an older version. In theory, newer CMake versions should work fine with older CMake scripts: the CMake policy mechanism is supposed to help.

**Comment by devjgm** [comment]
A newer cmake SGTM
