### ISSUE TITLE
Bazel build for pub/sub quickstart fails on Windows

### ISSUE THREAD

**Issue by rastogi-ayush** [googleapis/google-cloud-cpp#5865]
Hello,
I am trying to build cloud pub/sub c++ client libraries on Windows to try out some POCs of integrating Google Cloud with 3rd party enterprise systems for internal use.
I have not been able to build these libraries and I get the following error,

`C:\google-cloud-cpp-master\google\cloud\pubsub\quickstart>bazel build ... --verbose_failuresINFO: Analyzed target //:quickstart (0 packages loaded, 0 targets configured).INFO: Found 1 target...ERROR: C:/users/znext_admin/_bazel_znext_admin/cmd3toj5/external/com_github_googleapis_google_cloud_cpp/google/cloud/pubsub/BUILD:21:11: Compiling google/cloud/pubsub/internal/batching_publisher_connection.cc failed: (Exit 1): cl.exe failed: error executing command cd C:/users/znext_admin/_bazel_znext_admin/cmd3toj5/execroot/google_cloud_cpp_pubsub_quickstart SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\ATLMFC\include;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\include;C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt SET PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\\Extensions\Microsoft\IntelliCode\CLI;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\\x64;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\;C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\\MSBuild\Current\Bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\;;C:\Windows\system32;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja SET PWD=/proc/self/cwd SET RUNFILES_MANIFEST_ONLY=1 SET TEMP=C:\Users\ZNEXT_~1\AppData\Local\Temp\2 SET TMP=C:\Users\ZNEXT_~1\AppData\Local\Temp\2 C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/HostX64/x64/cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /bigobj /Zm500 /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /Iexternal/com_github_googleapis_google_cloud_cpp /Ibazel-out/x64_windows-fastbuild/bin/external/com_github_googleapis_google_cloud_cpp /Iexternal/com_google_absl /Ibazel-out/x64_windows-fastbuild/bin/external/com_google_absl /Iexternal/com_github_grpc_grpc /Ibazel-out/x64_windows-fastbuild/bin/external/com_github_grpc_grpc /Iexternal/zlib /Ibazel-out/x64_windows-fastbuild/bin/external/zlib /Iexternal/upb /Ibazel-out/x64_windows-fastbuild/bin/external/upb /Iexternal/com_github_cares_cares /Ibazel-out/x64_windows-fastbuild/bin/external/com_github_cares_cares /Iexternal/boringssl /Ibazel-out/x64_windows-fastbuild/bin/external/boringssl /Iexternal/com_google_protobuf /Ibazel-out/x64_windows-fastbuild/bin/external/com_google_protobuf /Iexternal/com_google_googleapis /Ibazel-out/x64_windows-fastbuild/bin/external/com_google_googleapis /Ibazel-out/x64_windows-fastbuild/bin/external/com_google_protobuf/_virtual_includes/any_proto /Ibazel-out/x64_windows-fastbuild/bin/external/com_google_protobuf/_virtual_includes/descriptor_proto /Ibazel-out/x64_windows-fastbuild/bin/external/com_google_protobuf/_virtual_includes/duration_proto /Ibazel-out/x64_windows-fastbuild/bin/external/com_google_protobuf/_virtual_includes/empty_proto /Ibazel-out/x64_windows-fastbuild/bin/external/com_google_protobuf/_virtual_includes/field_mask_proto /Ibazel-out/x64_windows-fastbuild/bin/external/com_google_protobuf/_virtual_includes/timestamp_proto /Iexternal/com_github_grpc_grpc/include /Ibazel-out/x64_windows-fastbuild/bin/external/com_github_grpc_grpc/include /Iexternal/com_github_grpc_grpc/src/core/ext/upb-generated /Ibazel-out/x64_windows-fastbuild/bin/external/com_github_grpc_grpc/src/core/ext/upb-generated /Iexternal/zlib /Ibazel-out/x64_windows-fastbuild/bin/external/zlib /Iexternal/com_github_cares_cares /Ibazel-out/x64_windows-fastbuild/bin/external/com_github_cares_cares /Iexternal/com_github_grpc_grpc/third_party/address_sorting/include /Ibazel-out/x64_windows-fastbuild/bin/external/com_github_grpc_grpc/third_party/address_sorting/include /Iexternal/boringssl/src/include /Ibazel-out/x64_windows-fastbuild/bin/external/boringssl/src/include /Iexternal/com_google_protobuf/src /Ibazel-out/x64_windows-fastbuild/bin/external/com_google_protobuf/src /Iexternal/com_google_googleapis /Ibazel-out/x64_windows-fastbuild/bin/external/com_google_googleapis /DCARES_STATICLIB /D__CLANG_SUPPORT_DYN_ANNOTATION__ /showIncludes /MD /Od /Z7 /wd4117 -D__DATE__="redacted" -D__TIMESTAMP__="redacted" -D__TIME__="redacted" /Fobazel-out/x64_windows-fastbuild/bin/external/com_github_googleapis_google_cloud_cpp/google/cloud/pubsub/_objs/google_cloud_cpp_pubsub/batching_publisher_connection.obj /c external/com_github_googleapis_google_cloud_cpp/google/cloud/pubsub/internal/batching_publisher_connection.ccExecution platform: @local_config_platform//:hostC:\users\znext_admin\_bazel_znext_admin\cmd3toj5\execroot\google_cloud_cpp_pubsub_quickstart\external\com_github_googleapis_google_cloud_cpp\google\cloud\pubsub\internal\batching_publisher_connection.cc : fatal error C1083: Cannot open compiler generated file: '': Invalid argumentTarget //:quickstart failed to buildINFO: Elapsed time: 7.103s, Critical Path: 6.54sINFO: 9 processes: 9 internal.FAILED: Build did NOT complete successfully`

I suspect that it is a file size issue on Windows.If there is a workaround or fix for this issue please let me know.
Thanks,Ayush

**What component of `google-cloud-cpp` is this related to?**
pub/sub c++ client libraries on windows

**To Reproduce**
Please follow the steps described on this page on a windows machine
https://github.com/googleapis/google-cloud-cpp/tree/master/google/cloud/pubsub/quickstart 

**Expected behavior**
Clean build 

**Operating system:**
Microsoft Hyper v server 2016

**Comment by coryan** [comment]
Thank you for the detailed but report. 

> I suspect that it is a file size issue on Windows.

If you mean the filenames may be too long, then I agree.  We compile with: `bazel --output_user_root=C:\b build ...` to workaround these limitations.

**Comment by rastogi-ayush** [comment]
Thanks @coryan for your help. 👍 

I can build run this the tutorial with after using the `--output_user_root` flag.

I will suggest to have this flag documented perhaps in the Windows build section to help other who might into the same.
