### ISSUE TITLE
macOS build-hazel.sh should not try to install bazel again

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#5878]
I'm following the instructions at https://github.com/googleapis/google-cloud-cpp/blob/master/doc/contributor/howto-guide-setup-development-workstation.md#macos on a fresh macOS machine, and the `./ci/kokoro/macOS/build.sh bazel` failed because it was trying to re-install Bazel after I'd already installed it via home-brew. I was able to workaround this problem with a change like:

```diff
--- a/ci/kokoro/macos/build-bazel.sh
+++ b/ci/kokoro/macos/build-bazel.sh
@@ -27,15 +27,16 @@ io::log_yellow "update or install Bazel."
 # thing:
 function sha256sum() { shasum -a 256 "$@"; } && export -f sha256sum
 
-mkdir -p "cmake-out/download"
-(
-  cd "cmake-out/download"
-  "${PROJECT_ROOT}/ci/install-bazel.sh" >/dev/null
-)
+#mkdir -p "cmake-out/download"
+#(
+#  cd "cmake-out/download"
+#  "${PROJECT_ROOT}/ci/install-bazel.sh" >/dev/null
+#)
 
 echo
 echo "================================================================"
-readonly BAZEL_BIN="$HOME/bin/bazel"
+#readonly BAZEL_BIN="$HOME/bin/bazel"
+readonly BAZEL_BIN="bazel"
```

We probably want to make this change.

**Comment by coryan** [comment]
Reducing installs SGTM, I think that step is needed because bazel on the Kokoro machines is too old, worth trying, of course.  I keep seeing people using [bazelisk](https://github.com/bazelbuild/bazelisk) to install the "Right Version", somehow, also worth a shot I think.

**Comment by devjgm** [comment]
Actually, the problem is that the `install-bazel.sh` script is trying to install bazel's "darwin + arm" package, which doesn't exist. However, we can instead use darwin+x86_64 in emulated mode even on arm64.
