### ISSUE TITLE
Consider using dropdowns in packaging.md

### ISSUE THREAD

**Issue by remyabel** [googleapis/google-cloud-cpp#5901]
Github allows you to use the [\<details\> tag](https://gist.github.com/citrusui/07978f14b11adada364ff901e27c7f61) to create dropdowns in Markdown. As it's unwieldy to scroll in packaging.md when finding the appropriate section, we could save some real estate by using dropdowns.

This is what it looks like:

https://github.com/remyabel/google-cloud-cpp-1/blob/test/doc/packaging.md

**Comment by coryan** [comment]
Looks great, do you want to send a PR?  There is a generator for that file, but I am sure it would be easy to change to add the `<details>` tags.
