### ISSUE TITLE
spanner DatabaseAdminClient::CreateBackup() is erroneously labelled as non-idempotent

### ISSUE THREAD

**Issue by devbww** [googleapis/google-cloud-cpp#5907]
`DatabaseAdminClient::CreateBackup()` is treated as non-idempotent, but it will return `StatusCode::kAlreadyExists` given an existing `backup_id`, so transient errors could indeed be retried without risk.

For what it's worth, `DatabaseAdminClient::RestoreDatabase()` seems to fall into the same category.

`DatabaseAdminClient::CreateDatabase()` isn't documented either way, but it is also treated as non-idempotent.

**Comment by devbww** [comment]
Note that changing an operation from non-idempotent to idempotent means that callers should be prepared to see "already exists" returns from create operations, and "does not exist" returns from delete operations, due to retries after attempts that actually completed but failed to report an OK status all the way back.

**Comment by devjgm** [comment]
This is related to https://github.com/googleapis/google-cloud-cpp-spanner/issues/512

Does Spanner guarantee something about `CreateBackup` wrt `kAlreadyExists`? I thought this function was funny in that it _seemed_ like it should be idempotent, but there was something weird on the server side that made it not actually idempotent. Sorry I don't recall more.

**Comment by devbww** [comment]
> Does Spanner guarantee something about `CreateBackup` wrt `kAlreadyExists`?

This is only how I imagine it must work, but I'll say yes ... just like `open(O_CREAT | O_EXCL)` does with `EEXIST`.

> I thought this function was funny in that it seemed like it should be idempotent, but there was something weird on the server side that made it not actually idempotent.

I'll claim that it is not actually idempotent ... repeated applications do not have the same affect.  The question here, given the guarantee above, it whether the library should retry transient errors, and then expect callers to treat `kAlreadyExists` as success.

My latest thought on that is _"no, it should not"_, as the retry would be indistinguishable from a racing `CreateBackup`, and now that the requested backup has attributes like `version_time` and `encryption_config`, treating `kAlreadyExists` as success would be wrong (at least without then verifying those attributes).

That is, I now disagree with the _"transient errors could indeed be retried without risk"_ in the problem statement, and I think this should be closed.

**Comment by coryan** [comment]
> > Does Spanner guarantee something about `CreateBackup` wrt `kAlreadyExists`?
> 
> This is only how I imagine it must work, but I'll say yes ... just like `open(O_CREAT | O_EXCL)` does with `EEXIST`.
> 
> > I thought this function was funny in that it seemed like it should be idempotent, but there was something weird on the server side that made it not actually idempotent.
> 
> I'll claim that it is not actually idempotent ... repeated applications do not have the same affect.

The only definition of idempotent that I found in a reputable book [[1]] is "A set of **replicated messages** is *idempotent* if the effect of receiving more than one copy of a message is the same as receiving only a single copy" [emphasis mine].  Could you provide an example where multiple *replicated* copies of `CreateBackup()` do not have the same effect as a single request?

[1]: https://www.springer.com/gp/book/9781441982360

> My latest thought on that is _"no, it should not"_, as the retry would be indistinguishable from a racing `CreateBackup`,

The archetype (at least in my mind) of an idempotent message is "set the value of X to Y" (where X is an existing record).  If one has to consider racing messages to "set the value of X to Y1"  vs. "set the value of X to Y2" then idempotence would not be a very useful concept.

> and now that the requested backup has attributes like `version_time` and `encryption_config`, treating `kAlreadyExists` as success would be wrong (at least without then verifying those attributes).

I think that analysis is not quite right.  Or I completely misunderstood something.

> That is, I now disagree with the _"transient errors could indeed be retried without risk"_ in the problem statement, and I think this should be closed.

I disagree, but maybe you had something in mind that I am missing.

**Comment by coryan** [comment]
Ping.  What are the next steps here?

**Comment by coryan** [comment]
An example of an operation that could have been retried but was not.  I do agree that if retried this could have returned `kNotFound`, and the test would need to be prepared for such a return value.

https://pantheon.corp.google.com/cloud-build/builds;region=us-east1/3962c5fb-bb4f-42f5-a792-d3c997875b36;step=3?project=cloud-cpp-testing-resources

```
2021-09-23T08:11:55.004918381Z [DEBUG] <140600243849280> DropDatabase() << database: "projects/cloud-cpp-testing-resources/instances/test-instance-mr-0/databases/db-2021-09-23-ak88fh-gfwigt8uq"  (./google/cloud/internal/log_wrapper.h:73)
2021-09-23T08:11:55.005916111Z [DEBUG] <140600243849280> DropDatabase() >> status=GOAWAY received [UNAVAILABLE] (./google/cloud/internal/log_wrapper.h:75)
```

**Comment by coryan** [comment]
Close it for now.
