### ISSUE TITLE
Encountering an undefined reference link error when attempting to use the Google GCS C++ library

### ISSUE THREAD

**Issue by av8or1** [googleapis/google-cloud-cpp#5918]
We have a need to use Google's GCS C++ client library. We've downloaded the library (version 1.23.0) and all of its dependencies. We've built those libraries. I am attempting to modify one of the sample programs that Google supplies along with their GCS C++ library. Background: we're running on RHEL 7, gcc 7.4.0, GCS C++ 1.23.0 and building using the std=C++11 keyword.

The sample program creates credentials and a client handle. It then uses that handle to exercise various API methods in the GCS C++ library.

The relevant portion of the sample code I have follows:

```
std::string authBuffer = ""; //Deleted actual key for obvious reasons

// The credentials are successfully created:
auto creds = gcs::oauth2::CreateServiceAccountCredentialsFromJsonContents( authBuffer );

// As is the client handle:
gcs::Client client=gcs::Client(gcs::ClientOptions(*creds));

// This code will build and run without error:
auto writer = client.WriteObject(std::string("temp"), "quickstart.txt");
writer << "Hello world!";
writer.Close();

// However this is the problem line of code:
auto bucketReader = client.ListBucketsForProject( std::string( "my_project" ) );
```

As stated in the comments above, the bucket reader code fails to link. I encounter the following link error:

```
In function `google::cloud::v1::StatusOr<google::cloud::storage::v1::BucketMetadata>::StatusOr(google::cloud::v1::Status)': <first part of path snipped>/gc-cpp/google-cloud-cpp-1.23.0/install6/include/google/cloud/status_or.h:118: undefined reference to `google::cloud::v1::internal::ThrowInvalidArgument(char const*)'

sample.o: In function `_ZNK4absl14lts_2020_09_2316variant_internal17PerformVisitationIZN6google5cloud2v18internal11StreamRangeINS4_7storage2v114BucketMetadataEE4NextEvE13UnpackVariantJNS0_7variantIJNS5_6StatusESA_EEEEE3RunIJLm0EEJLm18446744073709551615EEEEvSt17integral_constantIbLb1EENS0_16integer_sequenceImJXT_EEEEDpSI_ImXT0_EE':

<first part of path snipped>/abseil-cpp/abseil-cpp-20200923.3/install6/include/absl/types/internal/variant.h:942: undefined reference to `absl::lts_2020_09_23::variant_internal::ThrowBadVariantAccess()'
```
All of which is a bunch of gooblty-gook upon first glance. I mean we all know what an undefined reference is, but why is this happening within the GCS C++ library code? It's almost as if Google is utilizing some type of macro build magic in order to tell me that I have malformed code of some sort. If that's the case I'm not certain where I am going awry.

Interestingly, if I comment the bucket reader statement out, then the program will build and run without incident. I can see the new quickstart.txt file appear in the bucket within the project in my GCS account via a web browser.  Furthermore, if I add in code to read the objects in a bucket (object reader) then I encounter the same link error but instead of the text stating "BucketMetadata" it states "ObjectMetadata".  And why does commenting out this code avoid the link error?  Is the internal `ThrowInvalidArgument `method not referenced by the code that I've stated does build and run successfully (ergo the write code)?

So what gives with this bucket reader/object reader business? Anyone have an idea where I am off base?  Thanks!

**Comment by coryan** [comment]
Thank you for filing a detailed bug report, and sorry you are running into trouble.

Can you share how are you compiling and linking your program?  It almost seems that some libraries are missing, for example:

```
<first part of path snipped>/abseil-cpp/abseil-cpp-20200923.3/install6/include/absl/types/internal/variant.h:942: undefined reference to `absl::lts_2020_09_23::variant_internal::ThrowBadVariantAccess()
```

That makes me believe that an Abseil library is missing from the link line, probably `-labsl_bad_variant_access`.  And this:

```
In function `google::cloud::v1::StatusOr<google::cloud::storage::v1::BucketMetadata>::StatusOr(google::cloud::v1::Status)': <first part of path snipped>/gc-cpp/google-cloud-cpp-1.23.0/install6/include/google/cloud/status_or.h:118: undefined reference to `google::cloud::v1::internal::ThrowInvalidArgument(char const*)'
```

Makes me believe that `-lgoogle_cloud_cpp_common` is missing.

Now, if you are compiling with CMake and using the exported targets (currently `google-cloud-cpp::storage`, but I think it was `storage_client` as-of 1.23.0) then the targets *should* define all their dependencies and this is a bug in our (CMake) code.  Same thing if you are using something like `pkg-config` to find the necessary libraries.

If you are writing your link lines manually, then I am afraid you need to discover these the hard way.

> And why does commenting out this code avoid the link error? Is the internal ThrowInvalidArgument method not referenced by the code that I've stated does build and run successfully (ergo the write code)?

Right.  Listing the buckets hits a different path, links a different `.o` from the `.a` and you get different dependencies.

> So what gives with this bucket reader/object reader business? Anyone have an idea where I am off base?

Hopefully I started giving an answer above. If that does not solve your problem please send us more details, including how you are compiling your program.  An [MVCE](https://stackoverflow.com/help/minimal-reproducible-example) would help, but we understand that you may be working with confidential or proprietary information, and thus it is not required.

**Comment by av8or1** [comment]
Hi Carlos-
Thank you for the detailed feedback, I appreciate that.  Yes, I am composing the build script manually with this project.  Prior to reading your reply I searched the symbol table for those names and added the -l for the two libraries that you cited, respectively, to the script.  Glad to receive verification from you that I was on the right path.  Too much reliance on automation can make one rusty with this stuff and I suppose that this was an example of that phenomenon.  I digress.
We are using the GCS C++ client library to support customer need in our products.  Therefore this is an important endeavor for us.  For that reason I may have additional questions in the future.  I'll try to make them more substantive (though the instructions did say to ask anything - hah!), but  for my information, is this the best place to pose such questions?
As an example, one question that comes to mind is in regard to the string parameters that are passed to the various GCS C++ library API methods.  Is there a particular encoding (UTF-8, ASCII, etc.) that the content of these strings should be in?  My guess was UTF-8, but not certain.
Thank you again for  your time and expertise Carlos, I appreciate it!

**Comment by coryan** [comment]
> but for my information, is this the best place to pose such questions?

Yes.  We try to monitor other channels (GitHub issues, the Google Cloud Platform community slack, stackoverflow questions tagged for `google-cloud-cpp` and/or the several products), but this is the most reliable way to get our attention.  If your questions need to be confidential then you should get in touch with your sales rep, they can find us inside Google (or maybe you can guess my email address).

> Is there a particular encoding (UTF-8, ASCII, etc.) that the content of these strings should be in?

Generally UTF-8. Names of buckets, objects, metadata, etc. are expected to be UTF-8 encoded.  We will URL encode them as-needed when sending them via HTTP (the object names for example go in the URL).

Data (the contents of a GCS object) is generally treated as binary blobs.

**Comment by av8or1** [comment]
Ok Carlos, thank you for the additional feedback.  I'll be in touch if I have any further questions.
