### ISSUE TITLE
common_options.h: What type for UserAgentPrefixOption?

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#5952]
This comment from @coryan https://github.com/googleapis/google-cloud-cpp/pull/5949#pullrequestreview-601260170

> Maybe a followup PR, I am not sure what the right representation for the UserAgent header should be. I think the following properties are desirable:

> * Applications can add their own.
> * Intermediate libraries (think something like Tensorflow, built on top of our GCS library) could add their own.
> * Applications cannot remove the prefixes added by libraries (because we lose the ability to troubleshoot things).
> * The end result is a string that we put in some HTTP header (or a similar thing).

> Seems like order should matter, maybe a std::vector<> is better than std::set<>, seems like it will always be "small", maybe a dozen elements. Seems like a std::string could handle this just fine.

According to https://tools.ietf.org/html/rfc7231#section-5.5.3, it looks like order is important: "By convention, the product identifiers are listed in decreasing order of their significance for identifying the user agent software." So the original choice of `std::set` was not good.

Uniqueness seems somewhat important, because what's the point of listing the same user-agent multiple times? However, it's likely easy enough to just rely on folks simply not setting it multiple times. That is, I think I agree now that the uniqueness offered by `std::set` is not crucial.

Regarding "Applications cannot remove the prefixes added by libraries", I'm not sure if/how we can avoid that one for certain. Other than to say that user-agents can only ever be added by a library that has access to the `internal::Options` instance that's eventually passed to `MakeConnection()`. _Our_ user-agent string will be added _within_ `MakeConnection()`, so nobody could ever remove ours. This all seems fine to me.

I agree that a `std::string` could work. One concern with `std::string` is that it doesn't capture the fact that multiple "product identifiers" (terminology from RFC 7231) can be added. I know we use the term "prefix", but it would be easy for a user to accidentally _set_ the string to their product, thus erasing previously set product identifiers. Whereas, if we used a type that naturally conveys the fact that there can be multiple user-agent product identifiers, it may be less likely that users accidentally erase others' product IDs. Additionally "appending" one's product ID to a user-agent `std::vector` (or better yet, `std::deque` to allow prepending) would be even easier for users since they wouldn't need to worry about concatenating, and joining with a space.

### Proposal

So given all that, I think I agree that `std::set` was the wrong choice:

https://github.com/googleapis/google-cloud-cpp/blob/37054c009d74917d04cabe40aa796be9950e8ed2/google/cloud/internal/common_options.h#L46-L48

However, now I think `std::deque` may be preferred.

Thoughts?

**Comment by coryan** [comment]
> However, now I think `std::deque` may be preferred.

`std::deque` would work. Alternatively, `std::vector<>` using `.push_back()` to add and `.rbegin()/.rend()` to iterate would work too?  

>  Our user-agent string will be added within MakeConnection(), so nobody could ever remove ours. This all seems fine to me.

That seems like a good place to start, and most likely all we will ever need.
