### ISSUE TITLE
Cleanup {Get,Set}NativeBucketIamPolicy

### ISSUE THREAD

**Issue by ghost** [googleapis/google-cloud-cpp#5958]
In #5937 these two functions were implemented but there are a few things that need to be cleaned up. First:

https://github.com/googleapis/google-cloud-cpp/blob/f403eeafe56a35ee83c5f0be7e24eb6ede045759/google/cloud/storage/emulator/gcs/bucket.py#L246

This almost certainly seems wrong, `policy_pb2` should be able to accept an `etag`, but this workaround was added because the test freezes suggesting either a bug in the test or how the emulator handles the data.

Secondly, the integration test does not test the etag at all and it probably should. 

~~Finally, the resource is currently set to just the bucket name but maybe it should be a full URL instead (i.e similar to the format `projects/*project*/bucket/*bucket_name*`). The documentation says to "check the operation documentation" without a link, however setting just the bucket name for the emulator seems to work just fine.~~

The HybridClient may also need a conditional to call `grpc_->SetBucketIamPolicy`. Note the excessive use of "may"/"probably" because I am unsure of these things.

That is all I can remember for now.

**Comment by coryan** [comment]
FWIW, the resource name for buckets is `projects/_/buckets/*bucket_name*`, that is, the project is always replaced by `_` as a wildcard.

**Comment by remyabel** [comment]
Per https://github.com/googleapis/google-cloud-cpp/pull/6852 it seems like we don't need to care about the resource name anymore.

**Comment by coryan** [comment]
Blocked on GCS+gRPC implementing etags.

**Comment by coryan** [comment]
This is fixed.
