### ISSUE TITLE
[Flake] FutureTestVoid wait_for returned too quickly

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#5966]
https://source.cloud.google.com/results/invocations/f6be89cf-0ef2-496a-8c48-415be422500a/targets/cloud-cpp%2Fgithub%2Fgoogle-cloud-cpp%2Fmaster%2Fmacos%2Fcmake-super/log

```
[ RUN      ] FutureTestVoid.conform_30_6_6_21
/Volumes/BuildData/tmpfs/src/github/google-cloud-cpp/google/cloud/future_void_test.cc:600: Failure
Expected equality of these values:
  std::future_status::timeout
    Which is: 4-byte object <01-00 00-00>
  waiter.wait_for(2_ms)
    Which is: 4-byte object <00-00 00-00>
[  FAILED  ] FutureTestVoid.conform_30_6_6_21 (664 ms)
```

https://github.com/googleapis/google-cloud-cpp/blob/69a409afdb147fef2e2e5ce999429864d4e98b8e/google/cloud/future_void_test.cc#L578-L603

The error was on **line 600**.

I'm no expert on `future`, but it looks like the code expected `std::future_status::timeout` to be returned which had a value of `1`, but something else was returned with a value of `0`. The enum for `std::future_status` looks like:

```cc
  /// Status code for futures
  enum class future_status
  {
    ready,
    timeout,
    deferred
  };
```

So it looks like `waiter.wait_for(2_ms)` returned `std::future_status::ready`.

---

So one guess is that the test got blocked somewhere after the first thread started waiting, and by the the time the second thread called `waiter.wait_for(2_ms)`, the first thread was already done waiting. If this sounds right, we may be able to avoid this flake by having the first thread wait longer than 500ms? But I'll wait for someone like @coryan to double check this theory before I bother.

**Comment by devjgm** [comment]
FWIW, I was not able to repro any flakes w/ that test in 10k runs on my **Linux* machine, though I realize that the above error was from our macos cmake-super build

`bazel test google/cloud:future_void_test --runs_per_test=10000` was OK

**Comment by coryan** [comment]
It might require loading the workstation too, like running a build at the same time.  I think what happens is:

- the thread suspended in line 600 does not return for 500ms (instead of the 2ms requested)
-  **and** for the `ScopedThread` created in line 591 completes (even though the other thread is suspended).

All of this suggests we should use a latch / barrier to coordinate the two threads.  But amusingly we are testing the classes we would use to implement those.

**Comment by coryan** [comment]
https://source.cloud.google.com/results/invocations/460f3c5a-f63f-446d-958e-a3fe87063075

**Comment by coryan** [comment]
https://source.cloud.google.com/results/invocations/d9b3ded9-4230-4d07-8a52-ac7781a1d5cc

**Comment by coryan** [comment]
https://source.cloud.google.com/results/invocations/6e30ae65-b507-4c0d-8e57-841ceab671b1
