### ISSUE TITLE
generator: inline namespace in hierarchy causes ambiguity

### ISSUE THREAD

**Issue by scotthart** [googleapis/google-cloud-cpp#5974]
Problem:
With the new microgenerator we wanted to have the namespace hierarchy as:
namespace google {
namespace cloud {
inline namespace GOOGLE_CLOUD_CPP_NS {
namespace product_name {

however, proto code pb.h and pb.cc files from googleapis//google/cloud/product_name generate their own namespace hierarchy:
namespace google {
namespace cloud {
namespace product_name {

this results in ambiguity that the compiler cannot resolve.

Proposal:
adjust the generated namespace hierarchy to:
namespace google {
namespace cloud {
namespace product_name {
inline namespace GOOGLE_CLOUD_CPP_NS {

**Comment by devjgm** [comment]
FYI, not blocked on, but related to https://github.com/googleapis/google-cloud-cpp/issues/5976
