### ISSUE TITLE
Consider removing sudo from ci scripts

### ISSUE THREAD

**Issue by remyabel** [googleapis/google-cloud-cpp#6013]
It is common practice for people to add themselves to the docker group (`usermod -aG docker`) to avoid using `sudo`. The ci scripts currently use sudo which means that they will always prompt for sudo whether you're in the group or not. I think it would be better to add to the documentation to add yourself to the docker group and remove sudo to avoid the unnecessary prompt and most people will already have added themselves to the group anyway since it is part of the Docker documentation.

**Comment by coryan** [comment]
Good idea, I can take a stab at it, unless you prefer to do it.
