### ISSUE TITLE
[Flake] Pub/Sub samples timeout in test

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#6053]
https://source.cloud.google.com/results/invocations/29229a70-3153-456e-8e9e-f55f127bafad

```
7/7 Test #207: pubsub_samples ...............................***Timeout 1500.10 sec
```

**Comment by dbolduc** [comment]
```
Running SubscribeAvroRecords() sample

Running PublishAvroRecords() sample

Waiting for session [SubscribeAvroRecords]... TIMEOUT
Standard exception raised: session timeout
```

* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/a47ece6e-0bea-4a9e-954d-982ae9853396;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/9430/3787eabd7ed84dfdea7eafc194b7946ab7bba8bc/fedora-35-cmake-gcs-rest/log-a47ece6e-0bea-4a9e-954d-982ae9853396.txt

**Comment by dbolduc** [comment]
It is not the same problem. I probably should have opened a separate issue. I only filed it here because the title matched.

**Comment by coryan** [comment]
No repeats in 90d, and probably reopened in error. Closing.
