### ISSUE TITLE
Cleanup `return` from void function to avoid confusion

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#6059]
Some static analysis tools (including the ones made out of carbon instead of silicon and bits) read this code and think it may be trying to return a value through a `void` function:

https://github.com/googleapis/google-cloud-cpp/blob/ddefe5bd3320d99631a886fe4920a09aa7f58053/google/cloud/future_void.h#L75

The `tmp->get()` expression always returns `void`, but it is unnecessarily confusing.

**Comment by devbww** [comment]
"Confusing" may be in the eye of the beholder, but this is C++ where "[A return statement with an operand of type void shall be used only in a function whose return type is cv void](http://eel.is/c++draft/stmt.return#2)."  So, I'd say the tool is over reaching.

**Comment by coryan** [comment]
I thought maybe the tool was being conservative in the face of a template, but the only templates here are fully specialized.  The return type from `tmp->get();` is `void` and can only be `void`.  On a second look, I agree with @devbww.
