### ISSUE TITLE
Consider removing bash specific workaround

### ISSUE THREAD

**Issue by remyabel** [googleapis/google-cloud-cpp#6081]
This workaround:

https://github.com/googleapis/google-cloud-cpp/blob/98fe207f2f20147b4e6a9e5df1d87fad3f71796e/ci/kokoro/docker/build-in-docker-cmake.sh#L122-L127

was added because of an edge case in older versions of Bash. However, enough time has passed that we should revisit whether or not this workaround is still necessary.

**Comment by coryan** [comment]
I actually tried without the workaround a couple of days ago and it did not work for one of our builds:

https://github.com/googleapis/google-cloud-cpp/pull/6065/commits/8cd286bd66b61df04a0219f5d9f165c3f2711608

I needed to add them back:

https://github.com/googleapis/google-cloud-cpp/pull/6065/commits/2c03cddc4a7d33f967c8ee58b7b379c613c1038a

Maybe we should consider removing those builds, but that is a much larger discussion.

**Comment by coryan** [comment]
Maybe we should replace the builds based on Ubuntu:16.04 with builds in `ci/kokoro/install`, these would be:

- [ ] gcc-5.4: use a new (?) build in `ci/kokoro/install`
- [ ] clang-3.8: use a new (?) build in `ci/kokoro/install`

Note that Ubuntu:16.04 is reaching end of standard support before 2021-05-01, at which point maybe we should stop supporting `clang-3.8` and `gcc-5.4` (see #5677).  So in about a month we might remove (we need to decide if "end of standard support" is enough to drop these compilers) these builds and then we can simplify all of this with less effort.

I think we should wait a few weeks and decide then.

**Comment by devjgm** [comment]
Obsolete by https://github.com/googleapis/google-cloud-cpp/projects/11, which replaced all the `ci/kokoro/{docker,install}` code with `ci/cloudbuild/`
