### ISSUE TITLE
Move Linux builds to Cloud Build

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#6083]
This issue is to capture notes about our use of Google Cloud Build for some (or all of?) our Linux builds. In https://github.com/googleapis/google-cloud-cpp/pull/6080 I added the basic Cloud Build configs along with some basic scripts. With this change, we're now able to trigger cloud builds (manually) with commands like:

```
$ ci/cloudbuild/build.sh asan # runs the asan build on GCB
$ ci/cloudbuild/build.sh asan --docker # runs the asan build in your local docker
$ ci/cloudbuild/build.sh asan --local # runs the asan build in your local environment
```

I also configure a couple test triggers in the Cloud Build UI for the cloud-cpp-testing-resources project. The following are some remaining things that we need to figure out:

- [x] Figure out caching. The bazel builds should use the remote bazel cache. The cmake builds should use ccache and should store/fetch the ccache's directory.
- [x] Add support for integration tests. We'll need to get the correct credentials working
- [x] Add "install" / "quickstart" builds
- [x] Figure out if there are build artifacts that we should be capturing. Maybe we should capture the test output from all unit tests that we run?
- [x] Figure out how best to run these builds locally. The more logic we put in cloudbuild.yaml, the more difficult it may be to run builds locally. Though we can try cloud-build-local, which may make this easier.
- [x] Figure out how to expose the build logs so that OSS contributors can see the build output and diagnose their own build breaks. Maybe we can funnel the logs over to result store somehow?
- [x] Figure out if there's a way to programmatically configure triggers so that we can check the trigger configuration into github.
- [x] Add more build configurations. Ideally, we'd replace all of `ci/kokoro/docker/`. In particular a configuration to generate and publish doxygen docs when the release branch is created would be cool
- [ ] Figure out how to add build badges
- [ ] Setup failure notifications for failed CI builds

**Comment by devjgm** [comment]
All these builds now exist in GCB. The remaining issue about build badges exists in a separate issue.

**Comment by devbww** [comment]
```
$ git grep '#6083'
ci/cloudbuild/builds/lib/integration.sh:  # TODO(#6083): Run //google/cloud/bigtable/examples:bigtable_grpc_credentials
ci/cloudbuild/builds/lib/integration.sh:  # TODO(#6083): Add support for:
```
