### ISSUE TITLE
Doc landing page contains vulnerable libraries

### ISSUE THREAD

**Issue by remyabel** [googleapis/google-cloud-cpp#6085]
These:

https://github.com/googleapis/google-cloud-cpp/blob/aec571cd53fe638d300e78748f6133dd42d04abe/doc/landing/index.html#L191-L193

are outdated and contain [vulnerabilities](https://snyk.io/test/website-scanner/?test=210322_XiVJ_8b28022e3e2d1d717c5791af8cfc6b4a&utm_medium=referral&utm_source=webpagetest&utm_campaign=website-scanner). They should be updated.

**Comment by remyabel** [comment]
Actually, the web stuff in general hasn't been updated in 2 years. Just a couple of notes:

- modernizr probably isn't needed because the browsers it supports (< IE11) represents a miniscule demographic, I think html5shiv would be better
- angular can be removed, the website seems to run just fine without it
- the other dependencies (CSS) need to be updated as well
- I could go on about best practices but the details aren't important

It appears that the web stuff was added by directly committing to gh-pages. You guys may not be happy about adding web stuff to the build process, but it would avoid having to manually check and do this again 2 years down the line.

**Comment by coryan** [comment]
I think we should change all these landing pages to re-directs to googleapis.dev/$version

**Comment by devjgm** [comment]
Too many separate documentation locations is not great for users. I agree with @coryan that having a single, canonical location for docs would be a better UX. More concretely, I think we want to:

1. Remove all the content on our `gh-pages` branch.
2. Add a single file that tells folks to see our main github README.md file and perhaps also links to https://googleapis.dev/cpp/$lib/latest/
3. Stop our bot that's updating `gh-pages`, because there will be nothing to update.

Do we know of any important links *into* this site that may be affected?

Is this the plan that we're thinking?

**Comment by remyabel** [comment]
> Do we know of any important links into this site that may be affected?

I think it may be possible to use google search central or a similar tool to look for links that link to the page.

The link sounds good but may be improved by doing an automatic redirect.

**Comment by devjgm** [comment]
I don't think Google supports `link:` searches anymore, sadly.

**Comment by devjgm** [comment]
Question: Should the `googelapis.github.io/google-cloud-cpp` URLs redirect to the `googleapis.dev/...` docs, or simply redirect to `https://github.com/googleapis/google-cloud-cpp`? I'm mildly inclined to say the latter but would be happy the other way also.

**Comment by coryan** [comment]
People going to googleapis.github.io/google-cloud-cpp are looking for the reference documents. Landing on the the top-level `google-cloud-cpp` would be frustrating to me.  Landing on a `.md` that says "the reference documents moved to googleapis.dev" with links per library or something would be less surprising (and would not raise my blood pressure).

**Comment by devjgm** [comment]
> People going to googleapis.github.io/google-cloud-cpp are looking for the reference documents.

Serious question: how do we know that?

> Landing on the the top-level `google-cloud-cpp` would be frustrating to me. Landing on a `.md` that says "the reference documents moved to googleapis.dev" with links per library or something would be less surprising (and would not raise my blood pressure).

A static set of links sounds fine to me. But I'd like to avoid the need to have a build that auto-generates anything on `gh-pages`. I'd rather just deprecate it as if it didn't exist. The links or redirect is just there for anyone who may happen to have it bookmarked.

**Comment by coryan** [comment]
> > People going to googleapis.github.io/google-cloud-cpp are looking for the reference documents.
> 
> Serious question: how do we know that?

Okay, maybe I was overly confident.

The reference documents used to be there, at least the current customers, that used `gh-pages` would continue to expect them to be there.

The folks "guessing" that the page exist would probably expect the "project documentation" (see the description at https://pages.github.com/).

Of course folks host all kinds of stuff there too, blogs and pretty sites.

In any case, if one has to guess "where are the documents for a project", it is either the gh-pages or https://readthedocs.io/

> A static set of links sounds fine to me.

That sounds good.

>  But I'd like to avoid the need to have a build that auto-generates anything on `gh-pages`. I'd rather just deprecate it as if it didn't exist. The links or redirect is just there for anyone who may happen to have it bookmarked.

I agree with that too.
