### ISSUE TITLE
Include info on where to file bugs for library / service failures

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#6094]
In a few places the libraries validate the output from the service, e.g.:

https://github.com/googleapis/google-cloud-cpp/blob/fbe2945392871cfd7137747e13c07ea0ff7ed922/google/cloud/bigtable/internal/readrowsparser.cc#L38-L46

When this happens we should add a place where developers can file a bug.  When it is ambiguous if this is a library or service bug we should point folks to our GitHub repository, for service bugs we can point them to:

https://issuetracker.google.com/issues/new?component=187065&template=1380925

Or one of the more specific components:

https://issuetracker.google.com/components/187206 -> Cloud Bigtable
https://issuetracker.google.com/components/187173 -> Cloud Pub/Sub
https://issuetracker.google.com/components/187243 -> Cloud Storage
https://issuetracker.google.com/components/190851 -> Cloud Spanner

PS: the example is for Bigtable, but this request is more general than that.

**Comment by devjgm** [comment]
Closing. It's probably best for customers to just file the issue w/ us on GitHub.
