### ISSUE TITLE
[Flake] Spanner unit test fails with "leaked" mock object

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#6145]
The log says:

```
../../google/cloud/spanner/database_admin_connection_test.cc:917: ERROR: this mock object (used in test DatabaseAdminClientTest.CreateBackupWithEncryption) should be deleted but never is. Its address is @0xd49970.
ERROR: 1 leaked mock object found at program exit. Expectations on a mock object is verified when the object is destructed. Leaking a mock means that its expectations aren't verified, which is usually a test bug. If you really intend to leak a mock, you can suppress this error using testing::Mock::AllowLeak(mock_object), or you may use a fake or stub instead of a mock.
```

https://source.cloud.google.com/results/invocations/b4c30a87-27e9-4640-b290-f47f10282ce8

I think this is related to #4444, the mocks remain referenced by a (detached) thread.  Let the record reflect that I think detached threads are a "Bad Thing":tm:, but with that out of the way, I think the changes proposed in #4038 these should go away.

**Comment by coryan** [comment]
https://source.cloud.google.com/results/invocations/abd6e9a8-860e-4ca4-8886-f28037a7d635

**Comment by devjgm** [comment]
Another https://source.cloud.google.com/results/invocations/2905bfd8-d475-4c4e-9902-ed3ffa2e104d/targets/cloud-cpp%2Fgithub%2Fgoogle-cloud-cpp%2Fmaster%2Fdocker%2Fnoex-presubmit/log
