### ISSUE TITLE
Document how grpc::GoogleIAMCredentials works

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#6154]
To use these in the GUAC implementation we need to understand:

- [ ] What exactly is the format for `authorization_token`?
- [ ] What exactly is the format for `authority_selector`?
- [ ] Do these credentials automatically refresh or do we have to take action after some time?  In other words:
    - [ ] Are new tokens created by gRPC?
    - [ ] Do we need to create a new `grpc::CallCredentials` object?

**Comment by coryan** [comment]
This is very frustrating, I cannot find a single example using this API.  It seems that it is used to set two headers: `x-goog-iam-authoritization-token, and `x-goog-iam-authority-selector`. But I cannot find any documentation about them either.

**Comment by devjgm** [comment]
Will reopen if we ever decide that we need to support this.
