### ISSUE TITLE
[GCB] Enable bigtable integration tests that use an access token

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#6178]
The following kokoro tests

 https://github.com/googleapis/google-cloud-cpp/blob/ec966f4ba835fe6665cde85284b479070a0428d0/ci/kokoro/docker/build-in-docker-bazel.sh#L279-L299

Are not yet implemented in our GCB builds.

https://github.com/googleapis/google-cloud-cpp/blob/ec966f4ba835fe6665cde85284b479070a0428d0/ci/cloudbuild/builds/integration.sh#L73-L74

We need to fix this.

**Comment by coryan** [comment]
Maybe use the IAM library in this example and avoid all the stuff with `gcloud`:

https://github.com/googleapis/google-cloud-cpp/blob/ad115d5d6c772b4fef5b3fc415b0b62e4e373b04/google/cloud/iam/samples/grpc_credential_types.cc#L42-L50
