### ISSUE TITLE
[GCB] Create a PROD integration test

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#6181]
We prefer running our integration tests against emulators because they're much faster and less flaky (usually). However, we should have at least one build that runs the integration tests against actual production servers.

Today we have macOS and Windows builds on Kokoro that hit production when running integration tests, but we may want to disable those integration tests on macOS and Windows. If we do, we'll need to be running them on GCB.

Depending on our server-side quota limitations, we could run these builds on every PR and CI (might be slow), or we could run them nightly, or N times per day. We have options.

**Comment by coryan** [comment]
Just something to consider as you restructure these: currently `ci/cloudbuild/builds/integration.sh` runs the tests for service A, then service B, then service C, etc.  That is wasting opportunities for parallelism when running against production. It was (more or less) unavoidable when running against emulators (and less important because the emulators are "fast"), but when running against production there is value in running as many tests in parallel as possible.

**Comment by coryan** [comment]
Thinking out loud here to help me reason through this:

- The goal is to test each library against production: that is what matters to our customers.
- Running against production is slow, and fraught with flakiness, and quota issues so we prefer to use emulators.
- Using the emulators creates a few coverage (as in "feature coverage", not "line coverage") gaps: e.g., verifying the actually endpoints are correct, and that authentication works, and that the headers we include with each RPC are not rejected.
- In addition, the emulators do not support all features.  We test those features by running a small subset of the tests using production.
- Largely, running that handful of tests against production closes the previous gap.

So I think in general the answer would be:

> If we have a library / service tested against the emulator, then we just need a handful of tests using production.

So I would say we do **NOT** need a separate build.  With the following caveat:

I cannot recall if all libraries that use the emulator at least one test using production.  In some cases (e.g. storage signed URLs) the library is not used to hit the production service at all. I think your recollection / knowledge is better than mine at this point.

PS: I am not sure how to apply this reasoning to the interaction between the production tests on macOS and Windows vs. the other tests... I think there is a case for "don't test on Linux if you already tests on macOS and Windows".

**Comment by devjgm** [comment]
Thanks. OK, so at this point, it sounds like there's nothing explicit that we need to do.

If at some point we decide to stop running the prod-facing integration tests on mac or windows, at that point we may need to make sure that prod-facing integration functionality exists on GCB. Until then, I think we can close this.
