### ISSUE TITLE
[Flake] timeout in cmake-super build

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#6184]
One of the GCB builds timed out:

https://pantheon.corp.google.com/cloud-build/builds;region=global/0b9e85cc-2331-4136-98ae-7601d8b32519?project=cloud-cpp-testing-resources

Maybe the timeout is too optimistic?

**Comment by devjgm** [comment]
1 hour on 32 cores _should_ be enough. Not sure what happened here. I wish CMake could output periodic time stamps, that would help.

One other though is that it doesn't look like the super build is using ccache for the deps it compiles. We may want to change the `CC` and `CXX` vars to look like `export CXX="ccache ${CXX}"`. That may help.

**Comment by coryan** [comment]
We have stopped using super builds, this is now obsolete.
