### ISSUE TITLE
[Generator] use GOOGLE_CLOUD_CPP_ENABLE_TRACING to initialize tracing components

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#6185]
While writing some examples for `google/cloud/iam/` (they will help me understand credentials for the GUAC project) I discovered that `GOOGLE_CLOUD_CPP_ENABLE_TRACING` does not seem to work for generated clients.  At a guess, the tracing components in ` google::cloud::Options` is not getting initialized from the environment variable.

**Comment by devbww** [comment]
It looks like this was fixed by #8294, yes?

**Comment by coryan** [comment]
You are correct. Closing.
