### ISSUE TITLE
Use CURLSSLOPT_NATIVE_CA to rely on the Windows native CA

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#6214]
With recent (>= 7.71.0) versions of `libcurl` one can use the native CA on Windows:

https://stackoverflow.com/questions/37551409/configure-curl-to-use-default-system-cert-store-on-windows
https://curl.se/libcurl/c/CURLOPT_SSL_OPTIONS.html

We need to make sure this still works when libcurl was compiled against `Schannel`, but that seems like a reasonably safe bet.

**Comment by devjgm** [comment]
Keeping open, but can't do it now.

**Comment by coryan** [comment]
Strike two.

**Comment by coryan** [comment]
No time for this, to the backlog.
