### ISSUE TITLE
[Flake] macOS failure in HTTP request after 3 retries

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#6220]
Build failure:

https://source.cloud.google.com/results/invocations/5f90ab44-cc51-4b6e-aeb5-cf4a4da3f139

```
[ RUN      ] SignedUrlIntegrationTest.CreateV2SignedUrlGet
../../../../google/cloud/storage/tests/signed_url_integration_test.cc:84: Failure
Value of: response
Expected: code is equal to OK and message is anything
  Actual: 88-byte object <0E-00 00-00 33-90 F8-0A 41-00 00-00 00-00 00-00 39-00 00-00 00-00 00-00 E0-DB C1-B6 FA-7F 00-00 6A-B3 0B-E7 F8-74 1A-1E F7-84 45-75 94-56 67-60 72-8B 6E-7C EB-98 B3-26 03-6B A1-6A 63-D2 97-7B F5-45 CF-48 C2-4C EF-6F 20-27 AC-BD E5-03 AF-3A 24-52 59-9F 48-40 67-21>, whose status is EasyPerform() - CURL error [7]=Couldn't connect to server [UNAVAILABLE], with a code that isn't equal to OK, but a message that is anything
```

The error is coming from here:

https://github.com/googleapis/google-cloud-cpp/blob/5733893ffef4f85df28b63d08852a2f89cc311b7/google/cloud/storage/tests/signed_url_integration_test.cc#L83-L84

I thought I had "fixed" this in #5664.  We may need more retries, or maybe more interesting backoff policies.

**Comment by coryan** [comment]
I am changing the description because it also happens in non-raw HTTP requests:

https://source.cloud.google.com/results/invocations/0a927011-95fa-42e6-84fc-6c3437963a36

**Comment by devbww** [comment]
https://source.cloud.google.com/results/invocations/b635598a-c8e8-4973-b4bf-cb94ad7e3f4b

**Comment by coryan** [comment]
No repeats in 90d, closing.
