### ISSUE TITLE
Most Kokoro builds are currently broken

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#6226]
Internal tracking bug: b/185053280

It looks like there's a kokoro issue that's making all/most of the kokoro builds fail. We probably want to remove our kokoro builds as "required" builds before we merge. We can change the required builds to GCB builds for the time being.

It seems the Kokoro Windows builds are still working. Not sure why.

**Comment by devjgm** [comment]
Actually, I just made the change to our branch settings.

* I removed `clang-tidy` (kokoro) as a required build
* I removed `integration` (kokoro) as a required build
* I added a few GCB builds that cover bazel, cmake, and our checkers as required instead

**Comment by coryan** [comment]
This is now resolved.
