### ISSUE TITLE
GCB: Consider changing demo doc tags to avoid clash w/ snippet-bot

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#6241]
nit: the use of `START` and `END` markers clashes with the cloud site documentation tags.  You may be in a good position to fix this as part of this PR series.

_Originally posted by @coryan in https://github.com/googleapis/google-cloud-cpp/pull/6239#discussion_r612603056_

**Comment by devjgm** [comment]
The regex that the snippet bot uses is here:

https://github.com/googleapis/repo-automation-bots/blob/e6ac5813b8fb4e05b4ef020f09220594c2f6b2cf/packages/snippet-bot/src/region-tag-parser.ts#L57-L58

```typescript
export const START_TAG_REGEX = /\[START ([^\]]*)\]/;
const END_TAG_REGEX = /\[END ([^\]]*)\]/;
```

So we just need something that doesn't match that.

We could use `BEGIN` and `DONE`? Or something else if someone has a better name.

**Comment by coryan** [comment]
> We could use `BEGIN` and `DONE`? Or something else if someone has a better name.

I think that will work, no I do not have a better name.
