### ISSUE TITLE
[GCB] demo-fedora-{pr,ci} builds are failing when triggered, but pass locally

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#6247]
See https://pantheon.corp.google.com/cloud-build/builds/785e1059-b0ee-4f88-96a1-3d5d133e4e4b;step=2?project=cloud-cpp-testing-resources

These builds seem to fail when triggered by GCB, but they pass when I run it in a local docker container, and when I run it in GCB myself.

I do not know why. I disabled these triggers until this bug is fixed.

**Comment by devjgm** [comment]
Here's the first build that would have created the docker images in kaniko: https://pantheon.corp.google.com/cloud-build/builds;region=global/10c90920-48bb-42e9-a97e-43f2f9ae1622;step=0?project=cloud-cpp-testing-resources

**Comment by devjgm** [comment]
Actually, I can reproduce this build failure but only when I run the build in the `cloud-cpp-testing-resources` project:

```
 ci/cloudbuild/build.sh -t demo-fedora-pr --project cloud-cpp-testing-resources
```

**Comment by coryan** [comment]
FWIW, the CMake-based build passed, it is only the Make-based build that fails, and only when trying to run things.  That suggests CMake is doing a better job with the RPATH settings, maybe?
