### ISSUE TITLE
Rationalize GCS+gRPC integration tests

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#6268]
# Objective

We want our customers to have a good experience with the GCS+gRPC plugin when it becomes available, that requires extensive integration tests.  We also want to detect defects as early as possible during development, that argues for early integration tests.

# Background

Unlike other services the GCS+gRPC plugin is under development more or less at the same time that the service is.  We have often developed *features* at the same time as the service is under development, we just implement the features in the emulator and test them only against the emulator until the service is ready.  This is an extreme case of that approach.

To support simultaneous development the GCS emulator supports both REST and gRPC APIs. However, only the data operations (`InsertObject()`, `WriteObject`, `ReadObject()`) are implemented in the service.

To reuse existing integration tests and benchmarks we implemented a "hybrid" plugin. This routes requests to the gRPC plugin when possible (i.e. when implemented in production), and routes other requests to the existing REST-based implementation (i.e., storage::internal::CurlClient).

The plugin itself is under development, some features are not implemented in the GCS+gRPC plugin.

The storage integration tests use `GOOGLE_CLOUD_CPP_STORAGE_GRPC_CONFIG` to select which plugin they are testing. The integration tests use the following values:

* If set to `media`, use the hybrid plugin, only data operations are sent to production or the emulator.
* If set to `metadata`, use the gRPC plugin, both data and metadata operations are sent to production or the emulator, as only the emulator supports this, it should not be enabled in builds using production.
* any other value, or if unset, use the REST-based plugin.

# Goals

We want to:

* **(A)** Test the GCS+gRPC plugin as early as possible, using the emulator to test as many features as possible.
* **(B)** Test the GCS+gRPC plugin against production for those operations that are supported in production.
* **(C)** Test that the code can be compiled with the GCS+gRPC plugin turned on or off, so applications can omit building the plugin.

# Current Status

The `gcs-grpc` build is specifically designed to satisfy **(B)**.  It runs **all** the storage integration tests against production, with the hybrid plugin to route operations through the right protocol. Note that as of 2021-04-15 this is not true, because the service has been down since 2021-03-18 (see #6062), but normally it would be (see #6063).

The builds running against the emulator test **(A)** because there is one integration test (`grpc_integration_test.cc`) that always tests with both `GOOGLE_CLOUD_CPP_STORAGE_GRPC_CONFIG=media` and `GOOGLE_CLOUD_CPP_STORAGE_GRPC_CONFIG=metadata`.

The `gcs-no-grpc` build is specifically designed to satisfy **(C)**.

**Comment by devjgm** [comment]
Keeping open.

**Comment by coryan** [comment]
I am planning to clean this up in the next milestone for GCS+gRPC, during 2022-Q4.

**Comment by coryan** [comment]
For the record.  I think we should consolidate all the tests against GCS+gRPC in the `production-integration` build.  That would make it much easier to reason about where the tests are and what they are testing.  At the moment we cannot, the behavior of GCS+gRPC is too unstable to block PRs on it. The `gcs-grpc` build tests that it works, but it is not a required build.
