### ISSUE TITLE
Consider integrating all the Doxygen documentation to a single page.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#637]
Currently we have separate pages for each library:

https://googlecloudplatform.github.io/google-cloud-cpp/latest/storage/
https://googlecloudplatform.github.io/google-cloud-cpp/latest/bigtable/
https://googlecloudplatform.github.io/google-cloud-cpp/latest/firestore/

We should consider a single page where all the documentation is grouped together.  I think the other languages do that.

**Comment by coryan** [comment]
@mbrukman @ghaisa @sduskis @houglum I would be interested in your thoughts about this.

@frankyn or @sduskis we should probably loop some of the Cloud Client Libraries folks into this, can you `@-mention` them in this bug some they can chime in?  Thanks!

**Comment by coryan** [comment]
@JustinBeckwith thoughts?

**Comment by JustinBeckwith** [comment]
Greetings!  We do generally try to put all the reference API documentation on a single site that's easily acessible.  Right now it's kind of confusing, as [this page](https://googlecloudplatform.github.io/google-cloud-cpp/0.1.0/index.html) only calls out BigTable.

Is this something doxygen will let you do easily?

**Comment by coryan** [comment]
Once we have moved some of the code around merging the Doxygen stuff should be easy.

**Comment by frankyn** [comment]
Raised in Client library weekly. Agree with Justin it's a good idea to have a single page that links to all documentation pages and the pattern is used by the other client libraries as well.

**Comment by coryan** [comment]
I have a branch with this implemented, the preview of the pages is here:

https://coryan.github.io/google-cloud-cpp/latest/html/index.html

Will send PR when the tests pass.

**Comment by houglum** [comment]
Sounds reasonable to me, as long as we can keep the docs structure of "google/cloud/<library>/doc/..." (and if not, at least have a README under that directory linking to the correct location).  This is where I'd expect to find docs for each library, personally.

**Comment by frankyn** [comment]
Feedback:
[Namespaces](https://coryan.github.io/google-cloud-cpp/latest/html/namespaces.html)
1. BigTable and Storage aren't under a namespace
1. Storage shouldn't be there yet? 

[Landing page](https://coryan.github.io/google-cloud-cpp/latest/html/index.html)
1. I only see BigTable and not Firestore

[Related Pages](https://coryan.github.io/google-cloud-cpp/latest/html/pages.html)
1. Can you rename the title to **Examples**? 

[Files Page](https://coryan.github.io/google-cloud-cpp/latest/html/files.html)
1. Contains information on Storage library which I think should be removed.

**Comment by coryan** [comment]
> Namespaces
>
> BigTable and Storage aren't under a namespace

Because the classes are not, not yet: #652, #629 

> Storage shouldn't be there yet?

Easy enough to remove, but the code is on the `master` branch, so I would rather see it exposed in the documentation for it.

> Landing page
> I only see BigTable and not Firestore

We should create one: #657.

> Related Pages
>  Can you rename the title to Examples?

According to stackoverflow [yes](https://stackoverflow.com/questions/10761125/doxygen-related-pages), but what if we have other stuff there later?  Tutorials, or something else?  Anyway: #658.

> Files Page
> Contains information on Storage library which I think should be removed.

See above, I would rather have the current documentation reflect the actual code that folks will download.

**Comment by frankyn** [comment]
cc: @theacodes

**Comment by theacodes** [comment]
I would hold off on any work here until our documentation plan is finalized.

**Comment by frankyn** [comment]
@coryan, can you block for now?

**Comment by coryan** [comment]
Sure, I am really efficient at "not working". Please note that the documentation is automatically generated and pushed to github.io ([here](https://googlecloudplatform.github.io/google-cloud-cpp/latest/bigtable/index.html), and [here](https://googlecloudplatform.github.io/google-cloud-cpp/latest/storage/files.html)) on each commit to `master`.

**Comment by theacodes** [comment]
Cool. Totally fine with charging ahead on the docs for individual packages, I just wouldn't sink too much time into making them all be one big giant docset.

**Comment by coryan** [comment]
@theacodes @JustinBeckwith @frankyn have you finalized your documentation plan? Can I work towards fixing this issue or is it still too early?

**Comment by frankyn** [comment]
@theacodes is out, we will need to wait until she's back to get more information.

**Comment by frankyn** [comment]
Apologies, I let this one slip through the cracks. 
@theacodes, do you mean keeping cloud.google.com docs and Doxygen docs separated OR not merging all client libraries as a single Doxygen docset to make it easier to integrate into cloud.google.com?

**Comment by theacodes** [comment]
both.

> do you mean keeping cloud.google.com docs and Doxygen docs separated

yes.

> not merging all client libraries as a single Doxygen docset to make it easier to integrate into cloud.google.com?

yes.

**Comment by frankyn** [comment]
ty!

**Comment by coryan** [comment]
@tmatsuo I take it that your design makes this feature request obsolete and we should then close it?

**Comment by tmatsuo** [comment]
Yeah, I think we can close this now, but let me clarify. What was the original motivation for merging the sub components?

**Comment by JustinBeckwith** [comment]
As of today, we do not have a generalized strategy for language focused landing pages.  @theacodes is working on a roadmap for googleapis.dev, where I would expect this to be a little more solidified :)

**Comment by coryan** [comment]
I am going to close this, I am not sure it serves any purpose anymore. When we have a better plan for documentation in `googleapis.dev` we are reopen this or open the right bugs.
