### ISSUE TITLE
We should delete or maintain the coverity-scan build

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#6371]
We have a script that runs coverity over our code and uploads the results to https://scan.coverity.com/projects/googlecloudplatform-google-cloud-cpp

![image](https://user-images.githubusercontent.com/9447643/115972560-2054e000-a51d-11eb-8af2-adc345bb228b.png)

It looks like we haven't run the build in a while. I can't run the build because I don't have the coverity tools installed and I'm not sure the build works. Our script is here: https://github.com/googleapis/google-cloud-cpp/blob/master/ci/coverity-scan.sh

I think we want to minimize the bit-rotting scripts in the repo, so I think we should either:

A. Delete the script, if we don't use it.
B. Move the [`coverity-scan.sh`](https://github.com/googleapis/google-cloud-cpp/blob/master/ci/coverity-scan.sh) script to a cleaned-up `ci/cloudbuild/builds/coverity-scan.sh` script along with a Dockerfile that has all the right tools so that any of us could run the build

NOTE: we have other builds, like [`scan-build`](https://github.com/googleapis/google-cloud-cpp/blob/master/ci/cloudbuild/builds/scan-build.sh) that don't have triggers and require us to manually invoke them. I think that's OK, fwiw.... and we always have the option to add triggers and run these builds all the time if they prove useful

If we use the script I vote for (B). If we don't, I vote for (A).

**Comment by coryan** [comment]
I have deleted the branch.  It was an attractive nuisance.

**Comment by devjgm** [comment]
Actually, I'm not sure what branch was deleted. Do we want to delete https://github.com/googleapis/google-cloud-cpp/blob/main/ci/coverity-scan.sh or do we still want to hang on to it in case we ever decide to run it?

**Comment by coryan** [comment]
Let's delete that too.
