### ISSUE TITLE
[Q] How do I make a `gcs::Client` from an access token and project ID?

### ISSUE THREAD

**Issue by SamuelMarks** [googleapis/google-cloud-cpp#6394]
I've found many useful functions for this, but they all seem to be marked internal, like https://github.com/googleapis/google-cloud-cpp/blob/ca13e51/google/cloud/internal/credentials.cc#L33

I mean, I could try constructing a [`RefreshingCredentialsWrapper`](https://github.com/googleapis/google-cloud-cpp/blob/ca13e51/google/cloud/storage/oauth2/refreshing_credentials_wrapper.h#L34) and making that a [`oauth2::Credentials`](https://github.com/googleapis/google-cloud-cpp/blob/ca13e51/google/cloud/storage/oauth2/credentials.h#L60) by I don't know, inheriting it and filling in what it expects? - Or maybe hacking to conform to an interface of one of its existent implementors?

---

So am I meant to hack something like this?

```c++
class OutOfBandCredentials: public google::cloud::storage::oauth2::Credentials {
public:
    OutOfBandCredentials(const char *access_token): access_token(access_token) {}

    google::cloud::StatusOr<std::string> AuthorizationHeader() override {
        return "Authorization: Bearer " + std::string(access_token);
    }

private:
    const char *access_token;
};

int write_to_bucket(const char *access_token, const char *project_id, const char *bucket_name) {
    google::cloud::storage::Client client = google::cloud::storage::Client(
            std::make_unique<OutOfBandCredentials>(OutOfBandCredentials(access_token))
    );
    auto writer = client.WriteObject(bucket_name, "quickstart.txt");
    writer << "Hello World!";
    writer.Close();
    if (writer.metadata()) {
        std::cout << "Successfully created object: " << *writer.metadata() << "\n";
    } else {
        std::cerr << "Error creating object: " << writer.metadata().status()
                  << "\n";
        return EXIT_FAILURE;
    }
    return EXIT_SUCCESS;
}
```

It gives `Error creating object: Permanent error in CreateResumableSession:`
```json
{
  "error": {
    "code": 401,
    "message": "Invalid Credentials",
    "errors": [
      {
        "message": "Invalid Credentials",
        "domain": "global",
        "reason": "authError",
        "locationType": "header",
        "location": "Authorization"
      }
    ]
  }
}
````
> [UNAUTHENTICATED]

**Comment by coryan** [comment]
Good questions.  **TL;DR:** the classes you want are not ready yet, but will be "Real Soon Now":tm:

A little longer of an answer, I think your class is basically Okay (I would have used a `std::string access_token_;` member variable, but meh). How did you fetch the access token?  I have a similar class that (I think) works, we even have a test:

https://github.com/googleapis/google-cloud-cpp/blob/0f25e284d1fc3530108ce604a4cdbee96b28a292/google/cloud/storage/tests/unified_credentials_integration_test.cc#L99

### The long version

* We are working towards a unified set of authentication primitives that work for both gRPC and REST (really just GCS at this point) libraries.
* The `google::cloud::internal::Credentials` class and its factory functions you discovered will fill that role.
* The work will take a while, most likely all this quarter and parts of next quarter.
* We are doing this incrementally
* The APIs are changing a lot as we figure things out (see #6387 and #6310 for recent changes), so we don't want them as "public" yet.
* We will move the classes out of `google::cloud::internal::` as soon as we think they are stable.

Until then, creating your own class is the only supported solution. Any of the types currently in `*internal::` can change without notice.

**Comment by SamuelMarks** [comment]
Thanks for the feedback and insights as to your roadmap.

---

Not sure why my code isn't working then, I also tried stubbing in:
```c++
#include <iostream>
#include <utility>
#include <google/cloud/storage/oauth2/credential_constants.h>
#include <google/cloud/storage/oauth2/service_account_credentials.h>
#include <google/cloud/storage/client.h>

class OutOfBandCredentials: public google::cloud::storage::oauth2::Credentials {
public:
    explicit OutOfBandCredentials(
            const char *access_token,
            google::cloud::storage::oauth2::ServiceAccountCredentialsInfo info)
            : access_token(access_token), info_(std::move(info)) {}

    google::cloud::StatusOr<std::string> AuthorizationHeader() override {
        return "Authorization: Bearer " + std::string(access_token);
    }

    google::cloud::StatusOr<std::vector<std::uint8_t>> SignBlob(
            google::cloud::storage::SigningAccount const& signing_account,
            std::string const& blob) const override {
        if (signing_account.has_value() &&
            signing_account.value() != info_.client_email ||
            true /* TODO */
            ) {
            return google::cloud::Status(google::cloud::StatusCode::kInvalidArgument,
                          "The current_credentials cannot sign blobs for " +
                          signing_account.value());
        }
        /* return google::cloud::storage::oauth2::internal::SignStringWithPem(
                         blob, info_.private_key,
                         google::cloud::storage::oauth2::JwtSigningAlgorithms::RS256); */
    }

private:
    const char *access_token;
    google::cloud::storage::oauth2::ServiceAccountCredentialsInfo info_;
};

int write_to_bucket(const char *access_token, const char *project_id, const char *bucket_name) {
    google::cloud::storage::Client client = google::cloud::storage::Client(
            std::make_unique<OutOfBandCredentials>(
                    OutOfBandCredentials(
                            access_token,
                            google::cloud::storage::oauth2::ServiceAccountCredentialsInfo{/* TODO */})
            )
    );
    /* previous code from original question goes here */
}
```

---

To answer how I am getting the authentication token (access token) it's via #6291, namely https://github.com/SamuelMarks/oauth2/blob/47830ad/cpp/src/main_google.cpp#L24-L101

PS: I can cheat and include `internal` namespace code in my code by using the full `#include`… right?

**Comment by coryan** [comment]
shhhh ... if you don't tell me you are cheating I cannot catch you 😁

**Comment by SamuelMarks** [comment]
xD

Oh on a slightly unrelated note I started hacking this together:

```c++
namespace Compute {
    struct Deprecated {
        /*enum*/std::string state;
        std::string replacement;
        std::string deprecated;
        std::string obsolete;
        std::string deleted;
    }

    struct Zone {
        std::string id;
        std::string creationTimestamp;
        std::string name;
        std::string description;
        /*enum*/ std::string status;
        /*deprecated*/ Deprecated deprecated;
        std::string region;
        std::string selfLink;
        std::string availableCpuPlatforms: std::string[];
        bool supportsPzs;
        std::string kind;
    };

    class Zones {
    public:
        Zones(const char *project_id, const char *access_token): project_id(project_id), access_token(access_token) {}

        std::vector<Zone> list() {
            /* https://cloud.google.com/compute/docs/reference/rest/v1/zones/list */
            /* GET https://compute.googleapis.com/compute/v1/projects/{project}/zones */
            return make_request(
                    static_cast<const std::ostringstream&>(
                            std::ostringstream() <<
                                                 "/v1/projects/" << project_id << "/zones").str()
        }
    private:
        const char *project_id, *access_token;
        /* TODO: Make this a template and parse the JSON into a struct or a vector of structs) */
        Request make_request(const std::string &path, const std::string &verb) {
            const Url url = Url("https://compute.googleapis.com/compute" + path);
            Request req;
            req.verb = verb;
            req.uri.protocol = "HTTP";
            req.uri.protocol_version = "1.0";
            req.uri.use_ssl = true;
            req.uri.port = 443;
            req.uri.host = u.domain;
            req.uri.path = u.path;
            req.uri.querystring = u.encoded_querystring();
            req.uri.fragment = u.fragment;
            req.headers.push_back("HOST: "+req.uri.host);
            req.headers.push_back("Authorization: Bearer " + std::string(access_token));
            return req;
        }
    };
};
};
```

I assume I'm meant to throw this whole thing away and generate the entire API using one of your fancy schemes? [pun intended]

I.e., generate the whole thing and then create a small "friendly" interface atop it for people to easily work from

Happy to add Compute support to google-cloud-cpp (time permitting)

**Comment by coryan** [comment]
> I assume I'm meant to throw this whole thing away and generate the entire API using one of your fancy schemes? [pun intended]

If I was going to do this, yes, I would probably generate the API from the discovery doc:

https://developers.google.com/discovery
https://developers.google.com/discovery/v1/getting_started

In this case the JSON description would be at:

https://www.googleapis.com/discovery/v1/apis/compute/v1/rest

> Happy to add Compute support to google-cloud-cpp (time permitting)

We have no specific plans to implement a client library for compute, it does not seem like something folks want to do from C++: run C++ in GCE VMs? Absolutely. Use C++ to create and manage GCE VMs? No demand so far, but that does not mean it wouldn't get used.

If we were to host such a contribution we would need to discuss the surface API in detail with you first, maybe through a design document in Google doc.  I would expect this to take a while, compute has a large surface (the discovery doc is 10x the size of the storage library, gulp).

We would then need to discuss the implementation in a separate document. I would expect the second to go fast, as we would model this implementation on the other libraries.

/cc: @devjgm FYI

**Comment by coryan** [comment]
I think the original question in this thread is answered. If you have other questions please open a new issue or start a [discussion](https://github.com/googleapis/google-cloud-cpp/discussions)

**Comment by SamuelMarks** [comment]
@coryan Weren't we going to discuss the compute implementation? - Or are you saying that should become a new issue/discussion?

**Comment by coryan** [comment]
>  Weren't we going to discuss the compute implementation? - Or are you saying that should become a new issue/discussion?

Yes, let's separate the discussion.  That is going to be a bit long.
