### ISSUE TITLE
`cmake-oldest-deps` GCS tests failed

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#6399]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=global/8e8ddfbf-bec5-4ae9-8f77-d1f4c7537037;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/6397/629292ed28bcb099d7c2e0b727777d40c5048afd/fedora-cmake-oldest-deps/log-8e8ddfbf-bec5-4ae9-8f77-d1f4c7537037.txt

```
...
12/61 Test #389: storage_object_file_multi_threaded_test .........................***Failed  307.60 sec
Running main() from gmock_main.cc
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from ObjectFileMultiThreadedTest
[ RUN      ] ObjectFileMultiThreadedTest.Download
Create test objects . DONE
Performing downloads +.+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ DONE
Delete test objects .../../google/cloud/storage/tests/object_file_multi_threaded_test.cc:136: Failure
Value of: status
Expected: code is equal to OK and message is anything
  Actual: Retry policy exhausted in DeleteObject: EasyPerform() - CURL error [28]=Timeout was reached [DEADLINE_EXCEEDED] (of type google::cloud::v1::Status), with a code that isn't equal to OK, but a message that is anything
../../google/cloud/storage/tests/object_file_multi_threaded_test.cc:136: Failure
Value of: status
```

**Comment by devjgm** [comment]
It looks like all invocations of this build have failed. I disabled the PR and CI triggers for this build until we can figure it out.

![image](https://user-images.githubusercontent.com/9447643/116431065-6956ae00-a815-11eb-9b7e-bd44ea9b7be8.png)

To re-enable, just click the 3-dots and select "Enable"

**Comment by coryan** [comment]
I must have changed something after I tested and before merging, because it passed for me a couple of times. FWIW, this reproduces locally with `--docker`.
