### ISSUE TITLE
[GCB] Enable integration tests when run in --docker

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#6410]
Currently the GCB builds can only run integration tests when run in GCB with `--project cloud-cpp-testing-resources`, because that's the project and account w/ all the right permissions. However, our dev cycle is slow if we're iterating on an integration test and always waiting 5+ minutes for the integration tests to run in that account.

We want to be able to run integration tests locally in docker.

Idea:
* We could create a separate service account (in cloud-cpp-testing-resources) that has all the right permissions to run integration tests.
* We create some keys on that account that we can download and use locally
* We somehow (I think this may work, but need to tests) enable our gcloud ADC use the SA credential
* We need to make sure this SA credential works w/in the docker container
* voila, integration tests work w/in a local docker container ??? 

Note:
* We'll need to rotate the SA keys periodically. That's OK. 
* This SA will *only* be used for local docker tests -- nothing else.

**Comment by coryan** [comment]
Not sure if this works, but worth a try maybe. Mount `$HOME/.config/gcloud` into the corresponding Docker image directory. Then the build scripts could run with whatever ADC the developer has stored there.  If they are an owner for the integration test project (and all of us are) they should have all the privileges needed to run the integration tests.  I think maybe the Bazel builds would need some tweaks to get access to those files, not sure?

That would eliminate the need to download service account keys, create separate accounts, etc.

**Comment by devjgm** [comment]
I love that idea. I actually tried this a few weeks ago and couldn't get it work. I came to the conclusion that our "owner" accounts still didn't have the right permissions. But maybe I was confused maybe something else was broken at the time.

I'll look into this again, because it would be the easiest and nicest solution if it works. Thanks for suggesting!

**Comment by devjgm** [comment]
When trying to run the bazel integration tests as me in docker, I get the following error:

```
================================================================================
FAIL: //google/cloud/iam/samples:grpc_credential_types (see /h/.cache/bazel/_bazel_jgm/eab0d61a99b6696edb3d2aff87b585e8/execroot/com_github_googleapis_google_cloud_cpp/bazel-out/k8-fastbuild/testlogs/google/cloud/iam/samples/grpc_credential_types/test.log)
INFO: From Testing //google/cloud/iam/samples:grpc_credential_types:
==================== Test output for //google/cloud/iam/samples:grpc_credential_types:

Running UseAccessToken() example
Standard exception raised: Error in non-idempotent operation GenerateAccessToken: The caller does not have permission
2021-04-29T13:26:50.278632325Z [INFO] <140353785537728> Enabled logging for gRPC calls (google/cloud/iam/internal/iam_credentials_stub_factory.cc:48)
2021-04-29T13:26:50.279812706Z [DEBUG] <140353785537728> GenerateAccessToken() << name: "projects/-/serviceAccounts/kokoro-run@cloud-cpp-testing-resources.iam.gserviceaccount.com" scope: "https://www.googleapis.com/auth/cloud-platform" lifetime { seconds: 60 }  (./google/cloud/internal/log_wrapper.h:86)
2021-04-29T13:26:50.513507172Z [DEBUG] <140353785537728> GenerateAccessToken() >> status=The caller does not have permission [PERMISSION_DENIED] (./google/cloud/internal/log_wrapper.h:89)
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error in non-idempotent operation GenerateAccessToken: The caller does not have permission
================================================================================
```

**Comment by coryan** [comment]
The permissions to do that are documented here:

https://cloud.google.com/iam/docs/reference/credentials/rest/v1/projects.serviceAccounts/generateAccessToken

That permission is included in the `roles/iam.serviceAccountTokenCreator` role.  Try giving yourself that role for the service account in question and see if that works.

**Comment by devjgm** [comment]
To my surprise that one credential seems to do the trick. I'm surprised because we, with "Owner" role, seem to be able to do everything, like access GCS, spanner, etc, but why did "Owner" not give us that one "generateAccessToken" permission?  Not sure.

But anyway, yay! This seems like an excellent solution to running integration tests in docker.
