### ISSUE TITLE
[renovate] consolidate PRs for Docker and Bazel

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#6432]
renovate bot groups all the updates for the "same dependency" into a single PR. As best I can tell, the name of the dependency is used to determine if two changes are for the same dependency.

The dependencies in Dockerfiles are named using the regex matcher:

https://github.com/googleapis/google-cloud-cpp/blob/17ee70bc4506e9afc7d0e6fe40566957dfeca281/.github/renovate.json#L11

They allow a certain amount of rewriting:

https://docs.renovatebot.com/configuration-options/#depnametemplate

With examples here:

https://docs.renovatebot.com/modules/manager/regex/#advanced-capture

**Comment by devjgm** [comment]
This would be a cool cleanup.

**Comment by coryan** [comment]
I am going to mark this as closed.  @dbolduc fixed a bunch of these.  If we need this in more cases we should open more specific issues.
