### ISSUE TITLE
Bucket list gives garbage names (ListBuckets, i.e., google::cloud::storage::ListBucketsReader)

### ISSUE THREAD

**Issue by SamuelMarks** [googleapis/google-cloud-cpp#6460]
**What component of `google-cloud-cpp` is this related to?**
`google/cloud/storage`

**Describe the bug**
```
Bucket name: �P�� ("�P��")	# of labels: 140676117339136
```

**To Reproduce**
```c++
google::cloud::storage::ListBucketsReader bucketsReader = client.ListBuckets();
std::vector<const char*> bucketNames;
for (const auto &bucket : bucketsReader) {
    std::cout << "Bucket name: " << bucket->name() << " (\"" << bucket->name().c_str() << "\")\t"
              << "# of labels: " << bucket->labels().size() << std::endl;
}
```

**Expected behavior**
Names

**Operating system:**
macOS 11.3 (20E232)

**What compiler and version are you using?**
```
Apple clang version 12.0.5 (clang-1205.0.22.9)
Target: x86_64-apple-darwin20.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**What version of `google-cloud-cpp` are you using?**
1.26.0

**Additional context**
Do I need to set the encoding of my stdout to something?

**Comment by coryan** [comment]
Did you check if `bucket.ok()` was true before using it?  The value type of a `ListBucketsReader` is `StatusOr<Bucket>`, if the `Status` is not `ok` then reading the bucket attributes is UB.

I would have written the loop as:

```cc
std::vector<std::string> bucketNames; // beware lifetime issues!
for (auto bucket : client.ListBuckets()) {
  if (!bucket) throw std::runtime_error(bucket.status().message());
  bucketNames.push_back(bucket->name());
}
```

**Comment by remyabel** [comment]
The two things that stick out to me are `std::vector<const char*> bucketNames;` and `bucket->name().c_str()`. Is there a reason you're not using `std::string`? I don't see `bucketNames` used anywhere in your example code, but if the original string is modified/destroyed then `c_str()` is no longer valid and can return garbage.

**Comment by SamuelMarks** [comment]
@remyabel Oh I'm doing some C compatibility things.

@coryan Thanks for that, that pointed out the error:
```
Permanent error in ListBuckets: {
  "error": {
    "code": 400,
    "message": "Invalid argument",
    "errors": [
      {
        "message": "Invalid argument",
        "domain": "global",
        "reason": "invalid"
      }
    ]
  }
}
```

How do I debug further?

My C++ code:
```c++
#include <iostream>
#include <utility>

#include <google/cloud/storage/oauth2/service_account_credentials.h>
#include <google/cloud/storage/client.h>
#include <google/cloud/storage/version.h>

class OutOfBandCredentials: public google::cloud::storage::oauth2::Credentials {
public:
    explicit OutOfBandCredentials(
            const char *google_access_token,
            google::cloud::storage::oauth2::ServiceAccountCredentialsInfo info)
            : google_access_token(google_access_token), info_(std::move(info)) {}

    google::cloud::StatusOr<std::string> AuthorizationHeader() override {
        return "Authorization: Bearer " + std::string(google_access_token);
    }

#if __cplusplus >= 201703L
    [[nodiscard]]
#endif
    google::cloud::StatusOr<std::vector<std::uint8_t>> SignBlob(
            google::cloud::storage::SigningAccount const& signing_account,
            std::string const& blob) const override {
        if ((signing_account.has_value() &&
                (signing_account.value() != info_.client_email)) ||
            true /* TODO */
            ) {
            return google::cloud::Status(google::cloud::StatusCode::kInvalidArgument,
                          "The current_credentials cannot sign blobs for " +
                          signing_account.value());
        }
        /* return google::cloud::storage::oauth2::internal::SignStringWithPem(
                         blob, info_.private_key,
                         google::cloud::storage::oauth2::JwtSigningAlgorithms::RS256); */
    }

private:
    const char *google_access_token;
    google::cloud::storage::oauth2::ServiceAccountCredentialsInfo info_;
};

void storage(const char *google_access_token)  {
    google::cloud::storage::Client client = google::cloud::storage::Client(
            std::make_unique<OutOfBandCredentials>(
                    OutOfBandCredentials(
                            google_access_token,
                            google::cloud::storage::oauth2::ServiceAccountCredentialsInfo{/* TODO */})
            )
    );
    google::cloud::storage::ListBucketsReader bucketsReader = client.ListBuckets();
    std::vector<const char*> bucketNames;
    for (const auto &bucket : bucketsReader) {
        /* bucket->label */
        if (!bucket) {
            std::cerr << bucket.status().message().c_str() << std::endl;
            exit(EXIT_FAILURE);
        }
        std::cout << "Bucket name: " << bucket->name() << " (\"" << bucket->name().c_str() << "\")\t"
                  << "# of labels: " << bucket->labels().size() << std::endl;
        bucketNames.push_back(strdup(bucket->name().c_str()));
    }
    /* rest removed for brevity */
}
```

**Comment by coryan** [comment]
Could you be missing the default project?  The `ListBuckets()` function needs the project initialized (it is one of the few operations that does).  The client library picks your default project from the `GOOGLE_CLOUD_PROJECT` environment variable, or from the `project_id()` parameter in the `ClientOptions()`.

If you prefer to use an explicit project, consider `ListBucketsForProject()` instead.

**Comment by remyabel** [comment]
This is not related to the error message, but continuing off of the original problem. To avoid further issues, I would change `bucketNames` to be a `std::vector<std::string>` and then only using `c_str()` when passing it to the C API. This will avoid the need of `strdup` (and having to remember to free the memory/potential ownership issues). You also don't need `c_str()` when printing the bucket names with `std::cerr/std::cout`. So the loop would look like Carlos' suggested code, then something like `c_api_function(bucket_name.c_str())`.

**Comment by coryan** [comment]
> This is not related to the error message, but continuing off of the original problem. To avoid further issues, I would change `bucketNames` to be a `std::vector<std::string>` and then only using `c_str()` when passing it to the C API.

I suspect @SamuelMarks needs to pass the array of strings to a C API, so he needs `bucketNames.data()` to be `char const**` or some such.  Better him than me 😨

**Comment by SamuelMarks** [comment]
Yeah I do the whole `std::copy` thing after a `malloc` (although I could always loop over and `strdup` instead). Anyway the garbage content seems to be from the 400 `Invalid argument` error.

Any idea how to resolve?

**Comment by coryan** [comment]
See above regarding the default project.

**Comment by SamuelMarks** [comment]
Hmm well the `ListBucketsForProject` worked and I'm just debugging the `CreateBucketForProject`.

I'm getting a segmentation fault from this:

```c++
const google::cloud::StatusOr<google::cloud::storage::BucketMetadata> bucket =
                _client.CreateBucketForProject(config->google_bucket_name, config->google_project_id,
                                              google::cloud::storage::BucketMetadata()
                                              .set_location(config->google_zone)
                                              .set_storage_class(google::cloud::storage::storage_class::Regional()));
```

(from your old docs https://googleapis.dev/cpp/google-cloud-storage/0.5.0/index.html )

I tried with `strdup` everything to no avail

**Comment by remyabel** [comment]
Hard to say, but likely `config` is null and deferencing a null pointer tends to result in crashes. Can you generate a backtrace?

> I tried with strdup everything to no avail

`strdup` should not be necessary here. In the above code, you would be creating a memory leak if you use `strdup`. If you are passing a `std::string` or `const char*` to `set_location()` et al. it will already be automatically copied.

**Comment by SamuelMarks** [comment]
@remyabel With my debugger I've confirmed that `config` is not null and is popular with the right contents.

Here's a self-contained example:
```c++
#include <iostream>
#include <utility>

#include <google/cloud/storage/oauth2/service_account_credentials.h>
#include <google/cloud/storage/client.h>
#include <google/cloud/storage/version.h>

class OutOfBandCredentials: public google::cloud::storage::oauth2::Credentials {
public:
    explicit OutOfBandCredentials(
            const char *google_access_token,
            google::cloud::storage::oauth2::ServiceAccountCredentialsInfo info)
            : google_access_token(google_access_token), info_(std::move(info)) {}

    google::cloud::StatusOr<std::string> AuthorizationHeader() override {
        return "Authorization: Bearer " + std::string(google_access_token);
    }

#if __cplusplus >= 201703L
    [[nodiscard]]
#endif
    google::cloud::StatusOr<std::vector<std::uint8_t>> SignBlob(
            google::cloud::storage::SigningAccount const& signing_account,
            std::string const& blob) const override {
        if ((signing_account.has_value() &&
                (signing_account.value() != info_.client_email)) ||
            true /* TODO */
            ) {
            return google::cloud::Status(google::cloud::StatusCode::kInvalidArgument,
                          "The current_credentials cannot sign blobs for " +
                          signing_account.value());
        }
        /* return google::cloud::storage::oauth2::internal::SignStringWithPem(
                         blob, info_.private_key,
                         google::cloud::storage::oauth2::JwtSigningAlgorithms::RS256); */
    }

private:
    const char *google_access_token;
    google::cloud::storage::oauth2::ServiceAccountCredentialsInfo info_;
};


void storage(const char *project_id, const char *bucket_name, const char *zone, const char *access_token)  {
        google::cloud::storage::Client _client = google::cloud::storage::Client(
                std::make_unique<OutOfBandCredentials>(
                        OutOfBandCredentials(
                                access_token,
                                google::cloud::storage::oauth2::ServiceAccountCredentialsInfo{/* TODO */})
                )
        );
        const google::cloud::StatusOr<google::cloud::storage::BucketMetadata> bucket =
                _client.CreateBucketForProject(strdup(bucket_name), strdup(project_id),
                                              google::cloud::storage::BucketMetadata()
                                              .set_location(strdup(zone))
                                              .set_storage_class(google::cloud::storage::storage_class::Regional()));
}
```

**Comment by coryan** [comment]
A stack trace would be most useful, it is not clear where this is crashing.

A few observations:

```cc
class OutOfBandCredentials: public google::cloud::storage::oauth2::Credentials {
public:
    explicit OutOfBandCredentials(
            const char *google_access_token,
            google::cloud::storage::oauth2::ServiceAccountCredentialsInfo info)
            : google_access_token(google_access_token), info_(std::move(info)) {}
```

Note that here you are initializing `google_access_token` with itself. That does not seem safe.  Consider using a trailing `_` consistently on member variables to avoid this problem...  Also, note that you are using the `const char *google_access_token` member variable as a `std::string` every time:

```cc
    google::cloud::StatusOr<std::string> AuthorizationHeader() override {
        return "Authorization: Bearer " + std::string(google_access_token);
    }
```

Consider making the variable a `std::string` and saving yourself the extra allocations in each call to `AuthorizationHeader()`. Maybe pre-compute the full header while you are at it.

If I may: I understand the need to interface with C steers you towards unsafe types like `char const*`, and `char const**`. In your shoes I would avoid them except when strictly needed, life is easier with C++ abstractions.

In addition your code reads:

```cc
         .set_location(strdup(zone))
         .set_storage_class(google::cloud::storage::storage_class::Regional()));
```

As you probably know the call to `strdup()` here is not needed. But the more important bit is the `zone`: regional buckets (as you are trying to create here) live in a region, make sure you are passing a value like `us-central1` (a region) and not like `us-central1-a` (a zone).

**Comment by SamuelMarks** [comment]
Good point. Okay I've rewritten it to:
```c++
class OutOfBandCredentials: public google::cloud::storage::oauth2::Credentials {
public:
    explicit OutOfBandCredentials(
            const std::string &google_access_token,
            google::cloud::storage::oauth2::ServiceAccountCredentialsInfo info)
            : authorisation_header("Authorization: Bearer " + google_access_token), info_(std::move(info)) {}

    google::cloud::StatusOr<std::string> AuthorizationHeader() override {
        return authorisation_header;
    }

#if __cplusplus >= 201703L
    [[nodiscard]]
#endif
    google::cloud::StatusOr<std::vector<std::uint8_t>> SignBlob; /* omitted for brevity */

private:
    const std::string authorisation_header;
    const google::cloud::storage::oauth2::ServiceAccountCredentialsInfo info_;
};
```

In terms of those `strdup` that was just me debugging the `SIGSEGV`.

So I'm still getting that error. Can you replicate it with my code?

**Comment by remyabel** [comment]
It would probably be faster to provide a [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) and a backtrace. It is hard to tell from the code given what the issue is. I would test your code but it takes time to compile the library and to run a test program against the emulator, so I will do that eventually later.

**Comment by coryan** [comment]
@SamuelMarks you mentioned earlier:

> With my debugger I've confirmed that `config` is not null and is popular with the right contents.

If you can run this with a debugger, presumably you can get a stack trace at the point where it SEGVs?  What does it show?

**Comment by coryan** [comment]
Changed the type because this has turned into a question rather than a bug report.

**Comment by SamuelMarks** [comment]
> presumably you can get a stack trace at the point where it SEGVs

No I can only debug earlier (incl into the google-cloud-cpp code); but I can't go inside where this occurs, it drops to assembly then back to my code saying memory access violation

**Comment by coryan** [comment]
I copied your code into a minimal program (tarball attached) and it does not crash for me, it runs successfully.  I encourage you to:

- Try to create a self-contained, minimal program that reproduces the problem, we can try to help you based on that.
- Most debuggers can show you a stack trace even after a crash in assembly, maybe that can help.
- Run your program with a memory debugger, like valgrind, or compile it with something like AddressSanitizer.

I ran the program with:

```shell
./cmake-out/vscode/main coryan-test coryan-test-bucket-i0 us-central1 "$(gcloud auth print-access-token)"
```

and it created a bucket:

```shell
gsutil ls -l -b gs://coryan-test-bucket-i0
gs://coryan-test-bucket-i0/

echo $?
0
```

[repro-6460.tar.gz](https://github.com/googleapis/google-cloud-cpp/files/6448547/repro-6460.tar.gz)

**Comment by SamuelMarks** [comment]
Thanks experimenting with that option now. BTW: Are you on Linux or macOS?

```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==37179==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7fff203ec552 bp 0x7ffeebb995a0 sp 0x7ffeebb995a0 T0)
==37179==The signal is caused by a READ memory access.
==37179==Hint: address points to the zero page.
    #0 0x7fff203ec552 in _platform_strlen+0x12 (libsystem_platform.dylib:x86_64+0x1552)
    #1 0x106095741 in wrap_strdup+0x41 (libclang_rt.asan_osx_dynamic.dylib:x86_64h+0x43741)
    #2 0x1040e7906 in storage cloud_bucket.cpp:115
    #3 0x104069bac in config_gui config_gui.c:97
    #4 0x1040692f5 in main main.c:7
    #5 0x7fff203c4f3c in start+0x0 (libdyld.dylib:x86_64+0x15f3c)

==37179==Register values:
rax = 0x0000000106d6bae4  rbx = 0x00007ffeebb9b180  rcx = 0x0000000000000000  rdx = 0x0000000000000000  
rdi = 0x0000000000000000  rsi = 0x0000000000000000  rbp = 0x00007ffeebb995a0  rsp = 0x00007ffeebb995a0  
 r8 = 0xf7d82fcde5930004   r9 = 0x0000000000000050  r10 = 0x00000fffdd7735c0  r11 = 0x00001fffdd773610  
r12 = 0x00007ffeebb9a490  r13 = 0x00007ffeebb9a4b0  r14 = 0x0000000000000000  r15 = 0x00007ffeebb9a470  
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (libsystem_platform.dylib:x86_64+0x1552) in _platform_strlen+0x12
==37179==ABORTING

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

**Comment by coryan** [comment]
Seems like the problem is fixed 🎉   🎉   I was testing on Linux for whatever it is worth.
