### ISSUE TITLE
[GCB] Make Fedora version configurable

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#6502]
## What?

I want to make the Fedora version used by each build configurable, using a flag for `build.sh` or a substitution for the triggers.

## Why?

Because when updating Fedora sometimes we need to keep one or more builds behind.  Right now this is all the Bazel+GCC builds, as BoringSSL does not compile with GCC 11 and Bazel.

## Any alternatives?

We could move some of those builds to a different distro, one of the Ubuntus for example, but that is (probably) more confusing.

We could wait until BoringSSL is ready. But we will have this problem on every update, and updating all the builds in sync will always be problematic.

We could use a more stable distro for our builds, e.g., one of the Ubuntu LTS releases.  Those are typically stable over 5 years.  I have never written this down, but I think Fedora offers better tradeoffs:

- The releases are stable for a year, which means the development tools are never "too old".
- There are six months of overlap between "current" and "latest", which gives us time to update.
- We are *forced* to update after a year, which means we keep up with the current compiler releases.
- It includes a lot of the development tools (and dependencies) we need.

I think the work with take 2 or 3 PRs, so I opened an issue.

**Comment by devjgm** [comment]
Another alternative to consider: Create separate `fedora-33.Dockerfile` and `fedora-34.Dockerfile` (etc.) dockerfiles, and use each one where appropriate.

Pros:
* Consistency w/ the existing model used for other distros, such as `ubuntu-bionic.Dockerfile`, etc.
* Doesn't add a flag to `build.sh` that only applies to certain distros but not others
* Allows us the option to vary the details of each fedora image

Cons:
* If we truly want all the steps of the fedora images to be identical except for the distro version, then having multiple Dockerfiles would cause duplication

**Comment by coryan** [comment]
> Another alternative to consider: Create separate `fedora-33.Dockerfile` and `fedora-34.Dockerfile` (etc.) dockerfiles, and use each one where appropriate.

Yup, that just occurred to me today.  Let me change the PR to do that.

**Comment by coryan** [comment]
I think this is now fixed.
