### ISSUE TITLE
Compute API implementation

### ISSUE THREAD

**Issue by SamuelMarks** [googleapis/google-cloud-cpp#6522]
**What component of `google-cloud-cpp` is this feature request for?**
https://cloud.google.com/compute/docs/reference/rest/v1

**Is your feature request related to a problem? Please describe.**
Would be nice to have this implemented.

**Describe the solution you'd like**
Maybe I'll implement it. I've been doing some work for a client, so depending on their wishes—in terms of time resources—I'll implement the first version for you.

**Describe alternatives you've considered**
FFI with another language implementation.

**Additional context**
How do you usually generate from the [discovery JSON](https://www.googleapis.com/discovery/v1/apis/compute/v1/rest)? - I'm tempted to write something myself using [LLVM](https://llvm.org)'s [LibClang](https://clang.llvm.org/doxygen/group__CINDEX.html) or [LibTooling](https://clang.llvm.org/docs/LibTooling.html) (probably the latter)…

BTW: There was initially some discussion here a fortnight ago https://github.com/googleapis/google-cloud-cpp/issues/6394

**Comment by devjgm** [comment]
One point I forgot to add: regardless of where your GCE library ends up living, if you have questions, need help, or want advice while implementing it, feel free to ask here and we'll certainly always do our best to help. We still want to help you accomplish your goals with Google Cloud and C++, even if it's not with a library that we directly provide.

**Comment by SamuelMarks** [comment]
Thanks for the design suggestions and offer of support.

In the short-term will just hand-write for a few more endpoints as per my client's wishes. Hopefully medium-term will have the time to write those code-generators, at which point I can offer the contribution back to google-cloud-cpp

[keeping this issue open for others to chime in; and if people want access to my pre-alpha code]

**Comment by remyabel** [comment]
Sure, I would like to see the pre-alpha code. If I learned anything it's that it's important to share code early so that others can chime in and avoid sinking too much time in an approach that ultimately won't work.

**Comment by SamuelMarks** [comment]
PS: Slightly offtopic, but I was finally was able to pitch this to my client's representative. Hoping to close the deal on Tuesday. There are three possibilities:

  0. [unlikely] My client wants it but won't let me *open-source 
  1. My clients wants it and will let me *open-source
  2. [likely] My client doesn't want it, so I'll *open-source in my own time (not a high priority but will get done eventually)

*open-source under the (Apache-2.0 OR MIT) license

---

Ideas for encouraging one:

  - Open-source means community will have incentive to—exist and—maintain:
    - new features
    - documentation
    - security fixes [CVE®, for example]
  - I will [likely] continue to maintain this after the project has finished, as I'll [likely] be using it for future client projects

Commercially, this means:

  - Google will feature this project (e.g., on https://github.com/googleapis/google-cloud-cpp)
  - Huge number of potential new use-cases in the multicloud world
  - Easy to interface with (because C FTW):
      - FFI
      - REST API
      - RPC APIs
      - &etc.

---

Do you have any suggestions for how I can convince them to go with funding its open-source development?

Thanks

**Comment by SamuelMarks** [comment]
Update: open-source convincing was successful, it's now online at https://github.com/offscale/google-cloud-c

TODO: automatically [re]create the bulk of this library, namely (from the [discovery JSON](https://www.googleapis.com/discovery/v1/apis/compute/v1/rest)) statically code-generate:
    - `struct`s;
    -  `free` code
    -  HTTPS calls

Not sure if the whole pipelining multiple HTTPS calls together will be in or out of scope, but that first TODO is sizeable enough. Confident that I can convince my commercial client for its development: watch this space!

**Comment by coryan** [comment]
@scotthart is working on this.

**Comment by scotthart** [comment]
The current plan is to leverage our existing C++ generator to produce a C++ Compute library. We don't intend to author or generate a C version of the library.

**Comment by coryan** [comment]
We are still working on this.

**Comment by coryan** [comment]
The first version of the full API is now part of the library.

**Comment by SamuelMarks** [comment]
Ah I see, you've done it from the Protobuf side. That works I guess. `enum class` for idempotency then a bunch of functions that return different `enum` values.  As for the regular things like getting the IP address from `AccessConfig` I'd have to look closer through your contributions as `rg -i` told me where neither `nat_ip` nor `natIP` were from d515f8f.

I assume examples are forthcoming, to do basic thinks like:
0. Create network
1. Create firewall
2. Create instance
3. Destroy instance
4. Destroy firewall
5. Destroy network

(it's obvious; albeit verbose [particular on the `struct` construction]; in my C client library for google-cloud, e.g., https://github.com/offscale/google-cloud-c/blob/9a362f7/google_cloud_c/compute/instance.h#L151)

---

From a further analysis, I suppose there's `AsyncInsertInstances`, `AsyncAddAccessConfig`, `AsyncDeleteInstance` in your stub https://github.com/googleapis/google-cloud-cpp/blob/d515f8fd/google/cloud/compute/instances/v1/internal/instances_rest_stub.h

(also I'm not sure why these APIs have been generated in such a way as to make the incompatible with C; rather than C/C++ compatible… this means we'll need a new implementation for Rust, Erlang, Swift, Java, Python, Ruby, Go, Zig, D, C#)

Anyway good to see some progress on compute API integration!

**Comment by SamuelMarks** [comment]
Ah I see, you've done it from the Protobuf side. That works I guess. Weird use of `enum class` for idempotency with those follow-up functions that return different `enum` values.  As for the regular things like getting the IP address from `AccessConfig` I'd have to look closer through your contributions as `rg -i` told me where neither `nat_ip` nor `natIP` were from d515f8f.

I assume examples are forthcoming, to do basic thinks like:

0. Create network
1. Create firewall
2. Create instance
3. Destroy instance
4. Destroy firewall
5. Destroy network

(it's obvious; albeit verbose [particular on the `struct` construction]; in my C client library for google-cloud, e.g., https://github.com/offscale/google-cloud-c/blob/9a362f7/google_cloud_c/compute/instance.h#L151)

---

From a further analysis, I suppose there's `AsyncInsertInstances`, `AsyncAddAccessConfig`, `AsyncDeleteInstance` in your stub https://github.com/googleapis/google-cloud-cpp/blob/d515f8fd/google/cloud/compute/instances/v1/internal/instances_rest_stub.h

(also I'm not sure why these APIs have been generated in such a way as to make the incompatible with C; rather than C/C++ compatible… this means we'll need a new implementation for Rust, Erlang, Swift, Java, Python, Ruby, Go, Zig, D, C#, & others)

---

Anyway good to see some progress on compute API integration!

**Comment by coryan** [comment]
You are right about Rust, Erlang, Switch, D, Zig and many other languages. Java, Python, Go, C#, Ruby, NodeJS and PHP have their own libraries:

https://cloud.google.com/compute/docs/api/libraries

I hope we never claimed that the C++ client libraries would be usable to wrap and then use from other languages.  That has never been a goal for us.

**Comment by coryan** [comment]
The library is now GA, closing.
