### ISSUE TITLE
google::cloud::StatusOr<gcs::Client>

### ISSUE THREAD

**Issue by FranceAS89** [googleapis/google-cloud-cpp#6546]
My issue regards google cloud storage.
I need to define `google:cloud:StatusOr<gcs::Client>` setting both:
- credentials from JsonFilePath without environment variable GOOGLE_APPLICATION_CREDENTIALS
- client options to give ssl root path(gcs::ClientOptions::CreateDefaultClientOptions( gcs::ChannelOptions().set_ssl_root_path(...))

Searching documentation online I havent't found any example with these requests. It is possibile to do this?

I'm using Windows 8
I compile with MSV 2019 and c++11.

**Comment by coryan** [comment]
I think you want something like this:

```cc
namespace gcs = ::google::cloud::storage;
using ::google::cloud::StatusOr;
using ::google::cloud::Status;

StatusOr<gcs::Client> F(std::string const& path, std::string const& ssl_root_path) {
  auto credentials = google::cloud::oauth2::CreateServiceAccountCredentialsFromJsonFilePath(
      path, /*scopes=*/absl::nullopt, /*subject=*/absl::nullopt,
      ChannelOptions{}.set_ssl_root_path(ssl_root_path));
  if (!credentials) return std::move(credentials).status();

  return gcs::Client(gcs::ClientOptions(*credentials));
}
```

**Comment by FranceAS89** [comment]
Thanks. I've tryed to defined in this way my client.
auto credentials = gcs::v1::oauth2::CreateServiceAccountCredentialsFromJsonFilePath(path_json, /*scopes=*/absl::nullopt, /*subject=*/absl::nullopt, gcs::ChannelOptions{}.set_ssl_root_path(path_ssl_root));
google::cloud::StatusOr<gcs::Client> client = gcs::Client(gcs::ClientOptions(*credentials));
But when I write on cloud (client->WriteObject(bucket, codice_file_L3d))I have this certificate problem
"Permanent error in CreateResumableSession: EasyPerform() - CURL error [60]=SSL peer certificate or SSH remote key was not OK [UNKNOWN]"
I don't have any problem if I use Enviroment variabile (GOOGLE_APPLICATION_CREDENTIALS) and define client 
google::cloud::StatusOr<gcs::Client> client =gcs::Client(gcs::ClientOptions::CreateDefaultClientOptions( gcs::ChannelOptions().set_ssl_root_path(path2)).value())

**Comment by coryan** [comment]
Ah, yes, I think you need to provide the `ChannelOptions` twice:

```cc
namespace gcs = ::google::cloud::storage;
using ::google::cloud::StatusOr;
using ::google::cloud::Status;

StatusOr<gcs::Client> F(std::string const& path, std::string const& ssl_root_path) {
  auto credentials = google::cloud::oauth2::CreateServiceAccountCredentialsFromJsonFilePath(
      path, /*scopes=*/absl::nullopt, /*subject=*/absl::nullopt,
      gcs::ChannelOptions{}.set_ssl_root_path(ssl_root_path));
  if (!credentials) return std::move(credentials).status();

  return gcs::Client(gcs::ClientOptions(*credentials, gcs::ChannelOptions{}.set_ssl_root_path(ssl_root_path)));
}
```

I have not tested this, so take it with a grain of salt.

**Comment by FranceAS89** [comment]
Thanks. It works!
