### ISSUE TITLE
GCB BigQuery notifier is crashing

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#6580]
![image](https://user-images.githubusercontent.com/9447643/118363364-02016380-b562-11eb-9574-5f83a5a136de.png)

The BigQuery notifiery job (https://github.com/googleapis/google-cloud-cpp/blob/main/ci/cloudbuild/notifiers/bigquery/README.md) is crashing on start up and not working. This is a [community notifier](https://github.com/GoogleCloudPlatform/cloud-build-notifiers/tree/master/bigquery) that we run to write GCB notifications to a bigquery table. It was working originally, now it's failing. I'm not sure why, and we didn't write it, it's written in golang, so I can't debug it quickly.

I'm disabling this notifier for the time being until we can get it working again. It may be easier to just rewrite this thing using the C++ functions framework.

**Comment by coryan** [comment]
s/not crashing/crashing/?

**Comment by devjgm** [comment]
yes, fixed typo.

**Comment by devjgm** [comment]
This is still happening (or, happening again):

![image](https://user-images.githubusercontent.com/9447643/119179974-9f1a3b80-ba3d-11eb-9259-70748f44800b.png)

I don't know why or what's going on w/ this notifier. But I suspect the ultimate answer is that we should stop using that one and write our own notifier in C++ following the pattern we used for our [logs](https://github.com/googleapis/google-cloud-cpp/tree/main/ci/cloudbuild/notifiers/logs) and [alerts](https://github.com/googleapis/google-cloud-cpp/tree/main/ci/cloudbuild/notifiers/alerts) notifiers.

To be clear, I think what we probably want is:

* Stop using the current BQ notifier (not ours; it's written in Go)
* Create a new table in BQ w/ the schema that we want. The schema we want likely matches the "view" we created named `cloudbuild.google_cloud_cpp_denorm`.
* Write a C++ notifier to subscribe to the GCB build notifications. It will run in Cloud Run like our other notifiers.
* It should write each notification to a new row in the table. Since we don't have a C++ BigQuery client library, we may need to see if we can do this w/ a JSON POST or something. I assume that's possible.

**Comment by devjgm** [comment]
I found the following golang stack trace in the logs:

```

2021/05/21 19:16:54 http: panic serving 169.254.8.129:39528: runtime error: invalid memory address or nil pointer dereference
goroutine 49 [running]:
net/http.(*conn).serve.func1(0xc0003c0e60)
	/usr/local/go/src/net/http/server.go:1824 +0x153
panic(0xd78aa0, 0x1592d30)
	/usr/local/go/src/runtime/panic.go:971 +0x499
main.(*bqNotifier).SendNotification(0xc0003d2d50, 0xff2320, 0xc0001cc240, 0xc000231500, 0x2928, 0x3000)
	/go-src/bigquery/main.go:238 +0x846
github.com/GoogleCloudPlatform/cloud-build-notifiers/lib/notifiers.newReceiver.func1(0xff09c0, 0xc000337260, 0xc000460200)
	/go-src/lib/notifiers/notifiers.go:448 +0x938
net/http.HandlerFunc.ServeHTTP(0xc0005e0ea0, 0xff09c0, 0xc000337260, 0xc000460200)
	/usr/local/go/src/net/http/server.go:2069 +0x44
net/http.(*ServeMux).ServeHTTP(0x15af920, 0xff09c0, 0xc000337260, 0xc000460200)
	/usr/local/go/src/net/http/server.go:2448 +0x1ad
net/http.serverHandler.ServeHTTP(0xc000337180, 0xff09c0, 0xc000337260, 0xc000460200)
	/usr/local/go/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc0003c0e60, 0xff23c8, 0xc0001cc180)
	/usr/local/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3013 +0x39b 
```

**Comment by devjgm** [comment]
fyi, the GCB folks are looking into the crash of this BQ notifier. The crash is from this line:
https://github.com/GoogleCloudPlatform/cloud-build-notifiers/blob/b77fd4368030af5b735e1bdd296fc8af63bbd6a9/bigquery/main.go#L238

```golang
		startTime, err := parsePBTime(step.Timing.StartTime)
```
And the current guess is that not all build steps have timing info, we adding some `nil` checks there may fix this crash. I don't know the first thing about golang, but that sounds reasonable/likely to me.

**Comment by devjgm** [comment]
Good news: @prabenzom submitted a few [fixes](https://github.com/GoogleCloudPlatform/cloud-build-notifiers/commit/ac220aecd2d7d8899d88fef63b21192ffe034640#diff-243269b0805de328ce233361b6a6e94d971e1d18e7727433c832fd42e4c19f28) to the BigQuery notifier and fixed the panic crashes. Yay! Thank you very much!!!

Bad news: The BQ notifier is still dropping a lot of updates. The reason seems to be that non-SUCCESS build alerts are often missing `step.Timing` information, and that causes the insert into BQ to fail

```
"E0527 00:54:23.418135       1 notifiers.go:449] failed to run SendNotification: Error inserting row into BQ: 1 row insertion failed (insertion of row [insertID: "YuH2meB46KYBgLxZNid82J1zGHU"; insertIndex: 0] failed with error: {Location: "steps[5].endtime"; Message: "Invalid datetime string \"0000-00-00 00:00:00\""; Reason: "invalid"})"
```
So it looks like our BQ data is missing info for all or most failed builds.

@prabenzom suggested inserting some default timestamp if none is present, which seems fine to me (if it results in the BQ inserts succeeding). Not sure if/when they'll have time to do this.

**Comment by devjgm** [comment]
The new issue filed for the BQ notifier dropping failed statuses is https://github.com/GoogleCloudPlatform/cloud-build-notifiers/issues/115

**Comment by devjgm** [comment]
@prabenzom fixed the issue in https://github.com/GoogleCloudPlatform/cloud-build-notifiers/commit/f246eff11f8dbe3365de0e56423c460cc94b72e2#diff-243269b0805de328ce233361b6a6e94d971e1d18e7727433c832fd42e4c19f28 **Yay!!**

Our logs now look clean, and 2500 unack'd pubsub messages are now being processed:

![image](https://user-images.githubusercontent.com/9447643/119859873-c6f91b80-bee3-11eb-9611-7ababd49f9d2.png)

So I think this issue is fixed, and I'm hopeful that our BQ data and dashboards will now be accurate.
