### ISSUE TITLE
Storage(emulator): Revise nextPageToken for iterators in emulator

### ISSUE THREAD

**Issue by cojenco** [googleapis/google-cloud-cpp#6635]
Per discussion with @frankyn , currently the nextPageToken is assigned to an empty string in "storage.xxx.list" emulator endpoints, and causes the corresponding api calls to result in an infinite loop.  

Endpoints affected include:
[`storage.buckets.list`](https://github.com/googleapis/google-cloud-cpp/blob/6f634fcfaa56dbdd6518a8bd2b5f11803bd7b3e7/google/cloud/storage/emulator/emulator.py#L109)
[`storage.objects.list`](https://github.com/googleapis/google-cloud-cpp/blob/6f634fcfaa56dbdd6518a8bd2b5f11803bd7b3e7/google/cloud/storage/emulator/emulator.py#L370)

**Comment by coryan** [comment]
If you send a PR to change the current behavior I would gladly review and merge. I will note that empty page tokens seem to be explicitly supported (even recommended):

https://google.aip.dev/158

> If the end of the collection has been reached, the next_page_token field must be empty. This is the only way to communicate "end-of-collection" to users.

**Comment by cojenco** [comment]
Thanks @coryan for the AIP link. Currently, [python-api-core](https://github.com/googleapis/python-api-core/blob/11032cf08ecc16dd252a6cda8b33b0b28ec4f4ba/google/api_core/page_iterator.py#L404) determines whether or not there are more pages with result by checking if `nextPageToken is None`. Therefore, empty page tokens causes infinite loops. So we will need to further discuss with yoshi python team on how to improve this in the long run. 

We're proposing to remove the `nextPageToken` field entirely for now in [`storage.buckets.list`](https://github.com/googleapis/google-cloud-cpp/blob/6f634fcfaa56dbdd6518a8bd2b5f11803bd7b3e7/google/cloud/storage/emulator/emulator.py#L109) and [`storage.objects.list`](https://github.com/googleapis/google-cloud-cpp/blob/6f634fcfaa56dbdd6518a8bd2b5f11803bd7b3e7/google/cloud/storage/emulator/emulator.py#L370). Inspecting the JSON API with a one-page result, there is no nextPageToken field within the response. If we remove this field `nextPageToken` in the emulator, will it cause any issues with other usages? Appreciate your input on this. Thanks!

**Comment by coryan** [comment]
> If we remove this field nextPageToken in the emulator, will it cause any issues with other usages?

I believe that should work (the CI builds will tell us otherwise). As I said above, I am happy to merge a PR changing this behavior.
