### ISSUE TITLE
Consider moving google/cloud/storage/emulator/... to a separate repo

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#6643]
https://github.com/googleapis/google-cloud-cpp/tree/main/google/cloud/storage/emulator contains an emulator for GCS written in python. It is used by this project, but I believe it's also used by other projects as well (or will be soon? maybe someone can correct me if I'm wrong). The owners of this repo (`@googleapis/cloud-cxx-owners`) do not actually own or work on this code, may not be python experts, and may not be the right people to troubleshoot issues w/ this code.

I think we probably want to move `google/cloud/storage/emulator/...` to a separate repo. 

**Who will own the new repo?** Not sure, but I'd look to @frankyn to either own it or help identify appropriate owner(s).

**How will we (and others) access the emulator?** Do other teams use it today out of this repo today? How do they do that? Maybe we can continue doing that. Or maybe it can be published in a docker image, or as a pip module, or add it to `gcloud alpha emulators`.

**When should this happen?** There's no urgency, but I'd say now would work. Later would work too if now is booked.

**What should move?** All the (python) emulator code in https://github.com/googleapis/google-cloud-cpp/tree/main/google/cloud/storage/emulator

Thoughts? @frankyn @coryan Feel free to add others who you think might have opinions.

**Comment by frankyn** [comment]
IIUC, the C++ library uses the emulator to run local Storage integration tests, is that no longer true @coryan?

**Comment by devjgm** [comment]
We do use the emulator in our GCS tests. Are we the _only_ folks who use it or do other teams/projects use this emulator as well?

**Comment by frankyn** [comment]
We are planning to use to support the retry strategy alignment project with Storage clients in other languages. Shared design doc with you.

**Comment by devjgm** [comment]
Thanks, Frank. OK, so it sounds like other teams _will_ be using the GCS emulator. Then I'm back to the original post where I think the _C++_ library repo is not the right place for the python-based GCS emulator to live. It seems like it would be better if the emulator moved to a separate repo w/ appropriate owners assigned (likely not `@googleapis/cloud-cxx-owners`), and then we will continue to _use_ the emulator just like all the other client libraries.

WDYT?

**Comment by frankyn** [comment]
I think it makes sense to split it out given we want to use it across languages. I have reservations about doing a split now because it could signal to customers that it's fully supported (which it's not but we could change that).

**Comment by devjgm** [comment]
Cool. Moving it before other libraries start depending on it living here may make things easier, but I'm happy to not push that requirement on you. Re customer, a clear and loud README that says it's unsupported etc?

**Comment by frankyn** [comment]
I'll find time for us to sync along with the Storage EM. cc: @danielduhh

**Comment by coryan** [comment]
I am actually in the process of doing this, see googleapis/storage-testbench#24
