### ISSUE TITLE
add post update task to renovate-bot so that it regenerates packaging.md

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#6657]
We have [PR's from renovate-bot](https://github.com/googleapis/google-cloud-cpp/pull/6656) that dont pass `checkers-pr`. This is because the `packaging.md` file is not touched by renovate-bot, but it is regenerated by `checkers-pr`. If a dependency in `packaging.md` is changed, the build breaks.

It looks like renovate-bot has [postUpgradeTasks](https://docs.renovatebot.com/configuration-options/#postupgradetasks) which could be promising? maybe we can use this to run `ci/generate-markdown/generate-packaging.sh > doc/packaging.md`?

**Comment by devjgm** [comment]
I'm not sure of the context in which these post upgrade tasks run, but if it's possible to have it run `ci/cloudbuild/build.sh -t checkers-pr` (maybe with `--local` or `--docker`), that would re-generate the `packaging.md` file and run the other checks, which might be helpful. However, if that's too heavyweight, regenerating just the `packaging.md` file as you described seems reasonable.

**Comment by dbolduc** [comment]
It turns out postUpgradeTasks is only applicable to self hosted configurations. (we use github app)

https://github.com/renovatebot/renovate/issues/838#issuecomment-581821049

**Comment by coryan** [comment]
Consider just adding `doc/packaging.md` as one of the files that renovate updates, just like it updated `*.Dockerfile` files.
