### ISSUE TITLE
Kokoro build timeout. Executor terminated.

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#6675]
Kokoro macOS bazel build was terminated about 2 hours after it was started. It was running `google-cloud-sdk/install.sh`.

Test Grid classifies it as a tool failure. This almost certainly has nothing to do with Cloud C++.

Log:
https://fusion2.corp.google.com/invocations/0755b7cc-d855-484f-b05c-d69bb8fefccd/targets

Last line of the log:
>╔════════════════════════════════════════════════════════════╗
>╠═ Installing: anthoscli                                    ═╣
>╚══════════════════════════════[08:24:44] Executor 269892771 is unresponsive. Build terminated.

possibly the same as #3645

**Comment by devjgm** [comment]
The publicly accessible log in ResultStore is: https://source.cloud.google.com/results/invocations/0755b7cc-d855-484f-b05c-d69bb8fefccd

(You can find this shown at the top of the fusion2 log output)

**Comment by dbolduc** [comment]
Another tool failure. This time it died while compiling our code.
https://fusion2.corp.google.com/invocations/6644229f-2e71-4bb8-8474-7ef6901c2f98/targets/

**Comment by dbolduc** [comment]
2 more. (corp links)

https://fusion2.corp.google.com/invocations/f92c4966-f2ed-49b5-885d-24221d6211ef/targets/cloud-devrel%2Fclient-libraries%2Fcpp%2Fgoogle-cloud-cpp%2Fwindows%2Fcmake-release/log

https://fusion2.corp.google.com/invocations/47759fc1-e653-4d67-83d9-77ce9cb3df0e/targets/cloud-devrel%2Fclient-libraries%2Fcpp%2Fgoogle-cloud-cpp%2Fwindows%2Fbazel-debug-2017/log

**Comment by dbolduc** [comment]
(someone else's) proposal to fix this sort of flake: b/192459282

**Comment by devbww** [comment]
https://source.cloud.google.com/results/invocations/b999bc73-3e4e-4f28-a41a-e76299385e68

**Comment by devjgm** [comment]
Closing since this has been >90 days.
