### ISSUE TITLE
release script usage of hub requires oauth token

### ISSUE THREAD

**Issue by scotthart** [googleapis/google-cloud-cpp#6682]
release/release.sh invokes `hub`, which will check for an oauth token in ~/.config/hub. Despite some version of hub prompting for username/password when ~/.config/hub is not found, these credentials are ignored. There must exists a ~/.config/hub with the proper oauth token.

**Comment by devjgm** [comment]
I think hub now requires a personal access token rather than a password. https://github.blog/2020-07-30-token-authentication-requirements-for-api-and-git-operations/
