### ISSUE TITLE
Apple M1 cmake-super build fails due to too many file descriptors

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#6683]
```console
$ ./ci/kokoro/macos/build.sh cmake-super
...
[ RUN      ] SubscriptionMessageQueueOrderingTest/SubscriptionMessageQueueOrderingTest.RespectOrderingKeysTorture/Thread1Key1000Message1000
libc++abi: terminating with uncaught exception of type std::__1::system_error: random_device failed to open /dev/urandom: Too many open files
libc++abi: terminating with uncaught exception of type std::__1::system_error: random_device failed to open /dev/urandom: Too many open files
```

The FD limit on my machine (`ulimit -n`) is 256. Increasing this to 512 allows the test to pass.

It's possible that the issue here has nothing to do with the ARM chip and maybe just has to do w/ more cores (8 on my machine) or something.

**Comment by devjgm** [comment]
This is the test that fails, when it's invoked with `message_count == 1000`, `thread_count == 1`, and `key_count == 1000`.

https://github.com/googleapis/google-cloud-cpp/blob/adb9c7f2545e7655e84eef373c4100ee00831671/google/cloud/pubsub/internal/subscription_message_queue_test.cc#L397-L488

**Comment by coryan** [comment]
Well, that is fun.  I think the offending lines are:

https://github.com/googleapis/google-cloud-cpp/blob/adb9c7f2545e7655e84eef373c4100ee00831671/google/cloud/pubsub/internal/subscription_message_queue_test.cc#L452

and

https://github.com/googleapis/google-cloud-cpp/blob/adb9c7f2545e7655e84eef373c4100ee00831671/google/cloud/pubsub/internal/subscription_message_queue_test.cc#L467

We are starting 1,000 threads and they all open `/dev/urandom` more or less at the same time.  Leaving aside the fact that I am stealing 32,000 bits of entropy for this test (😬 ).  All we need is to fetch the bits first and then feed them to each thread,  e.g.:

```cc
  auto worker = [batch_callback](std::string const& key, int count, std::random_device::result_type seed) {
    auto gen = google::cloud::internal::DefaultPRNG(seed);
    ... ...
  };
  std::vector<std::random_device::result_type> seeds(key_count);
  std::generate(seeds.begin(), seeds.end(), [&generator] { return generator(); });
  ... /* change the calls to `worker` to pull seeds from `seeds` */ ...
```

Probably even better would be to initialize a `std::sed_seq` with just a few bits of entropy (maybe 64 or 128) and generate `key_count` from them.

**Comment by remyabel** [comment]
It looks like there's already a `MakePRNG` function that does just that:

https://github.com/googleapis/google-cloud-cpp/blob/73ff44ecc03f1f7783c8a1a0c3a2775b0b84b9ab/google/cloud/internal/random.h#L43

Should the code be cleaned up to replace instances of `DefaultPRNG(std::random_device{}());` with `MakePRNG()`?

**Comment by coryan** [comment]
I think `MakePRNG()` actually takes *more* bits of entropy out of `/dev/urandom` than a single call to `std::random_device{}()` does, right?
