### ISSUE TITLE
Storage(emulator): Handle requests with empty data

### ISSUE THREAD

**Issue by cojenco** [googleapis/google-cloud-cpp#6692]
There are cases where the request sent to the emulator has empty data. `json.loads(request.data)` causes an `JSONDecodeError` when `request.data` is an empty byte string. One example in the emulator is [`objects.copy()`](https://github.com/googleapis/google-cloud-cpp/blob/591fa09e2009e1c4b855e513c26457d037195004/google/cloud/storage/emulator/emulator.py#L564) where metadata can be optionally supplied.

**Comment by coryan** [comment]
Is that a bug in the emulator?  The documentation says: "In the request body, supply the relevant portions of an object resource, according to the rules of patch semantics." That suggests the contents must be a valid JSON object, and an empty string or body is not a valid JSON object.

I understand that some client libraries may be sending empty bodies and GCS may be accepting them *today*.  That is a bug in a client library, and a nicety that GCS may withdraw at any moment, without notice.  We should not require GCS to preserve undocumented behavior.

**Comment by cojenco** [comment]
Apologies for the confusion. I've updated the description to point to the emulator endpoint [`objects.copy()`](https://github.com/googleapis/google-cloud-cpp/blob/591fa09e2009e1c4b855e513c26457d037195004/google/cloud/storage/emulator/emulator.py#L564). According to the documentation, the request body may optionally supply metadata to apply to the copied object using an object resource. In this case, we need to handle requests with no metadata supplied.
