### ISSUE TITLE
[Flake] Windows builds failed to choco install bazelisk

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#6787]
The windows bazel-presubmit build failed in https://source.cloud.google.com/results/invocations/c29fea23-a2a3-43d8-9117-ec555935db8f/targets/cloud-devrel%2Fclient-libraries%2Fcpp%2Fgoogle-cloud-cpp%2Fwindows%2Fbazel-presubmit/log 

Due to:
```
T:\src>choco install --no-progress -y bazelisk 
Chocolatey v0.10.15
Installing the following packages:
bazelisk
By installing you accept licenses for the packages.
bazelisk not installed. An error occurred during installation:
 The operation has timed out
bazelisk package files install completed. Performing other installation steps.
The install of bazelisk was NOT successful.
bazelisk not installed. An error occurred during installation:
The operation has timed out
```

To avoid these errors, we could
* Retry the choco install command
* Avoid choco and directly download the bazelisk binary. This is what we do in our Dockerfiles run on GCB
* Update our Windows VM image to include the bazelisk binary so we don't need to fetch it at all ([some notes on how to do this](https://docs.google.com/document/d/14NodFbvoIvdQZ_FgQlKeIQbfu-sQWvhYs91feDDouVw/edit)).

**Comment by coryan** [comment]
https://source.cloud.google.com/results/invocations/92a503a5-8a43-45d8-817b-4473bb1e06c0

**Comment by coryan** [comment]
https://source.cloud.google.com/results/invocations/d9092269-e311-45e9-b4ce-1913bc3f0cf1

**Comment by coryan** [comment]
https://source.cloud.google.com/results/invocations/d6b82e8c-f23a-446d-9bcc-39f16b419add
https://source.cloud.google.com/results/invocations/cc87c929-6073-46d6-9a32-b4f0b9c25106
https://source.cloud.google.com/results/invocations/73270399-1c9b-4ed3-a9f1-05f4c3ae4a2b
