### ISSUE TITLE
Enable vcpkg builds on Linux ARM

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#6798]
Trying to run `vcpkg` on ARM gives the following error:
`Environment variable VCPKG_FORCE_SYSTEM_BINARIES must be set on arm and s390x platforms.` 

To work around this, we need to insert `export VCPKG_FORCE_SYSTEM_BINARIES=1` in `vcpkg.sh`. I am not sure if we want to set this for all Linux builds, or just Linux ARM builds.

The builds in question are: `cmake-oldest-deps` and `quickstart-cmake`

Discussion on vcpkg: https://github.com/microsoft/vcpkg/discussions/17738.

**Comment by devjgm** [comment]
Closing until we have an ARM build environment.
