### ISSUE TITLE
Printing usage should not result in an error

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#6819]
In our [base Example class](https://github.com/googleapis/google-cloud-cpp/blob/59d7cf6a8d3b521caf304c274fc127d636d102c3/google/cloud/testing_util/example_driver.cc) and several other places printing the usage results in a shell error.

This is not very important, but it seems mean to instruct users to run a command that results in an error:
https://github.com/googleapis/google-cloud-cpp/blob/59d7cf6a8d3b521caf304c274fc127d636d102c3/google/cloud/spanner/samples/README.md#L55-L59

As far as I can tell we want a successful print usage call to look like this:
```console
$ ./target --help
Usage: blah blah blah
$ echo $?
0
```

And for the case of examples, which have commands, we do the following to successfully print usage for a given command:
```console
$ ./example command --help
```

**Comment by devjgm** [comment]
Punt once.

**Comment by coryan** [comment]
Strike 2

**Comment by Dhruv1107** [comment]
Hi @dbolduc and @devjgm ,
This issue seems to be a good initiation of my journey towards contribution to FOSS projects.
Can you please assign this to me?

**Comment by dbolduc** [comment]
> Can you please assign this to me?

Happily.

<hr />

Let's start by just building and running an example. I'd pick the pubsub samples, which uses the `google::cloud::testing_util::Example` class:
https://github.com/googleapis/google-cloud-cpp/blob/eb5ad369a7c5fc35aba1f4678eed44b686610c5e/google/cloud/pubsub/samples/samples.cc#L2375
https://github.com/googleapis/google-cloud-cpp/blob/eb5ad369a7c5fc35aba1f4678eed44b686610c5e/google/cloud/pubsub/samples/samples.cc#L2521

We can run the example with [Bazel](https://bazel.build/) using this command:  (Warning: the initial build will be *really* slow)

```sh
$ bazel run //google/cloud/pubsub/samples:samples

# Output
Missing command
Usage: samples <command> [arguments]

Commands:
    create-avro-schema <project-id> <schema-id>
    ....etc....
```

We can then print the result of the previous command
```sh
$ echo $?

# Output
1
```

When that is working, we are ready to start solving the problem. We like that the program exits with a failed status when no commands are supplied. But we want to be able to pass it a `--help` and have it both
* print the usage
* return a 0 (success)

```sh
$ bazel run //google/cloud/pubsub/samples:samples -- --help

# Output
Usage: blah blah blah....
```
```sh
$ echo $?

# Current Output
1

# Desired Output
0
```

So the question is how should we modify the [Example class](https://github.com/googleapis/google-cloud-cpp/blob/eb5ad369a7c5fc35aba1f4678eed44b686610c5e/google/cloud/testing_util/example_driver.h#L75-L86) to make that happen?

**Comment by antonjfernando2021** [comment]
I want to get into open source dev in c++, no idea where to start, gcs seems like a good place.

**Comment by coryan** [comment]
Seems like we do not have time to work on this. Closing for now.
