### ISSUE TITLE
Nuget Package  for "Google-Cloud-cpp" is not available

### ISSUE THREAD

**Issue by pisipatimahadev** [googleapis/google-cloud-cpp#6856]
Hi,
   I have not found the Nuget Package for the googleapis/google-could-cpp. If it is already available, Can you please share the information needed ? If not available, will it be supported in near future ?

Note: Nuget Package is available for dot-net. Expecting the same for CPP code as well

Regards,
Mahadev

**Comment by coryan** [comment]
> I have not found the Nuget Package for the googleapis/google-could-cpp. 

In C++ we do not create binary packages for any platform, including Windows.

> If not available, will it be supported in near future ?

We have no specific plans to support binary packages, so I would not expect them to appear "in the near future".  We are noticing more demand for them, so our plans could change.

**Comment by pisipatimahadev** [comment]
Thanks Carlos, for quicker response :)
I hope that the plans should change quickly and the Binary Packages(cpp) should be available on Windows.

As of now, we are using the GCS Interoperability (awsclient apis). But it is not allowing the full usage of GCS features. 

For Example, we are not able to set the "location"/"location type"/ "Storage Class" while creating the GCS bucket.   
Always the location is defaulting to **US(multiregion)**. This is troublesome.

Regards,
Mahadev

**Comment by coryan** [comment]
Other than it is very tedious, or slow, or both: is there a reason you cannot build the libraries from source? We try to test with a number of compilers and configurations, so it should work.  I am just trying to understand / document why "compile from source" does not work for everybody.

Alternatively, we keep the packages in `vcpkg` relatively up to date, you should be able to use `vcpkg` to create a nuget package yourself.  If the [blog post](https://devblogs.microsoft.com/cppblog/vcpkg-introducing-export-command/) is still accurate something like this should do the trick:

```console
git clone https://github.com/microsoft/vcpkg
.\vcpkg\bootstrap-vcpkg.bat
.\vcpkg\vcpkg install google-cloud-cpp
.\vcpkg\vcpkg export google-cloud-cpp --nuget
```

**Comment by pisipatimahadev** [comment]
Thank you Coryan. I was able to build the nuget package for google-cloud-cpp successfully (on Windows 10 box)

git clone https://github.com/microsoft/vcpkg
./vcpkg/bootstrap-vcpkg.bat
./vcpkg/vcpkg.exe update
./vcpkg/vcpkg.exe upgrade --no-dry-run
./vcpkg/vcpkg.exe install google-cloud-cpp
./vcpkg/vcpkg export google-cloud-cpp --nuget
