### ISSUE TITLE
Update Bigtable filter samples to look like other client libraries' samples

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#6868]
For example: https://cloud.google.com/bigtable/docs/samples/bigtable-filters-limit-pass-all

**Comment by remyabel** [comment]
Can you provide more clarification on the work to be done? Like which samples need changing and what about them does not conform to the other library samples.

**Comment by dbolduc** [comment]
Sorry, I should have been more explicit in the statement of the issue.

The snippets in question are the ones shown on the Cloud Bigtable documentation page, [Using Filters](https://cloud.google.com/bigtable/docs/using-filters#c++). Our code is pulled from [`data_filter_snippets.cc`](https://github.com/googleapis/google-cloud-cpp/blob/e36926c3cd485f869b301947be0641f2ffeeda39/google/cloud/bigtable/examples/data_filter_snippets.cc). I think this is all of them... but we should do a Ctrl+F for "filter" in the snippet regions to make sure.

The main difference between the C++ snippets and the other languages has to do with the expected data in the table. The other languages are expecting [this data](https://cloud.google.com/bigtable/docs/using-filters#data). The C++ snippets [initialize our table with a different set of data](https://github.com/googleapis/google-cloud-cpp/blob/e36926c3cd485f869b301947be0641f2ffeeda39/google/cloud/bigtable/examples/data_filter_snippets.cc#L489-L535).

So the task is to
1. Modify that `InsertTestData` method to create the table the other samples use
2. Update the individual methods to match the other filters, (e.g. use `RowKeysRegex(".*#20190501$")` instead of `RowKeysRegex("key.*9$")` for the [row key regex example](https://cloud.google.com/bigtable/docs/using-filters#row-key-regex)

There is another difference, which is that the other samples call some method to return / print the rows. (e.g. `print_row(row)` in Python). C++ has the printing written out inline. We could make a print function that each sample calls..... but I am on the fence about it.

Arguably, a code sample should not use methods that are neither defined in the code block nor the API.... But if the method name is super obvious like `PrintRow(row)`, then maybe it's fine.

**Comment by remyabel** [comment]
Whoops, completely forgot about this. Thanks for expanding on the info.

> There is another difference, which is that the other samples call some method to return / print the rows. (e.g. print_row(row) in Python). C++ has the printing written out inline. We could make a print function that each sample calls..... but I am on the fence about it.

Agreed that we shouldn't create a new function just to match this, I think it will be fine just to use `std::cout` here.
