### ISSUE TITLE
Storage benchmarks should upload results to a bucket

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#6883]
Currently the storage benchmarks print results to `stdout`. This is fine when running one benchmark, but to run multiple benchmarks in a cluster (specially if we use GKE) it would be more convenient if the benchmark uploaded its own results to GCS.

Maybe the benchmarks should accept a `--results=<destination>` option, with `destination` taking several forms:

* `stdout` would behave like today
* `file:<directory>` would save the output to a file in `<directory>`
* `gs://<bucket>/<prefix>and the parameters would save the results to a GCS object in `<bucket>` with a name starting with `<prefix>.

It would be convenient if the benchmark created a unique name for the destination file / object, so one could just run all the instances of the benchmark in a cluster with the same command-line parameters.

**Comment by devjgm** [comment]
Discussed. not going to happen, and not too important.
