### ISSUE TITLE
C++ API confusion

### ISSUE THREAD

**Issue by laoshaw** [googleapis/google-cloud-cpp#6928]
new to google cloud cpp, first cpp is not listed at client-api page: https://developers.google.com/api-client-library

then there is a page saying c++ client api is deprecated: https://google.github.io/google-api-cpp-client/latest/

so I thought OK only AWS provides a c++ SDK these days, then I saw this project at github from google: https://github.com/googleapis/google-cloud-cpp which is also listed here: https://cloud.google.com/apis/docs/cloud-client-libraries

so, is this google-cloud-app a replacement for the deprecated c++ client api?

also cloud-storage-c++-api is include here as well?

sorry I could not find a place to ask general questions.

**Comment by coryan** [comment]
> first cpp is not listed at client-api page: https://developers.google.com/api-client-library

Correct.  Without going too much into history, this project (`google-cloud-cpp`) aims to provide C++ client libraries for [Google Cloud Platform](https://cloud.google.com), and we are only human, so we have prioritized the libraries with most demand (as we understand it) first.  We are not trying to write C++ client libraries for all google services, e.g., Ads.  If we have missed a library or you think we should prioritize some Cloud service ahead of the others do let us know, that is valuable information.

> then there is a page saying c++ client api is deprecated: https://google.github.io/google-api-cpp-client/latest/

Correct.  Those libraries were based on automatic code generation for the REST APIs.  For a number of reasons that is not the best approach for some of the most interesting services (e.g., Google Cloud Storage, or Cloud Spanner).

> so, is this google-cloud-cpp a replacement for the deprecated c++ client api?

See above.  I think the answer is "partially yes".

> also cloud-storage-c++-api is include here as well?

This repository contains a client library for Google Cloud Storage, yes.  See the README for details:

https://github.com/googleapis/google-cloud-cpp/blob/main/google/cloud/storage/README.md

> sorry I could not find a place to ask general questions.

Using an issue is perfectly fine, using [GitHub Discussions](https://github.com/googleapis/google-cloud-cpp/discussions) is also fine.  Your preference.

**Comment by laoshaw** [comment]
Thanks a lot for the clarification.
