### ISSUE TITLE
[Flake] errors trying to download googleapis tarball

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#6930]
Several builds failed for #6927, probably environmental, but we can setup some defense in depth (I think, more on that below).

The more interesting bits of the log are:

```
Step #3:   GET /googleapis/googleapis/tar.gz/2c6e4dd22260e34403b468cc6d19aa43a9c684ed
Step #3:   HTTP/2
Step #3: 
Step #3:   Host: codeload.github.com
Step #3: 
Step #3:   user-agent: curl/7.76.1
Step #3: 
Step #3:   accept: */*
Step #3: 
[snip snip snip]

Step #3: 
Step #3:   HTTP/2 500 
Step #3: 

Step #3: 
Step #3:   The requested URL returned error: 500
Step #3: 
Step #3:   stopped the pause stream!
Step #3: 
```

This failed across multiple builds at the same time:

https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/6927/e148f2292426358a87d95c8435d8dd3d7a112609/index.html

So maybe GitHub was having a bad moment.  There are some things we can do to protect against these problems:

* We *could* copy the `googleapis/googleapis` directory into our source code.  There is very little reason in forcing customers to download the code, specially since the code is pinned to an specific version.
* Cache the tarball in GCS, create a public bucket to contain the tarballs, and have one of the builds "seed" the bucket when the SHA changes, both CMake and Bazel accept a list of URLs to download the tarball from
* Some of these builds may be using older versions of CMake, which do not retry the download.  Maybe we can download the tarball outside CMake (with `curl --retry`) and then point the build to use that tarball.

**Comment by devbww** [comment]
More than 90d without repeats, closing.
