### ISSUE TITLE
google/cloud/storage throws exceptions, contradicting the documentation

### ISSUE THREAD

**Issue by lgruen** [googleapis/google-cloud-cpp#6933]
**What component of `google-cloud-cpp` is this related to?**
google/cloud/storage

**Describe the bug**
The google-cloud-storage documentation (https://googleapis.dev/cpp/google-cloud-storage/latest/) states:

> This library never throws exceptions to signal error. In general, the library returns a StatusOr<T> if an error is possible. Some functions return objects that already have an existing error handling mechanism, such as types derived from std::ostream where the application can check the state flags to determine if there was an error. In these cases no StatusOr wrapper is used.

I thought this means that checking the return values of client library calls is sufficient and that `catch`-clauses aren't required.

However, the google-cloud-storage library throws exceptions in a number of places (one concrete example is `ThrowSetOptionError`).

**Expected behavior**
Either the docs should state that exception handling is required or the library should never throw exceptions.

**What version of `google-cloud-cpp` are you using?**
1.29.0

**Comment by remyabel** [comment]
I think the intent is that none of the APIs use exceptions to signal errors? As far as I can tell, the code you're referring to is internal (i.e, not user facing). If exceptions are not enabled, it will just print the message and then terminate. But since it is user facing code there is no need for you to use a `catch` clause to handle the error.

**Comment by lgruen** [comment]
Hi @remyabel! You're right that all the functions in `google/cloud/internal/throw_delegate.h` just terminate when exceptions are disabled at compile-time. By "user facing code", do you mean code that's calling into the client libraries? The exceptions thrown by e.g. `ThrowRuntimeError` definitely get passed all the way to the calling code, i.e. are not caught internally in the library.

Maybe you're saying that these exceptions are used in the way that assertions are typically employed, only to signal invariants that should never fail? So in the case of a failure, an abort is really all one can do? That doesn't seem to be the pattern used throughout the library either though, or at least it's not immediately clear to me why e.g. some of the parsers that throw exceptions couldn't handle failures gracefully.

**Comment by coryan** [comment]
> **Expected behavior**
> Either the docs should state that exception handling is required or the library should never throw exceptions.

You are right, of course.  Fortunately, I think we can treat the remaining `Throw*()` call sites as bugs, their priority might be a matter for debate (see below).

> However, the google-cloud-storage library throws exceptions in a number of places (one concrete example is ThrowSetOptionError).

These are effectively assertions, if they do happen they indicate the data structures are corrupted, or that the library is coded incorrectly (e.g., calling libcurl in the wrong sequence), no amount of `StatusOr<T>` would help you recover from those problems.

> e.g. some of the parsers that throw exceptions couldn't handle failures gracefully.

I think this is more of a problem, but maybe not a huge one in practice: to hit this error you would need bug in the service, or garbled data received over HTTPS.

I just created a couple of follow up bugs to break this down a bit.  We may need to do another pass after they are fixed to find any remaining problems, leaving this open until then.

**Comment by lgruen** [comment]
Awesome, really appreciate that, @coryan!

**Comment by coryan** [comment]
I just created two more followup issues.  For both the exceptions probably indicate corrupted memory or some other serious bug where error handling would be unlikely to help.

That just leaves the exceptions in the streambuf classes, which are required and captured by the C++ library anyway.

I think we can close this issue now, as the remaining work is documented elsewhere.  Feel free to reopen if you disagree or I missed something.
