### ISSUE TITLE
Refactor default `Options`

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#6965]
If we think it is cleaner, prefer:

**A**
```c++
Options DefaultOptions(Options opts) {
  return MergeOptions(std::move(opts),
      Options{}.set<Option1>(default1)
               .set<Option2>(default2)
               // etc.
               .set<OptionN>(defaultN));
}
```
to:
**B**
```c++
Options DefaultOptions(Options opts) {
  if (!opts.has<Option1>())
    opts.set<Option1>(default1);
  if (!opts.has<Option2>())
    opts.set<Option2>(default2);
  // etc.
  if (!opts.has<OptionN>())
    opts.set<OptionN>(defaultN);
  return opts;
}
```
(which we use in bigtable, spanner, generated libraries)

**Comment by devjgm** [comment]
The version @dbolduc is proposing certainly does look cleaner, IMO. The only potential downsides I can think of are:

1. That requires computing all the default values up front, even in cases where the default is not needed. However, this cost could be avoided by using a function-local static constant "`kDeafults`" that's initialized by invoking a lambda. That way, we compute all the default values once, and can re-use the same defaults on every subsequent invocation.
2. Some defaults [depend on other options](https://github.com/googleapis/google-cloud-cpp/blob/ca2208c56cce9f710e1a71f1a5ebdd93b6df4a8b/google/cloud/spanner/internal/defaults.cc#L95-L106), and it may be difficult/impossible to pre-compute these correctly. However, that may not be a big problem. We could still use the preferred "MergeOptions" implementation for most defaults, followed by a handful of special-case options.

I think both of these "downsides" have reasonable workarounds. I'd be happy to see a PR where someone converts one of the existing `DefaultOptions()` functions to use this new approach so we can see how it improves things.

**Comment by dbolduc** [comment]
Closing. If anyone feels strongly, they can reopen the issue.
