### ISSUE TITLE
Move GCS+gRPC plugin to v2 protos

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#6982]
The `v2` protos for GCS+gRPC were just published:

https://github.com/googleapis/googleapis/tree/master/google/storage/v2

We would like to move the GCS+gRPC plugin to use these protos. I anticipate at least the following steps:

- [x] Pick a new minimum version of Clang (DONE: 6.0) and create a build for it
- [x] Remove the clang-38 build and update documentation to say Clang-6.0 is the new minimum
- [x] Update the googleapis baseline.
- [x] Update all the builds to require Protobuf >= 3.15 
- [x] Add the new protos to the storage_protos library.
- [x] Remove the functionality not available in `v2/` protos.
- [x] Remove any tests or integration tests using functionality (e.g. metadata operations) that these protos do not implement.
- [x] Change the emulator to use the new protos.
- [x] Rewrite the `StorageStub` (and friends) and the `internal::GrpcClient` to use these new protos.
- [x] Figure out what to do with the `QuotaUser` field.

**Comment by coryan** [comment]
I picked Clang-6.0 as the new minimum because it is the earliest default Clang in any of the distros we support.  Ubuntu:16.04 ships with Clang-3.8, and Ubuntu:18.04 ships with Clang-6.0... So 6.0 it is.

**Comment by vnvo2409** [comment]
Hi @coryan , please ping if there is anything I can help on this issue :smile:

**Comment by coryan** [comment]
@vnvo2409 thanks for the offer.  Please be patient with us, I just deleted a lot of the code you wrote, but we will add it back (with some -- hopefully minor -- changes).

**Comment by coryan** [comment]
Okay, I figured out the answer to quota user, we need to add this as as `x-quota-user` header in the `grpc::ClientContext`:

https://cloud.google.com/apis/docs/system-parameters
