### ISSUE TITLE
Common configuration for ClientOptions in tests.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#699]
As we write tests for the GCS client we would like to have a simple way to configure all the `ClientOptions` parameters. We want something that would not interfere with the configuration of the library for application developers.  Some alternatives to implement this are:

- A helper function in `google::cloud::storage::testing` that creates the `ClientOptions` based on a file.
- A small number of environment variables to set the configuration.
- Command-line arguments for the tests (and only the tests).

**Comment by rsimion** [comment]
@coryan 

which one do you this is most appropriate approach?

**Comment by coryan** [comment]
I think this bug is now obsolete.  I am closing it.
