### ISSUE TITLE
IAM quickstart README refers to Pub/Sub quickstart

### ISSUE THREAD

**Issue by hegemonic** [googleapis/google-cloud-cpp#7009]
**Does this issue affect the google-cloud-cpp project?**
Yes

**What component of `google-cloud-cpp` is this related to?**
`google/cloud/iam/quickstart/README.md`

**Describe the bug**
This `README` file is for the IAM quickstart. However, step 3 of [Using with CMake](https://github.com/googleapis/google-cloud-cpp/tree/f0048fa6857546b0ea0857fad8d521be9be261bf/google/cloud/iam/quickstart#using-with-cmake) tells you to change directories to the Pub/Sub quickstart:

```sh
cd $HOME/google-cloud-cpp/google/cloud/pubsub/quickstart
```

**To Reproduce**
n/a

**Expected behavior**
The `cd` command looks like this:

```sh
cd $HOME/google-cloud-cpp/google/cloud/iam/quickstart
```

**Operating system:**
n/a

**What compiler and version are you using?**
n/a

**What version of `google-cloud-cpp` are you using?**
https://github.com/googleapis/google-cloud-cpp/tree/f0048fa6857546b0ea0857fad8d521be9be261bf/google/cloud/iam/quickstart#using-with-cmake

**Additional context**
I would have sent a pull request to fix this issue, but I'm not sure whether this `README` is autogenerated. Happy to send a PR if you can tell me which file to update.

**Comment by dbolduc** [comment]
@hegemonic You are right. Thanks for pointing this out!

I have submitted a PR that will correct the quickstart documentation. Thanks for offering to do so yourself!
