### ISSUE TITLE
XML Upload possible?

### ISSUE THREAD

**Issue by mcybz** [googleapis/google-cloud-cpp#7053]
Despite documentation of XML multipart uploads available, not seeing anything in the form of code/sdk for cpp. 

https://cloud.google.com/storage/docs/multipart-uploads

Does a library exist to handle xml multipart uploads?

**Comment by mcybz** [comment]
AFAICT the

`parallel_upload.h` implementation uses the old compose method (that incurs early delete charges), not the newer xml multipart method. (which doesnt incur such charges)

**Comment by coryan** [comment]
The client library does not (yet) use multipart-uploads.

**Comment by coryan** [comment]
> Does a library exist to handle xml multipart uploads?

Google does not (yet) have any client libraries that support MPU, in C++ or any other language.  We have been thinking about it, but I neglected to create a feature request.  Just did that (#7054).

**Comment by mcybz** [comment]
Glad it's on the radar now. Thanks for that. 👍
