### ISSUE TITLE
Support multipart-uploads (MPU) in the client library

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#7054]
This is a new feature in GCS:

https://cloud.google.com/storage/docs/xml-api/post-object-multipart
https://cloud.google.com/storage/docs/xml-api/put-object-multipart
https://cloud.google.com/storage/docs/xml-api/post-object-complete
https://cloud.google.com/storage/docs/xml-api/delete-multipart
https://cloud.google.com/storage/docs/xml-api/get-bucket-uploads

It requires parsing some XML, but at least the formats are fixed.

**Comment by coryan** [comment]
Thanks for reaching out.  Unfortunately I do not think we will be able to work on this during 2021-Q4.

**Comment by devjgm** [comment]
Still want to do this, but no time yet.

**Comment by coryan** [comment]
Strike 2.  We will want to do it, but no time yet.

**Comment by tmatsuo** [comment]
If someone really needs this feature, consider hiring me as a temporary freelance engineer (my github bio has contact).

Tasks included:
- Propose a design to the google-cloud-cpp team at google and get approved
- Send PRs for implementation and get merged

Background: I was assigned to this project starting from 2023. It was still in early prototype and design phase. @coryan and I agreed to have a simple XML parser in google-cloud-cpp so I started implementing it (#10558, #10564, #10568, #10608). The overall design was still in early stage, but @coryan and I discussed several times and I have a rough idea of the overall design.

Then unfortunately I got affected by the recent layoff 😥
I'll need to spend my time for surviving this situation, so I can't work on this project anymore unless someone hires me 😅

@coryan 
Feel free to
- delete this post if you feel it's spammy
- endorse me if you feel this proposal is reasonable (and you still like me)

**Comment by coryan** [comment]
I do not think we will have time to work on this during 2023-H2.

**Comment by coryan** [comment]
This is not scheduled for 2023, maybe in 2024.

**Comment by coryan** [comment]
We have decided not to work on this.  We believe [Parallel Composite Uploads](https://cloud.google.com/storage/docs/parallel-composite-uploads) cover most cases, and in C++ we already implement PCUs via [ParallelUploadFile()](https://cloud.google.com/cpp/docs/reference/storage/latest/namespacegoogle_1_1cloud_1_1storage#namespacegoogle_1_1cloud_1_1storage_1aa96cdb12055fcf33dae8f7344fbdeb08)
