### ISSUE TITLE
Support HMAC authentication for downloads and uploads

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#7055]
The client library does not support HMAC authentication, while some customers need it.  The service only supports HMAC authentication for the XML API.   The client library uses the JSON API for all metadata operations, but we do use XML for downloads, and could support it for downloads.

Maybe we could expose a limited client, something like:

```cc
namespace storage_experimental {
class ReadWriteClient {
  public:
    storage::ReadObjectStream ReadObject(...);
    storage::WriteObjectStream WriteObject(...);
};

ReadWriteClient CreateClient(HmacCredentials ... , Options opts);

}
```

This client would support HMAC but would be limited to a subset of the operations that are supported with it.  Alternatively, just return a `storage::Client` that always fails with `kUnimplemented` for operations that do not support HMAC

**Comment by devjgm** [comment]
Punt

**Comment by coryan** [comment]
Strike 2

**Comment by coryan** [comment]
We have no time for this, closing.
