### ISSUE TITLE
Cleanup original Bigtable Benchmarks

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#7097]
There's probably more to do, but at least:
1. Modernize the command line parsing. Currently, if you want to set one option, you must set [all options listed before it](https://github.com/googleapis/google-cloud-cpp/blob/e3f07517967a57de21eda9994f602c73f0a6808c/google/cloud/bigtable/benchmarks/setup.cc#L116-L168). This can be made cleaner by using `OptionDescriptor`.

2. Change the table prefixes so that they match [this regex](https://github.com/googleapis/google-cloud-cpp/blob/1295b30097a21451f4b7cf0582660989b91200d7/google/cloud/bigtable/testing/random_names.cc#L25). Then, if they leak, they will get [cleaned up](https://github.com/googleapis/google-cloud-cpp/blob/1295b30097a21451f4b7cf0582660989b91200d7/google/cloud/bigtable/testing/cleanup_stale_resources.cc#L25-L44).

**Comment by remyabel** [comment]
I could be wrong, but looks like `setup.h` is only included in `embedded_server.cc` and `BenchmarkSetupData` isn't even actually used. Remove it?

**Comment by dbolduc** [comment]
At the moment, `setup.h` is also included in `benchmark.h`, the base class for the old benchmarks. They all use the `MakeBenchmarkSetup()` method, for example, here: https://github.com/googleapis/google-cloud-cpp/blob/8794ddcc40c2211ada81c4d67a782112ba864504/google/cloud/bigtable/benchmarks/apply_read_latency_benchmark.cc#L106

The cleanest solution to this problem probably involves removing `setup.h`, and starting over with an `Options`-based approach, like in `mutation_batcher_throughput_benchmark.cc`.
