### ISSUE TITLE
Internal Cleanup for spanner benchmarks

### ISSUE THREAD

**Issue by Kavya-choudhary** [googleapis/google-cloud-cpp#7101]
I tried to use this google-cloud-cpp for my C++ application. While installing google-cloud-cpp with vcpkg, I got the following error for cleanup for spanner benchmarks "google/cloud/spanner/CMakeLists.txt" not found.

**Comment by coryan** [comment]
Could you share what version of `vcpkg` you were using?  What platform? Did you use manifest mode with `vcpkg` or did you use `vcpkg install google-cloud-cpp`?

How do the spanner benchmarks come into play?  I do not believe they are installed or compiled with `vcpkg` when trying to *use* `google-cloud-cpp`.

**Comment by coryan** [comment]
I am going to close this because we cannot help you without additional information.
