### ISSUE TITLE
Remove emulator workarounds for default_leader in Spanner integration tests

### ISSUE THREAD

**Issue by devbww** [googleapis/google-cloud-cpp#7144]
There is some cleanup to do in the integration tests and samples when the Spanner emulator supports `default_leader`.

**Comment by devbww** [comment]
Let's keep the reminder open (if only to keep our `TODO(#7144)` comments live).

**Comment by devbww** [comment]
Let's keep the reminder open (if only to keep our TODO(#7144) comments live).

**Comment by coryan** [comment]
This is waiting for emulator to fix things.
