### ISSUE TITLE
TIMESTAMP invalid argument

### ISSUE THREAD

**Issue by qizzzh** [googleapis/google-cloud-cpp#7202]
**Does this issue affect the google-cloud-cpp project?**
yes

**What component of `google-cloud-cpp` is this related to?**
spanner

**Describe the bug**
I have a timestamp column and would like to use the spanner CPP library to insert values to this column.
However spanner complains about invalid argument with no further information. The code is like below:
```
    auto timestamp = spanner::MakeTimestamp(
        std::chrono::system_clock::time_point(
            std::chrono::seconds(std::intmax_t(1628814573.0))
        ));
```
```
spanner::SqlStatement("INSERT INTO abc(
                                         " timestamp "
                                         ") VALUES("
                                         " @ts "
                                         ")",
                                        {
                                         { "ts", spanner::Value(timestamp.value())}
                                        }));
```

The error only says expected a TIMESTAMP and INVALID_ARGUMENT. Nothing else. I'm not sure what went wrong.

**To Reproduce**
See the code above.

**Expected behavior**
Expected the insertion to complete without errors.

**Operating system:**
macos and ubuntu 20.04

**What version of `google-cloud-cpp` are you using?**
1.25.0

**Comment by dorian3d** [comment]
For completeness, as a workaround, we can insert the timestamp as a string:
```
auto abslTimestamp = timestamp.value().get<absl::Time>();
spanner::SqlStatement("INSERT INTO abc(
                                         " timestamp "
                                         ") VALUES("
                                         " @ts "
                                         ")",
                                        {
                                         { "ts", spanner::Value(absl::FormatTime(abslTimestamp.value())) }
                                        }));
```

We have also seen a related issue. We get an error when we try to retrieve a timestamp (created by `CURRENT_TIMESTAMP()`) as a `spanner::Timestamp` object:
```
spanner::SqlStatement select("SELECT id, timestamp FROM abc WHERE id = @id", { { "id", "id" } });
auto rows = spannerClient_->ExecuteQuery(std::move(select));

using RowType = std::tuple<std::string, absl::optional<spanner::Timestamp>>;
auto maybe_row_tuple = *(spanner::StreamOf<RowType>(rows).begin());
```
`maybe_row_tuple.ok()` is `false` and `status()` returns:
```
2021-08-20T20:38:02.99714905Z: Failed to parse input [INVALID_ARGUMENT]
```

**Comment by devjgm** [comment]
Thanks for the bug report. We're looking into it.

One quick data point, but the following example code worked for me when built against head:

```cc
  namespace spanner = ::google::cloud::spanner;
  auto timestamp = spanner::MakeTimestamp(std::chrono::system_clock::time_point(
      std::chrono::seconds(std::intmax_t(1628814573.0))));
  auto sql = spanner::SqlStatement(
      "INSERT INTO Performances("
      "  SingerId, VenueId, LastUpdateTime"
      ") VALUES("
      "  1, 2, @ts"
      ")",
      {{"ts", spanner::Value(timestamp.value())}});
  auto txn = spanner::MakeReadWriteTransaction();
  auto insert = client.ExecuteDml(txn, std::move(sql));
  if (!insert) throw std::runtime_error(insert.status().message());
```

That was when run on a table created with the following (we already had this code and sample lying around):

```cc
  auto metadata = client
                      .UpdateDatabase(database, {R"""(
                        CREATE TABLE Performances (
                            SingerId        INT64 NOT NULL,
                            VenueId         INT64 NOT NULL,
                            EventDate       Date,
                            Revenue         INT64,
                            LastUpdateTime  TIMESTAMP NOT NULL OPTIONS
                                (allow_commit_timestamp=true)
                        ) PRIMARY KEY (SingerId, VenueId, EventDate),
                            INTERLEAVE IN PARENT Singers ON DELETE CASCADE)"""})
                      .get();
```
If you can point out what I'm doing wrong, that may help. Otherwise, we can try with version 1.25.0, which I believe you said you're using.

Can you confirm that your `timestamp` field was created with the type `TIMESTAMP`?

**Comment by qizzzh** [comment]
That looks pretty close to what we are doing however it doesn't for us using version 1.25.0.
Confirmed the `timestamp` columns was created with the type `TIMESTAMP` and is nullable.

**Comment by devbww** [comment]
I cannot reproduce this with 1.25.0.

I created table that is at least a subset of what it seems you have ...
```
  CREATE TABLE abc (
      id         STRING(1024),
      timestamp  TIMESTAMP
  ) PRIMARY KEY (id)
```
and then **successfully** inserted a row with ...
```
  namespace spanner = ::google::cloud::spanner;
  auto txn = spanner::MakeReadWriteTransaction();
  auto timestamp = spanner::MakeTimestamp(
      std::chrono::system_clock::from_time_t(1628814573));
  auto sql = spanner::SqlStatement("INSERT INTO abc (timestamp) VALUES (@ts)",
                                   {{"ts", spanner::Value(timestamp.value())}});
  auto insert = client.ExecuteDml(txn, std::move(sql));
  if (!insert) throw std::runtime_error(insert.status().message());
```
So, something else must be going on.

Perhaps you could try to run your example with the following environment variables set:
```
  GOOGLE_CLOUD_CPP_ENABLE_CLOG=1
  GOOGLE_CLOUD_CPP_ENABLE_TRACING=rpc,rpc-streams
  GOOGLE_CLOUD_CPP_TRACING_OPTIONS=single_line_mode=off,truncate_string_field_longer_than=0
```

When I do that I see the following (slightly edited) RPC trace for the `ExecuteDml()` call:
```
2021-08-21T04:39:08.475667428Z [DEBUG] <140267015327872> ExecuteSql() <<
session: "projects/<project>/instances/<instance>/databases/<database>/sessions/<session>"
transaction {
  begin {
    read_write {
    }
  }
}
sql: "INSERT INTO abc (timestamp) VALUES (@ts)"
params {
  fields {
    key: "ts"
    value {
      string_value: "2021-08-13T00:29:33Z"
    }
  }
}
param_types {
  key: "ts"
  value {
    code: TIMESTAMP
  }
}
seqno: 1
 (./google/cloud/internal/log_wrapper.h:84)
2021-08-21T04:39:08.558529228Z [DEBUG] <140267015327872> ExecuteSql() >> response=
metadata {
  row_type {
  }
  transaction {
    id: "AN4G3x_wynkJ9UTPwL4HU2tG_A-ZSGhQNo6TFg"
  }
}
stats {
  row_count_exact: 1
}
 (./google/cloud/internal/log_wrapper.h:89)

**Comment by qizzzh** [comment]
@devbww we noticed when printed the timestamp format is in a different format than yours : e.g. `2020-09-2121:39:3521:39:35Z` is it possible that this could be causing the issue?

**Comment by devbww** [comment]
> we noticed when printed the timestamp is in a different format than yours : e.g. `2020-09-2121:39:3521:39:35Z` is it possible that this could be causing the issue?

Absolutely!

This is formatted by `TimestampToRFC3339()` in `google/cloud/spanner/timestamp.cc`, and the missing `T` separator and the duplication of the time in your trace implies that you're using a version of the Abseil library that does not support the `%ET` format specifier.  It was introduced there on 2020-06-02, which looks like it would have first appeared in the `20200923.1` release.

At the moment, `doc/packaging.md` says that `20200923.3` is the minimum supported Abseil release.

**Comment by qizzzh** [comment]
@devbww  This is really helpful. We are using `20200205`. We will upgrade and test again. Thank you!

**Comment by qizzzh** [comment]
On the other hand would it make sense to fail the build or at least emit a warning if an incompatible version is used? It seems not ideal to fail silently.

**Comment by devbww** [comment]
> On the other hand would it make sense to fail the build if an incompatible version is used? It seems not ideal to fail at runtime.

Have you run the tests?  Many of them would fail in this configuration, I believe.

**Comment by qizzzh** [comment]
It does fail our unit tests though it was not clear what went wrong from the error message (just invalid argument as seen above). It would be great if more details can be added to the error or simply fail the build so we don't need to debug it at runtime.

**Comment by devbww** [comment]
I'm referring to things like `google/cloud/spanner/timestamp_test.cc`, and other tests that use `TIMESTAMP` values.  The former, at least, has direct tests for timestamp <=> string conversions.  That would highlight the problem directly.

**Comment by qizzzh** [comment]
I see. We didn't run the tests..

**Comment by qizzzh** [comment]
If we need to backport the change instead of upgrading could someone point me to the commit? We have a lot of packages depending on absl and upgrading is not a trivial effort.

**Comment by devbww** [comment]
It looks like it was https://github.com/abseil/abseil-cpp/commit/da3a87690c56f965705b6a233d25ba5a3294067c, but I'm afraid I have no idea whether that will apply cleanly over the https://github.com/abseil/abseil-cpp/releases/tag/20200225.3 release, or, even if it does, how the result will behave.

**Comment by coryan** [comment]
Looks like abseil/abseil-cpp@33caf1097ecce4fe892567462fa8821d477854b4 is needed too. That is the commit that actually implemented `%ET` ?

**Comment by devbww** [comment]
> Looks like [abseil/abseil-cpp@33caf10](https://github.com/abseil/abseil-cpp/commit/33caf1097ecce4fe892567462fa8821d477854b4) is needed too. That is the commit that actually implemented `%ET` ?

Yes, right you are.  Thanks.

**Comment by qizzzh** [comment]
Thanks all! We are trying to upgrade absl internally. It's a bit painful but since we may need it anyway in the future we decided to do it.
