### ISSUE TITLE
Verify dependencies meet our needs at compile-time

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#7211]
Motivated by #7202.  We should try to detect at compile-time if the versions of our various dependencies do not meet our needs.  Note that:

* Relying on unit or integration tests to detect problems is not suitable, the customers may not be able to run the unit tests.
* Sometimes we depend on specific behaviors, not just the presence of specific APIs, so the problems are not detected at compile time.
* With Bazel, we cannot rely on the `bazel/google_cloud_cpp_deps.bzl` file.  Customers may override the preferences we express there.
* With CMake, we sometimes can request a minimum version in `find_package()`, but this depends on the dependency defining a proper version file.

AFAIK, we would need to do this for:

- [ ] Abseil: **no** version macros are available
- [ ] gRPC: **no** version macros that I know of
- [ ] crc32c: **no** version macros available
- [ ] Protobuf: version macros **are** available
- [ ] OpenSSL: version macros **are** available
- [ ] nlohmann::json: version macros **are** available
- [ ] libcurl: version macros **are** available

**Comment by devjgm** [comment]
Probably still want to do something like this.

**Comment by coryan** [comment]
Strike 2. coryan will ask the other C++ libraries at google.

**Comment by coryan** [comment]
Abseil and gRPC have version macros, but we do not have the time to work on this.
