### ISSUE TITLE
Create a "mutation batcher" for spanner

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#7238]
**What component of `google-cloud-cpp` is this feature request for?**

Cloud Spanner

**Is your feature request related to a problem? Please describe.**

A single commit cannot be larger than 100 MiB, and cannot perform more than 20,000 mutations, where each (row, column) pair counts as a "mutation":

https://cloud.google.com/spanner/quotas#limits_for_creating_reading_updating_and_deleting_data

Sometimes one has a stream of mutations, like when reading a CSV file and trying to upload it.  The application has to manually break down the stream based on these rules.

**Describe the solution you'd like**

I would like a class or function that automatically batches mutations.  I would like to describe the maximum number of mutations in flight, or per transaction, stream the `spanner::Mutation` object to it, and the class would automatically create transactions as needed.  For extra credit, make it asynchronous so I can do other work while the transaction executes, maybe with flow control.  

Maybe something like this:

```cc
struct Data { /* some application-level object with lots of fields */ };
spanner::Mutation DataToMutation(Data d);

void F(spanner::Client client, std::vector<Data> very_large_list) {
  auto batcher = spanner::MutationBatch(client);
  for (auto& d : very_large_list) {
    batcher.Apply(DataToMutation(std::move(d))).then([](auto f) {
       auto status = f.get();
       if (s.ok()) return;
       std::cerr << "error in mutation " << status << "\n";
    });
  }
  batcher.Flush();
}
```

**Describe alternatives you've considered**

Well, manually creating the batches.

**Additional context**

For inspiration look at:

https://github.com/googleapis/google-cloud-cpp/blob/f13ded90f4e1c59166a2e3611ba4ff7fa01c006e/google/cloud/bigtable/mutation_batcher.h#L36-L38

**Comment by devjgm** [comment]
My first thought about how to do this may be too simplistic, but it would be a single non-member function like:

```cc
// Efficiently batches and applies all the mutations in `v`. Each batch is committed
// using a separate Transaction. Any batch that fails, stops the processing and a non-OK
// Status is returned. An OK status indicates that all Mutations were successfully committed.
Status Apply(std::vector<spanner::Mutation> const& v, Options opts = {});
```

It's blocking, yes. I'm not sure what the `opts` are needed for, but maybe something. The return value may need to be more complex to indicate exactly which Mutations were applied.

Is this too naive to the point where it doesn't actually even help w/ the original motiviating use case?

**Comment by devjgm** [comment]
I see. I was focused on the part before "For extra credit, make it asynchronous ...". Perhaps the async part is really the key of this feature request.

**Comment by devjgm** [comment]
Still thinking about this one.

**Comment by coryan** [comment]
Close for now, if somebody asks for this we can reopen.
