### ISSUE TITLE
Polling Policy Simple Test flakes

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#7269]
GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/2c6c34d4-994e-415e-a3ba-ca9f9dc779f9;tab=detail?project=cloud-cpp-testing-resources
Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/7268/73c70496d02cd51fb8d1144c05d072665edf7acf/fedora-34-clang-tidy/log-2c6c34d4-994e-415e-a3ba-ca9f9dc779f9.txt

```
100/383 Test #110: bigtable_polling_policy_test ..........................................................***Failed    0.56 sec
Running main() from gmock_main.cc
[==========] Running 4 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 4 tests from GenericPollingPolicy
[ RUN      ] GenericPollingPolicy.Simple
../google/cloud/testing_util/check_predicate_becomes_false.h:59: Failure
Value of: actual
  Actual: false
Expected: true
../google/cloud/testing_util/check_predicate_becomes_false.h:59: Failure
Value of: actual
  Actual: false
Expected: true
[  FAILED  ] GenericPollingPolicy.Simple (82 ms)
```

**Comment by coryan** [comment]
No repeats in 90d, closing.

**Comment by dbolduc** [comment]
@coryan reports: "Second time I run into this during a PR. [...] At a guess the timeouts are too short for the CI environment."

GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/0a6bf5ea-2ffd-4542-a775-c40c81c9eb31;tab=detail?project=cloud-cpp-testing-resources
Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/7882/8f9fcecee2b1e1b592aa3757ae372a8a9a7ca4e7/fedora-34-shared/log-0a6bf5ea-2ffd-4542-a775-c40c81c9eb31.txt

**Comment by coryan** [comment]
GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/945b207d-de31-4b23-990d-d9c73e04c7a1;tab=detail?project=cloud-cpp-testing-resources
Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/8049/31a93a93e4e93711a64e9200cc11d2da201c8de2/fedora-34-shared/log-945b207d-de31-4b23-990d-d9c73e04c7a1.txt

**Comment by dbolduc** [comment]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/cbed23cf-05db-413e-97b6-48a9ffb83e63;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/8383/6fc731fd1c77787a700d37965f95ce16ad5e03af/fedora-34-shared/log-cbed23cf-05db-413e-97b6-48a9ffb83e63.txt

**Comment by dbolduc** [comment]
No repeats in 90 days.
