### ISSUE TITLE
storage/quickstart.cc failure

### ISSUE THREAD

**Issue by wkyu2kg** [googleapis/google-cloud-cpp#7334]
### Discussed in https://github.com/googleapis/google-cloud-cpp/discussions/7333

<div type='discussions-op-text'>

<sup>Originally posted by **wkyu2kg** September 19, 2021</sup>
It seems that the quickstart.cc program fails due to an error on the WriteObject() function. This happens to v1.28.0~v1.31.1

# ./quickstart gs://useast01
Error creating object: Permanent error in CreateResumableSession: Not Found [NOT_FOUND]</div>

**Comment by coryan** [comment]
The program expects a bucket name, like `my-bucket`.  A string like `gs://my-bucket` will not work.

**Comment by wkyu2kg** [comment]
I see. Thanks. It was expecting the prefix a month ago.

**Comment by wkyu2kg** [comment]
Hello, again,

The same program, quickstart.cc, runs well on ubuntu 18.04 from one GCP instance. From another GCP instance with ubuntu 20.04, it runs into this error. But I can read/write my bucket without any issue. What could be the cause of the scope error (403)?

(base) wkyu@vm01:~/tools/google-cloud-cpp-1.28.0$ ./quickstart useast01
Error creating object: Permanent error in CreateResumableSession: {
  "error": {
    "code": 403,
    "message": "Provided scope(s) are not authorized",
    "errors": [
      {
        "message": "Provided scope(s) are not authorized",
        "domain": "global",
        "reason": "forbidden"
      }
    ]
  }
}
 [PERMISSION_DENIED]
(base) wkyu@vm01:~/tools/google-cloud-cpp-1.28.0$ gsutil ls gs://useast01
gs://useast01/quickstart.txt
gs://useast01/gsn_tests/
gs://useast01/rmat15/
gs://useast01/rmat15m/
gs://useast01/rmat15s/
gs://useast01/rmat15sm/
gs://useast01/rmat15sma/
gs://useast01/rmat15smab/
gs://useast01/tsuba_test/

**Comment by wkyu2kg** [comment]
Much appreciated! I got it fixed via this page: https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances#changeserviceaccountandscopes.

**Comment by coryan** [comment]
Glad you found a solution. Closing for now, feel free to reopen if needed.
