### ISSUE TITLE
Convenient way to pass a CQ to disable gRPC background threads using Options

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#7346]
# The Problem
Previously, users could call `g::c::ConnectionOptions{}.DisableBackgroundThreads(cq)` or `g::c::bigtable::ClientOptions{}.DisableBackgroundThreads(cq)`.

But these are being deprecated in favor of `g::c::Options`. Currently the way to get the same behavior out of `Options` looks like: https://github.com/googleapis/google-cloud-cpp/blob/7414d8ad4517560e71ffe306d9ddd2ccd5a3dc8d/google/cloud/bigtable/client_options.cc#L66-L69

The code is not concise. We also can't recommend that users use an `internal` class.

So we need a convenient way to pass in a `CompletionQueue` that makes the transition to `Options` as smooth as possible for users.

# Possible Solutions

## A function to generate the `BackgroundThreadsFactory` from the CQ

PR #7345 was an attempt at this. I think it demonstrates the need for such a feature. But the name of the function and the location of the function are highly questionable. Using a function at all is questionable, too.

## A new CQ option

We should also consider an option like...
```c++
struct GrpcDisableBackgroundThreadsOption {
  using Type = CompletionQueue;
}
```
... where we modify... https://github.com/googleapis/google-cloud-cpp/blob/7414d8ad4517560e71ffe306d9ddd2ccd5a3dc8d/google/cloud/grpc_options.cc#L63-L71
... to return `CustomerSuppliedBackgroundThreads` if the CQ option is set.

The name is subject to change, but it would at least allow for user code that looks more like what it used to:
```c++
ConnectionOptions{}.DisableBackgroundThreads(cq)
// becomes
Options{}.set<GrpcDisableBackgroundThreadsOption>(cq)
// instead of what is done in PR #7345 which looks like:
Options{}.set<GrpcBackgroundThreadsFactoryOption>(DisableBackgroundThreads(cq))
// or what is done now, which is just gross
Options{}.set<GrpcBackgroundThreadsFactoryOption>([cq] { 
  return absl::make_unique<internal::CustomerSuppliedBackgroundThreads>(cq); 
 }); 
```

I kind of like the CQ as an option approach. In the same way that `CustomerSuppliedBackgroundThreads` complements `AutomaticallyCreatedBackgroundThreads`, we would have `GrpcDisableBackgroundThreadsOption` which complements the `GrpcBackgroundThreadPoolSizeOption`.

**Comment by coryan** [comment]
> I kind of like the CQ as an option approach

Me too.  The name of the option is a bit awkward.  Maybe you (or @devbww) can think of a better name.  Here is what we want to say:

- The library needs a completion queue *and* some threads servicing that completion queue to run background operations
- The library will create its own CQ and pool of threads if the application does not provide one
- The application *can* provide a CQ and then the library will assume the CQ already has a pool of threads
- Incidentally, the CQ can be shared across clients in that case

`DisableAutomaticallyCreatedBackgroundThreadsOption`? `UseApplicationProvidedCompletionQueueOption`? `UseCustomBackgroundThreadsOption`?

**Comment by devjgm** [comment]
Name suggestion:
```cc
// Tells libraries to use the specified completion queue rather than its own.
// The caller is responsible for making sure there are thread(s) servicing the specified completion queue.
struct GrpcCompletionQueueOption {
  using Type = CompletionQueue;
};
```
