### ISSUE TITLE
Consider using named volumes for CI builds

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#7375]
Our CI builds use bind mounts in `$PROJECT_ROOT/cmake-out` and `$PROJECT_ROOT/build-out`.  Maybe we should use named volumes:

https://docs.docker.com/storage/volumes/

Those would not create ugly directories in the source. They can be backed up, e.g. to preserve `$HOME/.ccache`, admittedly the approach is a bit clunky:

https://docs.docker.com/storage/volumes/#backup-a-container

**Comment by devjgm** [comment]
Considered and happy enough w/ the current solution. keeping as-is.
