### ISSUE TITLE
Add support for turbo replication

### ISSUE THREAD

**Issue by ddelgrosso1** [googleapis/google-cloud-cpp#7380]
We need to add support for a new metadata field: `rpo`. Full details are available in [this doc](https://docs.google.com/document/d/1ee3LzRfyArNIR4rLEeY60Eio7DBwLy5TkmvcMPxSork/edit?usp=sharing&resourcekey=0-4CYSH1Gc0ekxa1oUntE9yg).

Please wait for approval from myself before merging or releasing this change so we can coordinate around release dates.

**Comment by coryan** [comment]
We do not delay or accelerate our releases based on features, specially minor features like this. The C++ client libraries are released monthly, at the beginning of the month.  The features are merged when ready.

**Comment by ddelgrosso1** [comment]
Thanks @coryan. That should be fine.
