### ISSUE TITLE
[Flake] integration-daily GCB timeout

### ISSUE THREAD

**Issue by scotthart** [googleapis/google-cloud-cpp#7417]
Could possibly be due to version bump invalidating cache and bad luck that this build was the first to run requiring everything to be rebuilt.

https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/6f6967cb56fe1765b493b46c6b54c8dd59d41f73/fedora-34-integration-daily/log-7fc4a1db-9d04-4e8c-a5c0-ec2009c7cc9d.txt

**Comment by coryan** [comment]
I am going to mark this a dup of #4306.
