### ISSUE TITLE
Define constants or literal operators to deal with MiB, GiB, etc.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#742]
Sometimes we need to say things like "2 GiB" and it would be nice to have a literal operator and/or constant to avoid writing `2 * 1024 * 1024 * 1024` or `2 * (1 << 30)`.

**Comment by rsimion** [comment]
Something like this?

```
// `unsigned long long` parameter required for integer literal.
long long operator "" _GiB(unsigned long long val) {
  return val * 1024 * 1024 * 1024;
}
```
or 
```
// `unsigned long long` parameter required for integer literal.
long long operator "" _GiB(unsigned long long val) {
  return val * (1 << 30);
}

std::cout << 1_GiB << '\n'; //1073741824
std::cout << 2_GiB << '\n'; //2147483648

```

**Comment by coryan** [comment]
I like user-defined literals, but given the other discussion around them (#109), I think maybe this:

```C++
template <typename T /* maybe with a std::enable_if<is_integral<T>::value> */>
std::int64_t GiB(T value) {
  return value * (1LL << 30);
}
```

or maybe this:

```
constexpr std::int64_t GiB = std::int64_t(1) << 30;
```

Or alternatively, just close this bug, I am not sure these constants would be *that* useful.

**Comment by rsimion** [comment]
I will close it. 
Those constants do not seem to be very useful.
