### ISSUE TITLE
asynchronous dns is not enabled in bazel builds of curl

### ISSUE THREAD

**Issue by janbernloehr** [googleapis/google-cloud-cpp#7462]
**Does this issue affect the google-cloud-cpp project?**
Yes

**What component of `google-cloud-cpp` is this related to?**
All libraries built with bazel that depend on curl.

**Describe the bug**
The bazel build currently does not set `USE_ARES` or `USE_THREADS_POSIX` or `USE_THREADS_WIN32` in `bazel/curl.BUILD` which results in synchronous dns lookups which ultimately results in this issue: https://stackoverflow.com/questions/9191668/error-longjmp-causes-uninitialized-stack-frame

**To Reproduce**
The is difficult to reproduce since one would need to run into a timeout during dns lookup. This then causes an `alarm` to be issued causing a `longjmp` which crashes on modern linux systems.

**Expected behavior**
The bazel build of curl should use asynchronous dns lookup.

**Operating system:**
Ubuntu 18.04 and 20.04 but other modern linux os will be affected as well.

**What compiler and version are you using?**
g++ 7

**What version of `google-cloud-cpp` are you using?**
1.21 but this seems to not have changed in more recent version.

**Additional context**

**Comment by janbernloehr** [comment]
I am not sure if I would phrase this as a feature request and not a bug. The reason is that on modern Linux systems synchronous dns lookups in curl lead to crashes.

**Comment by coryan** [comment]
>The reason is that on modern Linux systems synchronous dns lookups in curl lead to crashes.

I completely missed that.  I just sent #7761 for review, I think it does switch libcurl to use `c-ares` library.

I hope this did not stop you from using the library, in the future, keep in mind that you can provide your own definition of `@com_github_curl_curl` in your `WORKSPACE` file.
