### ISSUE TITLE
Change default to C++14

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#7494]
We recently dropped support (or at least CI testing) for GCC-5.4 and with that, all the compilers we support default to C++14.  This is a proposal to switch the default build to C++14. I think we need to:

- [x] Create at least one build with C++11
- [ ] Maybe switch all our dependencies to compile with C++14 too
- [ ] Change the top-level CMake file to default to C++14

**Comment by coryan** [comment]
FWIW, MSVC [defaults to C++14](https://docs.microsoft.com/en-us/cpp/build/reference/std-specify-language-standard-version?view=msvc-160)

**Comment by devjgm** [comment]
Just an LGTM to this proposal

**Comment by coryan** [comment]
Closing, this is not going to give us the telemetry we want.
