### ISSUE TITLE
Reduce the disk space needed to install the SDK

### ISSUE THREAD

**Issue by pepisg** [googleapis/google-cloud-cpp#7506]
**What component of `google-cloud-cpp` is this feature request for?**
Bigquery and GCS

**Is your feature request related to a problem? Please describe.**
The installation of `google-cloud-cpp` and its dependencies is taking up nearly 2GB of disk space, I'm running the sdk inside a docker (linux) container on a space constrained system, and it would be great to have a more straightforward and efficient way of installing the sdk along with its dependencies. Is this install size normal or am I doing something wrong?

**Describe the solution you'd like**
It would be great if the sdk took less space on disk and could be installed using prebuilt debian packages. I'm aware that dependencies can be downloaded and built using vcpkg for each specific library, however for GCS and Bigquery need almost everything. Is it possible to install only what is strictly necessary? 

**Describe alternatives you've considered**
Create Debian packages for each library and reduce the needed disk space. 

**Additional context**
I don't know if its possible to reduce the install size by other means or if maybe I'm missing something in the installation process.

Thanks in advance for your help!

**Comment by coryan** [comment]
> I'm using [this](https://github.com/googleapis/google-cloud-cpp/blob/main/doc/packaging.md?plain=1#L460) instructions to install the library and dependencies on ubuntu 20.04. I'm cloning/downloading all the sources in the same folder and I'm removing this folder after everything is built and installed. Am I missing some optimization?

Sorry to keep pestering you with questions.  I think your strategy is sound, assuming you are using the canonical Docker tricks to minimize the layer sizes.  As you probably know, each `RUN` command creates a layer and removing files in a new layer does not reduce the overall Docker image size.  You need to use something like build stages, or a lot of `RUN cmake ... && cmake --build ... --target install && rm -fr build` directory to make each layer minimal.


> Also, are you getting those install sizes only accounting for the google sdk or also for all the dependencies? (Abseil, gRPC, crc32c, etc)

That is with all the dependencies, even with some extra stuff (like Boost) in it.
