### ISSUE TITLE
Here is the check if the popup has the map property `this._popup._map` and in `_openPopup` the check is `if (this._map.hasLayer(this._popup))`

### ISSUE THREAD

**Issue by Queens666** [googleapis/google-cloud-cpp#7541]
https://github.com/openmaptiles/maptiler-basic-gl-style/commit/26b0b9124c4b1df59d413d9bba0ed1566d4199d5

**Comment by coryan** [comment]
This is an invalid report.  @Queens666 please stop spamming the repository with invalid PRs and bugs.
