### ISSUE TITLE
[Flake] macOS failed to extract bazel / bazelisk

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#7544]
[Resultstore Log](https://source.cloud.google.com/results/invocations/e4a08a6f-7de8-4c15-b661-8d39d884aea7/log)

```
2021/10/31 20:43:49 Downloading https://releases.bazel.build/3.5.0/release/bazel-3.5.0-darwin-x86_64...
Bazelisk version: v1.5.0
Extracting Bazel installation...
FATAL: Error reading zip file '/Users/kbuilder/Library/Caches/bazelisk/bin/bazelbuild/bazel-3.5.0-darwin-x86_64': zlib returned error code -3 during inflate.

2021-11-01T03:43:51Z (+75s): build script reported errors.
```

**Comment by dbolduc** [comment]
https://source.cloud.google.com/results/invocations/3adf94b1-277e-466d-ad9d-6dbf184b21e0/targets

**Comment by dbolduc** [comment]
https://source.cloud.google.com/results/invocations/6355117f-ff50-4659-9030-32f1eafad09a

**Comment by coryan** [comment]
https://source.cloud.google.com/results/invocations/aed38e79-b26a-4d3e-b08f-5a1a7a7ba945

**Comment by scotthart** [comment]
fixed in https://github.com/googleapis/google-cloud-cpp/pull/7744
