### ISSUE TITLE
Consider dropping all CURL* associated with the same connection

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#7616]
When a transfer fails with a libcurl error we avoid reusing the handle for future requests (see #7088).  However, if the application is using HTTP/2 then other CURL* may be using the same connection, it may be a good idea to stop using it.  It is unclear if it is possible to identify all handles that have this problem, so we need to do some research first.

**Comment by scotthart** [comment]
Per https://everything.curl.dev/libcurl/connectionreuse, when using the easy interface, each easy handle has a connection cache that goes away when curl_easy_cleanup is called on the handle. When using the multi interface, the connection cache is associated with the multi handle and connections persist across calls to curl_easy_cleanup. Calling curl_multi_cleanup on the multi handle causes any connections in the connection cache to be closed.

Per #7088 (https://github.com/googleapis/google-cloud-cpp/pull/7088), when a transfer error occurs, both the easy handle and the multi handle are cleaned up. This should cause connection caches associated with either to be discarded.
