### ISSUE TITLE
Add ErrorInfo support to GCS

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#7644]
This is a follow on issue related to https://github.com/googleapis/google-cloud-cpp/issues/7429. In that issue, we added ErrorInfo support to `g::c::Status`, per https://google.aip.dev/193. That's now done for gRPC based services.

GCS is not gRPC, and so it needs the ability to fill in the ErrorInfo class that's (optionally) passed to `g::c::Status`. Per @coryan 's comment in https://github.com/googleapis/google-cloud-cpp/pull/7640

> For a future PR: I think we should do the same thing for GCS, at least here:
https://github.com/googleapis/google-cloud-cpp/blob/75d5b339f6f3efc3eb5ef74c0dc88eb094bdf81d/google/cloud/storage/internal/http_response.cc#L25

> Something like:

```cc
Status AsStatus(HttpResponse const& http_response) {
  if (HttpStatusCode::kMinContinue <= http_response.status_code &&
      http_response.status_code < HttpStatusCode::kMinSuccess) {
    // We treat the 100s (e.g. 100 Continue) as OK results. They normally are
    // ignored by libcurl, so we do not really expect to see them.
    return Status{};
  }
  if (HttpStatusCode::kMinSuccess <= http_response.status_code &&
      http_response.status_code < HttpStatusCode::kMinRedirects) {
    // We treat the 200s as Okay results.
    return Status{};
  }
  // Parse the payload as a JSON object, see https://cloud.google.com/apis/design/errors#http_mapping
  auto parsed = nlohmann::json::parse(http_response.payload, nullptr, false);
  ErrorInfo error_info = ExtractErrorInfo(parsed);
  return Status(/* map HTTP code */, parsed.value("message", ""), error_info);
```

**Comment by devjgm** [comment]
From https://cloud.google.com/apis/design/errors#http_mapping, an example response with "error info" data is:

```json
{
  "error": {
    "code": 400,
    "message": "API key not valid. Please pass a valid API key.",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.ErrorInfo",
        "reason": "API_KEY_INVALID",
        "domain": "googleapis.com",
        "metadata": {
          "service": "translate.googleapis.com"
        }
      }
    ]
  }
}
```

**Comment by devjgm** [comment]
Question: Within `AsStatus()`, is the `HttpResponse::payload` field always JSON? I see sometimes the payload is used directly as the Status's "message" field, so I'm not sure what format the payload field is.

**Comment by coryan** [comment]
> Question: Within `AsStatus()`, is the `HttpResponse::payload` field always JSON? I see sometimes the payload is used directly as the Status's "message" field, so I'm not sure what format the payload field is.

I do not think we can guarantee that it is always JSON.  Some error messages arrive from the load balancer, where they are not necessarily in JSON format.  But when the error message is from the JSON API, then they are in the format outlined above.

We can try to parse them as JSON, and if that fails we just stick the full message in the message string (as we do today).  If the parsing succeeds, then we can extract the `ErrorInfo` and use it in `Status`.

**Comment by devjgm** [comment]
In progress diff: https://github.com/googleapis/google-cloud-cpp/compare/main...devjgm:gcs-error-info?expand=1

**Comment by devjgm** [comment]
One problem currently is that GCS (or maybe it's the emulator) is returning some valid JSON that I'm not expecting. According to https://cloud.google.com/apis/design/errors#http_mapping, my code expects error JSON of the form:

```json
     {
       "error": {
         "code": ...,
         "message": "..."
         ...
         "details": [
           ...
         ]
       }
  }
``` 
But I'm sometimes seeing JSON of the form
```json
  {
     "code": ...,
     "message": ...
  }
```

That is, I see JSON data that looks like the _contents_ of the "error" object. So I'm not sure which of these formats I should actually expect.

**Comment by coryan** [comment]
Ugh... That might be the emulator, specifically the code around here:

https://github.com/googleapis/storage-testbench/blob/main/testbench/error.py#L37
