### ISSUE TITLE
Client and bidirectional streaming generated methods should not take a request

### ISSUE THREAD

**Issue by dpcollins-google** [googleapis/google-cloud-cpp#7659]
**Does this issue affect the google-cloud-cpp project?**
yes

**What component of `google-cloud-cpp` is this related to?**
Any that use Client-streaming or bidirectional-streaming RPCs

**Describe the bug**
The interface for the Pub/Sub streaming pull bidirectional streaming RPC is as follows:
```
/// Start a bi-directional stream to read messages and send ack/nacks.
  virtual std::shared_ptr<AsyncPullStream> AsyncStreamingPull(
      google::cloud::CompletionQueue&, std::unique_ptr<grpc::ClientContext>,
      google::pubsub::v1::StreamingPullRequest const& request) = 0;
```

However, in the implementation, the request argument is dropped entirely:

```
std::shared_ptr<AsyncPullStream> AsyncStreamingPull(
      google::cloud::CompletionQueue& cq,
      std::unique_ptr<grpc::ClientContext> context,
      google::pubsub::v1::StreamingPullRequest const&) override {
    return google::cloud::internal::MakeStreamingReadWriteRpc<
        google::pubsub::v1::StreamingPullRequest,
        google::pubsub::v1::StreamingPullResponse>(
        cq, std::move(context),
        [this](grpc::ClientContext* context, grpc::CompletionQueue* cq) {
          return grpc_stub_->PrepareAsyncStreamingPull(context, cq);
        });
  }
```

This leads to an error prone interface where a user might reasonably expect the request passed to the stub to be used for the initial request on the stream, but in practice it is unused and they need to send a default constructed instance of the request to this call.

**Comment by coryan** [comment]
Are you referring to this:

https://github.com/googleapis/google-cloud-cpp/blob/caca0ae1614fbd04cc0148f4ce771b20dd2226e6/google/cloud/pubsub/internal/subscriber_stub.h#L78-L81

That is in the `pubsub_internal` namespace, in a `pubsub/internal/*.h` header. We explicitly exclude those from the public API.  Folks should not use that function, should draw no conclusion about how it works from its signature, and we can change it at any time.

It is confusing, but just for us, we should clean it up.

**Comment by dpcollins-google** [comment]
Yes sorry. Closing, I was not aware that this was handwritten.
