### ISSUE TITLE
Implement the Pub/Sub Lite client library

### ISSUE THREAD

**Issue by dpcollins-google** [googleapis/google-cloud-cpp#7670]
**What component of `google-cloud-cpp` is this feature request for?**
pubsublite

**Is your feature request related to a problem? Please describe.**
pubsublite should be usable from c++

**Describe the solution you'd like**
A hand written client library for Pub/Sub Lite in C++ sharing the Cloud Pub/Sub API surface like it does in other languages.

**Comment by dpcollins-google** [comment]
Not sure if this can be reassigned to me for now?

**Comment by coryan** [comment]
I am going to close this because it is not specific enough.  Seems like we need to breakdown the remaining work in a series of  issues.  Completing this library is now part of our general backlog, fear not.
