### ISSUE TITLE
add storage support for per-operation options

### ISSUE THREAD

**Issue by devbww** [googleapis/google-cloud-cpp#7691]
Add an `Options options = {}` argument to the constructor of the client class(es).  Merge these options with the default options for the service, and store them as a member of the client class.

Add an `Options options = {}` argument to each operation within each client.  These options should then be merged with the client options from above, and installed as the prevailing options for the duration of the operation by instantiating an `internal::OptionsSpan`.

You could then use `internal::CurrentOptions()` to obtain (a `const&` to) the prevailing options from anywhere you might need them.  Any cleanup for call paths where `Options` have been passed explicitly is discretionary.

Similar support for the generated client classes was added in #7683, so you might be able to use that as an example.

----

I (@coryan) will steal some of the description to break down the work a bit. 

- [x] Change all the `storage::internal::*Request` classes to ignore `google::cloud::Options` in `set_multiple_options()`
- [x] Create some helpers to convert parameter packs into a `google::cloud::Options` and to create spans 
- [x] Change all the member functions in `storage::Client` to create an `OptionsSpan`
- [x] Add tests to verify all these spans are created
- [x] Change `storage::internal::CurlClient` to use `google::cloud::internal::CurrentOptions()` 
- [x] Change `storage::internal::RetryClient` to use `google::cloud::internal::CurrentOptions()`
- [x] Change `storage::internal::GrpcClient` to stop creating its own spans
- [x] Change `storage::internal::RestClient` to use `google::cloud::internal::CurrentOptions()`
- [ ] Update the documentation in `storage::Client`

**Comment by devbww** [comment]
Note: The options stored in the client class should now include the `connection->options()`.  So something like ...
```
ServiceClient::ServiceClient(std::shared_ptr<ServiceConnection> connection, Options opts = {})
    : connection_(std::move(connection)),
      opts_(internal::MergeOptions(std::move(opts), 
                                   service_internal::DefaultOptions(connection_->options()))) {
  ...
}

T ServiceClient::Operation(..., Options opts = {}) {
  internal::OptionsSpan span(internal::MergeOptions(std::move(opts), opts_));
  ...
}
```

**Comment by coryan** [comment]
## Background

All operations in the storage library already have a parameter pack:

https://github.com/googleapis/google-cloud-cpp/blob/5cb53865c0e9b113bd38fbdfb7ab8268bffc415e/google/cloud/storage/client.h#L1114-L1117

There are several alternatives to add `google::cloud::Options` to this set.

## Alternative 1 (my proposal)

Support passing `google::cloud::Options o` in the parameter pack.  The implementation of each operation would look more or less like this:

```cc
  template <typename... Options>
  StatusOr<ObjectMetadata> GetObjectMetadata(std::string const& bucket_name,
                                             std::string const& object_name,
                                             Options&&... options) {
    internal::GetObjectMetadataRequest request(bucket_name, object_name);
    // any `options` of type `::google::cloud::Options` are ignored here.
    request.set_multiple_options(std::forward<Options>(options)...);
    OptionSpan span(MergeWithRequestOptions(options_, std::forward<Options>(options)...);
    return raw_client_->GetObjectMetadata(request);
  }
```

where `MergeWithRequestOptions` would be specific to this client class, probably implemented like this:

```
  google::cloud::Options MergeWithRequestOptions(g::c::Options options) { return options; }

  template <typename... Tail>
  google::cloud::Options MergeWithRequestOptions(g::c::Options options, g::c::Options per_operation, Tail&&... tail) {
    return MergeWithRequestOptions(g::c::MergeOptions(std::move(per_operation), std::move(options)), std::forward<Tail>(tail)...);
  }
  template <typename Front, typename... Tail>
  google::cloud::Options MergeWithRequestOptions(g::c::Options options, Front&& front, Tail&&... tail) {
    return MergeWithRequestOptions(std::move(options), std::forward<Tail>(tail)...);
  }
```


## Alternative 2

Convert all things we pass in parameter packs to be `FooOption` classes (i.e., to define a `Type`).  Then change all the `Request` classes to store data in `Options`.  This seems fairly complicated, and it could be done after we do "Alternative 1"?

## Alternative 3

Try to consume all the `FooOption` things directly, without the `google::cloud::Options`, seems very different from the other libraries, and hard to implement, and probably confusing.

**Comment by coryan** [comment]
I am going to exclude the standalone functions and postpone that work to #9211
