### ISSUE TITLE
storage-testbench clone fails

### ISSUE THREAD

**Issue by devbww** [googleapis/google-cloud-cpp#7719]
ci/cloudbuild/builds/lib/integration.sh failed to install the dependencies for the storage emulator.
```
Step #3:   ERROR: Command errored out with exit status 128:
Step #3:    command: git clone -q https://github.com/googleapis/storage-testbench /tmp/pip-req-build-8x6zfeom
Step #3:        cwd: None
Step #3:   Complete output (4 lines):
Step #3:   error: RPC failed; curl 56 GnuTLS recv error (-24): Decryption has failed.
Step #3:   fatal: the remote end hung up unexpectedly
Step #3:   fatal: early EOF
Step #3:   fatal: index-pack failed
Step #3:   ----------------------------------------
Step #3: ERROR: Command errored out with exit status 128: git clone -q https://github.com/googleapis/storage-testbench /tmp/pip-req-build-8x6zfeom Check the logs for full command output.
```
GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/43b5fd08-d022-4550-a8c1-da33c77401e9;tab=detail?project=cloud-cpp-testing-resources
Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/faff4cc1d7517f6d586775bb4d3c8c4694ed2959/ubuntu-focal-cmake-oldest-deps/log-43b5fd08-d022-4550-a8c1-da33c77401e9.txt

**Comment by coryan** [comment]
No repeats since 2021-12-09, closing.
