### ISSUE TITLE
Remove unnecessary OpenSslUtils struct; define methods at namespace level

### ISSUE THREAD

**Issue by houglum** [googleapis/google-cloud-cpp#774]
As mentioned in PR #766, OpenSslUtils struct should not be wrapping the methods currently inside of it. Rather, they should be defined at namespace level.  This TODO tracks doing that small refactor in a subsequent commit.

**Comment by coryan** [comment]
Moving out of the Beta Release milestone, this is not part of the public API anyway.

**Comment by coryan** [comment]
I will take a stab at this.  I want to cleanup some other stuff too.
