### ISSUE TITLE
 support pubsub in C/C++

### ISSUE THREAD

**Issue by hungminhtran** [googleapis/google-cloud-cpp#777]
Do you have plan to support pub/sub in C/C++? I see a lot of language but no C/C++
We want to use it as a substitute for kafka

**Comment by coryan** [comment]
Currently there are no specific plans to add a C++ client library for pub/sub.  Proving that there is demand would help us argue internally for it though, so thanks for taking the time to file this issue.

**Comment by cschuet** [comment]
We are looking into using Cloud Pub/Sub for Long-running Tasks. Since these operations are really compute intense we'd prefer to implement our works in C++ creating the desire to have a C++ PubSub client.

**Comment by brodin** [comment]
@sduskis I guess this is no longer prioritized?

**Comment by sduskis** [comment]
@brodin, I removed the 'p2' label for internal reasons.  We have a policy to only set priorities on "type: bug".

**Comment by bitomaxsp** [comment]
@hungminhtran @cschuet Perhaps this is what you were looking for: https://github.com/sandvikcode/pubsuber

**Comment by agasparovic-sabre** [comment]
Hi @coryan, I see you're committing to https://github.com/googleapis/google-cloud-cpp-pubsub - is there a timeline for when it would support production workloads? Even a rough idea would be helpful.

**Comment by coryan** [comment]
We have not built a timeline for `google-cloud-cpp-pubsub` yet, and I really hesitate to set the wrong expectations.  At least a quarter is the best I can say right now.

**Comment by agasparovic-sabre** [comment]
No problem! Great to see something is in the works though. 😄

**Comment by coryan** [comment]
FWIW.  We now think all the APIs for Cloud Pub/Sub are stable (no promises), we still have a ways to go for [GA](https://github.com/googleapis/google-cloud-cpp/milestone/26).  Any folks that have the time, please consider testing the library and letting us know if they run into any problems, or awkward APIs, or anything.

**Comment by coryan** [comment]
Another update on this. We are shooting for GA in 2020-Q4.  Maybe early in the quarter if things go well.  We now expect some (minor) changes to the API, we will try to wrap those up before the next release.

**Comment by coryan** [comment]
For those following this bug, I just merged the PR that made the library GA.  We understand some folks may prefer to wait for a release, but you can download the code right now.
