### ISSUE TITLE
Cloud Composer API: `composer.googleapis.com`

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#7869]

**Comment by dbolduc** [comment]
In the Cloud Composer API, we have a few RPCs like [this one](https://github.com/googleapis/googleapis/blob/10380880f030101709b3ebe1eb1dd121fa8b4116/google/cloud/orchestration/airflow/service/v1/environments.proto#L79-L89). `OperationMetadata` is defined in [a separate proto](https://github.com/googleapis/googleapis/blob/10380880f030101709b3ebe1eb1dd121fa8b4116/google/cloud/orchestration/airflow/service/v1/operations.proto#L28), which is [not included](https://github.com/googleapis/googleapis/blob/10380880f030101709b3ebe1eb1dd121fa8b4116/google/cloud/orchestration/airflow/service/v1/environments.proto#L19-L25) by the original.

Our `*Connection` class will return the `metadata_type` for a longrunning operation whose `response_type` is `protobuf::Empty`. If this `metadata_type` is not imported from the original proto we do not include the generated `.pb.h` in `*_connection.h`. Thus, our code does not compile, because it cannot find the definition of `OperationMetadata`.

I do not think this is a bug with the generator. I think it is a bug with the proto. I will send a CL upstream.

**Comment by coryan** [comment]
FWIW, AppEngine has the same issue.

**Comment by dbolduc** [comment]
Blocked by #7922
