### ISSUE TITLE
Replace git+git instructions

### ISSUE THREAD

**Issue by remyabel2** [googleapis/google-cloud-cpp#7899]
https://github.com/googleapis/google-cloud-cpp/blob/c9cd27080e26c857dc0ea1c43af51d16fa860e3d/doc/contributor/howto-guide-setup-development-workstation.md#L106

This is [discouraged](https://pip.pypa.io/en/latest/topics/vcs-support/) and will [stop working anyway](https://github.blog/2021-09-01-improving-git-protocol-security-github/).

**Comment by coryan** [comment]
Hey, long time no see.  Thanks for the heads up, I need to update this code for other reasons anyway.
