### ISSUE TITLE
Cloud Document AI API: `documentai.googleapis.com`

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#7976]
- [x] Make the quickstart work, and run it in our ci builds.
- [ ] Add a helper function for setting the EndpointOption.

**Comment by dbolduc** [comment]
Still to-do:

- [ ] Make the quickstart work, and run it in our ci builds.
- [ ] Add a helper function for setting the `EndpointOption`.

**Comment by devbww** [comment]
We don't need the helper function for setting the EndpointOption now.  You can pass the location directly to `MakeDocumentProcessorServiceConnection()` instead.
