### ISSUE TITLE
Proto libraries in `external/googleapis/` are always compiled

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#8022]
The proto libraries in `external/googleapis/` are always compiled (unless gRPC is completely disabled, but that is Okay).

Most of them are small libraries with only one proto file in them, and many of them (things like "api.proto") are used by almost all libraries.  Not particularly onerous, but there are a few (e.g. `google_cloud_cpp_cloud_texttospeech`, `google_cloud_cpp_monitoring`) that are larger.  We could move them to `google/cloud/${service}` and compile them only when needed.

We need to have a plan on how to deal with these larger libraries.

We should also consider merging all the smaller libraries into a single `.a` file.  "One library per proto" makes no sense for the CMake build + install model, creates friction for customers, and (if we solve the many other problems) is very inconvenient for DLLs exports.  We can be backwards compatible with a series of interface-only targets.

**Comment by dbolduc** [comment]
A customer is asking for this.  See the discussion in: #10174

**Comment by coryan** [comment]
Realistically we will not have time to work on this. Closing for now.

**Comment by dbolduc** [comment]
We discussed this, and decided that building extra protos is in fact a bug. It is an unnecessary burden on customers who build with cmake and do not want to compile these extra protos.
