### ISSUE TITLE
[Flake] error in JSON library in storage signed_url_integration_test.cc

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#8027]
I ran `asan-pr` locally, and ran into the following flake in this test: https://github.com/googleapis/google-cloud-cpp/blob/9c793dae470fd82a9ea86572fb0c8ab4a12ea736/google/cloud/storage/tests/signed_url_integration_test.cc#L132

```
[ RUN      ] SignedUrlIntegrationTest.CreateV4SignedUrlGet
terminate called after throwing an instance of 'nlohmann::detail::type_error'
  what():  [json.exception.type_error.306] cannot use value() with string
```

The error message reminds me of this PR: #7702

**Comment by coryan** [comment]
You are probably right that it is similar to #7702, but the problem is "where"?  I will search for `is_discarded()` (as you suggested via IM) and fix those.  We may miss stuff though.
