### ISSUE TITLE
Consider documenting `g::c::Options` in a dedicated doc

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#8045]
`Options`, as a class, are [pretty well documented](https://googleapis.dev/cpp/google-cloud-common/HEAD/classgoogle_1_1cloud_1_1Options.html#details).

We might want to make a new doc (e.g. `doc/options.dox`) to expand on it though. We can go into more details on the different types of `Options` (per-call options, client options, connection options) and how they are applied. We can also highlight commonly used `Options`.

Maybe a helpful example use case could be: "How to share a background thread pool across multiple clients". (by setting the `GrpcCompletionQueueOption` and passing it into `Make*Connection(options)`)

**Comment by coryan** [comment]
Keep it open. Maybe for a doc fixit.

**Comment by coryan** [comment]
I think https://googleapis.dev/cpp/google-cloud-common/HEAD/group__options.html fixes this problem.  Closing.
