### ISSUE TITLE
Build failed to fetch googleapis data from github

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#8102]
GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/d82e4697-5b63-4e69-8590-66aedae4c47f;tab=detail?project=cloud-cpp-testing-resources
Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/56601817f1c8a853436c10c30360e0c75c51f94d/fedora-34-cmake-install/log-d82e4697-5b63-4e69-8590-66aedae4c47f.txt

Snippet of error:

```
T+6.333s [133/2626] Performing download step (download, verify and extract) for 'googleapis_download'
FAILED: external/googleapis/src/googleapis_download-stamp/googleapis_download-download 
cd /workspace/cmake-out/external/googleapis/src && /usr/bin/cmake -P /workspace/cmake-out/external/googleapis/src/googleapis_download-stamp/download-googleapis_download.cmake && /usr/bin/cmake -P /workspace/cmake-out/external/googleapis/src/googleapis_download-stamp/verify-googleapis_download.cmake && /usr/bin/cmake -P /workspace/cmake-out/external/googleapis/src/googleapis_download-stamp/extract-googleapis_download.cmake && /usr/bin/cmake -E touch /workspace/cmake-out/external/googleapis/src/googleapis_download-stamp/googleapis_download-download
-- Downloading...
   dst='/workspace/cmake-out/external/googleapis/src/16b43024639e5bcbb0f0367230db654f02cb8499.tar.gz'
   timeout='none'
   inactivity timeout='none'
-- Using src='https://github.com/googleapis/googleapis/archive/16b43024639e5bcbb0f0367230db654f02cb8499.tar.gz'
-- [download 100% complete]
-- [download 0% complete]
CMake Error at googleapis_download-stamp/download-googleapis_download.cmake:170 (message):
  Each download failed!

    error: downloading 'https://github.com/googleapis/googleapis/archive/16b43024639e5bcbb0f0367230db654f02cb8499.tar.gz' failed
          status_code: 22
          status_string: "HTTP response code said error"
          log:
          --- LOG BEGIN ---
            Trying 140.82.112.4:443...

  Connected to github.com (140.82.112.4) port 443 (#0)
...
```

It looks to me like a transient error w/ github servers.

**Comment by coryan** [comment]
I think this might be a dup, but I cannot find the other bug.  We may want to consider hosting these in a public GCS bucket, so we have an alternative source to download them from.

A more radical idea: just copy the protos into our repository: we pin to an specific version in each build, we are forcing folks to download `googleapis/googleapis` when we know exactly what stream of bytes they need.

**Comment by coryan** [comment]
And then I found it: #6930

**Comment by coryan** [comment]
GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/e7504d09-35aa-42b5-b176-f755cdf30e74;tab=detail?project=cloud-cpp-testing-resources
Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/8142/bd2296cef8ac58cd76356cd13faf4fc758ed6bb5/fedora-34-publish-docs/log-e7504d09-35aa-42b5-b176-f755cdf30e74.txt

**Comment by coryan** [comment]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/8aa2239c-7afb-453c-895b-61e87ea57fb1;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/0db3ec537f896557b0b6b612426d6bc961aa9a58/ubuntu-focal-quickstart-bazel/log-8aa2239c-7afb-453c-895b-61e87ea57fb1.txt

This one was using Bazel:

```
WARNING: Download from https://github.com/googleapis/google-cloud-cpp/archive/v1.40.2.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 502 Bad Gateway
ERROR: An error occurred during the fetch of repository 'com_github_googleapis_google_cloud_cpp':
   Traceback (most recent call last):
	File "/h/.cache/bazel/_bazel_root/14b5e1e306cbba6a5e6802706a50a915/external/bazel_tools/tools/build_defs/repo/http.bzl", line 100, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/googleapis/google-cloud-cpp/archive/v1.40.2.tar.gz] to /h/.cache/bazel/_bazel_root/14b5e1e306cbba6a5e6802706a50a915/external/com_github_googleapis_google_cloud_cpp/temp9248656697082125585/v1.40.2.tar.gz: GET returned 502 Bad Gateway
ERROR: /workspace/google/cloud/bigquery/quickstart/WORKSPACE.bazel:24:13: fetching http_archive rule //external:com_github_googleapis_google_cloud_cpp: Traceback (most recent call last):
	File "/h/.cache/bazel/_bazel_root/14b5e1e306cbba6a5e6802706a50a915/external/bazel_tools/tools/build_defs/repo/http.bzl", line 100, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/googleapis/google-cloud-cpp/archive/v1.40.2.tar.gz] to /h/.cache/bazel/_bazel_root/14b5e1e306cbba6a5e6802706a50a915/external/com_github_googleapis_google_cloud_cpp/temp9248656697082125585/v1.40.2.tar.gz: GET returned 502 Bad Gateway
ERROR: no such package '@com_github_googleapis_google_cloud_cpp//bazel': java.io.IOException: Error downloading [https://github.com/googleapis/google-cloud-cpp/archive/v1.40.2.tar.gz] to /h/.cache/bazel/_bazel_root/14b5e1e306cbba6a5e6802706a50a915/external/com_github_googleapis_google_cloud_cpp/temp9248656697082125585/v1.40.2.tar.gz: GET returned 502 Bad Gateway
```

**Comment by coryan** [comment]
We discussed this in the team.  Of all the proposed solutions, using a backup source for the tarball (say a public GCS bucket) had consensus.  It would require changing the script that updates the googleapis commit SHA to also create that backup tarball, but that seems reasonably easy to do.

**Comment by coryan** [comment]
https://source.cloud.google.com/results/invocations/6b922034-135c-41b0-9a5e-6b88bd833200

**Comment by coryan** [comment]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/cf4f6674-262b-4658-99a2-daaa32087aa3;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/4e02afd6ab2cbe6a21646b220e609ded5a990de0/demo-opensuse-leap-demo-install/log-cf4f6674-262b-4658-99a2-daaa32087aa3.txt
