### ISSUE TITLE
Enable google/cloud/channel on on multiple platforms

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#8125]
https://github.com/googleapis/google-cloud-cpp/pull/8116 adds the `google/cloud/channel` library. However, that build breaks on macos due to:

```
bazel-out/darwin-fastbuild/bin/external/com_google_googleapis/google/cloud/channel/v1/common.pb.h:545:33: error: expected member name or ';' after declaration specifiers
  static constexpr CustomerType DOMAIN =
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Applications/Xcode_12.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/math.h:732:17: note: expanded from macro 'DOMAIN'
#define DOMAIN          1
                        ^
```
https://source.cloud.google.com/results/invocations/8ee5da3b-6410-4185-a0d2-b38f5282069c/targets/cloud-cpp%2Fgithub%2Fgoogle-cloud-cpp%2Fmain%2Fmacos%2Fbazel-presubmit/log

That is, protobuf-generated code uses a symbol named `DOMAIN` that conflicts w/ a macro definition.

We will temporarily disable this library on macos, and re-enable it once protobuf is fixed to not choke on `DOMAIN`.

_Originally posted by @devjgm in https://github.com/googleapis/google-cloud-cpp/issues/8115#issuecomment-1022677732_

**Comment by devjgm** [comment]
The fix was submitted internally in cl/424720867. Now we need to wait for a release that contains the fix.

**Comment by coryan** [comment]
This is also a problem on Windows.

**Comment by coryan** [comment]
I sent a CL to fix Protobuf, but it will take a while to seep into the open source version.

**Comment by coryan** [comment]
This is now fixed.
