### ISSUE TITLE
Spanner "Invalid filter in ListInstances request"

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#8128]
GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/8a5c0c56-8312-47f7-ba27-819919f5b6c9;tab=detail?project=cloud-cpp-testing-resources
Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/de38ee9cf7e1af5e78edf077e0899da29f30db2d/fedora-34-integration-daily/log-8a5c0c56-8312-47f7-ba27-819919f5b6c9.txt

```
2022-01-27T08:16:27.984589316Z [DEBUG] <140247788318016> ListInstances() << google.spanner.admin.instance.v1.ListInstancesRequest { parent: "projects/cloud-cpp-testing-resources" filter: "name:projects/cloud-cpp-testing-resources/instances/test-instance- AND (NOT name:/instances/test-instance-mr-)" } (./google/cloud/internal/log_wrapper.h:86)
2022-01-27T08:16:28.053481721Z [DEBUG] <140247788318016> ListInstances() >> status=INVALID_ARGUMENT: Invalid filter in ListInstances request. (./google/cloud/internal/log_wrapper.h:89)
[  FAILED  ] DatabaseAdminClientTest.VersionRetentionPeriodCreate (77 ms)
```

Note the use of instance names like `projects/cloud-cpp-testing-resources/instances/test-instance-`, which looks like it's missing something after the trailing hyphen. 

/cc @devbww who might know what's going on.

**Comment by devbww** [comment]
That isn't missing anything.  The `name:...` form means a sub-string match.

So, I'm not sure what the problem is.  I'll investigate, but it would be nice if the error was more than "Invalid filter" (and that they didn't change behavior).

**Comment by devbww** [comment]
GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/89045117-19f1-469b-975c-abbc671e7669;tab=detail?project=cloud-cpp-testing-resources
Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/7d738e0ff4d391e4712d24a45b7a46a661da97e3/fedora-34-integration-daily/log-89045117-19f1-469b-975c-abbc671e7669.txt

**Comment by coryan** [comment]
GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/7d5300ab-6eb0-4001-b25d-2cd7bf283904;tab=detail?project=cloud-cpp-testing-resources
Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/2f34f2937fc8a25c0e2b8ce94c4a2a29a41dc918/fedora-34-integration-production/log-7d5300ab-6eb0-4001-b25d-2cd7bf283904.txt

**Comment by coryan** [comment]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/09dd3d7d-711e-4b67-b14a-448cc2b9f3e1;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/8666e7c8e13982f0ef7519b97f06763261ce2982/fedora-34-integration-production/log-09dd3d7d-711e-4b67-b14a-448cc2b9f3e1.txt

This may be getting worse, or maybe we notice more because the new CI builds have test caching disabled.

**Comment by coryan** [comment]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/1cf41f29-680b-469f-b392-3b476f1744a2;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/0ca8f0b0b41ca9f49acad65844da2e3bc3503ac4/fedora-34-integration-production/log-1cf41f29-680b-469f-b392-3b476f1744a2.txt

**Comment by coryan** [comment]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/47f11bdb-6f63-46aa-af47-49f4c203a8cc;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/5f0c67402c859aecdfc5587531bc9aef779c6c8e/fedora-34-integration-production/log-47f11bdb-6f63-46aa-af47-49f4c203a8cc.txt

**Comment by coryan** [comment]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/688dde3d-791e-49ea-b680-3895a79eadd9;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/83faf28e9a648a2df0ef5c0ad7b80698f870e9dc/fedora-34-integration-production/log-688dde3d-791e-49ea-b680-3895a79eadd9.txt

**Comment by coryan** [comment]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/85e7530c-f9dd-4163-810c-83891eec6a3d;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/541eb09c32c91c09ea84a55fc0861e916ebec56a/fedora-34-integration-daily/log-85e7530c-f9dd-4163-810c-83891eec6a3d.txt

**Comment by devbww** [comment]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/b579c19f-7f25-4e84-b293-5d71d7c314a4;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/0b1849448bb9e93564e1eb1a323703e695a84b67/fedora-34-integration-daily/log-b579c19f-7f25-4e84-b293-5d71d7c314a4.txt

**Comment by dbolduc** [comment]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/91f50678-30e6-4c7b-a294-e95993ea74f0;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/8452/5ccd1aadbc8d51030a09a642107d4b3348d6f62d/fedora-34-integration-production/log-91f50678-30e6-4c7b-a294-e95993ea74f0.txt

**Comment by coryan** [comment]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/581ac026-8ae9-4e4d-8437-35354db8e863;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/1aff874655f6a69d443a2e0694af4b16a32c7435/fedora-34-integration-daily/log-581ac026-8ae9-4e4d-8437-35354db8e863.txt

**Comment by dbolduc** [comment]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/50eef7d2-3a10-4cc5-a19d-fba92210bc06;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/c1ce073101fb72357362b3bf06951ffb43fa3a69/fedora-34-integration-daily/log-50eef7d2-3a10-4cc5-a19d-fba92210bc06.txt

**Comment by coryan** [comment]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/9e3835c3-ab4a-488e-b913-ccd0204c3882;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/576643220688e299eed931ddca2493c6aa97c7a7/fedora-34-integration-daily/log-9e3835c3-ab4a-488e-b913-ccd0204c3882.txt

**Comment by devbww** [comment]
For the record, the fix is scheduled to be in the next Spanner release (25.7).

**Comment by coryan** [comment]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/61bbcab9-ce56-4b96-9c06-bcafaaee55df;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/576643220688e299eed931ddca2493c6aa97c7a7/fedora-34-integration-daily/log-61bbcab9-ce56-4b96-9c06-bcafaaee55df.txt

**Comment by dbolduc** [comment]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/17902852-e783-4263-8a0f-81a2e1025452;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/e98b8ce22945be88b01feed53e378690e98200cb/fedora-34-integration-daily/log-17902852-e783-4263-8a0f-81a2e1025452.txt

**Comment by dbolduc** [comment]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/a066576a-a8b6-4c7f-b423-204058610e2e;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/ff42afc6ec84d9cac626c57b71fb031b5226c2ec/fedora-34-integration-production/log-a066576a-a8b6-4c7f-b423-204058610e2e.txt

**Comment by dbolduc** [comment]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/61307522-ee8b-4f54-b7f7-0d2499eb3c6f;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/ff42afc6ec84d9cac626c57b71fb031b5226c2ec/fedora-34-integration-daily/log-61307522-ee8b-4f54-b7f7-0d2499eb3c6f.txt

**Comment by dbolduc** [comment]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/54807812-2ed9-443c-a7d2-44d690f70a3f;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/4a857267d02c0d41375d2aeda95abee71fb8708a/fedora-34-integration-daily/log-54807812-2ed9-443c-a7d2-44d690f70a3f.txt

**Comment by devjgm** [comment]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/b6f4a8d1-82c0-4113-9dba-d15dfbf4fbdc;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/290d38f61af3eca8260761ec15cc38d7addb4e6f/fedora-34-integration-daily/log-b6f4a8d1-82c0-4113-9dba-d15dfbf4fbdc.txt

**Comment by devbww** [comment]
> For the record, the fix is scheduled to be in the next Spanner release (25.7).

25.7.1 is now at 100% deployment in Cloud Spanner, so this should be a thing of the past.  I'll close if things remain quiet for a few more days.

**Comment by devbww** [comment]
All quiet.
