### ISSUE TITLE
Enable google/cloud/asset

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#8145]
We cannot compile `google/cloud/asset` with protobuf <= 3.19.3 (current as-of 2022-01-28) because the protos define `TRUE` and `FALSE` as enums, while they are macros on macOS:

```
In file included from bazel-out/darwin-fastbuild/bin/external/com_google_googleapis/google/cloud/asset/v1/asset_service.pb.h:40:
bazel-out/darwin-fastbuild/bin/external/com_google_googleapis/google/cloud/asset/v1/assets.pb.h:4015:36: error: expected member name or ';' after declaration specifiers
  static constexpr EvaluationValue TRUE =
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Applications/Xcode_12.0.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/mach/boolean.h:81:17: note: expanded from macro 'TRUE'
#define TRUE    1
                ^
```

**Comment by dbolduc** [comment]
Windows bazel builds are still blocked. E.g. https://source.cloud.google.com/results/invocations/90512c0b-7383-4221-a311-b49200c0e635

They fail on the `TRUE`, `FALSE` definitions. `port_def.inc` inside google3 handles these ([internal link](http://google3/third_party/protobuf/port_def.inc;l=980-995;rcl=461364268)), but the open source doesn't ([link](https://github.com/protocolbuffers/protobuf/blob/40e8161842eb1920369a1a4884e61de4162db40a/src/google/protobuf/port_def.inc#L910-L915)). I did not look into why these are out of sync, despite the internal changes being made in 2021-04

**Comment by coryan** [comment]
Need to wait until Protobuf v23 and the corresponding changes in gRPC.

**Comment by coryan** [comment]
Only cleaning up some CI builds remains.  We need to wait until a release of `google-cloud-cpp`, and a release of `vcpkg` that includes Protobuf 23 and our library.

**Comment by coryan** [comment]
This is now fixed.
