### ISSUE TITLE
Tracking bug for client OptionsSpan

### ISSUE THREAD

**Issue by devbww** [googleapis/google-cloud-cpp#8164]
## Instructions

Client operation functions should create local `internal::OptionsSpan` objects, with at least the default options for the service, so that our internal libraries can use `internal::CurrentOptions()` to obtain information about the call that is otherwise difficult to plumb through the various layers.

In general, the `ServiceConnectionImpl` and `ServiceClient` constructors, and the `Service::Operation()` function should look like:
```
ServiceConnectionImpl::ServiceConnectionImpl(..., Options options)
    : ...,
      options_(internal::MergeOptions(std::move(options),
                                      service_internal::ServiceDefaultOptions(ServiceConnection::options()))) {}

ServiceClient::ServiceClient(std::shared_ptr<ServiceConnection> connection, Options options)
    : connection_(std::move(connection)),
      options_(internal::MergeOptions(std::move(options), 
                                      service_internal::ServiceDefaultOptions(connection_->options()))) {}

ReturnType
ServiceClient::Operation(..., Options options) {
  internal::OptionsSpan span(internal::MergeOptions(std::move(options), options_));
    :
  return connection_->Operation(...);
}
```

This is already true for the generated libraries, but we need to ensure that the hand-written libraries follow the same pattern.

Some libraries may not yet have connection-, client-, or operation-specific `Options`, so you'll have to work with what you have, but the minimal operation function should be:
```
ReturnType
ServiceClient::Operation(...) {
  internal::OptionsSpan span(service_internal::ServiceDefaultOptions(Options{}));
    :
  return connection_->Operation(...);
}
```

## Library List

- [ ] #7688
- [ ] #8510
- [ ] #8511
- [x] #7689
- [x] #7690
- [x] #8438
- [x] #8439
- [x] #7691

**Comment by dbolduc** [comment]
We can close this, because the remaining tasks all have dedicated issues.
