### ISSUE TITLE
Provide additional context in extracting PrivateKeyData from service account key response

### ISSUE THREAD

**Issue by Sita04** [googleapis/google-cloud-cpp#8173]
Context: extract PrivateKeyData from the response obtained by creating a service account key. The PrivateKeyData contains the json file credentials. This PrivateKeyData is base64 encoded.

Master issue: googleapis/google-cloud-python#7824
 or 
b/216208252 : Please modify the code snippet as per the PRs created in other languages.

Code: https://github.com/googleapis/google-cloud-cpp/blob/HEAD/google/cloud/iam/samples/iam_samples.cc#L196-L217

**Comment by coryan** [comment]
I just tested that example and I got:

```
private_key_data: "{\n  \"type\": \"service_account\",\n  \"project_id\": \"coryan-test\",\n  \"private_key_id\": \"5970234d3d09ebb67bd976adf304fc18650dbd49\",\n 
[snip snip]
```

That does not look like a base64 encoded string.  I think that might be because we use the gRPC API, the REST API would base64-encode this field, but gRPC won't.

**Comment by Sita04** [comment]
Thank you for verifying the issue. Closing it.
