### ISSUE TITLE
Relocate OAuth2 support from storage to common

### ISSUE THREAD

**Issue by scotthart** [googleapis/google-cloud-cpp#8219]
OAuth2 support is currently coupled with storage. With the new REST library and future client libraries with REST transport, the OAuth2 files and types are to be relocated to `google/cloud/internal` under the name space `google::cloud::oauth2_internal`. The oauth2 subdir in storage will be removed once storage has been refactored to use the REST library.

**Comment by coryan** [comment]
Still working on this, needs some refactoring.

**Comment by coryan** [comment]
This is done. We have support for OAuth2 in the common libraries.
