### ISSUE TITLE
Helper function for regional endpoints

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#8239]
We need a helper function (for a future PR), something like:

```cc
namespace google::cloud::dataproc {
gc::Options WithRegionalEndpoint(Options options, std::string const& region);
}
```

_Originally posted by @coryan in https://github.com/googleapis/google-cloud-cpp/pull/8231#discussion_r799474901_

**Comment by devbww** [comment]
Could this make use of the new generator support for `ServiceConfiguration.EndpointLocationStyle`?

**Comment by coryan** [comment]
> Could this make use of the new generator support for `ServiceConfiguration.EndpointLocationStyle`?

Probably.  How would the code for this `dataproc/quickstart` would look like?

**Comment by coryan** [comment]
I think the first option is more explicit and we should go with it.
