### ISSUE TITLE
Pub/Sub emulator may have crashed build

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#8252]
GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/5262894b-0080-4dd3-ae1c-1301a1acca06;tab=detail?project=cloud-cpp-testing-resources
Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/e1857fc5a3eb8a382e08cf0814e938783d27b7c3/fedora-34-cxx11-cxx11/log-5262894b-0080-4dd3-ae1c-1301a1acca06.txt

the last lines of the log are:
```
Step #3: 2022-02-04T15:32:30Z (+105s)
Step #3: ---------------------------------------------------------
Step #3: |   Running Pub/Sub integration tests (with emulator)   |
Step #3: ---------------------------------------------------------
Step #3: 2022-02-04T15:32:30Z (+105s): Launching Cloud Pub/Sub emulator in the background
```

**Comment by coryan** [comment]
More than 90d without repeat, closing.
