### ISSUE TITLE
Bigtable service unavailable on `CreateTable()`.

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#8253]
GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/76f650f0-ab20-45e3-8125-71e1567fa3b0;tab=detail?project=cloud-cpp-testing-resources
Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/88972d0b473ee7c5d93e116d32f0e6f285a79777/fedora-34-coverage/log-76f650f0-ab20-45e3-8125-71e1567fa3b0.txt

```
# Called as part of the setup for admin_iam_policy_snippets.cc, which runs against production.

google/cloud/bigtable/testing/table_integration_test.cc:78: Failure
Value of: TableAdminClient().CreateTable( bigtable::InstanceName(project_id_, instance_id_), table_id_, std::move(t))
Expected: code is equal to OK and message is anything
  Actual: 296-byte object <...>, whose status is UNAVAILABLE: Error in non-idempotent operation CreateTable: The service is currently unavailable., with a code that isn't equal to OK, but a message that is anything
```

`CreateTable()` is non-idempotent, but we would also call it "retryable on failure". If we retry on `kUnavailable`, we might receive a `kAlreadyExists` if our first attempt was successful. Our tests should treat this as a success, not a failure.

This is the same argument/idea as in #5907, but for Bigtable instead of Spanner.

**Comment by dbolduc** [comment]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/e875ee11-4de6-4eb0-adc2-2643181288a9;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/7bdc41a4f86caceff6946b9160a5119b39470513/fedora-35-integration-production/log-e875ee11-4de6-4eb0-adc2-2643181288a9.txt

**Comment by coryan** [comment]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/1e5d0846-7d32-42c8-acd3-6f3f976dfbf7;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/7a88a757bc8e9b38fb399277502eca67e1f60f16/fedora-35-libcxx/log-1e5d0846-7d32-42c8-acd3-6f3f976dfbf7.txt

**Comment by coryan** [comment]
No repeats in 90d, closing.
