### ISSUE TITLE
Consider testing with "oldest" bazel vs. "latest"

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#8259]
We may want to use the latest bazel for most of our builds.  In the majority of the Bazel builds (`*san`, `coverage`) we are using Bazel as the tool to test our code, we probably want to use the latest and greatest Bazel in those builds to take advantage of all bug fixes.

In contrast, we want to keep a "oldest" build to make sure we do not accidentally use a feature that does not exist in older Bazel's and drop backwards compatiblity.

Finally, I think we should not be using the literal `latest` here:

https://github.com/googleapis/google-cloud-cpp/blob/6d7d6c330e107030b3846180df81106e55aa5ac4/ci/cloudbuild/builds/bazel-latest.sh#L19

That means that a broken release of Bazel would break all our CI immediately.  Instead we should configure renovate bot to update the version we use to whatever happens to be Bazel's latest revision, if the PR passes we happily start using it.  If it fails we do whatever is needed and then upgrade.

**Comment by devjgm** [comment]
That all sounds like good ideas to me.
