### ISSUE TITLE
reconsider form data specific `RestClient:Post` overload

### ISSUE THREAD

**Issue by scotthart** [googleapis/google-cloud-cpp#8296]
The addition of this overload was driven by lack of a url encoding function other than `curl_easy_escape`. `curl_easy_escape` requires an easy handle which would break our encapsulation of libcurl in order to provide access to it prior to the `Post` method being called.

Rolling our own url encode/decode functions could obviate the need for this form specific overload.

**Comment by coryan** [comment]
Closing for now, if it becomes a problem we can reopen.
