### ISSUE TITLE
Return ErrorCredentials in lieu of StatusOr<Credentials>

### ISSUE THREAD

**Issue by scotthart** [googleapis/google-cloud-cpp#8401]
In `google/cloud/internal/unified_rest_credentials.cc` There are opportunities to refactor some of the helper functions to return an `ErrorCredentials` containing the `Status` rather than as part of a `StatusOr`.

**Comment by coryan** [comment]
Punt for now, will revisit later.

**Comment by coryan** [comment]
We think this is done.  Scott will write the right comment.

**Comment by coryan** [comment]
Scott will review.

**Comment by scotthart** [comment]
fixed in #8400
