### ISSUE TITLE
ObjectMetadata has incorrect published documents

### ISSUE THREAD

**Issue by emkornfield** [googleapis/google-cloud-cpp#8429]
**Does this issue affect the google-cloud-cpp project?**
The [doxygen docs](https://googleapis.dev/cpp/google-cloud-storage/latest/classgoogle_1_1cloud_1_1storage_1_1v1_1_1ObjectMetadata.html) for GCS ObjectMetadata seem misaligned.

**What component of `google-cloud-cpp` is this related to?**
GCS

**Describe the bug**
The [doxygen docs](https://googleapis.dev/cpp/google-cloud-storage/latest/classgoogle_1_1cloud_1_1storage_1_1v1_1_1ObjectMetadata.html) for GCS ObjectMetadata seem misaligned. `has_metadata()` and `metadata()` have the same documentation as `delete_metadata(...)`

**To Reproduce**
1. Read the render docs.

**Expected behavior**
Documentation that makes sense according to the method name

**Operating system:**
N/A

**What compiler and version are you using?**
N/A

**What version of `google-cloud-cpp` are you using?**
Latest website.

**Additional context**

**Comment by coryan** [comment]
Thanks for bringing this to my attention. I have a PR in flight as you probably noticed.
