### ISSUE TITLE
[Flake] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder"

### ISSUE THREAD

**Issue by devbww** [googleapis/google-cloud-cpp#8539]
I seem to be to running into this more and more often:
```
2022-03-15T07:28:48Z (+185s)
---------------------------------------------------------
|   Running Pub/Sub integration tests (with emulator)   |
---------------------------------------------------------
2022-03-15T07:28:48Z (+185s): Launching Cloud Pub/Sub emulator in the background
Cannot determine Cloud Pub/Sub emulator port.
Executing: /usr/local/google-cloud-sdk/platform/pubsub-emulator/bin/cloud-pubsub-emulator --host=localhost --port=8085
[pubsub] This is the Google Pub/Sub fake.
[pubsub] Implementation may be incomplete or differ from the real system.
[pubsub] Mar 15, 2022 7:28:56 AM com.google.cloud.pubsub.testing.v1.Main main
[pubsub] INFO: IAM integration is disabled. IAM policy methods and ACL checks are not supported
[pubsub] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[pubsub] SLF4J: Defaulting to no-operation (NOP) logger implementation
[pubsub] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[pubsub] Mar 15, 2022 7:28:59 AM com.google.cloud.pubsub.testing.v1.Main main
[pubsub] INFO: Server started, listening on 8085
Killing Pub/Sub Emulator [27984] +. done.
==> __ cxx11 completed in 194.014 seconds
```
https://www.slf4j.org/codes.html#StaticLoggerBinder

**Comment by coryan** [comment]
Seems noisy, but does it prevent anything from working?

**Comment by devbww** [comment]
> does it prevent anything from working?

The test fails, if that counts.

**Comment by coryan** [comment]
I think the SLF4J may be only tangentially related.  Maybe it slows down the startup enough that it makes the driver script here fail more often:

https://github.com/googleapis/google-cloud-cpp/blob/128b77e85d6aa9479d3781c83c1cd01ba4bb7e21/google/cloud/pubsub/ci/lib/pubsub_emulator.sh#L74-L76

But I think whether SLF4J is used or not should have no other impact.  The driver waits up to 12 seconds for the emulator to start:

https://github.com/googleapis/google-cloud-cpp/blob/128b77e85d6aa9479d3781c83c1cd01ba4bb7e21/google/cloud/pubsub/ci/lib/pubsub_emulator.sh#L34-L42

Maybe we should increase that?  Make it 5 or even 10 times longer would not hurt anything, right?

**Comment by devbww** [comment]
You're right ... I perhaps only notice those messages when there has already been a failing timeout.

I'm happy to experiment with increasing the poll time, and will report back with my findings.
