### ISSUE TITLE
storage: Add Support for Dual Region Buckets

### ISSUE THREAD

**Issue by danielbankhead** [googleapis/google-cloud-cpp#8586]
**What component of `google-cloud-cpp` is this feature request for?**
`google/cloud/storage`

**FR:** Support dual region buckets.

The method for creating a bucket should accept a string with 2 regions concatenated with a '+' (e.g. `US-EAST1+US-WEST1`).

**System tests:**
- Verify a dual region bucket with specified regions can be created
- Verify a dual region bucket's `location` metadata is the specified dual region provided
- Verify a dual region bucket's `locationType` metadata is `dual-region`

[Internal] For details and coordination: [go/gcs-dpe-dual-region-milestones](http://go/gcs-dpe-dual-region-milestones)

**Comment by coryan** [comment]
I am adding an example in #8595.  The library, however, seems to support dual regions without any changes.  I am closing this bug.

**Comment by danielbankhead** [comment]
Sounds good. While the library itself supports dual-region without any changes, do you think the following integration test could be updated to satisfy the integration test request?
- `NAM4` can be replaced here with a specified dual-region bucket: https://github.com/googleapis/google-cloud-cpp/blob/2688fd9b5b1ffc3daf4c66192c9d2251284d9385/google/cloud/storage/tests/bucket_integration_test.cc#L478

**Comment by coryan** [comment]
Changing that `NAM4` will not make the integration tests any worse nor better.  And FWIW, the examples run as part of the CI builds, including the new dual region example in #8595.
