### ISSUE TITLE
[Flake] CreateBackup: Read-only transaction exceeded maximum staleness

### ISSUE THREAD

**Issue by devbww** [googleapis/google-cloud-cpp#8594]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/37cbcdf5-ddb6-47f8-8685-ecfcb89fb60d;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/48d0da112ab8b542aebe8f33af4e7aaa20e6d569/fedora-34-integration-daily/log-37cbcdf5-ddb6-47f8-8685-ecfcb89fb60d.txt

Only looking at the occurrence for which we have an RPC log (the generated-admin `BackupExtraIntegrationTest.BackupRestoreWithCMEK`) ...
```
2022-03-24T08:08:36.023583825Z [DEBUG] <140361652491840> AsyncGetOperation(99) >>
  response=google.longrunning.Operation {
    name: "projects/cloud-cpp-testing-resources/instances/test-instance-13/backups/db_2022_03_24_30lil5vae_m1l6hd/operations/_auto_op_08d26f4f5526d749"
    metadata {
      type_url: "type.googleapis.com/google.spanner.admin.database.v1.CreateBackupMetadata"
      value: "\nfprojects/cloud-cpp-testing-resources/instances/test-instance-13/backups/db_2022_03_24_30lil5vae_m1l6hd\022hprojects/cloud-cpp-testing-resources/instances/test-instance-13/databases/db_2022_03_24_30lil5vae_m1l6hd\032\036\010d\022\014\010\204\305\360\221\006\020\240\247\340\344\002\032\014\010\341\315\360\221\006\020\310\322\275\306\003"
    }
    done: true
    error {
      code: 9
      message: "Read-only transaction timestamp 2022-03-24T07:49:24.748164Z has exceeded the maximum timestamp staleness"
      details {
        type_url: "type.googleapis.com/google.rpc.Help"
        value: "\nY\n\037Timestamp bounds documentation.\0226https://cloud.google.com/spanner/docs/timestamp-bounds"
      }
    }
  } (./google/cloud/internal/log_wrapper.h:196)
```
..., the transaction timestamp is 2022-03-24T07:49:24.748164Z, while the error occurs (modulo a possible ~45s polling delay) at 2022-03-24T08:08:36.023583825Z, for a delta of about 19:11.

Given that there is no user-level transaction here, I'm not sure where the "maximum staleness" originates.  So, I'll suggest that we await a reoccurrence, to see if we can gather more information, before even asking a question of the backend folks.

**Comment by scotthart** [comment]
Another occurrence on 2022/03/28
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/38643b8c7f3b792c37d7c7cd43fe352079348cec/fedora-34-integration-daily/log-760fa080-84eb-4d4c-8616-c41fd2ac9022.txt

**Comment by devbww** [comment]
#8605 temporarily tolerates the failure in CreateBackup(), until we can get some guidance from the backend folks.
