### ISSUE TITLE
[Flake] Spanner backup_integration_test timeout in integration-daily

### ISSUE THREAD

**Issue by scotthart** [googleapis/google-cloud-cpp#8616]
Timeout occured in //google/cloud/spanner/integration_tests:backup_integration_test

https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/c126d1d55295c65e04fd61da0b4bac9bb118ca72/fedora-34-integration-daily/log-f4532a47-e4b8-45d0-9ef1-1dd6c4bcf646.txt

**Comment by coryan** [comment]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/ca7a5a8b-d603-412b-8f37-8fc2b43b23c7;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/bedfd74aed8e027aaee8847de7d8f3a53ecbda65/fedora-34-integration-daily/log-ca7a5a8b-d603-412b-8f37-8fc2b43b23c7.txt

**Comment by devbww** [comment]
Transfer from #8628:

https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/b26a3594d97bd4dce5be67b84a95cc83027ba774/fedora-34-integration-daily/log-41205cf7-cb1a-47bb-9c62-ea8ced6d1e94.txt

**Comment by devbww** [comment]
Transfer from #8628:

Here is one with the decreased LRO polling-time limit, which therefore fails before the timeout, and so shows an RPC trace of what we were waiting for.

GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/3b521951-cb36-4382-87fe-4735560a633b;tab=detail?project=cloud-cpp-testing-resources
Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/ad4e1dc2b80420918f62c866cf448cde59f367ae/fedora-34-integration-daily/log-3b521951-cb36-4382-87fe-4735560a633b.txt

**Comment by coryan** [comment]
No repeats in 90d, closing.
