### ISSUE TITLE
[Flake] Spanner backup_extra_integration_test timeout in integration-daily

### ISSUE THREAD

**Issue by scotthart** [googleapis/google-cloud-cpp#8628]
https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/b26a3594d97bd4dce5be67b84a95cc83027ba774/fedora-34-integration-daily/log-41205cf7-cb1a-47bb-9c62-ea8ced6d1e94.txt

**Comment by devbww** [comment]
Here is one with the decreased LRO polling-time limit, which therefore fails before the timeout, and so shows an RPC trace of what we were waiting for.

* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/3b521951-cb36-4382-87fe-4735560a633b;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/ad4e1dc2b80420918f62c866cf448cde59f367ae/fedora-34-integration-daily/log-3b521951-cb36-4382-87fe-4735560a633b.txt

**Comment by devbww** [comment]
Closing in favor of #8616.
