### ISSUE TITLE
Fix "Library Reference" landing page

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#8682]
The "Library Reference" link for C++ at https://cloud.google.com/apis/docs/cloud-client-libraries points to https://googleapis.github.io/google-cloud-cpp/, which incorrectly lists our libraries and repos, making it look like we have very few C++ client libraries. We should probably change that link to point to https://github.com/googleapis/google-cloud-cpp/blob/main/README.md or something similar.

**Comment by coryan** [comment]
I think the new landing pages are good enough to close this bug. Feel free to reopen if we think of specific improvements.
