### ISSUE TITLE
#8605 temporarily tolerates the failure in CreateBackup(), until we can get some guidance from the backend folks.

### ISSUE THREAD

**Issue by acun87** [googleapis/google-cloud-cpp#8702]
#8605 temporarily tolerates the failure in CreateBackup(), until we can get some guidance from the backend folks.

_Originally posted by @devbww in https://github.com/googleapis/google-cloud-cpp/issues/8594#issuecomment-1083377801_

**Comment by devbww** [comment]
Hi acun87.  Is this issue supposed to add anything over #8594?
