### ISSUE TITLE
Create helper function to initialize Dialogflow CX options

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#8704]
Dialogflow uses regional endpoints **and** requires the authority to match the target endpoint:

We need something like this:

```cc
namespace gc = google::cloud;
auto DefaultOptions(std::string const& region) {
  return   gc::Options{}
          .set<gc::EndpointOption>(region + "-dialogflow.googleapis.com")
          .set<gc::AuthorityOption>(region + "-dialogflow.googleapis.com");
}
```

**Comment by devbww** [comment]
We don't need the helper function for setting the EndpointOption now. You can pass the location directly to one of the `MakeFooConnection()` functions instead.
