### ISSUE TITLE
Mounkoun

### ISSUE THREAD

**Issue by Mounkoung** [googleapis/google-cloud-cpp#8744]
**What component of `google-cloud-cpp` is this feature request for?**
For example, is this related to bigtable (i.e., something in `google/cloud/bigtable`), or GCS (i.e., something in `google/cloud/storage`)?

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by coryan** [comment]
This looks like a mistake, closing.  If I missed something feel free to reopen and edit the feature to let us know what we missed.
