### ISSUE TITLE
Network Connectivity API: `networkconnectivity.googleapis.com`

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#8761]
The [API reference](https://cloud.google.com/network-connectivity/docs/reference/networkconnectivity/rest) only mentions REST...

But here is a public proto: https://github.com/googleapis/googleapis/blob/7bc124cb895a4131f2a6338661db0566e272bd25/google/cloud/networkconnectivity/v1/hub.proto#L54

**Comment by coryan** [comment]
IAM has the same problem.  I think when gRPC is a documented API it definitely works, but sometimes it works even if undocumented.

**Comment by coryan** [comment]
The operator should try again.
