### ISSUE TITLE
Make `bigtable::RowReader` mockable

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#8797]
- [x] refactor class into a pimpl class
- [ ] add MockRowReader factory function

This is mostly done in: https://github.com/googleapis/google-cloud-cpp/compare/main...dbolduc:mockable-row-reader

... except we want to call the current implementation: `LegacyRowReaderImpl` (and leave `DefaultRowReaderImpl` for the implementation that interacts with a Stub)

**Comment by dbolduc** [comment]
For the record, I am going back and forth on which namespace to put `MakeMockRowReader()` in. I will develop it in the `bigtable_internal` namespace until it is needed anywhere. I am leaning towards Option B (listed below).

I am pretty sure I want to have `MockRowReaderImpl` in `bigtable_internal` namespace. I would like to use that impl to return `kUnimplemented` in the base connection. I think I will also want to call it in order to construct a default `RowReader` (#8892).

<hr />

**Option A**: in the normal namespace

```c++
/// file: bigtable/row_reader.h
namespace google::cloud::bigtable {
RowReader MakeMockRowReader(std::vector<StatusOr<Row>> expected_rows) {
  auto impl = std::make_shared<bigtable_internal::MockRowReaderImpl>(std::move(expected_rows));
  return bigtable_internal::MakeRowReader(std::move(impl));
}
}  // namespace google::cloud::bigtable
```

**Option B**: in `bigtable_internal` and `bigtable_mocks`

```c++
// file: bigtable/row_reader.h
namespace google::cloud::bigtable_internal {
bigtable::RowReader MakeRowReader(std::vector<StatusOr<bigtable::Row>> values);
  auto impl = std::make_shared<MockRowReaderImpl>(std::move(expected_rows));
  return MakeRowReader(std::move(impl));
}  // namespace google::cloud::bigtable_internal
```

```c++
// file: bigtable/mocks/mock_row_reader.h
// built with `google_cloud_cpp_bigtable_mocks`
namespace google::cloud::bigtable_mocks {
bigtable::RowReader MakeMockRowReader(std::vector<StatusOr<bigtable::Row>> expected_rows) {
  return bigtable_internal::MakeRowReader(expected_rows):
}
}  // namespace google::cloud::bigtable_mocks
```

**Comment by coryan** [comment]
I think the options are:

- Do you think application developers will *need* this function to mock things?  Then it goes into `bigtable_mocks` and it becomes part of our public API.
- Do we just need it for our own tests?  Then it goes into `bigtable_testing`.

**Comment by dbolduc** [comment]
My only hesitation towards putting it in `g::c::bigtable_mocks` is that it's not a gMock object. I still think Option B makes the most sense.

Adding a factory function in `g::c::bigtable` that is only relevant for testing (Option A) is probably dumb.
