### ISSUE TITLE
Rename bigtable_samples_instance_admin_ext file.

### ISSUE THREAD

**Issue by manish-qlogic** [googleapis/google-cloud-cpp#881]
Renaming file for better readability.

* Rename `bigtable_samples_instance_admin` to `bigtable_instance_admin_snippets`.
* Rename `bigtable_samples_instance_admin_ext` to `bigtable_samples_instance_admin`

**Comment by rsimion** [comment]
@coryan 
What about this one?
Close it or do it?

**Comment by coryan** [comment]
Sounds like a good cleanup, go for it.
