### ISSUE TITLE
Consider supporting `BackoffPolicyOption` in Pub/Sub Lite

### ISSUE THREAD

**Issue by 18suresha** [googleapis/google-cloud-cpp#8819]
This discussion was skipped in https://github.com/googleapis/google-cloud-cpp/pull/8736 to prevent blocking the PR.

**Comment by coryan** [comment]
Punt on this for now.

**Comment by coryan** [comment]
We do not have plans to work on this, but when we retake work in the Pub/Sub Lite library we should reconsider.
