### ISSUE TITLE
Kokoro can't open file `kokoro_log_reader.py`

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#8839]
https://source.cloud.google.com/results/invocations/e503f1ca-d90a-4db8-95c3-ed9bb8c58539

```
/Users/kbuilder/.pyenv/versions/3.8.3/bin/python3: can't open file '/tmpfs/kokoro_log_reader.py': [Errno 2] No such file or directory
```

This occurence was on macOS. Note that the problem has also happened on Windows: https://github.com/googleapis/google-cloud-cpp/issues/4363#issuecomment-682315087

**Comment by scotthart** [comment]
https://source.cloud.google.com/results/invocations/0e8e8d40-eb55-4ede-ba15-dc3d857c5ecf

```
/Users/kbuilder/.pyenv/versions/3.8.3/bin/python3: can't open file '/tmpfs/kokoro_log_reader.py': [Errno 2] No such file or directory
```

**Comment by coryan** [comment]
No repeats in 90d, closing.
