### ISSUE TITLE
Document `FooConnection`, `MakeFooConnection` in generator

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#8863]
https://github.com/googleapis/google-cloud-cpp/blob/d405ec7691611a8a687d2bf9f69dcc21a9171455/google/cloud/accessapproval/access_approval_connection.h#L48-L49
https://github.com/googleapis/google-cloud-cpp/blob/d405ec7691611a8a687d2bf9f69dcc21a9171455/google/cloud/accessapproval/access_approval_connection.h#L88-L90
https://github.com/googleapis/google-cloud-cpp/blob/08f1d4a76d92d79c8a5200a3c13e4453e8ad29a4/google/cloud/accessapproval/mocks/mock_access_approval_connection.h#L29-L30

As @coryan points out, these are in the public API and thus they should be documented.

**Comment by coryan** [comment]
We do not need to generate detailed documentation for these, a reference to a generic document about the role of the `*Connection` class would do.  Maybe something like:

```
/**
 * The `*Connection` object for `AccessApprovalClient`.
 *
 * Use this class to mock the client class in your tests.
 * 
 * @see https://<somewhere> for a general description of how `*Client` and `*Connection` classes can be used in
 *      unit tests.
 */
class AccessApprovalConnection ...
```
