### ISSUE TITLE
Segfault or Uncommitted GCS Object in ResumableUpload

### ISSUE THREAD

**Issue by Jseph** [googleapis/google-cloud-cpp#8868]
**Does this issue affect the google-cloud-cpp project?**
Yes

**What component of `google-cloud-cpp` is this related to?**
GCS

**Describe the bug**
There appears to be an edge case where calls to ObjectWriteStream::Close result in a stream that is still in a good and open state.  A subsequent call to Close will result in a segfault.  I've been working on debugging a core dump and I think I've figured out how this happens.

**To Reproduce**
1. Create a resumable upload ObjectWriteStream write_stream
2. Write `N` bytes to the internal buffer
3. Call Close()
4. Call write_stream.IsOpen() returns true
5. Call write_stream.good() returns true
6. Call Close()
7. segfault

Here's what I think is happening during step 3 that gets the stream into this state.  Sorry if some of this ends up a bit stale due to the ongoing refactor but AFAICT it's still an issue in the live version of the code.

1. [FlushFinal()](https://github.com/googleapis/google-cloud-cpp/blob/143a5d7ce4c553d1e1bbb48b9ea5141932c323a0/google/cloud/storage/internal/object_write_streambuf.cc#L135) is called.
2. [hash_function_](https://github.com/googleapis/google-cloud-cpp/blob/143a5d7ce4c553d1e1bbb48b9ea5141932c323a0/google/cloud/storage/internal/object_write_streambuf.cc#L144) is moved and can no longer be used.
3. client_->UploadChunk() is called with a request to upload the bytes in the buffer and finalize the upload.
4. This is handled by [RetryClient::UploadChunk](https://github.com/googleapis/google-cloud-cpp/blob/143a5d7ce4c553d1e1bbb48b9ea5141932c323a0/google/cloud/storage/internal/retry_client.cc#L433).
5. Attempt to upload and finalize the object fails with a retirable error.  Behind the scenes GCS succeeded in committing the provided bytes, but failed to finalize the upload session and actually create the GCS object.
6. The status of the upload session is queried and GCS replies that the upload is in progress with all `N` bytes written.
7. [This line](https://github.com/googleapis/google-cloud-cpp/blob/143a5d7ce4c553d1e1bbb48b9ea5141932c323a0/google/cloud/storage/internal/retry_client.cc#L553) determines that the upload was successful and returns the result.  Note that the upload is still in progress.
8. Since response was good [last_status_](https://github.com/googleapis/google-cloud-cpp/blob/143a5d7ce4c553d1e1bbb48b9ea5141932c323a0/google/cloud/storage/internal/object_write_streambuf.cc#L152) is set to a good and in progress state.
9. I'm not sure what happens [here](https://github.com/googleapis/google-cloud-cpp/blob/143a5d7ce4c553d1e1bbb48b9ea5141932c323a0/google/cloud/storage/internal/object_write_streambuf.cc#L155) because it's different than the code I was testing, but it's a bug either way because either `IsOpen()` will still evaluate to `true` even though the stream was closed, or the stream will claim it has closed successfully despite the destination object not being created.  Pretty sure metadata will be nullopt and the stream stays open but I haven't traced that behavior to be sure.

**Expected behavior**
When the final chunk is uploaded the client library should retry until the resumable upload session is closed or return an error and put the stream in a bad state.

**Operating system:**
Na

**What compiler and version are you using?**
Na

**What version of `google-cloud-cpp` are you using?**
I was debugging a core with gcloud-cpp/v1.40.0 but I think this is still present in the most recent code.

**Additional context**
Please ping me if you need any additional info on this.

**Comment by coryan** [comment]
Where you say:

> 6. The status of the upload session is queried and GCS replies that the upload is in progress with all `N` bytes written.
> 7. [This line](https://github.com/googleapis/google-cloud-cpp/blob/143a5d7ce4c553d1e1bbb48b9ea5141932c323a0/google/cloud/storage/internal/retry_client.cc#L553) determines that the upload was successful and returns the result. Note that the upload is still in progress.

That implies this condition was false:

https://github.com/googleapis/google-cloud-cpp/blob/143a5d7ce4c553d1e1bbb48b9ea5141932c323a0/google/cloud/storage/internal/retry_client.cc#L497

In other words, it seems that querying the resumable upload returned "all bytes committed", and (presumably) the upload is finalized *but* there was no object payload?  For some reason, I did not expect that to be a thing...

Do you know if this query return a 308 or a 200 (or 201) response?  I guess we could try again on a 308 with a missing object, or we could query the object metadata explicitly (though that seems like could be problematic too).

FWIW, when I do a query [1] for a completed upload, the service does seem to return a payload:


[1]: By a "query" I mean https://cloud.google.com/storage/docs/performing-resumable-uploads#status-check for example:

```
curl -i -d "" -H "Content-Range: */*" -X PUT "https://storage.googleapis.com/upload/storage/v1/b/coryan-test-bucket/o?uploadType=resumable&name=resumable-test-001.txt&upload_id=[censored]

HTTP/2 200 
x-guploader-uploadid: [censored]
etag: CMDi5NG3xPcCEAE=
content-type: application/json; charset=UTF-8
date: Tue, 03 May 2022 23:00:39 GMT
vary: Origin
vary: X-Origin
cache-control: no-cache, no-store, max-age=0, must-revalidate
expires: Mon, 01 Jan 1990 00:00:00 GMT
pragma: no-cache
content-length: 775
server: UploadServer

{
  "kind": "storage#object",
  "id": "coryan-test-bucket/resumable-test-001.txt/1651618839343424",
  "selfLink": "https://www.googleapis.com/storage/v1/b/coryan-test-bucket/o/resumable-test-001.txt",
  "mediaLink": "https://storage.googleapis.com/download/storage/v1/b/coryan-test-bucket/o/resumable-test-001.txt?generation=1651618839343424&alt=media",
  "name": "resumable-test-001.txt",
  "bucket": "coryan-test-bucket",
  "generation": "1651618839343424",
  "metageneration": "1",
  "storageClass": "MULTI_REGIONAL",
  "size": "1",
  "md5Hash": "M21evFQ2U05h0W5j3fyjJw==",
  "crc32c": "zeiRXA==",
  "etag": "CMDi5NG3xPcCEAE=",
  "timeCreated": "2022-05-03T23:00:39.388Z",
  "updated": "2022-05-03T23:00:39.388Z",
  "timeStorageClassUpdated": "2022-05-03T23:00:39.388Z"
}

```

**Comment by Jseph** [comment]
Unfortunately the upload that experienced this is more than 7 days old but I may be able to get access to some internal logs to see what was returned.

From the core dump I can see the contents of last_response_ (this is old code).

```
upload_state = google::cloud::storage::v1_40_0::internal::ResumableUploadResponse::kInProgress,
                    committed_size = {<std::__u::__optional_move_assign_base<unsigned long, true>> = {<std::__u::__optional_copy_assign_base<unsigned long, true>> = {<std::__u::__optional_move_base<unsigned long, true>> = {<std::__u::__optional_copy_base<unsigned long, true>> = {<std::__u::__optional_storage_base<unsigned long, false>> = {<std::__u::__optional_destruct_base<unsigned long, true>> = {{__null_state_ = 109 'm', __val_ = 365}
```

I can also see that `payload` appears to be uninitialized.

Because `upload_state = kInProgress` it means GCS returned a status code that wasn't `200` or `201` so I assume they returned `308` because (I'm speculating) the upload isn't handled atomically, it's done in 2 parts. Part 1 is they commit the bytes to the temporary buffer, Part 2 they create the object in GCS storage and finalize the upload.  I think what happened here is part 1 succeeded but part 2 timed out so when we query the state we get to total bytes uploaded as expected but the upload session still hasn't been finalized.

**Comment by coryan** [comment]
I have created a unit test to repro this problem (see https://github.com/coryan/google-cloud-cpp/commit/6a49043573851d7bb4bcb28d39b9b6d751610ffd).  The question is how to fix it.

- I can change the retry layer to continue querying (for final chunks) until the payload is not empty.  In practice this seems to work, but I cannot find any documentation that it should work.  That does not fill me with confidencen.
- I can change the code to make the upload fail with `kAborted` (like we do for other unexpected conditions), and then the application can try to resume the upload.  That seems like punting the problem to the application.

I am inclined to go with the first approach, thoughts?

**Comment by Jseph** [comment]
Either of these solutions would work for my application.  I think fixing
this at the retry layer probably makes the most sense.  I'm not sure if
just querying repeatedly will work or not.  We should probably get feedback
on this from someone more familiar with the GCS upload path.  My suspicion
is there are some cases where we actually need to do another upload with a
range header that would trigger finalizing the upload session.
