### ISSUE TITLE
Document when `GrpcNumChannelsOption` applies

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#8906]
https://github.com/googleapis/google-cloud-cpp/blob/472f20a660310973191fcb99b7fbca81ec843a47/google/cloud/grpc_options.h#L38-L47

This option only applies in certain libraries (the handwritten ones). We should make this clear.

This means documenting the option:
```
@note This option only applies to a few libraries. Check the service's `*Connection` documentation for details.
```

... and documenting the connection pool for the Connections that use it.
* `bigtable::DataConnection` (currently under development; #1553)
* `spanner::Connection`
* `pubsub::PublisherConnection`
* `pubsub::SubscriberConnection`
* `storage_experimental::DefaultGrpcClient()` (i think)

**Comment by coryan** [comment]
Just fixing the existing comment seems good enough.
