### ISSUE TITLE
Could not find a package configuration file provided by "google_cloud_cpp_rest_internal"

### ISSUE THREAD

**Issue by SamuelMarks** [googleapis/google-cloud-cpp#8919]
**Does this issue affect the google-cloud-cpp project?**
vcpkg @ [`a5d6d1`](https://github.com/microsoft/vcpkg/tree/a5d6d145164e82e67fbf91a4a30f98699d30de63)

**What component of `google-cloud-cpp` is this related to?**
```json
"dependencies": [
    {
      "name": "google-cloud-cpp",
      "default-features": true,
      "features": [
        "storage"
      ]
    }
  ]
```

**Describe the bug**
```
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:824 (_find_package):
  By not providing "Findgoogle_cloud_cpp_rest_internal.cmake" in
  CMAKE_MODULE_PATH this project has asked CMake to find a package
  configuration file provided by "google_cloud_cpp_rest_internal", but CMake
  did not find one.

  Could not find a package configuration file provided by
  "google_cloud_cpp_rest_internal" with any of the following names:

    google_cloud_cpp_rest_internalConfig.cmake
    google_cloud_cpp_rest_internal-config.cmake

  Add the installation prefix of "google_cloud_cpp_rest_internal" to
  CMAKE_PREFIX_PATH or set "google_cloud_cpp_rest_internal_DIR" to a
  directory containing one of the above files.  If
  "google_cloud_cpp_rest_internal" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.23.1/share/cmake/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  cmake-build-debug/vcpkg_installed/x64-osx/share/google_cloud_cpp_storage/google_cloud_cpp_storage-config.cmake:16 (find_dependency)
  vcpkg/scripts/buildsystems/vcpkg.cmake:824 (_find_package)
  google_cloud_bucket_c/CMakeLists.txt:29 (find_package)


-- Configuring incomplete, errors occurred!
See also "google-cloud-bucket-c/cmake-build-debug/CMakeFiles/CMakeOutput.log".
See also "google-cloud-bucket-c/cmake-build-debug/CMakeFiles/CMakeError.log".
```

**To Reproduce**
1. `git clone --depth=1 https://github.com/offscale/google-cloud-bucket-c`
2. `mkdir google-cloud-bucket-c/build && cd "$_"`
3. `cmake -DCMAKE_TOOLCHAIN_FILE='[root]/vcpkg/scripts/buildsystems/vcpkg.cmake' -DCMAKE_BUILD_TYPE='Debug' ..`
4. `cmake --build .`
5. See error

Or if you don't want to use my package, then use the aforementioned `vcpkg.json` with:
```cmake
find_package(google_cloud_cpp_storage CONFIG REQUIRED)
target_link_libraries(
        "${LIBRARY_NAME}"
        PRIVATE
        "CURL::libcurl" "google-cloud-cpp::storage" "google-cloud-cpp::experimental-storage-grpc"
)
```

**Expected behavior**
No error

**Operating system:**
macOS 12.2.1 (21D62)

**What compiler and version are you using?**
```
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: x86_64-apple-darwin21.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**What version of `google-cloud-cpp` are you using?**
1.40.1

**Additional context**
This was working previously

**Comment by coryan** [comment]
Reproduced using:

```Dockerfile
FROM debian:buster

RUN apt-get update && \
    apt-get --no-install-recommends install -y apt-transport-https apt-utils \
        automake build-essential ca-certificates ccache cmake curl git \
        gcc g++ libc-ares-dev libc-ares2 libcurl4-openssl-dev libre2-dev \
        libssl-dev m4 make ninja-build pkg-config tar wget zlib1g-dev

RUN apt-get update && apt-get --no-install-recommends install -y zip unzip tar cmake ninja-build

WORKDIR /var/tmp/build/vcpkg
#              https://github.com/microsoft/vcpkg/archive/refs/heads/master.zip
RUN curl -sSL https://github.com/microsoft/vcpkg/archive/40a4e68a4f177c1569aca69bfe1ba59b8153a8a1.tar.gz | \
     tar -xzf - --strip-components=1

RUN ./bootstrap-vcpkg.sh
RUN ./vcpkg install google-cloud-cpp[core,iot]

WORKDIR /var/tmp/build/google-cloud-cpp
RUN curl -sSL https://github.com/googleapis/google-cloud-cpp/archive/refs/tags/v1.40.1.tar.gz | \
     tar -xzf - --strip-components=1

WORKDIR /var/tmp/build/google-cloud-cpp/google/cloud/iot/quickstart
RUN cmake -H. -B.build -DCMAKE_TOOLCHAIN_FILE=/var/tmp/build/vcpkg/scripts/buildsystems/vcpkg.cmake
RUN cmake --build .build
```

**Comment by coryan** [comment]
Aside: this is unrelated to this bug, some suggestions for improvement:

- Your `vcpkg.json` has `"default-features": true`, consider `false` so you can avoid compiling libraries you do not use (bigtable, spanner, pubsub, etc.) and their dependencies (protobuf and  gRPC).
- I am not sure why vcpkg recommends `google-cloud-cpp::experimental-storage-grpc` for `target_link_libraries()`.  You can safely remove that unless you really want to use the gRPC plugin for GCS, but keep in mind that (1) it is not GA, as the name implies, (2) the service itself is not GA and only available if you are on an allow-list, (3) only workloads with extreme throughput needs (and I mean *extreme*) benefit from it.

**Comment by SamuelMarks** [comment]
Thanks for addressing this + making a self-contained replica

On the aside:

  - yeah I think originally I had an error when I had `"default-features": false` and because of the slow build times I didn't investigate to fix
  - actually I would benefit from extreme workloads, my client actually is expecting huge throughput (video files, that are then processed through ML). Should apply for being added to that list [know anyone? :P]

**Comment by coryan** [comment]
The `vcpkg` folks just merged my patch, closing.
