### ISSUE TITLE
AsyncWaitConnectionReady deadline exceeded on macOS (cmake-vcpkg)

### ISSUE THREAD

**Issue by devjgm** [googleapis/google-cloud-cpp#8932]
https://source.cloud.google.com/results/invocations/0f1bdb28-13d0-474c-a54a-06e17da99e13/targets

```
[ RUN      ] CompletionQueueTest.SuccessfulWaitingForConnection
../../google/cloud/internal/async_connection_ready_test.cc:80: Failure
Value of: cli_cq .AsyncWaitConnectionReady(channel, std::chrono::system_clock::now() + std::chrono::seconds(1)) .get()
Expected: code is equal to OK and message is anything
  Actual: DEADLINE_EXCEEDED: Connection couldn't connect before requested deadline (of type google::cloud::v1_41_0::Status), with a code that isn't equal to OK, but a message that is anything
E0509 13:53:38.896633000 4423249344 completion_queue_cc.cc:135]        CompletionQueue shutdown being shutdown before its server.
[  FAILED  ] CompletionQueueTest.SuccessfulWaitingForConnection (1005 ms)
```

**Comment by scotthart** [comment]
https://source.cloud.google.com/results/invocations/058437f2-5b07-4166-aa07-401174f19cc0

[ RUN      ] CompletionQueueTest.SuccessfulWaitingForConnection
[../../google/cloud/internal/async_connection_ready_test.cc:80](https://cs.corp.google.com/piper///google/cloud/internal/async_connection_ready_test.cc?l=80): Failure
Value of: cli_cq .AsyncWaitConnectionReady(channel, std::chrono::system_clock::now() + std::chrono::seconds(1)) .get()
Expected: code is equal to OK and message is anything
  Actual: DEADLINE_EXCEEDED: Connection couldn't connect before requested deadline (of type google::cloud::v1_42_0::Status), with a code that isn't equal to OK, but a message that is anything
E0606 16:23:34.594974000 4669550016 completion_queue_cc.cc:135]        CompletionQueue shutdown being shutdown before its server.
[  FAILED  ] CompletionQueueTest.SuccessfulWaitingForConnection (1008 ms)

**Comment by coryan** [comment]
No repeats in 90d, closing.
