### ISSUE TITLE
macOS server terminated abruptly. Socket Closed.

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#8956]
This was on our macOS bazel build. Seems like a Kokoro problem.
```
Server terminated abruptly (error code: 14, error message: 'Socket closed', log file: '/private/var/tmp/_bazel_kbuilder/958e32d54e02d3b435828e68d1d5184e/server/jvm.out')
```

https://source.cloud.google.com/results/invocations/8d756584-0538-4f6d-9d07-b83cc1ff0265

Looks like this happened once before on a cmake build: https://github.com/googleapis/google-cloud-cpp/issues/3645#issuecomment-1049157715

**Comment by coryan** [comment]
No repeats in 90d, closing.
