### ISSUE TITLE
google storage client json throw exception when http request fails

### ISSUE THREAD

**Issue by dentiny** [googleapis/google-cloud-cpp#8965]
**What component of `google-cloud-cpp` is this related to?**
GCS

**Describe the bug**
When http response fails, it would rely on json library to get detailed error message.
Code here: https://github.com/googleapis/google-cloud-cpp/blob/643fa047a549422ebaa40f9173ab0c2c8372aede/google/cloud/storage/internal/http_response.cc#L172

Sample http response-1:
```
{\"error\":\"invalid_grant\",\"error_description\":\"Invalid grant: account not found\"}
```
Exception stacktrace:
```
terminate called after throwing an instance of 'nlohmann::detail::type_error'
  what():  [json.exception.type_error.306] cannot use value() with string
```
Using some logging, the exception happens: https://github.com/googleapis/google-cloud-cpp/blob/643fa047a549422ebaa40f9173ab0c2c8372aede/google/cloud/storage/internal/http_response.cc#L189

Sample http response-2:
```
Service Unavailable
```
Exception stacktrace:
```
terminate called after throwing an instance of 'nlohmann::detail::type_error'
  what():  [json.exception.type_error.306] cannot use value() with string
```
With some logging the error happens:
https://github.com/googleapis/google-cloud-cpp/blob/643fa047a549422ebaa40f9173ab0c2c8372aede/google/cloud/storage/internal/http_response.cc#L175

**Expected behavior**
No exception would be thrown.

**Operating system:**
ubuntu 20

**What compiler and version are you using?**
clang v13.0.0

**What version of `google-cloud-cpp` are you using?**
v1.38.0

**Additional information**
I tried to reproduce locally with the above error response, but cannot repro it.
I want you to give me some intuitions.

**Comment by coryan** [comment]
Ugh... that seems like an invalid message returned by the service, but the library should not raise or crash when that happens.

**Comment by dentiny** [comment]
@coryan Thank you for quick reply! One thing I'm not sure, why exception is not thrown with my local run, with the same json library? Does that mean json library keeps some state when parsing? Thank you!

**Comment by coryan** [comment]
Sorry I missed the `response-2` case, I think it is still fixed, but I should have added some test cases:

> 1. why exception is not thrown with my local run, with the same json library? Does that mean json library keeps some state when parsing?

It is hard to say.  You did not mention what was the difference between your "local" run vs. the run where you saw these problems?  Are the environments different (GCE vs. on-prem?  user account vs. service account for authentication?) At a guess you are getting no error messages, or different error messages, in each environment and some of them are parseable.

> 2. Even with your fix, this line of code would still throw exception, could you please take a look my above error message?

`nlohman::json::parse(..., ..., false)` should not throw. The third parameter is called "`allow_exceptions`":

https://json.nlohmann.me/api/basic_json/parse/

I just tested with both `Service Unavailable` and `"Service Unavailable"` and both parse as I would expect.  I will send a PR with the new test cases.

**Comment by dentiny** [comment]
@coryan 

My local run is something like 
```
#include "nlohmann/json.hpp"

#include <string>

int main() {
  std::string error_http_response_1 = "Service Unavailable";

  std::string error_response_2 = R"(<!DOCTYPE html>
  <html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 502 (Server Error)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>502.</b> <ins>That’s an error.</ins>
  <p>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.  <ins>That’s all we know.</ins>)";

std::string error_response_3 = "{\"error\":\"invalid_grant\",\"error_description\":\"Invalid grant: account not found\"}";

  auto json = nlohmann::json::parse(error_response_2, nullptr, false);
  if (!json.is_object()) return 0;
  [[maybe_unused]] auto error = json.value("error", nlohmann::json::object());
  return 0;
```

None of the three error response throws exception in my local run, but all of them would lead to exception in prod env.

**Comment by coryan** [comment]
FWIW, I added the additional test cases.  I also went through the code guarding against parsing problems.  Without additional information I can only speculate about why you are seeing problems in production but not locally (different `nlomann::json` version?  maybe the exception is raised elsewhere?).  If you collect more detailed info please open a new bug with those details.
