### ISSUE TITLE
Sample code and quickstarts should print full errors

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#9016]
Our sample/quickstart code only prints the error message, discarding the error code and error info. They look something like this (in the `StatusOr<>` case):
https://github.com/googleapis/google-cloud-cpp/blob/08f1d4a76d92d79c8a5200a3c13e4453e8ad29a4/google/cloud/accessapproval/quickstart/quickstart.cc#L31

Printing the full error gives customers more information to debug issues they might encounter. Our sample/quickstart code should reflect the code we want our customers to write.

We can just make this public: https://github.com/googleapis/google-cloud-cpp/blob/08f1d4a76d92d79c8a5200a3c13e4453e8ad29a4/google/cloud/status.cc#L22-L26
... and do a tedious find and replace.

- [x] Fix `examples/`
- [x] Fix `google/cloud/bigquery/samples/`
- [x] Fix `google/cloud/iam/samples/`
- [x] Fix `google/cloud/pubsub/samples/`
- [x] Fix `google/cloud/bigtable/examples/`
- [x] Fix `google/cloud/storage/examples/`

**Comment by devbww** [comment]
How about throwing the whole `Status` value, and then just streaming it when caught?

**Comment by coryan** [comment]
We will start fixing these as we see them.

**Comment by coryan** [comment]
Consider breaking this bug into smaller bugs (one per service?) to make them easier to handle.

**Comment by Qarthak** [comment]
@coryan @devbww Is this issue closed? I'm new to open source and coming from a C/C++ background I think I can work on this. But from what I know, a merge means the issue has been handled right?

**Comment by coryan** [comment]
> But from what I know, a merge means the issue has been handled right?

Some teams break down larger bugs into smaller issues that can be solved in a single PRs.  Some go as far as *requiring* that a PR fixes exactly one bug.  We do neither.  Many issues are resolved by a single PR, some larger issues require multiple small PRs to resolve.

Generally, we let each person follow whatever approach works best for organizing / planning their development.

@Qarthak if you need some help breaking this down, this outline may help:

- [ ] Fix `examples/`
- [ ] Fix `google/cloud/bigquery/samples/`
- [ ] Fix `google/cloud/iam/samples/`
- [ ] Fix `google/cloud/pubsub/samples/`
- [ ] Fix `google/cloud/bigtable/examples/`
- [ ] Fix `google/cloud/storage/examples/`

I got that using:

```
git grep 'throw.*message()'  | awk '{print $1}' | xargs -I{} dirname {} | sort | uniq -c
      5 examples
      5 google/cloud/bigquery/samples
    156 google/cloud/bigtable/examples
     26 google/cloud/iam/samples
     45 google/cloud/pubsub/samples
    207 google/cloud/storage/examples
```

**Comment by Qarthak** [comment]
@coryan @devbww I am currently running `cmake --build cmake-out/home`, as per [Dev Workstation Setup Guide](https://github.com/Qarthak/google-cloud-cpp/blob/main/doc/contributor/howto-guide-setup-development-workstation.md) but I have seen some optional setup like [Enable clang-based tooling in your IDE](https://github.com/Qarthak/google-cloud-cpp/blob/main/doc/contributor/howto-guide-setup-development-workstation.md#optional-enable-clang-based-tooling-in-your-ide). I'm not sure how much setup is required for this issue. Do I need to follow [Working with Bazel and CMake](https://github.com/Qarthak/google-cloud-cpp/blob/main/doc/contributor/working-with-bazel-and-cmake.md). The project has added a whopping ~35GBs on my system so I want to make sure I'm following the right steps.

**Comment by coryan** [comment]
Maybe read about how to run the formatting scripts: 

https://github.com/googleapis/google-cloud-cpp/tree/main/doc/contributor

I know 35GB feels like a lot, but I stopped worrying about this a long time ago.

**Comment by Qarthak** [comment]
Here's what I've done so far:

- Installed the dependencies 
- Installed Google Cloud SDK
- Cloned and compiled the code 

Can I start working on the code now? Once I have made the correct changes, I need to run the integration tests for Google Cloud Storage and Google Cloud Bigtable to make sure my changes don't break anything. I'll also make sure my code is correctly formatted using the formatting scripts. After that, can I make a PR or am I missing something?

**Comment by coryan** [comment]
Looks like you are ready to start, yes.  Worst case we discover that you need some other tool / configuration, but you can add those at that time.

**Comment by Qarthak** [comment]
@coryan I got a mail telling me to sign a CLA and I just did. This is my first PR to an open source org and I don't know how to redo the the CLA test?

**Comment by coryan** [comment]
I just re-ran the CLA test for you, all clear!

**Comment by Qarthak** [comment]
@coryan, while running `sudo ci/cloudbuild/build.sh -t clang-tidy-pr --docker` I get this. 
```
2022-10-28T08:53:09Z (+2s): + docker run --interactive --tty=true --rm --network=bridge --user=0:0 --env=PS1=docker:fedora-36\$\  --env=USER=root --env=TERM=xterm-256color --env=TZ=UTC0 --env=CI_LIB_IO_FIRST_TIMESTAMP=1666947187 --env=CODECOV_TOKEN= --env=BRANCH_NAME= --env=COMMIT_SHA=7f850251b5795674be31a845ed64d3d5b6d9f4b4 --env=TRIGGER_TYPE=manual --env=VERBOSE_FLAG=false --env=USE_BAZEL_VERSION= --volume=/workspace/build-out --volume=/home/sarthak/google-cloud-cpp:/workspace:Z --workdir=/workspace --volume=/home/sarthak/google-cloud-cpp/build-out/fedora-36-clang-tidy/cmake-out:/workspace/cmake-out:Z --volume=/home/sarthak/google-cloud-cpp/build-out/fedora-36-clang-tidy/h:/h:Z --env=HOME=/h --volume=/root/.config/gcloud:/h/.config/gcloud:Z gcb-fedora-36:latest ci/cloudbuild/build.sh --local --build clang-tidy
fatal: detected dubious ownership in repository at '/workspace'
To add an exception for this directory, call:

	git config --global --add safe.directory /workspace

2022-10-28T08:53:09Z (+2s)
========================================
|   Starting local build: clang-tidy   |
========================================
2022-10-28T08:53:09Z (+2s): Using CMake version
cmake version 3.22.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
2022-10-28T08:53:09Z (+2s): Clearing ccache stats
Statistics zeroed
2022-10-28T08:53:09Z (+2s): Checking for a valid git environment...
2022-10-28T08:53:09Z (+2s): Creating a git repository
warning: re-init: ignored --initial-branch=ephemeral-branch
Reinitialized existing Git repository in /workspace/.git/
fatal: --local can only be used inside a git repository
==> 🕑 clang-tidy completed in 0.132 seconds
```
I looked it up and none of the solutions seem to work. `Git init` doesn't help since we're already inside a git repository and `git config --global --add safe.directory /workspace` doesn't help either. Maybe these changes are not taking place inside the docker container?

**Comment by coryan** [comment]
> fatal: detected dubious ownership in repository at '/workspace'
> To add an exception for this directory, call:
>     git config --global --add safe.directory /workspace

Hmmm... I have never seen that error before.  I am just saying that to warn you that we will be doing some troubleshooting together, I will be learning how to fix this with you.  Seems like you are running this as `root`:

> `sudo ci/cloudbuild/build.sh ...`
> --user=0:0 

Is it possible for you to configure [sudo-less docker](https://docs.docker.com/engine/install/linux-postinstall/) and try again?  I suspect `git` does not like to work on directories owned by root for some reason.

**Comment by coryan** [comment]
This is now fixed.
