### ISSUE TITLE
Do not allow 'using directives' in header or source files.

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#910]
We need to change the `ci/check-style.sh` script to break the build if a using directive is introduced. See #908 for more details.

cc: @houglum

**Comment by coryan** [comment]
@devjgm Would it be as simple as grepping for `using namespace` in the header+source files and failing the build if we ever have one of those?

**Comment by devjgm** [comment]
I think we could do this with a few greps. I don't want to be overly strict, but a check-style script to prevent accidental checkins would be good.

**Comment by coryan** [comment]
Actually, I just found the magic clang-tidy(1) option:

```patch
diff --git a/.clang-tidy b/.clang-tidy
index e3b256df9..db77d15ed 100644
--- a/.clang-tidy
+++ b/.clang-tidy
@@ -7,6 +7,7 @@
 Checks: >-
   bugprone-*,
   google-readability-*,
+  google-build-using-namespace,
   misc-*,
   modernize-*,
   readability-*,
```

And then compile with:

```bash
CHECK_STYLE=yes GENERATE_DOCS=yes CMAKE_FLAGS=-DGOOGLE_CLOUD_CPP_CLANG_TIDY=yes DISTRO=ubuntu DISTRO_VERSION=18.04 CXX=clang++ CC=clang NCPU=$(nproc) TRAVIS_OS_NAME=linux ./ci/travis/build-linux.sh 
```

There are too many errors to introduce the flag easily. We should also consider enabling `google-*` (though a few might be hard).

**Comment by devjgm** [comment]
We've now enabled `google-*`, which includes the tidy warning for this. So it looks like this issue has been addressed.

https://github.com/googleapis/google-cloud-cpp/blob/20bda61b7b9d33d1c669a7d9e5337bd838a573fb/.clang-tidy#L36
