### ISSUE TITLE
[Flake] Permanent error in CreateBucket: Bucket name is invalid

### ISSUE THREAD

**Issue by devbww** [googleapis/google-cloud-cpp#9106]
```
[ RUN      ] BucketIntegrationTest.NativeIamCRUD
google/cloud/storage/tests/bucket_integration_test.cc:799: Failure
Value of: meta
Expected: code is equal to OK and message is anything
  Actual: 712-byte object <E0-9E 22-02 00-00 00-00 00-22 53-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 ... 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00 00-00>, whose status is INVALID_ARGUMENT: Permanent error in CreateBucket: {"error":{"code":400,"message":"{\"error\": {\"errors\": [{\"domain\": \"global\", \"message\": \"Bucket name cloud-cpp-testing-2022-05-30_xzeg5fhpmld3mtl82ubkdj65s0nug00gl3 is invalid.\"}]}}"}}
, with a code that isn't equal to OK, but a message that is anything
```

* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/c10f198c-011c-443f-ac15-d49a6602ee84;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/678a3d3414090de61c17f08178196444d10abe34/fedora-35-xsan/log-c10f198c-011c-443f-ac15-d49a6602ee84.txt

Something similar in #4917.

**Comment by coryan** [comment]
Ah... I see what happened here.  The random section contains `g00gl3` which is one of the prohibited sub-strings (too similar to `google` or `goog`):

https://cloud.google.com/storage/docs/naming-buckets

It is not a common occurrence (as was about to close this bug for staleness), but it is also easy to fix.
