### ISSUE TITLE
[Flake] kokoro macOS truncated gzip input downloading vcpkg

### ISSUE THREAD

**Issue by devbww** [googleapis/google-cloud-cpp#9138]
```
2022-06-02T04:40:13Z (+1506s): Downloading vcpkg into /Users/kbuilder/vcpkg-quickstart...
tar: truncated gzip input
tar: Error exit delayed from previous errors.
2022-06-02T04:40:18Z (+1511s): build script reported errors.
```
https://source.cloud.google.com/results/invocations/56f7b3cf-3430-48c0-8451-f680fa1f73d6

**Comment by coryan** [comment]
The code that generated this is:

https://github.com/googleapis/google-cloud-cpp/blob/e2802d1d681f27fcd377872a12082c7354645df6/ci/kokoro/macos/builds/cmake-vcpkg.sh#L43-L44

Seems like another case of a download from GitHub failing, despite retrying.  See #8102 for some ideas on how to mitigate these problems.

**Comment by coryan** [comment]
No repeats in 90d, closing.

**Comment by coryan** [comment]
http://sponge2.corp.google.com/8ae89e6a-d0a8-42a9-9ba4-afb1bc603700

**Comment by coryan** [comment]
The problem might be that we retry the download, but sometimes GitHub returns nonsense and the download succeeds, but the data is useless.

**Comment by coryan** [comment]
One possible fix is to create backups for these tarballs in GCS.
Closing for now as there have been no repeats in over 90d.
