### ISSUE TITLE
Consider dropping or simplifying `ConnectionImpl::*_policy()` getters

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#9168]
We do not need the `else` branch that uses the connection's `options_` in this code:
https://github.com/googleapis/google-cloud-cpp/blob/292265193edcbe6737cde4053145610a5f3e267d/google/cloud/tpu/internal/tpu_connection_impl.h#L89-L119

These policy options are defaulted in the connection, and passed back to the client. This means that any `OptionsSpan` the client creates will have the policy options we should use present.

We may need to update some unit tests for the `ConnectionImpl`s which do not have a client present to create such a span.

**Comment by devbww** [comment]
> We may need to update some unit tests for the `ConnectionImpl`s which do not have a client present to create such a span.

For the record, here is the comment that describes the current behavior of those tests.

https://github.com/googleapis/google-cloud-cpp/blob/292265193edcbe6737cde4053145610a5f3e267d/generator/internal/connection_impl_generator.cc#L113-L117

**Comment by coryan** [comment]
@dbolduc thinks there is not enough value. Closing.

**Comment by coryan** [comment]
This is now fixed.
