### ISSUE TITLE
Bigtable quickstart hits deadline

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#9187]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/a29fc6bb-5c8b-4dfc-8eca-d734e6c511cd;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/4af8f2dd1058278108c0fb9cdc612b318323fcfa/demo-ubuntu-jammy-demo-install/log-a29fc6bb-5c8b-4dfc-8eca-d734e6c511cd.txt

```
------------------------------------
|   Running quickstart: bigtable   |
------------------------------------
2022-06-07T14:01:01Z (+91s): [ CMake ]
Getting a single row by row key:cf1:greeting    @ 1614343652198000us
"Hello World!"

2022-06-07T14:01:01Z (+91s): [ Make ]
Standard C++ exception raised: Deadline expired before operation could complete.
```

**Comment by coryan** [comment]
Is this a dup of #8280 (which hilariously I almost closed)
