### ISSUE TITLE
Enable StreamingReadTimeout test for storage client with Rest transport

### ISSUE THREAD

**Issue by scotthart** [googleapis/google-cloud-cpp#9201]
This test instructs the emulator to stall sufficiently cause a timeout. However, when using the rest library as transport, the storage client is able to successfully read the bytes and not timeout. Figure out if the request being sent to the emulator is incorrect, or if the issue is in the emulator.

**Comment by coryan** [comment]
I think this was created when writing #9201 and resolved before it was merged. Closing.
