### ISSUE TITLE
Optimization AI quickstart fails because service is unavailable

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#9224]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/7b9d1d85-3020-4a0b-afb2-03c35083c8b8;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/ff78e98ff3c87322081a341d37a83d062ee9c9d0/fedora-35-quickstart-production/log-7b9d1d85-3020-4a0b-afb2-03c35083c8b8.txt

```
49/82 Test #271: optimization_quickstart ............***Failed    0.34 sec
CMake Error at /workspace/cmake/quickstart-runner.cmake:90 (message):
  Non-zero exit status (1) running
  /workspace/cmake-out/google/cloud/optimization/optimization_quickstart

  Request sent to the service...

  Standard exception raised: Error in non-idempotent operation
  BatchOptimizeTours: The service is currently unavailable.
```

**Comment by coryan** [comment]
The operation is not idempotent, so the retry loop does not apply.  Sadly, all the RPCs in this service are non-idempotent.

Maybe we can figure out a way to ignore this error?

**Comment by coryan** [comment]
No repeats in 90d, closing.
