### ISSUE TITLE
Yocto Support

### ISSUE THREAD

**Issue by ankit-lathiya** [googleapis/google-cloud-cpp#9233]
Can't we have Yocto recipe for google cloud support?

**Comment by coryan** [comment]
In general, we do not distribute binary packages, nor do we create packaging recipes for each different Linux distribution.  

We provide [instructions](/googleapis/google-cloud-cpp/blob/main/doc/packaging.md) on how to build the `google-cloud-cpp` libraries on multiple platforms.  Maybe those could be the basis for a recipe?  If you would like to contribute a recipe we can think about where to put it into this repo and how to keep it tested and up to date.

**Comment by ankit-lathiya** [comment]
Then How can this can be used for ARM platform?

**Comment by coryan** [comment]
Are you trying to cross-compile from x86 to ARM?  Our instructions do not cover that case, and we would need to figure that out (I am sure it is possible, we have just not done this).

If you are not trying to cross-compile, I expect it is the same as any other build.
