### ISSUE TITLE
Ability to build modules selectively to avoid building the whole package when only one module is needed

### ISSUE THREAD

**Issue by pepisg** [googleapis/google-cloud-cpp#9290]
**What component of `google-cloud-cpp` is this feature request for?**
`google/cloud/storage`

**Is your feature request related to a problem? Please describe.**
I have to build all the libraries but I only need to use `google/cloud/storage`. This forces me to install a version of `protobuf` that is conflicting with the one needed by another package ([gazebo](https://classic.gazebosim.org/tutorials?tut=guided_a2&cat=))

**Describe the solution you'd like**
It would be nice if modules could be built selectively. Im my case, I only need to use `google/cloud/storage`, so I would only like to built this package and its dependencies

**Describe alternatives you've considered**
Is somehow possible run packages using the cmake file that in their folder?

**Comment by coryan** [comment]
This is possible, but it is not well documented.  You can do this:

```sh
cmake -S . -B .build -DGOOGLE_CLOUD_CPP_ENABLE=storage
cmake --build .build
```

Does that answer your question?

If you are just using `storage` then you do not have a dependency on `gRPC` or `Protobuf`, so you can avoid compiling / installing those too.

**Comment by pepisg** [comment]
That was exactly what I was looking for. Thanks @coryan!
