### ISSUE TITLE
Spanner Postgresql samples duplicate column name

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#9312]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/4de02137-cd60-4843-b80a-5a5604419a4b;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/d12b9c4fb6ca5967875703422d52ff036e531ad5/fedora-35-integration-daily/log-4de02137-cd60-4843-b80a-5a5604419a4b.txt

```
//google/cloud/spanner/samples:postgresql_samples                        FAILED in 65.6s
...
Running spanner_postgresql_add_column sample at 2022-06-19T07:15:36Z
Database projects/cloud-cpp-testing-resources/instances/test-instance-14/databases/db-2022-06-19-40ajg3sx4qu538dh dropped.

Duplicate column name albums.marketingbudget.
```

This might be a problem with the service... Googlers can see b/192520720

**Comment by dbolduc** [comment]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/06eb5e5a-10e0-49c9-951e-c147885a75b9;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/97298d7ffaf51db6fdb7c5e32271d520faaefc1c/fedora-36-integration-daily/log-06eb5e5a-10e0-49c9-951e-c147885a75b9.txt

**Comment by coryan** [comment]
90d without repeats, and it is really a problem in the service. Closing.
