### ISSUE TITLE
`ids` quickstart is flaky

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#9325]
This is the second failure during today, both in PR builds:

```
 9/82 Test #264: ids_quickstart .....................***Failed    0.08 sec
CMake Error at /workspace/cmake/quickstart-runner.cmake:90 (message):
  Non-zero exit status (1) running
  /workspace/cmake-out/google/cloud/ids/ids_quickstart

  Standard exception raised: Permanent error in ListEndpoints: Internal error
  encountered.




      Start 271: memcache_quickstart
```

* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/f4a693db-2f93-48b9-8b25-fe6703a064c1;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/9324/1ba8d0d9ee3aeba366895b82e16de63850f107ef/fedora-35-quickstart-production/log-f4a693db-2f93-48b9-8b25-fe6703a064c1.txt

If it never repeats, then we can remove this.  If it repeats more often, we would want to start tracking it.  Note that `ListEndpoints()` is idempotent, but `Internal error` is not retryable.

**Comment by coryan** [comment]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/fde4e63f-e841-44c9-98cb-ba438c34efb9;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/9330/f6bf5d7937a1506765f4b4e957bf1430ca284590/fedora-35-quickstart-production/log-fde4e63f-e841-44c9-98cb-ba438c34efb9.txt

**Comment by coryan** [comment]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/13624a9e-3cae-4c9a-be9c-790944e78d36;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/9344/ddb4657af0d156d54af1c1935d48ee262498fdf4/fedora-35-quickstart-production/log-13624a9e-3cae-4c9a-be9c-790944e78d36.txt

**Comment by dbolduc** [comment]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/8895e5b2-69b3-4908-a4ac-1f296ede4f54;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/9353/0b2543b7a21f3ca62b4caba23c8450bb06d327aa/fedora-35-quickstart-production/log-8895e5b2-69b3-4908-a4ac-1f296ede4f54.txt

**Comment by dbolduc** [comment]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/f51169b3-8417-4506-b25d-95c321f20bed;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/8b167c857740f8fb972ad85b1dabf617072725c9/fedora-35-quickstart-production/log-f51169b3-8417-4506-b25d-95c321f20bed.txt

**Comment by coryan** [comment]
No repeats in 90d, closing.
