### ISSUE TITLE
BigQuery `AppendRows` API could accept a `write_stream`

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#9381]
We cannot currently send routing metadata for streaming writes. Mainly because we must configure the `grpc::ClientContext` before we know what the first request will be.

In BigQuery, the semantics are to add extra [routing](https://github.com/googleapis/googleapis/blob/79287704c3d7c2f239b52ecfb74b2efaf7e675d2/google/cloud/bigquery/storage/v1/storage.proto#L178-L181) information in the initial request, via the `write_stream` [field](https://github.com/googleapis/googleapis/blob/79287704c3d7c2f239b52ecfb74b2efaf7e675d2/google/cloud/bigquery/storage/v1/storage.proto#L414-L431). (Note that `write_stream` is also listed as a [method signature)](https://github.com/googleapis/googleapis/blob/79287704c3d7c2f239b52ecfb74b2efaf7e675d2/google/cloud/bigquery/storage/v1/storage.proto#L182)

Maybe we should add `std::string const& write_stream` as a parameter to the client call. Then we could set `internal::GrpcSetupOption` to `[write_stream] (auto& context) { context.AddMetadata("x-goog-request-params", write_stream); }` in order to achieve routing. I do not know whether we should try to modify the initial request to set this field.

**Comment by coryan** [comment]
We do not have time for this.
