### ISSUE TITLE
Consider calling `ConfigureContext()` everywhere

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#9454]
Motivation: #4926 

We currently call `ConfigureContext(context, internal::CurrentOptions)` in `RetryLoop`, `AsyncRetryLoop`, and the handwritten bigtable connection. If #9543 goes through, then we call it in storage too.

We do not call it for streaming reads. We can teach the generator to call `ConfigureContext` any time we make a `grpc::ClientContext`. Which would be here: https://github.com/googleapis/google-cloud-cpp/blob/ac964c9f9f97c711e8aa1d583f1c6cd87b66c6d4/google/cloud/bigquery/internal/bigquery_read_connection_impl.cc#L68-L69

I do not know what, if anything, needs to change in handwritten code other than bigtable and storage.

**Comment by coryan** [comment]
Closing, not enough time to work on this.
