### ISSUE TITLE
coverage-ci failure in signed_url_conformance_test

### ISSUE THREAD

**Issue by scotthart** [googleapis/google-cloud-cpp#9631]
//google/cloud/storage/tests:signed_url_conformance_test                 FAILED in 29.2s
  /h/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/com_github_googleapis_google_cloud_cpp/bazel-out/k8-fastbuild/testlogs/google/cloud/storage/tests/signed_url_conformance_test/test.log

https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/155a7852c5e0d909ec5582d2ac5c184f92d2850b/fedora-36-coverage/log-6f3ea0fc-f2e0-4cc7-b482-48622f4b7313.txt

**Comment by coryan** [comment]
This is a dup of #6952  You can tell because the log includes:

```
Step #3: #
Step #3: # A fatal error has been detected by the Java Runtime Environment:
Step #3: #
Step #3: #  SIGBUS (0x7) at pc=0x00007f394f1e4e0a, pid=12, tid=2576
```
