### ISSUE TITLE
Retire `CurlClient` transport implementation for GCS

### ISSUE THREAD

**Issue by scotthart** [googleapis/google-cloud-cpp#9659]
Add option to GCS to choose between new internal rest library or legacy implementation for http transport, defaulting to new rest library. Legacy implementation option will remain available for 3 months after switchover as an escape hatch.

**Comment by scotthart** [comment]
[GCS Transport Benchmark_ Legacy vs RestLib.pdf](https://github.com/googleapis/google-cloud-cpp/files/9303733/GCS.Transport.Benchmark_.Legacy.vs.RestLib.pdf)

**Comment by coryan** [comment]
We still need to see more usage to switch.

**Comment by coryan** [comment]
We are still waiting for usage to go down.

**Comment by coryan** [comment]
We are expecting to close this around 2023-10-01.
