### ISSUE TITLE
Unit test segfaults after test passes on windows

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#9664]
https://source.cloud.google.com/results/invocations/b5ebd3b1-d6a0-4ac4-8787-f6e170dec463

```
276/410 Test #335: spanner_internal_spanner_stub_test ...............................................***Exception: SegFault  0.35 sec

Running main() from gmock_main.cc
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from SpannerStub
[ RUN      ] SpannerStub.CreateDefaultStub
[       OK ] SpannerStub.CreateDefaultStub (6 ms)
[ RUN      ] SpannerStub.CreateDefaultStubWithLogging
[       OK ] SpannerStub.CreateDefaultStubWithLogging (8 ms)
[----------] 2 tests from SpannerStub (14 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test suite ran. (14 ms total)
[  PASSED  ] 2 tests.
```

This failure mode looks a lot like #3933

**Comment by dbolduc** [comment]
https://source.cloud.google.com/results/invocations/53fe3964-841e-4b84-ad01-0788c0a1bda1

same test but this time with bazel.

**Comment by coryan** [comment]
90d without repeat.  Closing.  Possibly related to #9990, thread leaks can result in UB under Windows.  Note that gRPC has implemented some mitigations for the thread leaks, but has not fixed the problems.

**Comment by dbolduc** [comment]
https://source.cloud.google.com/results/invocations/e49c051f-09c6-4186-9f72-79536e7bd805

**Comment by coryan** [comment]
https://source.cloud.google.com/results/invocations/4c9bda63-5467-4264-be79-92c578d3789d

**Comment by dbolduc** [comment]
https://source.cloud.google.com/results/invocations/6ab66bb7-20c7-4105-9284-6453a95a45a2

**Comment by coryan** [comment]
https://source.cloud.google.com/results/invocations/449faeb8-015f-476d-b69b-e783e844884d
