### ISSUE TITLE
Expose `internal::GrpcSetupOption` as an experimental option

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#9691]
I have told two different Googlers to use this internal option. I feel bad about doing it. I would feel better recommending `google::cloud::experimental::GrpcSetupOption` (even though experimental symbols have the same guarantees as internal ones).

**Comment by coryan** [comment]
Please take a look and make a decision.

**Comment by coryan** [comment]
Evidently we do not have time to work on this. Closing for now.
