### ISSUE TITLE
Storage integration test segfault

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#9702]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/ed89510c-0a1f-46a5-ab14-0029de38d3c1;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/bc12403ee6c20614e3adb402dd63cb11de4be8f9/fedora-36-noex/log-ed89510c-0a1f-46a5-ab14-0029de38d3c1.txt

```
45/58 Test #483: storage_object_integration_test .................................***Exception: SegFault  9.94 sec
Running main() from gmock_main.cc
[==========] Running 33 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 33 tests from ObjectIntegrationTest
[ RUN      ] ObjectIntegrationTest.FullPatch
[       OK ] ObjectIntegrationTest.FullPatch (617 ms)
...
...
[       OK ] ObjectIntegrationTest.GetObjectMetadataFailure (229 ms)
[ RUN      ] ObjectIntegrationTest.StreamingWriteFailure
```

**Comment by coryan** [comment]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/941ecdf8-a083-4406-81c3-570da5c6e705;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/e8c5586e41ba29472c865b4ac86fec714d1781e2/fedora-36-noex/log-941ecdf8-a083-4406-81c3-570da5c6e705.txt

**Comment by coryan** [comment]
Cannot reproduce locally.  I ran 1,000 times with ASAN and -fno-exceptions, and a few times with CMake and no exceptions.  No luck.

**Comment by coryan** [comment]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/b629da0a-a259-4d86-8703-0e4f44771f53;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/cb589628f493067c4a728a839ced623b369fa508/fedora-36-noex/log-b629da0a-a259-4d86-8703-0e4f44771f53.txt

**Comment by coryan** [comment]
No luck with 1,000 runs of MSAN + no-exceptions:

```
env -u GOOGLE_CLOUD_CPP_STORAGE_TEST_BUCKET_NAME /h/.local/bin/gunicorn --bind "0.0.0.0:7075" --worker-class sync --threads 10 --reload --access-logfile - "testbench:run()" >emulator.log 2>&1 </dev/null &

printf '{"name": "%s"}' "${GOOGLE_CLOUD_CPP_STORAGE_TEST_BUCKET_NAME}" |     curl -i -X POST --data-binary @-       -H "Content-Type: application/json"       "${CLOUD_STORAGE_EMULATOR_ENDPOINT}/storage/v1/b?project=${GOOGLE_CLOUD_PROJECT}"
CXX=clang++ CC=clang bazel test --test_env=GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT} --test_env=CLOUD_STORAGE_EMULATOR_ENDPOINT=${CLOUD_STORAGE_EMULATOR_ENDPOINT} --test_env=GOOGLE_CLOUD_CPP_STORAGE_TEST_BUCKET_NAME=${GOOGLE_CLOUD_CPP_STORAGE_TEST_BUCKET_NAME} --test_env=HOME=$HOME --test_output=errors --runs_per_test=1000 --jobs=32 --config=msan --cxxopt=-fno-exceptions //google/cloud/storage/tests:object_integration_test

```

**Comment by dbolduc** [comment]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/a76522fb-5c54-4459-8ddb-b97cc837788d;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/9718/7af728d396424d32bb0e0eb1ebefd3b019b0d6ab/fedora-36-noex/log-a76522fb-5c54-4459-8ddb-b97cc837788d.txt

**Comment by devbww** [comment]
Q:  How is it that `ObjectIntegrationTest.StreamingWriteFailure`, which expects exceptions, is even supposed to function in a "noex" build?

**Comment by coryan** [comment]
> Q: How is it that `ObjectIntegrationTest.StreamingWriteFailure`, which expects exceptions, is even supposed to function in a "noex" build?

`testing_util::ExceptException<>()`  expects an exception or a crash.  I am happy disabling the test for the `noex` build.  I am not sure if  enabling exceptions in iostreams and compiling with `-fno-exceptions` is UB, but it is easy to justify that it should be.

Let me try that
