### ISSUE TITLE
Error in validatecommittedsize

### ISSUE THREAD

**Issue by garlicnation** [googleapis/google-cloud-cpp#9750]
During a transfer using the cpp library, we observed this error.

ValidateCommittedSize: the server indicates that 41943040000 bytes are committed  but given the current request no more than 41810919424 should be. This could be caused by multiple applications trying to use the same resumable upload, but could be a bug in the library or the service. If you believe this is a bug, please contact support or report the bug at [https://github.com/googleapis/google-cloud-cpp/issues/new](https://www.google.com/url?sa=D&q=https%3A%2F%2Fgithub.com%2Fgoogleapis%2Fgoogle-cloud-cpp%2Fissues%2Fnew) Include as much information as you can including this message, session_id

I have the session id and other information to share out of band(don't want to post on github)

**Comment by coryan** [comment]
@garlicnation as we discussed elsewhere, there is one scenario that could explain this problem:

1. The application is uploading object X, and has uploaded 10 * 256 KiB.
2. Assume the service has received all the data, i.e., 10 * 256KiB but has not *committed* the full amount.
3. The application has checkpointed the upload id.
4. The application restarts before finalizing the upload, it reads the upload id, and asks the C++ client library to resume the upload.
5. The client library queries the service and the service returns that 4 * 256 KiB have been uploaded.
6. The application sends 2 * 256 KiB.
7. The service responds that now 10 * 256 KiB are committed.

All of these steps are possible, but (with the current API) the client library returns at error, and the application will need to manually resume the upload (once again, though eventually it should converge).

I cannot assert that this is the problem you noticed, but it is plausible.  I am going to think about improvements to the error (maybe reference this note). Beyond that, I do not think there is enough information to take action at this point.
