### ISSUE TITLE
Bigtable UNAVAILABLE error during consistency check

### ISSUE THREAD

**Issue by coryan** [googleapis/google-cloud-cpp#9870]
This fails because `CheckConsistency` is not considered idempotent, that seems odd as this is a read-only operation.  It also seems odd that somewhere we are "modifying" the instance while trying to run this test.

```
2022-09-18T07:14:55.796105608Z [DEBUG] <140710506651200> CheckConsistency() << google.bigtable.admin.v2.CheckConsistencyRequest {
  name: "projects/cloud-cpp-testing-resources/instances/test-instance/tables/tbl-2022-09-18-bt4put3l9dh3do8fa8nqx06icjr9yszake"
  consistency_token: "01mpkjAumIOvd_amlWMhkLalQAAABmCPNVm2x-wmF0KmtMzQ27OO7cWxO1K_alX9Cc47YrMO0GFex_JDGKdDXWPU0a1jv6ApeG0yt6E9b43Yfp1q25q5DbgkT_0YHiKn7DcnzA8ZKnC9usLZrSNdIIqy-UOs8"
} (./google/cloud/internal/log_wrapper.h:91)
2022-09-18T07:14:56.142049178Z [DEBUG] <140710506651200> CheckConsistency() >> status=UNAVAILABLE: Consistency checks not available while instance is being modified (./google/cloud/internal/log_wrapper.h:94)
Error in non-idempotent operation CheckConsistency: Consistency checks not available while instance is being modified
```

* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/e67884de-73db-4105-be33-b898ad46022c;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/8c339f1cf4ee0fb004bbef039cea24bab6b29e6f/fedora-36-integration-daily/log-e67884de-73db-4105-be33-b898ad46022c.txt

**Comment by dbolduc** [comment]
* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/bbdf8247-1710-48f2-9b3a-c2bcc9c919f9;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/f3d08b736565af0d5bef916c8134b52c77a579a4/fedora-36-integration-daily/log-bbdf8247-1710-48f2-9b3a-c2bcc9c919f9.txt

**Comment by coryan** [comment]
Closing in favor of #10413
