### ISSUE TITLE
Bazel cannot download deps

### ISSUE THREAD

**Issue by dbolduc** [googleapis/google-cloud-cpp#9975]
https://source.cloud.google.com/results/invocations/31e32615-f117-4292-be1c-94588723eeb2

```
WARNING: Download from [https://github.com/bazelbuild/rules_cc/releases/download/0.0.1/rules_cc-0.0.1.tar.gz](https://www.google.com/url?q=https://github.com/bazelbuild/rules_cc/releases/download/0.0.1/rules_cc-0.0.1.tar.gz&sa=D) failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Unknown host: github.com

ERROR: An error occurred during the fetch of repository 'rules_cc':
   Traceback (most recent call last):
	File "C:/b/rvommcsc/external/bazel_tools/tools/build_defs/repo/http.bzl", line 125, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
```

I think the important bit is the "Unknown host: *github.com"

**Comment by dbolduc** [comment]
https://source.cloud.google.com/results/invocations/96c23c5a-6a20-4a00-bd4c-b6a2f726f8b3

**Comment by dbolduc** [comment]
```
ERROR: An error occurred during the fetch of repository 'com_github_curl_curl':
```
https://source.cloud.google.com/results/invocations/5381f281-c4db-4875-b717-d1057d2ed6f8

**Comment by coryan** [comment]
Blegh, DNS resolution not working on the build servers.  Note that we already try to download these things 3 times, it is unclear that more downloads would help.

**Comment by scotthart** [comment]
https://source.cloud.google.com/results/invocations/a080cb72-ce8e-419b-a43a-7ac85e84ecf0

**Comment by scotthart** [comment]
https://source.cloud.google.com/results/invocations/18a3cfba-f128-4fe1-aabf-201f3cc9b297

**Comment by coryan** [comment]
https://source.cloud.google.com/results/invocations/20fadbc9-f9fd-4c67-a450-ab0e901a98cc

**Comment by devbww** [comment]
https://source.cloud.google.com/results/invocations/e07f21d7-e8dd-4e33-92d3-2cdf542f5f3c

**Comment by dbolduc** [comment]
https://source.cloud.google.com/results/invocations/e2ceefa6-1026-4cb3-a0b9-90e035d26b17

**Comment by coryan** [comment]
https://source.cloud.google.com/results/invocations/a2a10986-a838-41c1-b8f8-48194aa1db87

**Comment by coryan** [comment]
Not only Windows:

* GCB: https://console.cloud.google.com/cloud-build/builds;region=us-east1/7cc139f5-4b8d-40be-8ba9-57293120bcfa;tab=detail?project=cloud-cpp-testing-resources
* Raw: https://storage.googleapis.com/cloud-cpp-community-publiclogs/logs/google-cloud-cpp/main/edc7583ec249d08dd6cb129bd3206dedc36ad820/ubuntu-focal-quickstart-bazel/log-7cc139f5-4b8d-40be-8ba9-57293120bcfa.txt

**Comment by coryan** [comment]
This is Kokoro-specific and we no longer use Kokoro.
